### ISSUE TITLE
真机运行崩

### ISSUE THREAD

**Issue by qq756585379** [banchichen/TZImagePickerController#1]

**Comment by banchichen** [comment]
请提供一下崩溃手机的型号和系统版本号等更详细的信息，最好请连上Xcode调试一下输入崩溃日志，然后把日志放过来，谢谢，目前其他手机都没发现崩溃。

**Comment by banchichen** [comment]
刚刚另一位朋友也提了这个bug，应该是同一个，已修复，谢谢~
