### ISSUE TITLE
present进去之后 是相册的列表 并不是照片列表 

### ISSUE THREAD

**Issue by ClegeJJ** [banchichen/TZImagePickerController#10]
present进去之后 是相册的列表 并不是照片列表  然后点击选择一个相册之后，没有这个相册里面的照片..一片空白.怎么解决？？

**Comment by ClegeJJ** [comment]
没问题了 谢谢- - 是我自己疏忽..  作者给控制器添加的模型名用的model..model在我的项目中有冲突..

**Comment by banchichen** [comment]
好的吧~解决了就好~
