### ISSUE TITLE
发生很多NSInvalidArgumentException错误

### ISSUE THREAD

**Issue by ymuzi** [banchichen/TZImagePickerController#1004]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？——是【**如果Demo没问题，请升级新版**】
2、你用的是什么版本？升级后是否正常？——3.0.9，已经是用的最新版
3、是否有改动过我库内部的代码？——否【**如有，请告诉我你改了什么**】

**bug内容描述**
请在这里描述bug的内容：

![1540356772506](https://user-images.githubusercontent.com/7507105/47407154-62560d00-d78c-11e8-89c2-024a57f43ad5.jpg)
![1540345670350](https://user-images.githubusercontent.com/7507105/47407180-8d406100-d78c-11e8-97c4-4efa319595ab.jpg)

**如何复现这个bug？**
以下是示例，请替换你的bug复现步骤：
1、Demo默认设置，去选择照片
2、选择照片，点击预览
3、App崩溃，

**截图**
如有，请在这贴上你的截图：

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
这个问题，我怎么复现？

**Comment by ymuzi** [comment]
目前没找到确切复现的路径

**Comment by banchichen** [comment]
嗯嗯，期待找到复现路径后的更新🤝

**Comment by ymuzi** [comment]
@banchichen 不是控件的问题，我们小伙伴打包时把带僵尸对象的包发出去了，造成用户内存耗尽了，加上图片选择是频次比较高的地方，去掉了僵尸对象，又连续测了6个小时，没有问题了

**Comment by banchichen** [comment]
嗯嗯，OK👌
