### ISSUE TITLE
WARNING: [ImageManager] First stage of an opportunistic image request returned a non-table format image, this is not fatal, but it is unexpected

### ISSUE THREAD

**Issue by xxzizixx** [banchichen/TZImagePickerController#1005]
当我选择图片并调用原图的时候，就会打印：[ImageManager] First stage of an opportunistic image request returned a non-table format image, this is not fatal, but it is unexpected
看了其他的issue，并没有提到这个，也搜不到其他信息。所以想问一下这个是apple的bug还是其他的问题？

**Comment by banchichen** [comment]
不懂苹果又搞了什么，获取图片的API使用是OK的。

只找到一个链接：https://stackoverflow.com/questions/49865609/getting-a-non-fatal-but-unexpected-error-while-converting-a-phasset-to-a-uiimage
但好像没啥用...

**Comment by xxzizixx** [comment]
@banchichen  嗯嗯，链接这个我看过，也试过，感觉没啥用～
