### ISSUE TITLE
关于最新版本的问题

### ISSUE THREAD

**Issue by zhangjieJay** [banchichen/TZImagePickerController#1007]
看git上面有3.0.9的版本,但是pod search一下只有3.0.2版本,3.0.2没有适配X,请问楼主pod哪儿能获取最新的

**Comment by banchichen** [comment]
readme有：

Q：pod search TZImagePickerController 搜索出来的不是最新版本
A：需要在终端执行cd转换文件路径命令退回到Desktop，然后执行pod setup命令更新本地spec缓存（可能需要几分钟）,然后再搜索就可以了

**Comment by zhangjieJay** [comment]
谢谢,正如你所描述的那样
