### ISSUE TITLE
发送原图时支持heif，heic格式转png，jpg吗

### ISSUE THREAD

**Issue by zhuzhiyongai** [banchichen/TZImagePickerController#1008]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
原图的获取是在库外面做的哈

**Comment by zhuzhiyongai** [comment]
已实现，谢谢回复

**Comment by banchichen** [comment]
👍
给TZImageManager提个PR不？
