### ISSUE TITLE
3.0.4选择图片后再裁剪，有白色框框，3.0.7版本后，白色框框没了。图层上也没看到

### ISSUE THREAD

**Issue by YanYuYunYuan** [banchichen/TZImagePickerController#1009]
代码逻辑：
//选择图片后的Block回调
[pickerVC setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
        TZImagePickerController *cropVC = [[TZImagePickerController alloc] initCropTypeWithAsset:assets[0] photo:photos[0] completion:^(UIImage *cropImage, PHAsset *asset) {
           //裁剪完成处理
        }];
//传入cropRect ，3.0.4版本有白色框框的，升级后没了
        cropVC.cropRect = [self cropImageRectWithOriginalImage:photos[0]];
        [self presentViewController:cropVC animated:YES completion:nil];
        
    }];
    [self presentViewController:pickerVC animated:YES completion:nil];

这是大大去掉了框框吗

**Comment by banchichen** [comment]
设置下allowPickingImage为YES哈。

我内部多加了判断...

**Comment by banchichen** [comment]
或者升级到3.1.0版本哈
