### ISSUE TITLE
如何把拍照的功能放到外面？

### ISSUE THREAD

**Issue by shiyonghui** [banchichen/TZImagePickerController#101]

**Comment by shiyonghui** [comment]
我把拍照的功能放到外面 但是把拍照的照片展示出来，然后在从相册选图片选不了图片

**Comment by banchichen** [comment]
2016.6.22更新:
刚刚更新了代码，现在版本更新到了1.5.0。更新如下：
1.可把拍照按钮放在外面了,可以设置弹出一个sheet提示用户选择相册或相机；
2.新增了sortAscendingByModificationDate属性，默认为YES，设置为NO时，照片会按修改时间降序，拍照按钮会在第一个；
3.优化了Demo页面的UI，新增6个开关控件，可方便地更改各个设置来打开选择器；
4.修复了若干bug；

你好，我刚刚更新了代码，更新到1.5.0就可以了~

**Comment by shiyonghui** [comment]
thank you ！！
