### ISSUE TITLE
判断是否可选视频

### ISSUE THREAD

**Issue by sunzhongliangde** [banchichen/TZImagePickerController#1011]
你好，我在isAssetCanSelect 代理方法里面需要判断视频时长或者视频大小，大于一定长度就不允许上传视频，但我搜了好多用来获取视频信息的方法，都只能在异步block里面做处理（异步block返回值不好处理）
并且这个代理方法一旦相册视频太多，容易有性能问题（代理是把相册所有的资源文件找一遍）
能否有点击相册的时候的代理，当用户选择视频或者相册的时候去做判断，alert或者toast提醒用户，

感谢作者辛苦付出

**Comment by banchichen** [comment]
视频时长可以哦，Demo有示例哈

![image](https://user-images.githubusercontent.com/12755494/47990133-bd3f1b00-e121-11e8-86b5-a983c7141288.png)
