### ISSUE TITLE
实际使用中当相册图片达到10000多张，并且在选择图片的界面快速滑动的时候，会出现闪退问题

### ISSUE THREAD

**Issue by WildStrom** [banchichen/TZImagePickerController#1018]
使用allocation查看内存，发现是创建了很多图片，最终内存占用可能达到800甚至1000M以上。禁用cellModel中image的缓存可以减低内存占用，不再会出现闪退，但是可能影响流畅性，各位大神看下这里有啥好方法？

**Comment by banchichen** [comment]
这个缓存image的方案确实不靠谱...
问题现在已修复哈，新版本：3.1.5
