### ISSUE TITLE
Swift 不能使用TZLocationManager.manager()

### ISSUE THREAD

**Issue by liuzhida33** [banchichen/TZImagePickerController#1019]
**版本号：3.1.3**
在swift项目中不能直接使用`TZLocationManager.manager()`，即便我直接使用了`TZLocationManager()`也无法进入该`manager`的断点调试，希望能和`TZImageManager`为该`manager`方法一样添加`NS_SWIFT_NAME(default())`，截图如下，感激不尽

**截图**

<img width="833" alt="image" src="https://user-images.githubusercontent.com/15240589/48458137-fc472d80-e7ff-11e8-8435-5d1c56b2cbad.png">

**Comment by banchichen** [comment]
OK，已发新版：3.1.2
