### ISSUE TITLE
图片过多,快速滚动,卡死将近10s

### ISSUE THREAD

**Issue by haohao110** [banchichen/TZImagePickerController#102]
cpu暴增到200%,然后卡死,我这将6000多张图

**Comment by banchichen** [comment]
你好，在连线调试的情况下，卡死的情况我遇到过若干次的，但是在不调试的时候，倒没遇到过，我估计你是在调试的时候遇到这样的情况，麻烦再在非调试环境下测试下，非调试时我没遇到过这种情况。我的设备目前照片数是1000多一点。

在调试的情况下，Apple提供的Demo也偶尔会有卡死的情况，原因暂时无解...
