### ISSUE TITLE
集成到VC里的图片选择方法有几率会走两次

### ISSUE THREAD

**Issue by maybenai** [banchichen/TZImagePickerController#1021]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
@maybenai  填一下上面的模板

**Comment by maybenai** [comment]
1.我没有看demo，接手的项目
2.最新的版本
3.没有改过内部代码

这个bug概率性的。。我自己一直复现不了，但是测试妹子的手机一拿去就出来了

******************我是如下取图片的********************
<img width="1258" alt="wechatimg141" src="https://user-images.githubusercontent.com/12791647/49202392-6efb0000-f3df-11e8-9f09-3297dfcba2e6.png">

**Comment by banchichen** [comment]
看一下方法注释你就知道了
