### ISSUE TITLE
TZImageManager可否为getOriginalPhotoDataWithAsset:completion:方法添加一个PHImageRequestID的返回值？

### ISSUE THREAD

**Issue by hulala1210** [banchichen/TZImagePickerController#1022]
在我的项目中，不光使用了TZImagePickerController组件，还单独使用了TZImageManager来新建对象，做一些优化。其中使用到了getOriginalPhotoDataWithAsset:completion:这个API，在优化过程中，我希望有一个方法可以去取消正在进行的PHAsset的请求，但是当前的API未能满足。希望作者能添加一个取消请求的API，或者在getOriginalPhotoDataWithAsset:completion:返回PHImageRequestID出来，我们自己进行Cancel。

**Comment by banchichen** [comment]
已加返回值PHImageRequestID，新版本：3.1.3

**Comment by raodaye** [comment]
> 在我的项目中，不光使用了TZImagePickerController组件，还单独使用了TZImageManager来新建对象，做一些优化。其中使用到了getOriginalPhotoDataWithAsset:completion:这个API，在优化过程中，我希望有一个方法可以去取消正在进行的PHAsset的请求，但是当前的API未能满足。希望作者能添加一个取消请求的API，或者在getOriginalPhotoDataWithAsset:completion:返回PHImageRequestID出来，我们自己进行Cancel。



> 已加返回值PHImageRequestID，新版本：3.1.3

这个API取出的data能压缩吗？   感觉这个data直接上传的话图片有点大

**Comment by banchichen** [comment]
@raodaye 这个是取原图的API
