### ISSUE TITLE
预览功能超宽图片的展示问题

### ISSUE THREAD

**Issue by QiuFairy** [banchichen/TZImagePickerController#1023]
使用预览功能时，如果是超宽图片，那么最大放大比不够填满Y轴，代码显示 `_scrollView.maximumZoomScale = allowCrop ? 4.0 : 2.5;`  

**解决办法：**
代码中已有对超宽图片的优化，代码在：`TZPhotoPreviewCell -- setAllowCrop` ，只是部分代码没有放对地方，解决方式：`TZPhotoPreviewController -- cellForItemAtIndexPath `中将`cell.model = model;提到photoPreviewCell.allowCrop = _tzImagePickerVc.allowCrop;之前即可`

**Comment by QiuFairy** [comment]
问题中已包含解办法！

**Comment by banchichen** [comment]
👍
已修复
新版本：3.1.3
