### ISSUE TITLE
多选时点击选择图片支持回调

### ISSUE THREAD

**Issue by aiquantong** [banchichen/TZImagePickerController#1024]
**问：你希望加什么新功能？**
答：用户点击选择图片和视频，判断是否可以选择。

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：支持，如：微信不支持低于1s视频分享，用户选择低于1s视频，微信会提示“不能分享短于1s的视频”

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合所有人，通过代理或者block实现。

**其它你希望补充的内容**

**Comment by yy981998440** [comment]
同楼上

**Comment by shaolelng** [comment]
我在源码cell.didSelectPhotoBlock中调用了  [self doneButtonClick]的方法，现在可以做到单次点击图片,回调了。同时将tzImagePickController的autoDismiss设为NO

**Comment by banchichen** [comment]
最新版已支持哈，3.5.8

可以参考Demo的isAssetCanBeSelected，不能选中的可以return NO并自主弹提示
