### ISSUE TITLE
视频预览没有声音

### ISSUE THREAD

**Issue by jacylouis** [banchichen/TZImagePickerController#1027]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答： 有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.1.3版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：未更改代码

**bug内容描述**

编译环境: Xcode 10.1  Xcode9.4.1
运行环境: iPhoneSE  iOS11.3.1

视频预览没有声音,不知道是你本来就没有做声音的处理,还是需要什么字段去设置,或者是我的设备的问题,我想问一下,我应该怎么解决视频声音的问题?

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
不可能呀，你确定我的demo也会这样？
多个设备都这样还是只有某一个？

**Comment by jacylouis** [comment]
非常感谢您的及时回复,刚刚百度了一下找到原因了, 主要是我手机开了静音导致的, 因为有些app 比如微信, 在手机开静音模式下 选择视频和预览也是有声音的, 我想当然的以为是这个demo有问题,没有考虑到手机开着静音模式. 
加上下面这句代码 就能在静音模式下 播放视频也有声音了:
//不随着静音键和屏幕关闭而静音。code by Aevit
[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];

这也算不上bug ,只是需求不同罢了.不知道你后期是否考虑加入此代码

**Comment by banchichen** [comment]
赞👍

这个设置我不打算加哈，你们需要的话就在你们APP里设置吧，看起来是全局的
