### ISSUE TITLE
图片剪切问题

### ISSUE THREAD

**Issue by songyuanhang** [banchichen/TZImagePickerController#1029]
单张图片剪切的时候，在设置的剪切框高度或者宽度 大于目标相册图片的高度或者宽度，剪切完成的图片，有白边。最新demo同样有这个问题。参考别人提的issue方案，同样出现剪切完成达到的图片有白边。

**Comment by banchichen** [comment]
不要提交重复的issue哈，在这里讨论即可：https://github.com/banchichen/TZImagePickerController/issues/804

**Comment by songyuanhang** [comment]
好哦，大佬，那个问题用你这个框架能解决吗？




| |
宋功德
邮箱：syhandyx@163.com
|

签名由 网易邮箱大师 定制

在2018年11月27日 14:08，谭真 写道：

不要提交重复的issue哈，在这里讨论即可：#804
