### ISSUE TITLE
类似微信朋友圈的选择图片 可调节选择顺序

### ISSUE THREAD

**Issue by lhh-sofy** [banchichen/TZImagePickerController#1030]
**问：你希望加什么新功能？**
答：选中使用数字表示，可以清晰选择显示的顺序

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有的，参考的就是微信朋友圈的功能

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：应该是适应所有人的，我选择图片的顺序就是我需要显示的顺序，加数字的话，会更清新一些

**其它你希望补充的内容**

**Comment by banchichen** [comment]
最新的demo，默认效果就是有序号的哦....
