### ISSUE TITLE
取消按钮用UIBarButtonItemStylePlain创建的话在iOS11以上会偏移

### ISSUE THREAD

**Issue by ArthurCL** [banchichen/TZImagePickerController#1032]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：新版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**

返回按钮用UIBarButtonItemStylePlain创建的话    在iOS 11系统上按钮会偏移

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/49143501-20ddf200-f336-11e8-8334-1e2f8e9a3237.png)

**Comment by banchichen** [comment]
在Demo里直接改代码自定义呢？
应该是UINavigation-SXFixSpace的影响啊。

**Comment by ArthurCL** [comment]
我用pod导入的代码       直接改的话      下次不小心更新一下pod的话   代码会还原     拖进来的部分代码有报错

**Comment by banchichen** [comment]
你现在是要先确定是哪里的问题呀，如果在demo里直接改代码改成UIBarButtonItemStylePlain类型的，是没错的呀。

所以问题在UINavigation-SXFixSpace，得去找这个库的作者...

**Comment by ArthurCL** [comment]
[imagePickerVc setNavLeftBarButtonSettingBlock:^(UIButton *leftButton){
        [leftButton setImage:[UIImage imageNamed:@"back"] forState:UIControlStateNormal];
        [leftButton setImageEdgeInsets:UIEdgeInsetsMake(0, -10, 0, 20)];
    }];


取消按钮有没有这个方法呢？

**Comment by banchichen** [comment]
没有...

**Comment by banchichen** [comment]
@ArthurCL 目前就是UIBarButtonItemStylePlain类型啊，你想设置什么？

**Comment by ArthurCL** [comment]
导航栏按钮在iOS11的系统以上 是有偏移的    所以我才用那个库解决偏移问题     但这个解决偏移的库 并不适用UIBarButtonItemStylePlain 而是用UIBarButtonItem的customView来放Button的

**Comment by banchichen** [comment]
有对比的效果图吗？
没发现啥偏移啊。。。

你要么hook下TZAlbumPickerController和TZPhotoPickerController的viewDidLoad，自己设置下navigationItem.rightBarButtonItem

**Comment by ArthurCL** [comment]
<img width="944" alt="wechat0618f522f043068e371b266022463d30" src="https://user-images.githubusercontent.com/26400117/49161636-336f2000-f364-11e8-9a87-7f6d774f6a7e.png">

**Comment by ArthurCL** [comment]
用继承在子控制器中设置右边按钮完全没效果     能不能把取消的按钮弄成自定义的  取消的方法单独抽出来

**Comment by banchichen** [comment]
继承当然没效果了，我内部又不是push你新建的子类...

你对照demo啊，demo在iOS11上取消按钮也没那样啊，你项目环境的问题吧。。。

**Comment by dgynfi** [comment]
谢谢，我已经移除这个库了

**Comment by dgynfi** [comment]
确实是个这个库影响了取消按钮的偏移

**Comment by Liyongcong** [comment]
> 确实是个这个库影响了取消按钮的偏移

请问怎么解决的
