### ISSUE TITLE
自定义预览页面的样式。请尽快回复

### ISSUE THREAD

**Issue by tianxiawoyougood** [banchichen/TZImagePickerController#1035]
大佬，我想自定义预览页面的样式。要隐藏掉naviBar的选中按钮，数量label。toolbar的原图按钮、完成按钮、选中数量的label。怎么办？请尽快回复哈

**Comment by banchichen** [comment]
你找头文件不是更快吗

photoPreviewPageUIConfigBlock

**Comment by tianxiawoyougood** [comment]
photoPreviewPageUIConfigBlock试过了。不能隐藏掉。
` imagePickerVc.photoPreviewPageUIConfigBlock = ^(UICollectionView *collectionView, UIView *naviBar, UIButton *backButton, UIButton *selectButton, UILabel *indexLabel, UIView *toolBar, UIButton *originalPhotoButton, UILabel *originalPhotoLabel, UIButton *doneButton, UIImageView *numberImageView, UILabel *numberLabel) {
                doneButton.hidden = YES;
                originalPhotoButton.hidden = YES;
                originalPhotoLabel.hidden = YES;
                
                numberImageView.hidden = YES;
                numberLabel.hidden = YES;
                
            };`

**Comment by tianxiawoyougood** [comment]
![image](https://user-images.githubusercontent.com/9163388/49793762-e0886600-fd70-11e8-8152-8cfcb288f7d6.png)

**Comment by tianxiawoyougood** [comment]
滑动还是可以显示。因为源码中refreshNaviBarAndBottomBarState方法，又设置hidden为NO了
