### ISSUE TITLE
可否增加图片旋转以及调色的功能

### ISSUE THREAD

**Issue by lhh-sofy** [banchichen/TZImagePickerController#1039]
**问：你希望加什么新功能？**
答：图片旋转的功能

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：类似ios中相册中图片进行编辑的场景

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
没有精力哈，建议找专业的图片编辑库，和tz一起使用
