### ISSUE TITLE
压缩视频出错 AVAssetExportSessionStatusFailed

### ISSUE THREAD

**Issue by AngryOC** [banchichen/TZImagePickerController#1040]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新的demo

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
项目中从相册压缩某个视频(大小:13M)到沙盒( 大部分能压缩成功), 提示 AVAssetExportSessionStatusFailed, 运行demo, 存在同样的问题.

目前我项目中不再压缩视频, 直接从相册写到沙盒,就可以了, 出现压缩失败, 不知道什么原因, 希望看看.

**我如何复现这个bug？**
1. 下载相关视频 链接: https://pan.baidu.com/s/1ERrxaZCefvTciF8xaRYn7Q 提取码: sh35 , 保存到手机相册;
2.运行最新demo, allowPickingMultipleVideo是NO,选择下载的视频, 确定选择, 会执行下面的方法, 报错;

// 如果用户选择了一个视频且allowPickingMultipleVideo是NO，下面的代理方法会被执行
- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingVideo:(UIImage *)coverImage sourceAssets:(PHAsset *)asset

**截图**
![image](https://user-images.githubusercontent.com/16474869/50413249-d8d4c100-0848-11e9-9470-c6c207e82044.png)

**Comment by CCBrother** [comment]
我也遇到同样问题

**Comment by mlp1995** [comment]
老哥这个问题解决了吗

**Comment by misanyrock** [comment]
老哥这个问题解决了吗 +1

**Comment by banchichen** [comment]
Duplicate of #1073 
升级到3.5.3试试哈，原因我写在1073里了
