### ISSUE TITLE
imagePickerVC.allowPickingGif = YES;设置属性没有用

### ISSUE THREAD

**Issue by ZhuHongSheng** [banchichen/TZImagePickerController#1041]
正确
if (type == TZAssetCellTypePhoto || type == TZAssetCellTypeLivePhoto || (type == TZAssetCellTypePhotoGif && self.allowPickingGif) || self.allowPickingMultipleVideo) {
错误
if (type == TZAssetCellTypePhoto || type == TZAssetCellTypeLivePhoto || (type == TZAssetCellTypePhotoGif && !self.allowPickingGif) || self.allowPickingMultipleVideo) {

**Comment by ZhuHongSheng** [comment]
> @ZhuHongSheng 上面的逻辑没错的，你那目前的表现和你期望的表现分别是？
 首先谢谢的你的回复！我项目是从TZImagePickerController2.1.6升级到了3.1.6，然后旧的设置 imagePickerVC.allowPickingGif = YES;不起作用了，导致我进去相册选取图片时，gif图片可以显示，但是右上角的选择按钮没有了，不可以选择GIF图。因为版本跨度有点大，我还在看区别和改动！

**Comment by banchichen** [comment]
@ZhuHongSheng gif图之前的版本一直没有选择按钮哈，新增了allowPickingMultipleVideo属性允许设置多选视频/gif/图片后，gif图右上角才有选择按钮。

如果需要gif图和其它图片/视频混合多选，设置下allowPickingMultipleVideo为YES。
