### ISSUE TITLE
希望添加一个在外部选择是拍照还是进入相册的功能

### ISSUE THREAD

**Issue by changanli** [banchichen/TZImagePickerController#1042]
**问：你希望加什么新功能？**
答：希望添加一个在外部选择是拍照还是进入相册的功能

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有的

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：需要加一个开关属性

**其它你希望补充的内容**

**Comment by banchichen** [comment]
Demo就有这个效果，打开这个开关：

![image](https://user-images.githubusercontent.com/12755494/50445591-b6c36780-094a-11e9-9b68-5693502e551d.png)

**Comment by bolee** [comment]
看demo是在外面还写了好多代码，要是可以直接集成进去就好了
