### ISSUE TITLE
获取不到图片路径

### ISSUE THREAD

**Issue by yuagithub** [banchichen/TZImagePickerController#1043]
当前使用的版本是3.0.9。
测试环境是本人手机。
问题：部分图片无法获取路径。
1、相册里本人拍摄的相片可以拿到路径。
2、相册里保存的从其它app下载的图片可以拿到路径。
3、相册里保存的手机截图部分拿不到路径（经测试，手机截图时，有被裁剪过的截图可以拿到路径，没有被裁剪过的截图拿不到）。
信息：拿不到路径的截图的info里面只有： 
    PHImageResultDeliveredImageFormatKey = 4035;
    PHImageResultImageTypeKey = 4;
    PHImageResultIsDegradedKey = 0;
    PHImageResultRequestIDKey = 33;

**Comment by yuagithub** [comment]
原生的图片选择可以拿到所有的路径

**Comment by banchichen** [comment]
@yuagithub 对于一个同样的照片，会出现TZ里选取后没有路径，系统的有路径？

**Comment by banchichen** [comment]
@yuagithub 估计是系统会获取原图，而我这是只获取大图的缘故。
如果非要图片路径的话，你可以调一下TZImageManager的获取原图的方法，里面有，不过性能会差些

你拿这个路径是要做什么？
![image](https://user-images.githubusercontent.com/12755494/50578646-7fd3e100-0e77-11e9-8ba3-8985fb447f27.png)
