### ISSUE TITLE
为什么还不支持LivePhoto,希望快点支持~

### ISSUE THREAD

**Issue by xiongHenry** [banchichen/TZImagePickerController#1044]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1343
