### ISSUE TITLE
多选视频操作权限

### ISSUE THREAD

**Issue by for-meng** [banchichen/TZImagePickerController#1045]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：最新的3.1.0

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
真机(iPone 6p)下 , 使用框架允许多选视频得到视频信息->视频地址 , 在使用VodUpload上传时报错提示
'------------------Error Domain=NSCocoaErrorDomain Code=257 "未能打开文件“IMG_0928.MP4”，因为您没有查看它的权限。" UserInfo={NSFilePath=/var/mobile/Media/DCIM/100APPLE/IMG_0928.MP4, NSUnderlyingError=0x1141521e0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}  ---------------'
但是同样的视频 , 禁止视频多选之后 , 就可以上传成功 , 获取到的视频路径都是相同的 , 但是为什么会有权限问题?

**我如何复现这个bug？**
如上

**截图**
![image](https://user-images.githubusercontent.com/16735123/51067853-03988500-1651-11e9-9696-f7ee64be9f31.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
跟demo初始化一样, 只是修改了一些初始化设置
![image](https://user-images.githubusercontent.com/16735123/51067899-8a4d6200-1651-11e9-804a-277d2ab30ac5.png)

(而且本地是可以直接播放这个视频的)

**Comment by banchichen** [comment]
根据沙盒机制，你只能访问应用沙盒内的文件，系统资源库的视频路径你无法直接访问读取。

参考demo的做法，把视频导出到沙盒再上传：
![image](https://user-images.githubusercontent.com/12755494/51069053-8544de80-1662-11e9-9a1c-e48f3ec565a9.png)
