### ISSUE TITLE
关于内存问题的疑问

### ISSUE THREAD

**Issue by liuhuan3344** [banchichen/TZImagePickerController#1046]
由于我的app支持选择多张图片。我最开始的版本是1.7.8，更新以后使用的是3.1.2。当我选择60张图片确认的时候。1.7.8版本的内存最高达到200M，3.1.2版本的内存高达300M，我对照了一下代码。改版比较大。代码没办法进行修改替换。这个问题。能有什么办法吗。新版本的内存反而增高了。

**Comment by banchichen** [comment]
@liuhuan3344 试下最新的3.1.8版本，如觉得内存仍然大可设置下photoWidth，默认是828像素，可调大降低内存占用。
