### ISSUE TITLE
在预览相册时，从图片滚动到下一个视频，视频不能播放

### ISSUE THREAD

**Issue by fengyunjue** [banchichen/TZImagePickerController#1047]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：
Demo里也存在这个问题。
2、你用的是什么版本？升级到最新版后是否正常？
答：
之前的版本不晓得，当前3.1.9有这个问题
3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：
没有
**bug内容描述**
问题一：预览相册时，先点开一个图片，之后滑动到下一个视频时，视频没有播放按钮，也不能播放。
问题二：预览相册时，先点开一个视频，视频能正常播放，但不能左右滑动到两边的图片。

**我如何复现这个bug？**
使用3.1.9版本，当前的demo，直接运行，选择图片即可复现

**截图**
![untitled1](https://user-images.githubusercontent.com/6801297/51305435-ca5b7d00-1a75-11e9-9727-c72684ac1cc7.gif)

**Comment by fengyunjue** [comment]
上面的gif打开比较慢，可以看这个https://i.loli.net/2019/01/17/5c403e8c8ac67.gif

**Comment by banchichen** [comment]
要播放的话，需要允许视频和图片一起选，设置下属性allowPickingMultipleVideo为YES

**Comment by fengyunjue** [comment]
可以了，谢谢^_^
