### ISSUE TITLE
使用getOriginalPhotoWithAsset获取超长图片原图显示严重模糊

### ISSUE THREAD

**Issue by wonderffee** [banchichen/TZImagePickerController#1048]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：最新版只能预览图片，没有调用 getOriginalPhotoWithAsset 方法，无法显示此bug。但在预览中超大图片只能显示非常模糊的图片

2、你用的是什么版本？升级到最新版后是否正常？
答：最新的3.1.9版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
我需要从本地相册库导入一张超长（超高）图片，尺寸为{918, 21598}， 使用getOriginalPhotoWithAsset 方法来获取原图不论怎么获取都获取不到真正的原图，得到的实际图片尺寸为{212, 5000}，显示模糊

**我如何复现这个bug？**
对一个长网页进行截图，存入iOS设备相册，在app中导入这个截图，就能复现

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
经过定位，应该是 getOriginalPhotoWithAsset 中指定targetSize 为 PHImageManagerMaximumSize 导致的，而如果像旧版本中指定原图尺寸给 targetSize 就能解决此问题

关于在预览中显示超大图片模糊的问题，原因自然是新版本中的 getPhotoWithAsset 方法增加了这样的代码：
```objc
        // 超宽图片
        if (aspectRatio > 1.8) {
            pixelWidth = pixelWidth * aspectRatio;
        }
        // 超高图片
        if (aspectRatio < 0.2) {
            pixelWidth = pixelWidth * 0.5;
        }
```
我想这是因为考虑到部分用户会出现加载超大图片崩溃问题，但是感觉不应一刀切，最好是给一个选项开关来设置超大图片在预览状态是否显示缩略图

**Comment by banchichen** [comment]
根据苹果文档，targetSize指定为PHImageManagerMaximumSize就是取原图，你那里试了如果不用PHImageManagerMaximumSize，自己指定图片尺寸作为targetSize，能取得更大更清晰的图？

预览里的处理是考虑了内存问题，你这个图片在微信、QQ、微博里预览怎么样，他们的清晰吗？

**Comment by wonderffee** [comment]
是的，自己指定图片尺寸作为targetSize，就能取得更大更清晰的图，我怀疑 PHImageManagerMaximumSize 就是一个坑
我在iPad 11.4.1系统上的微博和qq里预览这张图片，都是不清晰的

**Comment by banchichen** [comment]
好吧，那可能PHImageManagerMaximumSize也是有个上限限制的...

OK，图片取太大内存是挺危险，这个只能将就了...
