### ISSUE TITLE
请问可否增加主动设置文案的接口？

### ISSUE THREAD

**Issue by likeSo** [banchichen/TZImagePickerController#1049]
TZImagePickerController的bundle内包含了en,vi,zh-Hant以及zh-Hans四种语言的语言包，我们现在的需求是适配泰语。考虑到以后的语言可能会越来越多，请考虑增加主动设置对应控件文案的接口，比如：
`imagePickerController.setTitle("", for: .title)`
`imagePickerController.setTitle("", for: .backButton)`
或者可以考虑做成全局配置。

**Comment by banchichen** [comment]
@likeSo 目前有这样的属性：languageBundle，demo里有示例，你试下

**Comment by likeSo** [comment]
不好意思老哥这两天有点忙没有回复，我试一下languageBundle这个，如果有问题我再反馈，谢谢！

**Comment by banchichen** [comment]
OK🤝
