### ISSUE TITLE
图片预览

### ISSUE THREAD

**Issue by WhoAreYou-Z** [banchichen/TZImagePickerController#1050]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
进入图片预览，滑动图片当你滑到视频的时候不能播放，展示的是视频的第一帧。

**我如何复现这个bug？**
进入图片预览，滑动图片当你滑到视频的时候不能播放，展示的是视频的第一帧。

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/1047

**Comment by banchichen** [comment]
看demo的isAssetCanSelect:的实现

**Comment by WhoAreYou-Z** [comment]
👌   谢谢🙏




| |
17600042177
邮箱：17600042177@163.com
|

Signature is customized by Netease Mail Master

在2019年01月23日 10:39，谭真 写道：

看demo的isAssetCanSelect:的实现
