### ISSUE TITLE
有一定概率出现图片乱序

### ISSUE THREAD

**Issue by GavinQin** [banchichen/TZImagePickerController#1056]
当默认进去不选择原图当时候，有一定几率出现图片乱序
ios11
1、启动相册选择图片，isSelectOriginalPhoto为NO
2、选中某一张图片，显示原图，大小不是选中的图片
3、代理里面得到的图片也不是选中的图片 
有一定概率出现

**Comment by GavinQin** [comment]
> issue模板的问题补充一下哈，比如版本信息啥的，否则很难定位
> 试下最新版是否会这样，如果会的话，麻烦先排查下提供下复现步骤哈

是下载最新版的也同样的有这个问题的，直接引用的库文件不是用的pods
![image](https://user-images.githubusercontent.com/724320/52547939-c701aa00-2e05-11e9-8730-357c2a853572.png)
![image](https://user-images.githubusercontent.com/724320/52547950-d2ed6c00-2e05-11e9-9c35-1e735c7b61c4.png)

选中图片的时候，显示原图，然后显示只有2k，实际有30M+，并且这个显示的2k的图片，不是真实选中的图片。

**Comment by banchichen** [comment]
看起来你改过我的代码，在我这的demo里会这样吗？
我如何复现这个问题？
