### ISSUE TITLE
希望添加一个选择每一张照片的代理方法

### ISSUE THREAD

**Issue by shafujiu** [banchichen/TZImagePickerController#1057]
**问：你希望加什么新功能？**
答：希望添加一个选择每一张照片的代理方法

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：会有，主要用来处理gif的，微信通常会有这样的限制，你可以尝试
1. 搞一张像素 无论是宽还是高 大于1024 的gif动态图片，在你的相册，
2. 选择你的任意好友点击发送图片，选择添加好的图片
3. 微信会给你 该gif图尺寸过大，无法发送的alert 提醒

还有app 像《即刻》是给出的一个toast，也是不让用户选择的。所以我们可以提供一个带BOOL返回值的一个代理方法，让用户自己去作图片尺寸的判断然后做出相应的返回。

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：这个完全可以定义一个非必须实现的代理，所以也不需要加开关，只是把事件回调抛出，并带上返回参数。

**其它你希望补充的内容**

希望能通过回调的返回值，让用户能有决定选不选的方式。像这样

`- (BOOL)imagePickerController:(TZImagePickerController *)picker shouldPickingPhoto:(id)asset;`

望采纳，如果觉得合适但是时间不是很允许的话，我或许可以给到提交

**Comment by banchichen** [comment]
根据图片尺寸过滤的话，倒可以通过实现isAssetCanSelect来做，返回NO的会不显示出来

如果不能被选中的图片需要在选中时给出提示的话，加一个回调是可以的，就是和isAssetCanSelect有一定的重复，API名字要好好设计下，欢迎PR哈

**Comment by TonightGod** [comment]
我们现在也有类似的需求，图片过大，例如大于20M，提示图片过大不能选择，这个相当于在选中之前做一些操作，是不是以block的形式会好一些。

**Comment by banchichen** [comment]
3.5.7已支持，可参考Demo实现isAssetCanBeSelected
