### ISSUE TITLE
Pods 上最新的3.1.6点击相册图片进入大图时，在点击返回闪退

### ISSUE THREAD

**Issue by lhm12520** [banchichen/TZImagePickerController#1058]
Demo 中没有出现，版本不同，我是正式开发中使用从pod中下载的3.1.6

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无改动

**bug内容描述**
presentViewController TZImagePickerController 后，点击一张图片，进入大图的页面，再点击返回按钮闪退

**截图**

**Comment by JackHenrry** [comment]
我的是在打开相册时出现Crash，偶发难复现，查看了源码未发现array使用问题，请问是什么原因？
报错日志 Collection was mutated while being enumerated.

**Comment by banchichen** [comment]
没日志和复现路径不好分析...

**Comment by lhm12520** [comment]
2019-02-18 15:54:45.368545+0800 HandBoxPro[28449:1392266] -[_UIFontCacheKey isHidden]: unrecognized selector sent to instance 0x600003cba580
2019-02-18 15:54:45.421820+0800 HandBoxPro[28449:1392266] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_UIFontCacheKey isHidden]: unrecognized selector sent to instance 0x600003cba580'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001070371bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001098b4735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107055f44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010703bed6 ___forwarding___ + 1446
	4   CoreFoundation                      0x000000010703dda8 _CF_forwarding_prep_0 + 120
	5   UIKitCore                           0x0000000113586178 -[UIView(Rendering) setHidden:] + 44
	6   UIKitCore                           0x0000000112ae59a6 -[UIButton _updateTitleView] + 314
	7   UIKitCore                           0x0000000112adcfbc -[UIButton titleLabel] + 144
	8   UIKitCore                           0x00000001127f44a5 -[_UIButtonBarButtonVisualProviderIOS _computeTextAttributesForBarButtonItem:] + 70
	9   UIKitCore                           0x00000001127f4eb6 -[_UIButtonBarButtonVisualProviderIOS _configureImageOrTitleFromBarButtonItem:forMetrics:] + 354
	10  UIKitCore                           0x00000001127f8b95 -[_UIButtonBarButtonVisualProviderIOS configureButton:fromBarButtonItem:] + 211
	11  UIKitCore                           0x00000001127f6bcf -[_UIButtonBarButtonVisualProviderIOS configureButton:withAppearanceDelegate:fromBarItem:] + 148
	12  UIKitCore                           0x00000001127f2fe4 -[_UIButtonBarButton _configureFromBarItem:appearanceDelegate:isBackButton:] + 86
	13  UIKitCore                           0x00000001127f2b6e -[_UIButtonBarButton configureFromBarItem:withAppearanceDelegate:] + 53
	14  UIKitCore                           0x00000001127f0320 -[_UIButtonBar _updatedViewForBarButtonItem:withView:] + 326
	15  UIKitCore                           0x00000001127eedd4 __32-[_UIButtonBar _newGroupLayout:]_block_invoke + 82
	16  UIKitCore                           0x00000001127fb1d9 -[_UIButtonBarItemLayout _updateItemView] + 53
	17  UIKitCore                           0x00000001127fb79c -[_UIButtonBarItemLayout _configure] + 39
	18  UIKitCore                           0x00000001127fa2a8 -[_UIButtonBarLayout configure] + 60
	19  UIKitCore                           0x00000001127fa3ef -[_UIButtonBarLayout addLayoutViews:] + 49
	20  UIKitCore                           0x00000001127fd77d -[_UIButtonBarItemGroupLayout _iterateConfiguredLayouts:] + 228
	21  UIKitCore                           0x00000001127fd859 -[_UIButtonBarItemGroupLayout _addLayoutViews:] + 111
	22  UIKitCore                           0x00000001127fa353 -[_UIButtonBarLayout addLayoutViews:layoutGuides:constraintsToActivate:constraintsToDeactivate:] + 111
	23  UIKitCore                           0x00000001127ef57b -[_UIButtonBar _layoutBar] + 1869
	24  UIKitCore                           0x00000001127f201b -[_UIButtonBarStackView updateConstraints] + 48
	25  UIKitCore                           0x00000001134ce059 -[UIView(AdditionalLayoutSupport) _sendUpdateConstraintsIfNecessaryForSecondPass:] + 161
	26  UIKitCore                           0x00000001134ce62e -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 1245
	27  UIKitCore                           0x00000001134ce4b2 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 865
	28  Foundation                          0x000000010853835a -[NSISEngine withBehaviors:performModifications:] + 110
	29  UIKitCore                           0x00000001134ce888 -[UIView(AdditionalLayoutSupport) _recursiveUpdateConstraintsIfNeededCollectingViews:forSecondPass:] + 112
	30  UIKitCore                           0x00000001134ce4b2 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 865
	31  UIKitCore                           0x00000001134cee4b __100-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:]_block_invoke + 85
	32  UIKitCore                           0x00000001134ce9d3 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:] + 155
	33  UIKitCore                           0x00000001134cfa87 -[UIView(AdditionalLayoutSupport) _updateConstraintsAtEngineLevelIfNeededWithViewForVariableChangeNotifications:] + 374
	34  UIKitCore                           0x000000011358496e -[UIView(Hierarchy) _updateConstraintsAsNecessaryAndApplyLayoutFromEngine] + 242
	35  UIKitCore                           0x00000001135997e9 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1525
	36  UIKitCore                           0x000000011282c3e8 -[UINavigationBar layoutSublayersOfLayer:] + 248
	37  QuartzCore                          0x0000000109476b19 -[CALayer layoutSublayers] + 175
	38  QuartzCore                          0x000000010947b9d3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	39  UIKitCore                           0x0000000113584077 -[UIView(Hierarchy) layoutBelowIfNeeded] + 1429
	40  UIKitCore                           0x00000001129ddd87 -[UINavigationController _positionNavigationBarHidden:edge:initialOffset:] + 800
	41  UIKitCore                           0x00000001129de024 -[UINavigationController _positionNavigationBarHidden:edge:] + 388
	42  UIKitCore                           0x00000001129dfd66 __54-[UINavigationController _unhideNavigationBarForEdge:]_block_invoke + 123
	43  UIKitCore                           0x000000011358b235 +[UIView(Animation) performWithoutAnimation:] + 90
	44  UIKitCore                           0x00000001129dfcce -[UINavigationController _unhideNavigationBarForEdge:] + 209
	45  UIKitCore                           0x00000001129dfeeb -[UINavigationController _setNavigationBarHidden:edge:duration:] + 207
	46  UIKitCore                           0x00000001129df4b1 -[UINavigationController _setNavigationBarHidden:edgeIfNotNavigating:duration:] + 537
	47  UIKitCore                           0x00000001129dda56 -[UINavigationController setNavigationBarHidden:animated:] + 141
	48  HandBoxPro                          0x0000000105dc277c -[TZPhotoPreviewController viewWillDisappear:] + 124
	49  UIKitCore                           0x0000000112a965b5 -[UIViewController _setViewAppearState:isAnimating:] + 1060
	50  UIKitCore                           0x0000000112a96d4c -[UIViewController __viewWillDisappear:] + 95
	51  UIKitCore                           0x00000001129dab49 -[UINavigationController _startCustomTransition:] + 1105
	52  UIKitCore                           0x00000001129f13f0 -[UINavigationController _startDeferredTransitionIfNeeded:] + 741
	53  UIKitCore                           0x00000001129f27e0 -[UINavigationController __viewWillLayoutSubviews] + 150
	54  UIKitCore                           0x00000001129d2600 -[UILayoutContainerView layoutSubviews] + 217
	55  UIKitCore                           0x0000000113599795 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1441
	56  QuartzCore                          0x0000000109476b19 -[CALayer layoutSublayers] + 175
	57  QuartzCore                          0x000000010947b9d3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	58  QuartzCore                          0x00000001093f47ca _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 342
	59  QuartzCore                          0x000000010942b97e _ZN2CA11Transaction6commitEv + 576
	60  QuartzCore                          0x000000010942c6fa _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 76
	61  CoreFoundation                      0x0000000106f9bc27 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	62  CoreFoundation                      0x0000000106f960be __CFRunLoopDoObservers + 430
	63  CoreFoundation                      0x0000000106f96751 __CFRunLoopRun + 1537
	64  CoreFoundation                      0x0000000106f95e11 CFRunLoopRunSpecific + 625
	65  GraphicsServices                    0x000000010f54b1dd GSEventRunModal + 62
	66  UIKitCore                           0x00000001130af81d UIApplicationMain + 140
	67  HandBoxPro                          0x0000000105c58570 main + 112
	68  libdyld.dylib                       0x000000010b255575 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by lhm12520** [comment]
进入相机胶卷 -》选择一张图片-》点击返回-》闪退

这个是pod里最新的版本

**Comment by banchichen** [comment]
@lhm12520 看堆栈是`-[TZPhotoPreviewController viewWillDisappear:]`里调了`-[UINavigationController setNavigationBarHidden:animated:]`就崩溃了...

**Comment by lhm12520** [comment]
链接:https://pan.baidu.com/s/1d088gbdnXUZKbhrNp6sEmw  密码:kfr8

这个是我这边的Demo，你可以试试下

**Comment by banchichen** [comment]
@lhm12520 你这个demo是必崩...隐藏导航栏的时候崩了，出现了野指针，但是TZImagePickerController和它的navigationBar引用计数都正常，而且隐藏导航栏后还执行了40多个系统UIKitCore库的方法，确定是navigationBar里的某个子视图野指针了...

但是我的demo和其他人没问题，大概是你工程里某个公共处理引起的，导致UIView、UIButton这类基础组件的生命周期异常了...

浏览代码发现`UIView+Skin`里重写了`dealloc`方法，将其注释后不再崩溃

分类方法优先级高，会覆盖系统UIView默认的dealloc实现，是个危险的动作，在这个场景下导致了TZ的navigationBar某个子视图野指针（内存空间释放了却未被置为nil）
