### ISSUE TITLE
关于照片顺序

### ISSUE THREAD

**Issue by Arthurli** [banchichen/TZImagePickerController#106]
为什么把排序由  创建时间排序 修改为 修改时间排序, 感觉大部分应用还是使用的 创建时间 这个属性进行排序

**Comment by banchichen** [comment]
你好，我看到微信是这样做的，系统的相册好像也是这样做的。比如如果在百度云中保存一个很久以前的照片到本地，在微信和系统相册中新保存的这个照片显示在第一个，而在我这里之前是按创建时间排序，这个很久以前的照片创建时间比较靠前，新保存来的照片就不好找了。而改成按修改时间排序就没有这样的困扰。

**Comment by Arthurli** [comment]
但是我目前看的微信的排序应该是创建时间排序, 你可以再关注下, 我目前的微信是最新版, 系统为 iOS10_beta_1

**Comment by banchichen** [comment]
恩，我之后还是开放一个属性可以自定义这里吧~之前2个问题中提到要求按修改时间排序~

**Comment by banchichen** [comment]
哈咯，我把你的代码都Merge了，我大致测了一下，预览时照片间距加了20px后导致了一个不好的体验：切换图片时反应比较慢~明显比微信的慢许多~    你看看~

**Comment by Arthurli** [comment]
你好 添加了图片间隔之后 不能再使用 `pagingEnabled` 这个属性, 需要自己做位移

我的做法是在实现代理
```
- (void)scrollViewWillEndDragging:(UIScrollView *)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(inout CGPoint *)targetContentOffset NS_AVAILABLE_IOS(5_0);
```
拖动结束的时候计算出新的目标位置 之后进行两步  
* 设置代理中 `targetContentOffset` 为当前位置, 因为这个滑动速度是根据当前速度和减速率决定的, 所以不能使用
* 在停止之后,执行一个位移动画, 但是目前问题是如果我自定义动画使用 `setContentOffset` 方法, 由于collectionView cell 的加载机制, cell 会在动画执行之间就被 EndDisplay 掉(从屏幕上消失)

关于这个问题, 目前我也没有找到一个很优雅的解决方案, 不过我会持续关注和解决这个 issue, 希望你也能对这一整套实现方式提出你的意见和解决方案 谢谢

当然,  作为这个库的主要维护者, 如果你认为目前的效果不能够作为一个 release 版本提供出来, 可以先把这个功能回滚 并开启一个新的 feature branch 来记录当前的代码

**Comment by banchichen** [comment]
好吧~ 反正最近不需要发什么新版本，先放着~  我有空也会来研究一下~
