### ISSUE TITLE
横竖屏切换

### ISSUE THREAD

**Issue by afskalsfk** [banchichen/TZImagePickerController#1060]
进入相册选择图片，手机横屏后会旋转    怎么禁止自动旋转

**Comment by banchichen** [comment]
在你的项目中，把横屏选项取消打钩：
![image](https://user-images.githubusercontent.com/12755494/53327114-22618b00-3922-11e9-8827-b54bc00b02c1.png)

**Comment by afskalsfk** [comment]
收到  已经勾选了，是我忘记在Delegate里设置返回样式，多谢
| |
杨战旗
|
|
yzqbeijixing@163.com
|
签名由网易邮箱大师定制


在2019年02月25日 17:24，谭真<notifications@github.com> 写道：

Closed #1060.
