### ISSUE TITLE
TZImageRequestOperation的start方法里，把request的请求放到了global_queue中

### ISSUE THREAD

**Issue by HePingLaoSan** [banchichen/TZImagePickerController#1063]
想了解下这么做的目的是什么？多谢哈

**Comment by banchichen** [comment]
为了控制最大并发，避免同时发起过多request导致内存暴增

**Comment by HePingLaoSan** [comment]
operationqueue本身就是并发，opreation的执行逻辑应该已经子线程了啊，感觉不需要再加globalqueue了

**Comment by banchichen** [comment]
嗯嗯，加到operationQueue里的时候这里是多余了，确实可以去掉
只有直接创建和start TZImageRequestOperation的场景有用

**Comment by HePingLaoSan** [comment]
嗯嗯
