### ISSUE TITLE
 imagePickerViewController.minPhotoWidthSelectable = 4400;         imagePickerViewController.minPhotoHeightSelectable = 800;         imagePickerViewController.hideWhenCanNotSelect = YES;

### ISSUE THREAD

**Issue by vistaLin** [banchichen/TZImagePickerController#1064]
imagePickerViewController.minPhotoWidthSelectable = 4400;
        imagePickerViewController.minPhotoHeightSelectable = 800;
        imagePickerViewController.hideWhenCanNotSelect = YES;
无法过滤掉电脑传给手机的图片,当这个图片并不符合至少大于4400的宽度的时候,也会显示出来

**Comment by banchichen** [comment]
@vistaLin
