### ISSUE TITLE
最新版本：设置最大可选一张图片后，可选两张图片。

### ISSUE THREAD

**Issue by NorthDogLi** [banchichen/TZImagePickerController#1065]
使用的最新版本！
你的demo也有这个问题。

初始化：
_tzPickerController = [[TZImagePickerController alloc] initWithMaxImagesCount:1 columnNumber:4 delegate:self pushPhotoPickerVc:YES];

设置最大可选一张图片。

操作流程：进入后，我同时用两个手指选两张图片，就会出现一次回调代理，一次提示我‘你最多只能选择1张照片’。

希望可以在最大可选一张照片的情况下，增加防抖机制。

**Comment by banchichen** [comment]
做这种"优化"价值太小了，给绝大部分不需要的人增加了包大小而已...
