### ISSUE TITLE
[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

### ISSUE THREAD

**Issue by HatsuneMikuV** [banchichen/TZImagePickerController#1066]
1、最新的Demo有这个bug
2、你用的3.1.9
3、没有改动

nil插入数组

![image](https://user-images.githubusercontent.com/14038743/54280102-9f069180-45d1-11e9-842d-ae9a53a82658.png)

**Comment by banchichen** [comment]
我这里可以怎样来复现？

**Comment by HatsuneMikuV** [comment]
线上用户crash   我也没找到复现的方式，但是 我觉得最后那一步   往数组里面添加   可以判断一下  对象是否存在   加一个安全判断
