### ISSUE TITLE
如何将获取的视频路径转为data ?

### ISSUE THREAD

**Issue by Mengxiaowei** [banchichen/TZImagePickerController#1067]
[[TZImageManager manager] getVideoOutputPathWithAsset:asset presetName:AVAssetExportPreset640x480 success:^(NSString *outputPath) {
        NSLog(@"视频导出到本地完成,沙盒路径为:%@",outputPath);
  } failure:^(NSString *errorMessage, NSError *error) {
        NSLog(@"视频导出失败:%@,error:%@",errorMessage, error);
    }];

如何将outputPath 转化为 data ?

**Comment by banchichen** [comment]
```objectivec
NSData *data = [NSData dataWithContentsOfFile:outputPath];
```
