### ISSUE TITLE
选中几张图片后，再打开选，选择按钮没有显示，滑动一下又出来了

### ISSUE THREAD

**Issue by YFBig-Heart** [banchichen/TZImagePickerController#1068]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
@YFBig-Heart 填一下上面的模板，试试最新demo是否正常
