### ISSUE TITLE
希望增加横屏适配

### ISSUE THREAD

**Issue by Mayinwei** [banchichen/TZImagePickerController#1070]
**问：你希望加什么新功能？**
答：
希望增加横屏适配
**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
@Mayinwei  目前选择器是支持横屏的，可以看下demo的效果
