### ISSUE TITLE
横屏预览图片时错位

### ISSUE THREAD

**Issue by Mayinwei** [banchichen/TZImagePickerController#1072]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**

横屏时预览图片出现错位，底部黑色间隔

**我如何复现这个bug？**

**截图**
![image](https://user-images.githubusercontent.com/20430546/54890155-ff0b0b00-4ee2-11e9-9fd4-05922e36ecb2.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
你是故意滑到这个位置的？
