### ISSUE TITLE
剩余可选图片数量

### ISSUE THREAD

**Issue by miniLV** [banchichen/TZImagePickerController#1075]
**问：你希望加什么新功能？**
答：假设，设置完maxImagesCount = 9，当前已选择3张，选择完成成后，重新进入相册选择，应该剩余可选6张，之前选择的3张不要带进新的图片选择列表(避免每次`didFinishPickingPhotos`都会将所有图片都再上传一次-如果图片上传的操作是在 didFinishPickingPhotos 中做的话)

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：需要

**其它你希望补充的内容**

**Comment by banchichen** [comment]
@miniLV 可以这样做：
1. 设置maxImagesCount=9，选完3张后
2. 新建一个TZ实例，设置maxImagesCount=6，不设置selectedAssets
