### ISSUE TITLE
照片选择滑动问题

### ISSUE THREAD

**Issue by ShaoShuaiiOS** [banchichen/TZImagePickerController#108]
如果照片特别多，然后向上划得特别快就会卡死或者直接闪退

**Comment by banchichen** [comment]
你好，在连线调试的情况下，卡死的情况我遇到过若干次的，但是在不调试的时候，倒没遇到过，我估计你是在调试的时候遇到这样的情况，麻烦再在非调试环境下测试下，非调试时我没遇到过这种情况。我的设备目前照片数是1000多一点。

在调试的情况下，Apple提供的Demo也偶尔会有卡死的情况，原因暂时无解...

**Comment by ShaoShuaiiOS** [comment]
非常感谢你的回复。

**Comment by ShaoShuaiiOS** [comment]
因为我现在项目要求每行显示三张照片，是因为这个引起的吗？

**Comment by banchichen** [comment]
不客气，你看我的Demo在你那里会崩溃吗？每行3张的话，对内存要求高一些，图片会取得大一些，性能上差一些，有可能是这个原因导致的...
