### ISSUE TITLE
右上角索引值bug

### ISSUE THREAD

**Issue by AndyFightting** [banchichen/TZImagePickerController#1080]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版，有

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
右上角索引值异常

**我如何复现这个bug？**
第一次选择照片A, 第二次又选择照片A(这时候外面有两张相同的A,这是正确的，照片只添加，没删除)，当点击查看第二张照片A时，右上角的索引值和第一张一样。

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
@AndyFightting 确实有这个问题，第二次选照片的时候，建议先参考demo设置下selectedAssets避开这个问题哈。

**Comment by cddjr** [comment]
复用了同一个TZImagePickerController导致的这类问题吧？
