### ISSUE TITLE
如果界面可二次编辑，图片来源是网络地址，如何兼容

### ISSUE THREAD

**Issue by FlyerYe** [banchichen/TZImagePickerController#1081]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by FlyerYe** [comment]
。

**Comment by banchichen** [comment]
看看这个是否满足需求：
Q：预览界面能否支持传入NSURL、UIImage对象？
A：3.0.1版本已支持，需新接一个库：TZImagePreviewController，请参考里面的Demo使用。
