### ISSUE TITLE
选择一组原图会阻塞线程

### ISSUE THREAD

**Issue by CivelXu** [banchichen/TZImagePickerController#1082]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：
利用了Demol中 TZImageUploadOperation 获取原图依旧会卡一下
2、你用的是什么版本？升级到最新版后是否正常？
答：
pod更新最新版本
3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：
没有
**bug内容描述**
获取一组图片的原图, 界面会卡顿一下; 做了异步的处理还是这样; 打印线程也是主线程;
debug 系统有错误日志
[ImageManager] First stage of an opportunistic image request returned a non-table format image, this is not fatal, but it is unexpected

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

`                /// 选择原图
                
                let model = UploadImages.init(pngImage: UIImage())
                var imgModels = [UploadImages](repeating: model, count: assets.count)
                
                let group = DispatchGroup()
                for (index, p) in assets.enumerated() {
                    group.enter()
                    TZImageManager.default()?.getOriginalPhoto(with: (p as? PHAsset),
                                                               newCompletion: { (image, info, flag) in
                                                                if !flag, let i = image {
                                                                    let model = UploadImages.init(pngImage: i)
                                                                    imgModels[index] = model
                                                                    group.leave()
                                                                }
                    })
                }
                group.notify(queue: .main, execute: {
                    hanlde(imgModels)
                })
            }`

**Comment by banchichen** [comment]
卡一下是卡多久，多少ms？
可以用instruments的time profiler看看主线程的各方法耗时
