### ISSUE TITLE
希望增加個tag屬性

### ISSUE THREAD

**Issue by 19aneng** [banchichen/TZImagePickerController#1084]
**问：你希望加什么新功能？**
答：TZImagePickerController增加一個tag屬性

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是

**其它你希望补充的内容**
一個界面可能會存在兩種格式的圖片,都經過代理方法出來不好處分,建議添加tag屬性
![image](https://user-images.githubusercontent.com/22389902/55936518-2135b480-5c69-11e9-9a6c-d094f4daa99d.png)

**Comment by banchichen** [comment]
@19aneng 你自己可以判断的哈
比如在控制器里声明一个属性，isCover

去选封面图的时候，设置isCover = true，在回调里就知道这个是封面
选内容的时候，再设置isCover = false
