### ISSUE TITLE
裁剪框适应图片大小

### ISSUE THREAD

**Issue by wenlian2035** [banchichen/TZImagePickerController#1086]
楼主，怎么设置裁剪框和图片一样大啊，固定大小的裁剪框如果图片太大不好选择啊，怎么设置成每次单选图的时候裁剪框就是图片大小勒？

**Comment by 57267612** [comment]
你可以设置cropRect

**Comment by banchichen** [comment]
@wenlian2035 目前不支持动态变化cropRect，你可以试试把cropRect设置成一个比较小的值....

**Comment by 57267612** [comment]
@wenlian2035 如果裁剪框和图片一样大小有什么意义呢，就不需要裁剪了吧。如果你在一个图片位置需要裁剪过的图片，你可以提前在跳转之前设置cropRect，裁剪框大小设置好就可以了。

**Comment by wenlian2035** [comment]
@57267612 和图片大小可以放大图片裁剪啊，如果图片很大，只需要裁剪边边一点的距离，不是和图片大小那怎么裁剪勒？裁剪框放太大小图片又不好处理了啊

**Comment by banchichen** [comment]
刚刚发了新版哈，大家试下3.2.1新增裁剪用scaleAspectFillCrop属性，设置为YES后，照片尺寸小于裁剪框时会自动放大撑满
