### ISSUE TITLE
图片选择完成，infos 数组返回的字段在模拟器和真机不一致

### ISSUE THREAD

**Issue by devvved** [banchichen/TZImagePickerController#1087]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.0

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
1.下载demo，打开修改 build ID 改成我项目目前使用的ID，方便在真机上调试。
2.选择模拟器运行，打开图片选择器，选择图片，在 didFinishPickingPhotos 函数中断点，查看 infos 数组中每个 字典key 的个数 。
3.经过多次对比，模拟器返回的字典key的个数为10个，真机返回的个数为4个或者5个。
4.我需要用 PHImageFileURLKey 这个字段，但是真机测试通过当前类库这个字段拿不到。

**我如何复现这个bug？**
用真机 和模拟器运行demo，选择图片， 在 didFinishPickingPhotos 函数中 看 infos 字典的key个数就好

**截图**
<img width="1231" alt="屏幕快照 2019-04-19 上午11 25 04" src="https://user-images.githubusercontent.com/35266402/56403833-d550c400-6295-11e9-84f2-dbcb345d1044.png">

<img width="877" alt="phone" src="https://user-images.githubusercontent.com/35266402/56403867-f6191980-6295-11e9-9c53-786fe159b0ed.png">

<img width="869" alt="phone1" src="https://user-images.githubusercontent.com/35266402/56403915-41cbc300-6296-11e9-9740-e2b55e3060a3.png">

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
@devvved 嗯嗯，info里的数据是不稳的，不保证返回所有信息
如果需要的话，可以试下用requestImageDataForAsset里返回的info，单独再调一下
