### ISSUE TITLE
照片选择过多

### ISSUE THREAD

**Issue by ShaoShuaiiOS** [banchichen/TZImagePickerController#109]
提示：Communications error: <OS_xpc_error: <error: 0x19cc0caf0> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x19cc0ce50> { length = 22, contents = "Connection interrupted" }
}> 然后直接闪掉

**Comment by banchichen** [comment]
你好，方便提供更多的信息吗，机型和系统版本，选择了多少张照片崩的呢？

**Comment by ShaoShuaiiOS** [comment]
苹果6plus的手机,选择了32张照片。还有就是苹果4s手机，选择了16张照片。
但是demo里测试没有问题，我在自己程序里使用就出现这个问题了，我想问一下我应该注意哪些设置问题吗

**Comment by banchichen** [comment]
昂，不需要什么设置噢...选择32张图片确实是一个危险的操作....点击确定后，读取32张图片时内存会增高的，这里会有风险...

**Comment by ShaoShuaiiOS** [comment]
最多建议选多少照片呢，我们现在有一个这种需求，如果实在不行我就减少一点。

**Comment by banchichen** [comment]
微信和QQ啥的都是9张咯，那你也先设置成9张试试~ 看看内存增长是不是能接受，能的话你再适当增加，对了，要注意使用最新版哈，旧版本对于内存控制上不是很好

**Comment by ShaoShuaiiOS** [comment]
非常感谢，升级到新版本之后就好用了，就算是选了32张照片。哈哈。

**Comment by banchichen** [comment]
不客气，好用就好~
