### ISSUE TITLE
现在我想设置网络图片到这个UICollectionView中，能实现吗？怎么实现

### ISSUE THREAD

**Issue by FakerCurry** [banchichen/TZImagePickerController#1090]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
参考这个库：https://github.com/banchichen/TZImagePreviewController
