### ISSUE TITLE
相册选择100张以上，下方选中数量的文字显示异常

### ISSUE THREAD

**Issue by michaelin1208** [banchichen/TZImagePickerController#1091]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.20

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**
测试机iPhone 5s，iOS12系统，相册选择100张以上，下方选中数量的文字显示异常，显示为 “1..”。

**我如何复现这个bug？**
选100张以上即可复现

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
3.2.2版本已修复，可以自动缩小了
