### ISSUE TITLE
增加网络图片显示与编辑

### ISSUE THREAD

**Issue by IamSiYe** [banchichen/TZImagePickerController#1092]
**问：你希望加什么新功能？**
答：加载网络图片显示，同时又可以继续从相册添加图片。如：我从相册上传照片后，接口返回url，加载url显示图片，我希望还可以从相册选择图片，再进行上传照片操作

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：是

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：不是，加个属性开关更好

**其它你希望补充的内容**

**Comment by banchichen** [comment]
参考这个库的demo：https://github.com/banchichen/TZImagePreviewController
