### ISSUE TITLE
demo从相册里选一张大于10M的图片，6plus闪退（Message from debugger: Terminated due to memory issue）

### ISSUE THREAD

**Issue by zifeizhang** [banchichen/TZImagePickerController#1093]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by ddangPengf520** [comment]
你好  问下  6p 这个问题解决了吗  我是6p选择原图 （50多张）崩溃的，大小 100M左右，

**Comment by BlueSky-TY** [comment]
> 你好 问下 6p 这个问题解决了吗 我是6p选择原图 （50多张）崩溃的，大小 100M左右，

我想应该是加载大量图片引起的内存暴涨而闪退，在选择完相册后不要直接存UIImage对象进数组，持有PHAsset对象就可以了，使用时通过PHAsset的回调方法赋值，如果需要上传图片直接通过PHAsset获取Data上传这样子可以避免内存暴涨从而引起闪退

**Comment by zifeizhang** [comment]
> > 你好 问下 6p 这个问题解决了吗 我是6p选择原图 （50多张）崩溃的，大小 100M左右，
> 
> 我想应该是加载大量图片引起的内存暴涨而闪退，在选择完相册后不要直接存UIImage对象进数组，持有PHAsset对象就可以了，使用时通过PHAsset的回调方法赋值，如果需要上传图片直接通过PHAsset获取Data上传这样子可以避免内存暴涨从而引起闪退

就是这种方式解决了。。。

**Comment by zifeizhang** [comment]
> 你好 问下 6p 这个问题解决了吗 我是6p选择原图 （50多张）崩溃的，大小 100M左右，

解决了
