### ISSUE TITLE
相册里面拍完照片， 回来刷新collectionView，拍照的那个照片默认没有勾选，iOS11.4，看了最新代码也是，逻辑是没问题的，加个回调主线程就正常了

### ISSUE THREAD

**Issue by CaraZTT** [banchichen/TZImagePickerController#1094]
//有个显示bug问题
源码
   self.selectPhotoButton.selected = model.isSelected;
   self.selectImageView.image = self.selectPhotoButton.isSelected ? [UIImage imageNamedFromMyBundle:self.photoSelImageName] : [UIImage imageNamedFromMyBundle:self.photoDefImageName];

修改了一下
    dispatch_async(dispatch_get_main_queue(), ^{
        self.selectPhotoButton.selected = model.isSelected;
        self.selectImageView.image = self.selectPhotoButton.isSelected ? [UIImage imageNamedFromMyBundle:self.photoSelImageName] : [UIImage imageNamedFromMyBundle:self.photoDefImageName];
    });
或者
   self.selectImageView.image = model.isSelected ? [UIImage imageNamedFromMyBundle:self.photoSelImageName] : [UIImage imageNamedFromMyBundle:self.photoDefImageName];

我在想是不是 self.selectPhotoButton.selected还么赋进去就开始了读操作

**Comment by banchichen** [comment]
试下最新demo或3.2.5版本可以吗？我这试了几次没复现
