### ISSUE TITLE
dismiss后 再push到子控制器,会出现状态栏往下偏移

### ISSUE THREAD

**Issue by XavierLost** [banchichen/TZImagePickerController#1095]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
在tabbarController主界面,选择图片选择器.选择图片后,TZImagePickerController dismiss后,如果这时候要push一个子界面,就会出现tabbar往下偏移

**我如何复现这个bug？**
 dismiss后 再push到子控制器,会出现状态栏往下偏移

**截图**
![WechatIMG15](https://user-images.githubusercontent.com/24632295/57524249-d4bdc180-7359-11e9-971c-ed96812ef478.jpeg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
[tabBar未见下移.mov.zip](https://github.com/banchichen/TZImagePickerController/files/5470292/tabBar.mov.zip)
如上截屏，测试正常

可以在最新demo里试下，如还有问题，请提供下可复现demo
