### ISSUE TITLE
手机前后台切换中导致图片数据为nil，需要判断

### ISSUE THREAD

**Issue by Mamakou** [banchichen/TZImagePickerController#1096]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：没有进行测试

2、你用的是什么版本？升级到最新版后是否正常？
答：最新的版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**

31  -[TZImageManager getCameraRollAlbum:allowPickingImage:needFetchAssets:completion:] (TZImageManager.m:0)
--
32 0x00000001029b9ba0 -[TZImagePickerController pushPhotoPickerVc] (TZImagePickerController.m:391)
33  0x00000001029b99ec -[TZImagePickerController observeAuthrizationStatusChange] (TZImagePickerController.m:377)
[NSMutableArray(Safe) hookAddObject:] (NSObjectSafe.m:726)

用户有比较频繁的切换前后台操作
**我如何复现这个bug？**

通过nsobjiectSafe发现的
**截图**
![8D087266-878B-4C52-8726-2656B049651C](https://user-images.githubusercontent.com/13375024/57593183-e4f9ba80-756c-11e9-8b31-fe17e2c39a7f.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
 [[TZImageManager manager] getCameraRollAlbum:tzImagePickerVc.allowPickingVideo allowPickingImage:tzImagePickerVc.allowPickingImage needFetchAssets:YES completion:^(TZAlbumModel *model) {
                self->_model = model;
////这里添加了判断
                if(self->_model.models != nil){
                    self->_models = [NSMutableArray arrayWithArray:self->_model.models];
                }
                [self initSubviews];
            }];

**Comment by banchichen** [comment]
请先在demo里复现哈

看堆栈，你们项目里有hook了系统类的方法，这个本身是不安全的，可能带来一些异常行为：
https://github.com/banchichen/TZImagePickerController/issues/1485
