### ISSUE TITLE
拉取视频列表的时候出现"正在处理..."

### ISSUE THREAD

**Issue by Lee5s** [banchichen/TZImagePickerController#1097]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：没有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.0.7 

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有
**bug内容描述**
使用present方法 进入，获取相册的视频列表时出现 ‘正在处理...’

**我如何复现这个bug？**
暂时无法复现 ，只遇到一例

**截图**
![106421558402873_ pic](https://user-images.githubusercontent.com/16056689/58064784-12221a80-7bb6-11e9-880f-24c39e906f0a.jpg)

**其它说明**

有没有其它要补充的？比如你的初始化TZImagePickerController的代码
初始化代码：

  TZImagePickerController *imagePickerVC = [[TZImagePickerController alloc]initWithMaxImagesCount:4 columnNumber:4 delegate:self pushPhotoPickerVc:YES];
    imagePickerVC.naviBgColor= kMainColor;
    imagePickerVC.sortAscendingByModificationDate = NO;
    imagePickerVC.alwaysEnableDoneBtn = YES;
    imagePickerVC.allowPickingMultipleVideo = NO;
    imagePickerVC.allowPickingImage = NO;
    [self presentViewController:imagePickerVC animated:YES completion:nil];

**Comment by banchichen** [comment]
升级到最新版试试：
![image](https://user-images.githubusercontent.com/12755494/58141647-ace22e00-7c76-11e9-9bf7-3b6b69888bc6.png)

设置了allowPickingImage为NO，若相册内无视频，会出现上面的情况
