### ISSUE TITLE
拿到的全景图变大

### ISSUE THREAD

**Issue by sherygril** [banchichen/TZImagePickerController#1099]
相册里一张1.1兆的全景图，非原图选择出来会变成3.4兆
![7811558347043_ pic_hd](https://user-images.githubusercontent.com/13061044/58075581-a00ffc80-7bda-11e9-8cd8-4d87cc09c603.jpg)

**Comment by banchichen** [comment]
3.4M这个值你是怎么拿到的？代码贴一下

**Comment by sherygril** [comment]
> 3.4M这个值你是怎么拿到的？代码贴一下

![image](https://user-images.githubusercontent.com/13061044/58142262-f5025000-7c78-11e9-955f-4af0a6069a30.png)

**Comment by banchichen** [comment]
@sherygril  把1.0改为0.9，数据就差不多了
