### ISSUE TITLE
怎么获得视频的数据

### ISSUE THREAD

**Issue by BC-Y** [banchichen/TZImagePickerController#11]
传回来的是一张img，那视频的数据呢，求解答下

**Comment by banchichen** [comment]
你好，如果用户选择的是视频，会调用- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingVideo:(UIImage *)coverImage sourceAssets:(id)asset 代理方法，和void (^didFinishPickingVideoHandle)(UIImage *coverImage,id asset); 这个Block，你实现其中一个即可，我只给你返回了一张视频的封面图片，和一个asset对象，是拿asset对象去获得视频的，请参考TZImageManager的.h里暴露的方法，用这里的方法：- (void)getVideoWithAsset:(id)asset completion:(void (^)(AVPlayerItem * playerItem, NSDictionary * info))completion; 可以获得视频资源。具体怎么播放playerItem对象，请参考TZVideoPlayerController类的播放代码。
