### ISSUE TITLE
创建TZImagePickerController crash崩溃

### ISSUE THREAD

**Issue by kinghour** [banchichen/TZImagePickerController#1101]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：无

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.0

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：
没有
**bug内容描述**

正常创建 TZImagePickerController 崩溃
TZImagePickerController * vc = [[TZImagePickerController alloc] initWithMaxImagesCount:6 delegate:self];
 [self presentViewController:vc animated:YES completion:nil];

我重新新建一个项目测试却没有任何问题 而且我正式项目里这个问题一开始是正常 从昨天开始才出现这样的异常

**我如何复现这个bug？**

**截图**

![image](https://user-images.githubusercontent.com/18476012/58169845-5dc2ea00-7cc4-11e9-9a4c-2e2b6fc95fcf.png)
**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
@kinghour 检查下最近做了啥改动，试着逐渐回退代码，看看是哪个commit导致的，再通过注释的方法定位到是哪行代码/哪个方法/哪个库引起的...
