### ISSUE TITLE
大神好，我用cocoapods集成了您的工程，当前系统语言为中文；在选择相册的时候，相机胶卷和最近添加都是英文的，其他的都是中文（比如”原图“，”取消“等），请问这是怎么回事？

### ISSUE THREAD

**Issue by DaZhuzhu** [banchichen/TZImagePickerController#1103]

**Comment by banchichen** [comment]
Q：系统语言是中文/英文，界面上却有部分相册名字、返回按钮显示成了英文/中文？
A：请参考 https://github.com/banchichen/TZImagePickerController/issues/443 和 https://github.com/banchichen/TZImagePickerController/issues/929

**Comment by DaZhuzhu** [comment]
收到，我的问题就是根据这个链接解决的，谢谢。


 
---原始邮件---
发件人: "谭真"<notifications@github.com>
发送时间: 2019年5月29日(星期三) 晚上6:26
收件人: "banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"MrW"<1224500307@qq.com>;
主题: Re: [banchichen/TZImagePickerController] 大神好，我用cocoapods集成了您的工程，当前系统语言为中文；在选择相册的时候，相机胶卷和最近添加都是英文的，其他的都是中文（比如”原图“，”取消“等），请问这是怎么回事？ (#1103)



Q：系统语言是中文/英文，界面上却有部分相册名字、返回按钮显示成了英文/中文？
 A：请参考 #443 和 #929
