### ISSUE TITLE
showSelectedIndex=NO时，选中预览后返回多了一个空的indexLabel

### ISSUE THREAD

**Issue by fanxiangyang** [banchichen/TZImagePickerController#1105]
showSelectedIndex=NO时，选中预览后返回多了一个空的indexLabel,虽然多了一个空的label没有影响，你的demo也正常，但是我由于导入YYKit这个库，里面很多category，估计是把indexLabel.userInteractionEnabled=YES了，因为这个为YES,会拦截选中和反选的按钮事件，你看看能不能吧labe做到button上，或者改变下层次结构，我是在回调里面重新隐藏了这个控件
```
[imagePickerVc setAssetCellDidSetModelBlock:^(TZAssetCell *cell, UIImageView *imageView, UIImageView *selectImageView, UILabel *indexLabel, UIView *bottomView, UILabel *timeLength, UIImageView *videoImgView) {
        indexLabel.hidden=YES;
    }];
```

**Comment by banchichen** [comment]
你这里改动要简单些，我里面_indexLabel逻辑挺多，先不动了...
