### ISSUE TITLE
裁剪图片界面 上方navigationcontroller的颜色 以及下方工具栏的颜色怎么设置?

### ISSUE THREAD

**Issue by scyios** [banchichen/TZImagePickerController#1107]
我设置了 TZImagePickerController 的naviBgColor 和naviTitleColor  
在相册选择的时候都是好使的    但是到了图片裁剪界面 颜色还是黑色的

**Comment by banchichen** [comment]
试试实现下这个photoPreviewPageUIConfigBlock，block里可以设置naviBar和toolBar
