### ISSUE TITLE
关于视频预览闪退的问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [banchichen/TZImagePickerController#1113]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：用模拟器未发现，之前集成到代码中的功能是正常的，但是昨天开发的时候出现了问题。

2、你用的是什么版本？升级到最新版后是否正常？
答：我对比了下代码，是最新版

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：未改动，只是在外层又做了封装

**bug内容描述**
2019-06-15 10:30:05.340866+0800 InforCenterMobile[2134:341561] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <AVKVODispatcher 0x281432160> for the key path "currentItem" from <AVPlayer 0x2814352a0> because it is not registered as an observer.'
*** First throw call stack:
(0x1babc527c 0x1b9d9f9f8 0x1baacf4b0 0x1bb56b430 0x1bb56b1ec 0x1026aff1c 0x1bb56af2c 0x1c0acd0f4 0x1c0c05858 0x1c0c06bdc 0x1c0aa8dcc 0x1061e76f0 0x1061e8c74 0x1061f0bf4 0x1061f18b4 0x1061fb77c 0x1ba7e5114 0x1ba7e7cd4)
libc++abi.dylib: terminating with uncaught exception of type NSException

**我如何复现这个bug？**
单选视频时，点击视频进行选择，然后在手机连接xcode开发时卡在预览界面，未加载视频缩略图，其他元素都有。如果不连xcode，点击选择视频直接闪退。

**截图**

**其它说明**
我用的iOS12.3.1系统，我同事在老的10.3系统测试没问题，和系统有关系？

**Comment by JamesLiAndroid** [comment]
补充一下，错误定位在

NSObject+SZKVO.m中removeDasen:forKeyPath:方法，第24行

**Comment by banchichen** [comment]
@JamesLiAndroid   hi，NSObject+SZKVO是你工程里的文件吧？不是我库里的

自己检查下哈，看起来KVO操作时，移除了一个未注册的观察者导致的
