### ISSUE TITLE
你好，我这里使用了图片裁剪，但是裁剪出来的图片发虚，请问怎么办？

### ISSUE THREAD

**Issue by yanngxinlei** [banchichen/TZImagePickerController#1114]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/13198051/59547472-287f8400-8f72-11e9-84e7-054eb9331be5.png">

**Comment by banchichen** [comment]
裁剪出来的图片大小，和cropRect是一致的
你如果放到更大尺寸的容器里预览，是会模糊的
