### ISSUE TITLE
scaleAspectFillCrop YES, 左右滑动会失效

### ISSUE THREAD

**Issue by lixiang1994** [banchichen/TZImagePickerController#1116]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有 

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.1

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**
开启scaleAspectFillCrop, 列表中选中一个图, 正常, 但是接下来左滑右滑后会失效

**我如何复现这个bug？**
开启scaleAspectFillCrop, 列表中选中一个图, 正常, 但是接下来左滑右滑后会失效

**截图**
应该不需要

**其它说明**
无

**Comment by 472125266** [comment]
1、我最新的Demo是否有这个bug？【如果Demo没问题，请升级新版】
答：有
2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.1，最新版本
3、是否有改动过我库内部的代码？【如有，请告诉我你改了什么】
答：无
步骤：
选择裁剪的图片，进入页面，图片会自动撑开，最短边自适应裁剪框->向左/向右滑动图片，即换一张图片->再滑动切换回来，原本应该继续撑开的图片，撑不开了。
希望能够优化一下，即当滑动的时候，如果是（开启scaleAspectFillCrop）刷新一下页面，帮助撑开。我们App一直用的TZ，跪求优化一下下。跪谢！！！

**Comment by lixiang1994** [comment]
@banchichen

**Comment by banchichen** [comment]
@472125266 @lixiang1994 也帮忙看看哈，欢迎PR呀...

**Comment by banchichen** [comment]
3.4.4版本优化了下这里：scaleAspectFillCrop和allowCrop都为true时，预览页面不允许左右滑动切换图片

算是绕过了这个问题。。。
