### ISSUE TITLE
拿到的图片顺序跟选择时不一样

### ISSUE THREAD

**Issue by madonya** [banchichen/TZImagePickerController#1120]
按照顺序选择图片，调用`- (void)getOriginalPhotoWithAsset:(PHAsset *)asset completion:(void (^)(UIImage *photo,NSDictionary *info))completion;
`方法获取原图，得到的图片顺序跟之前显示的不一致。

**Comment by banchichen** [comment]
@madonya 参考下TZPhotoPickerController里doneButtonClick方法的代码来保证图片顺序

**Comment by madonya** [comment]
> @madonya 参考下TZPhotoPickerController里doneButtonClick方法的代码来保证图片顺序

好的，谢谢。
