### ISSUE TITLE
本地化语言添加日语

### ISSUE THREAD

**Issue by WIndFate** [banchichen/TZImagePickerController#1121]
**问：你希望加什么新功能？**
答：本地化语言添加日语

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有日语

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：跟随系统语言自动设置就可以

**其它你希望补充的内容**

**Comment by banchichen** [comment]
@WIndFate 日语大部分APP不太需要，会给不需要的APP增加包大小

建议自备下语言文件，通过设置languageBundle参数来支持哈

可以使用自定义的languageBundle文件

**Comment by SuiFengLiuNian** [comment]
我这么设置     imagePickerVC.languageBundle = [NSBundle bundleWithPath:[[NSBundle mainBundle]pathForResource:@"ja" ofType:@"lproj"]];
为什么不起作用？语言还是英语而不是日语
