### ISSUE TITLE
强制开启 选择多个 GIF 图功能,    用 PHImageManager  类  requestImageDataForAsset方法选出GIF 是静态图

### ISSUE THREAD

**Issue by kakaxihoracker** [banchichen/TZImagePickerController#1122]
1.   描述:    
  修改  TZPhotoPickerController    中 didSelectItemAtIndexPath  和 cell 设置,   允许 GIF 多选,  
 选择多张 GIF,  确认选择,  通过选择出的   TZAssetModel 属性 assets list  ,   使用PHImageManager  类 requestImageDataForAsset 获取 GIF data数据流,    dataUTI  偶尔  不是 gif,   (例如选出9张 GIF,  会有 一张或两张 是静态图),

![屏幕快照 2019-06-24 下午12 07 01](https://user-images.githubusercontent.com/17845864/59991307-7e8eae80-9679-11e9-8612-89ecb460d83e.png)
![屏幕快照 2019-06-24 下午12 12 43](https://user-images.githubusercontent.com/17845864/59991308-7e8eae80-9679-11e9-8700-445be058486d.png)

2.   这种情况出现的时候,   有一种情况是,   选择GIF 时,   GIF 没有完全加载, GIF 预览是 旋转等待状态 ,  
![屏幕快照 2019-06-24 下午12 21 08](https://user-images.githubusercontent.com/17845864/59991609-a4688300-967a-11e9-817c-22865214c094.png)

3.  使用 最新版 3.2.1  发现的问题,   之前用的旧版本没有,    不知道是 框架代码的问题还是 系统 requestImageDataForAsset 选择出来会有问题,   劳烦楼主查看一下,

**Comment by kakaxihoracker** [comment]
PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
                option.version = PHImageRequestOptionsVersionOriginal;

 [[PHImageManager defaultManager] requestImageDataForAsset:model.asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
                   
        }];

**Comment by kakaxihoracker** [comment]
问题出现在系统 api上,     出现问题的 GIF 有15.6M  大小,    可能系统api 做了性能上的处理,   如果 option 为 nil,   选择出来的会是压缩的 jpg 图片,    
PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
                option.version = PHImageRequestOptionsVersionOriginal;
                 [[PHImageManager defaultManager] requestImageDataForAsset:model.asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
                    
                 }];

**Comment by banchichen** [comment]
@kakaxihoracker 如你上面的设置，option.version设置为PHImageRequestOptionsVersionOriginal，应该是原图吧？
如果也不动的话，也看下系统相册、微信里的这个图会不会动哈

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/60386571-2c121f80-9ac9-11e9-8db4-fe0d880b8572.png)
