### ISSUE TITLE
希望增加视频剪裁功能 用户选择开始时间和结束时间

### ISSUE THREAD

**Issue by hhz3136809** [banchichen/TZImagePickerController#1124]
**问：你希望加什么新功能？**
答：视频剪裁功能 用户选择开始时间和结束时间

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：微信发朋友圈有 视频3~15秒

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：需要属性开关

**其它你希望补充的内容**

**Comment by banchichen** [comment]
@hhz3136809 这个功能应该不会加，要加也是新开一个库哈，建议找下已有的库
然后设置autoDismiss为NO，这个tz不会自己dismiss，之后在回调里，用picker来push这个视频裁剪页面
