### ISSUE TITLE
wexin wechat 

### ISSUE THREAD

**Issue by ZhengHei** [banchichen/TZImagePickerController#1125]
作者可以把“wexin”“wechat”“微信”等有关微信的字眼去掉嘛？疑似因为有这关于微信的字眼，被拒有隐藏金融支付功能。

**Comment by banchichen** [comment]
@ZhengHei 你们被拒了吗？😂
看下苹果的邮件内容~

**Comment by ZhengHei** [comment]
被拒2.3.1 还在验证中，过几天来回复你

**Comment by marutite** [comment]
我的被2.3.1，不知道是不是也是这个问题

**Comment by banchichen** [comment]
@ZhengHei hi，你的APP后面通过审核了吗？找到问题了吗？

**Comment by cddjr** [comment]
项目中用了微信登录的记得改为不含支付功能的sdk，目前我项目中使用微信登录(不含支付)+TZImagePickerController审核一切正常

**Comment by ZhengHei** [comment]
我们一直被拒2.3.1，然后我们上诉，Apple告诉我们初次拒绝判断错误，不是2.3.1。所以被拒2.3.1和TZImagePickerController无关，是Apple审核判断错误。

**Comment by banchichen** [comment]
好的，那就好👍
