### ISSUE TITLE
swift Project Use Carthage ,Umbrella header for module 'TZImagePickerController' does not include header 'TZAssetCell.h'

### ISSUE THREAD

**Issue by LeoAiolia** [banchichen/TZImagePickerController#1126]
![图片](https://user-images.githubusercontent.com/16910025/60322801-f0853180-99b2-11e9-99e2-f896232cb79f.png)
Umbrella header for module 'TZImagePickerController' does not include header 'TZAssetCell.h'

my Version
github "banchichen/TZImagePickerController" "3.2.1"

**Comment by banchichen** [comment]
是个警告，不影响使用，先不管哈
