### ISSUE TITLE
[bug反馈]上传图片会超出限制:要求最多上传9张,这时候先选择8张, 然后再进入相册勾选1张,同时点击拍照拍一张图片, 选择右下角的“使用图片”这时候,会上传选择两张(包括之前在相册中选择的那一张),这样就会带来超出限制的问题.建议在TZPhotoPickerController.m文件的591行添加相机拍照按钮超出图片的限制.

### ISSUE THREAD

**Issue by suyuxinlong** [banchichen/TZImagePickerController#1127]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
可以体验下demo，达到最大可选张数后，虽然可以继续拍照，但拍照后点[使用照片]，新拍的照片不会被选中的，点击[完成]后回调里还是9张

**Comment by suyuxinlong** [comment]
这个bug,还是存在的, 上传确实是超过了9张, 稍后我会录制一个vlog

**Comment by banchichen** [comment]
@suyuxinlong 好，视频请拿demo录制哈
