### ISSUE TITLE
[bug反馈]上传图片会超出限制

### ISSUE THREAD

**Issue by suyuxinlong** [banchichen/TZImagePickerController#1128]
要求最多上传9张,这时候先选择8张, 然后再进入相册勾选1张,同时点击拍照拍一张图片, 选择右下角的“使用图片”这时候,会上传选择两张(包括之前在相册中选择的那一张),这样就会带来超出限制的问题.建议在TZPhotoPickerController.m文件的591行添加相机拍照按钮超出图片的限制.

**Comment by suyuxinlong** [comment]
最新版本源代码的.

**Comment by suyuxinlong** [comment]
// take a photo / 去拍照
    TZImagePickerController *tzImagePickerVc = (TZImagePickerController *)self.navigationController;
    
    // 解决超过上传图片多少的限制
    if (tzImagePickerVc.selectedModels.count >= tzImagePickerVc.maxImagesCount) {
        NSString *title = [NSString stringWithFormat:[NSBundle tz_localizedStringForKey:@"Select a maximum of %zd photos"], tzImagePickerVc.maxImagesCount];
        [tzImagePickerVc showAlertWithTitle:title];
        return;
    }

**Comment by banchichen** [comment]
看这个：https://github.com/banchichen/TZImagePickerController/issues/1127
