### ISSUE TITLE
iPhone6s iOS 12.2问题

### ISSUE THREAD

**Issue by ddangPengf520** [banchichen/TZImagePickerController#1129]
这个库找我至少已经使用过4个项目，今天突然发现一个问题，微信电脑端传给一张照片到手机微信，手机微信保存图片，相机胶卷图片总数+1正确，然后去应用上传照片，发现没有刚才保存的照片，但是图片总数是保存之后的总数，同样的代码  只有在iOS 12.2 iPhone6s上出现此问题

**Comment by banchichen** [comment]
@ddangPengf520 看来是图片排序的问题，可以在代码里搜一下：sortDescriptorWithKey:@"creationDate"

如果设置了sortAscendingByModificationDate为NO，TZ内部会根据照片创建时间排序，你导入的这个照片如果创建时间较早，就不会出现在最后一个...

建议保持sortAscendingByModificationDate为YES，这样能使用系统的默认排序，顺序会和相册的完全一样

**Comment by banchichen** [comment]
相关issue：https://github.com/banchichen/TZImagePickerController/issues/259

**Comment by ddangPengf520** [comment]
问题已经解决，之前一直sortAscendingByModificationDate设置为NO，风格变了  不过  问题不大，非常感谢！！！
