### ISSUE TITLE
多选视频 提示 最多可选？？照片

### ISSUE THREAD

**Issue by Vicktor0616** [banchichen/TZImagePickerController#1130]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.1

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
如题

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
![image](https://user-images.githubusercontent.com/15155110/60656598-4e69bb80-9e82-11e9-9162-c1e0d554e670.png)

**Comment by banchichen** [comment]
@Vicktor0616  如果你选9个视频，微信的提醒也是这样的

**Comment by banchichen** [comment]
有啥建议吗？
