### ISSUE TITLE
通知add了没有remove

### ISSUE THREAD

**Issue by ACFancy** [banchichen/TZImagePickerController#1131]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：现在源码就有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.0 没有

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
TZPhotoPickerController和TZPhotoPreviewController中，对这个UIApplicationDidChangeStatusBarOrientationNotification添加通知，没有移除

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
确实👍，我改下

**Comment by banchichen** [comment]
3.2.2版本已修复
