### ISSUE TITLE
iOS 版本号12.1.14 选择60张照片之后 直接崩溃 （运行demo也是如此，）

### ISSUE THREAD

**Issue by ddangPengf520** [banchichen/TZImagePickerController#1133]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by ddangPengf520** [comment]
Connection to assetsd was interrupted or assetsd died 直接弹出这个  demo看了下  12.1.14 版本  设置70张也是这样子，希望 大佬看下什么原因

**Comment by banchichen** [comment]
@ddangPengf520 超多图片获取images数组内存占用比较大，可以设置onlyReturnAsset为YES，我内部只返回assets，图片自己获取
如果是批量上传，可参考TZImageUploadOperation的代码，拿到图片直接上传，不要一直引用在内存里
