### ISSUE TITLE
希望添加选择图片角标的功能，右上角是你当前选中的下标

### ISSUE THREAD

**Issue by S209** [banchichen/TZImagePickerController#1138]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by S209** [comment]
qq和微信都有这个功能 显示1 、2、3、4

**Comment by yangbo930204** [comment]
这个库支持这个功能，有属性可以设置：showSelectedIndex
