### ISSUE TITLE
希望添加类似微信选择图片裁剪任意比例

### ISSUE THREAD

**Issue by MeowEight** [banchichen/TZImagePickerController#1139]
**问：你希望加什么新功能？**
答：任意裁剪比例，在裁剪的时候任意调整选择框的比例

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：微信选择头像

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是的，但是建议加入开关

**其它你希望补充的内容**
这个功能难度不大，个人可以修改，但我用pods集成，还是希望加入，比较方便

**Comment by banchichen** [comment]
@JanWirt 老哥，提个PR不？

**Comment by jerryhu** [comment]
推荐用第三方组件 https://github.com/TimOliver/TOCropViewController
