### ISSUE TITLE
照片清晰度

### ISSUE THREAD

**Issue by ShaoShuaiiOS** [banchichen/TZImagePickerController#114]
感觉现在的照片选择页面的清晰度没有之前的高了，这个可以在哪里调吗？

**Comment by banchichen** [comment]
/// Default is 600px / 默认600像素宽
@property (nonatomic, assign) CGFloat photoPreviewMaxWidth;
这里，把这里调大，清晰度会提高，不过这个主要是针对iPad的设置....iPhone下并没有怎么降低清晰度...而且这个也是照片预览页的。。。
