### ISSUE TITLE
截取得到的图片比截取的下移了一些 

### ISSUE THREAD

**Issue by a123478we** [banchichen/TZImagePickerController#1140]
代码和demo里面设置一样

  NSInteger widthHeight = self.view.gg_width - 2 * left ;
    NSInteger top = (self.view.gg_height - widthHeight) / 2 ;
    imagePickerVc.cropRect = CGRectMake(left, top, widthHeight, widthHeight);

**Comment by banchichen** [comment]
demo正常吗？和demo对比下哈
