### ISSUE TITLE
设置scaleAspectFillCrop = YES后，预览时左右切换下一张图片会导致截取图片区域出现问题

### ISSUE THREAD

**Issue by zkfpk6** [banchichen/TZImagePickerController#1142]
如图
[https://s2.ax1x.com/2019/08/08/eT1Rld.png](url)
[https://s2.ax1x.com/2019/08/08/eT12SH.png](url)

**Comment by Sexmonkey** [comment]
same problem.

**Comment by banchichen** [comment]
3.4.4版本优化了下：scaleAspectFillCrop和allowCrop都为true时，预览页面不允许左右滑动切换图片

这样算是绕过了这个问题...
