### ISSUE TITLE
在iOS通过XCode11 在iOS13设备上，设置仅显示视频，没有文件的时候，点击返回文件夹会崩溃。

### ISSUE THREAD

**Issue by ruomu023** [banchichen/TZImagePickerController#1143]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.1

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**

在iOS通过XCode11 在iOS13设备上，设置仅显示视频，没有文件的时候，点击返回文件夹会崩溃。

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by ruomu023** [comment]
通过XCode11 在iOS13设备上，设置仅显示视频，没有文件的时候，点击返回文件夹会崩溃。

 TZImagePickerController *  videoVc = [[TZImagePickerController alloc] initWithMaxImagesCount:1 delegate:weakSelf];

    videoVc.allowPickingVideo = YES;
    videoVc.allowPickingVideo = YES;
    videoVc.allowPickingImage = NO;
    videoVc.allowPickingOriginalPhoto = NO;
    videoVc.allowTakeVideo = NO;
    
[self presentViewController:videoVc animated:YES completion:nil];

**Comment by ruomu023** [comment]
还发现一个现象，在XCode 11 SDK编译的包，在iOS13设备上，选择视频，不能筛选出Live Photo的视频。

**Comment by banchichen** [comment]
没有视频时的奔溃，3.2.2版本已修复

Live Photo本来就不属于视频吧？微信也是这样的
