### ISSUE TITLE
remde例子中的代码第二步block 提示错误

### ISSUE THREAD

**Issue by hurosezhang** [banchichen/TZImagePickerController#1144]
例子中的代码，提示block 缺少一个参数
[imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets) {

    }];
正确的为
    [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
        
    }];

**Comment by banchichen** [comment]
感谢指出，已更正
