### ISSUE TITLE
关于"已隐藏"图片的选择

### ISSUE THREAD

**Issue by smallevil** [banchichen/TZImagePickerController#1145]
我的app以前是用的系统原生的选择照片的.
前段时间换成这个SDK.
但换完后,有用户反应,选择图片时,自己隐藏的图片不能选择了.
以前是可以的.

这个要怎么设置??或者什么时间能把这个功能加上?

**Comment by banchichen** [comment]
这个目前还不支持设置，可以搜一下：PHAssetCollectionSubtypeSmartAlbumAllHidden
要把这个行代码删掉
或者要不你hook下？

**Comment by smallevil** [comment]
我先试试
