### ISSUE TITLE
apng格式的动图怎么跟gif格式的图做一样的判断呢？

### ISSUE THREAD

**Issue by 77521** [banchichen/TZImagePickerController#1146]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：
有
2、你用的是什么版本？升级到最新版后是否正常？
答：
最新
3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**
我想让apng格式的图片 跟gif格式一样判断 因为 apng也是动图 怎么控制它的选择与否

**我如何复现这个bug？**
你找一张apng格式的图片就能看到 apng其实是png格式的一种动图 后缀也是png 所以不知道怎么判断

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
关于判断apng，试试这里的方法哈：https://www.cnblogs.com/w3live/p/8391599.html
不过apng不能直接播放吧？播放的话是否需要借助APNGKit...
