### ISSUE TITLE
右上角的取消按钮显示问题

### ISSUE THREAD

**Issue by leftw** [banchichen/TZImagePickerController#1147]
iOS 13
右上角的取消按钮有时显示，有时不显示，但点击事件有响应，只是显示问题。

**Comment by banchichen** [comment]
@leftw 有比较具体的复现路径吗？我这demo没复现

直接设置的navigationItem.backBarButtonItem，应该不太会出问题...

**Comment by leftw** [comment]
imagePickerVc.barItemTextColor = [UIColor redColor];
    imagePickerVc.naviBgColor = [UIColor whiteColor];
加入这两行代码，取消 按钮的显示有问题

**Comment by banchichen** [comment]
OK，这样设置后复现了，3.2.2版本已修复，升级下哈

**Comment by leftw** [comment]
好像还是有问题哦

**Comment by banchichen** [comment]
@leftw 是用的demo工程吗？截个图看下，我这边demo已经正常了

**Comment by leftw** [comment]
![IMG_0359](https://user-images.githubusercontent.com/7991745/63832838-36a34500-c9a4-11e9-8052-cac9908d03a2.PNG)
![IMG_0361](https://user-images.githubusercontent.com/7991745/63832858-3dca5300-c9a4-11e9-8dc0-583186bbcfd8.PNG)

**Comment by leftw** [comment]
![IMG_0362](https://user-images.githubusercontent.com/7991745/63833021-9863af00-c9a4-11e9-8bb3-74098243169d.PNG)

**Comment by CivelXu** [comment]
问题依旧存在；
在demo中设置
imagePickerVc.barItemTextColor = [UIColor redColor];
打开图片选择器，点击左上角的返回， 随便选一个照片分组进去， 右上角的取消按钮就变了。

**Comment by banchichen** [comment]
@CivelXu 在readme里加一下QQ群，在群里帮忙发个视频看下哈

**Comment by banchichen** [comment]
已修复，这个地方Xcode11-beta5是好的，Xcode11-beta6有问题....

新版本：3.2.3

**Comment by banchichen** [comment]
@leftw

**Comment by zxy1829760** [comment]
Version 3.2.3 and 3.2.2 does't work well in this question

**Comment by banchichen** [comment]
> Version 3.2.3 and 3.2.2 does't work well in this question

try 3.2.4

**Comment by YTSmile** [comment]
iOS 11 以上 navbar上的取消按钮距离右边缘太紧了，是否可以提供一个margin 供外界控制呢

**Comment by banchichen** [comment]
@YTSmile 试试设置下cancelBtnTitleStr，后面加一个空格？
