### ISSUE TITLE
视频播放时希望有进度条

### ISSUE THREAD

**Issue by jianqingyu** [banchichen/TZImagePickerController#1148]
**问：你希望加什么新功能？**
答：视频播放时有进度条

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：应该是适合所有人，最好UI可以公开自己定制

**其它你希望补充的内容**

**Comment by banchichen** [comment]
微信的图片选择器，没有进度条吧？

**Comment by winterwd** [comment]
我也碰到了这个需求，希望作者添加此功能吧
