### ISSUE TITLE
在 Xcode11, iOS13下点击系统返回按钮闪退

### ISSUE THREAD

**Issue by LuckyChen73p** [banchichen/TZImagePickerController#1151]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
进入照片选择页, 点击返回按钮push, 出现闪退  Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Override of -navigationBar:shouldPopItem: returned YES after manually popping a view controller (navigationController=<TZImagePickerController: 0x15aa66600>)'

**我如何复现这个bug？**
同上

**截图**
![image](https://user-images.githubusercontent.com/42130106/63505699-93b37c80-c506-11e9-9b30-bc42a4699bee.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by LuckyChen73p** [comment]
使用Xcode10生成的包安装在iOS13手机上正常, 试过的解决方法: 拦截/交换系统方法 -navigationBar:shouldPopItem: , 仍闪退......

**Comment by banchichen** [comment]
demo是正常的，是你项目中重写了-navigationBar:shouldPopItem吧....

**Comment by LuckyChen73p** [comment]
> demo是正常的，是你项目中重写了-navigationBar:shouldPopItem吧....

解决了, 感谢

**Comment by hYRamos** [comment]
> > demo是正常的，是你项目中重写了-navigationBar:shouldPopItem吧....
> 
> 解决了, 感谢

你好，请问怎么解决的，我也是一样的报错

**Comment by hYRamos** [comment]
还是WRNavigationBar的问题，修改了一下代码

`#pragma mark - deal the gesture of return
- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
    
    if ([[UIDevice currentDevice].systemVersion doubleValue] >= 13.0) {
        return YES;
    }else {
        __weak typeof (self) weakSelf = self;
        id<UIViewControllerTransitionCoordinator> coor = [self.topViewController transitionCoordinator];
        if ([coor initiallyInteractive] == YES) {
            NSString *sysVersion = [[UIDevice currentDevice] systemVersion];
            if ([sysVersion floatValue] >= 10) {
                [coor notifyWhenInteractionChangesUsingBlock:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
                    __strong typeof (self) pThis = weakSelf;
                    [pThis dealInteractionChanges:context];
                }];
            } else {
                [coor notifyWhenInteractionEndsUsingBlock:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
                    __strong typeof (self) pThis = weakSelf;
                    [pThis dealInteractionChanges:context];
                }];
            }
            return YES;
        }
        NSUInteger itemCount = self.navigationBar.items.count;
        NSUInteger n = self.viewControllers.count >= itemCount ? 2 : 1;
        UIViewController *popToVC = self.viewControllers[self.viewControllers.count - n];
        [self popToViewController:popToVC animated:YES];
        return YES;
    }

}`

**Comment by StevenGardnerGMJ** [comment]
WRNavigationBar.m 里

#pragma mark - deal the gesture of return
- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
  添加：  
===============
    if ([[UIDevice currentDevice].systemVersion doubleValue] >= 13.0) {
        return YES;
    }
================== =====
