### ISSUE TITLE
目前发现四个关键词没有汉化，希望及时修改啊

### ISSUE THREAD

**Issue by DevChen** [banchichen/TZImagePickerController#1152]
1、选择拍照页面的按钮“Cancel”和“PHOTO”，
2、选择带有拍照键的全部照片的标题，10.2.1上叫“All Photos”，12.3.1上叫“Camera Roll”
和12.3.1 
必现！

**Comment by banchichen** [comment]
1. 你把模拟器设置为中文，demo正常的
2. 你可以在我工程里搜下，是没有 All Photos 和 Camera Roll 两个文案的，这是系统给的，语音跟随项目设置、系统设置，Demo工程里，模拟器设置为中文，导航栏会是中文的：
![image](https://user-images.githubusercontent.com/12755494/63652557-4b10f300-c794-11e9-85d3-40f7507de124.png)

**Comment by DevChen** [comment]
thx~ Localization native development region = China 就好了 Xcode配置问题
