### ISSUE TITLE
导航栏标题 和 collectionView布局怎么修改

### ISSUE THREAD

**Issue by huangxianyu** [banchichen/TZImagePickerController#1153]
![image](https://user-images.githubusercontent.com/20720740/63768345-8cbfac00-c902-11e9-9084-bc0e0cce123a.png)
1.导航栏标题怎么改啊?
2.照片布局可以修改吗? 可以一行展示3个吗?

**Comment by huangxianyu** [comment]
![image](https://user-images.githubusercontent.com/20720740/63768597-369f3880-c903-11e9-9d4d-56223ef95018.png)
tableView背景色怎么改?

**Comment by banchichen** [comment]
1、不支持，显示的是相册的名字
2、初始化的时候，传入columnNumber
3、不支持，可以参考下photoPickerPageUIConfigBlock，提个PR过来？
