### ISSUE TITLE
3.2.2版本 访问相册没有权限时，还是会出现null

### ISSUE THREAD

**Issue by vhuichen** [banchichen/TZImagePickerController#1155]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：demo没有，建议对极端情况下优化下

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.2（最新版）

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**
3.2.2版本 访问相册没有权限时，还是会出现null。建议 appName 获取为空时做下处理

` NSDictionary *infoDict = [TZCommonTools tz_getInfoDictionary];

            NSString *appName = [infoDict valueForKey:@"CFBundleDisplayName"];

            if (!appName) appName = [infoDict valueForKey:@"CFBundleName"];

            NSString *tipText = [NSString stringWithFormat:[NSBundle tz_localizedStringForKey:@"Allow %@ to access your album in \"Settings -> Privacy -> Photos\""],appName];

            _tipLabel.text = tipText;

            [self.view addSubview:_tipLabel];`
这里最终拿到的 appName 也可能是空的，所以建议做下空值处理。

**我如何复现这个bug？**

**截图**
<img width="480" alt="屏幕快照 2019-09-02 16 13 20的副本" src="https://user-images.githubusercontent.com/12621313/64100130-89fb0600-cd9d-11e9-9149-27a2785e2e1a.png">

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
3.2.3版本已修复

**Comment by weqeo** [comment]
还是会出现，建议先用infoDictionary
`+ (NSDictionary *)tz_getInfoDictionary {
    NSDictionary *infoDict = [NSBundle mainBundle].infoDictionary;
    if (!infoDict || !infoDict.count) {
        infoDict = [NSBundle mainBundle].localizedInfoDictionary;
    }
    if (!infoDict || !infoDict.count) {
        NSString *path = [[NSBundle mainBundle] pathForResource:@"Info" ofType:@"plist"];
        infoDict = [NSDictionary dictionaryWithContentsOfFile:path];
    }
    return infoDict ? infoDict : @{};
}`

**Comment by banchichen** [comment]
@weqeo 你那里是localizedInfoDictionary有值但没有CFBundleDisplayName、CFBundleName，而infoDictionary里有吗？

**Comment by supermanyqq** [comment]
3.6.0 还是有这个问题 localizedInfoDictionary 取出来的是权限相关的配置 没有 CFBundleDisplayName、CFBundleName

**Comment by banchichen** [comment]
@supermanyqq 收到，刚刚发了个3.6.2，localizedInfoDictionary里没有CFBundleDisplayName和CFBundleName时，会尝试从[NSBundle mainBundle].infoDictionary里再读一次
