### ISSUE TITLE
ITMS-90683: NSLocationWhenInUseUsageDescription

### ISSUE THREAD

**Issue by xiaohange** [banchichen/TZImagePickerController#1156]
ITMS-90683：Info.plist中缺少用途字符串 - 您的应用程序代码引用一个或多个访问敏感用户数据的API。应用程序的Info.plist文件应包含一个NSLocationWhenInUseUsageDescription键，其中包含面向用户的用途字符串，清楚而完整地解释了您的应用程序需要数据的原因。从2019年春季开始，提交到App Store访问用户数据的所有应用都需要包含目的字符串。如果您使用的是外部库或SDK，则它们可能会引用需要用途字符串的API。虽然您的应用可能不使用这些API，但仍需要一个目的字符串。您可以联系库或SDK的开发人员，并请求他们发布不包含API的代码版本。了解详情（https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy）。

**Comment by xiaohange** [comment]
未使用到定位功能 该如何去掉呢?

**Comment by banchichen** [comment]
库里面拍照时会用到定位，建议参考demo完善下info.plist
