### ISSUE TITLE
单选模式下，如何在选择后直接返回，不进入确认页面？

### ISSUE THREAD

**Issue by emc2ws** [banchichen/TZImagePickerController#1157]
单选模式下，如何在选择后直接返回，不进入确认页面？

**Comment by banchichen** [comment]
/// Default is YES, if set NO, user can't preview photo.
/// 默认为YES，如果设置为NO,预览按钮将隐藏,用户将不能去预览照片
@property (nonatomic, assign) BOOL allowPreview;

**Comment by sagesse-cn** [comment]
> /// Default is YES, if set NO, user can't preview photo.
> /// 默认为YES，如果设置为NO,预览按钮将隐藏,用户将不能去预览照片
> @Property (nonatomic, assign) BOOL allowPreview;

实测仍进入确认页

**Comment by banchichen** [comment]
@sagesse-cn 不可能的，你拿demo试试，打开imagePickerVc.allowPreview = NO这行代码

**Comment by sagesse-cn** [comment]
> @sagesse-cn 不可能的，你拿demo试试，打开imagePickerVc.allowPreview = NO这行代码
好像是旧版问题，我升级看看
