### ISSUE TITLE
iOS 13 新的 present 效果有 UI Bug

### ISSUE THREAD

**Issue by RayJiang16** [banchichen/TZImagePickerController#1160]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：tag: 3.2.3，已经是最新版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
iOS 13 新的 present 效果有 UI Bug，顶部高出了一段距离（截图中红色区域）

**我如何复现这个bug？**
将 Demo 中的 ViewController 第 389 行注释掉

**截图**
![1568183592668](https://user-images.githubusercontent.com/17922324/64673599-2c537180-d4a1-11e9-8f69-acaca161f525.jpg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
无

**Comment by banchichen** [comment]
老哥，来个PR不？

**Comment by RayJiang16** [comment]
> 老哥，来个PR不？

这个问题改好了，但是又发现了新的问题，裁剪功能也会受到这个特性的影响，我把这个一起改掉再发PR给你哈

**Comment by banchichen** [comment]
👍👍

**Comment by banchichen** [comment]
赞，已合并，随着下次发版哈
