### ISSUE TITLE
希望加个视频裁剪的功能

### ISSUE THREAD

**Issue by VolleyZ** [banchichen/TZImagePickerController#1163]
**问：你希望加什么新功能？**
答：选择完视频后可编辑裁剪

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是。要加开关

**其它你希望补充的内容**

**Comment by banchichen** [comment]
Duplicate of https://github.com/banchichen/TZImagePickerController/issues/830
