### ISSUE TITLE
如果获取视频的地址呢？

### ISSUE THREAD

**Issue by yangguanghei** [banchichen/TZImagePickerController#1164]
如果获取视频的地址呢？ 有什么好的方法，网上的一些方法并获取不到地址。

**Comment by banchichen** [comment]
参考demo哈，可以直接导出到沙盒，再拿视频的沙盒地址

**Comment by yangguanghei** [comment]
很感谢您的回答。我之所以获取不到视频地址是因为视频是iCloud上的，现在解决了。

**Comment by banchichen** [comment]
@yangguanghei 赞👍，欢迎把解决方案写出来，供后面的同学参考

**Comment by xianxiaojian** [comment]
> 很感谢您的回答。我之所以获取不到视频地址是因为视频是iCloud上的，现在解决了。

你好，iCloud上的视频取不到你是怎么处理的呢
