### ISSUE TITLE
单选选择视频，取消预览功能并没有完全禁止，点击cell里的时间那黑条还能进行预览。。

### ISSUE THREAD

**Issue by VolleyZ** [banchichen/TZImagePickerController#1165]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没

**bug内容描述**
单选选择视频，取消预览功能并没有完全禁止，点击cell里的时间那黑条还能进行预览。。

**我如何复现这个bug？**
```
imagePickerVc.allowPickingImage = NO;
imagePickerVc.allowPreview = NO;
imagePickerVc.maxImagesCount = 1;
```

**截图**
![IMG_2153](https://user-images.githubusercontent.com/7054883/65123306-82865e80-da25-11e9-8025-ef7507d4dcec.jpeg)

点击这块黑边还能预览

**其它说明**
内部没有默认将交互关闭**bottomView.userInteractionEnabled = NO;**。
导致触发了didSelectItemAtIndexPath的方法进入了预览功能。

只能在外面关闭了。
```
imagePickerVc.assetCellDidLayoutSubviewsBlock = ^(TZAssetCell *cell, UIImageView *imageView, UIImageView *selectImageView, UILabel *indexLabel, UIView *bottomView, UILabel *timeLength, UIImageView *videoImgView) {
        bottomView.userInteractionEnabled = NO;
};
```

**Comment by banchichen** [comment]
3.4.0版本已修复，同时适配了iOS14，修复了2个严重适配问题，建议更新~

**Comment by MigratorySwan** [comment]
使用3.8.3版本，allowPreview设置为false。在cell上向左滑动，也会触发预览。

**Comment by banchichen** [comment]
@MigratorySwan 欢迎PR哈
