### ISSUE TITLE
iOS 12.1.4 6P 拍照后无反应，之后会崩溃

### ISSUE THREAD

**Issue by fengyufei** [banchichen/TZImagePickerController#1166]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有，用的就是Demo
<img width="980" alt="屏幕快照 2019-09-19 下午7 33 33" src="https://user-images.githubusercontent.com/12997867/65240734-83e28480-db14-11e9-9677-7a950a34855a.png">

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
点击拍照功能，完成后，处理照片过程中卡死。

**我如何复现这个bug？**
<img width="980" alt="屏幕快照 2019-09-19 下午7 33 33" src="https://user-images.githubusercontent.com/12997867/65240672-67dee300-db14-11e9-91af-99f030ebfae6.png">

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
哎，只贴了崩溃的代码，控制台的错误没发出来，然后难以复现...
过于久远，期间没有其他人反馈类似问题，于是关闭了，后续还有问题希望提供更多细节...
