### ISSUE TITLE
您好，发现个小bug，因为是pod导入，我就不便自己改动啦

### ISSUE THREAD

**Issue by Tony9527i** [banchichen/TZImagePickerController#1167]
在info.plist中添加View controller-based status bar appearance，并设置为NO
点击预览后，返回到相册，相册导航栏显示异常，少了个statusBar高度
只有iOS13系统会有这个问题，其余系统不会出现

**Comment by Tony9527i** [comment]
只有iOS13系统会有这个问题，其余系统不会出现

**Comment by banchichen** [comment]
嗯嗯，UIApplication管理状态栏的方案在iOS9就标记不再维护了，iOS13系统对状态栏做了大的改造，UIApplication管理状态栏的方式估计是不行了

建议跟随系统建议，View controller-based status bar appearance设置为YES哈

**Comment by banchichen** [comment]
如有绕过方案，也可以提个PR，我可以merge进去
