### ISSUE TITLE
最新版TZImageManager中引用CoreServices/CoreServices.h需要兼容低版本

### ISSUE THREAD

**Issue by asd6802862** [banchichen/TZImagePickerController#1168]
我目前使用系统为10.13.5，xcode使用的版本为9.4.1，我从这个库的3.2.0升到最新版本，TZImageManager中使用了CoreServices这个库，编译一直报错 ：'CoreServices/CoreServices.h' file not found，然后使用另一台电脑xcode是10点多，就没有问题，所以我只能在低版本这台电脑回退到这个库的3.2.0这个版本

**Comment by banchichen** [comment]
嗯嗯，有什么兼容的办法吗？提个PR过来吧？

**Comment by asd6802862** [comment]
大兄弟，目前还没有找到好的解决方法，😊😊

**Comment by banchichen** [comment]
好勒，找到后欢迎提PR哈

**Comment by LionBuer** [comment]
你好，请问怎么兼容啊？

**Comment by flysec** [comment]
大兄弟，在AFNetworking的AFURLRequestSerialization里找到了一个兼容方案,看样子是应该用MobileCoreServices?
因为不太好修改pod里的代码，所以目前我暂用
pod 'TZImagePickerController', '3.2.1'来解决编译问题

以下是AFURLRequestSerialization的代码
#if TARGET_OS_IOS || TARGET_OS_WATCH || TARGET_OS_TV
#import <MobileCoreServices/MobileCoreServices.h>
#else
#import <CoreServices/CoreServices.h>
#endif

**Comment by banchichen** [comment]
@flysec 👍

新版本3.2.8已发布，直接使用MobileCoreServices，不再依赖CoreServices了，可以更新了哈
