### ISSUE TITLE
自己拍摄的图片 加入到 selectPhoto中

### ISSUE THREAD

**Issue by JJCoderiOS** [banchichen/TZImagePickerController#117]
你好,我的项目目前在使用该库,请教如下问题,谢谢回复!
我自己在拍摄的照片,确认选择后 怎么添加到 selectedphotos中,现在拍摄的照片当在进入相册选择新照片时候 之前自己拍摄的照片就没有了....望回复!谢谢!

**Comment by banchichen** [comment]
2016.6.22更新: 刚刚更新了代码，现在版本更新到了1.5.0。更新如下： 1.可把拍照按钮放在外面了,可以设置弹出一个sheet提示用户选择相册或相机； 2.新增了sortAscendingByModificationDate属性，默认为YES，设置为NO时，照片会按修改时间降序，拍照按钮会在第一个； 3.优化了Demo页面的UI，新增6个开关控件，可方便地更改各个设置来打开选择器； 4.修复了若干bug；

你好，请参考最新的Demo，最新的Demo可以在外面拍照的。

**Comment by JJCoderiOS** [comment]
谢谢你的耐心回复,我稍后用最新的!谢谢
