### ISSUE TITLE
iOS 13 PHImageFileURLKey 获取不到

### ISSUE THREAD

**Issue by XavierLost** [banchichen/TZImagePickerController#1170]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
Q：有的图片info里没有PHImageFileURLKey？
A：不要去拿PHImageFileURLKey，没用的，只有通过Photos框架才能访问相册照片，光拿一个路径没用。
如果需要通过路径上传照片，请先把UIImage保存到沙盒，用沙盒路径。
如果你上传照片需要一个名字参数，请参考Demo直接用照片名字。

**Comment by andi911** [comment]
但是这样的话，不知道图片类型啊，比如本来png，你难道都改成jpg?

**Comment by andi911** [comment]
> Q：有的图片info里没有PHImageFileURLKey？
> A：不要去拿PHImageFileURLKey，没用的，只有通过Photos框架才能访问相册照片，光拿一个路径没用。
> 如果需要通过路径上传照片，请先把UIImage保存到沙盒，用沙盒路径。
> 如果你上传照片需要一个名字参数，请参考Demo直接用照片名字。

但是这样的话，不知道图片类型啊，比如本来png，你难道都改成jpg?

**Comment by banchichen** [comment]
用这个判断：https://www.jianshu.com/p/b148e9ce7c02
