### ISSUE TITLE
苹果8plus(无刘海系列)上弹出相册后，选择预览再返回就会出现导航栏上移

### ISSUE THREAD

**Issue by guo47** [banchichen/TZImagePickerController#1173]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.4

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**
1. 进入相册
2. 选择并放大一张照片
3. 点击返回
点击返回退出预览模式后 ，就会出现，而且必现，有刘海的手机没有这个问题

**我如何复现这个bug？**
必现

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
看看这个哈：https://github.com/banchichen/TZImagePickerController/issues/1167

**Comment by guo47** [comment]
收到，谢谢！验证过可以了




| |
郭世杰
邮箱：jgy32guo47@163.com
|

签名由 网易邮箱大师 定制

在2019年09月27日 13:17，谭真 写道：

看看这个哈：#1167
