### ISSUE TITLE
相册里面拍照按钮能否支持放在头部

### ISSUE THREAD

**Issue by watericon** [banchichen/TZImagePickerController#1174]
**问：你希望加什么新功能？**
答：相册里面拍照按钮能否支持放在头部

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是的，需要加个开关按钮

**其它你希望补充的内容**

**Comment by banchichen** [comment]
可以的，demo玩一玩，有个【照片按修改时间升序排列】开关
