### ISSUE TITLE
【重要优化】新版里的确认按钮太小，点击非常困难，严重影响体验！

### ISSUE THREAD

**Issue by JackJiang2011** [banchichen/TZImagePickerController#1175]
新版里的确认按钮太小，点击非常困难，很多时候以为是没有点到（**实际是整个按钮的可点击大小就只有文字那么一点点，没有设置空白边距！**），严重影响体验！

**见下图：**
![](http://www.52im.net/data/attachment/album/201909/27/222946xlqtgc5t9zlqwgs5.jpg)

**Comment by SingKing1987** [comment]
@property (nonatomic, copy) void (^photoPickerPageDidLayoutSubviewsBlock)(UICollectionView *collectionView, UIView *bottomToolBar, UIButton *previewButton, UIButton *originalPhotoButton, UILabel *originalPhotoLabel, UIButton *doneButton, UIImageView *numberImageView, UILabel *numberLabel, UIView *divideLine);

**Comment by banchichen** [comment]
3.6.0版本已优化，完成按钮旁边的数字也可以点了。

旧版实际的可点击范围不止文字那么大的，文字上下的间距也可点，要圈选到「UIButton-确认」视图
