### ISSUE TITLE
app启动第一次进入相册，点击返回相册列表有几秒钟卡顿。是否可以直接进入相册选择列表。

### ISSUE THREAD

**Issue by iron93** [banchichen/TZImagePickerController#1176]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.09

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
警告是在非主线程修改了ui
Main Thread Checker: UI API called on a background thread: -[UIViewController navigationController]

**我如何复现这个bug？**

**截图**

**其它说明**
xcode11 ios13

**Comment by banchichen** [comment]
升级到3.2.5试试
