### ISSUE TITLE
图片剪切时默认剪切区域只能在图片内

### ISSUE THREAD

**Issue by afskalsfk** [banchichen/TZImagePickerController#1177]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by afskalsfk** [comment]
比如一张长方形的图   如果不手动放大就可以剪切得到图片之外的区域，，上下是白色的  希望添加一个选项开关，限制剪切区域，如果yes 则最小剪切区域就是图片的最小边，，不能缩小到图片以外，，，，，，类似于手动放大且固定到图片满足剪切框的大小

**Comment by banchichen** [comment]
嗯， 这个功能有bug：https://github.com/banchichen/TZImagePickerController/issues/1142

**Comment by banchichen** [comment]
求PR呀
