### ISSUE TITLE
iOS13 顶部bar位置问题

### ISSUE THREAD

**Issue by YinZhifu** [banchichen/TZImagePickerController#1178]
1、我最新的Demo是否有这个bug
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.4

3、是否有改动过我库内部的代码？
答：没有

**bug内容描述**
iOS13 全屏present  tzimagepickercontroller 点击图片跳转到剪切页面 在返回 顶部bar位置上移动了

**Comment by banchichen** [comment]
看看这个哈：https://github.com/banchichen/TZImagePickerController/issues/1167
