### ISSUE TITLE
ios 13取原图的地方取出来也是模糊的图片取不到原图

### ISSUE THREAD

**Issue by wangxiaoyi2hao** [banchichen/TZImagePickerController#1179]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by seanLee** [comment]
PHImage获取图片的地方貌似会回掉两次,一次是缩略图,一次是全图,不知道是不是这里影响的.我现在的项目里没用到这个第三方,刚好碰巧看到类似的问题

**Comment by wangxiaoyi2hao** [comment]
> PHImage获取图片的地方貌似会回掉两次,一次是缩略图,一次是全图,不知道是不是这里影响的.我现在的项目里没用到这个第三方,刚好碰巧看到类似的问题

对的，确实是一次缩略一次原图，最后在
 PHImageRequestOptions *option = [[PHImageRequestOptions alloc]init];
   option.synchronous = YES;
保证图片返回一次，暂时现在都得到的是原图。

**Comment by banchichen** [comment]
嗯，系统API设计如此，会先返回缩略图，有个isDegraded参数，isDegraded为NO说明是大图/原图

synchronous比较危险，如果是iCloud图片会有个下载过程，注意多测试下表现
