### ISSUE TITLE
iPhone11 Pro 上从相册内选择相机拍摄视频闪退

### ISSUE THREAD

**Issue by for-meng** [banchichen/TZImagePickerController#1182]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.2 , 看了最新版本源码 , 该处无改动 , 并且直接使用UIImagePickerController也一样有bug

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**
在相册内选择相机 , 切换为视频 , 取消 , 重新再选择一次相机 , 再切换为视频会导致闪退
报错log为: 
 -[AVCaptureDevice setActiveColorSpace:] Not supported - use activeFormat.supportedColorSpaces

**我如何复现这个bug？**
在相册内选择相机 , 切换为视频 , 取消 , 重新再选择一次相机 , 再切换为视频会导致闪退(直接使用UIImagePickerController 也会有这个问题)

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
  目前发现是使用UIImagePickerController时的videoQuality设置的问题 , 如果使用默认设置或者设置为 UIImagePickerControllerQualityTypeHigh  ,  UIImagePickerControllerQualityTypeMedium 
 ,  UIImagePickerControllerQualityTypeLow  ,  UIImagePickerControllerQualityType640x480 这四个枚举会导致在iPhone11 上第二次使用UIImagePickerController打开相机闪退
而使用UIImagePickerControllerQualityTypeIFrame1280x720或UIImagePickerControllerQualityTypeIFrame960x540这两个枚举则不会闪退 。(但是不清楚具体原因)

**Comment by banchichen** [comment]
看来是Apple自己把UIImagePickerController改坏了.....

**Comment by Gantios** [comment]
我是也是这样~  有解决方案吗？

**Comment by for-meng** [comment]
emmmm我只知道如何避免崩溃 , 但是研究不出来原因...  
不要使用默认设置 , 创建UIPIImagePicker设置videoQuality 为 UIImagePickerControllerQualityTypeIFrame1280x720或UIImagePickerControllerQualityTypeIFrame960x540 这两个枚举则不会闪退 。
