### ISSUE TITLE
想将右上角的cancel按钮替换成完成按钮，求实现

### ISSUE THREAD

**Issue by zoushuyue** [banchichen/TZImagePickerController#1184]

**Comment by banchichen** [comment]
Hook下TZPhotoPickerController的viewDidLoad，覆盖下rightBarButtonItem

**Comment by zoushuyue** [comment]
谢谢，已经实现了





------------------ 原始邮件 ------------------
发件人: "谭真"<notifications@github.com>; 
发送时间: 2019年10月14日(星期一) 中午11:05
收件人: "banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com>; 
抄送: "拂溪"<1103617692@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [banchichen/TZImagePickerController] 想将右上角的cancel按钮替换成完成按钮，求实现 (#1184)




Hook下TZPhotoPickerController的viewDidLoad，覆盖下rightBarButtonItem
