### ISSUE TITLE
圆角裁剪出来有白色背景

### ISSUE THREAD

**Issue by xhjss** [banchichen/TZImagePickerController#1186]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

http://allsale-dev-1256326697.cos.ap-guangzhou.myqcloud.com/img/dg_1182913942394114048.jpeg

**Comment by banchichen** [comment]
Demo里返回的图片没有白色背景的，对比下Demo：
![image](https://user-images.githubusercontent.com/12755494/66727700-77cbb780-ee73-11e9-9257-cea238ecdbe3.png)
