### ISSUE TITLE
导航栏高度会变小

### ISSUE THREAD

**Issue by ox-man** [banchichen/TZImagePickerController#1188]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.4

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
导航栏的高度会变小。

**我如何复现这个bug？**
前提：
工程的info.plist里将View controller-based status bar appearance属性值设置为NO。
操作：
从图片列表页进入预览，再从预览返回图片列表页，导航栏的高度会变小。

**截图**
1.入口截图：

![WechatIMG11](https://user-images.githubusercontent.com/13120265/66728480-d5620300-ee77-11e9-9de7-acc634a4156b.jpeg)

2.图片列表截图：

![WechatIMG12](https://user-images.githubusercontent.com/13120265/66728504-edd21d80-ee77-11e9-80de-3464e67ebaa7.jpeg)

3.预览截图：

![WechatIMG13](https://user-images.githubusercontent.com/13120265/66728505-f1fe3b00-ee77-11e9-9d85-0d4df0dd923a.jpeg)

4.图片列表截图：

![WechatIMG14](https://user-images.githubusercontent.com/13120265/66728507-f4f92b80-ee77-11e9-90ef-8c73fe7f8c0a.jpeg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
赞PR！👍
已合并，新版3.2.5
