### ISSUE TITLE
TZImagePickerController 提示Main Thread Checker

### ISSUE THREAD

**Issue by afxyubang** [banchichen/TZImagePickerController#1191]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.5

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：未改变

**bug内容描述**
present TZImagePickerController  以后，点击左上角的返回btn，会明显的卡顿一会，Xcode 控制台显示Main Thread Checker: UI API called on a background thread.

**我如何复现这个bug？**

**截图**

**其它说明**
TZImagePickerController.m 中修改730行的dispatch_get_global_quque(0,0) 为dispatch_get_main_quque即可解决

**Comment by banchichen** [comment]
你这个好像不是3.2.5，730行不是dispatch...
可以clone工程下载跑跑demo，demo我这是好的

**Comment by Cyandnow** [comment]
> 你这个好像不是3.2.5，730行不是dispatch...
> 可以clone工程下载跑跑demo，demo我这是好的

3.4.1 还是有这个问题的
line 758:     dispatch_async(dispatch_get_global_queue(0, 0), ^{
