### ISSUE TITLE
希望允许使用自定义的拍照和录视频界面

### ISSUE THREAD

**Issue by bluerainxty** [banchichen/TZImagePickerController#1193]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
老哥，来个PR

**Comment by banchichen** [comment]
如果产品允许，最好是在选择器外面拍照/录制，想微信一样，弹出个sheet
