### ISSUE TITLE
视频这块能否加入过滤时长区间的参数呢，比如只能看到大于5秒小于30秒的视频

### ISSUE THREAD

**Issue by sinsen** [banchichen/TZImagePickerController#1195]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
Q：设置可选视频的最大/最小时长？照片的最小/最大尺寸？不符合要求的不显示
A：可以的，参照Demo的isAssetCanSelect方法实现。我会返回asset出来，显示与否你来决定，注意这个是一个同步方法，对于需要根据asset去异步获取的信息如视频的大小、视频是否存在iCloud里来过滤的，无法做到。如果真要这样做，相册打开速度会变慢，你需要改我源码。
