### ISSUE TITLE
获取iCloud视频标识符失败

### ISSUE THREAD

**Issue by CliffVardant** [banchichen/TZImagePickerController#1196]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：YES

2、你用的是什么版本？升级到最新版后是否正常？
答：最新的demo

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：NO

**bug内容描述**

环境：Xcode 11.1，iOS 13.0
获取到的asset(来自iCloud) info中，不包含PHImageResultIsInCloudKey了
这就无法判断视频或图片是否来自iCloud了
现在的info是这样的
```
{
    PHImageResultIsDegradedKey = 1;
    PHImageResultRequestIDKey = 188;
}
```
请问这有解决办法吗

**Comment by banchichen** [comment]
PHImageResultIsDegradedKey是1说明这次是缩略图，第二次回调的时候有PHImageResultIsInCloudKey吗？

**Comment by CliffVardant** [comment]
> PHImageResultIsDegradedKey是1说明这次是缩略图，第二次回调的时候有PHImageResultIsInCloudKey吗？

感谢你的回复~
对于图片而言，第二次回调会有PHImageResultIsInCloudKey，
视频的话第二次回调是这样的
`{
    PHImageResultIsDegradedKey = 0;
    PHImageResultRequestIDKey = 813;
}`

**Comment by banchichen** [comment]
具体内容是系统API返回的，可能是获取图片/封面的targetSize不够大，本地存储的缩略图已满足，可以尝试调大targetSize...

强依赖这个值的话，可以调研下，主动再调用下其它系统API尝试获取
