### ISSUE TITLE
选择相册时候,在iOS13以上按返回键崩溃

### ISSUE THREAD

**Issue by lijiace** [banchichen/TZImagePickerController#1197]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by lijiace** [comment]
我已经

**Comment by lijiace** [comment]
问题已经解决是WR中没有适配ios13.修改WR即可.

**Comment by xt-input** [comment]
可以说具体一点解决方案吗？我也遇到了
 *** Assertion failure in -[TZImagePickerController _popNavigationBar:item:]

**Comment by xt-input** [comment]
navigationBar(_ navigationBar: UINavigationBar, shouldPop item: UINavigationItem)
调用popToViewController的问题

**Comment by MataHu** [comment]
> navigationBar(_ navigationBar: UINavigationBar, shouldPop item: UINavigationItem)
> 调用popToViewController的问题

请问解决了吗，我也遇到了，应该是库的问题呀

**Comment by MataHu** [comment]
> 问题已经解决是WR中没有适配ios13.修改WR即可.
请问需要怎样修改，遇到同样的问题。谢谢！

**Comment by MataHu** [comment]
> 问题已经解决是WR中没有适配ios13.修改WR即可.

请问需要怎样修改，遇到同样的问题。谢谢！

**Comment by lijiace** [comment]
https://github.com/wangrui460/WRNavigationBar/issues 里面就有ios 13返回崩溃.
