### ISSUE TITLE
iOS13 暗黑模式背景色变了

### ISSUE THREAD

**Issue by YinZhifu** [banchichen/TZImagePickerController#1198]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.5

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
切换到暗黑模式 背景色变了

**截图**

![B657095B6C25752B7C1202175EE4330D](https://user-images.githubusercontent.com/15342721/67185521-9a804200-f418-11e9-8def-00181618ec70.jpg)

**Comment by banchichen** [comment]
已修复，升级到3.2.6哈
