### ISSUE TITLE
导航栏往上偏移一个状态栏的高度

### ISSUE THREAD

**Issue by liya0412** [banchichen/TZImagePickerController#1199]
照片预览之后返回上个页面出现了这个问题。（PS：外部进入TZImagePickerController框架的页面是自定义的导航栏）

**Comment by banchichen** [comment]
更新到3.2.5哈

**Comment by liya0412** [comment]
好的，我后面更新到最新版后没问题！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 谭真 <notifications@github.com&gt;
发送时间: 2019年10月21日 20:33
收件人: banchichen/TZImagePickerController <TZImagePickerController@noreply.github.com&gt;
抄送: liya0412 <2320020257@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[banchichen/TZImagePickerController] 导航栏往上偏移一个状态栏的高度 (#1199)




更新到3.2.5哈
