### ISSUE TITLE
选择原图跟不选择原图有什么区别呢？assets这个数组里装着什么?

### ISSUE THREAD

**Issue by ClegeJJ** [banchichen/TZImagePickerController#12]
选择原图跟不选择原图有什么区别呢？assets这个数组里装着什么?

**Comment by banchichen** [comment]
你好，请参考TZImagePickerController的h文件: 
//  这个照片选择器不会自己dismiss，用户dismiss这个选择器的时候，会执行下面的handle
//  如果用户没有选择发送原图,第二个数组将是空数组
@property (nonatomic, copy) void (^didFinishPickingPhotosHandle)(NSArray<UIImage *> *photos,NSArray *assets);
@property (nonatomic, copy) void (^didFinishPickingPhotosWithInfosHandle)(NSArray<UIImage *> *photos,NSArray *assets,NSArray<NSDictionary *> *infos);

如果用户选择了原图，assets数组会不是空数组，如果没有选择原图，那这个数组是个空数组。
assets数组装着asset对象，iOS8以上是PHAsset对象，iOS8以下是ALAsset对象，每一个asset对象，对应一个照片/视频/音频资源。
参考TZImageManager的h文件的方法，可以用一个asset对象去获得一张照片。
我错了.... 我的TZImageManager，没有提供获得原图的接口，只有获得全屏图片的接口...待我有空更新一下吧。你急着用的话，你把TZImageManager类235行的那个方法自己复制粘贴一下，把242行的targetSize设置为PHImageManagerMaximumSize，然后把252-256行删掉，加一句imageRef = assetRep.fullResolutionImage;  这样设置后，就是获得原图，原图一般比较大，性能较差。

**Comment by banchichen** [comment]
同样，你也可以用代理方法，代理和Block实现一个就可以。详见TZImagePickerController和TZImageManager的h文件
