### ISSUE TITLE
确认和取消根据方法的返回值决定是否 dismiss

### ISSUE THREAD

**Issue by KanLei** [banchichen/TZImagePickerController#120]
1. 当前的确认和取消会自动 dimiss，希望能根据 finish 和 cancel 方法的返回值来决定是否 dismiss，我目前的需求是要在选择后 push 一个新的 ViewController
2. 希望增加 takeVideo.png，takeAll.png，根据用户选项配置，设置对应的图片

**Comment by banchichen** [comment]
谢谢建议，新的代码中已经加入了相关属性~
