### ISSUE TITLE
关于scaleAspectFillCrop的问题

### ISSUE THREAD

**Issue by afskalsfk** [banchichen/TZImagePickerController#1200]
scaleAspectFillCrop设置为yes时 不能单纯的根据图片的大小，应该根据图片的宽高比，和剪切区域的宽高比进行计算，否则一张宽2000 高800的图在手机上只在中间部分展示，但是在剪切区域为300*300的时候还是会出现剪切区域超出图片范围， 图片没有自动放大，，，因为图片宽高已经大于300.。。希望核查一下

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by banchichen** [comment]
hi，抱歉回复晚了。。。

我造了一个2000x800的图，设置了300x300的裁剪区域，试了下Demo是正常的：
![image](https://user-images.githubusercontent.com/12755494/95757410-b049df80-0cd9-11eb-804e-e02ddd6d8287.png)

要不你再试下？如有问题请发一下对Demo的改动哈

**Comment by banchichen** [comment]
我用的是这个图片：https://gw.alicdn.com/tfs/TB1K73Nok9l0K4jSZFKXXXFjpXa-2000-800.png
对Demo仅改动了这一行：
![image](https://user-images.githubusercontent.com/12755494/95757588-e9824f80-0cd9-11eb-982e-3b9e5c5c824a.png)
