### ISSUE TITLE
修改导航栏不起作用

### ISSUE THREAD

**Issue by 624990742** [banchichen/TZImagePickerController#1201]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
修改什么属性，怎么修改的，demo是否正常？

**Comment by 624990742** [comment]
demo可以正常运行，demo中默认预览照片是黑色导航栏。我是想修改导航栏背景色为白色，字体颜色也想好修改。但是使用了框架中提空的属性不起作用。
        TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithSelectedAssets:_selectedAssets selectedPhotos:_selectedPhotos index:indexPath.item];
          imagePickerVc.naviBgColor = [UIColor whiteColor];
            imagePickerVc.naviTitleColor = [UIColor whiteColor];

**Comment by banchichen** [comment]
demo里属性是正常工作的，对比下demo吧
![image](https://user-images.githubusercontent.com/12755494/67649054-7a013c00-f972-11e9-85ba-bd5bb2923c4f.png)
