### ISSUE TITLE
图片裁剪出来图片很模糊，需要哪里设置还是以各问题

### ISSUE THREAD

**Issue by Yangxuefei** [banchichen/TZImagePickerController#1202]

**Comment by banchichen** [comment]
不模糊吧，裁剪框如果是300x300那返回的图片就是300x300，你若放大查看才会模糊

**Comment by Yangxuefei** [comment]
就是一个方形剪裁框，以屏幕宽为宽高。出来的图片有点失真，小图还好，预览起来小字就有点模糊那种感觉


发自我的 iPhone

**Comment by banchichen** [comment]
如果屏幕宽375，那么拿到的图片就是375x375，不放大看应该不模糊哈

相关代码在 TZImageCropManager里，可以去看一下，如有可优化点，欢迎提PR哈
