### ISSUE TITLE
pod 'MLeaksFinder'  发现循环引用，没有被安全释放

### ISSUE THREAD

**Issue by 295060456** [banchichen/TZImagePickerController#1203]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
有

2、你用的是什么版本？升级到最新版后是否正常？
目前使用的是 3.2.3（目前最新版），还有问题
3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**
pod 'MLeaksFinder' 
检测出未被释放。

**截图**
安装了自己就出现

block 没有做修饰
@ weakify（self）
@ strongify（self）

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/214

**Comment by 295060456** [comment]
我用的懒加载进行加载；
@property(nonatomic,strong)TZImagePickerController *imagePickerVC;

-(void)upLoadBtnClickEvent:(UIButton *)sender{
    NSLog(@"上传二维码");
    @weakify(self)
    [ECAuthorizationTools checkAndRequestAccessForType:ECPrivacyType_Photos
                                          accessStatus:^(ECAuthorizationStatus status,
                                                         ECPrivacyType type) {
        @strongify(self)
        // status 即为权限状态，
        //状态类型参考：ECAuthorizationStatus
        NSLog(@"%lu",(unsigned long)status);
        if (status == ECAuthorizationStatus_Authorized) {
            [self presentViewController:self_weak_.imagePickerVC
                               animated:YES
                             completion:nil];
        }else{
            NSLog(@"相册不可用:%lu",(unsigned long)status);
            [self showAlertViewTitle:@"获取相册权限"
                             message:@""
                         btnTitleArr:@[@"去获取"]
                      alertBtnAction:@[@"pushToSysConfig"]];
        }
    }];
}

如果这个地方写成self，不弱化，那么MLeaksFinder 会给弹窗警告说没被释放。
在TZImagePickerController里面，很多block都没有进行@weakify(self)、@strongify(self)弱化处理
得到的结果比之前的好。

**Comment by banchichen** [comment]
你可以对比下demo，demo是正常的

你这里imagePickerVC是strong，被当前页面强引用了，退出选择器时自然不会释放，然后MLeaksFinder给弹窗
可参考demo的做法，不要作为属性，选一次创建一次

**Comment by 295060456** [comment]
谢谢，我把属性weak就OK啦。
我习惯lazyload，这样模块化，方便查问题。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 谭真 <notifications@github.com&gt;
发送时间: 2019年10月29日 10:15
收件人: banchichen/TZImagePickerController <TZImagePickerController@noreply.github.com&gt;
抄送: Whiskey_On_The_Rocks <295060456@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[banchichen/TZImagePickerController] pod 'MLeaksFinder'  发现循环引用，没有被安全释放 (#1203)




你可以对比下demo，demo是正常的

你这里imagePickerVC是strong，被当前页面强引用了，退出选择器时自然不会释放，然后MLeaksFinder给弹窗
可参考demo的做法，不要作为属性，选一次创建一次
