### ISSUE TITLE
获取相册图片的URL？

### ISSUE THREAD

**Issue by Goallying** [banchichen/TZImagePickerController#1204]
怎么获取获取相册图片的URL？

**Comment by banchichen** [comment]
Q：有的图片info里没有PHImageFileURLKey？
A：不要去拿PHImageFileURLKey，没用的，只有通过Photos框架才能访问相册照片，光拿一个路径没用。
如果需要通过路径上传照片，请先把UIImage保存到沙盒，用沙盒路径。
如果你上传照片需要一个名字参数，请参考Demo直接用照片名字。
