### ISSUE TITLE
返回到相册列表之后，标题栏的标题和取消按钮消失

### ISSUE THREAD

**Issue by nmg1986** [banchichen/TZImagePickerController#1206]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：demo没问题，升级到最新版依然有问题

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.3

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
返回到相册列表时，导航栏的标题和取消按钮消失

**我如何复现这个bug？**
打开后按返回，返回到相册列表

**截图**
![image](https://user-images.githubusercontent.com/3889089/67764047-fcc5ec00-fa83-11e9-8702-a2eb7a08a8ea.png)
![image](https://user-images.githubusercontent.com/3889089/67764085-1bc47e00-fa84-11e9-9f8f-4fecbacb5440.png)

点击第一张图的返回按钮返回到第二张图之后，标题栏的标题和取消按钮消失

**其它说明**
初始化代码：
```
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:9 delegate:self];
    imagePickerVc.allowTakeVideo = NO;
    imagePickerVc.allowTakePicture = NO;
    imagePickerVc.allowPickingVideo = YES;
    imagePickerVc.allowPickingImage = YES;
    [self presentViewController:imagePickerVc animated:YES completion:nil];
```

**Comment by banchichen** [comment]
用最新版3.2.6
