### ISSUE TITLE
manager.cachingImageManager.allowsCachingHighQualityImages = NO; 漰溃

### ISSUE THREAD

**Issue by difoi** [banchichen/TZImagePickerController#121]
manager.cachingImageManager.allowsCachingHighQualityImages = NO;

ios8系统 在关闭相册权限的情况,打开,会出现漰溃; 
在生产环境下发现的BUG;
目前解决办法  allowsCachingHighQualityImages = YES; 或注释

**Comment by difoi** [comment]
希望作者尽快处理;

**Comment by banchichen** [comment]
谢谢反馈，已经纠正...
