### ISSUE TITLE
请教一个使用方面的问题

### ISSUE THREAD

**Issue by 624990742** [banchichen/TZImagePickerController#1210]
你好我想实现类似于微信朋友圈选择照片的功能，假如限制4张，我已经选择了两张，我到相册中还想选择已经选过的那两张(就是可以重复选择相同的照片)，，请问有相应的属性或者方法吗？

**Comment by banchichen** [comment]
再次选择的时候，不设置selectedAssets

如果是懒加载，再次选择的时候就清空下selectedAssets

这样选择器就不知道你选择过哪些图片，从而所有图片都可以选择
