### ISSUE TITLE
希望支持暗黑模式

### ISSUE THREAD

**Issue by PlacidoLv** [banchichen/TZImagePickerController#1212]
**问：你希望加什么新功能？**
答：希望支持暗黑模式

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：暂无

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是

**其它你希望补充的内容**

**Comment by Jacky-LinPeng** [comment]
同求+1

**Comment by banchichen** [comment]
已支持哈，新版本：3.4.3
