### ISSUE TITLE
播放视频时在 13.0 系统的新 present 模式下，状态栏消失

### ISSUE THREAD

**Issue by Charlin0701** [banchichen/TZImagePickerController#1214]
作者在播放视频时会隐藏状态栏，在暂停时恢复显示，但是在 iOS13.0 以上系统，使用系统新的 present 模式播放视频时使用下拉手势 dismiss 控制器时，消失的状态栏不能正常显示出来

**Comment by banchichen** [comment]
demo正常吗？

**Comment by banchichen** [comment]
我试了demo正常的，你试试更新到最新版吧

**Comment by Charlin0701** [comment]
很感谢您回复了我的问题，我尝试了一下 demo，demo 正常是因为预览视频时，present 模式是 UIModelPresentationFullScreen，如果您在 13.0 系统使用系统默认的模式，播放视频时，下滑手势 dismiss 控制器便会出现状态栏未恢复问题，请您注释“vc.modalPresentationStyle = UIModalPresentationFullScreen;”再尝试一下，谢谢
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "谭真"<notifications@github.com&gt;; 
发送时间: 2019年11月12日(星期二) 中午11:03
收件人: "banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;; 
抄送: "2more丶默言"<834991084@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [banchichen/TZImagePickerController] 播放视频时在 13.0 系统的新 present 模式下，状态栏消失 (#1214)




我试了demo正常的，你试试更新到最新版吧

**Comment by banchichen** [comment]
复现了，确实...

3.2.7版本修复了，更新下哈

**Comment by Charlin0701** [comment]
好的，非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "谭真"<notifications@github.com&gt;; 
发送时间: 2019年11月12日(星期二) 下午3:10
收件人: "banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;; 
抄送: "2more丶默言"<834991084@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [banchichen/TZImagePickerController] 播放视频时在 13.0 系统的新 present 模式下，状态栏消失 (#1214)




复现了，确实...
 
3.2.7版本修复了，更新下哈
