### ISSUE TITLE
iOS 13 ，导航栏背景颜色是白色，TZAlbumPickerController的rightBarButtonItem也是白色了，导致rightBarButtonItem看不到，iOS13以下的系统没事

### ISSUE THREAD

**Issue by NTT0302** [banchichen/TZImagePickerController#1215]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
demo是正常的，对比下

**Comment by banchichen** [comment]
可以升级到最新版本试试
