### ISSUE TITLE
能不能增加类似于微博图片选择界面的功能？

### ISSUE THREAD

**Issue by zhangqi02060227m** [banchichen/TZImagePickerController#1216]
**问：你希望加什么新功能？**
答：能不能增加类似于微博图片选择界面的功能？你这个TZImagePickerController样式不是我需要的样式，我想实现类似于微博那样的图片选择。
![IMG_2387](https://user-images.githubusercontent.com/16876013/68354188-a2ddba00-0146-11ea-98d9-d8ec4dbf71b7.PNG)

**Comment by banchichen** [comment]
这个不支持...
