### ISSUE TITLE
不应该在判断代理方法的时候强行解包

### ISSUE THREAD

**Issue by JonHome** [banchichen/TZImagePickerController#1218]
func callDelegateMethod() {
        if (self.pickerDelegate?.responds(to: #selector(self.pickerDelegate?.tz_imagePickerControllerDidCancel(_:))))! {
            self.pickerDelegate?.tz_imagePickerControllerDidCancel!(self)
        }
        if self.imagePickerControllerDidCancelHandle != nil {
            self.imagePickerControllerDidCancelHandle?()
        }
    }

这种方式会造成崩溃

**Comment by banchichen** [comment]
你这是swift版的？
swift版地址是这个：https://github.com/tanhuang/TZImagePickerControllerSwift ，维护不太及时，建议使用OC版哈
