### ISSUE TITLE
View controller-based status bar appearance 为YES时，弹出的图片选择器状态永远是白色的

### ISSUE THREAD

**Issue by jiuyuehuiyi** [banchichen/TZImagePickerController#1221]
**bug内容描述**
如果是基于控制器管理状态栏的, 即View controller-based status bar appearance设为YES时，statusBarStyle设置是失效的

**其它说明**
另外iOS13的darkMode的modalPresentationStyle希望也能在TZImagePickerController类中添加一个属性进行控制

**Comment by banchichen** [comment]
View controller-based status bar appearance设为YES时，参考demo实现preferredStatusBarStyle来设置状态栏

库内部没有present，你是指present出来TZImagePickerController吧，这个你的页面里设置就行了，参考Demo工程的ViewController.m

**Comment by jiuyuehuiyi** [comment]
我看示例demo中的弹出TZImagePickerController的控制器中也并没有重写preferredStatusBarStyle，只是在库内部的图片选择控制器中重写了preferredStatusBarStyle， 我现在碰到的问题是，如果当前控制器导航栏是dark模式的， present出来的TZImagePickerController的导航栏也是dark模式

**Comment by jiuyuehuiyi** [comment]
我把imagePickerVc.modalPresentationStyle = .fullScreen
手误写成了imagePickerVc.modalPresentationStyle = .overFullScreen，
写了两个demo工程发现OC正常， swift异常， 逐行对比代码发现😢

**Comment by banchichen** [comment]
好吧，这个是OC的哈，swift的issue可以提在   https://github.com/tanhuang/TZImagePickerControllerSwift 里哈
