### ISSUE TITLE
在支持选择多张图片的时候，可以支持重复选择同步一张图片吗？

### ISSUE THREAD

**Issue by 624990742** [banchichen/TZImagePickerController#1222]
您好，我现在在使用您的框架的时候遇到一个情况，就以微信发发布说说为例，假如我限制最大张数为4张，我从相册中先是选择了2张照片，返到了发布界面，然后我再次打开相册想选择之前已经选择过的那2张照片，我应该怎样去处理呢？

**Comment by banchichen** [comment]
selectedAssets不传就行，就允许选取所有图片了

**Comment by 624990742** [comment]
好的谢谢
