### ISSUE TITLE
网络请求回来的图片怎么和相册中的图片进行比较呢？

### ISSUE THREAD

**Issue by 624990742** [banchichen/TZImagePickerController#1223]
您好，我在使用过程中遇到这样一个问题，希望能得到您的帮助。我限制最大显示图片的数量为4张，默认显示了2张（这2张是网络请求回来的图片但是相册中也存在这2张图片），我想在打开相册选择剩余的2张图片时，将默认显示的2张图片标注为已经选择过，我应该怎么对框架做处理去实现这样的功能呢？

**Comment by banchichen** [comment]
换个需求不好做，可能引发别的问题，建议拒绝掉

实在要做的话，网络图片需要存储PHAsset的localIdentifier，localIdentifier对应唯一一个照片资源，有了localIdentifier后，通过PHAsset的这个方法
```objectivec
+ (PHFetchResult<PHAsset *> *)fetchAssetsWithLocalIdentifiers:(NSArray<NSString *> *)identifiers options:(nullable PHFetchOptions *)options; 
```
可以拿到PHAsset对象，然后添加到selectedAssets里传给TZImagePickerController，这几个图片就选中了

但是会有一些特殊case要多测测，比如照片被编辑了、删除了、隐藏了等等

至于这个localIdentifier怎么存起来，可以试试：
1、上传图片的时候，把localIdentifier作为照片名字传给服务端，到时候截取url的最后一段就能拿到localIdentifier？
2、把localIdentifier写到图片的exif里？

**Comment by 624990742** [comment]
好的，谢谢
