### ISSUE TITLE
相册中右上角提示标识不显示

### ISSUE THREAD

**Issue by 624990742** [banchichen/TZImagePickerController#1224]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答： version 3.2.5

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

相册中右上角提示标识不显示

**我如何复现这个bug？**
在demo的基础上限制图片张数改为4张，然后先打开相册选择3张图片（此时相册照片右上角的提示图标是在的），点击确定后返回展示界面，然后在点击“+”添加图片，此时选择第4张照片的时候，又上角图标不见了，而且点击直接到预览界面了。

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
你在我的demo基础上改了什么吧，我这里看是OK的...
