### ISSUE TITLE
直接运行demo是没问题的，但是放到自己的项目中，滑动页面的时候崩溃在如下代码中了（iOS13以上的真机，模拟器是没问题的）。弹出选择图片控制器的时候，控制台会打印这个信息（"Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""）不知道怎么解决

### ISSUE THREAD

**Issue by JokesWB** [banchichen/TZImagePickerController#1227]
`// 修复获取图片时出现的瞬间内存过高问题
    // 下面两行代码，来自hsjcom，他的github是：https://github.com/hsjcom 表示感谢
    PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
    option.resizeMode = PHImageRequestOptionsResizeModeFast;
    int32_t imageRequestID = [[PHImageManager defaultManager] requestImageForAsset:asset targetSize:imageSize contentMode:PHImageContentModeAspectFill options:option resultHandler:^(UIImage *result, NSDictionary *info) {
        if (result) {
            image = result;
        }`

**Comment by banchichen** [comment]
尽量在我的demo里复现，逐步导入你项目的依赖的pod或者对全局有影响的类再试，定位到具体哪个pod库或类影响了

**Comment by FelixYue** [comment]
同遇到。。。

**Comment by banchichen** [comment]
@FelixYue 你们可以加下readme里的QQ群沟通下，排查共同依赖的那些库

**Comment by FTyouth** [comment]
> 同遇到。。。

解决了么 我这也遇到了

**Comment by FTyouth** [comment]
> `// 修复获取图片时出现的瞬间内存过高问题 // 下面两行代码，来自hsjcom，他的github是：https://github.com/hsjcom 表示感谢 PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init]; option.resizeMode = PHImageRequestOptionsResizeModeFast; int32_t imageRequestID = [[PHImageManager defaultManager] requestImageForAsset:asset targetSize:imageSize contentMode:PHImageContentModeAspectFill options:option resultHandler:^(UIImage *result, NSDictionary *info) { if (result) { image = result; }`

问题解决了么 同样的问题遇到了

**Comment by JokesWB** [comment]
可能是因为内存过大吧，我没有解决，用的系统的选取图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"FTyouth"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 下午5:50
收件人:&nbsp;"banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;;
抄送:&nbsp;"风"<1510254832@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [banchichen/TZImagePickerController] 直接运行demo是没问题的，但是放到自己的项目中，滑动页面的时候崩溃在如下代码中了（iOS13以上的真机，模拟器是没问题的）。弹出选择图片控制器的时候，控制台会打印这个信息（"Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""）不知道怎么解决 (#1227)



 
同遇到。。。
  
解决了么 我这也遇到了

**Comment by FTyouth** [comment]
> 可能是因为内存过大吧，我没有解决，用的系统的选取图片
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"FTyouth"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月9日(星期一) 下午5:50 收件人:&nbsp;"banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;; 抄送:&nbsp;"风"<1510254832@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [banchichen/TZImagePickerController] 直接运行demo是没问题的，但是放到自己的项目中，滑动页面的时候崩溃在如下代码中了（iOS13以上的真机，模拟器是没问题的）。弹出选择图片控制器的时候，控制台会打印这个信息（"Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""）不知道怎么解决 (#1227) 同遇到。。。 解决了么 我这也遇到了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯 好的 谢谢

**Comment by JokesWB** [comment]
如果你解决了，希望说一下，谢谢哦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"FTyouth"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 下午5:53
收件人:&nbsp;"banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;;
抄送:&nbsp;"风"<1510254832@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [banchichen/TZImagePickerController] 直接运行demo是没问题的，但是放到自己的项目中，滑动页面的时候崩溃在如下代码中了（iOS13以上的真机，模拟器是没问题的）。弹出选择图片控制器的时候，控制台会打印这个信息（"Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""）不知道怎么解决 (#1227)



 
可能是因为内存过大吧，我没有解决，用的系统的选取图片
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"FTyouth"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月9日(星期一) 下午5:50 收件人:&nbsp;"banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;; 抄送:&nbsp;"风"<1510254832@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [banchichen/TZImagePickerController] 直接运行demo是没问题的，但是放到自己的项目中，滑动页面的时候崩溃在如下代码中了（iOS13以上的真机，模拟器是没问题的）。弹出选择图片控制器的时候，控制台会打印这个信息（"Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""）不知道怎么解决 (#1227) 同遇到。。。 解决了么 我这也遇到了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
嗯 好的 谢谢

**Comment by FTyouth** [comment]
> 如果你解决了，希望说一下，谢谢哦
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"FTyouth"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月9日(星期一) 下午5:53 收件人:&nbsp;"banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;; 抄送:&nbsp;"风"<1510254832@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [banchichen/TZImagePickerController] 直接运行demo是没问题的，但是放到自己的项目中，滑动页面的时候崩溃在如下代码中了（iOS13以上的真机，模拟器是没问题的）。弹出选择图片控制器的时候，控制台会打印这个信息（"Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""）不知道怎么解决 (#1227) 可能是因为内存过大吧，我没有解决，用的系统的选取图片 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"FTyouth"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月9日(星期一) 下午5:50 收件人:&nbsp;"banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;; 抄送:&nbsp;"风"<1510254832@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [banchichen/TZImagePickerController] 直接运行demo是没问题的，但是放到自己的项目中，滑动页面的时候崩溃在如下代码中了（iOS13以上的真机，模拟器是没问题的）。弹出选择图片控制器的时候，控制台会打印这个信息（"Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""）不知道怎么解决 (#1227) 同遇到。。。 解决了么 我这也遇到了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 嗯 好的 谢谢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
好的
