### ISSUE TITLE
从iCloud同步照片失败！

### ISSUE THREAD

**Issue by guichuan95** [banchichen/TZImagePickerController#1228]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：就是新Demo 

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否，直接运行的Demo

**bug内容描述**

[Generic] Failed to load image data for asset <PHAsset: 0x125e81170> 50234CFD-7367-4B25-BAA3-B42A3A96FC2D/L0/001 mediaType=1/0, sourceType=1, (590x442), creationDate=2018-10-19 11:05:17 +0000, location=0, hidden=0, favorite=0  with format 9999

**我如何复现这个bug？**
从真机相册中选择照片，照片是iCloud端的

**截图**
![image](https://user-images.githubusercontent.com/35914513/68990454-1b065700-088e-11ea-8cbe-4cde7a914e65.png)

![image](https://user-images.githubusercontent.com/35914513/68990474-7fc1b180-088e-11ea-9983-c48ef114c08a.png)
**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
NO

**Comment by banchichen** [comment]
这个日志倒不重要，如果当前网络是4G，查下手机的设置是否允许4G下同步iCloud，然后当前的网络是否正常
同步iCloud是走的系统方法，debug看下这个方法的返回，代码里搜索iCloud可以定位到具体的方法
