### ISSUE TITLE
您好，发现了一个Bug

### ISSUE THREAD

**Issue by karmaios** [banchichen/TZImagePickerController#123]
如图1：图片选择的的时候，有时候可以重复选择1张图片(9张相同的)，有时候已经没有打勾的对象了，下面的计数还有显示。
如图2：当选择了重复照片的时候，选择其中一种进入预览模式
如图3：当取消勾，在点确定的时候会crash
![img_3524](https://cloud.githubusercontent.com/assets/11553684/16642115/1bbfeb32-443a-11e6-8ec3-297e087254e2.PNG)
![img_3525](https://cloud.githubusercontent.com/assets/11553684/16642116/1c41924a-443a-11e6-8885-31fdd18c753b.PNG)
![img_3526](https://cloud.githubusercontent.com/assets/11553684/16642117/1c4d4f2c-443a-11e6-9df8-6965d4688573.PNG)

**Comment by banchichen** [comment]
你好，现在已经修复了，你再试试~  这个是前面几天的代码中出现的bug...
