### ISSUE TITLE
裁剪之后的白色背景问题

### ISSUE THREAD

**Issue by friendsheeps** [banchichen/TZImagePickerController#1230]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.7，不正常

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**

采用矩形裁剪框并将scaleAspectFillCrop设置为NO，裁剪完之后黑色部分在生成图片后背景变为白色，现在希望它继续是黑色或者透明色。

**截图**
![Simulator Screen Shot - iPhone Xʀ - 2019-11-18 at 15 16 47](https://user-images.githubusercontent.com/13128046/69032215-ed004e80-0a16-11ea-91cc-30f9c8d7c30b.png)
 
![Simulator Screen Shot - iPhone Xʀ - 2019-11-18 at 15 22 26](https://user-images.githubusercontent.com/13128046/69032459-731c9500-0a17-11ea-8f94-44ae8df0a118.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
那个是TZTestCell的背景色，你改下
