### ISSUE TITLE
相册选择多个视频时，有时会导出失败

### ISSUE THREAD

**Issue by Best11111111111** [banchichen/TZImagePickerController#1232]
相册选择多个视频时，有时会导出失败

**Comment by Best11111111111** [comment]
![image](https://user-images.githubusercontent.com/19279494/69228322-52db0a80-0bbe-11ea-99a0-8938be171846.png)
试了下demo也是有这个问题，版本是3.2.7

**Comment by cnjsyyb** [comment]
allowPickingMultipleVideo为true 视频多选确实有时会导出失败,icloud 视频无网情况下选择保存

**Comment by banchichen** [comment]
3.5.3已修复哈
