### ISSUE TITLE
本地图片无法显示

### ISSUE THREAD

**Issue by Yanhao-yu** [banchichen/TZImagePickerController#1233]
![2FC1F91C4AE9222E12F4B9C956C55DE8](https://user-images.githubusercontent.com/40618149/69626472-aef0d380-1083-11ea-9b9e-19311ab1abb8.png)

Demo 运行在手机上可以显示,  创建一个新项目之后也可以使用, 但是在旧项目中不出现上面图片无法显示的情况, 请问什么原因可能导致图中的问题 ?

**Comment by banchichen** [comment]
不好说，估计是啥库或hook影响了

可以在新项目了，逐步引入旧项目的库，看看什么时候出问题来定位原因
