### ISSUE TITLE
initWithMaxImagesCount:1  照片不可选

### ISSUE THREAD

**Issue by liudan550** [banchichen/TZImagePickerController#1235]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：最新demo

2、你用的是什么版本？升级到最新版后是否正常？
答：version 3.2.7,依然存在

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：未改动

**bug内容描述**
照片最大张数选择1的时候，进入相册都不可选

**我如何复现这个bug？**
照片最大张数设置成一

**截图**
<img width="337" alt="屏幕快照 2019-11-27 上午10 43 31" src="https://user-images.githubusercontent.com/22020865/69689044-d3d85b80-1102-11ea-92e4-496219577148.png">
<img width="347" alt="屏幕快照 2019-11-27 上午10 43 35" src="https://user-images.githubusercontent.com/22020865/69689059-df2b8700-1102-11ea-968d-f6ef5ef5a10f.png">

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
单选默认不显示选中按钮，需要的话，设置下showSelectBtn为YES
