### ISSUE TITLE
iPad iOS 13.2.3 从相册选择照片 模糊

### ISSUE THREAD

**Issue by RookiePyl** [banchichen/TZImagePickerController#1237]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有。

2、你用的是什么版本？升级到最新版后是否正常？
答：pod管理的。pod 'TZImagePickerController' ，下载github上的也有该问题。

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否。

**bug内容描述**
设备 iPad mini4， 版本 iOS 13.2.3,   选择相册照片 预览是模糊的。

**我如何复现这个bug？**
重复描述内容即可。 感谢您抽空回复 ^_^

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
参考头文件的说明，调大下photoWidth的值
