### ISSUE TITLE
优化建议(部分情况或导致图片无法显示)

### ISSUE THREAD

**Issue by Yanhao-yu** [banchichen/TZImagePickerController#1240]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：
说有或者没有好像都能说通
2、你用的是什么版本？升级到最新版后是否正常？
答：
最新
3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：
没有
**bug内容描述**
部分情况会出现图片无法显示的情况

**我如何复现这个bug？**
未知, 不清楚 bug 出现的原因

**截图**
现象：
![2FC1F91C4AE9222E12F4B9C956C55DE8](https://user-images.githubusercontent.com/40618149/69851679-337a6680-12bd-11ea-8fd9-86f2e717e00e.png)

原因：
 ![2B515275-86B9-4B62-AA65-F70E3B1285DF](https://user-images.githubusercontent.com/40618149/69850835-2b212c00-12bb-11ea-849e-30432782e9dd.png)

在 TZImageManager 这个类中, 如图所示, 代码判断是否把图片资源回调显示是根据 downloadFinined (是否下载完毕) 和 result (图片资源) 两个参数控制的, 而根据控制栏的打印情况可以知道,  result 是存在的, downloadFinined 则显示未完成, 由此导致图片无法回调显示。根据代码, downloadFinined 由 info 中的两个字段决定, 当 PHImageCancelledKey(取消) 和 PHImageErrorKey(报错)时, downloadFinined 未完成。而根据 info 的打印结果来看, PHImageErrorKey 仍旧是空的, 只是数据类型变成了 NSNULL 类型, 由此导致 downloadFinined 判断不正确。此种情况应该按图中注释代码对判断条件进行扩展, 将 PHImageErrorKey 为 NSNULL 这种情况排除。

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
补充：这种本地图片无法显示的情况出现的很偶然，虽然自己解决了，但我也不知道为什么会出现，所以对作者来说想复现的话不容易。a、运行demo没问题，b、创建新项目使用没问题，c、项目运行在iPhone6sp上也没有问题（有问题的是XS）d、把项目所有代码全部删掉，只保留项目中所有使用的第三方时，运行在XS上也没出现这种问题。综上，我也是一头雾水。（由于最初以为是iOS系统问题、项目配置问题、或者别的第三方工具类影响问题等卡了我两三天，今天下午看源码实现方式，才发现了这个原因，汗颜😓）

**Comment by LT-LittleFish** [comment]
1. 有
2. 3.2.7 -》3.2.8（更新后仍出现此类问题）
3. 没有改动
最近我这边使用时也出现了这样的情况，iphone 11，一个照片夹下的部分图片未能显示，进入图片预览后再返回后不显示的图片会显示出来

**Comment by banchichen** [comment]
已优化，新版本3.3.0哈
