### ISSUE TITLE
导航栏一片空白，按钮都看不见，什么都看不见

### ISSUE THREAD

**Issue by iOSSer** [banchichen/TZImagePickerController#1241]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：新版

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没

**bug内容描述**
如题

**我如何复现这个bug？**
    TZImagePickerController *imagePicker = [[TZImagePickerController alloc] initWithMaxImagesCount:maxImagesCount delegate:self];
//    imagePicker.naviBgColor = [UIColor blackColor];
    imagePicker.naviTitleColor = [UIColor redColor];
    imagePicker.allowPickingVideo = NO;
    imagePicker.allowPickingGif = NO;
    imagePicker.showSelectedIndex = YES;
    [self.navigationController presentViewController:imagePicker animated:YES completion:nil];

**截图**

![Simulator Screen Shot - iPhone 8 Plus - 2019-11-30 at 15 26 54](https://user-images.githubusercontent.com/3730100/69897381-49079300-1386-11ea-9789-2776d0fad6b0.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by iOSSer** [comment]
而且根本无法显示√勾选按钮，MaxImagesCount 设置了的，这怎么回事？
pod "TZImagePickerController",'~> 3.2.7'

**Comment by banchichen** [comment]
和demo对比下，demo正常的....

**Comment by iOSSer** [comment]
设置颜色根本无反应：

    imagePicker.navigationBar.barStyle = UIBarStyleDefault;
    imagePicker.navigationBar.tintColor = [UIColor blackColor];
    [self presentViewController:imagePicker animated:YES completion:nil];

    imagePicker.view.backgroundColor = [UIColor orangeColor];
    imagePicker.navigationBar.barTintColor = [UIColor orangeColor];
    imagePicker.navigationBar.tintColor = [UIColor redColor];

**Comment by Arvind-qrj** [comment]
一样碰到这个问题.导航栏按钮存在,可以点击,但是看不见,iOS13,12都有这个问题.
颜色设置不生效.

**Comment by banchichen** [comment]
可以参考下：https://github.com/banchichen/TZImagePickerController/issues/1226
