### ISSUE TITLE
TZImagePickerController、TZPhotoPreviewController等控制器背景色的如何修改

### ISSUE THREAD

**Issue by jiasongs** [banchichen/TZImagePickerController#1242]
**问：你希望加什么新功能？**
答：能够暴露修改TZImagePickerController、TZPhotoPreviewController等控制器背景色的接口，否则在暗黑模式下设置navBarStyle为UIBarStyleBlack时，导航栏的高斯模糊是有点问题的。
非正常情况下：（TZPhotoPickerController无法设置背景色）
<img width="373" alt="图片" src="https://user-images.githubusercontent.com/22904757/69930207-3b284e00-14fd-11ea-8064-e1e234685d0c.png">
正常情况下：（设置了TZAlbumPickerController的背景色）
<img width="377" alt="图片" src="https://user-images.githubusercontent.com/22904757/69930243-775bae80-14fd-11ea-89ec-7a37a2913b4e.png">

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合

**Comment by banchichen** [comment]
参考demo哈，导航栏背景色在外面可以直接设置的：
![image](https://user-images.githubusercontent.com/12755494/73521577-56ea9a80-4441-11ea-80e9-3f98a3f91f24.png)
