### ISSUE TITLE
iPad 上选取的图片大小被压缩，不是高清原图！

### ISSUE THREAD

**Issue by iOSSer** [banchichen/TZImagePickerController#1243]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
在 iPad 模拟器上测试，选取的图片并不是原图，大小都被压缩了。

**我如何复现这个bug？**
可有方式获取原图图？
或者说这个框架只适合 iPhone 使用？

**截图**

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-12-03 at 16 04 58](https://user-images.githubusercontent.com/3730100/70031767-efea6a00-15e6-11ea-829a-55e88c9ad0f5.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
// 这个照片选择器会自己dismiss，当选择器dismiss的时候，会执行下面的代理方法
// 你也可以设置autoDismiss属性为NO，选择器就不会自己dismis了
// 如果isSelectOriginalPhoto为YES，表明用户选择了原图
// 你可以通过一个asset获得原图，通过这个方法：[[TZImageManager manager] getOriginalPhotoWithAsset:completion:]
// photos数组里的UIImage对象，默认是828像素宽，你可以通过设置photoWidth属性的值来改变它
- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray<UIImage *> *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto;
