### ISSUE TITLE
部分机型没有返回原图

### ISSUE THREAD

**Issue by qwopczy** [banchichen/TZImagePickerController#1244]
使用 getOriginalPhotoDataWithAsset 获取到二进制NSData *imageData 数据，计算图片数据大小 float length1 = [imageData length] / 1024.0 /1024.0，发现在 iPhone8plus XR 几个机型上拍完照从相册选照片， 获取的不是原图，比如原图有5MB 左右 但获取的数据只有1MB多。在 iPhone 6 ，6 plus，5s,6s上同样试了又是原图。现在业务上一定要我上传原始图片数据

**Comment by banchichen** [comment]
要不试试getOriginalPhotoWithAsset？
拿到的图片再UIImageJPEGRepresentation(image, 0.9)或UIImageJPEGRepresentation(image, 1.0)一下

**Comment by qwopczy** [comment]
破案了 。。。测试那边说8，8p,XR上传的图片很小，被压缩了的原因是因为：iPhone 7及其后硬件，在iOS 11更新后，拍摄照片时的默认图像存储格式是HEIC。Heic是Apple的IOS 11系统中的HEVC和HEIF取代原始视频和照片的H.264和JEP格式。 这种方法不仅可以节省内存，还可以保留原始图像质量。其实是原图，只是该格式占用更下的内存空间。

**Comment by banchichen** [comment]
👍
