### ISSUE TITLE
视频预览返回按钮颜色

### ISSUE THREAD

**Issue by BestKai** [banchichen/TZImagePickerController#1246]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：同样存在

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.8

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
视频预览,当设置导航栏背景色为白色,导航栏文字颜色为黑色的时候,返回按钮 文字为黑色,图片为白色.demo也可以复现这个bug

**我如何复现这个bug？**

**截图**

![WechatIMG42](https://user-images.githubusercontent.com/8436462/70534631-66aed680-1b96-11ea-86c5-bf460e0e6046.jpeg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
那个颜色，是navigationBar的tintColor决定的，这样设置下：
```objectivec
    imagePickerVc.navigationBar.tintColor = [UIColor blackColor];
```
