### ISSUE TITLE
可以直接调用录制视频

### ISSUE THREAD

**Issue by hegelsu** [banchichen/TZImagePickerController#1247]
**问：你希望加什么新功能？**
答：可以直接调用录制视频，由于业务需要，视频只能现拍，当设置takePhoto,pickPhoto,pickVideo为false,同时takeVideo为true时，没有录像按钮入口，建议如设置为只能录视频的时候能显示录制视频的按钮并在界面显示完成后再自动打开录制视频的界面，用户录制完成后走现有的回调即可

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：无

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：在现有基础上并不需要加属性开关，不过可以加一个是否自动打开录制界面的开发

**其它你希望补充的内容**

**Comment by banchichen** [comment]
直接录制视频的话，建议你直接使用 UIImagePickerController ...

我里面的录制视频也是用的它，可参考用法
