### ISSUE TITLE
Tag: 3.2.8， 先设置showSelectedIndex属性为YES， 再设置iconThemeColor，会导致如下问题

### ISSUE THREAD

**Issue by 304164084** [banchichen/TZImagePickerController#1249]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.8

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**
如题

**我如何复现这个bug？**
在你的demo里写的。 必现

**截图**

![image](https://user-images.githubusercontent.com/17948098/70605661-e049d180-1c35-11ea-8721-e4b66b9b07b0.png)
**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
发现你的那些imageName相关的属性都是废弃了的，但是在设置iconThemeColor的set方法里又重新设置了一次导致问题的发生。

**Comment by banchichen** [comment]
是的，如注释所说，iconThemeColor要尽早设置：
```objectivec
/// icon主题色，默认是微信的绿色，值是r:31 g:185 b:34。目前仅支持showSelectedIndex为YES时的图片选中icon。如需要，请尽早设置它。
@property (strong, nonatomic) UIColor *iconThemeColor;
```
