### ISSUE TITLE
photoSelImage设置图片时候没有剪切

### ISSUE THREAD

**Issue by ZeroJson** [banchichen/TZImagePickerController#1250]
选中后是正方形的,没有剪切,在相册中重复选中已选中的正常

**Comment by banchichen** [comment]
库内部不会裁剪图片哈，你需要提前裁剪好

**Comment by ZeroJson** [comment]
我的选中按钮就是圆的------------------ 原始邮件 ------------------
发件人: "谭真"<notifications@github.com>
发送时间: 2019年12月16日(星期一) 晚上7:07
收件人: "banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com>;
抄送: "ZeroJson"<1165889915@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [banchichen/TZImagePickerController] photoSelImage设置图片时候没有剪切 (#1250)



库内部不会裁剪图片&#x54C8;，你需要提前裁剪好
 
&mdash;

**Comment by banchichen** [comment]
你可以搜索photoSelImage看下相关代码哈，库里面没处理这个图片，直接显示的，没做裁剪

**Comment by ZeroJson** [comment]
好,已经处理好了 感谢
