### ISSUE TITLE
支持iPadOS的多场景打开

### ISSUE THREAD

**Issue by yushuyi** [banchichen/TZImagePickerController#1251]
我们iPadApp 适配了 iOS13的 多场景，在TZImagePickerController整体过程中 没有什么严重问题，
目前只遇到一个问题，发现在更新 选中索引的时候，是在TZAssetCell里面 监听了一个通知TZ_PHOTO_PICKER_RELOAD_NOTIFICATION 用来判断该Cell 是否需要 选中，以及索引的更新。

但如果TZImagePickerController 应用在多场景里面时 
TZImagePickerController *tzImagePickerVc = (TZImagePickerController *)noti.object;
需要 确认 是否是 当前cell的 TZImagePickerController *tzImagePickerVc。

**Comment by yushuyi** [comment]
下图是我 修正这个Bug的代码，请过目


![image](https://user-images.githubusercontent.com/1632740/71163861-e4ef3500-2288-11ea-8b9a-057ab6fe2d97.png)

**Comment by banchichen** [comment]
老哥，提个PR吧？

**Comment by yushuyi** [comment]
@banchichen 兄弟，已提交
