### ISSUE TITLE
在用户禁止访问系统相册，里面的引导 在iPad屏幕变窄时没有适配

### ISSUE THREAD

**Issue by yushuyi** [banchichen/TZImagePickerController#1252]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.8

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
在用户禁止访问系统相册，里面的引导 在iPad屏幕变窄时没有适配

**我如何复现这个bug？**
在iPad双开App 分屏就可以重现

**截图**
![image](https://user-images.githubusercontent.com/1632740/71160383-6c857580-2282-11ea-8e10-3e0d11cb2636.png)

**其它说明**
只需要 加两行代码就解决了 
_tipLabel.autoresizingMask = UIViewAutoresizingFlexibleWidth;
_settingBtn.autoresizingMask = UIViewAutoresizingFlexibleWidth;

**Comment by banchichen** [comment]
👍
老哥，提个PR吧？

**Comment by yushuyi** [comment]
@banchichen 兄弟，已提交

**Comment by banchichen** [comment]
👍
3.2.9已发布
