### ISSUE TITLE
选择框支持传入网络视频及网络图片（url）

### ISSUE THREAD

**Issue by wxj1996** [banchichen/TZImagePickerController#1257]
**问：你希望加什么新功能？**
答：外层的图片选择框里，可以支持传入视频或者图片urls，因为有时候会重新编辑之前发布的图片内容。新增或者删除图片，这个时候的图片都是网络url, 问题就在于，原相册的数据和网络数据的处理。

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答： 部分有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：可以适合所有人，大多数人都有，图片发布过后，从网络图片到再编辑的需求

**其它你希望补充的内容**

**Comment by banchichen** [comment]
如果是要浏览网络图片，可以看看这个：https://github.com/banchichen/TZImagePreviewController

图片选择器是不会支持网络图片的，网络图片排在哪个位置，属于哪个相册等等，很多问题的

**Comment by wxj1996** [comment]
是的，明白，涉及太多，感谢作者你的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"谭真"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 下午2:05
收件人:&nbsp;"banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;;
抄送:&nbsp;"、One＂"<1731424551@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [banchichen/TZImagePickerController] 选择框支持传入网络视频及网络图片（url） (#1257)




如果是要浏览网络图片，可以看看这个：https://github.com/banchichen/TZImagePreviewController
 
图片选择器是不会支持网络图片的，网络图片排在哪个位置，属于哪个相册等等，很多问题的
