### ISSUE TITLE
能加一个直接拍照的功能接口么

### ISSUE THREAD

**Issue by jiaoshier** [banchichen/TZImagePickerController#1259]
**问：你希望加什么新功能？**
答：加一个直接拍照的功能

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：加接口就行

**其它你希望补充的内容**

**Comment by banchichen** [comment]
拍照是直接用的UIImagePickerController，具体代码见demo里的takePhoto方法，你把这相关方法拷走就行哈
