### ISSUE TITLE
weakself 错误

### ISSUE THREAD

**Issue by Mr-Luxry** [banchichen/TZImagePickerController#126]
您好！首先感谢您分享了这个库。但是我在将您这个库文件拖入工程后，编译，遇到了一下错误，尝试好久，都没有解决。所以来这里向您请教：
<img width="760" alt="2016-07-10 1 24 46" src="https://cloud.githubusercontent.com/assets/13265870/16709242/70b5a226-463d-11e6-8ff3-ae3c461345a9.png">
我尝试改变    __weak typeof(self) weakSelf = self; 的写法: __weak __typeof(self) weakSelf，但是在工程中的有些地方显示找不到这个weakSelf.网上搜了下，有些事c 语言编译库的问题，我把那个c语言编译库改成了和你的demo里的一样，还是不能运行。急急急。。。
这是我的QQ:928393948.期待你的回复，谢谢!

**Comment by banchichen** [comment]
你好，上次有人遇到这个问题，是一个Unity开发者，解决办法是改一种写法，__weak typeof(self) weakSelf = self 改成  SelfClass *weakSelf = self, 这里的SelfClass是self的类，一般是文件名，如果一个文件有多个类（有多处@interface），这里self的类就是往上找离它最近的@interface后面的词。如果是 __weak typeof(_numberImageView.layer) weakLayer = _numberImageView.layer 这样的，就是要找_numberImageView.layer的类名，_numberImageView.layer的类名是CALayer 。    照着 类名 *变量名 = 需要建立弱引用的变量 的方式去写就可以编译通过了。我已经加你QQ了，还有问题再在QQ上问吧~
