### ISSUE TITLE
摄像头冲突 内存暴增崩溃

### ISSUE THREAD

**Issue by cjckkk** [banchichen/TZImagePickerController#1266]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是的

2、你用的是什么版本？升级到最新版后是否正常？
答：最新 还是存在

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
A页面有个使用后摄像头预览,进入二级页面B使用TZImagePickerController 选择拍照,点击取消返回,再次点击拍照,内存爆增,崩溃.
Message from debugger: Terminated due to memory issue

**我如何复现这个bug？**
如上所诉

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

ios12.4 iphone6plus

**Comment by banchichen** [comment]
TZ里使用的拍照是系统的UIImagePickeController哈

从A页面进入B页面的时候，把A页面的【后摄像头预览】释放掉，页面viewWillAppear时再打开？
