### ISSUE TITLE
相册文件夹选择功能

### ISSUE THREAD

**Issue by xinru** [banchichen/TZImagePickerController#1273]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
老哥，把你的需求描述清楚哈

**Comment by xinru** [comment]
相册打开后 title 显示 最近项目 希望在‘最近项目’处添加可选择项，点击选择类似 ’截屏‘ 、 ’个人收藏‘ 等相簿文件夹。



在 2020-02-10 19:43:58，"谭真" <notifications@github.com> 写道：

老哥，把你的需求描述清楚哈

**Comment by banchichen** [comment]
目前不考虑支持哈，如有需要，欢迎PR哈
