### ISSUE TITLE
照片依照修改时间倒序排列时无法显示2M以上原图

### ISSUE THREAD

**Issue by xinru** [banchichen/TZImagePickerController#1276]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**
微信保存原图到相册中，如果是设置sortAscendingByModificationDate = YES;相册列表中可以看到刚保存的图片，如果是sortAscendingByModificationDate = NO;则无法看到保存的图片

**我如何复现这个bug？**
从微信中保存一张2M以上的原图照片，用最新的Demo运行，默认是按照修改时间升序排列是可以看到，改成sortAscendingByModificationDate = NO;排列则看不到

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
sortAscendingByModificationDate=NO，会按照片的创建时间排序，说明这种照片的创建时间比较早，你翻翻看，应该能找到的
