### ISSUE TITLE
希望在加一个限制可选择图片的最大内存功能

### ISSUE THREAD

**Issue by yangjikai** [banchichen/TZImagePickerController#1279]
**问：你希望加什么新功能？**
答：现在有最小可选中的图片宽度、高度的功能，能否在增加一个最大内存的限制，这样可以在用户选择内存特别大的图片/视频时候给用户一个比较友好的提示。

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：暂时没发现

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：这个应该是在上传的时候用到的比较多，需要加属性开关。

**其它你希望补充的内容**
或者我没找到相关的属性或方法，也没看到将要选择图片时的方法。

**Comment by banchichen** [comment]
参考下demo，实现isAssetCanSelect，根据宽度和高度信息可以过滤掉，宽度和高度越大，也就二进制数据越大
