### ISSUE TITLE
从选择第二个图片开始,如果来回的选择和取消会出错

### ISSUE THREAD

**Issue by waiting0902** [banchichen/TZImagePickerController#128]
NSArray *selectedModels = [NSArray arrayWithArray:tzImagePickerVc.selectedModels];
 for (TZAssetModel *model_item in selectedModels) {
//这个判断进不来
 if ([[[TZImageManager manager] getAssetIdentifier:model.asset] isEqualToString:  
               [[TZImageManager manager] getAssetIdentifier:model_item.asset]]) {
                    [tzImagePickerVc.selectedModels removeObject:model_item];
                }
                break;
            }
我换成这个没问题
  if ([tzImagePickerVc.selectedModels containsObject:model]) {
                [tzImagePickerVc.selectedModels removeObject:model];
            }

**Comment by banchichen** [comment]
你好，麻烦下载下最新的代码，这个问题前几天的代码中存在....
