### ISSUE TITLE
ios 在视频预览 点击不了完成选择按钮

### ISSUE THREAD

**Issue by iosLongFeng** [banchichen/TZImagePickerController#1281]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
iphoneSE 13.0
选择视频，点击视频跳入视频预览，想选择视频，但是下方“完成”按钮没反应，不可点击状态

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
hi，可以debug下TZVideoPlayerController的configMoviePlayer方法，看看
self->_doneButton.enabled = YES;
是否有执行哈

如果有的话，再看看点完成的时候，doneButtonClick方法是否有执行哈

昨天遇到一个类似提问，他们是改了TZVideoPlayerController的源码...
