### ISSUE TITLE
ITMS-90683: Missing Purpose String in Info.plist

### ISSUE THREAD

**Issue by qiangzai** [banchichen/TZImagePickerController#1283]
收到Apple的邮件，要求在info.plist里添加NSLocationWhenInUseUsageDescription，我也读了以前的issue，我和他们的情况不同，我只需用到选择照片，而**不使用拍照功能**，我添加NSLocationWhenInUseUsageDescription这个key，感觉无法向Apple合理解释清楚啊！由于Apple对权限管理比较严格，建议出一个不带定位功能的库，谢谢！

**Comment by banchichen** [comment]
hi，定位功能可以禁用的，就不会弹窗定位授权窗了哈
```objectivec
// 设置拍照时是否需要定位，仅对选择器内部拍照有效，外部拍照的，请拷贝手动把pushImagePickerController里定位方法的调用删掉
imagePickerVc.allowCameraLocation = NO;
```

**Comment by li-jun** [comment]
只要代码中有定位相关的api就必须在info.plist中声明权限，否则直接被拒，建议添加一个不使用定位api的subspec。
