### ISSUE TITLE
相册中的一个A视频，每次导出来，获取的A视频md5都不一样？

### ISSUE THREAD

**Issue by songhongkang** [banchichen/TZImagePickerController#1284]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有的。

2、你用的是什么版本？升级到最新版后是否正常？
答：下载的DEMO调试

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有改动

导出相同的视频，然后获取视频的md5，发现同一个视频导出的，不一样。

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
hi，导出的视频的NSData里，会不会有一些视频名字的数据？你可以看看哈
名字里有时间戳，md5后就不唯一了
