### ISSUE TITLE
IPad 10.2 裁剪适配有问题

### ISSUE THREAD

**Issue by huanzai** [banchichen/TZImagePickerController#1285]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没

**bug内容描述**
iPad 10.2 上“截取框”位置偏移

**我如何复现这个bug？**
使用 iPad 即可出现（横屏更明显），因为iPad上显示的view不是全屏。所以计算的 self.view.tz_width，self.view.tz_height 不是真正的大小。所以 cropRect.origin 计算有误。

**截图**
![avatar](https://raw.githubusercontent.com/huanzai/tmp/master/IMG_0023.PNG.JPG)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
全屏展示的话是可以的哈，建议全屏展示

实在要支持非全屏的话，欢迎提MR哈

**Comment by huanzai** [comment]
imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen;
补上这句就ok了。感谢
