### ISSUE TITLE
有个图片在iPhoneX上无法正常显示，其他机型可以。

### ISSUE THREAD

**Issue by chzm** [banchichen/TZImagePickerController#1286]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：Demo没跑起来

2、你用的是什么版本？升级到最新版后是否正常？
答：已是最新版本 [V3.2.9]

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
有一张图片，链接：
![问题图片链接](http://file06.16sucai.com/2016/0802/2770820468228b6acb7e51f762ceceae.jpg)
在iPhoneX上无法显示，其他机型可以。

**我如何复现这个bug？**
下载该图片到相册上，然后在对应的机型打开展示。

**截图**
![相册里的图片](https://user-images.githubusercontent.com/21350675/76839818-28017a00-6871-11ea-853a-0e2d114647fb.png)

![使用TZ显示不出图片](https://user-images.githubusercontent.com/21350675/76839843-3780c300-6871-11ea-96fc-7aa337681106.jpeg)

![手机基本信息](https://user-images.githubusercontent.com/21350675/76839904-4c5d5680-6871-11ea-8c7b-3f5aff2e523e.jpeg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

如还无法复现，联系微信号【anyshysh14】

**Comment by herobsxf** [comment]
我这里也收到了用户反馈有一张图片显示不出来，但是相册里面存在，蹲一个开发者回复
机型是这个
![WechatIMG16](https://user-images.githubusercontent.com/15306563/76922102-c0980880-690a-11ea-8178-48d3899eb24e.jpeg)
图片是这个
![WechatIMG22](https://user-images.githubusercontent.com/15306563/76922150-e45b4e80-690a-11ea-9bcf-75a401ecf57e.jpeg)

**Comment by banchichen** [comment]
这个应该是该图片的创建时间较早，你设置了sortAscendingByModificationDate=NO，按创建时间排序了，你上下翻翻找找
你不设置sortAscendingByModificationDate的话应该就正常了
