### ISSUE TITLE
照片里有相册，App内读取不到内容

### ISSUE THREAD

**Issue by lordlamb** [banchichen/TZImagePickerController#1287]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：没办法验证，因为是用户反馈的一个问题

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.7

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有改动

**bug内容描述**
用户有很多相册，并且相册里有内容，但是App里只能读取到“最近项目”这个相册，并且里面没有内容。

**我如何复现这个bug？**
来自用户反馈，我无法复现

**截图**
![image](https://user-images.githubusercontent.com/46437480/76942945-85f99480-6939-11ea-9085-58b5878b3973.png)
![WechatIMG17](https://user-images.githubusercontent.com/46437480/76943000-9a3d9180-6939-11ea-9650-7ca7dc173a7d.jpeg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
该用户在微信里打开图片选择器有照片吗？
可能需要和用户确认些环境细节，尽量重现出来，否则很难查...

**Comment by lordlamb** [comment]
联系了用户说微信里是正常的

**Comment by banchichen** [comment]
对应用取消相册授权，然后再授权上试试？
或者卸载APP试试？

**Comment by lordlamb** [comment]
这些都试过了，还是现在这个状况

**Comment by banchichen** [comment]
那比较玄幻了，原因肯定是用系统API读相册内容时没读到内容，可能需要拿用户手机debug下demo了...
