### ISSUE TITLE
选择相册第一次点击左上角返回的时候,严重卡顿, 系统报错没有放到主线程

### ISSUE THREAD

**Issue by yaoyao138966** [banchichen/TZImagePickerController#1288]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
选择相册第一次点击左上角返回的时候,严重卡顿, 系统报错没有放到主线程, 但我打印[NSThead currentthead] 是主线程1, main, 但在TZImagePickerController.m  - (void)configTableView{}中742行代码dispatch_async(dispatch_get_global_queue(0, 0), ^{  改为 dispatch_async(dispatch_get_main_queue(), ^{就好了, 在我理解范围内, 这两个是一样的, 求大佬解惑

**我如何复现这个bug？**
下载最新demo

**截图**

暂无
**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
老哥，你这个不是最新版本，这个问题应该修复约2年了...
最新版 3.3.1 哈

**Comment by yaoyao138966** [comment]
大佬, 我错了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "谭真"<notifications@github.com&gt;; 
发送时间: 2020年3月25日(星期三) 上午10:48
收件人: "banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;; 
抄送: "604019514"<604019514@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [banchichen/TZImagePickerController] 选择相册第一次点击左上角返回的时候,严重卡顿, 系统报错没有放到主线程 (#1288)





 
老哥，你这个不是最新版本，这个问题应该修复约2年了...
 最新版 3.3.1 哈

**Comment by yx-13729** [comment]
> 大佬, 我错了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "谭真"<notifications@github.com&gt;; 发送时间: 2020年3月25日(星期三) 上午10:48 收件人: "banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;; 抄送: "604019514"<604019514@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [banchichen/TZImagePickerController] 选择相册第一次点击左上角返回的时候,严重卡顿, 系统报错没有放到主线程 (#1288) 老哥，你这个不是最新版本，这个问题应该修复约2年了... 最新版 3.3.1 哈 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯? 怎么理解, 我看最新的3.4.1还是有这个问题的呀
