### ISSUE TITLE
自定义颜色无效

### ISSUE THREAD

**Issue by iFallen** [banchichen/TZImagePickerController#1289]
全局配置了UINavigationBar.appearance 的样式

导致所有navigationBar 相关颜色配置均无效
imagePickerVc.naviBgColor = UIColor.th.body
imagePickerVc.barItemTextColor = UIColor.th.body
...

**Comment by banchichen** [comment]
试试设置appearance的时候加个 appearanceWhenContainedInInstancesOfClasses 的限定？
