### ISSUE TITLE
允许拍照，不允许访问相册，拍照后保存不了，导致拿不到PHAsset or ALAsset对象，无法进入查看大图页面

### ISSUE THREAD

**Issue by 275080225** [banchichen/TZImagePickerController#129]
允许拍照，不允许访问相册，拍照后保存不了，导致拿不到PHAsset or ALAsset对象，无法进入查看大图页面
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithSelectedAssets:_selectedAssets selectedPhotos:_selectedPhotos index:selectedIndex];
建议可以不传selectedAssets也可以查看图片！

另外
- (void)savePhotoWithImage:(UIImage *)image completion:(void (^)())completion
建议加个失败的block

**Comment by banchichen** [comment]
好吧，只给相机授权不给相册授权.....   这里已经修复了，如果失败，会把失败对象传出去~       不传selectedAssets也可以查看图片要求对目前代码有较大改动，最近没有优化计划...
