### ISSUE TITLE
progressHUD消失时机不准确

### ISSUE THREAD

**Issue by ZhangCrow** [banchichen/TZImagePickerController#1290]
大神您好。
1、我最新的Demo是否有这个bug？
答：尝试最新Demo有该问题，可准确复现。

2、你用的是什么版本？升级到最新版后是否正常？
答：v3.2.6

3、是否有改动过我库内部的代码？
答：未改动

**bug内容描述**
TZImagePickerController的`showProgressHUD`方法中会执行延时隐藏HUD，如果timeout设置稍微长一些，切换TZImagePickerController层级并最终多选视频，点击完成。最终的HUD超时关闭可能会是前面切换层级的HUD的延时隐藏。

**我如何复现这个bug？**
* 控件配置
```
imagePickerVc.timeout = 60;
imagePickerVc.allowPickingMultipleVideo = YES;
```
* 设备iOS13.3.1(理论上应该没有版本要求)，开启iCloud照片，开启共享相簿。
* 设备录制一份短视频，并添加到共享相簿“相簿A”。
* 运行Demo，添加。从“最近项目”返回“照片”后选择“相簿A”，选择视频，点击完成。

**截图**
应该不需要截图吧

**其它说明**
在上述复现步骤中，“最近项目”configTableView，“照片”configTableView，点击完成。共触发了三次TZImagePickerController的`showProgressHUD`方法，只要最终并没有那么快的完成读取视频，那么有可能HUD是根据某一次configTableView触发的延时隐藏而不是点击完成的那次。

**Comment by ZhangCrow** [comment]
这是一个我排查其他问题时遇到的副产物，timeout设置60是因为，我发现当选择共享相簿中的视频时会大概率的提前隐藏HUD，并且几分钟后才会触发完成或失败的回调。这个问题稍后我可能会另外提一个issue来详细描述。

**Comment by banchichen** [comment]
赞👍
已merge
