### ISSUE TITLE
允许选取Gif和关闭预览时，Gif可以被重复选中，而且角标会不断增加

### ISSUE THREAD

**Issue by ReverseScale** [banchichen/TZImagePickerController#1292]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：存在问题

2、你用的是什么版本？升级到最新版后是否正常？
答：GitHub 下载的最新版本，跑的 Demo

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有动过

**bug内容描述**
允许选取Gif和关闭预览时，Gif可以被重复选中，而且角标会不断增加

**我如何复现这个bug？**
重复选中Gif

**截图**
![图片](https://s1.ax1x.com/2020/03/24/8LPr8S.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
3.4.0版本已修复，同时适配了iOS14，修复了2个严重适配问题，建议尽快升级~
