### ISSUE TITLE
是否可以直接打开相机？

### ISSUE THREAD

**Issue by tipshot** [banchichen/TZImagePickerController#1294]
是否可以直接打开相机？而不是先打开相册，然后才能有相机的按钮？初入，小白。

**Comment by banchichen** [comment]
玩玩Demo，选中 把拍照按钮放到外面

**Comment by masakapa** [comment]
我看了好多遍才看到这个选项，太瞎了我

**Comment by tanghaitao** [comment]
> 我看了好多遍才看到这个选项，太瞎了我

那个选项

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/132150015-2a1a50b6-f0e7-4b7d-9d7c-ded219060446.png)
