### ISSUE TITLE
裁剪完之后的 图片过大

### ISSUE THREAD

**Issue by lamchaohao** [banchichen/TZImagePickerController#1298]
裁剪完后保存的图片大小很大，比如完选择了圆形裁剪，半径大小192，完成后图片达到6.4M，原图片大小才2M。这个是我使用有问题吗？代码如下
`imagePickerVc.needCircleCrop=YES;
 imagePickerVc.allowPreview=YES; 
imagePickerVc.circleCropRadius= 192;`

**Comment by banchichen** [comment]
你用UIImageJPEGRepresentation(image, 0.9)，大小就合适了，png格式是很大的
