### ISSUE TITLE
// 如果没有选中过照片 点击确定时选中当前预览的照片

### ISSUE THREAD

**Issue by AndyFightting** [banchichen/TZImagePickerController#1299]
感觉这个不太好呀，这样始终都有一个，不能全部取消了....我把这两行代码注销了，<(*￣▽￣*)/
是不是应该  minImagesCount = 1 的时候才做这个操作呢？

**Comment by jianxuanlu** [comment]
对的，我也发现有这个疑问，想全部取消，就没有办法了

**Comment by banchichen** [comment]
升级到3.4.0，把autoSelectCurrentWhenDone设置为NO，就不会自动选中当前照片了哈

3.4.0同时适配了iOS14，修复了2个严重适配问题，建议尽快升级
