### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by leasontou** [banchichen/TZImagePickerController#13]
bug：
1.presentViewController的时候不会自动跳转到相机胶卷里，但是你的demo可以，看了下里面的代码实现，是根据名字来匹配的，这里面有坑。
2.demo里面将imagePickerVc.allowPickingVideo =NO;
设置成只能选图片之后，跳转出来的依旧可以选择视频

建议将NavigationController滑动返回的手势加上

**Comment by banchichen** [comment]
谢谢指出，1和2已经解决了~     你指的是全屏右滑返回吗？这个图片选择器作为第三方，是不应该这样做的，如果你项目中加了全屏右滑返回，这个图片选择器自然也有了全屏右滑。
