### ISSUE TITLE
当设置TZImagePickerController autodismiss为NO时，选择完照片后，使用TZImagePickerController present到一个新的控制器，如果是在选择照片页面跳转，下一控制器页面状态栏没有问题，但是如果是在preview页面跳转，发现下一页面所有控件向上便宜状态栏个点，不知道为啥状态栏高度变为零了了

### ISSUE THREAD

**Issue by dulifu** [banchichen/TZImagePickerController#1301]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.3.1

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**
当设置TZImagePickerController autodismiss为NO时，选择完照片后，使用TZImagePickerController present到一个新的控制器，如果是在选择照片页面跳转，下一控制器页面状态栏没有问题，但是如果是在preview页面跳转，发现下一页面所有控件向上偏移了状态栏高度个点，不知道为啥状态栏高度变为0了

**我如何复现这个bug？**
新建项目、跟控制器添加button button调用图片选择器，注意设置autodismiss为NO,然后做图片选择，注意到preview页面做done的操作，done后使用TZImagepickerController present到一个新的页面，发现新页面所有控件都向上偏移了状态栏个点，发现是状态栏高度变为了0

**截图**

![11586504356_ pic](https://user-images.githubusercontent.com/17981102/78972955-80aaf680-7b41-11ea-9579-f55fd2e4588d.jpg)
![21586504357_ pic](https://user-images.githubusercontent.com/17981102/78972977-8b658b80-7b41-11ea-911c-9357f53a3584.jpg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
[present新控制器.mov.zip](https://github.com/banchichen/TZImagePickerController/files/5475385/present.mov.zip)

随便建了个测试ViewController，没能复现你的问题

可以拿最新的Demo试试，如能复现，请提供下Demo吧
