### ISSUE TITLE
希望新增一个代理,返回值为BOOL,1个参数

### ISSUE THREAD

**Issue by yaoyao138966** [banchichen/TZImagePickerController#1302]
**问：你希望加什么新功能？**
答：希望新增一个代理,返回值为BOOL,1个参数. 参数为当前选中的一个(图片或者视频), 代理的返回值为YES, 就选中当前我们的点击, 为no就不能选中, 我们自己判断当前这种图片是否选中, 如果不能选中我们自己给弹框提示

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：没有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：不是, 可以

**其它你希望补充的内容**
感谢大神查看

**Comment by banchichen** [comment]
这功能可以的，欢迎提PR呀~

**Comment by banchichen** [comment]
3.5.7已支持，可参考Demo实现isAssetCanBeSelected
