### ISSUE TITLE
黑暗模式

### ISSUE THREAD

**Issue by lixuansheng** [banchichen/TZImagePickerController#1303]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by lixuansheng** [comment]
希望新增黑暗模式

**Comment by JamesWangAiHan** [comment]
现在不支持iOS13的暗黑模式，这点不友好

**Comment by qiubaiying** [comment]
希望新增黑暗模式

**Comment by pengpeng-wang** [comment]
暗黑模式背景还不支持

**Comment by damoncoo** [comment]
> 暗黑模式背景还不支持

希望早点支持暗黑

**Comment by Simon-Tseng** [comment]
急用的话，可以先参考我这个PR:
https://github.com/banchichen/TZImagePickerController/pull/1363

**Comment by banchichen** [comment]
已支持哈，新版本：3.4.3
