### ISSUE TITLE
选择图片以后相册置灰的小细节希望加一下，代码我添加如下

### ISSUE THREAD

**Issue by q760440238** [banchichen/TZImagePickerController#1304]
#pragma mark - Notification

- (void)reload:(NSNotification *)noti {
    TZImagePickerController *tzImagePickerVc = (TZImagePickerController *)noti.object;
    
    UIViewController *parentViewController = nil;
    UIResponder *responder = self.nextResponder;
    do {
        if ([responder isKindOfClass:[UIViewController class]]) {
            parentViewController = (UIViewController *)responder;
            break;
        }
        responder = responder.nextResponder;
    } while (responder);
    
    if (parentViewController.navigationController != tzImagePickerVc) {
        return;
    }
    
    if (self.model.isSelected && tzImagePickerVc.showSelectedIndex) {
        self.index = [tzImagePickerVc.selectedAssetIds indexOfObject:self.model.asset.localIdentifier] + 1;
    }
    self.indexLabel.hidden = !self.selectPhotoButton.isSelected;
    if (tzImagePickerVc.selectedModels.count >= tzImagePickerVc.maxImagesCount && tzImagePickerVc.showPhotoCannotSelectLayer && !self.model.isSelected) {
        self.cannotSelectLayerButton.backgroundColor = tzImagePickerVc.cannotSelectLayerColor;
        self.cannotSelectLayerButton.hidden = NO;
    } else {
        self.cannotSelectLayerButton.hidden = YES;
        if (self.model.type == TZAssetModelMediaTypeVideo) {
            if (tzImagePickerVc.selectedModels.count >= 1) {
                self.cannotSelectLayerButton.backgroundColor = tzImagePickerVc.cannotSelectLayerColor;
                self.cannotSelectLayerButton.hidden = NO;
            }else{
                self.cannotSelectLayerButton.hidden = YES;
            }
        }
    }
}

**Comment by banchichen** [comment]
设置了showPhotoCannotSelectLayer后，不能继续选择照片的时候，不就会置灰了吗？
