### ISSUE TITLE
能否添加一个传入已选择的图片数组

### ISSUE THREAD

**Issue by linhaosheng** [banchichen/TZImagePickerController#1305]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
参考demo的效果哈，已选择的可以通过selectedAssets属性传入，需要是PHAsset对象
