### ISSUE TITLE
threading violation: expected the main thread

### ISSUE THREAD

**Issue by Mamakou** [banchichen/TZImagePickerController#1306]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：暂无发现

2、你用的是什么版本？升级到最新版后是否正常？
答：这个bug之前碰到过 ，4月10号的时候用的最新版

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**
threading violation: expected the main thread
就是提示要主线程
**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by Mamakou** [comment]
在这个bug发生前，用户有频繁切换前后台的操作

**Comment by MRZHL** [comment]
有解决的么, bugly 上捕捉的, 出现的频率还很高

`
1605-12 22:04:52.218 [ TZPhotoPickerController ] WillAppear
1705-12 22:04:57.736 [ CAMImagePickerCameraViewController ] WillAppear
1805-12 22:04:57.748 [ CAMViewfinderViewController ] WillAppear
1905-12 22:04:57.748 [ CAMPreviewViewController ] WillAppear
2005-12 22:05:00.406 [ TZPhotoPickerController ] WillAppear
`
跟踪数据来看, 是在获取手机拍照功能以后,出现的问题

**Comment by MRZHL** [comment]
看看是不是你的项目里用到了GKPhotoBrowser, 好像是这个的问题

**Comment by Mamakou** [comment]
我项目中确实用到了GKPhotoBrowser，貌似有冲突？
