### ISSUE TITLE
Bugly统计到的崩溃问题

### ISSUE THREAD

**Issue by yaoqi-github** [banchichen/TZImagePickerController#1308]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：TZImagePickerController (3.3.1)

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**

**我如何复现这个bug？**

**截图**
bug统计到内存暴涨问题

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
*** NSAllocateMemoryPages(540861) failed
(null)
((
    0 CoreFoundation 0x0000000181fd237c + 148
    1 libobjc.A.dylib 0x0000000181218528 objc_exception_throw + 56
    2 CoreFoundation 0x0000000181fd22ac + 0
    3 Foundation 0x00000001829344d0 NSAllocateMemoryPages + 100
    4 Foundation 0x000000018290bb8c + 36
    5 Foundation 0x00000001828d7590 + 260
    6 UIKit 0x000000018b5e8274 + 360
    7 UIKit 0x000000018b759608 + 124
    8 UIKit 0x000000018b5e80d8 + 72
    9 ****!__95-[TZImageManager getPhotoWithAsset:photoWidth:completion:progressHandler:networkAccessAllowed:]_block_invoke_4 [TZImageManager.m : 389]
    10 Photos 0x000000019063be5c + 680
    11 libdispatch.dylib 0x000000018194ea54 + 24
    12 libdispatch.dylib 0x000000018194ea14 + 16
    13 libdispatch.dylib 0x000000018198fc80 + 968
    14 CoreFoundation 0x0000000181f7a544 + 12
    15 CoreFoundation 0x0000000181f78120 + 2012
    16 CoreFoundation 0x0000000181e97e58 CFRunLoopRunSpecific + 436
    17 GraphicsServices 0x0000000183d44f84 GSEventRunModal + 100
    18 UIKit 0x000000018b51767c UIApplicationMain + 236
    19 DZMallApp!main [main.m : 14]
    20 libdyld.dylib 0x00000001819b456c + 4
)
dSYM UUID: 
CPU Type: arm64
Slide Address:
Binary Image:
Base Address:

**Comment by banchichen** [comment]
容易复现吗？是不是这个手机里有个超大的图片？
