### ISSUE TITLE
iOS11系统返回到相册列表，导航栏控件消失

### ISSUE THREAD

**Issue by LuckilyHaveYou** [banchichen/TZImagePickerController#1309]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**
iOS11系统，在照片页显示正常，点击左上角返回到相册列表，导航栏控件消失

**我如何复现这个bug？**
iOS11系统，在照片页显示正常，点击左上角返回到相册列表，导航栏控件消失

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by LuckilyHaveYou** [comment]
已经是最新的版本

**Comment by banchichen** [comment]
demo是正常的，是某个三方库影响的，仔细看下readme里的qa，或搜下相关issue看看

**Comment by LuckilyHaveYou** [comment]
解决了，跟工程视图层级有关系。换成window.rootviewcontroller就没有问题了

**Comment by DoubleHeer** [comment]
你好，能说下是怎么解决的吗。
我这边测试demo正常，移到项目里iOS13测试正常，iOS11跟你一样，点击返回导航栏按钮就没了，侧滑返回导航栏按钮就变成照片页的按钮。
