### ISSUE TITLE
图片排序问题，创建时间或者最后修改时间

### ISSUE THREAD

**Issue by fuboyou** [banchichen/TZImagePickerController#1310]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.6

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

sortAscendingByModificationDate设置为NO时，将一个去年的图片添加到相册，图片在相册中的位置，微信会放到最前面，但是TZImagePickerController是按照文件创建时间排序，看到工程里有注释modificationDate排序的代码，是有其他的问题吗

**Comment by banchichen** [comment]
嗯，注释的原因在这：https://github.com/banchichen/TZImagePickerController/issues/259

**Comment by fuboyou** [comment]
> 嗯，注释的原因在这：#259

感谢
