### ISSUE TITLE
提交审核之后因为prefs:root=被拒了，查看了项目只有TZ的readme.md文件中有

### ISSUE THREAD

**Issue by pinzhouM** [banchichen/TZImagePickerController#1313]
想问一下，这个readme.md文件中的prefs:roots=升级删除的信息是否可能影响上架时候的审核呢，有人跟我遇到一样的情况吗

**Comment by banchichen** [comment]
应该不会，这个很久了没见反馈过
不过这个说明可以去掉了，我readme更新了，发了3.3.2版本
你可以更新下
