### ISSUE TITLE
允许选择gif图片功能异常

### ISSUE THREAD

**Issue by ZhangLi98745** [banchichen/TZImagePickerController#1314]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
允许选择gif图片功能异常

**我如何复现这个bug？**
最新demo中可以复现
Demo中打开允许选择gif图片，相册中的gif不能选取，预览之后 点击完成可以选取
关闭 允许选择gif图片，相册中gif可以选取
**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
1、GIF默认是单张选中，不能在列表页选取
2、关闭允许选择GIF后，选取的GIF实际是静态图了
3、设置allowPickingMultipleVideo为YES，则在列表页也可以选取GIF
