### ISSUE TITLE
真机 13.3 系统闪退，使用的是最新版本的，没给权限会进去闪退，给了权限之后，在图片选择页面滚动也会闪退

### ISSUE THREAD

**Issue by raopipi** [banchichen/TZImagePickerController#1316]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by raopipi** [comment]
demo跑真机正常

**Comment by banchichen** [comment]
demo正常的话，可以好好对比下哈...

**Comment by banchichen** [comment]
如不是pod引入的，可能之前的开发有修改了源码...
