### ISSUE TITLE
如何及时更新  TZImagePickerController 实例对象的 previewBtnTitleStr 属性值

### ISSUE THREAD

**Issue by PureCoderPan** [banchichen/TZImagePickerController#1317]
在创建 TZImagePickerController 实例对象（懒加载）时，通过`_imagePickerView.previewBtnTitleStr = @"哈哈哈哈"; ` 设置 previewBtn 的 title 生效的。但是在动态修改的时候就无法修改。例如当我将选择好的图片上传成功后需要再次 修改  previewBtn 的 title ，这时就无法修改（修改确定在主线程），请问支持动态修改吗？如果不支持的话有没有什么办法实现该需求？

**Comment by banchichen** [comment]
hi，可以在代码里搜一下
```
previewBtnTitleStr =
```
可以看到我内部会初始化这个值，你试试延迟设置的时机哈，这样就能覆盖内部的默认值
