### ISSUE TITLE
单纯预览自己的图片，Swift无法使用，没有相关写法参考，过于复杂。

### ISSUE THREAD

**Issue by YzStyle** [banchichen/TZImagePickerController#1318]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：无

2、你用的是什么版本？升级到最新版后是否正常？
答：3.3.2，选择那些功能都正常，只有单纯使用预览出问题。

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
rt

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
hi，TZImagePickerController是针对照片选择场景的，是对UIImagePickerController的功能增强，使用上可以直接参考demo，swift的用法和OC一样的

如果仅是预览图片，可以试试：https://github.com/banchichen/TZImagePreviewController  或者其他的库
