### ISSUE TITLE
设置了裁剪区域，但是图片没办法完整的放进裁剪区域内

### ISSUE THREAD

**Issue by ywdonga** [banchichen/TZImagePickerController#1319]
大神你好，在使用裁剪功能是，我们设置了一个自定义的裁剪区域，但是我发现图片没办法完整的放进裁剪区域内，款和高都多出很多。
![91591783335_ pic](https://user-images.githubusercontent.com/16291063/84255253-eec16900-ab44-11ea-92da-34fd32fa2c61.jpg)
![image](https://user-images.githubusercontent.com/16291063/84255368-187a9000-ab45-11ea-8fee-7c8b86157e19.png)

**Comment by ZhangXueFei** [comment]
运行demo是正常的，集成到项目中，裁剪区域总是会高出去一部分

**Comment by banchichen** [comment]
hi，我这Demo未复现这个问题哈
![image](https://user-images.githubusercontent.com/12755494/95756257-22212980-0cd8-11eb-907e-0379021e1c93.png)

可以再试试最新版Demo，今天优化了scaleAspectFillCrop的设置，会自动填满cropRect

如果试了Demo也有问题的话，请发一下对Demo的改动点，或者也可以试试，cropRect的高度不要设置太高

**Comment by ywdonga** [comment]
好的，我更新试试，谢谢大佬
