### ISSUE TITLE
视频预览页面完成按钮无法点击

### ISSUE THREAD

**Issue by shuLeesin** [banchichen/TZImagePickerController#1320]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.3.1

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
选择本机中某个视频后,进入视频预览页面 完成按钮无法点击,查看代码得出
TZVideoPlayerController类中configMoviePlayer方法里面
` [[TZImageManager manager] getPhotoWithAsset:_model.asset completion:^(UIImage *photo, NSDictionary *info, BOOL isDegraded) {
        if (!isDegraded && photo) {
            self->_cover = photo;
            self->_doneButton.enabled = YES;
        }
    }];`

这个方法中 photo获取为nil 导致 完成按钮不能点击

**我如何复现这个bug？**
目前只在本机上部分视频发现有这个问题,可以确定的是这个视频不是需要icloud下载的视频

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
` TZImagePickerController *imagePicker = [[TZImagePickerController alloc] init];
 imagePicker.allowTakeVideo = NO;
 imagePicker.allowTakePicture = NO;
 imagePicker.allowPickingImage = NO;
 imagePicker.pickerDelegate = self;
 [self presentViewController:imagePicker animated:YES [completion:nil];`]

**Comment by banchichen** [comment]
加下我QQ：736420282，这个视频发我下哈

**Comment by banchichen** [comment]
3.4.0版本已发布，修复了这个问题

对于iCloud同步失败的情况，跟微信一样在界面上给予合适的提示，感谢 @shuLeesin 的PR👍
