### ISSUE TITLE
自定义返回按钮且多选时侧滑返回无效，且界面变糊

### ISSUE THREAD

**Issue by LukeChow** [banchichen/TZImagePickerController#1322]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本，不正常

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：改动了，增加返回按钮的自定义设置：
    imagePickerVc.navLeftBarButtonSettingBlock = ^(UIButton *leftButton) {
            [leftButton setImage:[UIImage imageNamed:@"back"] forState:UIControlStateNormal];
        };

**bug内容描述**
增加返回按钮的自定义设置后，多选模式下，无法侧滑返回相册列表，尝试侧滑，界面轻微抖动，图片缩略图变糊。
    imagePickerVc.navLeftBarButtonSettingBlock = ^(UIButton *leftButton) {
            [leftButton setImage:[UIImage imageNamed:@"back"] forState:UIControlStateNormal];
        };

**我如何复现这个bug？**
系统：iOS13.5，手机：iPhone11，添加返回按钮的自定义设置后，多选模式下，即可出现

**截图**
不需要

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
在demo的基础上增加返回按钮的自定义设置即可出现

**Comment by banchichen** [comment]
自定义返回按钮，需要打开这些代码哈，如Demo：
```objectivec
- (void)pushTZImagePickerController {
    // 自定义导航栏上的返回按钮
    /*
    [imagePickerVc setNavLeftBarButtonSettingBlock:^(UIButton *leftButton){
        [leftButton setImage:[UIImage imageNamed:@"back"] forState:UIControlStateNormal];
        [leftButton setImageEdgeInsets:UIEdgeInsetsMake(0, -10, 0, 20)];
    }];
    imagePickerVc.delegate = self;
    */
}

/*
// 设置了navLeftBarButtonSettingBlock后，需打开这个方法，让系统的侧滑返回生效
- (void)navigationController:(UINavigationController *)navigationController didShowViewController:(UIViewController *)viewController animated:(BOOL)animated {
 
    navigationController.interactivePopGestureRecognizer.enabled = YES;
    if (viewController != navigationController.viewControllers[0]) {
        navigationController.interactivePopGestureRecognizer.delegate = nil; // 支持侧滑
    }
}
*/
```
