### ISSUE TITLE
录制视频的宽高可否增加属性自选

### ISSUE THREAD

**Issue by abc8312111** [banchichen/TZImagePickerController#1323]
**问：你希望加什么新功能？**
答：录制视频的宽高可否增加属性自选

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：无

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是的 很多app录制的视频不一定是竖屏

**其它你希望补充的内容**
希望能增加一个录制视频宽高自选的参数，我一直没找到。如果已经有了的话，希望作者大大告知是哪个属性。

**Comment by banchichen** [comment]
TZ里面的拍照、拍视频，是用的系统的UIImagePickerController，可以通过uiImagePickerControllerSettingBlock自定义设置
可以找找UIImagePickerController是否有相关的设置项
