### ISSUE TITLE
TZPhotoPickerController数组插入空对象崩溃

### ISSUE THREAD

**Issue by ryanwangh** [banchichen/TZImagePickerController#1324]
#0 Thread
NSInvalidArgumentException
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]
解析原始
0 CoreFoundation	0x0000000225816000 + 1149324
1 libobjc.A.dylib	objc_exception_throw + 56
2 CoreFoundation	_CFArgv + 0
3 CoreFoundation	0x0000000225816000 + 52436
4 CoreFoundation	0x0000000225816000 + 25752
5 	__82-[TZPhotoPickerController pushPhotoPrevireViewController:needCheckSelectedModels:]_block_invoke.609 (TZPhotoPickerController.m:755)
6 	-[TZPhotoPreviewController doneButtonClick] (TZPhotoPreviewController.m:401)
7 UIKitCore	-[UIApplication sendAction:to:from:forEvent:] + 96
8 UIKitCore	-[UIControl sendAction:to:forEvent:] + 80
9 UIKitCore	-[UIControl _sendActionsForEvents:withEvent:] + 440

**Comment by ZenonHuang** [comment]
我们 App 线上也发现有。你们急可以先修复，我提了个PR [pull request 1331](https://github.com/banchichen/TZImagePickerController/pull/1331)
