### ISSUE TITLE
筛选音频

### ISSUE THREAD

**Issue by PureCoderPan** [banchichen/TZImagePickerController#1325]
项目中使用 
TZImagePickerController 进行图片和视频的选择，现在需要增加音频和视频的筛选，请问这个问题有什么解决思路吗？

**Comment by banchichen** [comment]
可以重点看下fetchAssetModels方法，里面返回的models就是列表页显示的资源，通过控制models的内容可以实现筛选。
另外，也可以试试isAssetCanSelect，返回NO时该资源不会出现在列表页
