### ISSUE TITLE
不能按指定尺寸裁剪图片

### ISSUE THREAD

**Issue by Steven-Yung** [banchichen/TZImagePickerController#1326]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.3.2

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**

指定裁剪尺寸不生效
**我如何复现这个bug？**

可以运行demo，把
   ` imagePickerVc.cropRect = CGRectMake(left, top, widthHeight, widthHeight);`改为`imagePickerVc.cropRect = CGRectMake(0, 200, self.view.frame.width, 200);`即可复现问题
**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
cropRect的center应该是页面中心，因此这里的top应该是(self.view.frame.size.height - 200) / 2，这样设置试试：
```objectivec
imagePickerVc.cropRect = CGRectMake(0, (self.view.frame.size.height - 200) / 2, self.view.frame.size.width, 200);
```
