### ISSUE TITLE
iOS14.0 beta1中，图片授权为"选中的照片"，图片选择页展示不出图片

### ISSUE THREAD

**Issue by fuboyou** [banchichen/TZImagePickerController#1327]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.2.6版本，升级问题存在

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**
iOS14.0 beta1中，图片授权为"选中的照片"，图片选择页展示不出图片

**我如何复现这个bug？**
进入图片选择页，图片授权为"选中的照片"

**截图**
![IMG_1557](https://user-images.githubusercontent.com/12692889/85521681-306b0d00-b637-11ea-92c3-b862e2cd0cda.PNG)

**Comment by banchichen** [comment]
老哥，你动作有些快呀，来个PR不？

**Comment by yaoqi-github** [comment]
修改方案：TZAssetCell.m
- (UIImageView *)imageView {
    if (_imageView == nil) {
        UIImageView *imageView = [[UIImageView alloc] init];
        imageView.contentMode = UIViewContentModeScaleAspectFill;
        imageView.clipsToBounds = YES;
        [self.contentView addSubview:imageView];
        /// TODO: 解决图片在iOS14系统下显示不出来 开始
        [self.contentView bringSubviewToFront:self.selectImageView];
        imageView.frame = self.bounds;
        /// TODO: 解决图片在iOS14系统下显示不出来  结束
        _imageView = imageView;
        
        _tapGesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(didTapImageView)];
        [_imageView addGestureRecognizer:_tapGesture];
    }
    return _imageView;
}

**Comment by fuboyou** [comment]
> 修改方案：TZAssetCell.m
> 
> * (UIImageView *)imageView {
>   if (_imageView == nil) {
>   UIImageView *imageView = [[UIImageView alloc] init];
>   imageView.contentMode = UIViewContentModeScaleAspectFill;
>   imageView.clipsToBounds = YES;
>   [self.contentView addSubview:imageView];
>   /// TODO: 解决图片在iOS14系统下显示不出来 开始
>   [self.contentView bringSubviewToFront:self.selectImageView];
>   imageView.frame = self.bounds;
>   /// TODO: 解决图片在iOS14系统下显示不出来  结束
>   _imageView = imageView;
>   ```
>     _tapGesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(didTapImageView)];
>     [_imageView addGestureRecognizer:_tapGesture];
>   ```
>   
>   
>   }
>   return _imageView;
>   }

生效

**Comment by banchichen** [comment]
3.4.0版本已修复，适配了iOS14，建议升级~
