### ISSUE TITLE
图片可以重复选择问题，请教

### ISSUE THREAD

**Issue by ZYVIP** [banchichen/TZImagePickerController#133]
集成使用的时候，当我在一个界面点击进去图片选择器，选择了几张图片后，点击确定回到collectionView界面，可是当我再次点击最后一个item的时候，先前选中的图片不在选中状态，我请问一下是怎么回事。我看Demo是再次选择时，先前的选择是在选中状态的，不知道怎么回事，求指导。急求！！！谢谢了

**Comment by banchichen** [comment]
你好，传了selectedAssets，里面的就会是选中状态。

**Comment by ZYVIP** [comment]
我都是按照你的demo复制的代码，你说的实在没哪个方法里面的啊。谢谢了

**Comment by banchichen** [comment]
就在Demo页中pushImagePickerController方法里...这个参数
imagePickerVc.selectedAssets = _selectedAssets; // optional, 可选的
