### ISSUE TITLE
希望添加视频剪辑功能

### ISSUE THREAD

**Issue by CherishSmile** [banchichen/TZImagePickerController#1330]
**问：你希望加什么新功能？**
答：希望添加视频剪辑功能

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：微信、QQ没有，但是UIImagePickerController，抖音，快手等app有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是。可以加属性开关，判断是否可以编辑。和UIImagePickerController一样

**其它你希望补充的内容**

**Comment by banchichen** [comment]
Duplicate of https://github.com/banchichen/TZImagePickerController/issues/830
