### ISSUE TITLE
微信图片选择器结构改了

### ISSUE THREAD

**Issue by zhaoyongjiang** [banchichen/TZImagePickerController#1332]
**问：你希望加什么新功能？**
答：微信图片选择器album列表是在photopicker中下拉展示的。不是nav-album-photo的层次了

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：恩

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合所有人

**其它你希望补充的内容**

**Comment by tzwgod** [comment]
自定义一下就好了呀

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1277
