### ISSUE TITLE
希望添加能直接进入拍照的功能

### ISSUE THREAD

**Issue by f624728887** [banchichen/TZImagePickerController#1334]
**问：你希望加什么新功能？**
答：希望添加能直接进入拍照的功能。

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：微信具有直接进入拍照的功能。

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合所有人，我认为应该加个属性开关。

**其它你希望补充的内容**

**Comment by banchichen** [comment]
hi，Demo有演示直接拍照的功能，直接用的UIImagePickerController，建议拷贝相关代码直接使用哈
