### ISSUE TITLE
iOS 14 beta2 相册“选中的照片”模式下 拍照 -> 使用图片 asset 为 nil 导致闪退

### ISSUE THREAD

**Issue by xtyHY** [banchichen/TZImagePickerController#1336]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版，否

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
iOS 14 beta2 “选中的照片”模式下拍照确定图片会闪退

**我如何复现这个bug？**
1. iOS 14 beta 1 / 2 均可
2. 照片权限为“选中的照片”
3. 拍照 -> 使用照片 （ 点击右下角“使用照片” 稍微快一点，不要停留 ）
4. 断点如图，如果断在上面一行的话，再执行 `asset` 一直都不会为nil

**截图**
截图为Demo直接跑的
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/15955583/87267507-7874a580-c4fa-11ea-9477-f333ee1208b6.png">

**其它说明**
权限为“所有照片”时不会出现，目测是隐私模式保存再读图的时候有点慢，如果操作间隔0.5-1s就不会出现，目前我这边本地暂时判了下空然后做了个延迟再取的处理

**Comment by banchichen** [comment]
👍

3.4.0已修复，适配了iOS14，建议尽快升级~
