### ISSUE TITLE
单选时图片右上角勾去掉

### ISSUE THREAD

**Issue by zhouzhiqiang1** [banchichen/TZImagePickerController#134]
可不可以在我只要单选的时候把右上角的勾去掉   和页面右下角的按钮也隐藏掉
然后在点击一张图片就回调回去？

**Comment by banchichen** [comment]
已支持单选模式..... 最新的commit：新增单选模式，设置maxImagesCount为1即可..  久等~

**Comment by zhouzhiqiang1** [comment]
你修改的代码应该没有更新到pods 上去我更新带1.6.1 代码TZAssetCell 里面没有 maxImagesCount

**Comment by banchichen** [comment]
是的，pod上还没有更新的~  最新的emo支持了~

**Comment by zhouzhiqiang1** [comment]
恩恩  谢了  期望尽快 pod更新

**Comment by banchichen** [comment]
好的，已经更新了~ 最新版本1.6.2~
