### ISSUE TITLE
希望添加一个直接打开相机的属性开关

### ISSUE THREAD

**Issue by liangfaliang** [banchichen/TZImagePickerController#1340]
**问：你希望加什么新功能？**
答：希望添加一个直接打开相机的属性开关

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：不是

**其它你希望补充的内容**

**Comment by banchichen** [comment]
建议参考demo里【把拍照按钮放在外面】设置项对应的代码，直接使用UIImagePickerController进行拍照哈
