### ISSUE TITLE
导航栏不见了，一片空白，底部布局混乱

### ISSUE THREAD

**Issue by MichaelSSY** [banchichen/TZImagePickerController#1342]
当present模态弹出 TZImagePickerController 的时候，导航栏不见了，而且TZImagePickerController 底部布局混乱，请问导航栏怎么设置出现呢？
![WechatIMG13](https://user-images.githubusercontent.com/17715591/88028775-ac3f7300-cb6b-11ea-8f42-e3b41aa77609.jpeg)

**Comment by banchichen** [comment]
发个最小可复现demo出来，我来看一下，或者把我的demo复现上

**Comment by banchichen** [comment]
可以参考下这些问题：
Q：设置导航栏颜色无效？导航栏颜色总是白色？
A：是否有集成WRNavigationBar？如有，参考其readme调一下它的wr_setBlackList，把TZImagePickerController相关的控制器放到黑名单里，使得不受WRNavigationBar的影响。如果没有集成，可在issues列表里搜一下看看类似的issue参考下，如实在没头绪，可加群提供个能复现该问题的demo，0~2天给你解决。最近发现WRNavigationBar的黑名单会有不生效的情况，临时解决方案大家可参考：https://github.com/wangrui460/WRNavigationBar/issues/145

Q：导航栏没了？
A：是否有集成GKNavigationBarViewController？需要升级到2.0.4及以上版本，详见issue：https://github.com/QuintGao/GKNavigationBarViewController/issues/7。
