### ISSUE TITLE
pod查询不到最新版本

### ISSUE THREAD

**Issue by Foryourself** [banchichen/TZImagePickerController#1344]
pod查询不到最新版本 只到3.3.1了 3.4.1搜不到，有点尬

**Comment by banchichen** [comment]
Q：pod search TZImagePickerController 搜索出来的不是最新版本
A：需要在终端执行cd转换文件路径命令退回到Desktop，然后执行pod setup命令更新本地spec缓存（可能需要几分钟）,然后再搜索就可以了
