### ISSUE TITLE
增加视频裁剪编辑功能

### ISSUE THREAD

**Issue by iOSchuang** [banchichen/TZImagePickerController#1345]
**问：你希望加什么新功能？**
答：增加视频长度、尺寸裁剪功能，类似微信视频号发布

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：短视频类APP越来越流行，有必要增加视频编辑的功能，完善框架功能

**其它你希望补充的内容**

**Comment by AlianOL** [comment]
所以，，这个功能有了么？

**Comment by mistak1992** [comment]
HXPhotoPicker有这些功能

**Comment by AlianOL** [comment]
> HXPhotoPicker有这些功能

嗯，我看下了，确实，多谢

**Comment by banchichen** [comment]
Duplicate of  https://github.com/banchichen/TZImagePickerController/issues/830
