### ISSUE TITLE
升级 iOS14之后的bug

### ISSUE THREAD

**Issue by Superyanggod** [banchichen/TZImagePickerController#1347]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有这个问题

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.1

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
iOS 14版本，调用相册，相册内容没有展示全，只展示了最近的一段时间的媒体内容

**我如何复现这个bug？**
目前只在pad端做了测试，pad必现，手机端还没有测试

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

相同的代码，在iOS14以下没有问题，之后就有问题

**Comment by fengyunjue** [comment]
测试最新Demo的时候，如果选择了Select More Photos时，未被选中的图片会显示空白，也没法选中。
![WX20200806-154505](https://user-images.githubusercontent.com/6801297/89505265-ee1f1900-d7fb-11ea-98ba-1453f6bff2b3.png)

**Comment by banchichen** [comment]
@fengyunjue 确定是github上下的最新Demo吗，旧版是有这个情况，3.4.1已经修复了...

**Comment by fengyunjue** [comment]
我测试的Demo就是用的3.4.1，我刚才又重新下载测试了，运行后还是出现了空白的情况

**Comment by banchichen** [comment]
@fengyunjue 老哥，帮忙稍微定位下？重点看下TZAssetCell里的setModel方法，看看图片是否取成功了，和imageView的尺寸、层级是否正常？

**Comment by banchichen** [comment]
@fengyunjue @Superyanggod 试试3.4.2哈，我今天升级Xcode到beta4版本，复现了类似的问题，3.4.2如还有问题的话，请帮忙提供更多信息哈

**Comment by fengyunjue** [comment]
我刚才使用xcode12 beta5测试demo，还是存在这个问题。6个照片，我只选择了4个照片在APP中显示，但是TZImagePicker列表里还是会显示6个，有两个是显示空白，我看了下TZAssetCell里的setModel方法里，获取图片失败了，在TZImageManager里获取UIImage的方法里info返回以下信息。
![image](https://user-images.githubusercontent.com/6801297/91128356-a1cc4800-e6da-11ea-87b8-24ea04f9a2d9.png)
![image](https://user-images.githubusercontent.com/6801297/91128844-7e55cd00-e6db-11ea-9942-a9d3d86c396c.png)
![image](https://user-images.githubusercontent.com/6801297/91128880-8dd51600-e6db-11ea-97e6-e03046b65e2f.png)

**Comment by banchichen** [comment]
@fengyunjue 是用的最新的Demo吗，TZImagePickerController.h最上面version那行是3.4.2吗？

**Comment by fengyunjue** [comment]
是的，是我刚刚下载的

**Comment by fengyunjue** [comment]
我刚才又用真机ios14测试了下，是正常的，只有模拟器有问题。

**Comment by banchichen** [comment]
模拟器这块有bug，我这的模拟器，即使只选了1张图片，也会显示出来6张，是相关的PhotosKit API返回就是如此，先以真机结果为准哈...

**Comment by fengyunjue** [comment]
嗯嗯，感谢
