### ISSUE TITLE
iOS 14视频拍摄后选择使用视频时发生崩溃

### ISSUE THREAD

**Issue by key-start** [banchichen/TZImagePickerController#1349]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：iOS14.0

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：未改动

**bug内容描述**
运行demo，选择拍摄视频，拍摄结束点击使用视频时发生崩溃，崩溃原因：    [_selectedAssetIds addObject:model.asset.localIdentifier];运行到这行代码时会因为插入内容为nil而崩溃

**我如何复现这个bug？**
在iOS14上运行demo，然后选择拍摄视频，然后点击使用视频。

**截图**
![image](https://user-images.githubusercontent.com/12524077/89769300-7a4c7b80-db2f-11ea-8330-863138de22b1.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
无

**Comment by banchichen** [comment]
3.4.2版本已修复，升级下哈
