### ISSUE TITLE
图片选择被覆盖问题

### ISSUE THREAD

**Issue by AllenHong007** [banchichen/TZImagePickerController#135]
第一次选中的图片显示到cell上后，若想再添加图片到cell上，则第一次所选中的所有图片都被清空，这是什么情况？

**Comment by banchichen** [comment]
你好，在Demo控制器的288行，TZImagePickerControllerDelegate协议方法的选择了图片的代理方法中，有2句代码：
    _selectedPhotos = [NSMutableArray arrayWithArray:photos];
    _selectedAssets = [NSMutableArray arrayWithArray:assets];
这里对数组进行了重新初始化，自然没有上次的值。需要有，你把这里改成:
    [_selectedPhotos addObjectsFromArray:photos];
如果你完全参照Demo来写，是不会有这个问题的，所有图片都会带回来：
在pushImagePickerController方法中记得传：
    imagePickerVc.selectedAssets = _selectedAssets; // optional, 可选的
传了这个，上次被选中的图片也会被带进去，选择了新图片后，旧的也会返回回来。
详情请参考Demo，Demo是好的。。。

这个问题居然会三番五次被拿出来问...

**Comment by AllenHong007** [comment]
谢谢啊，弄清楚了，是我自己太二了。。。初始化ImagePickerController的时候少写了imagePickerVc.selectedAssets = _selectedAssets这行代码，其他的都没问题！感谢大大提供这么牛逼的框架！赞一个！

**Comment by syf345894943** [comment]
> 谢谢啊，弄清楚了，是我自己太二了。。。初始化ImagePickerController的时候少写了imagePickerVc.selectedAssets = _selectedAssets这行代码，其他的都没问题！感谢大大提供这么牛逼的框架！赞一个！

牛逼个鸡儿
