### ISSUE TITLE
能不能添加显示和隐藏icloud云上照片的属性

### ISSUE THREAD

**Issue by pstkqzy** [banchichen/TZImagePickerController#1352]
**问：你希望加什么新功能？**
答：能不能添加显示和隐藏icloud云上照片的属性

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：未调查

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是，加上属性开关，更加灵活，满足更多人的需求

**其它你希望补充的内容**
因为icloud照片选用时间长，而且icloud也不太稳定，我这的需求需要屏蔽icloud照片，感觉加上这个功能更加

**Comment by banchichen** [comment]
这样的话，对于开启【自动上传照片到iCloud】的用户是个灾难，如果最近几个小时没拍照的话，在你的选择器几乎没有照片....
