### ISSUE TITLE
languageBundle 设置不起作用

### ISSUE THREAD

**Issue by SuiFengLiuNian** [banchichen/TZImagePickerController#1353]
XYImagePickerController *imagePickerVC = [[XYImagePickerController alloc]initWithMaxImagesCount:1 columnNumber:4 delegate:self pushPhotoPickerVc:YES];
    [imagePickerVC setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
        NSLog(@"photos:%@",photos);
        [weakSelf uploadUserImg:photos];
    }];
    imagePickerVC.naviBgColor = [UIColor groupTableViewBackgroundColor];
    imagePickerVC.naviTitleColor = [UIColor blackColor];
    imagePickerVC.statusBarStyle = UIStatusBarStyleDefault;
    imagePickerVC.barItemTextColor = [UIColor groupTableViewBackgroundColor];
    //设置首选语言
    imagePickerVC.preferredLanguage = @"en";
    //自定义语言 ja.lproj
    imagePickerVC.languageBundle = [NSBundle bundleWithPath:[[NSBundle mainBundle]pathForResource:@"ja" ofType:@"lproj"]];
    [[UIApplication sharedApplication].keyWindow.rootViewController presentViewController:imagePickerVC animated:YES completion:nil];

我这么写得，应该没问题，但是语言切换不到日语怎么回事？

**Comment by SuiFengLiuNian** [comment]
@Arthurli @tinpont @VincentSit @godera

**Comment by banchichen** [comment]
可以试试demo，demo应该是好的，你这个XYImagePickerController一看是改动过源码的，可以调试下tz_localizedStringForKey方法，看看[TZImagePickerConfig sharedInstance].languageBundle里的languageBundle是不是你设置的

**Comment by SuiFengLiuNian** [comment]
NSBundle </Users/apple/Library/Developer/CoreSimulator/Devices/9AFD407C-2CC5-4028-B43A-E0AC55CE25FF/data/Containers/Bundle/Application/6EE2E8C4-49E8-4217-84C9-2A3B70E0EF99/EC.app/ja.lproj> (not yet loaded)
(lldb) 

我具体查看了，bundle是对的，但是根据响应的key取得值是错误的，依旧是英文，我查看了demo，demo现在也是错误的，显示是英文   Allow TZImagePickerController to access your album in "Setting>privacy>photos" 这句话依旧没有切换语言

**Comment by banchichen** [comment]
hi，看了下是这样哈，应该只有这句话有问题，它的时机太靠前了，在languageBundle设置前就运行了
你可以这样哈，在TZImagePickerController初始化之前，这样设置languageBundle：
```
[TZImagePickerConfig sharedInstance].languageBundle = [NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:@"tz-ru" ofType:@"lproj"]];
```

**Comment by SuiFengLiuNian** [comment]
感谢你的回复，demo是可以的，我的代码不可以，我输出后
Printing description of bundle:
NSBundle </var/containers/Bundle/Application/53A9753D-537C-4C03-AF43-3A2020D32A64/EC.app/ja.lproj> (not yet loaded)
Printing description of key:
Done
Printing description of value1:
Done
bundle对，key对应，value值不对应，我还在查，很尴尬
