### ISSUE TITLE
maxVideoDurations 对从相册选的视频应该也约束。

### ISSUE THREAD

**Issue by chakbun** [banchichen/TZImagePickerController#1357]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是。

2、你用的是什么版本？升级到最新版后是否正常？
答：3.3.2，否。

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否。

**bug内容描述**
其实这个更偏向需求，
读取相册视频，可以设置maxVideoDurations 对视频长度限制，但这个属性对从相册选的视频没有约束。我认为应该对从相册选的视频也应该限制maxVideoDurations。

**我如何复现这个bug？**
设置了 maxVideoDurations = 30， 但视频选择时候可以选取超过30s的视频文件。

**截图**
应该不需要截图吧。

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
这个你参考Demo的isAssetCanSelect来实现哈

videoMaximumDuration有默认值是10分钟，拍视频合适，选视频不一定合适，还是分成2种设置方式吧

**Comment by chakbun** [comment]
> 这个你参考Demo的isAssetCanSelect来实现哈
> 
> videoMaximumDuration有默认值是10分钟，拍视频合适，选视频不一定合适，还是分成2种设置方式吧

好的，谢谢
