### ISSUE TITLE
建议支持是以列表展示相册还是直接展示所有图片

### ISSUE THREAD

**Issue by Cordeiring** [banchichen/TZImagePickerController#1359]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
老哥，你是这个意思吗？  https://github.com/banchichen/TZImagePickerController/issues/1332

**Comment by banchichen** [comment]
一打开默认就是进入的【所有照片】相册，就是直接展示所有照片的...
