### ISSUE TITLE
图片裁剪后保存到照片的功能

### ISSUE THREAD

**Issue by bianfu** [banchichen/TZImagePickerController#1362]
使用图片裁剪功能，通过- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray<UIImage *> *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto infos:(NSArray<NSDictionary *> *)infos方法返回的photos中图片和assets是不对应的， photos中是裁剪后的图，assets是原图。
裁剪后的图并没有保存到相册，并且在deleget方法中无法获知此图片是否被裁剪过。

**Comment by banchichen** [comment]
1、如果单选模式下设置的允许裁剪，则回调里的图片都是被裁剪过的，多选不支持裁剪
2、裁剪不会修改相册的，你可以试下微信、微博的裁剪功能，只作用于当次选择的
