### ISSUE TITLE
建议将定位权限和麦克风权限单独分出来

### ISSUE THREAD

**Issue by TokapoNzld** [banchichen/TZImagePickerController#1364]
**问：你希望加什么新功能？**
答：建议将定位权限和麦克风权限单独分出来

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：-

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：单独分个spec

**其它你希望补充的内容**

项目里面只是用到了选取照片的功能，但是框架有定位权限请求，目前来说提审是没什么问题，但是Apple会返邮件说明 App内添加了申请定位权限Key，但是App内并没有显式的有定位的功能，要求下个版本改掉，后期可能会导致被拒

**Comment by banchichen** [comment]
确实可以把拍照、拍视频功能，单独抽一个新库...

**Comment by winterwd** [comment]
+1

**Comment by Snail67** [comment]
+1

**Comment by hubfresher** [comment]
+1

**Comment by GJNan** [comment]
已经被拒了，项目确实没有用到定位功能，目前把plist里面相关定位的去掉了  反正不影响使用。

**Comment by qiangzai** [comment]
+1

**Comment by iOSSer** [comment]
确实，麦克风毕竟拍视频要用。定位这么敏感的权限加在这里面有何用？

**Comment by banchichen** [comment]
系统的相机App，拍的照片会存储定位信息的

**Comment by mizhousoft** [comment]
+1

**Comment by hardyZhi** [comment]
+1

**Comment by banchichen** [comment]
#https://github.com/banchichen/TZImagePickerController/issues/1354

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1354
