### ISSUE TITLE
当maxImagesCount=1并且allowPreview=NO时，仍可以进入预览图片界面

### ISSUE THREAD

**Issue by PamSun** [banchichen/TZImagePickerController#1366]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.2

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
当maxImagesCount=1并且allowPreview=NO时，仍可以进入预览图片界面

**我如何复现这个bug？**
在图片选择界面长按图片后松开，极可能会进入预览页，执行了didSelectItemAtIndexPath代理方法

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
已修复哈，新版本：3.4.3
