### ISSUE TITLE
选择单张照片无返回数据

### ISSUE THREAD

**Issue by ccccccccai** [banchichen/TZImagePickerController#1367]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：使用3.4.2demo测试有这个问题

2、你用的是什么版本？升级到最新版后是否正常？
答：使用3.4.2demo测试有这个问题

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有改动代码

**bug内容描述**
运行demo，修改最大选择张数为1，然后打开相册选择，点击一张后打开大图，点击done，页面dismiss  但照片数据未返回

**我如何复现这个bug？**

**截图**
![avatar](/Users/mac/Desktop/1.png)
![avatar](/Users/mac/Desktop/2.png)
![avatar](/Users/mac/Desktop/3.png)
![avatar](/Users/mac/Desktop/4.jpeg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by ccccccccai** [comment]
![1](https://user-images.githubusercontent.com/44076949/92209565-cd5fe700-eebf-11ea-81e9-283f7d791e2a.png)
![2](https://user-images.githubusercontent.com/44076949/92209578-d2249b00-eebf-11ea-8b92-897400e2a358.png)
![3](https://user-images.githubusercontent.com/44076949/92209585-d51f8b80-eebf-11ea-83de-288295d32d2e.png)
![4](https://user-images.githubusercontent.com/44076949/92209587-d650b880-eebf-11ea-9d38-c11f5b1e481c.jpeg)

**Comment by banchichen** [comment]
把Demo的这行设置注释掉就有了哈：
```objectivec
imagePickerVc.autoSelectCurrentWhenDone = NO;
```
