### ISSUE TITLE
选择图片设置allowPickingGif为NO时，依然能够选择gif

### ISSUE THREAD

**Issue by huangfangkai** [banchichen/TZImagePickerController#1368]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：会有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.2,否

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
此时是当成普通图片来选的哈，返回的是普通UIImage对象

**Comment by georgegrape** [comment]
这里发现还有个其他问题,就是当图片是gif格式的时候,点击图片后,图片就会被选中,然后页面直接返回

**Comment by banchichen** [comment]
@georgegrape 嗯，gif默认只能选一张，所以和视频一样，点选一张就完成了。需要多选的话，设置下allowPickingMultipleVideo为YES
