### ISSUE TITLE
相机icon替换，背景色修改逻辑判断有问题

### ISSUE THREAD

**Issue by RunzhuZhao** [banchichen/TZImagePickerController#1369]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本。

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
最新版本中takePictureImageName字段是不可以修改的，但是拍照cell背景色设置又根据takePictureImageName来判断。

**我如何复现这个bug？**
自定义takePictureImage传入，但是拍照cell的背景仍然为灰色
**截图**
![image](https://user-images.githubusercontent.com/70840468/92341389-21511280-f0f0-11ea-89a7-90ea120a7490.png)
![image](https://user-images.githubusercontent.com/70840468/92341416-35950f80-f0f0-11ea-94b0-ab3b8beecaa2.png)
![image](https://user-images.githubusercontent.com/70840468/92341492-7bea6e80-f0f0-11ea-9d1e-e4d723d5769b.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
嗯，这块不是很合理，你可以先把takePictureImageName设置成个别的值哈，先绕过这个问题，可以改的

**Comment by banchichen** [comment]
已修复哈，新版本：3.4.3
