### ISSUE TITLE
1.国际化 2.全选问题 3.选中原图的bug

### ISSUE THREAD

**Issue by Engandend** [banchichen/TZImagePickerController#137]
1.国际化 我看了 有其他人也提出这个问题，我做的app需要多国家语言，目前版本对于多国家语言支持比较低  只能自己一个一个对着慢慢找 还可能有问题 
2.  我的做app是需要照片的导入导出功能 ，这个时候 需要有全选功能  但是目前并不支持  我建议把TZImagePickerController中多添加一个属性  allowSelectAll 默认为no  如果主动改为了yes 可以把  TZPhotoPickerController右上角的取消按钮换成全选和取消全选
3.  在图片列表选中原图  进入预览  把原图取消  返回  不做任何操作 在进入 预览  原图又被选中了 
4.  在tableview的cell里面 又一个初始化  写错了 具体忘记了  好想食一个button还是imageview  写的是 if（a ＝ nil）  
｛return b；｝

5，如果选择很多照片 比如20或者100张  显示多少张的绿色圆点 就有问题

**Comment by banchichen** [comment]
1. 1.6.0版本刚刚加入了国际化~
2. 这个，下版加上~
3. 不会的~
4. 是的，还导致了一个问题，后面改了~
5. 是的，当时考虑的是最多选9张~  以后优化下~

**Comment by banchichen** [comment]
5. 这里优化了，但是2.... 全选的话，我在想在全选状态下，全选了后，点击确定去哪里~？....  全选模式下，我就不会主动去请求大图再返回了，全选后直接给你asset数组资源 ？对这样的交互我不是很熟悉...
