### ISSUE TITLE
单选视频的时候，预览页面没有大小显示

### ISSUE THREAD

**Issue by WangNingN** [banchichen/TZImagePickerController#1370]
1、选择视频的时候，进入到预览页面，没有大小显示
2、直接进入视频预览页面（不是从相册列表进入的），右下角的doneButton样式没法改
3、相册列表选择某一个视频或者图的时候，没有回调。比如我想显示5分钟的视频，但是用户选择的时候给个提示，这个没有回调。

**Comment by banchichen** [comment]
1、Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1169
2、欢迎PR，或者使用的时候还是包一个TZImagePickerController导航控制台，通过videoPreviewPageUIConfigBlock来改？
3、新版已解决，参考下isAssetCanBeSelected，有代理方法可以自定义了
