### ISSUE TITLE
iOS14,相册权限选择'选中的照片'

### ISSUE THREAD

**Issue by TungKamLau** [banchichen/TZImagePickerController#1371]
iOS新增加了可选择部分照片供app使用，当用户选择部分照片时，无法正常显示

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/1347
参考下这个issue哈，如是模拟器出现真机正常，则可以忽略

**Comment by TungKamLau** [comment]
> #1347
> 参考下这个issue哈，如是模拟器出现真机正常，则可以忽略

目前来看是真机有问题，目前版本3.3.1，cocoapods搜到的最新版本就是3.3.1

**Comment by banchichen** [comment]
你这不是最新版。。。

五. FAQ 常见问题
Q：pod search TZImagePickerController 搜索出来的不是最新版本
A：需要在终端执行cd转换文件路径命令退回到Desktop，然后执行pod setup命令更新本地spec缓存（可能需要几分钟）,然后再搜索就可以了
