### ISSUE TITLE
属性化此控制器，dissmiss不走630行的dealloc，是一个很明显的内存泄漏问题

### ISSUE THREAD

**Issue by 295060456** [banchichen/TZImagePickerController#1374]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
参考Demo用法，Demo控制器没有强引用该图片选择器，会释放

你如果强引用该选择器，那是否释放就由你控制了，建议不要这样
