### ISSUE TITLE
适配iOS14

### ISSUE THREAD

**Issue by Harryyan** [banchichen/TZImagePickerController#1379]
**问：你希望加什么新功能？**
答：希望在已有照片选择器上针对 “select photo”用户  添加 **重新选择** 按钮，方便用户在应用内从新赋予app访问更多照片的权限；而不是打开setting让用户选择 or 重启app再次选择。系统方法： PHPhotoLibrary.shared().presentLimitedLibraryPicker(from: self)
--

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：目前没有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合所有人

**Comment by mlch911** [comment]
+1

**Comment by hensonChang** [comment]
+1

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1390

**Comment by gdutxzy** [comment]
赞同
