### ISSUE TITLE
iOS 14适配相关

### ISSUE THREAD

**Issue by yehangithub** [banchichen/TZImagePickerController#1380]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：模拟器上有。

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.2

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
”select photo“模式下，选择三张图片可以访问，通过断点可以看到TZAlbumModel.count == 6（本地相册的所有图片数量)，点击空白图片返回后，collectionview展示的图片混乱，并且空白的图片也可以选中。

**我如何复现这个bug？**
选择 select photo 模式，选择一部分图片可供访问

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1347
