### ISSUE TITLE
iOS14选择iCloud视频，无法播放

### ISSUE THREAD

**Issue by CliffVardant** [banchichen/TZImagePickerController#1383]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有。

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版的demo。

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否。

**bug内容描述**
iOS 14选择iCloud的视频时，无法进行播放

**Comment by banchichen** [comment]
帮忙提供下更多信息哈，搜索下getVideoWithAsset方法，debug下是否有正常返回AVPlayerItem，是否有啥错误信息，播放是用的系统的AVPlayer

**Comment by BenTan123** [comment]
1，在iOS 14 AVPlayerItem 有正常返回 （<AVPlayerItem: 0x281330270, asset = <AVURLAsset: 0x28160c7c0, URL = file:///var/mobile/Media/PhotoData/Metadata/DCIM/109APPLE/IMG_9043.medium.MP4>> ）
没有错误信息。
2，Video 的url 可是用NSFileManager   fileExistsAtPath 查看此路径是否存在视频，返回来的是NO

**Comment by BenTan123** [comment]
而且这种问题只要在苹果相册里面打开一遍视频，再去获取视频问题就解决了，可是实际用户不会去那样操作，这个bug纠结了很多天了，帮忙看一下吧。

**Comment by banchichen** [comment]
目前只有你这有反馈，应该不是BUG，检查下是否给Demo工程开了网络权限，我这测试是OK的，如下面的视频
也可以试试还原网络设置、重新下载安装Demo...

![iOS14 iCloud视频播放 2020-10-11 13_51_51](https://user-images.githubusercontent.com/12755494/95671379-f5cab780-0bc8-11eb-8f8a-2367ee6fdca6.gif)

**Comment by SeriusXiang** [comment]
这个问题我也遇到了，请问有解决方案吗

**Comment by BenTan123** [comment]
> 这个问题我也遇到了，请问有解决方案吗

没有解决，不过使用requestPlayerItemForVideo 感觉会稍微好一点，我这个问题是在iphone X 上面比较容易复现 ，系统版本是iOS 14.

**Comment by SeriusXiang** [comment]
> > 这个问题我也遇到了，请问有解决方案吗
> 
> 没有解决，不过使用requestPlayerItemForVideo 感觉会稍微好一点，我这个问题是在iphone X 上面比较容易复现 ，系统版本是iOS 14.

好的。不过我这边不是需要获取视频播放，而需要做编辑处理。我的设备也是iPhone X，系统是iOS 14。我认为可能是iOS 14的问题。

**Comment by BenTan123** [comment]
> > > 这个问题我也遇到了，请问有解决方案吗
> > 
> > 
> > 没有解决，不过使用requestPlayerItemForVideo感觉会稍微好一点，我这个问题是在iphone X上面比较容易复现，系统版本是iOS 14。
> 
> 好的。不过我这边不是需要获取视频播放，而需要做编辑处理。我的设备也是iPhone X，系统是iOS14。我认为可能是iOS 14的问题。

通过 requestPlayerItemForVideo 也可以获取到  AVURLAsset *asset = (AVURLAsset *)playerItem.asset;  转一下就好了，你可以试一下

**Comment by SeriusXiang** [comment]
> > > > 这个问题我也遇到了，请问有解决方案吗
> > > 
> > > 
> > > 没有解决，不过使用requestPlayerItemForVideo感觉会稍微好一点，我这个问题是在iphone X上面比较容易复现，系统版本是iOS 14。
> > 
> > 
> > 好的。不过我这边不是需要获取视频播放，而需要做编辑处理。我的设备也是iPhone X，系统是iOS14。我认为可能是iOS 14的问题。
> 
> 通过 requestPlayerItemForVideo 也可以获取到 AVURLAsset *asset = (AVURLAsset *)playerItem.asset; 转一下就好了，你可以试一下

试过了，可以拿到AVURLAsset对象，但是拿到的AVURLAsset对象的duration都是0，无法播放，更别说编辑了。所以我才认为这个是苹果的bug

**Comment by BenTan123** [comment]
> > > > > 这个问题我也遇到了，请问有解决方案吗
> > > > 
> > > > 
> > > > 没有解决，不过使用requestPlayerItemForVideo感觉会稍微好一点，我这个问题是在iphone X上面比较容易复现，系统版本是iOS 14。
> > > 
> > > 
> > > 好的。不过我这边不是需要获取视频播放，而需要做编辑处理。我的设备也是iPhone X，系统是iOS14。我认为可能是iOS 14的问题。
> > 
> > 
> > 通过requestPlayerItemForVideo也可以获取到AVURLAsset * asset =（AVURLAsset *）playerItem.asset; 转一下就好了，你可以试一下
> 
> 试过了，可以拿到AVURLAsset对象，但是拿到的AVURLAsset对象的duration都是0，无法播放，更别说编辑了。所以我才认为这个是苹果的bug

一开始我也怀疑是苹果的bug，可是用微信来获取视频又是正常的，难道微信获取视频的方式不用苹果API 吗，我很好奇微信是怎么处理的。

**Comment by SeriusXiang** [comment]
> > > > > > 这个问题我也遇到了，请问有解决方案吗
> > > > > 
> > > > > 
> > > > > 没有解决，不过使用requestPlayerItemForVideo感觉会稍微好一点，我这个问题是在iphone X上面比较容易复现，系统版本是iOS 14。
> > > > 
> > > > 
> > > > 好的。不过我这边不是需要获取视频播放，而需要做编辑处理。我的设备也是iPhone X，系统是iOS14。我认为可能是iOS 14的问题。
> > > 
> > > 
> > > 通过requestPlayerItemForVideo也可以获取到AVURLAsset * asset =（AVURLAsset *）playerItem.asset; 转一下就好了，你可以试一下
> > 
> > 
> > 试过了，可以拿到AVURLAsset对象，但是拿到的AVURLAsset对象的duration都是0，无法播放，更别说编辑了。所以我才认为这个是苹果的bug
> 
> 一开始我也怀疑是苹果的bug，可是用微信来获取视频又是正常的，难道微信获取视频的方式不用苹果API 吗，我很好奇微信是怎么处理的。

对，微信确实没有问题。这个问题并非所有视频都存在，去相册先看过有问题的视频之后，获取就不再出现问题了。我用抖音和微信都试过，抖音也有类似问题，会直接提示从iCloud拉取失败，微信确实没有问题。所以我也很纳闷。或许微信是用的其他方式获取的。

**Comment by SeriusXiang** [comment]
> > > > > > > 这个问题我也遇到了，请问有解决方案吗
> > > > > > 
> > > > > > 
> > > > > > 没有解决，不过使用requestPlayerItemForVideo感觉会稍微好一点，我这个问题是在iphone X上面比较容易复现，系统版本是iOS 14。
> > > > > 
> > > > > 
> > > > > 好的。不过我这边不是需要获取视频播放，而需要做编辑处理。我的设备也是iPhone X，系统是iOS14。我认为可能是iOS 14的问题。
> > > > 
> > > > 
> > > > 通过requestPlayerItemForVideo也可以获取到AVURLAsset * asset =（AVURLAsset *）playerItem.asset; 转一下就好了，你可以试一下
> > > 
> > > 
> > > 试过了，可以拿到AVURLAsset对象，但是拿到的AVURLAsset对象的duration都是0，无法播放，更别说编辑了。所以我才认为这个是苹果的bug
> > 
> > 
> > 一开始我也怀疑是苹果的bug，可是用微信来获取视频又是正常的，难道微信获取视频的方式不用苹果API 吗，我很好奇微信是怎么处理的。
> 
> 对，微信确实没有问题。这个问题并非所有视频都存在，去相册先看过有问题的视频之后，获取就不再出现问题了。我用抖音和微信都试过，抖音也有类似问题，会直接提示从iCloud拉取失败，微信确实没有问题。所以我也很纳闷。或许微信是用的其他方式获取的。

我可能找到了这个问题的原因。并且我这里有一个解决方案：当获取的视频无法播放时，将PHVideoRequestOptions 的 deliveryMode 修改成 PHVideoRequestOptionsDeliveryModeHighQualityFormat，这是获取最高质量的视频，这样iCloud会重新去获取视频，再次获取到的视频可以使用。我猜想微信也是通过此方式来获取的iCloud视频。希望这个方法能帮助到大家。

**Comment by BenTan123** [comment]
> > > > > > > > 这个问题我也遇到了，请问有解决方案吗
> > > > > > > 
> > > > > > > 
> > > > > > > 没有解决，不过使用requestPlayerItemForVideo感觉会稍微好一点，我这个问题是在iphone X上面比较容易复现，系统版本是iOS 14。
> > > > > > 
> > > > > > 
> > > > > > 好的。不过我这边不是需要获取视频播放，而需要做编辑处理。我的设备也是iPhone X，系统是iOS14。我认为可能是iOS 14的问题。
> > > > > 
> > > > > 
> > > > > 通过requestPlayerItemForVideo也可以获取到AVURLAsset *资产=（AVURLAsset *）playerItem.asset; 转一下就好了，你可以试一下
> > > > 
> > > > 
> > > > 试过了，可以拿到AVURLAsset对象，但是拿到的AVURLAsset对象的duration都是0，无法播放，更别说编辑了。所以我才认为这个是苹果的bug
> > > 
> > > 
> > > 一开始我也怀疑是苹果的bug，可是用微信来获取视频又是正常的，难道微信获取视频的方式不用苹果API吗，我很好奇微信是怎么处理的。
> > 
> > 
> > 对，微信确实没有问题。这个问题并非所有视频都存在，去相册先看过有问题的视频之后，获取就不再出现问题了。我用抖音和微信都试过，抖音也有类似问题，会直接提示从iCloud拉取失败，微信确实没有问题。所以我也很纳闷。或许微信是用的其他方式获取的。
> 
> 我可能找到了这个问题的原因。并且我这里有一个解决方案：当获取的视频无法播放时，将PHVideoRequestOptions的deliveryMode修改为PHVideoRequestOptionsDeliveryModeHighQualityFormat，这是获取最高质量的视频，这样iCloud会重新去获取视频，再次获取到的视频可以使用。我猜想微信也是通过此方式来获取的iCloud视频。希望这个方法能帮助到大家。

好的谢谢，我试一下看看。

**Comment by JRJian** [comment]
> > > > > > > > 这个问题我也遇到了，请问有解决方案吗
> > > > > > > 
> > > > > > > 
> > > > > > > 没有解决，不过使用requestPlayerItemForVideo感觉会稍微好一点，我这个问题是在iphone X上面比较容易复现，系统版本是iOS 14。
> > > > > > 
> > > > > > 
> > > > > > 好的。不过我这边不是需要获取视频播放，而需要做编辑处理。我的设备也是iPhone X，系统是iOS14。我认为可能是iOS 14的问题。
> > > > > 
> > > > > 
> > > > > 通过requestPlayerItemForVideo也可以获取到AVURLAsset * asset =（AVURLAsset *）playerItem.asset; 转一下就好了，你可以试一下
> > > > 
> > > > 
> > > > 试过了，可以拿到AVURLAsset对象，但是拿到的AVURLAsset对象的duration都是0，无法播放，更别说编辑了。所以我才认为这个是苹果的bug
> > > 
> > > 
> > > 一开始我也怀疑是苹果的bug，可是用微信来获取视频又是正常的，难道微信获取视频的方式不用苹果API 吗，我很好奇微信是怎么处理的。
> > 
> > 
> > 对，微信确实没有问题。这个问题并非所有视频都存在，去相册先看过有问题的视频之后，获取就不再出现问题了。我用抖音和微信都试过，抖音也有类似问题，会直接提示从iCloud拉取失败，微信确实没有问题。所以我也很纳闷。或许微信是用的其他方式获取的。
> 
> 我可能找到了这个问题的原因。并且我这里有一个解决方案：当获取的视频无法播放时，将PHVideoRequestOptions 的 deliveryMode 修改成 PHVideoRequestOptionsDeliveryModeHighQualityFormat，这是获取最高质量的视频，这样iCloud会重新去获取视频，再次获取到的视频可以使用。我猜想微信也是通过此方式来获取的iCloud视频。希望这个方法能帮助到大家。

亲测可行
