### ISSUE TITLE
IOS13 出现状态栏相关bug

### ISSUE THREAD

**Issue by xuzeyu** [banchichen/TZImagePickerController#1386]
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：IOS13以上出现，采用最新版本

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.1

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没改动过代码

**bug内容描述**
1.IOS13以后，进入选择图片，再进入裁剪页面，返回选择图片页面时，状态栏出现错位现象，即你的导航栏会向上移动一个状态栏位置
2.IOS13以后，裁剪位置不准确，会向下偏移一个状态栏位置
具体原因查看其他说明

**我如何复现这个bug？**
info.plist文件 View controller-based status bar appearance 不填，或者设置为默认YES

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
以上两个bug都是因为ios13 [UIApplication sharedApplication].statusBarHidden 属性设置失效导致
请改成最新的状态栏隐藏显示的设置方法

裁剪位置偏移，很影响裁剪功能，望修正。

**Comment by banchichen** [comment]
你那Demo是好的吗？

我这Demo正常，你可以对比下哈

**Comment by xuzeyu** [comment]
第一个问题是我的添加的侧滑库FDFullscreenPopGesture，影响了显示问题，修改了后。裁剪位置还是向下偏移了。跟这个网址的人描述类似https://www.jianshu.com/p/05963e99dab5 。 你的最新demo我跑了一遍，没出现问题

**Comment by xuzeyu** [comment]
1.IOS13以后，进入选择图片，再进入裁剪页面，返回选择图片页面时，状态栏出现错位现象，即你的导航栏会向上移动一个状态栏位置
 这个问题已修正是我导入的第三库影响到了
2.IOS13以后，裁剪位置不准确，会向下偏移一个导航栏位置
这个问题还存在

最新demo下载不存在以上问题
