### ISSUE TITLE
iOS14 权限为选择照片 显示bug

### ISSUE THREAD

**Issue by adolph-suntao** [banchichen/TZImagePickerController#1387]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.3

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答： 没有

**bug内容描述**
iOS 14，模拟器。 选择照片，权限选择 “选择照片”。 然后选择一张图片。 点击确定后页面有多余的占位。并且预览图片返回后，出现重复图片。

**我如何复现这个bug？**
iOS 14，模拟器。 选择照片，权限选择 “选择照片”。 然后选择一张图片。 点击确定后页面有多余的占位。并且预览图片返回后，出现重复图片。

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by adolph-suntao** [comment]
图片链接:https://pan.baidu.com/s/1WBhBijsAEUsTdL5GEBjfpQ  密码:4k70

**Comment by banchichen** [comment]
关于iOS14模拟器的问题
PHAuthorizationStatusLimited授权模式下，iOS14模拟器有bug，未授权照片无法显示，真机正常，暂可忽略：https://github.com/banchichen/TZImagePickerController/issues/1347
