### ISSUE TITLE
如果项目hook了 dismiss 方法 会导致从相册选择图片无法回调代理的问题(包括block)

### ISSUE THREAD

**Issue by GitHubYYBS** [banchichen/TZImagePickerController#1388]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：最新的

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.3

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
给UIViewController 增加一个 分类并hook 系统的 "dismissViewControllerAnimated:completion:" 方法  会导致从相册选中图片后 代理及block 均不会回调了

**我如何复现这个bug？**
如 bug 描述  

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

建议作者代理方法的回调 及 block 的调用 不要放在 控制器dismiss中触发

**Comment by banchichen** [comment]
你hook了系统的方法，不会调用原实现吗？
