### ISSUE TITLE
支持全选或选择某个目录下的所有照片，支持滑动选择多张照片

### ISSUE THREAD

**Issue by WinJayQ** [banchichen/TZImagePickerController#1389]
**问：你希望加什么新功能？**
答：1）手指滑动选择多张照片
       2）支持全选或选择某个目录下的所有照片；全选后直接asset数组资源

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：1）滑动选择多张照片：QQ有该功能，微信没有
       2）支持全选或选择某个目录下的所有照片：QQ、微信没有该功能，但是这种需求还是很多人想要
**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：1）滑动选择多张照片：适合所有人，图片多的话不用一张张去选，比较方便
       2）支持全选或选择某个目录下的所有照片：不适合所有人，需要加个属性开关

**其它你希望补充的内容**

**Comment by banchichen** [comment]
需求过于小众，不会考虑支持哈
