### ISSUE TITLE
在iOS7 系统下面，用ALAsset取得的图片旋转顺序是错乱的

### ISSUE THREAD

**Issue by RicoCL** [banchichen/TZImagePickerController#139]
解决：在TZImageManager.m  line460 更改UIImageOrientationUp为(UIImageOrientation)assetRep.orientation

UIImage *originalImage = [UIImage imageWithCGImage:originalImageRef scale:1.0 orientation:(UIImageOrientation)assetRep.orientation];

**Comment by banchichen** [comment]
你好，我刚刚又仔细比对了几遍，发现使用UIImageOrientationUp也没有问题...  我测试了取assetRep.orientation也是没问题的，我还是改为assetRep.orientation吧~
