### ISSUE TITLE
类似QQ里面选择头像的图片选择器: “部分图片已经隐藏，前往设置”功能

### ISSUE THREAD

**Issue by changanli** [banchichen/TZImagePickerController#1390]
**问：你希望加什么新功能？**
答：添加一个按钮来选择更多图片。目前这个功能只是在打开App的时候会弹出，如果选择完了图片，就没有办法添加更多图片了，这个很不友好。

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：QQ里面的添加头像功能里面的图片选择器有一行字:部分图片已经隐藏，前往设置

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合所有人。可能文字需要自定义。

**其它你希望补充的内容**

**Comment by banchichen** [comment]
好想法，有没有人感兴趣提PR呀

有的话加readme里的钉钉群，欢迎一起共建呀

**Comment by gdutxzy** [comment]
这功能确实需要啊。我的老板和领导一直都说这是bug，为什么相册里一堆相片，app里就只能看到几张。

**Comment by gdutxzy** [comment]
我准备自己fork代码，自行随便找个地方放了个按钮 “更多照片”，然后调起 <PhotosUI/PHPhotoLibrary+PhotosUISupport.h>里的[[PHPhotoLibrary sharedPhotoLibrary] presentLimitedLibraryPickerFromViewController:self]。再然后用PHPhotoLibraryChangeObserver 观察是否有变化需要更新UI.

**Comment by banchichen** [comment]
3.8.0版本已增加「部分照片」权限状态下的提示，欢迎大家运行demo体验效果，验证效果OK的可进行升级
<img width="300" src="https://user-images.githubusercontent.com/12755494/161687321-eba4af8c-fe76-41af-ab08-8fe7aa247852.png" />

升级注意点：
1、为了降低多语言维护成本，移除了14个语言文件，目前剩余12个，这次的功能新增了2处文案，只更新了**简体中文、繁体中文、英语**，其余9个小众语言未更新，这2处文案会降级为显示英文文案，如有需要请大家再提PR，或通过languageBundle使用自定义的文案    
2、info.plist里要配置Prevent limited photos access alert，设置为true，可参考demo
