### ISSUE TITLE
多图片裁剪

### ISSUE THREAD

**Issue by W-hale** [banchichen/TZImagePickerController#1391]
我现在有个功能就是多图片裁剪，选完多图之后，然后这个图片数组一起裁剪，应该如何实现呢，如果一张一张裁剪，体验很差...谢谢指教

**Comment by banchichen** [comment]
可以找找相关的库哈

一起裁剪应该是不方便的，尺寸、宽高比不一样，不方便同时运用一个裁剪规则...

**Comment by W-hale** [comment]
我的裁剪尺寸固定的 就是那个正方形就行 正好需要一起裁剪

**Comment by banchichen** [comment]
可以找找相关的库哈，TZ目前不会支持这种方式
