### ISSUE TITLE
[self addSubview:_progressView]; 应该是 [self.contentView addSubview:_progressView];

### ISSUE THREAD

**Issue by zzzworm** [banchichen/TZImagePickerController#1392]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.4

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
TZAssetCell.m 文件
- (TZProgressView *)progressView {
    if (_progressView == nil) {
        _progressView = [[TZProgressView alloc] init];
        _progressView.hidden = YES;
        [self addSubview:_progressView];
    }
    return _progressView;
}

**我如何复现这个bug？**
[self addSubview:_progressView]; 应该是 [self.contentView addSubview:_progressView];

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
_progressView需要在最上面，如果是加在self.contentView上，每次显示时要bringSubviewToFront下才保险，没必要
