### ISSUE TITLE
【GIF问题】如何禁止选择GIF图片

### ISSUE THREAD

**Issue by mengxianliang** [banchichen/TZImagePickerController#1393]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.3，否 

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**其它说明**
allowPickingGif默认是NO，GIF图片会按照静态图片处理（这是现在的逻辑，我看你在其他issue里也是这么说明的）
我想在禁止选择GIF的时候，待选择列表里不显示GIF图片，就像禁止选择视频时，列表里不显示视频一样，该如何处理？

**Comment by banchichen** [comment]
试试isAssetCanSelect，可以参考下Demo

**Comment by mengxianliang** [comment]
好的感谢
