### ISSUE TITLE
通过请求iCloud 的图片或者适配资源 ，是否是下载到相册里面了

### ISSUE THREAD

**Issue by zhangbenwei** [banchichen/TZImagePickerController#1394]
通过请求iCloud 的图片或者适配资源 ，是否是下载到相册里面了？

每次获取都需要通过icloud  请求，这样很耗时间。直接下载到相册 ，这样会不会提升效率

**Comment by banchichen** [comment]
老哥，这是系统设置，用户可以选择是否把照片/视频存储到iCloud里，选择了存到iCloud里的才会在预览时需要下载，系统相册也是同样的效果

一些用户的相册可能十几甚至几十GB，本地存不下的

**Comment by github-liuxu** [comment]
> 老哥，这是系统设置，用户可以选择是否把照片/视频存储到iCloud里，选择了存到iCloud里的才会在预览时需要下载，系统相册也是同样的效果
> 
> 一些用户的相册可能十几甚至几十GB，本地存不下的

大佬，有计划给一个选项，让用户可以把iCloud视频下载到相册的计划吗？

**Comment by banchichen** [comment]
是否把iCloud视频下载到本地，完全由用户设置&系统机制决定，我们控制不了的
