### ISSUE TITLE
iOS13以上，加载单个iCloud视频完成后，只会dismiss掉iCloud提示弹窗，TZImagePickerController未dismiss

### ISSUE THREAD

**Issue by HuiZist** [banchichen/TZImagePickerController#1398]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.5 最新版

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
在iOS13&14上选择单个视频，如果该视频要从iCloud下载，点击cell之后弹出“iCloud下载”白色弹窗，加载完成后拿到asset，调用imagepicker dismiss 未消失

**我如何复现这个bug？**
找一个iOS13+，开启iCloud的手机，只要选择视频后出现“iCloud下载”白色弹窗，imagepicker就必定不会消失，即使调用了dismiss

**截图**
![image](https://user-images.githubusercontent.com/27760883/96108740-89c1b980-0f10-11eb-9773-c0da4999ef1d.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

经调试发现从iCloud下载资源，走到progressHandler弹出alertView，最后走到completion，虽然调用了hideAlertView，但是在iOS13上，alertView仍然存在，导致开启autoDismiss或者completion后续代理回调中调用了imagepicker dismiss，dismiss调的也只是alertView，而imagepickerVC仍然未消失

**Comment by banchichen** [comment]
3.4.9修复了哈
