### ISSUE TITLE
照片会重复选择

### ISSUE THREAD

**Issue by tot1987** [banchichen/TZImagePickerController#14]
一张图片能多次被选择，😄辛苦了

**Comment by banchichen** [comment]
你好，图片被多次选择的情况有2种。一. 调起imagePicker添加了图片后，再次调起继续添加，这里没有判断该照片是否已被选择过，可能会多次选择。微信也是这样子的，没有做特殊处理，微博这里倒是做了一些优化，但是这样的话，使用起来就复杂一点~每次调用imagePicker的时候，你得传给我一个数组，告诉我现在用户选择好的照片是哪些。。。我才能在imagePicker里面做判断~  所以这里我还没做的~   二、切换相册，同一张照片可能被多次选择。这个我也是照微信的效果做的~QQ空间倒是做了处理的~

**Comment by tot1987** [comment]
:+1:
