### ISSUE TITLE
tz_statusBarHeight错误

### ISSUE THREAD

**Issue by JockerLUO** [banchichen/TZImagePickerController#1400]
+ (CGFloat)tz_statusBarHeight {
    if ([UIWindow instancesRespondToSelector:@selector(safeAreaInsets)]) {
        return [self tz_safeAreaInsets].top > 0 ?: 20;
    }
    return 20;
}
“[self tz_safeAreaInsets].top > 0 ?: 20;“这应改为 “[self tz_safeAreaInsets].top ?: 20;“
不然iPhoneX上 tz_statusBarHeight 为 1

**Comment by banchichen** [comment]
见笑了...
已修复哈，3.4.7
