### ISSUE TITLE
相册截图bug

### ISSUE THREAD

**Issue by JockerLUO** [banchichen/TZImagePickerController#1401]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.6

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**
相册 TZPhotoPickerController 界面截图，
回调  - (void)photoLibraryDidChange:(PHChange *)changeInstance，
调用 - (void)fetchAssetModels，
再调用 - (void)initSubviews，
继续调用 - (void)configBottomToolBar，
会创建多个 _bottomToolBar，底部会有多层_bottomToolBar

**我如何复现这个bug？**
相册截图就会出现

**截图**
![image](https://user-images.githubusercontent.com/28944925/96326519-e1bd0500-1063-11eb-9a5c-1c9838f32608.png)

**Comment by banchichen** [comment]
已修复哈，3.4.7
