### ISSUE TITLE
iOS 14 backBarButtonItem

### ISSUE THREAD

**Issue by smqh-github** [banchichen/TZImagePickerController#1402]
iOS14 改变 了 backBarButtonItem 工作机制，
在非调试模式下，存在 crash 问题，请知悉。

**Comment by WuZhuoXuan** [comment]
我也遇到这个问题

**Comment by WuZhuoXuan** [comment]
TZPhotoPickerController  102行 改成
     UIBarButtonItem *backItem = [[UIBarButtonItem alloc] initWithTitle:[NSBundle tz_localizedStringForKey:@"Back"] style:UIBarButtonItemStylePlain target:self action:@selector(navLeftBarButtonClick)];
        [TZCommonTools configBarButtonItem:backItem tzImagePickerVc:tzImagePickerVc];
        self.navigationItem.leftBarButtonItem = backItem;
就不闪退了

**Comment by shijinliang** [comment]
同样遇到这个问题了，直接run调试的时候是正常的，但是在手机上单独操作就是不行

**Comment by WuZhuoXuan** [comment]
改过没 ，改过代码是不会闪退的

**Comment by shijinliang** [comment]
> 改过没 ，改过代码是不会闪退的

按照你的方法先改了👍

**Comment by SingKing1987** [comment]
哇！！！我也是直接run调试没问题，断开手机单独操作crash，想不到在这里找到答案，还看了log文件，死活看不出问题，感谢楼上大佬！

**Comment by SingKing1987** [comment]
顺便问一句，为什么调试模式并不会，真机ios14.2，连着不crash，拔掉单独运行crash

**Comment by SingKing1987** [comment]
这样改法兼容其他ios版本吗

**Comment by banchichen** [comment]
这个我这一直没复现...
102行改成这个了：UIBarButtonItem *backItem = [[UIBarButtonItem alloc] initWithTitle:[NSBundle tz_localizedStringForKey:@"Back"] style:UIBarButtonItemStylePlain target:self action:@selector(navLeftBarButtonClick)];
已发新版：3.6.6
