### ISSUE TITLE
如何多次调用isAssetCanSelect来实时刷新TZPhotoPickerController展示的图片？

### ISSUE THREAD

**Issue by xiaowasly** [banchichen/TZImagePickerController#1403]
正在做一个要显示全部文件 已上传文件 的需求  isAssetCanSelect只能同步进来的第一次，我如何再次触发isAssetCanSelect来更新照片显示？谢谢

**Comment by banchichen** [comment]
想办法触发下TZPhotoPickerController里fetchAssetModels的调用

**Comment by xiaowasly** [comment]
> 想办法触发下TZPhotoPickerController里fetchAssetModels的调用

好的，非常感谢您的回复，膜拜一波。
