### ISSUE TITLE
授权部分图片，返回时，图片重复，出现空白图片

### ISSUE THREAD

**Issue by AgoniNemo** [banchichen/TZImagePickerController#1404]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.8

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
图片重复，出现空白图片

**我如何复现这个bug？**
授权时，选择图片，只授权三张图片，返回时，出现图片重复，空白图片

**截图**
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-21 at 17 45 46](https://user-images.githubusercontent.com/13228978/96703409-65108a80-13c5-11eb-9bc7-bd831ce2ad78.png)

![Simulator Screen Shot - iPhone 11 Pro](https://user-images.githubusercontent.com/13228978/96702822-b8cea400-13c4-11eb-8886-271f84e6a72a.png)

**其它说明**
初始化如下：
```
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:9 columnNumber:1 delegate:self pushPhotoPickerVc:YES];
 
imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen;
[self presentViewController:imagePickerVc animated:YES completion:nil];
```

**Comment by banchichen** [comment]
见readme：

PHAuthorizationStatusLimited授权模式下，iOS14模拟器有bug，未授权照片无法显示，真机正常，暂可忽略：https://github.com/banchichen/TZImagePickerController/issues/1347
