### ISSUE TITLE
getAllAlbums方法内部传递参数缺省 获得相册/相册数组无法获取模型中无视频models

### ISSUE THREAD

**Issue by pirder** [banchichen/TZImagePickerController#1405]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：demo中是无问题的，因为这是自己ViewController: `UIViewController,TZImagePickerControllerDelegate` 继承了delgate 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/29139348/96996314-3bd93100-1562-11eb-98c2-dc96c7d305f2.png">

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本，否

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
- (void)getAllAlbums:(BOOL)allowPickingVideo allowPickingImage:(BOOL)allowPickingImage needFetchAssets:(BOOL)needFetchAssets completion:(void (^)(NSArray<TZAlbumModel *> *models))completion;
这个方法中 留意到是存在allowPickingVideo参数来决定是否能够加载视频的 但是在后面的传递中
<img width="818" alt="image" src="https://user-images.githubusercontent.com/29139348/96996640-c6ba2b80-1562-11eb-8c13-f9fdbfc00ae5.png">
- (TZAlbumModel *)modelWithResult:(PHFetchResult *)result collection:(PHAssetCollection *)collection isCameraRoll:(BOOL)isCameraRoll needFetchAssets:(BOOL)needFetchAssets options:(PHFetchOptions *)options ;
<img width="889" alt="image" src="https://user-images.githubusercontent.com/29139348/96999426-b8224300-1567-11eb-88c2-8266827d9399.png">
此方法 中的 model的处理是使用- (void)getAssetsFromFetchResult:(PHFetchResult *)result completion:(void (^)(NSArray<TZAssetModel *> *))completion;的方法该方法中
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/29139348/96999469-c4a69b80-1567-11eb-837e-779dfd71768d.png">

    TZImagePickerConfig *config = [TZImagePickerConfig sharedInstance];
    return [self getAssetsFromFetchResult:result allowPickingVideo:config.allowPickingVideo allowPickingImage:config.allowPickingImage completion:completion]; 却采用了TZImagePickerConfig sharedInstance中的值 并不会 使用getAllAlbums该函数的参数传递 

**我如何复现这个bug？**
拿到的相册模型中 count是存在的 models中是没有这个 用我提供的zip中的vc和cell是可以重现的

**截图**
<img width="883" alt="demo1测试" src="https://user-images.githubusercontent.com/29139348/96998882-e2bfcc00-1566-11eb-9861-80244d7871c8.png">
这是我修改过后的
<img width="939" alt="demo1测试完成修改后" src="https://user-images.githubusercontent.com/29139348/96998890-e81d1680-1566-11eb-99ef-19152b967723.png">

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
[VCAndCell.zip](https://github.com/banchichen/TZImagePickerController/files/5429176/VCAndCell.zip)

**Comment by pirder** [comment]
按照逻辑来 没有设置[TZImagePickerConfig sharedInstance]中的allowPickingVideo是无法实现加载models中的视频

**Comment by banchichen** [comment]
嗯，TZImagePickerConfig是后面新增的

目前优化了下：https://github.com/banchichen/TZImagePickerController/commit/333e33245693291c473ef38a90030e21320624fb
加了个deprecated提示，提醒使用新的方法和TZImagePickerConfig
