### ISSUE TITLE
xcode12，iOS14选择照片后点击完成，dissmiss不了，卡在正在处理

### ISSUE THREAD

**Issue by yaolove3** [banchichen/TZImagePickerController#1406]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.9

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
选择照片后点击完成，dissmiss不了，卡在正在处理

**我如何复现这个bug？**
在demo里面，选择照片后点击完成

**截图**
![image](https://user-images.githubusercontent.com/18161544/97408852-acec6000-1937-11eb-8d48-48861317e07a.png)

**其它说明**
xcode12，iOS14

**Comment by BigPoro** [comment]
我这边也出现了，真机版本14.0.1

**Comment by iOScc** [comment]
我也遇到了，我用cocoapods集成到我自己的demo上后， 在真机上跑 iOS12， 也会出现同样的问题，选完照片以后，点击完成 就会出现

**Comment by kidneyband** [comment]
same problem here

**Comment by banchichen** [comment]
3.5.0已修复哈
