### ISSUE TITLE
最新demo选择照片，点击完成后只转圈

### ISSUE THREAD

**Issue by iOScc** [banchichen/TZImagePickerController#1407]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是最新

2、你用的是什么版本？升级到最新版后是否正常？
答：最新

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
demo下载下来后 直接在模拟器运行 iPhone 11 Pro Max，系统iOS14.0，点击demo首页的加号按钮去选照片，不管选几张，点击完成只有加载中...过几秒加载动画消失，然后并没有任何反应。

**我如何复现这个bug？**
下载demo，直接运行

**截图**
![1531603874284_ pic_hd](https://user-images.githubusercontent.com/17263394/97412104-11112300-193c-11eb-9ede-c505f48f399a.jpg)
![1541603874298_ pic](https://user-images.githubusercontent.com/17263394/97412123-18d0c780-193c-11eb-8c24-6bf929ab5b79.jpg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
3.5.0已修复哈

**Comment by liufeng0504** [comment]
@banchichen 真机 iOS 9.3.5 仍存在这个问题，请问是什么原因造成的，我应急先改一下，谢谢。

**Comment by banchichen** [comment]
@liufeng0504 可能需要你调试看下，确认是3.5.0及以上版本的话，应该是不会再出现这个问题的

**Comment by liufeng0504** [comment]
@banchichen 我尝试把pods全部删除从新安装，现在已经好了，非常感谢你的回复。
