### ISSUE TITLE
设置了裁剪正方形区域，比裁剪区域大的正方形图片没办法完整的放进裁剪区域内

### ISSUE THREAD

**Issue by winterwd** [banchichen/TZImagePickerController#1408]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.5.0

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
正方形图片没办法完整的放进裁剪区域内

**我如何复现这个bug？**
iPhone11Pro 模拟器，选择一张400x400(大于裁剪区域都可以)的图片，进行裁剪，图片没办法完整的放进裁剪区域内

**截图**
<img width="379" alt="iShot2020-10-28 18 03 01" src="https://user-images.githubusercontent.com/14071671/97425380-0612be80-194d-11eb-8631-9676bea8a401.png">

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
没有

**Comment by winterwd** [comment]
附上 图片下载 地址：[测试图片下载地址](https://dss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=3845316197,2129479838&fm=111&gp=0.jpg)

**Comment by banchichen** [comment]
不支持缩小图片的
