### ISSUE TITLE
使用裁剪框时，图片比边框大

### ISSUE THREAD

**Issue by ccccccccai** [banchichen/TZImagePickerController#1409]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.5.0的demo进行测试

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
图片大于裁剪框，导致图片裁剪不全，能否让照片边缘贴近裁剪框。

**我如何复现这个bug？**
运行后点击-单选模式下允许裁剪，然后点击加号进入照片裁剪页面，照片明显大于裁剪框。

**截图**
![264D02D0A7E8E3EEF4B76F86C4BFDC54](https://user-images.githubusercontent.com/44076949/97464126-7afced00-197b-11eb-96fc-8ca50d71e05d.jpg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by ccccccccai** [comment]
![264D02D0A7E8E3EEF4B76F86C4BFDC54](https://user-images.githubusercontent.com/44076949/97464564-08d8d800-197c-11eb-86ab-3d6b8eb95339.jpg)

**Comment by ccccccccai** [comment]
![264D02D0A7E8E3EEF4B76F86C4BFDC54](https://user-images.githubusercontent.com/44076949/97464815-59503580-197c-11eb-9a8d-ae53217b928d.jpg)

**Comment by ccccccccai** [comment]
![264D02D0A7E8E3EEF4B76F86C4BFDC54](https://user-images.githubusercontent.com/44076949/97464947-7dac1200-197c-11eb-893e-2def9b85e923.jpg)

**Comment by banchichen** [comment]
不支持缩小图片...

如确有需要，欢迎提个PR...
