### ISSUE TITLE
cocoapods上没有3.4.7版本

### ISSUE THREAD

**Issue by Xiaoyouyou** [banchichen/TZImagePickerController#1410]
pod管理，最新的之后3.4.4版本。没有3.4.7版本

**Comment by banchichen** [comment]
Q：pod search TZImagePickerController 搜索出来的不是最新版本
A：需要在终端执行cd转换文件路径命令退回到Desktop，然后执行pod setup命令更新本地spec缓存（可能需要几分钟）,然后再搜索就可以了
