### ISSUE TITLE
弱网情况下，选择iCloud照片，连续快速点击完成，会多次调用选择图片完成的回调

### ISSUE THREAD

**Issue by zkfpk6** [banchichen/TZImagePickerController#1412]
_doneButton.enabled = NO;
也拦不住，救命

**Comment by banchichen** [comment]
@zkfpk6 最新版Demo也这样吗？

**Comment by zkfpk6** [comment]
> @zkfpk6 最新版Demo也这样吗？

您好，最新版的demo也会有这个问题，而且在doneButtonClick里面的showProgressHUD并不展示loading图

**Comment by banchichen** [comment]
[弱网选择iCloud照片.mov.zip](https://github.com/banchichen/TZImagePickerController/files/5491640/iCloud.mov.zip)
如上视频，我这是好的...

**Comment by zkfpk6** [comment]
[https://github.com/zkfpk6/YGFlyCommentManager-Danmaku/raw/zkfpk6-patch-1/1604545501249970.mp4.zip](url)
您好，我这暂时没复现出这个问题，但是复现出了loading消失的问题，导致在拉取iCloud图片过程中可以继续点选其他图片并点击完成的问题

**Comment by zkfpk6** [comment]
https://github.com/zkfpk6/YGFlyCommentManager-Danmaku/blob/zkfpk6-patch-1/1604545501249970.mp4.zip
您好，我这暂时没复现出这个问题，但是复现出了loading消失的问题，导致在拉取iCloud图片过程中可以继续点选其他图片并点击完成的问题

**Comment by zkfpk6** [comment]
https://github.com/zkfpk6/YGFlyCommentManager-Danmaku/raw/zkfpk6-patch-1/1604545501249970.mp4.zip
您好，烦请查看这个视频

**Comment by zkfpk6** [comment]
问题已定位，当选择的iCloud图片下载完成一张的时候，TZPhotoPickerController的initSubviews方法会hideProgressHUD，导致loading直接消失，之后再操作就会有问题

**Comment by banchichen** [comment]
👍

@zkfpk6 已修复哈，提交到master了，帮忙拿最新Demo验证下哈。最近会发版

如果还发现HUD会消失，应该是超时导致，可以选择把timeout调大，默认是30秒后会隐藏HUD

**Comment by zkfpk6** [comment]
> 👍
> 
> @zkfpk6 已修复哈，提交到master了，帮忙拿最新Demo验证下哈。最近会发版
> 
> 如果还发现HUD会消失，应该是超时导致，可以选择把timeout调大，默认是30秒后会隐藏HUD

好的非常感谢及时调试，那个我也注意到了已经改大了一些

**Comment by banchichen** [comment]
3.5.2已发布哈
