### ISSUE TITLE
更细cocoapods的版本呀

### ISSUE THREAD

**Issue by NiuYangYang** [banchichen/TZImagePickerController#1418]

**Comment by banchichen** [comment]
Q：pod search TZImagePickerController 搜索出来的不是最新版本
A：需要在终端执行cd转换文件路径命令退回到Desktop，然后执行pod setup命令更新本地spec缓存（可能需要几分钟）,然后再搜索就可以了

**Comment by NiuYangYang** [comment]
![image](https://user-images.githubusercontent.com/19486884/98619553-6f77d180-233e-11eb-8a8f-3202ad74568e.png)

**Comment by NiuYangYang** [comment]
Podfile.lock并没有变化, Podfile.lock删了重新install也是一样

**Comment by NiuYangYang** [comment]
- TZImagePickerController (3.4.5)

**Comment by banchichen** [comment]
1、podfile里 TZImagePickerController 是否有指定版本号？
2、有Podfile.lock的情况下你install是不可能更新版本的，要执行pod update

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/98637915-16229900-2364-11eb-9259-2836203ade4a.png)
