### ISSUE TITLE
预览图片取消图片的选择，点击完成还会有图片返回

### ISSUE THREAD

**Issue by ZackDT** [banchichen/TZImagePickerController#1420]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新的版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有，pod管理的。demo也有

**bug内容描述**
选择图片，点击图片进入预览界面，在预览界面取消所选择的图片。显示没有 选择的 图片，完成按钮前面没有数字按钮。可以机选点击完成按钮，而且会返回选中的最后一个张图片

**我如何复现这个bug？**

**截图**
![41604995872_ pic](https://user-images.githubusercontent.com/15107710/98647140-6521fb80-236f-11eb-986d-7473bcf3032c.jpg)
![21604995870_ pic](https://user-images.githubusercontent.com/15107710/98647156-6bb07300-236f-11eb-974c-49279614bdbb.jpg)
![31604995871_ pic](https://user-images.githubusercontent.com/15107710/98647169-70752700-236f-11eb-97e9-aef3772168ee.jpg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/812
