### ISSUE TITLE
支持图片大小选择限制

### ISSUE THREAD

**Issue by RunzhuZhao** [banchichen/TZImagePickerController#1421]
**问：你希望加什么新功能？**
答：选择图片时可以根据设置大小限制是否可选，在列表以及预览页选择图片。可区分静态图和GIF图大小

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：否，加属性开关

**其它你希望补充的内容**

**Comment by banchichen** [comment]
参考Demo实现isAssetCanSelect

**Comment by RunzhuZhao** [comment]
谢谢，已了解isAssetCanSelect的实现。提的功能倾向的是列表可以展示图片，但是点击的时候会进行图片大小判断，可toast提示。


------------------&nbsp;Original&nbsp;------------------

**Comment by banchichen** [comment]
这个能力暂时没有哈

有些需要toast，有些需要alert，有些需要置灰不可点，加一个新特性改动不小...
