### ISSUE TITLE
iOS14 ipad 上授权照片后 会弹出系统 弹框。

### ISSUE THREAD

**Issue by 874516119** [banchichen/TZImagePickerController#1423]
ipad 上授权照片后 会弹出系统 弹框。
第一次授权时必现问题

**Comment by banchichen** [comment]
老哥，截个图看下

**Comment by 152016726** [comment]
> 老哥，截个图看下

添加原生框架中所需的 bundle 文件,node_modules包里没有那个node_modules/react-native-syan-image-picker/ios/TZImagePickerController/TZImagePickerController.bundle，倒是在ios的Pods文件夹下有找到这个，但不能添加上去啊

**Comment by banchichen** [comment]
@152016726 可以去问问react-native-syan-image-picker的作者哈，然后不添加的话功能正常吗？
