### ISSUE TITLE
选择完成的时候可以获取地址

### ISSUE THREAD

**Issue by cnjsyyb** [banchichen/TZImagePickerController#1424]
**问：你希望加什么新功能？**
答：选择完成的时候可以获取图片和视频地址

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：开发flutter插件需要

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是，希望可以加个属性开关，谢谢啦

**其它你希望补充的内容**

**Comment by banchichen** [comment]
如QQ沟通，需要自行把图片存到沙盒、视频导出到沙盒哈。
