### ISSUE TITLE
选择图片下完成按钮左侧数字是否也可以支持点击？

### ISSUE THREAD

**Issue by leejnull** [banchichen/TZImagePickerController#1425]
**问：你希望加什么新功能？**
答：完成按钮左侧数字label支持点击

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：我看微信上是数字和完成是一个按钮上的title

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：我们测试跟我反映说，经常点完成按钮没有反应，最后发现是数字和按钮是分开的两个控件的原因，这里觉得放在一起会比较合适，大多数人都会以为完成按钮的可点击区域会包括左侧数字

**其它你希望补充的内容**

**Comment by YourReference** [comment]
附议

**Comment by AppLog** [comment]
附议
我们测试MM给我提了个Bug

**Comment by banchichen** [comment]
有哥们提了pr，3.5.9版本已优化，大家可以试下
