### ISSUE TITLE
使用getOriginalPhotoDataWithAsset获取原图Data后,图片被旋转了,请问有办法解决吗?

### ISSUE THREAD

**Issue by a497500306** [banchichen/TZImagePickerController#1428]
使用getOriginalPhotoDataWithAsset获取原图Data后,直接把data上传给oss, 发现图片出现了旋转
如果使用getOriginalPhotoWithAsset,然后把photo转Data, 那么原图大小与框架选择原图时大小不一致,
请问有什么方法解决该问题吗?

**Comment by banchichen** [comment]
使用UIImageJPEGRepresentation(image, 0.9)得到NSData，大小就基本一致了
