### ISSUE TITLE
在iPhone12上系统版本14.2.1

### ISSUE THREAD

**Issue by moling5463** [banchichen/TZImagePickerController#1429]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有，刚刚下载demo试验过了

2、你用的是什么版本？升级到最新版后是否正常？
答：3.4.2和3.5.3

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：无

**bug内容描述**
图片选择界面上面显示不完整

**我如何复现这个bug？**
直接调用即可

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by moling5463** [comment]
![IMG_0586](https://user-images.githubusercontent.com/30916223/100585253-3c66a380-3328-11eb-98b1-727017780853.PNG)

**Comment by moling5463** [comment]
imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen;

**Comment by banchichen** [comment]
我这未能复现，有对Demo做什么设置吗？
