### ISSUE TITLE
TZImageManager.m 723 行 得到视频原始文件地址有问题

### ISSUE THREAD

**Issue by Nonable** [banchichen/TZImagePickerController#1432]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：应该有。没有使用

2、你用的是什么版本？升级到最新版后是否正常？
答：3.5.5

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
得到视频原始文件地址有问题，选择视频一直返回error

**我如何复现这个bug？**
通过 (PHAsset *)asset 获取视频原始文件地址

**截图**

**其它说明**
修改：
if ([asset isKindOfClass:[AVURLAsset class]]) {

->

if ([avasset isKindOfClass:[AVAsset class]]) {

**Comment by banchichen** [comment]
慢视频文件是AVComposition对象，没有URL

**Comment by Nonable** [comment]
如果用传进来的 asset 来判断 是不是 就一直不会进if里？一直走else 的error 了么？

**Comment by Nonable** [comment]
if ([asset isKindOfClass:[AVURLAsset class]]) {

->

if ([avasset isKindOfClass:[AVURLAsset class]]) {

这样修改呢？

**Comment by banchichen** [comment]
确实这里搞错了...  新版本3.5.6哈

**Comment by Nonable** [comment]
好嘞~
