### ISSUE TITLE
希望添加一个选择视频长度限制属性

### ISSUE THREAD

**Issue by huangfangkai** [banchichen/TZImagePickerController#1436]
**问：你希望加什么新功能？**
答：

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
参考Demo自己实现下isAssetCanBeSelected或者isAssetCanBeDisplayed
