### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by huangfangkai** [banchichen/TZImagePickerController#1437]
**问：你希望加什么新功能？**
答：添加一个选择视频时长度限制

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1436
