### ISSUE TITLE
导航栏上的 Item 高亮状态字体显示问题

### ISSUE THREAD

**Issue by windorz9** [banchichen/TZImagePickerController#1444]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答: 最新版本代码 Demo. 手机 ip6 系统版本 12.4.8. ip7 系统版本 13.1.3.

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答:没有

**bug内容描述**
导航栏上的 item 高亮状态下的字体问题

**我如何复现这个bug？**
长按导航栏上的 Item 进入高亮状态就可以复现, 问题在这个 + (void)configBarButtonItem:(UIBarButtonItem *)item tzImagePickerVc:(TZImagePickerController *)tzImagePickerVc 方法里面, 只设置了普通状态下的 item 属性, 长按进入高亮状态后, 字体大小发生明显的变化.

**截图**
![IMG_3661](https://user-images.githubusercontent.com/21336297/102567281-245e9480-411c-11eb-9daf-bd6c4da7b7eb.PNG)
![IMG_3663](https://user-images.githubusercontent.com/21336297/102567287-29234880-411c-11eb-966c-126b0c7be8fe.PNG)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
不知道这算不算 bug. 使用过程当中看效果试出来的, 解决方案就是在配置 configBarButtonItem 也设置一下高亮状态的 item

**Comment by banchichen** [comment]
3.6.6已修复哈
