### ISSUE TITLE
iOS14 系统 第一次进入，授权保存图片后，在调用图片选择器，出现弹出卡顿，并且图片加载不出来

### ISSUE THREAD

**Issue by shuleihen** [banchichen/TZImagePickerController#1445]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：
NO
2、你用的是什么版本？升级到最新版后是否正常？
答：
3.4.8
3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：
NO
**bug内容描述**
iOS14 系统 第一次进入，授权保存图片后，在调用图片选择器，出现弹出卡顿，并且图片加载不出来
![WechatIMG2](https://user-images.githubusercontent.com/2232053/102570390-32afaf00-4122-11eb-9476-a63ea549e241.jpeg)

**我如何复现这个bug？**
iOS14系统，在设置中将 定位和隐私重置，然后进入APP，先保存图片（授权选择YES），然后调用图片选择（授权选择全部图片），

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
试一下Demo是否正常：
1、我最新的Demo是否有这个bug？【如果Demo没问题，请升级新版】
2、升级到最新版后是否正常？
