### ISSUE TITLE
相册点击左上角返回崩溃的问题

### ISSUE THREAD

**Issue by YourReference** [banchichen/TZImagePickerController#1446]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：否

2、你用的是什么版本？升级到最新版后是否正常？
答：3.5.2，这应该就是最新的了吧，不正常

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
我是iPhonexr，版本13.7，在项目中pods后，进入相册，有返回按钮，点击返回到相簿，直接崩溃，奇怪之处在于代码运行时，不会崩溃，一切正常，手动启动APP，操作返回相簿，就会崩溃；在另一个手机iPhone se 手机上没有这个问题，下载下来的demo运行也没问题；

**我如何复现这个bug？**
未解决，很着急，不知道什么问题

**截图**

https://user-images.githubusercontent.com/28887127/102684560-931f1900-4214-11eb-9547-aa4110763a36.mp4

进入相册后，点击左上角的返回，直接崩溃

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by YourReference** [comment]
如果知道问题所在，请发送邮件给我，谢谢 27267112@qq.com

**Comment by YourReference** [comment]
刚更新到3.5.7的版本，仍然有这个bug

**Comment by banchichen** [comment]
Demo没问题时，需要考虑下你项目的三方库的影响，可以参考：https://github.com/banchichen/TZImagePickerController/issues/1197

**Comment by tanpengsccd** [comment]
遇到同样问题。Debug 时 不会崩溃。

**Comment by banchichen** [comment]
@tanpengsccd 你是不是使用了WRNavigationBar：wangrui460/WRNavigationBar#182

**Comment by tanpengsccd** [comment]
> @tanpengsccd 你是不是使用了WRNavigationBar：[wangrui460/WRNavigationBar#182](https://github.com/wangrui460/WRNavigationBar/issues/182)

是的，已经修正了。但是WRNavigationBar 没维护了很多bug ，我也是没办法啊，维护老代码 又不敢大改。。。
我在别人改过的代码的上上又改了一波。现在 似乎没大问题了。
https://github.com/tanpengsccd/WRNavigationBar

Podfile 文件
```
 pod 'WRNavigationBar', :git => 'https://github.com/tanpengsccd/WRNavigationBar'  #必须这样写
```
