### ISSUE TITLE
有个方法感觉不合适

### ISSUE THREAD

**Issue by macMaJi** [banchichen/TZImagePickerController#1448]
获取原图的两种方法
同一张照片第一种方法获取到的图片(data)(TZ框架中获取图片大小用的是此方法)
第二种方法获取的图片(image),第二种方法猜测内部会渲染、裁剪,且第二种占用更高的内存
//第一种方法 :内存没有泄漏
return [[PHImageManager defaultManager] requestImageDataForAsset:asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
        BOOL cancelled = [[info objectForKey:PHImageCancelledKey] boolValue];
        if (!cancelled && imageData) {
            UIImage *result = [self fixOrientation:[UIImage imageWithData:imageData]];
            BOOL isDegraded = [[info objectForKey:PHImageResultIsDegradedKey] boolValue];
            if (completion) completion(result,info,isDegraded);
        }
    }];

//第二种方法 :内存有泄漏  "TZImageManager.m"用到的
    return [[PHImageManager defaultManager] requestImageForAsset:asset targetSize:PHImageManagerMaximumSize contentMode:PHImageContentModeAspectFit options:option resultHandler:^(UIImage *result, NSDictionary *info) {
//        BOOL cancelled = [[info objectForKey:PHImageCancelledKey] boolValue];
//        if (!cancelled && result) {
//            result = [self fixOrientation:result];
//            BOOL isDegraded = [[info objectForKey:PHImageResultIsDegradedKey] boolValue];
//            if (completion) completion(result,info,isDegraded);
//        }
    }];

官方文档:
https://developer.apple.com/documentation/photokit/phimagemanager/1616964-requestimageforasset?language=objc
从官方文档上来看,此方法建议用于图像请求提供缩略图图像,提供裁剪方式和大小
TZImage作者用此方法通过传递targetSize为最大值(PHImageManagerMaximumSize),来获取图片原图,感觉这种方法不恰当啊
或者作者能给出这个地方用"requestImageForAsset:asset"的合理解释,谢谢!

**Comment by banchichen** [comment]
PR已merge https://github.com/banchichen/TZImagePickerController/pull/1449，新版3.5.8
