### ISSUE TITLE
图片尺寸问题！

### ISSUE THREAD

**Issue by 676787080** [banchichen/TZImagePickerController#145]
现在的图片每行都是4张图片，现在有没有便捷的方式能让我控制它每行显示三张图片呢，4张图片看起来比较小！

**Comment by banchichen** [comment]
下次吧......目前还没有计划......

**Comment by banchichen** [comment]
你好，目前已经支持这样设置了，详情最新Demo.
更新说明：新增可设置columnNumber的初始化方法，可自定义photoPicker页每行展示照片个数，默认为每行4个
