### ISSUE TITLE
刚更新到3.5.7的版本，仍然有这个bug

### ISSUE THREAD

**Issue by Liyongcong** [banchichen/TZImagePickerController#1451]
刚更新到3.5.7的版本，仍然有这个bug

_Originally posted by @YourReference in https://github.com/banchichen/TZImagePickerController/issues/1446#issuecomment-748442213_
我也遇到了这个问题，请问你怎么解决的

**Comment by banchichen** [comment]
你是不是使用了WRNavigationBar：https://github.com/wangrui460/WRNavigationBar/issues/182

**Comment by Liyongcong** [comment]
是的，已经处理了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "谭真"<notifications@github.com&gt;; 
发送时间: 2020年12月28日(星期一) 上午10:45
收件人: "banchichen/TZImagePickerController"<TZImagePickerController@noreply.github.com&gt;; 
抄送: "有bug的程序猿"<570703516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [banchichen/TZImagePickerController] 刚更新到3.5.7的版本，仍然有这个bug (#1451)





 
你是不是使用了WRNavigationBar：wangrui460/WRNavigationBar#182
