### ISSUE TITLE
注意到，选用纯图有2个方法，他们只相差一个NSArray<NSDictionary *> *infos，你回调不使用即可，是否这块比较冗余？

### ISSUE THREAD

**Issue by 295060456** [banchichen/TZImagePickerController#1453]
/**
 
 /// Video
         [self.imagePickerVC setDidFinishPickingVideoHandle:^(UIImage *coverImage,
                                                              PHAsset *asset) {
             @strongify(self)
             if (self.picBlock) {
                 self.picBlock(@2,
                               coverImage,
                               asset);
             }
         }];
 /// Pic
 //        [self.imagePickerVC setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos,
 //                                                              NSArray *assets,
 //                                                              BOOL isSelectOriginalPhoto) {
 //            @strongify(self)
 //            if (self.picBlock) {
 //                self.picBlock(@3,
 //                              photos,
 //                              assets,
 //                              @(isSelectOriginalPhoto));
 //            }
 //        }];
         // 仅仅多了一个infos回调
         [self.imagePickerVC setDidFinishPickingPhotosWithInfosHandle:^(NSArray<UIImage *> *photos,
                                                                        NSArray *assets,
                                                                        BOOL isSelectOriginalPhoto,
                                                                        NSArray<NSDictionary *> *infos) {
             @strongify(self)
             if (self.picBlock) {
                 self.picBlock(@4,
                               photos,
                               assets,
                               @(isSelectOriginalPhoto),
                               infos);
             }
         }];
 /// Gif_Pic
         [self.imagePickerVC setDidFinishPickingGifImageHandle:^(UIImage *animatedImage,
                                                                 id sourceAssets) {
             @strongify(self)
             if (self.picBlock) {
                 self.picBlock(@2,
                               animatedImage,
                               sourceAssets);
             }
         }];
 
 */

**Comment by banchichen** [comment]
历史原因，最开始没有带infos的回调，后面支持了

为了无缝升级，不带infos的旧回调没删除
