### ISSUE TITLE
在ipad air第四代，iOS14.3系统上，截图中间镂空没有居中

### ISSUE THREAD

**Issue by STShenZhaoliang** [banchichen/TZImagePickerController#1457]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有任何改动

**bug内容描述**

**我如何复现这个bug？**

选择图片，图片需要切图，然而中间的部分没有居中显示

**截图**

![Simulator Screen Shot - iPad Air (4th generation) - 2021-01-06 at 17 15 36](https://user-images.githubusercontent.com/13865738/103751363-2349c480-5043-11eb-82e7-cd390dbce941.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
参考Demo，设置下imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen

**Comment by STShenZhaoliang** [comment]
谢谢，已解决
