### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by liangdahong** [banchichen/TZImagePickerController#1458]
1. scaleAspectFillCrop 属性是乎对 gif 无效 ？
2. 【配置了不可以选择 gif 】同时设置了 hideWhenCanNotSelect 好像也无法控制 gif 的选择和隐藏 ？

**Comment by banchichen** [comment]
1. GIF不支持裁剪
2. hideWhenCanNotSelect这个只支持隐藏尺寸不满足要求的照片。你可以参考试试 isAssetCanBeDisplayed
