### ISSUE TITLE
建议iOS14系统下照片权限（选中的照片）提示说明可以参考微信

### ISSUE THREAD

**Issue by TML007** [banchichen/TZImagePickerController#1459]
**问：你希望加什么新功能？**
答：
权限拒绝时的说明
**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：
微信
**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：
是
**其它你希望补充的内容**
![WechatIMG18](https://user-images.githubusercontent.com/19261542/104141517-30273900-53f2-11eb-9821-53b5f6f7dc34.jpeg)
![WechatIMG19](https://user-images.githubusercontent.com/19261542/104141519-32899300-53f2-11eb-8e8b-b258730f97b7.jpeg)

**Comment by bigNiuSanMao** [comment]
遇到同样的问题，有个疑问如何确定 当前相册的选中状态 是选择了 （选中的照片）

**Comment by TML007** [comment]
> 遇到同样的问题，有个疑问如何确定 当前相册的选中状态 是选择了 （选中的照片）

if (@available(iOS 14, *)) {
        PHAccessLevel level2 = PHAccessLevelReadWrite;
        PHAuthorizationStatus status = [PHPhotoLibrary authorizationStatusForAccessLevel:level2];
        if (status == PHAuthorizationStatusLimited) {
              ///限制权限
        }
    }

**Comment by bigNiuSanMao** [comment]
> > 遇到同样的问题，有个疑问如何确定 当前相册的选中状态 是选择了 （选中的照片）
> 
> if (@available(iOS 14, *)) {
> PHAccessLevel level2 = PHAccessLevelReadWrite;
> PHAuthorizationStatus status = [PHPhotoLibrary authorizationStatusForAccessLevel:level2];
> if (status == PHAuthorizationStatusLimited) {
> ///限制权限
> }
> }

感谢 已经兼容了iOS14系统的这个问题

**Comment by banchichen** [comment]
3.8.0版本已增加「部分照片」权限状态下的提示，欢迎大家运行demo体验效果，验证效果OK的可进行升级
![image](https://user-images.githubusercontent.com/12755494/161687321-eba4af8c-fe76-41af-ab08-8fe7aa247852.png)


升级注意点：
1、为了降低多语言维护成本，移除了14个语言文件，目前剩余12个，这次的功能新增了2处文案，只更新了**简体中文、繁体中文、英语**，其余9个小众语言未更新，这2处文案会降级为显示英文文案，如有需要请大家再提PR，或通过languageBundle使用自定义的文案    
2、info.plist里要配置Prevent limited photos access alert，设置为true，可参考demo
