### ISSUE TITLE
图片浏览功能

### ISSUE THREAD

**Issue by leezhihua** [banchichen/TZImagePickerController#1460]
**问：你希望加什么新功能？**
答：图片浏览功能，（在TZPhotoPreviewController基础上）增加UIPageControl或者index/total
初始化增加url已适应远程图片浏览

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是（TZPhotoPreviewController外部单独使用几率很低，不如修改后增加TZPhotoBrowserController）

**其它你希望补充的内容**

**Comment by banchichen** [comment]
没有这个计划哈
