### ISSUE TITLE
适配多语言

### ISSUE THREAD

**Issue by lxy8383** [banchichen/TZImagePickerController#1462]
为了适配多语言 期望把这块修改一下 
- (void)setPreferredLanguage:(NSString *)preferredLanguage {
    _preferredLanguage = preferredLanguage;
    
    if (!preferredLanguage || !preferredLanguage.length) {
        preferredLanguage = [NSLocale preferredLanguages].firstObject;
    }
    if ([preferredLanguage rangeOfString:@"zh-Hans"].location != NSNotFound) {
        preferredLanguage = @"zh-Hans";
    } else if ([preferredLanguage rangeOfString:@"zh-Hant"].location != NSNotFound) {
        preferredLanguage = @"zh-Hant";
    } else if ([preferredLanguage rangeOfString:@"vi"].location != NSNotFound) {
        preferredLanguage = @"vi";
    } else {
        preferredLanguage = @"en";
    }
    _languageBundle = [NSBundle bundleWithPath:[[NSBundle tz_imagePickerBundle] pathForResource:preferredLanguage ofType:@"lproj"]];
}

**Comment by banchichen** [comment]
没明白你的问题是什么....

**Comment by banchichen** [comment]
3.6.6已修复...

**Comment by sauchye** [comment]
![IMG_0552](https://user-images.githubusercontent.com/4171847/135256858-29acea35-a41b-4744-9471-af2b5ac7bc09.jpg)
@banchichen 你好，弱弱的咨询一下下，我的设备系统是中文简体，App切换到阿拉伯语言，我怎么去更改这里列表的显示呢。
Controller的控制器TZAlbumModel模型获取name，我查到name的赋值代码
```
    TZAlbumModel *model = [[TZAlbumModel alloc] init];
    [model setResult:result needFetchAssets:needFetchAssets];
    model.name = collection.localizedTitle;
```
我分别在初始化前尝试，但是没有效果。另外我不是最新的类库=  =，不是pod，之前更改了一些些，非常感谢！
```
                NSString *languageKey = @"zh-Hant";
                if (isArabicLanuage) {
                    languageKey = @"ar";
                } 
                [TZImagePickerConfig sharedInstance].preferredLanguage = languageKey;
                self.tzimagePickerVC.preferredLanguage = languageKey;
```

**Comment by banchichen** [comment]
@sauchye 相册的名字，参考下这个哈：
Q：系统语言是中文/英文，界面上却有部分相册名字、返回按钮显示成了英文/中文？
A：请参考 https://github.com/banchichen/TZImagePickerController/issues/443 和 https://github.com/banchichen/TZImagePickerController/issues/929

**Comment by sauchye** [comment]
感谢感谢！相册的部分title是取的系统语言，我切换微信英文，相册依旧是系统中文。那RTL翻转只能自己去修改一些镜像的问题吗？如一些些icon，选中icon，预览视频都被翻转

**Comment by banchichen** [comment]
关于RTL，TZ做的事情很少，更多是系统做的，可以搜索下tz_isRightToLeftLayout，这是TZ关于RTL的判断和几处适配...

**Comment by sauchye** [comment]
感谢作者，我fork了一份，主要处理RTL视频翻转问题，以及back按钮需要翻转，https://github.com/sauchye/TZImagePickerController
这里集成了https://github.com/bytedance/AWERTL 类库，主要适配RTL
添加enableRTL全局设置RTL，如果有需要再pr给作者，感谢作者~
```
#pragma mark - RTL
- (void)settingEnableRTL:(BOOL)enableRTL {
    /// RTL
    [TZImagePickerConfig sharedInstance].enableRTL = enableRTL;
    [AWERTLManager sharedInstance].enableRTL       = enableRTL;
}

// image 翻转
+ (UIImage *)tz_flipImage:(UIImage *)image;///<  flip picture eg:RTL
```
