### ISSUE TITLE
iOS14.3 打开相机选择视频崩溃

### ISSUE THREAD

**Issue by nehzx** [banchichen/TZImagePickerController#1464]
**bug内容描述**
打开相机录制视频崩溃

**我如何复现这个bug？**
选择相机-> 选择视频，

**截图**

**其它说明**
let imagePrick = TZImagePickerController()
        imagePrick.maxImagesCount = 100
        self.present(imagePrick, animated: true)
        
        imagePrick.didFinishPickingPhotosWithInfosHandle = { photos, _, _, _ in
            print(photos)
        }

**Comment by banchichen** [comment]
最新的Demo是好的吗，崩溃时的控制台打印的错误内容贴一下...

录制视频是用的系统的UIImagePickerController，不是我这控制的...
