### ISSUE TITLE
iphone8 plus  系统14.2  导出视频经常失败

### ISSUE THREAD

**Issue by MiTuShuSheng2019** [banchichen/TZImagePickerController#1465]
![icon](https://user-images.githubusercontent.com/59526642/106105810-8c72b280-617f-11eb-89f5-e043325001fa.png)

 上面是截图，下面是代码

#pragma mark -- 开始转换视频
-(void)convertVideoWithAsset:(PHAsset *)asset{
    
    __block CGFloat duration = asset.duration;
    //根据PHAsset 获取视频相关信息
    PHVideoRequestOptions *options = [[PHVideoRequestOptions alloc] init];
    options.version = PHVideoRequestOptionsVersionCurrent;
    __weak typeof(self) weakSelf = self;
    [[PHImageManager defaultManager] requestAVAssetForVideo:asset options:options resultHandler:^(AVAsset *asset, AVAudioMix *audioMix, NSDictionary *info) {
        
       //  asset  这里有时候会返回空的
        if ([asset isKindOfClass:[AVURLAsset class]]) {

          
        }
    }];

}

**Comment by banchichen** [comment]
可参考最新版的requestVideoOutputPathWithAsset，这个方法支持iOS14

可参考：https://github.com/banchichen/TZImagePickerController/issues/1073
