### ISSUE TITLE
部分视频不能显示问题

### ISSUE THREAD

**Issue by jozdee** [banchichen/TZImagePickerController#1470]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：0204日期最新的版本

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
sortAscendingByModificationDate设置为NO会丢失最新隔空投送过来的视频
sortAscendingByModificationDate不设置就会显示最新的视频

**我如何复现这个bug？**
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:1 delegate:nil];
//    imagePickerVc.sortAscendingByModificationDate = NO;
    imagePickerVc.allowTakeVideo = NO;
    imagePickerVc.allowPickingImage = NO;
    imagePickerVc.allowPickingVideo = YES;
    imagePickerVc.isSelectOriginalPhoto = YES;
    imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen;
    [imagePickerVc setDidFinishPickingVideoHandle:^(UIImage *coverImage, PHAsset *asset) {

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
sortAscendingByModificationDate设置为NO会丢失最新隔空投送过来的视频

不是会丢失，而是设置为NO后，照片/视频会按creationDate排序。
你今天隔空投送的视频，creationDate可能是2018年，所以不是一打开就看到，需要翻一番

**Comment by jozdee** [comment]
> sortAscendingByModificationDate设置为NO会丢失最新隔空投送过来的视频
> 
> 不是会丢失，而是设置为NO后，照片/视频会按creationDate排序。
> 你今天隔空投送的视频，creationDate可能是2018年，所以不是一打开就看到，需要滑动下

嗯嗯，是这个问题
