### ISSUE TITLE
建议添加新的风格

### ISSUE THREAD

**Issue by jacky8293676** [banchichen/TZImagePickerController#1471]
**问：你希望加什么新功能？**
答：添加新的相册风格

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：微博

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合

**其它你希望补充的内容**

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1277
