### ISSUE TITLE
图片大小被修改

### ISSUE THREAD

**Issue by adolph-suntao** [banchichen/TZImagePickerController#1475]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.5.8

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
选择一张大小为277k的图片，点击原图，debug查看图片大小，变为了543k。 微信选择原图，查看是285k

**我如何复现这个bug？**

选择一张大小为277k的图片，点击原图，debug查看图片大小，变为了543k

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
543kb这个值是在哪看到的？或是用什么API算出来的？
