### ISSUE TITLE
ios8下拍照会存入“最近添加”

### ISSUE THREAD

**Issue by Chris958** [banchichen/TZImagePickerController#148]
所以
`if ([collection.localizedTitle isEqualToString:@"Camera Roll"] || [collection.localizedTitle isEqualToString:@"相机胶卷"] ||  [collection.localizedTitle isEqualToString:@"所有照片"] || [collection.localizedTitle isEqualToString:@"All Photos"] ) {
                PHFetchResult *fetchResult = [PHAsset fetchAssetsInAssetCollection:collection options:option];
                model = [self modelWithResult:fetchResult name:collection.localizedTitle];
                if (completion) completion(model);
                break;
            }
`
应该添加一个
`[collection.localizedTitle isEqualToString:@"最近添加"]`，否则获取不到asset

**Comment by AppleEIN** [comment]
我也是刚刚发现了这个bug，准备来提发现你解决了

**Comment by banchichen** [comment]
你好，请问你们具体是8.几的版本呢？ 我手上一台iOS8.3的设备，拍照后也是存在相机胶卷中，可能iOS8早期几个版本拍照照片是会存在"最近添加"中，麻烦提供一下你们具体的系统版本~ 我这里再判断一下~

**Comment by Chris958** [comment]
设备iPhone6 版本8.0.2

**Comment by banchichen** [comment]
@Chris958  好的，麻烦你再看一下相册，请问你那里iPhone6版本8.0.2设备中，没有相机胶卷和所有照片相册对吧，系统相册应用中最近添加是排在第一个吗？

**Comment by Chris958** [comment]
是的

**Comment by banchichen** [comment]
好的，谢谢~  @AppleEIN  请问你具体是8.几的版本呢？ 我手上一台iOS8.3的设备，拍照后也是存在相机胶卷中，可能iOS8早期几个版本拍照照片是会存在"最近添加"中，麻烦提供一下你们具体的系统版本~ 我这里再判断一下~

**Comment by banchichen** [comment]
目前我先这样处理了~  
优化拍照照片保存相册的判断，目前已知在8.0-8.0.2版本中，拍照照片会保存在最近添加
