### ISSUE TITLE
pod install 失败

### ISSUE THREAD

**Issue by zhoujintang** [banchichen/TZImagePickerController#1480]
Installing TZImagePickerController 3.5.8 (was 3.5.1)

[!] Error installing TZImagePickerController
[!] /usr/local/bin/git clone https://github.com/banchichen/TZImagePickerController.git /var/folders/qb/bsyz_1gn5gvbrc7qyp3zzrc00000gn/T/d20210325-41569-1e0ize6 --template= --single-branch --depth 1 --branch 3.5.8

Cloning into '/var/folders/qb/bsyz_1gn5gvbrc7qyp3zzrc00000gn/T/d20210325-41569-1e0ize6'...
fatal: unable to access 'https://github.com/banchichen/TZImagePickerController.git/': Error in the HTTP2 framing layer

**Comment by banchichen** [comment]
这是你本机网络问题哦

**Comment by zhoujintang** [comment]
能够正常访问网络的

**Comment by HuangFeiPeng** [comment]
[!] Error installing TZImagePickerController
[!] /usr/bin/git clone https://github.com/banchichen/TZImagePickerController.git /var/folders/m6/vg9__9cn31zf8svljr5b02xh0000gn/T/d20221009-75199-e1z25u --template= --single-branch --depth 1 --branch 3.8.3

Cloning into '/var/folders/m6/vg9__9cn31zf8svljr5b02xh0000gn/T/d20221009-75199-e1z25u'...
fatal: unable to access 'https://github.com/banchichen/TZImagePickerController.git/': Failed to connect to 127.0.0.1 port 1080 after 60 ms: Connection refused

开启了科学上网确实也遇到了类似问题，比较奇怪
