### ISSUE TITLE
无法获取图片，提示处理中

### ISSUE THREAD

**Issue by ywwgolife** [banchichen/TZImagePickerController#1481]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是的

2、你用的是什么版本？升级到最新版后是否正常？
答：pod 3.5.2

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
允许选择原图，选择后一直处理中，直到结束也选择不了图片

**我如何复现这个bug？**

**截图**
![image](https://user-images.githubusercontent.com/14039080/113162738-1ddecd80-9272-11eb-9133-dfba06dfe585.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
你这不是最新版：https://github.com/banchichen/TZImagePickerController/tags
最新的版本和demo没这个问题
