### ISSUE TITLE
照片在iOS14的时候，并且用户照片权限选择了限制的情况下，希望能在照片列表页面加个按钮用来修改限制照片的功能

### ISSUE THREAD

**Issue by panlinhai** [banchichen/TZImagePickerController#1484]
**问：你希望加什么新功能？**
答：照片在iOS14的时候，并且用户照片权限选择了限制的情况下，希望能在照片列表页面加个按钮用来修改限制照片的功能

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是

**其它你希望补充的内容**

**Comment by shywoody** [comment]
> **问：你希望加什么新功能？**
> 答：照片在iOS14的时候，并且用户照片权限选择了限制的情况下，希望能在照片列表页面加个按钮用来修改限制照片的功能
> 
> **问：微信、QQ等大APP的选择器，是否有这个功能？**
> 答：有
> 
> **问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
> 答：是
> 
> **其它你希望补充的内容**

问下，就是这个权限下在相册选择了图片后是相册有更新么？
是什么逻辑做到的额

**Comment by kwzcoder** [comment]
HXPhotoPicker   加了这个功能  要么就自己改源码
                         
1. viewController.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"添加" style:UIBarButtonItemStylePlain target:weakSelf action:@selector(photoListAddClick)];
2. 
- (void)photoListAddClick {
#ifdef __IPHONE_14_0
    if (@available(iOS 14, *)) {
        [[PHPhotoLibrary sharedPhotoLibrary] presentLimitedLibraryPickerFromViewController:[UIApplication sharedApplication].keyWindow.rootViewController.navigationController];
    }
#endif
}

比较坑的地方 : 
'-[PHPhotoLibrary presentLimitedLibraryPickerFromViewController:]: unrecognized selector sent to instance xxxxxx'
解决方法:
1.  #import <PhotosUI/PhotosUI.h>
2. link PhotosUI.framework
in
TARGETS > General > Frameworks and Libraries

**Comment by banchichen** [comment]
3.8.0版本已增加「部分照片」权限状态下的提示，欢迎大家运行demo体验效果，验证效果OK的可进行升级
<img width="300" src="https://user-images.githubusercontent.com/12755494/161687321-eba4af8c-fe76-41af-ab08-8fe7aa247852.png" />

升级注意点：
1、为了降低多语言维护成本，移除了14个语言文件，目前剩余12个，这次的功能新增了2处文案，只更新了**简体中文、繁体中文、英语**，其余9个小众语言未更新，这2处文案会降级为显示英文文案，如有需要请大家再提PR，或通过languageBundle使用自定义的文案    
2、info.plist里要配置Prevent limited photos access alert，设置为true，可参考demo
