### ISSUE TITLE
使用最新的3.5.8版本的时候,出现奔溃异常

### ISSUE THREAD

**Issue by DongfengWang123** [banchichen/TZImagePickerController#1485]
问题:之前使用的时候正常,更新到最新的3.5.8 SDK的时候就会出现奔溃异常?
奔溃地方:    PHFetchResult *smartAlbums = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeSmartAlbum subtype:PHAssetCollectionSubtypeAlbumRegular options:nil];
奔溃原因:Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)"
测试工具:Iphone X(真机)
备注:我已经在info文件里面设置了相应的权限

**Comment by banchichen** [comment]
看起来是Photos库的问题，可以试试升级下Xcode或者iPhone X的系统版本：https://forums.raywenderlich.com/t/chapter-4-error-returned-from-daemon-error-domain-com-apple-accounts-code-7-null-completed-photo-selection/118476

**Comment by DongfengWang123** [comment]
libc++abi.dylib: terminate_handler unexpectedly threw an exception
terminate_handler unexpectedly threw an exception

手机系统已经升级到最新系统,在调用相册的时候还会报以上错误.帮忙看看为何呗!

**Comment by banchichen** [comment]
还只有你一个人遇到，是普遍问题的几率微乎其微，感觉你提供的这些信息，我这也复现不了，你需要自己多搜搜看看...

还有试了Demo没...

可以参考：https://www.jianshu.com/p/69e6bc6ab018  尝试捕捉更多信息

**Comment by DongfengWang123** [comment]
你好:
   经过我多次的验证发现是因为防止线上数组越界造成闪退异常.我使用创建了数组的类别,使用runtime进行处理.发现TZImagePickerController选择照片的时候就出现以上错误.请问是否可有优化的空间呢

**Comment by banchichen** [comment]
hook一些基础方法是比较危险的，最好是加一个前缀的，比如xx_objectAtIndex这样

只根据你上面提供的信息，我也不知怎么解决

**Comment by omnizhang** [comment]
我试了几次，的确是系统相册的问题。由于访问相册苹果给的都是加号方法，应该是初始化CoreData时资源冲突引起的报错,不会影响正常使用，只在APP生命周期第一次访问相册时出现。可以在你的代码中加入任何一个fetchAsset方法（例如：[PHAsset fetchAssetsWithOptions:nil];）让这个报错提前，也可以完全不用处理……又不是不能用😬
