### ISSUE TITLE
底部栏点击穿透

### ISSUE THREAD

**Issue by jasonhe88** [banchichen/TZImagePickerController#1487]
如图所示的红色框部分点击空白处，或者没有选图片时点击灰色文字，会触发底部覆盖的页面组件，如果恰好有输入框，还会弹出键盘，，，，
版本 3.6.0

![photoPickerVc](https://user-images.githubusercontent.com/6936520/114325117-0a304280-9b61-11eb-88ba-773819776d0a.jpg)

**Comment by banchichen** [comment]
不能理解，在我的页面里，怎么会触发你的事件...

麻烦提供个复现demo，可以fork我的demo，复现这个问题后，把链接回复出来...

**Comment by jasonhe88** [comment]
因为是作为 flutter 的一个plugin, 等我单独写个demo, 在模拟器和真机上都发现了这个问题

flutter 页面上有个类似微信的输入界面，点击某个图标后弹出TZImagePicker

此时如果点击‘原图’和‘确定’之间的空白处，正好就会触发在覆盖在底部的文字输入框

键盘就弹出来了，，，

**Comment by banchichen** [comment]
感觉不是TZ的问题，和flutter的事件系统相关，可以看看怎么设置native界面的事件不透传到flutter侧（组件级别事件透传合理，ViewController级别的不合理）

**Comment by jasonhe88** [comment]
好的，我先自己查查
发现问题症结后再来商讨
多谢如此棒的项目！！
