### ISSUE TITLE
请问如何获取相册图片的本地地址？

### ISSUE THREAD

**Issue by wangtongvip** [banchichen/TZImagePickerController#149]
[imagePickerVc setDidFinishPickingPhotosWithInfosHandle:^(NSArray<UIImage *> *photos,NSArray *assets,BOOL isSelectOriginalPhoto,NSArray<NSDictionary *> *infos) {}];
通过这个方法的 infos，可以拿到某张图片的 PHImageFileURLKey = "file:///var/mobile/Media/DCIM/103APPLE/IMG_3216.JPG";

请问我访问这个地址 "file:///var/mobile/Media/DCIM/103APPLE/IMG_3216.JPG" ，为什么访问不到？
PHImageFileURLKey 对应的内容是图片的本地地址吗

**Comment by banchichen** [comment]
访问相册数据，必须通过这系统提供的API的，无法通过路径访问的，我们应用中可以访问的数据，都是在我们沙盒中的。你可以把照片数据在沙盒保存一份，就能访问了。。。

**Comment by simanlx** [comment]
可以自己拼接得到 Users/Mr-Han/Library/Developer/CoreSimulator/Devices/A5F0B71C-D3D7-42D3-9552-7DE1D19B1A48/data/Media/DCIM/100APPLE/IMG_0018.mp4 可以直接访问
沙盒转存需要时间 有的场景不实用
