### ISSUE TITLE
浏览Document 文件夹下的图片和视频

### ISSUE THREAD

**Issue by KevinXinSuiLu** [banchichen/TZImagePickerController#1491]
**问：你希望加什么新功能？**
答：  浏览App 沙盒 Document 文件夹下的图片和视频

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答: 有,聊天记录中查看视频和图片

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是

**其它你希望补充的内容**

**Comment by banchichen** [comment]
没有支持的计划哈...
