### ISSUE TITLE
.videoMaximumDuration = 600.0

### ISSUE THREAD

**Issue by leleyinhangjia** [banchichen/TZImagePickerController#1492]
iOS  14.5 系统,视频选择都是小于10s的视频,设置.videoMaximumDuration = 600.0或者不设置.不管怎么设置videoMaximumDuration,都是无效的

**Comment by banchichen** [comment]
看下头文件的说明，videoMaximumDuration是视频拍摄时长限制

可以先去玩玩demo，这个小于10秒，可能是你们项目里自定义的配置，可以搜下isAssetCanSelect、isAssetCanBeDisplayed

**Comment by leleyinhangjia** [comment]
OK,谢了,我这里看一下,估计是就是拍摄视频时长和选择视频时长不是一个概念,抱歉我这边没有特意留意
