### ISSUE TITLE
导航上按钮，及标题颜色失效

### ISSUE THREAD

**Issue by CherishSmile** [banchichen/TZImagePickerController#1494]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：没有问题

2、你用的是什么版本？升级到最新版后是否正常？
答：用的最新版本。升级的最新版本后，修改导航上按钮，及标题颜色失效

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**

导航上按钮，及标题颜色修改无效。未自定义导航。
之前版本的都好好的。最近升级的新版本，三个项目里的，颜色都失效了。我定义的白色的导航，灰色的字体。现在字体颜色全都失效，变成默认的白色，看不见了。

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
![Snip20210425_5](https://user-images.githubusercontent.com/17586122/115980102-a2481600-a5bc-11eb-8ec7-9a3f2bd45412.png)

**Comment by banchichen** [comment]
试下这个配置放在Demo工程里生效吗？

如果也有问题的话，尝试调整下设置顺序，比如iconThemeColor，这个要尽可能靠前

**Comment by CherishSmile** [comment]
找到原因了。所有颜色属性不支持UIDynamicProviderColor。凡是设置成UIDynamicProviderColor的，都无效，望修改

**Comment by iiHorizon** [comment]
@CherishSmile 
你直接设置imagePickerVc.navigationBar.barStyle = UIBarStyleDefault，试一下
```objectivec
imagePickerVc.navigationBar.barStyle = UIBarStyleDefault;
```

**Comment by iiHorizon** [comment]
@CherishSmile 如果还是不行的话，给我看一下ZTTextPaleGrayColor这个宏的具体代码

**Comment by CherishSmile** [comment]
ios13以后有了暗黑模式，所以UIColor中新增了UIDynamicProviderColor。具体初始化方法为：
![image](https://user-images.githubusercontent.com/17586122/116170660-d4cb4d80-a739-11eb-80c6-bdd172c8a9e3.png)
凡是以以上方式初始化的UIColor，设置后，均无效，应该是版本适配问题，望修改。
我的ZTTextPaleGrayColor代码如下：
![image](https://user-images.githubusercontent.com/17586122/116170817-19ef7f80-a73a-11eb-9685-2662eff1a1a4.png)
![image](https://user-images.githubusercontent.com/17586122/116170851-2ecc1300-a73a-11eb-9bef-8f04b137816e.png)

**Comment by CherishSmile** [comment]
你说的这个可以，把barStyle设置UIBarStyleDefault，可以解决UIDynamicProviderColor的问题。
如果不设置的话，仅仅用普通颜色正常显示，动态颜色无效。
