### ISSUE TITLE
无法选择iCloud图片

### ISSUE THREAD

**Issue by Jokemac** [banchichen/TZImagePickerController#1497]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：使用Demo没有问题, 只出现在个人项目中

2、你用的是什么版本？升级到最新版后是否正常？
答：使用最新版本 3.6.0

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有任何改动

**bug内容描述**
选择图片时挑选在iCloud的图片, 然后点击完成获取失败
在getOriginalPhotoWithAsset中断点返回
{
    PHImageErrorKey = "Error Domain=NSCocoaErrorDomain Code=-1 \"(null)\"";
    PHImageResultIsDegradedKey = 0;
    PHImageResultRequestIDKey = 1566;
}

**我如何复现这个bug？**
选择图片时挑选在iCloud的图片, 然后点击完成获取失败

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
TZImagePickerController *imagePicker = [[TZImagePickerController alloc] initWithMaxImagesCount:1 delegate:nil];
            [imagePicker setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
                [[TZImageManager manager] getOriginalPhotoWithAsset:assets.firstObject completion:^(UIImage *photo, NSDictionary *info) {
                    NSLog(@"%@", info);
                }];
            }];

**Comment by banchichen** [comment]
比较奇怪了，即使是同一张照片，也是Demo可以，你的项目中不行吗？
可以check下你的项目是否有打开网络授权...

确认已打开的话，可以加钉钉群，把项目发过来看下

**Comment by Jokemac** [comment]
同一张图片在项目中不可以 Demo中可以

**Comment by banchichen** [comment]
可以把demo改造下，逐步和你的项目环境对齐，特别是依赖的三方库，各种项目配置啥的，看到哪一步的时候能复现你项目中的问题...

也可以反过来，从你的项目里，拷贝一份，逐步删依赖....

**Comment by Jokemac** [comment]
好的 我先尝试下 感谢帮助

**Comment by davidear** [comment]
这个问题我有遇到过，但不确定是同一个原因。我这里的原因是网络问题，访问icloud服务器不成功，修改网络后可以了

**Comment by Jokemac** [comment]
> 这个问题我有遇到过，但不确定是同一个原因。我这里的原因是网络问题，访问icloud服务器不成功，修改网络后可以了

感谢帮助, 我尝试更换了网络但是没有成功获取图片.
现在还在逐步删除代码来排查

**Comment by hqx1992** [comment]
@Jokemac 你好，我想问一下，你的这个问题解决了吗，我遇到和你同样的问题了，demo可以，项目里不行，无法成功获取图片，多年的老项目了，感谢

**Comment by Jokemac** [comment]
> @Jokemac 你好，我想问一下，你的这个问题解决了吗，我遇到和你同样的问题了，demo可以，项目里不行，无法成功获取图片，多年的老项目了，感谢

已经解决了, 最终排查到我们项目里的扩展类重写了NSObject的identifier, 给这个改了个名字加了前缀就解决了.

**Comment by hqx1992** [comment]
> NSObject

大佬好，NSObject这个类没有identifier这个属性啊，我们代码里也有一个NSobject分类，有个identiifer方法，获取机型的，你们的是这样吗，感谢

**Comment by hqx1992** [comment]
> > @Jokemac 你好，我想问一下，你的这个问题解决了吗，我遇到和你同样的问题了，demo可以，项目里不行，无法成功获取图片，多年的老项目了，感谢
> 
> 已经解决了, 最终排查到我们项目里的扩展类重写了NSObject的identifier, 给这个改了个名字加了前缀就解决了.

大佬好，NSObject这个类没有identifier这个属性啊，我们代码里也有一个NSobject分类，有个identiifer方法，获取机型的，你们的是这样吗，感谢

**Comment by Jokemac** [comment]
> > > @Jokemac 你好，我想问一下，你的这个问题解决了吗，我遇到和你同样的问题了，demo可以，项目里不行，无法成功获取图片，多年的老项目了，感谢
> > 
> > 
> > 已经解决了, 最终排查到我们项目里的扩展类重写了NSObject的identifier, 给这个改了个名字加了前缀就解决了.
> 
> 大佬好，NSObject这个类没有identifier这个属性啊，我们代码里也有一个NSobject分类，有个identiifer方法，获取机型的，你们的是这样吗，感谢

我们项目里的identiifer方法是做其他用途的, 但是应该跟这个没有关系, identiifer可能是NSObject的私有属性.
你尝试把这个属性加个前缀或者后缀试试. 我们的项目里只修改了这一个地方就解决了.
