### ISSUE TITLE
iCloud图片显示问题

### ISSUE THREAD

**Issue by dota2AndTI** [banchichen/TZImagePickerController#1498]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
iCloud图片显示缩略图时未能正常显示，选择时也会出问题

**我如何复现这个bug？**
选择iCloud图时再将它划出屏幕然后再返回找到该张图缩略图显示不同
**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by dota2AndTI** [comment]
看不了了，iCloud图片现在已经在本地了

**Comment by banchichen** [comment]
可以过段时间再试试，系统会择机上传到iCloud然后本地只留缩略图

**Comment by dota2AndTI** [comment]
你的相册内图片展示时没有请求iCloud图片好像

**Comment by banchichen** [comment]
列表页应该是没有的，预览页会

**Comment by dota2AndTI** [comment]
那这样不就iCloud的图片没有展示图了吗？
