### ISSUE TITLE
UIView+Layout Category引起冲突

### ISSUE THREAD

**Issue by VIIIO** [banchichen/TZImagePickerController#15]
由于您在UIView+Layout这个Category中定义了UIView的left、top等属性，与Mansory（封装Autolayout的框架）中定义产生了冲突，导致我不得不重构您的代码来使用

建议不要采用这个Category，或者将里面的属性改为较复杂的名称。因为在多组件运用的工程中很容易出现类似的冲突，而兼容性是您的组件需要考虑的问题

最后多谢您的分享，期待您在下个版本中修复此问题

**Comment by veryip7** [comment]
我们也遇到这个问题了，我们在UIView+Layout文件中和属性和方法都加上了TZ

**Comment by veryip7** [comment]
还有在TZAssetCell.m文件中setModel函数里面，
    [[TZImageManager manager] getPhotoWithAsset:model.asset photoWidth:50 completion:^(UIImage *photo, NSDictionary *info, BOOL isDegraded) {
        self.imageView.image = photo;
    }];
如果photoWidth传值self.width，会导致在ipad中非常卡顿然后闪退，所以这里传值也应该考虑一下。

**Comment by VIIIO** [comment]
@veryip7 我和你采用同样的解决方法，直接属性和方法都加上TZ前缀

**Comment by banchichen** [comment]
大家好，抱歉哈，最近这段时间特别忙，所以没顾得上这里....今天有一个同志提了个Pull request，把UIView+Layout的所有属性和方法加了前缀tz....刚刚代码合并了~   辛苦这位同志了....我考虑不周~抱歉~

**Comment by banchichen** [comment]
@veryip7  谢谢指出ipad环境下的这个问题，下版会修复~
