### ISSUE TITLE
iCloud网络加载的图片在预览里尺寸不正确

### ISSUE THREAD

**Issue by ccx201013050225** [banchichen/TZImagePickerController#150]
<img width="939" alt="6a28ac65-845f-4470-94d7-2d5383c2d0ca" src="https://cloud.githubusercontent.com/assets/6970978/17170500/e7a80b1e-541e-11e6-9f34-7a9980fc16e7.png">
这句应该改成：
![a2846400-ae77-4565-a625-ba013b29ff3b](https://cloud.githubusercontent.com/assets/6970978/17170510/fd928a62-541e-11e6-8546-a6ec0ed94446.png)

**Comment by LnsooXD** [comment]
谢谢分享 @ccx201013050225

**Comment by banchichen** [comment]
你好，谢谢指出~
