### ISSUE TITLE
设置单选的情况下，预览裁剪页面，点击底部的完成按钮时，按钮左边会闪一下数字1

### ISSUE THREAD

**Issue by huangrun** [banchichen/TZImagePickerController#1500]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.6.0，已是最新版

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：否

**bug内容描述**
如题，感觉会对体验有一点影响，单选一般用于上传头像功能，看了下微信的上传头像，没有此问题。

**我如何复现这个bug？**
使用demo，设置照片最大可选张数为1

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
3.6.6已修复哈
