### ISSUE TITLE
[TZImageManager fetchAssetByIocalIdentifier:retryCount:completion:] 崩溃

### ISSUE THREAD

**Issue by Cordeiring** [banchichen/TZImagePickerController#1503]
![image](https://user-images.githubusercontent.com/16833864/119432259-96c84600-bd46-11eb-8633-5bb4aedf1d3f.png)
感觉像是这个localIdentifier没有做保护

**Comment by banchichen** [comment]
@Cordeiring 在demo里可以复现吗？

**Comment by Cordeiring** [comment]
> @Cordeiring 在demo里可以复现吗？

我在我们项目中都没有复现，我是在bugly上看到的崩溃信息

**Comment by banchichen** [comment]
好的，这里优化了下，下版本发掉：
https://github.com/banchichen/TZImagePickerController/commit/4c6020a7b52abf138a5d61d6b2141b0408f4fc7e

不过此时用户还是遇到问题了，拍照后会没反应...
最好能复现出这个场景

**Comment by Cordeiring** [comment]
> 好的，这里优化了下，下版本发掉：
> [4c6020a](https://github.com/banchichen/TZImagePickerController/commit/4c6020a7b52abf138a5d61d6b2141b0408f4fc7e)
> 
> 不过此时用户还是遇到问题了，拍照后会没反应...
> 最好能复现出这个场景

我注意一下。我昨天一下午都没有复现

**Comment by Cordeiring** [comment]
> 好的，这里优化了下，下版本发掉：
> [4c6020a](https://github.com/banchichen/TZImagePickerController/commit/4c6020a7b52abf138a5d61d6b2141b0408f4fc7e)
> 
> 不过此时用户还是遇到问题了，拍照后会没反应...
> 最好能复现出这个场景

可以看一下我这个崩溃日志

**Comment by Cordeiring** [comment]
> 好的，这里优化了下，下版本发掉：
> [4c6020a](https://github.com/banchichen/TZImagePickerController/commit/4c6020a7b52abf138a5d61d6b2141b0408f4fc7e)
> 
> 不过此时用户还是遇到问题了，拍照后会没反应...
> 最好能复现出这个场景

![image](https://user-images.githubusercontent.com/16833864/119596867-909f9b80-be12-11eb-95fc-cb8c5335d494.png)
![image](https://user-images.githubusercontent.com/16833864/119596882-9b5a3080-be12-11eb-9b59-085aca1d9b87.png)

**Comment by banchichen** [comment]
嗯，看代码行数，应该是比较旧的版本，可以升级下

从最新代码看，出现这个问题，是performChanges成功了，但却没拿到localIdentifier，是里面的系统方法出异常了

**Comment by Cordeiring** [comment]
> 嗯，看代码行数，应该是比较旧的版本，可以升级下
> 
> 从最新代码看，出现这个问题，是performChanges成功了，但却没拿到localIdentifier，是里面的系统方法出异常了

今天我复现这个问题了。原因不在那里。在这个地方
![image](https://user-images.githubusercontent.com/16833864/120297586-d02b2380-c2fb-11eb-964f-c45cff47395e.png)

是在没有保存到相册权限的时候拍照保存到相册的时候asset为nil 前边的或判断直接进去了

**Comment by banchichen** [comment]
@Cordeiring 你用demo能复现这个问题吗？
进入tz选择器前会判断相册授权，没权限应该进不去的
