### ISSUE TITLE
跑demo，点击iCloud图片，进入预览，progressView不显示

### ISSUE THREAD

**Issue by davidear** [banchichen/TZImagePickerController#1505]
大佬，请教一下，发现一个问题
ios14.4.2
iphone12
跑demo，未改动代码，进入demo后未改动设置，点击+号，进入云相册，点击iCloud图片，进入预览模式，TZPhotoPreviewView中的progressView未被正常显示，然后过一段时间等图片加载完毕后直接显示图片了
这里我排查了一下，发现
- (PHImageRequestID)getPhotoWithAsset:(PHAsset *)asset completion:(void (^)(UIImage *photo,NSDictionary *info,BOOL isDegraded))completion progressHandler:(void (^)(double progress, NSError *error, BOOL *stop, NSDictionary *info))progressHandler networkAccessAllowed:(BOOL)networkAccessAllowed
的progressHandler回调只触发了一次，该次返回progress为1，一直跟到系统方法，也是只触发一次。
这里等待时间较长，我通过network conditioner 改动了网络速率。
感觉有点奇怪，请大佬与大家一起帮忙看看，到底是啥原因。

**Comment by banchichen** [comment]
我这里Demo试了是可以的...
![IMG_6252](https://user-images.githubusercontent.com/12755494/120416254-7116ee80-c38f-11eb-8c5e-e9861c880ca9.PNG)

**Comment by davidear** [comment]
嗯好，感谢，我再排查一下，
