### ISSUE TITLE
选择iCloud视频的【完成】按钮是否可用，应该由获取视频来决定，而不是预览图决定

### ISSUE THREAD

**Issue by hzz2020** [banchichen/TZImagePickerController#1506]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版3.6.0

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：我在我的本地环境改了调试；红色框内是我添加的代码。
![1621936561741](https://user-images.githubusercontent.com/14156004/119478958-c7c66c00-bd82-11eb-8ac1-3138422d1387.jpg)

**bug内容描述**
iCloud视频
【TZVideoPlayerController】configMoviePlayer方法中执行了两个方法：
①[[TZImageManager manager] getPhotoWithAsset（获取预览图）
②[[TZImageManager manager] getVideoWithAsset（获取视频）
底部【完成】按钮的是否可用 应该由②方法来决定，毕竟我要拿到的是视频，而不是一张预览图。

**我如何复现这个bug？**
1、iCloud视频 本地相册 下载失败
2、Demo直接去选择此视频

**截图**
我是这么改的
![1621936561741](https://user-images.githubusercontent.com/14156004/119478958-c7c66c00-bd82-11eb-8ac1-3138422d1387.jpg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
使用的是本Demo

**Comment by banchichen** [comment]
是这样的，getVideoWithAsset只是用来播放的，即使这个方法还没完成，用户也是可以选择
选择完后在外面会拿PHAsset去导出视频，可以参考demo此处的逻辑
