### ISSUE TITLE
allowEditVideo 这个属性在Pod install  3.6.0 版本后找不到

### ISSUE THREAD

**Issue by frankkly** [banchichen/TZImagePickerController#1509]
allowEditVideo 这个属性在Pod install  3.6.0 版本后找不到，但是demo里面能到找，并且demo里面也是3.6.0版本

**Comment by banchichen** [comment]
allowEditVideo还没发版哈，还没测试好
老哥可以用最新的demo测试下，看是否满足需求，满足的话我就发一版出来

**Comment by YWDrenched** [comment]
发一版本吧老哥

**Comment by banchichen** [comment]
不好意思久等了...
已发版，3.6.1
