### ISSUE TITLE
ios15 beta版 导航变成白色 

### ISSUE THREAD

**Issue by hujindong007** [banchichen/TZImagePickerController#1510]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.6.0

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
向上滑动就显示  向下滑动头导航又变成白色

**我如何复现这个bug？**

**截图**
![Simulator Screen Shot - iPhone 8 - 2021-06-09 at 15 49 57](https://user-images.githubusercontent.com/16041886/121316503-fe33e780-c93b-11eb-8703-27bd93e0bc56.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
我暂时修改  TZImagePickerController 和 TZPhotoPickerController 这两个页面背景色 大佬你看看修复一下
 if (@available(iOS 13.0, *)) {
        self.view.backgroundColor = [UIColor colorWithRed:66.0/255.0 green:66.0/255.0 blue:66.0/255.0 alpha:1.0];
    }

**Comment by banchichen** [comment]
3.6.3已修复哈：https://github.com/banchichen/TZImagePickerController/commit/e33ca82a602093894ce2cc5422cc09067d1d91a6
