### ISSUE TITLE
视频临时路径问题

### ISSUE THREAD

**Issue by stulip** [banchichen/TZImagePickerController#1516]
路径采用日期格式化不应该出现 `：`， 导致React Native无法读取此路径并上传到服务器

![image](https://user-images.githubusercontent.com/5770971/124256468-ed068100-db5d-11eb-8e47-ecd0d15d609a.png)

修改后
![image](https://user-images.githubusercontent.com/5770971/124256407-d5c79380-db5d-11eb-845d-d1bf70131005.png)

**Comment by banchichen** [comment]
已修改，3.6.1

**Comment by stulip** [comment]
非常感谢，正好最近几天在弄这个。
