### ISSUE TITLE
3.6.1 Crash 

### ISSUE THREAD

**Issue by wongzigii** [banchichen/TZImagePickerController#1517]
TZImageManager.h 里有这个方法，但是 .m 文件里没有这个方法实现，是忘记实现了吗？这会导致使用这个方法的旧项目崩溃。

- requestVideoOutputPathWithAsset:(PHAsset *)asset presetName:(NSString *)presetName success:(void (^)(NSString *outputPath))success failure:(void (^)(NSString *errorMessage, NSError *error))failure

**Comment by banchichen** [comment]
已修复哈，3.6.2
