### ISSUE TITLE
能不能增加导航栏item的颜色属性设置

### ISSUE THREAD

**Issue by zhongdom** [banchichen/TZImagePickerController#152]
默认导航栏的右边的取消按钮是白色的，左边的返回箭头也是白色的，能不能暴露一个属性用来设置这两个颜色呢？，现在我是在源码中修改这个两个属性的，但是我希望用Cocoapod来管理这个库

**Comment by banchichen** [comment]
好的，谢谢建议，下次改进这里~

**Comment by banchichen** [comment]
已新增barItemTextFont和barItemTextColor两个属性~
