### ISSUE TITLE
怎么隐藏导航栏返回相册列表功能，包括侧滑手势进入该列表页

### ISSUE THREAD

**Issue by zeqinjie** [banchichen/TZImagePickerController#1522]
**问：你希望加什么新功能？**
答：
1. 隐藏导航栏返回相册列表功能，包括侧滑手势进入该列表页
2. 录制视频后，直接退出选中该录制是视频

**Comment by banchichen** [comment]
1、不支持哈
2、如果你设置了允许多选视频，录制视频后，点使用视频，是会自动选中的
设置只能选一张的话，拍完视频也会自动选中的
