### ISSUE TITLE
能把相册和相机的权限分开吗，现在关闭了相册权限也没办法进行相机拍摄。

### ISSUE THREAD

**Issue by hewentao1023** [banchichen/TZImagePickerController#1524]
**问：你希望加什么新功能？**
答：直接拍照不强行判断相册权限，没有相册权限可以不写入相册，直接返回图片

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：是

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合

**其它你希望补充的内容**

**Comment by banchichen** [comment]
可以参考demo，把相机放在外面

**Comment by hewentao1023** [comment]
但是demo把相机放在外面了也是要相册权限的

**Comment by banchichen** [comment]
放在外面了，代码就是demo页面里的那坨，你全部拷贝走，自己控制逻辑就行
