### ISSUE TITLE
上传视频 无论大小，都显示正在处理中

### ISSUE THREAD

**Issue by tanghk** [banchichen/TZImagePickerController#1525]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：
有
2、你用的是什么版本？升级到最新版后是否正常？
答：
最新版
3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：
没有改动
**bug内容描述**

上传视频 无论大小，都显示正在处理中
**我如何复现这个bug？**
相册选择视频

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by tanghk** [comment]
因为视频过大原因 ，一直在导出视频，怎么做处理，视频过大给提示

**Comment by banchichen** [comment]
可以参考下demo，isAssetCanBeDisplayed和isAssetCanBeSelected，过滤掉时长很长的视频
