### ISSUE TITLE
横竖屏下裁剪 图片位置不对

### ISSUE THREAD

**Issue by forkdog** [banchichen/TZImagePickerController#1528]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：不知道

2、你用的是什么版本？升级到最新版后是否正常？
答：3.6.4

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
裁剪图片，旋转屏幕横屏下，图片位置不对了

**我如何复现这个bug？**
裁剪图片，旋转屏幕横屏下，图片位置不对了

**截图**
![横屏](https://tva1.sinaimg.cn/large/008i3skNgy1gu2dwh7hr4j61ds0n0q3t02.jpg)
![竖屏](https://tva1.sinaimg.cn/large/008i3skNgy1gu2dwwkq58j60n01dsq4u02.jpg)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
let picker = TZImagePickerController(maxImagesCount: 1, delegate: self)
picker?.allowCrop = true
picker?.allowTakeVideo = false
picker?.allowTakePicture = true
picker?.allowPickingVideo = false
picker?.scaleAspectFillCrop = true
picker?.needCircleCrop = false
picker?.modalPresentationStyle = .fullScreen
var width = UIScreen.main.bounds.size.width
var height = UIScreen.main.bounds.size.height
if width > height {
    width = height
    height = UIScreen.main.bounds.size.width
}
picker?.cropRect = CGRect(x: 0, y: (height - width)/2, width: width, height: width)

**Comment by banchichen** [comment]
试下我的demo是否正常哈

**Comment by forkdog** [comment]
> 试下我的demo是否正常哈

使用demo横屏下图片也会偏移
![](https://tva1.sinaimg.cn/large/008i3skNgy1gu38pjnq4uj607g0cuzkk02.jpg)
![](https://tva1.sinaimg.cn/large/008i3skNgy1gu38plcszhj60g308w75102.jpg)

**Comment by banchichen** [comment]
老哥来个PR不

**Comment by banchichen** [comment]
已修复哈，3.6.5版本

**Comment by smallgirl** [comment]
最新版本的demo 也还有这个问题啊，并没有修复？

**Comment by smallgirl** [comment]
具体复现步骤，如果ViewController 是竖屏界面，然后跳转，后面不管怎么切换横竖屏都没问题， 如果如果ViewController 是横屏界面，然后跳转 裁剪界面切换横竖屏 就有问题了。

**Comment by banchichen** [comment]
@smallgirl 嗯，横屏状态下进去的会有问题，3.6.9修复了，demo正常了，demo里横屏下cropRect传参也有变化
