### ISSUE TITLE
横屏模式预览图片有偏移

### ISSUE THREAD

**Issue by 15757857346** [banchichen/TZImagePickerController#1530]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有
在appdelegate里面加入以下代码 默认进去横屏 
-(UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window{
    return UIInterfaceOrientationMaskLandscapeRight;
}

2、你用的是什么版本？升级到最新版后是否正常？
答： 3.6.4 最新版本 

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**

**我如何复现这个bug？**
选择图片  预览   iPhone11   14系统    图片没有居中 

![241631190639_ pic](https://user-images.githubusercontent.com/19381167/132688274-af277ee5-cfd1-431d-bc8f-e47e54938779.jpg)

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
已修复哈，3.6.5版本
