### ISSUE TITLE
能否添加一个图片选中可旋转功能(选中图片时的旋转以及裁剪框中的图片旋转)？

### ISSUE THREAD

**Issue by dearDragon** [banchichen/TZImagePickerController#1532]
**问：你希望加什么新功能？**
答：能否添加一个图片选中可旋转功能(选中图片时的选中以及裁剪框中的选择)？

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：是的，有的

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：个人感觉适合于部分人，对选择裁剪旋转有要求的人群。是需要加属性开关的。

**其它你希望补充的内容**
如果按照现在不能手动拖动设置裁剪框大小的情况下 ，有一个旋转感觉就挺好的，因为有横屏拍照的这种常见操作的，这时候固定大小就不太合适了。当然如果可以手动拖动设置裁剪框大小和旋转一起最好。哈哈哈哈，谢谢

**Comment by banchichen** [comment]
应该没精力搞哈，欢迎PR，看怎么和现有的图片编辑库结合起来使用...
