### ISSUE TITLE
iOS 14 在非全屏模式下present的，手动向上滑动时会多次触发TZPhotoPickerController的viewDidLayoutSubviews方法，导致图片不停的在刷新，出现闪烁问题。全屏模式就没有这个问题。 版本：3.6.4, ios14,ipone7

### ISSUE THREAD

**Issue by zkf63858** [banchichen/TZImagePickerController#1535]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
复现了，图片不足一屏时上滑才会出现（不常遇到，且用户一般不会做上滑操作）
或者在底部或顶部上滑（几乎没用户会这样操作）

因此这个细节不会优化哈，免得改动引起其他问题
