### ISSUE TITLE
对这个导出视频的逻辑有点疑问？

### ISSUE THREAD

**Issue by Will-ZJ** [banchichen/TZImagePickerController#1536]
```objectivec
- (void)getVideoOutputPathWithAsset:(PHAsset *)asset presetName:(NSString *)presetName timeRange:(CMTimeRange)timeRange success:(void (^)(NSString *outputPath))success failure:(void (^)(NSString *errorMessage, NSError *error))failure {
    if (@available(iOS 14.0, *)) {
        [self requestVideoOutputPathWithAsset:asset presetName:presetName timeRange:timeRange success:success failure:failure];
        return;
    }
    [[PHImageManager defaultManager] requestAVAssetForVideo:asset options:[self getVideoRequestOptions] resultHandler:^(AVAsset* avasset, AVAudioMix* audioMix, NSDictionary* info){
        // NSLog(@"Info:\n%@",info);
        AVURLAsset *videoAsset = (AVURLAsset*)avasset;
        // NSLog(@"AVAsset URL: %@",myAsset.URL);
        [self startExportVideoWithVideoAsset:videoAsset timeRange:timeRange presetName:presetName success:success failure:failure];
    }];
}
```
请问这个源码中iOS14.0的处理方式的依据是什么？我看这两个逻辑调用的系统api的有效版本是一致的

**Comment by banchichen** [comment]
不是一样的呀...
iOS以上的requestVideoOutputPathWithAsset调了requestExportSessionForVideo
以下的是requestAVAssetForVideo

背景见：https://github.com/banchichen/TZImagePickerController/issues/1397

**Comment by Will-ZJ** [comment]
> 不是一样的呀...
> iOS以上的requestVideoOutputPathWithAsset调了requestExportSessionForVideo
> 以下的是requestAVAssetForVideo
> 
> 背景见：#1397

我的意思就是requestExportSessionForVideo和requestAVAssetForVideo这两个api在系统里面并没有iOS14.0的有效版本之分，不太理解为啥iOS14用requestExportSessionForVideo的依据，虽然事实上requestExportSessionForVideo能结局导出失败的问题

**Comment by banchichen** [comment]
纯粹是因为iOS14以下一直用的requestAVAssetForVideo，只在iOS14下iCloud视频有问题

而requestExportSessionForVideo没被大量验证过

**Comment by banchichen** [comment]
不太理解为啥iOS14用requestExportSessionForVideo的依据，虽然事实上requestExportSessionForVideo能结局导出失败的问题

**Comment by banchichen** [comment]
如果你等得起，你可以给Apple提issue，让他们解决requestAVAssetForVideo的iOS14 iCloud视频导出问题

**Comment by Will-ZJ** [comment]
> 如果你等得起，你可以给Apple提issue，让他们解决requestAVAssetForVideo的iOS14 iCloud视频导出问题

多谢解惑
