### ISSUE TITLE
iOS15下导航栏颜色异常问题

### ISSUE THREAD

**Issue by liangshuiluan** [banchichen/TZImagePickerController#1539]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：就是最新的3.6.6出现的

2、你用的是什么版本？升级到最新版后是否正常？
答：3.6.6

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：没有

**bug内容描述**
相册选择导航栏颜色没问题，但是相册授权是选中的照片时，打开相册选择跳转到这个选择照片的界面就会白底

**我如何复现这个bug？**
应用的相册授权为选中的照片，再进入应用进行相册的选中，选择跳转选择更多照片就会出问题

**截图**

![43EC1ED28324E84780D3740D04280B41](https://user-images.githubusercontent.com/82855110/135409834-5da4e0ba-61c7-4a8d-aacd-207142b07d48.png)
**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
这个是系统的页面，TZ没做过处理，应该是你们自己工程里自定义过导航栏样式，然后iOS15导航栏做了改造，你们自定义导航栏样式的代码要升级下，可以参考：https://github.com/banchichen/TZImagePickerController/commit/e33ca82a602093894ce2cc5422cc09067d1d91a6
