### ISSUE TITLE
当用户选择“允许访问选择的图片”权限时，每次选择图片时，能新增允许访问的图片数据么？如 微信在此权限下，是可以添加更多访问照片的！

### ISSUE THREAD

**Issue by zhangyunfeiFly** [banchichen/TZImagePickerController#1543]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答 没改动

**Comment by SuiTang** [comment]
复议

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1543
