### ISSUE TITLE
导航取消按钮靠屏幕边缘了，怎么调整？

### ISSUE THREAD

**Issue by dgynfi** [banchichen/TZImagePickerController#1548]
导航取消按钮靠屏幕边缘了，怎么调整？
![Simulator Screen Shot - iPhone 13 Pro Max - 2021-11-20 at 16 58 29](https://user-images.githubusercontent.com/15623781/142720665-d30c768e-e41b-4d72-bead-d79a3cc1fda4.png)

**Comment by banchichen** [comment]
demo是好的吗？

**Comment by dgynfi** [comment]
跑了Demo 是没问题的，不知道什么影响了它的frame

**Comment by banchichen** [comment]
可以梳理下对导航栏的全局设置，appearance设置，和导航栏相关的三方库，逐个注释掉试试...

**Comment by dgynfi** [comment]
UINavigation-SXFixSpace 是这个库影响TZImagePickerController导航取消按钮偏移

**Comment by Liyongcong** [comment]
> UINavigation-SXFixSpace 是这个库影响TZImagePickerController导航取消按钮偏移
这个怎么解决呢

**Comment by banchichen** [comment]
@Liyongcong 可以去 UINavigation-SXFixSpace 库的readme、issue里找找方案，没有就给UINavigation-SXFixSpace提个issue
