### ISSUE TITLE
PHAsset 视频，怎么样转NSData

### ISSUE THREAD

**Issue by YangKai123** [banchichen/TZImagePickerController#1549]
[imagePicker setDidFinishPickingVideoHandle:^(UIImage *coverImage, PHAsset *asset) {

    }];
PHAsset 视频，怎么样转NSData

**Comment by banchichen** [comment]
参考demo的用法，和TZImageManager里视频导出相关API

**Comment by YangKai123** [comment]
可以了 谢谢大佬



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 谭真 ***@***.***&gt;
发送时间: 2021年11月27日 12:08
收件人: banchichen/TZImagePickerController ***@***.***&gt;
抄送: YangKai123 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[banchichen/TZImagePickerController] PHAsset 视频，怎么样转NSData (Issue #1549)





 
Closed #1549.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
