### ISSUE TITLE
拍照出现问题

### ISSUE THREAD

**Issue by AFlamen** [banchichen/TZImagePickerController#1550]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：3.6.7

2、你用的是什么版本？升级到最新版后是否正常？
答：3.6.7

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**bug内容描述**
使用没有刘海屏的手机（6/6s/6puls/7/8）拍照图片会旋转180度，有刘海屏（xr）的手机不会出现图片旋转问题

**我如何复现这个bug？**
每次都出现

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
拍照是用的UIImagePickerController，直接保存的[info objectForKey:UIImagePickerControllerOriginalImage]内容本身，你这个问题用系统相机直接拍照也会遇到？

**Comment by AFlamen** [comment]
> 拍照是用的系统的UIImagePickerController，直接保存的[info objectForKey:UIImagePickerControllerOriginalImage]内容本身，你这个问题用系统相机直接拍照也会遇到？
我刚才试使用UIImagePickerController也会遇到，可能苹果的UIImagePickerController这个控件出现bug，原生控件出现问题估计很难改，算了我把拍照功能隐藏不给用户使用了
我上传我拍照时的截图
![003](https://user-images.githubusercontent.com/17897752/143551020-4d934ca1-62c5-4eec-869f-0f4d150e127b.jpeg)
![002](https://user-images.githubusercontent.com/17897752/143551029-323a96aa-1e26-4f80-8155-90c96a291347.jpeg)
![001](https://user-images.githubusercontent.com/17897752/143551034-3446011a-8c8a-4362-869f-d28bb325c738.jpeg)
问题

**Comment by AFlamen** [comment]
> 拍照是用的系统的UIImagePickerController，直接保存的[info objectForKey:UIImagePickerControllerOriginalImage]内容本身，你这个问题用系统相机直接拍照也会遇到？
