### ISSUE TITLE
希望getSelectedPhotoBytes支持外部实现

### ISSUE THREAD

**Issue by ipad4** [banchichen/TZImagePickerController#1552]
**问：你希望加什么新功能？**
答：计算原图大小支持外部实现

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：可能有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：作为block属性，外部不实现就按照默认逻辑处理

**其它你希望补充的内容**

**Comment by banchichen** [comment]
为什么要用外部的实现呢，你那的场景是？

**Comment by ipad4** [comment]
HEIC格式的图片大小显示为4M，修正方向后的JPG格式图片实际大小6M，所以在Picker中原图大小期望展示修正方向后实际使用的图片大小

**Comment by banchichen** [comment]
可以提个PR过来
