### ISSUE TITLE
当进入ImagePickerVC后，比如选择6张照片/视频（开启了允许多选视频），相应选中照片有对应的序号（1 2 3 4  5 6 ）此时退出后台，进入系统相册，删除选中的第三个照片后，再进入ImagePickerVC， 此时选中照片序号没有及时改变(1 2 4 5 6)，并且右下角的选择总数仍是 6

### ISSUE THREAD

**Issue by Cwolfberry** [banchichen/TZImagePickerController#1553]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.6.7

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答： 没有

**bug内容描述**
当进入ImagePickerVC后，比如选择6张照片/视频（开启了允许多选视频），相应选中照片有对应的序号（1 2 3 4  5 6 ）此时退出后台，进入系统相册，删除选中的第三个照片后，再进入ImagePickerVC， 此时选中照片序号没有及时改变(1 2 4 5 6)，并且右下角的选择总数仍是 6

**我如何复现这个bug？**
参考bug描述

**截图**
.

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
这种情况，微信、钉钉也没处理，感觉一点都没有必要
真有用户会这样操作？
