### ISSUE TITLE
未授权的情况下每隔0.2秒, 这个能优化下吗

### ISSUE THREAD

**Issue by A-Lost-Boy** [banchichen/TZImagePickerController#1555]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.6.7

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

你好，由于我们合规这边发现了每0.2秒一次检查权限这个问题，发现是没有用的，如果用户改变权限APP会重启的，不改变权限的话做这个定时器也没意义，这个定时器能去掉吗？

![调用](https://user-images.githubusercontent.com/31183385/144843184-7940213c-5307-4fe1-b293-ca01929c64be.jpg)
![实现](https://user-images.githubusercontent.com/31183385/144843191-73d708d9-52eb-4ee1-be18-0dc5dc65c79c.jpg)

**Comment by banchichen** [comment]
你可以验证下，去掉后
首次打开，询问用户权限时，用户点了同意
界面会空白

这种有询问弹窗的场景，用户的拒绝/同意，是不会触发APP重启的

**Comment by banchichen** [comment]
并且判断了PHAuthorizationStatusNotDetermined时才有定时器，已授权/拒绝的状态，是不会有的
