### ISSUE TITLE
iOS15版本下，选择图片，预览图片，退出预览图片，导航栏上移了20px

### ISSUE THREAD

**Issue by Sundyyer** [banchichen/TZImagePickerController#1556]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：xocde13 , iOS15

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

**bug内容描述**
iOS15版本下，选择图片，预览图片，退出预览图片，导航栏上移了20px

**我如何复现这个bug？**
iOS15版本下，选择图片，预览图片，退出预览图片，导航栏上移了20px

**截图**
![11638930199_ pic](https://user-images.githubusercontent.com/44721858/145137627-d1160ed1-ec39-4f9d-afc8-70bacbc993f9.jpg)
<img width="962" alt="image" src="https://user-images.githubusercontent.com/44721858/145137696-a7b6b026-dad8-4240-b56c-6e38e2beed7e.png">

**其它说明**
导致这个问题的出现，是因为在预览图片的时候，把状态栏隐藏了，直接先修改状态栏的状态再去修改导航栏的状态即可

**Comment by banchichen** [comment]
没能复现....

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1546

**Comment by baiyidjp** [comment]
@banchichen 这个我也必现了，在一个没有状态栏的页面打开后必现

https://user-images.githubusercontent.com/12672573/148322069-462242f2-f165-4c77-b028-825489ef5e78.mov

**Comment by banchichen** [comment]
@baiyidjp 你这个视频，和楼主反馈的不是一个问题，他是照片列表页导航栏上移，你是相册列表页相册列表上移
我在demo里，把demo页的状态栏隐藏了，进入TZ，没能复现你视频里的问题，你用demo能复现吗？

**Comment by Sundyyer** [comment]
自定义的控制器，如果导航栏隐藏掉，点击事件进入到图片的选择器，再进入到预览的控制器，返回的时候就会出现这个问题

**Comment by Sundyyer** [comment]
@banchichen 自定义的控制器，如果自定义控制器的导航栏隐藏掉，点击事件进入到图片的选择器，再进入到预览的控制器，返回的时候就会出现这个问题

**Comment by Sundyyer** [comment]
https://user-images.githubusercontent.com/44721858/148639028-10eca614-593c-4a5e-8144-4fa33cf72128.mp4

@banchichen

**Comment by banchichen** [comment]
@Sundyyer 请使用demo复现这个问题吧。。。
我刚刚提了点代码： https://github.com/banchichen/TZImagePickerController/commit/eaaf66030881295c7e93f6f19f00b3a25969d6c8
从 隐藏导航栏 的控制器里push TZ，未能复现你的问题...
