### ISSUE TITLE
导出视频的几个方法，请将 PHImageRequestID 返回

### ISSUE THREAD

**Issue by dagundejuzi** [banchichen/TZImagePickerController#1557]
导出视频的几个方法，麻烦把系统请求的 PHImageRequestID 返回出来下，导出时间太长的时候需要取消请求。
图片都返回出来了，为啥视频的没返回啊。
![image](https://user-images.githubusercontent.com/16382880/145184555-46f4e242-c57e-4c92-88a3-1cbced7f0c61.png)

**Comment by banchichen** [comment]
视频导出分两步，拿到PHImageRequestID取消只能取消第一步，到了第二步需要拿到AVAssetExportSession调用cancelExport，会比较麻烦，有这个需求的话，建议把相关方法复制到自己项目里维护下
