### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by bear15s** [banchichen/TZImagePickerController#1559]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：最新的demo也有这个问题

![image](https://user-images.githubusercontent.com/10527992/146527850-556e9ef7-cb7e-4489-baa2-5515973ce608.png)

2、你用的是什么版本？升级到最新版后是否正常？
答：3.6.7

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

**bug内容描述**
内存泄露

**我如何复现这个bug？**
选完图片之后就出现内存泄露了

**截图**
![image](https://user-images.githubusercontent.com/10527992/146526918-4b7e96c3-1a6f-4f36-a449-718afd4e341c.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
[TZImagePickerDemo.zip](https://github.com/banchichen/TZImagePickerController/files/7734239/TZImagePickerDemo.zip)

**Comment by zwx0322** [comment]
大哥，你解决内存泄漏问题了么？

**Comment by wqforever** [comment]
我也发现这个问题了，定位到是系统的方法，也不知道怎么修复
