### ISSUE TITLE
错误使用 PHAssetCollectionSubtype

### ISSUE THREAD

**Issue by tomrlq** [banchichen/TZImagePickerController#156]
PHAssetCollectionSubtype 不是 NS_OPTIONS，不可以用按位或运算，然而在 TZImageManager 里面发现了大量的对 PHAssetCollectionSubtype 使用按位或。

**Comment by iwpz** [comment]
TZImageManager是使用错误的方式取了PHAssetCollectionSubtype，导致最终结果是223，然后再通过字符串的方式跳过“最近删除”等。
应针对某个subtype单独取对应相册，再添加到array中。

**Comment by banchichen** [comment]
谢谢指正~ 当时从别处参考来的代码..   已修复~
