### ISSUE TITLE
预览照片时didFinishPickingPhotos 会在 controller dissmiss后才触发而不是点击“完成/done”时触发

### ISSUE THREAD

**Issue by KanathanZhou** [banchichen/TZImagePickerController#1560]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.6.7, 否

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：否

**bug内容描述**
let tzPicker = TZImagePickerController(selectedAssets: NSMutableArray(array: assets), selectedPhotos: NSMutableArray(array: photos), index: 0)
tzPicker.setDidFinishPickerPhotosHandle = { images, assets, isSelectingOriginalPhoto in 
  ...
  // 点击完成时不触发，在dismiss后才触发
  ...
} 

**我如何复现这个bug？**
只有init为预览照片时能复现，let tzPicker = TZImagePickerController() 是正常的

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

在点击“完成/done”后我需要做一些操作然后再dismiss tzimagepicker，所以我加了tzPicker.autoDismiss = false, 在点击"完成/done“时先执行我的逻辑，然后再手动tzPicker.dismiss(animated: true, completion: nil)，但是预览照片时点击“完成/done”后没有触发handler。

感谢谭真大大救命！！！！也有可能是我哪里写的有问题，但是奇怪的是非预览照片时是正常的，所以疑似是一个defect

**Comment by banchichen** [comment]
我这里用demo试了是可以的：

https://user-images.githubusercontent.com/12755494/147311098-1376bfe2-62bd-4729-a270-0ad091b113d1.mov

**Comment by KanathanZhou** [comment]
稍等容我到家后上传一个clip

**Comment by KanathanZhou** [comment]
https://user-images.githubusercontent.com/20479084/147440240-c18b9e52-7579-4a52-a412-063f8195ee24.MP4

**Comment by banchichen** [comment]
哥，你前后说的都不是一个问题。。。
刚开始你说【但是预览照片时点击“完成/done”后没有触发handler】
上面说的先后顺序问题...

3.7.0版已优化，autoDismiss为false时，预览态不自动dismiss，会直接调用handle：https://github.com/banchichen/TZImagePickerController/commit/4f682ae666849b7b84e9e94ffc0f26f863f857d6

**Comment by KanathanZhou** [comment]
太酷了，多谢谭大
