### ISSUE TITLE
IOS 15之后系统进相册，没滑动到底部。

### ISSUE THREAD

**Issue by ChangChangXin** [banchichen/TZImagePickerController#1562]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：2.3.7.0

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**bug内容描述**
IOS 15系统进相册，没滑动到底部。 TZPhotoPickerController 这个控制器，这个_collectionView.contentOffset有问题。

**我如何复现这个bug？**
运行demo，点击加号进入相册，（15.0之后系统）没出现就杀进程，再进，首次出现几率很大。几乎100%

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
我这复现不了，用demo录个视频看下

**Comment by ChangChangXin** [comment]
视频中，第一次进入照片滑动到底部了，杀进程再进，停留在顶部，没滑动到底部。大部分15系统之后会有这个问题，demo版本是最新的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "banchichen/TZImagePickerController"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 晚上9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [banchichen/TZImagePickerController] IOS 15之后系统进相册，没滑动到底部。 (Issue #1562)





 
我这复现不了，用demo录个视频看下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

RPReplay_Final1640918340.mp4.zip (52.50M, 2022年01月30日 10:35 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=616531384868dd9eeaf8057c1264574d0507025e52525455195c575b0549515103541c005107034f0051555c5555505056010759344465306437544858051c3d720c5f5958555356045c00000750554c591505164e0d156209&t=exs_ftn_download&code=4e184deb

**Comment by baiyidjp** [comment]
我这边也有好多用户反馈这个了，但是我无法复现

**Comment by ChangChangXin** [comment]
应该不是所有ios 15手机都会发生该情况，至少我们大部分ios 15之后的iPhone或者ipad都会出现。
我把自己代码做了如下调整

//暂时做偏移处理。
 
&nbsp; &nbsp; if ***@***.***(iOS 15.0, *)) {
 
&nbsp; &nbsp; &nbsp; &nbsp; if (_collectionView.contentOffset.y &gt; _collectionView.adjustedContentInset.bottom) {
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return;
 
&nbsp; &nbsp; &nbsp; &nbsp; }
 
&nbsp; &nbsp; &nbsp; &nbsp; _collectionView.contentOffset = CGPointMake(- _collectionView.adjustedContentInset.left , _collectionView.contentSize.height - _collectionView.frame.size.height + _collectionView.adjustedContentInset.bottom);
 
&nbsp; &nbsp; }





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "banchichen/TZImagePickerController"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月31日(星期五) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [banchichen/TZImagePickerController] IOS 15之后系统进相册，没滑动到底部。 (Issue #1562)





 
我这边也有好多用户反馈这个了，但是我无法复现
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

TZPhotoPickerController.m (56.6K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2a373230f12ccc9bbaaa06741e31014b525550525b065554495351520d1c075357071f525c545749000f57525e08055456070506382833303e675a5f4c5e630d075c57427b5e5d1016585e5c5d431d09640a&t=exs_ftn_download&code=d720813d

**Comment by cabbageTingZhang** [comment]
也遇到了同样的问题， 手机iPhone 12 pro ， 系统iOS 15.2

**Comment by baiyidjp** [comment]
> 也遇到了同样的问题， 手机iPhone 12 pro ， 系统iOS 15.2

我按照楼上的操作加上代码后可以了

**Comment by cabbageTingZhang** [comment]
> > 也遇到了同样的问题， 手机iPhone 12 pro ， 系统iOS 15.2
> 
> 我按照楼上的操作加上代码后可以了

可以说说具体的需要修改的文件类名以及修改的地方吗

**Comment by baiyidjp** [comment]
> > > 也遇到了同样的问题， 手机iPhone 12 pro ， 系统iOS 15.2
> > 
> > 
> > 我按照楼上的操作加上代码后可以了
> 
> 可以说说具体的需要修改的文件类名以及修改的地方吗

TZPhotoPickerController.m  413 行

    
    //暂时做偏移处理。
    if (@available(iOS 15.0, *)) {
        if (_collectionView.contentOffset.y > _collectionView.adjustedContentInset.bottom) {
            return;
        }
        _collectionView.contentOffset = CGPointMake(- _collectionView.adjustedContentInset.left , _collectionView.contentSize.height - _collectionView.frame.size.height + _collectionView.adjustedContentInset.bottom);
    }

**Comment by cabbageTingZhang** [comment]
> > > > 也遇到了同样的问题， 手机iPhone 12 pro ， 系统iOS 15.2
> > > 
> > > 
> > > 我按照楼上的操作加上代码后可以了
> > 
> > 
> > 可以说说具体的需要修改的文件类名以及修改的地方吗
> 
> TZPhotoPickerController.m 413 行
> 
> ```
> //暂时做偏移处理。
> if (@available(iOS 15.0, *)) {
>     if (_collectionView.contentOffset.y > _collectionView.adjustedContentInset.bottom) {
>         return;
>     }
>     _collectionView.contentOffset = CGPointMake(- _collectionView.adjustedContentInset.left , _collectionView.contentSize.height - _collectionView.frame.size.height + _collectionView.adjustedContentInset.bottom);
> }
> ```

我的版本比较低， 413行应该是viewDidLayoutSubviews方法的最后， 多谢，我试试

**Comment by banchichen** [comment]
3.7.1尝试修复了这个问题，正在发版

可下载最新Demo验证是否还存在这个问题，改动的代码：https://github.com/banchichen/TZImagePickerController/commit/f6b7b54360f0782f438969c78df5cc7a6f564b60

**Comment by ChangChangXin** [comment]
我测试了一下，还是复现。版本 3.7.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "banchichen/TZImagePickerController"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月7日(星期五) 晚上7:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [banchichen/TZImagePickerController] IOS 15之后系统进相册，没滑动到底部。 (Issue #1562)





 
3.7.1尝试修复了这个问题，正在发版
 
可下载最新Demo验证是否还存在这个问题，改动的代码：f6b7b54
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by banchichen** [comment]
@ChangChangXin 有发现啥规律吗？我这的机器复现不出来
demo的prepareScrollCollectionViewToBottom方法，iOS15下也走dispatch_after，时间逐步调大，试下是否会解决哈

**Comment by cabbageTingZhang** [comment]
> @ChangChangXin 有发现啥规律吗？我这的机器复现不出来 demo的prepareScrollCollectionViewToBottom方法，iOS15下也走dispatch_after，时间逐步调大，试下是否会解决哈

可以用楼上我们讨论的方法先暂时修复， 反馈问题的用户现在反馈已经没问题了

**Comment by jumplee** [comment]
> > > > > 也遇到了同样的问题， 手机iPhone 12 pro ， 系统iOS 15.2
> > > > 
> > > > 
> > > > 我按照楼上的操作加上代码后可以了
> > > 
> > > 
> > > 可以说说具体的需要修改的文件类名以及修改的地方吗
> > 
> > 
> > TZPhotoPickerController.m 413 行
> > ```
> > //暂时做偏移处理。
> > if (@available(iOS 15.0, *)) {
> >     if (_collectionView.contentOffset.y > _collectionView.adjustedContentInset.bottom) {
> >         return;
> >     }
> >     _collectionView.contentOffset = CGPointMake(- _collectionView.adjustedContentInset.left , _collectionView.contentSize.height - _collectionView.frame.size.height + _collectionView.adjustedContentInset.bottom);
> > }
> > ```
> 
> 我的版本比较低， 413行应该是viewDidLayoutSubviews方法的最后， 多谢，我试试

经过测试sortAscendingByModificationDate参数也要配置成YES，再加上上面的代码可以解决问题

**Comment by jumplee** [comment]
> @ChangChangXin 有发现啥规律吗？我这的机器复现不出来 demo的prepareScrollCollectionViewToBottom方法，iOS15下也走dispatch_after，时间逐步调大，试下是否会解决哈

如果用户手机照片少，且性能很强（iphone13等），可能会闪一下滚动到底部。暂时解决这个问题
```objective-c
    // 暂时做偏移处理。
    if (@available(iOS 15.0, *)) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            if (_collectionView.contentOffset.y > _collectionView.adjustedContentInset.bottom) {
                return;
            }
            _collectionView.contentOffset = CGPointMake(- _collectionView.adjustedContentInset.left , _collectionView.contentSize.height - _collectionView.frame.size.height + _collectionView.adjustedContentInset.bottom);
         });

    }
```

**Comment by ruixingchen** [comment]
> 

我这边实测即使在viewDidLayoutSubviews里面加上这个也不行，还是会出现offset在初始位置的情况，在上面的`[self.collectionView reloadData];` 后面加一个`[self.collectionView layoutIfNeeded];` 实测可以解决

**Comment by ruixingchen** [comment]
> > @ChangChangXin 有发现啥规律吗？我这的机器复现不出来 demo的prepareScrollCollectionViewToBottom方法，iOS15下也走dispatch_after，时间逐步调大，试下是否会解决哈
> 
> 可以用楼上我们讨论的方法先暂时修复， 反馈问题的用户现在反馈已经没问题了

上面的代码在相册数量很少的情况下会强制让图片都显示在最底部，我稍微优化了一下
```
if (@available(iOS 15.0, *)) {
        if (!_touched && self.collectionView.bounds.size.height > 0 && self.collectionView.contentSize.height+self.additionalSafeAreaInsets.top+self.additionalSafeAreaInsets.bottom > self.collectionView.bounds.size.height) {
            CGFloat offsetY = self.collectionView.contentSize.height - self.collectionView.bounds.size.height + self.collectionView.adjustedContentInset.bottom;
            [self.collectionView setContentOffset:CGPointMake(-self.collectionView.adjustedContentInset.left, offsetY) animated:false];
        }
    }
```
这里_touched 用来标记用户是否滚动过内容

**Comment by OCer** [comment]
@ruixingchen 是在 `- (void)scrollViewDidScroll:(UIScrollView *)scrollView` 这个方法里给 `_touched ` 赋值吗

**Comment by OCer** [comment]
@banchichen 3.7.2还是有这个问题啊

**Comment by OCer** [comment]
把 `- (void)prepareScrollCollectionViewToBottom`关于iOS15的注释掉就OK了 - -

**Comment by myiosemail** [comment]
@banchichen 3.7.2版本  这个问题依然存在

**Comment by gorpeln** [comment]
第一次点击授权进入相册无法滑到最后，杀死再进入就好了

**Comment by gorpeln** [comment]
ios 15.3.1 添加上面的代码 也不行了

**Comment by myiosemail** [comment]
@banchichen 3.7.3版本 这个问题依然存在

**Comment by icesquall** [comment]
> 把 `- (void)prepareScrollCollectionViewToBottom`关于iOS15的注释掉就OK了 - -

@banchichen 我这边注释了可以解决
注释if (@available(iOS 15.0, *)) {
统一走dispatch_after

我多台机型
iOS15系统，有些正常，只有iPhone12，重现了

**Comment by banchichen** [comment]
3.7.5再优化了下，iOS15下多等待0.1秒，@icesquall 那里正常了，大家可以验证下，改动代码是：
![image](https://user-images.githubusercontent.com/12755494/156286052-c73ddc0d-5d23-458b-b727-d60af0bc715b.png)

**Comment by icesquall** [comment]
> @icesquall hi，感谢验证，3.7.4已移除iOS15的处理，统一走dispatch_after
> 
> 对于走dispatch_after后仍然出现未滑动到底部的问题，在复现的机器上，麻烦试试「dispatch_after的时间逐步调大」，试下是否会解决哈

已用有问题的机子试了一下，没有问题了，可以滚动到底部

**Comment by liuvbill** [comment]
Fatal Exception: NSInternalInconsistencyException
Attempted to scroll the collection view to an out-of-bounds item (5168) when there are only 5168 items in section 0. Collection view: <TZCollectionView: 0x106336c00; baseClass = UICollectionView; frame = (0 0; 375 640); clipsToBounds = YES; hidden = YES; gestureRecognizers = <NSArray: 0x2807cc2a0>; layer = <CALayer: 0x280f7b4e0>; contentOffset: {-5, 0}; contentSize: {365, 119505}; adjustedContentInset: {5, 5, 5, 5}; layout: <UICollectionViewFlowLayout: 0x10b88ffb0>; dataSource: <TZPhotoPickerController: 0x105203400>>.

还是有呀

**Comment by banchichen** [comment]
@liuvbill 在demo里可以复现吗？是设置了怎样的配置呢？
不是上面说的问题，你发的这个是index计算不对...

**Comment by liuvbill** [comment]
我这边复现不了，我手机也没几千张图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "banchichen/TZImagePickerController"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 下午3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [banchichen/TZImagePickerController] IOS 15之后系统进相册，没滑动到底部。 (Issue #1562)





 
@liuvbill 在demo里可以复现吗？是设置了怎样的配置呢？
 不是上面说的问题，你发的这个是index计算不对...

**Comment by liuvbill** [comment]
我这边复现不了，我手机也没几千张图片




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "banchichen/TZImagePickerController"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 下午3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [banchichen/TZImagePickerController] IOS 15之后系统进相册，没滑动到底部。 (Issue #1562)





 
@liuvbill 在demo里可以复现吗？是设置了怎样的配置呢？
 不是上面说的问题，你发的这个是index计算不对...

**Comment by liuvbill** [comment]
> @liuvbill在演示中可以复现吗？是设置了怎样的配置呢？ 不是上面说的问题，你发的这个是索引计算不正确...
![1651130413812](https://user-images.githubusercontent.com/22655068/165700047-ddfbcf13-a659-48df-b273-bf0540e7bb27.jpg)
![1651130466398](https://user-images.githubusercontent.com/22655068/165700059-14fe566b-4a83-4c77-a0f6-8c24c97c7f04.jpg)
![1651130494436](https://user-images.githubusercontent.com/22655068/165700073-a0ba824a-2d74-4136-b29a-0468e801b33d.jpg)
`//
//  CusImagePickerController.swift
//  Ubit
//
//  Created by XL on 2021/11/29.
//

import UIKit
import TZImagePickerController

extension CusImagePickerController {
    
    static func getPickController(maxImagesCount: Int, columnNumber: Int, delegate: TZImagePickerControllerDelegate!, pushPhotoPickerVc: Bool) -> CusImagePickerController {
        let vc = CusImagePickerController.init(maxImagesCount: maxImagesCount, columnNumber: columnNumber, delegate: delegate, pushPhotoPickerVc: pushPhotoPickerVc)!
        vc.modalPresentationCapturesStatusBarAppearance = true
        vc.preferredLanguage = LanguageTool.shared().currentLanguage
        vc.languageBundle = Bundle.init(path: Bundle.main.path(forResource: LanguageTool.shared().currentLanguage, ofType: "lproj")!)
        vc.iconThemeColor = ColorDefine.BrandColor.color
        vc.navigationBar.setBackgroundImage(UIImage(), for: .default)
        vc.navigationBar.shadowImage = UIImage()
        vc.navigationBar.barTintColor = .white
        vc.navigationBar.isTranslucent = false
        vc.navigationBar.titleTextAttributes = [NSAttributedString.Key.foregroundColor : ColorDefine.FirstTextColor.color]
        if #available(iOS 13.0, *) {
            let appearance = UINavigationBarAppearance()
            appearance.backgroundColor = .white
            appearance.titleTextAttributes = [NSAttributedString.Key.foregroundColor : ColorDefine.FirstTextColor.color]
            vc.navigationBar.standardAppearance = appearance
            vc.navigationBar.scrollEdgeAppearance = appearance
        }
        vc.navLeftBarButtonSettingBlock = { btn in
            btn?.setImage(UIImage.init(named: "nav_icon_return_black"), for: .normal)
            btn?.setTitle(nil, for: .normal)
        }
        vc.barItemTextColor = ColorDefine.FirstTextColor.color
        vc.photoPickerPageUIConfigBlock = { collectionView , bottomToolBar , previewBtn , _,_,doneBtn,_,_,line in
            collectionView?.backgroundColor = .white
            bottomToolBar?.backgroundColor = .white
            line?.backgroundColor = ColorDefine.LineColor.color
            previewBtn?.setTitleColor(ColorDefine.FirstTextColor.color, for: .normal)
            previewBtn?.setTitleColor(UIColor.colorWithHexString("#999999"), for: .disabled)
            doneBtn?.setTitleColor(ColorDefine.BrandColor.color, for: .normal)
            doneBtn?.setTitleColor(UIColor.colorWithHexString("#999999"), for: .disabled)
        }
        vc.photoPreviewPageUIConfigBlock = { collectionView,naviBar,backButton,selectButton,_ ,toolBar,_,_,doneBtn,_,_ in
            backButton?.setImage(UIImage.init(named: "nav_icon_return_black"), for: .normal)
            doneBtn?.setTitleColor(ColorDefine.BrandColor.color, for: .normal)
            doneBtn?.setTitleColor(UIColor.colorWithHexString("#999999"), for: .disabled)
            naviBar?.backgroundColor = .white
            toolBar?.backgroundColor = .white
            
        }
        vc.albumPickerPageUIConfigBlock = { tableView in
            tableView?.backgroundColor = .white
        }
        //        self.albumCellDidSetModelBlock = { cell , _ ,lb in
        //            cell?.backgroundColor = .white
        //            cell?.contentView.backgroundColor = .white
        //            lb?.textColor = ColorDefine.FirstTextColor.color
        //        }
        vc.photoPickerPageDidLayoutSubviewsBlock = { collectionView , bottomToolBar , previewBtn , _,_,doneBtn,_,_,line in
            previewBtn?.frame = CGRect.init(x: previewBtn!.frame.origin.x, y: previewBtn!.frame.origin.y, width: previewBtn!.currentTitle!.sizeWithText(font: previewBtn!.titleLabel!.font, size: CGSize.init(width: 0, height: 30)).width + 1, height: previewBtn!.frame.size.height)
            doneBtn?.frame = CGRect.init(x: doneBtn!.frame.origin.x, y: doneBtn!.frame.origin.y, width: doneBtn!.currentTitle!.sizeWithText(font: doneBtn!.titleLabel!.font, size: CGSize.init(width: 0, height: 30)).width + 1, height: doneBtn!.frame.size.height)
        }
        
        vc.allowPickingImage = true
        vc.allowPickingOriginalPhoto = false
        vc.allowCrop = false;
        vc.allowPickingVideo = false
        vc.modalPresentationStyle = .fullScreen
        return vc
    }
    
}

class CusImagePickerController: TZImagePickerController {
    
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .default
    }
}
`

**Comment by banchichen** [comment]
和照片个数应该没关系的，我是1W+，没遇到这个问题

**Comment by sugite** [comment]
> > @liuvbill在演示中可以复现吗？是设置了怎样的配置呢？ 不是上面说的问题，你发的这个是索引计算不正确...
> > ![1651130413812](https://user-images.githubusercontent.com/22655068/165700047-ddfbcf13-a659-48df-b273-bf0540e7bb27.jpg)
> > ![1651130466398](https://user-images.githubusercontent.com/22655068/165700059-14fe566b-4a83-4c77-a0f6-8c24c97c7f04.jpg)
> > ![1651130494436](https://user-images.githubusercontent.com/22655068/165700073-a0ba824a-2d74-4136-b29a-0468e801b33d.jpg)
> > `//
> > //  CusImagePickerController.swift
> > //  Ubit
> > //
> > //  Created by XL on 2021/11/29.
> > //
> 
> import UIKit import TZImagePickerController
> 
> extension CusImagePickerController {
> 
> ```
> static func getPickController(maxImagesCount: Int, columnNumber: Int, delegate: TZImagePickerControllerDelegate!, pushPhotoPickerVc: Bool) -> CusImagePickerController {
>     let vc = CusImagePickerController.init(maxImagesCount: maxImagesCount, columnNumber: columnNumber, delegate: delegate, pushPhotoPickerVc: pushPhotoPickerVc)!
>     vc.modalPresentationCapturesStatusBarAppearance = true
>     vc.preferredLanguage = LanguageTool.shared().currentLanguage
>     vc.languageBundle = Bundle.init(path: Bundle.main.path(forResource: LanguageTool.shared().currentLanguage, ofType: "lproj")!)
>     vc.iconThemeColor = ColorDefine.BrandColor.color
>     vc.navigationBar.setBackgroundImage(UIImage(), for: .default)
>     vc.navigationBar.shadowImage = UIImage()
>     vc.navigationBar.barTintColor = .white
>     vc.navigationBar.isTranslucent = false
>     vc.navigationBar.titleTextAttributes = [NSAttributedString.Key.foregroundColor : ColorDefine.FirstTextColor.color]
>     if #available(iOS 13.0, *) {
>         let appearance = UINavigationBarAppearance()
>         appearance.backgroundColor = .white
>         appearance.titleTextAttributes = [NSAttributedString.Key.foregroundColor : ColorDefine.FirstTextColor.color]
>         vc.navigationBar.standardAppearance = appearance
>         vc.navigationBar.scrollEdgeAppearance = appearance
>     }
>     vc.navLeftBarButtonSettingBlock = { btn in
>         btn?.setImage(UIImage.init(named: "nav_icon_return_black"), for: .normal)
>         btn?.setTitle(nil, for: .normal)
>     }
>     vc.barItemTextColor = ColorDefine.FirstTextColor.color
>     vc.photoPickerPageUIConfigBlock = { collectionView , bottomToolBar , previewBtn , _,_,doneBtn,_,_,line in
>         collectionView?.backgroundColor = .white
>         bottomToolBar?.backgroundColor = .white
>         line?.backgroundColor = ColorDefine.LineColor.color
>         previewBtn?.setTitleColor(ColorDefine.FirstTextColor.color, for: .normal)
>         previewBtn?.setTitleColor(UIColor.colorWithHexString("#999999"), for: .disabled)
>         doneBtn?.setTitleColor(ColorDefine.BrandColor.color, for: .normal)
>         doneBtn?.setTitleColor(UIColor.colorWithHexString("#999999"), for: .disabled)
>     }
>     vc.photoPreviewPageUIConfigBlock = { collectionView,naviBar,backButton,selectButton,_ ,toolBar,_,_,doneBtn,_,_ in
>         backButton?.setImage(UIImage.init(named: "nav_icon_return_black"), for: .normal)
>         doneBtn?.setTitleColor(ColorDefine.BrandColor.color, for: .normal)
>         doneBtn?.setTitleColor(UIColor.colorWithHexString("#999999"), for: .disabled)
>         naviBar?.backgroundColor = .white
>         toolBar?.backgroundColor = .white
>         
>     }
>     vc.albumPickerPageUIConfigBlock = { tableView in
>         tableView?.backgroundColor = .white
>     }
>     //        self.albumCellDidSetModelBlock = { cell , _ ,lb in
>     //            cell?.backgroundColor = .white
>     //            cell?.contentView.backgroundColor = .white
>     //            lb?.textColor = ColorDefine.FirstTextColor.color
>     //        }
>     vc.photoPickerPageDidLayoutSubviewsBlock = { collectionView , bottomToolBar , previewBtn , _,_,doneBtn,_,_,line in
>         previewBtn?.frame = CGRect.init(x: previewBtn!.frame.origin.x, y: previewBtn!.frame.origin.y, width: previewBtn!.currentTitle!.sizeWithText(font: previewBtn!.titleLabel!.font, size: CGSize.init(width: 0, height: 30)).width + 1, height: previewBtn!.frame.size.height)
>         doneBtn?.frame = CGRect.init(x: doneBtn!.frame.origin.x, y: doneBtn!.frame.origin.y, width: doneBtn!.currentTitle!.sizeWithText(font: doneBtn!.titleLabel!.font, size: CGSize.init(width: 0, height: 30)).width + 1, height: doneBtn!.frame.size.height)
>     }
>     
>     vc.allowPickingImage = true
>     vc.allowPickingOriginalPhoto = false
>     vc.allowCrop = false;
>     vc.allowPickingVideo = false
>     vc.modalPresentationStyle = .fullScreen
>     return vc
> }
> ```
> 
> }
> 
> class CusImagePickerController: TZImagePickerController {
> 
> ```
> override var preferredStatusBarStyle: UIStatusBarStyle {
>     return .default
> }
> ```
> 
> } ` 我复现不了，我手机没那么多图片呀

我也遇到了，没法复现，你那边解决了么

**Comment by sugite** [comment]
> Fatal Exception: NSInternalInconsistencyException Attempted to scroll the collection view to an out-of-bounds item (5168) when there are only 5168 items in section 0. Collection view: <TZCollectionView: 0x106336c00; baseClass = UICollectionView; frame = (0 0; 375 640); clipsToBounds = YES; hidden = YES; gestureRecognizers = <NSArray: 0x2807cc2a0>; layer = <CALayer: 0x280f7b4e0>; contentOffset: {-5, 0}; contentSize: {365, 119505}; adjustedContentInset: {5, 5, 5, 5}; layout: <UICollectionViewFlowLayout: 0x10b88ffb0>; dataSource: <TZPhotoPickerController: 0x105203400>>.
> 
> 还是有呀,3.8.1

@liuvbill  我也遇到了，但是没法复现，你那边解决了么

**Comment by lxm1799** [comment]
我也遇到了，可以换一个滚动到底部的方法.
[self->_collectionView scrollRectToVisible:CGRectMake(0, 0, self->_collectionView.tz_width, self->_collectionView.contentSize.height) animated:NO];

**Comment by GHeminghui** [comment]
Attempted to scroll the collection view to an out-of-bounds item (168) when there are only 168 items in section 0. Collection view: <TZCollectionView: 0x1071fd600; baseClass = UICollectionView; frame = (0 70; 834 1054); clipsToBounds = YES; hidden = YES; gestureRecognizers = <NSArray: 0x283fb62e0>; backgroundColor = <UIDynamicSystemColor: 0x282540800; name = tertiarySystemBackgroundColor>; layer = <CALayer: 0x28317da80>; contentOffset: {0, 7630.5}; contentSize: {824, 8699.5}; adjustedContentInset: {9, 5, 5, 5}; layout: <UICollectionViewFlowLayout: 0x14a60f2e0>; dataSource: <TZPhotoPickerController: 0x10619de00>>.

@sugite 我也遇到了线上报的这个问题，但无法复现

**Comment by bolee** [comment]
目前3.8.4，暂时没出现，不知道是否彻底解决了
