### ISSUE TITLE
允许视频/照片同时选择前提下，若最大可选择数为6，超过6以后，弹窗提示“你最多只能选择 6 张照片”，此处文案建议“你最多只能选择 6 个文件”

### ISSUE THREAD

**Issue by Cwolfberry** [banchichen/TZImagePickerController#1564]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.6.7

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**bug内容描述**
同标题

**我如何复现这个bug？**
同标题

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by lipopli** [comment]
通过重写TZImagePickerController 中的 - (UIAlertController *)showAlertWithTitle:(NSString *)title; 方法，可以自定义提示语

**Comment by banchichen** [comment]
微信的提示文案也是这样，不打算修改，有诉求的可参考上面的方案
