### ISSUE TITLE
webp格式图片保存相册出错

### ISSUE THREAD

**Issue by shichuanyang** [banchichen/TZImagePickerController#1568]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：不正常

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**bug内容描述**
保存webp格式的图片 失败

**我如何复现这个bug？**
直接照一张webp格式的图片进行保存

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
[BYIHKit_Example] findWriterForTypeAndAlternateType:119: unsupported file format 'org.webmproject.webp'
 BYIHKit_Example[8880:499786] 保存照片出错:未能完成操作。（PHPhotosErrorDomain错误3302。）

**Comment by banchichen** [comment]
我这个库哪里会涉及webp格式图片的保存？

**Comment by shichuanyang** [comment]
我这边的场景是  我生成了 webp格式的图片 然后调用yzimage 的方法去保存




------------------------------------------------------------------
发件人：谭真 ***@***.***>
发送时间：2022年1月12日(星期三) 15:24
收件人：banchichen/TZImagePickerController ***@***.***>
抄　送：石传洋 ***@***.***>; Author ***@***.***>
主　题：Re: [banchichen/TZImagePickerController] webp格式图片保存相册出错 (Issue #1568)

我这个库哪里会涉及webp格式图片的保存？
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
