### ISSUE TITLE
貌似有内存泄露

### ISSUE THREAD

**Issue by michaelxxw** [banchichen/TZImagePickerController#157]
如题，我项目中使用了MLeaksFinder检测循环引用问题，发现TZImagePickerController有报内存泄露，于是我下载了官方的demo测试了下，也有报。作者可以检查下看看，如果是误报，请忽略：）

**Comment by banchichen** [comment]
你好，我刚刚调试了下，发现当进入照片预览页面后，如不返回上一个页面，而是直接点击确定dismiss掉的话，此时的内存释放会延后10s左右，而不会立即释放...   通过Leaks分析倒没提示说有泄露...  我试着优化一下，看怎样让内存尽快释放掉~
