### ISSUE TITLE
添加一个不可取消 已选中资源 的代理方法

### ISSUE THREAD

**Issue by dagundejuzi** [banchichen/TZImagePickerController#1571]
**问：你希望加什么新功能？**
答：代理方法增加一个 isAssetCanBeDeselected 方法，控制已选中的资源是否可以取消选中。

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：没有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：应该不是所有人需要，但是加了也不会对现有功能有影响。

**其它你希望补充的内容**

**Comment by banchichen** [comment]
可以提个PR过来

**Comment by 173323222** [comment]
这个功能实现了吗？我这现在就有一个这样的需求。

已经选择过的照片，再次打开相册时，默认时选中状态，并且不能取消选择，最好之前已经选择过照片的✅都可以变色

**Comment by banchichen** [comment]
目前还没有

**Comment by banchichen** [comment]
欢迎PR，可以参考 isAssetCanBeSelected 方法做个类似的
