### ISSUE TITLE
拍照以后不保存系统相册，保存在app沙盒直接编辑

### ISSUE THREAD

**Issue by smallgirl** [banchichen/TZImagePickerController#1581]
/// This init method for crop photo / 用这个初始化方法以裁剪图片
- (instancetype)initCropTypeWithAsset:(PHAsset *)asset photo:(UIImage *)photo completion:(void (^)(UIImage *cropImage,PHAsset *asset))completion {
}

不保存系统相册 无法生成PHAsset 如何处理？

**Comment by banchichen** [comment]
你可以再接一个编辑的库哈，TZ没有支持拿UIImage编辑的计划
