### ISSUE TITLE
ipad 更新iOS 15系统以后圆形选中框发生偏移

### ISSUE THREAD

**Issue by GarinFan** [banchichen/TZImagePickerController#1582]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：无

2、你用的是什么版本？升级到最新版后是否正常？
答：3.7.0 有问题

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有改动

**bug内容描述**
ipad 更新iOS 15系统以后圆形白色选中框发生偏移
iphone 更新后使用同一个包，并没有问题

**我如何复现这个bug？**
我是开发的unity游戏，pod 'TZImagePickerController' 方式导入的最新代码
写了调用代码，没有改过源码

**截图**
代码截图：
![code](https://user-images.githubusercontent.com/13727711/155477111-78600e4f-1498-4cf5-82d9-5db09a49fae2.png)

ipad 截图：
![ipad(ios15)](https://user-images.githubusercontent.com/13727711/155477144-faad8584-8ea1-4413-8c97-a6330609f731.png)

iphone 截图：
![iphone(ios15)](https://user-images.githubusercontent.com/13727711/155477183-d3d12388-1815-48da-bc48-1f8207b85d31.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
初始化代码：
`
- (void)OpenPhotoLibrary:(int)outw outh:(int)outh isClip:(BOOL)isClip
{
    self.allowPhotoCrop = isClip;
    outW = outw;
    outH = outh;
    TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:maxImageCount delegate:self];
    
#pragma mark - 相册个性化设置
    
    imagePickerVc.allowTakePicture = NO;    // 内部显示拍照按钮
    imagePickerVc.allowTakeVideo = NO;      // 内部显示拍视频按钮
    
    imagePickerVc.allowPickingVideo = NO;   // 是否可以选择视频
    imagePickerVc.allowPickingGif = NO;     // 是否可以选择GIF图
    
    imagePickerVc.showSelectBtn = NO;
    imagePickerVc.allowCrop = self.allowPhotoCrop;
    imagePickerVc.needCircleCrop = self.allowPhotoCrop;
#pragma mark - 到这里为止
    
    // You can get the photos by block, the same as by delegate.
    // 你可以通过block或者代理，来得到用户选择的照片.
    [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
    }];
    
    imagePickerVc.modalPresentationStyle = UIModalPresentationPageSheet;
    [[UIApplication sharedApplication].delegate.window.rootViewController presentViewController:imagePickerVc animated:YES completion:nil];
}
`

**Comment by banchichen** [comment]
demo是好的，因为设置了imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen，全屏弹出TZ图片选择器，建议你也加上

如果希望不全屏弹的话，继续往下看：
1、cropRect是弹出前设置的，按当前视图宽（self.view.tz_width，也就是屏幕宽）来算的，比如demo是这样设的：
```objectivec
    NSInteger left = 30;
    NSInteger widthHeight = self.view.tz_width - 2 * left;
    NSInteger top = (self.view.tz_height - widthHeight) / 2;
    imagePickerVc.cropRect = CGRectMake(left, top, widthHeight, widthHeight);
```
当非全屏弹出TZ的时候，TZ照片预览页面的宽度，是小于self.view.tz_width的，相当于屏幕变小了，但 X / left 值没变
一个给大屏设置的框，被用到了小屏了
所以框看起来往右移了
2、解决办法：延迟imagePickerVc.cropRect的设置，用真实的imagePickerVc.view.width来计算cropRect
比如把上面那坨代码，改为：
```objectivec
  __weak typeof(imagePickerVc) weakPicker = imagePickerVc;
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        NSInteger left = 30;
        NSInteger widthHeight = weakPicker.view.tz_width - 2 * left;
        NSInteger top = (self.view.tz_height - widthHeight) / 2;
        weakPicker.cropRect = CGRectMake(left, top, widthHeight, widthHeight);
    });
```

**Comment by banchichen** [comment]
手机是好的，因为TZ图片选择器是满屏宽的，imagePickerVc.view.width = self.view.tz_width
