### ISSUE TITLE
iPhoneXS 15.2 使用3.7.3版本 ，第一次唤起摄像头拍照 ，需要等待很久

### ISSUE THREAD

**Issue by TQDJonas** [banchichen/TZImagePickerController#1583]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.7.3

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**bug内容描述**
iPhoneXS 15.2 使用3.7.3版本 ，第一次唤起摄像头拍照 ，需要等待20多秒钟 。

**我如何复现这个bug？**
使用iOS系统15.2版本，然后重装3.7.3 版本dome ，第一次使用拍照功能，然后就会卡在当前界面很久

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
@TQDJonas Demo里，选中「把拍照按钮放在外面」，此时去拍照会卡住吗？

**Comment by TQDJonas** [comment]
3.7.3 Dome  把拍照按钮放在外面 ，第一次使用 也会卡很久 。

**Comment by banchichen** [comment]
@TQDJonas 这个就和TZ没任何关系了哈，放在外面，TZ的代码还没执行，只是走了demo里的调起相机

**Comment by banchichen** [comment]
可以试试其它APP拍照是不是也如此，然后也可以重启手机试试
