### ISSUE TITLE
视频预览 playButton 自定义图片只在初始 生效 点击播放暂停后还是原来的icon

### ISSUE THREAD

**Issue by JoyTomi** [banchichen/TZImagePickerController#1584]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
已优化，新版本3.7.6
