### ISSUE TITLE
希望增加 获取图片格式的接口

### ISSUE THREAD

**Issue by shichuanyang** [banchichen/TZImagePickerController#1587]
**问：你希望加什么新功能？**
答：获取原图格式

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：好像没发现

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：图片格式 通用信息, 因为苹果相册里有很多格式 

**其它你希望补充的内容**

**Comment by banchichen** [comment]
自己研究下哈，PHAsset返回出去了
可以参考：https://stackoverflow.com/questions/35353042/how-to-properly-detect-a-phassets-file-type-gif
