### ISSUE TITLE
将相册权限设置为部分照片,拍照后页面会闪烁(必现)

### ISSUE THREAD

**Issue by 19aneng** [banchichen/TZImagePickerController#1588]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

**bug内容描述**
将相册权限设置为部分照片,拍照后页面会闪烁

**我如何复现这个bug？**
将相册权限设置为部分照片,拍照后页面会闪烁.(必现)

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by 19aneng** [comment]
@banchichen 
iOS 15,iPhone12,相册设置为部分权限,拍照后相册列表刷新闪烁,滑动列表闪烁.旧的SDK和新的SDK都会

**Comment by 19aneng** [comment]
![image](https://user-images.githubusercontent.com/22389902/160738530-27e485db-6694-42b9-b0e8-1fc4e63df718.png)
![image](https://user-images.githubusercontent.com/22389902/160739928-9b2b6f36-0e17-487a-8986-30e5dd6c0310.png)

**Comment by 19aneng** [comment]
拍照后闪烁问题主要是这里,之前基本上同步执行完,马上异步回调.
拍照后,获取图片异步变慢了

**Comment by 19aneng** [comment]
![image](https://user-images.githubusercontent.com/22389902/160741919-ea506f9a-7a3a-4445-8170-a793848f4a51.png)
![image](https://user-images.githubusercontent.com/22389902/160741933-fc72f9a1-0051-4caf-9f81-33b8df2fc6b4.png)

**Comment by banchichen** [comment]
欢迎提PR哈

**Comment by banchichen** [comment]
优化了下，应该好些了，改动代码是：https://github.com/banchichen/TZImagePickerController/commit/a37ed2e39257246d27cb27eb67414b042562b9c6

**Comment by ToninZhao** [comment]
现在还能复现这个问题。TZImagePickerController 版本3.8.3
