### ISSUE TITLE
希望添加多选剪切功能

### ISSUE THREAD

**Issue by mqingG** [banchichen/TZImagePickerController#1589]
**问：你希望加什么新功能？**
答：多选时限制必须剪切，按照固定比例剪切

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：否

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合，需要添加属性开关

**其它你希望补充的内容**

**Comment by banchichen** [comment]
应该不会支持哈，建议调研下专门的裁剪库，和TZ联合使用
如有需要TZ配合的地方，欢迎PR，和专门的裁剪库配合一起实现这个需求
