### ISSUE TITLE
最好在图片预览的时候，可以进行编辑（马赛克，画笔，裁剪等），可参考TOCropViewController

### ISSUE THREAD

**Issue by wty302857194** [banchichen/TZImagePickerController#1590]
类似微信图片编辑

**Comment by banchichen** [comment]
不会内置这种复杂裁剪哈，可以设置autoDismiss为NO，自己对接后续的裁剪功能，看起来 #https://github.com/banchichen/TZImagePickerController/issues/1622 是这样做的
