### ISSUE TITLE
希望可以支持实况照片

### ISSUE THREAD

**Issue by json1994** [banchichen/TZImagePickerController#1594]
**问：你希望加什么新功能？**
答：希望可以支持实况照片

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：未测试

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：可以加个属性开关

**其它你希望补充的内容**

**Comment by banchichen** [comment]
#1416

**Comment by banchichen** [comment]
duplicate of #1343
