### ISSUE TITLE
使用instrument跑了一下，有一些内存问题

### ISSUE THREAD

**Issue by wqforever** [banchichen/TZImagePickerController#1596]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.1

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

有一些内存峰值，包括一些内存泄露
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/15868474/168719443-fff03aaf-a7f7-4a9a-84ac-ae81f10a66e0.png">

**Comment by banchichen** [comment]
欢迎提PR哈

**Comment by wqforever** [comment]
还没找到解决办法，我看下怎么解决再提PR吧
