### ISSUE TITLE
iOS 15.2 Unauthorized access: client does not have valid TCC authorization

### ISSUE THREAD

**Issue by huainanzi** [banchichen/TZImagePickerController#1597]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.1

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没

**bug内容描述**
通过[TZImageManager manager]getCameraRollAlbumWithFetchAssets获取相册图片，进行授权，在打开相册卡死或白屏。

**我如何复现这个bug？**
demo中的viewDidAppear:调用[TZImageManager manager]getCameraRollAlbumWithFetchAssets

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
可以参考这个判断：
```
if ([[TZImageManager manager] authorizationStatusAuthorized] || !SYSTEM_VERSION_GREATER_THAN_15) {
    [[PHPhotoLibrary sharedPhotoLibrary] registerChangeObserver:self];
}
```
iOS15下未被授权时，不能调访问相册数据的API

**Comment by banchichen** [comment]
你在外面需要访问相册数据的话，未授权时，你可以设计个引导页面，引导用户授权，授权完成才能调，可以参考TZ的引导界面
