### ISSUE TITLE
相册权限文案本地化更新不及时问题

### ISSUE THREAD

**Issue by jokeface** [banchichen/TZImagePickerController#1598]
1.关闭app相册权限
2.代码设置 PreferredLanguage = “zh-Hans”
3. 点击present方法调用（这时候显示“请在iPhone的\"设置-隐私-照片\"选项中，允许%@访问你的手机相册”）
4. 同时调用方法 PreferredLanguage = “en”
5. 点击present方法调用（这时候依旧显示“请在iPhone的\"设置-隐私-照片\"选项中，允许%@访问你的手机相册”
6. 再一次点击present方法调用（这时候才显示正确的"Allow %@ to access your album in \"Settings > Privacy > Photos\")

**Comment by banchichen** [comment]
不要复用TZImagePickerController实例哈，每次都present一个新的
