### ISSUE TITLE
关闭可选择gif图片时,gif图还是能在选择图片界面展示

### ISSUE THREAD

**Issue by zhou963215** [banchichen/TZImagePickerController#1599]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：新demo也有这个问题

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有改动

**bug内容描述**

**我如何复现这个bug？**

**截图**
<img width="306" alt="image" src="https://user-images.githubusercontent.com/15116416/171380060-cdfff890-0481-4077-887b-51f40a223b36.png">
最后一张为gif格式图片

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
设计上是这样的，不可选择GIF时，GIF会被当成普通图片
需要过滤掉不显示的话，可以实现 isAssetCanBeDisplayed
