### ISSUE TITLE
除了楼上说的问题外还有两点问题我觉得也需要修复一下

### ISSUE THREAD

**Issue by veryip7** [banchichen/TZImagePickerController#16]
1. 如果设置imagePicker.allowPickingVideo = NO;
在相机胶卷中就不应该出现视频，应该过滤掉。
2. 选择两张图片后，进入预览，在预览界面再将两张图片取消选中，确定按钮可以点击，点击后会选择一张图片（应该一张图片都没有。）

3.还有一点：
在getPhotoWithAsset:photoWidth:completion:函数中，
CGImageRef thumbnailImageRef = alAsset.aspectRatioThumbnail;这句如果在ios6.0平台，缩略图会很模糊，感觉改为：CGImageRef thumbnailImageRef = alAsset.thumbnail;比较合适。

**Comment by banchichen** [comment]
你好，谢谢指出。
1. 已修复~漏了一句判断...
2. 这个我是完全参照微信来做的，微信也是这样子的~在没有选中任何图片的情况下，在预览界面中点击确定按钮，会把这一张图片带出去~
3. 我测试iOS6设备时发现没怎么模糊~这个我之后再好好研究吧~如果你找到了准确的资料，请再回复我~
