### ISSUE TITLE
图片选择界面 导航栏 添加其他按钮

### ISSUE THREAD

**Issue by shichuanyang** [banchichen/TZImagePickerController#1600]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：没有

2、你用的是什么版本？升级到最新版后是否正常？
答：正常

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

图片选择页面的导航栏如何实现 图片中的效果

![image](https://user-images.githubusercontent.com/75350000/172130169-8da882b9-ca75-4f1a-af60-2db6f6028ab0.png)

**Comment by shichuanyang** [comment]
我直接设置 self.imagePickerVc.navigationItem.rightBarButtonItems = xxx
不生效

**Comment by banchichen** [comment]
库里面会在viewDidLoad的时候设置navigationItem.rightBarButtonItem，你可以setTimeout一下试试，或者hook TZPhotoPickerController 的viewWillAppear

**Comment by banchichen** [comment]
如有其它需要库里开口子配合的地方，可以提个PR
