### ISSUE TITLE
截图功能太弱了

### ISSUE THREAD

**Issue by vitasapple** [banchichen/TZImagePickerController#1602]
**问：你希望加什么新功能？**
答：截图功能太弱，希望能加一个自由选择范围可拖动的截图控件

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：业务不同

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：要加属性开关

**其它你希望补充的内容**

**Comment by banchichen** [comment]
没有优化的计划哈，建议对接专业的裁剪库一起使用，配合过程中tz可以开一些口子，欢迎PR
