### ISSUE TITLE
使用swift package manager 集成时出现错误。

### ISSUE THREAD

**Issue by iT-Boyer** [banchichen/TZImagePickerController#1604]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有
2、你用的是什么版本？升级到最新版后是否正常？
答：master版本，问题仍在

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

**bug内容描述**
```

Showing All Messages
target 'TZImagePickerController' has invalid header layout: umbrella header found at '../TZImagePickerController/TZImagePickerController/TZImagePickerController/TZImagePickerController.h', but directories exist next to it: .../TZImagePickerController/TZImagePickerController/TZImagePickerController/TZImagePickerController.bundle; consider removing them=
```

**我如何复现这个bug？**
按照xcode SPM 集成包的方式，集成后会提示以上错误。

**截图**
![截屏2022-06-22 13 24 31](https://user-images.githubusercontent.com/4022953/174950068-ae48943e-1c0c-4ef1-bea7-8780b98c4a28.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
老哥，来个PR不

**Comment by EngineHG** [comment]
@banchichen 建议参考 MJRefresh 修改一下 Package.swift 应该就可以解决上面的问题
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/8623979/181405485-41b9cdf8-d9c4-4778-99b5-99f888340d7d.png">

**Comment by EngineHG** [comment]
@iT-Boyer 我解决了这个问题，等作者合PR了，你也可以先用我这里的修改 https://github.com/EngineHG/TZImagePickerController

**Comment by banchichen** [comment]
3.8.12版本已支持SPM
