### ISSUE TITLE
友盟搜集到的Bug

### ISSUE THREAD

**Issue by ITzhao** [banchichen/TZImagePickerController#1605]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：使用3.7.0，升级后也存在

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**bug内容描述**
获取图片错误

**我如何复现这个bug？**
系统：iOS14.4.1， 日志如下
TZImagePickerController  Application threw exception NSInvalidArgumentException: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]6 TZImagePickerController 0x0000000106614e7c __82-[TZPhotoPickerController pushPhotoPrevireViewController:needCheckSelectedModels:]_block_invoke.645 + [TZPhotoPickerController.m : 828]

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
你在我最新Demo里如何复现这个问题？
我这是好的
