### ISSUE TITLE
V3.8.1，相册空数据占位显示错误

### ISSUE THREAD

**Issue by BigPoro** [banchichen/TZImagePickerController#1607]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：不确定，目前使用最新版本SDK.

2、你用的是什么版本？升级到最新版后是否正常？
答：V3.8.1。

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无。

**bug内容描述**
相册空数据占位显示错误，出现字体重叠，有图片还提示无图片或视频

**我如何复现这个bug？**
清空部分选择的照片，切换到所有权限，再切换到部分，选择一个视频，再选择一个图片，查看显示。
系统为iOS15.0

**截图**
![file-read-11852](https://user-images.githubusercontent.com/23748306/179969072-aa9ab7b9-06ce-4223-a1b0-6f29143e63c8.png)
![file-read-11853](https://user-images.githubusercontent.com/23748306/179969673-55ef2de3-0c33-4281-8d39-82bc13940a4c.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
```
    TZImagePickerController *vc = [[TZImagePickerController alloc] initWithMaxImagesCount:1 columnNumber:4 delegate:self pushPhotoPickerVc:YES];
    vc.allowPickingImage = YES;
    vc.allowPickingOriginalPhoto = YES;
    vc.sortAscendingByModificationDate = NO;
    vc.showSelectBtn = NO;
    vc.allowTakePicture = NO;
    vc.allowCameraLocation = NO;
    vc.allowTakeVideo = NO;
    vc.allowPickingVideo = NO;
    vc.statusBarStyle = UIStatusBarStyleLightContent;
    vc.showSelectedIndex = NO;
    vc.modalPresentationStyle = UIModalPresentationFullScreen;
    [self presentViewController:vc animated:YES completion:nil];
```

**Comment by Tralny** [comment]
我也有这个问题，但是我不能每次都浮现

**Comment by banchichen** [comment]
这个PR已经修复了：https://github.com/banchichen/TZImagePickerController/pull/1663
