### ISSUE TITLE
求大大解答：最新版本，iOS15导航栏上的取消按钮点了没反应，完全不知道该怎么处理，

### ISSUE THREAD

**Issue by Krysaya** [banchichen/TZImagePickerController#1608]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：不知道

2、你用的是什么版本？升级到最新版后是否正常？
答：最新

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**Comment by banchichen** [comment]
为什么不试试demo？demo可以，你那不可以的话，就对比下使用上差异
