### ISSUE TITLE
照片流

### ISSUE THREAD

**Issue by zhumeiteng** [banchichen/TZImagePickerController#161]
选择照片流中的账片有些不成功

**Comment by banchichen** [comment]
你好，麻烦提供下更多信息，选照片的时候，会走TZImageManager中getPhotoWithAsset方法，取到图片后便会返回，如果一直转菊花，说明图片还没取回来，可能是该图片是在iCloud中存储的，麻烦你在那调试下，为什么成功的回调没走...

**Comment by smartom101** [comment]
这个问题我也遇到了，上传icloud的图片获取asset会一直等下载图片，所以菊花一直转，不知道能不能直接获取本地版本，不等下载高清版本，我看微信就是直接用的本地非高清版本的照片的

**Comment by banchichen** [comment]
抱歉...各位久等了，最近难得闲下来一会，今天把iCloud图片的显示与选择做了优化：
1、iCloud中存储的照片未同步到本地前，是会提示用户正在同步照片，并且有圆环指示器显示进度~  
2、在用户选中某一个图片时，会去请求该图片的大图（如果结果表明大图存储在iCloud中则会去同步iCloud中的大图），如果用户取消选中，则会取消同步大图的请求。

之前的代码中，默认菊花的转圈是15秒，如果图片不是很小，15秒是不够同步iCloud照片的，因此经常出现菊花结束了，但是照片选择器没dismiss...所以十分不友好...

目前最新的版本是1.7.3，已经更新到github和CocoaPods，上次1.7.2的版本主要是加入了裁剪功能，允许在单选模式下用任意矩形框裁剪图片。欢迎大家更新到新版....
