### ISSUE TITLE
所以使用图片的地方都会出现原生键盘偏移的问题

### ISSUE THREAD

**Issue by linqifeng26147** [banchichen/TZImagePickerController#1612]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.7.6 暂时无法升级到最新版

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

**bug内容描述**
所以使用图片的地方都会出现原生键盘偏移的问题

**我如何复现这个bug？**
选择图片 拍照 反复 然后再使用输入框 然后偶尔会出现前面的导航标题  返回消失  和键盘中间模块偏移的问题

**截图**
![image](https://user-images.githubusercontent.com/95924075/183591469-990ddb7d-bd9d-4557-81ee-24be702d1ea6.png)
![image](https://user-images.githubusercontent.com/95924075/183591776-16f4de2b-0698-438b-bfa9-a558cb05e7fc.png)
![image](https://user-images.githubusercontent.com/95924075/183591986-7125e322-fad4-40a1-98a5-61666944ebdd.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
1、我最新的Demo是否有这个bug？【如果Demo没问题，请升级新版】
答：是

既然Demo能复现的话，贴图应该是Demo的哈。然后把复现后的Demo工程可以打包发出来下，我需要有个可复现的工程进行排查
