### ISSUE TITLE
怎么清除相册选择记忆？

### ISSUE THREAD

**Issue by sking100** [banchichen/TZImagePickerController#1618]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.1

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：只是修改了icon和字体颜色
  进入相册选择N张照片回到上级页面，再次进入相册页面，上次的选择依然保留了

**Comment by banchichen** [comment]
不传selectedAssets

**Comment by sking100** [comment]
我现在改成每次进相册都创建一个新的，这样能避免保留上次选择的问题

**Comment by banchichen** [comment]
可以的，推荐这样做，Demo也是如此
