### ISSUE TITLE
能不能增加一个Flutter版本？

### ISSUE THREAD

**Issue by tianxiawoyougood** [banchichen/TZImagePickerController#1619]
**问：你希望加什么新功能？**
答：增加Flutter版本

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
没有计划哈...欢迎PR
