### ISSUE TITLE
iOS8 使用allowsCachingHighQualityImages属性crash

### ISSUE THREAD

**Issue by LIVE1016** [banchichen/TZImagePickerController#162]
iOS8系统中，关闭照片权限的情况下，使用allowsCachingHighQualityImages属性会造成crash，日志如下：
 *** This application is not allowed to access Photo data. (
	0   PhotoLibraryServices                0x000000018daced1c <redacted> + 668
	1   Photos                              0x0000000185f7c27c <redacted> + 68
	2   libdispatch.dylib                   0x0000000102214f94 _dispatch_client_callout + 16
	3   libdispatch.dylib                   0x0000000102215ea0 dispatch_once_f + 148
	4   Photos                              0x0000000185f7c230 <redacted> + 156
	5   Photos                              0x0000000185f503e8 <redacted> + 88
	6   Photos                              0x0000000185f6d2b4 <redacted> + 112
	7   Photos                              0x0000000185f6e38c <redacted> + 68
	8   SuperCarMan                         0x00000001008dfab4 __25+[TZImageManager manager]_block_invoke + 228
	9   libdispatch.dylib                   0x0000000102214f94 _dispatch_client_callout + 16
	10  libdispatch.dylib                   0x0000000102215ea0 dispatch_once_f + 148
	11  SuperCarMan                         0x00000001008df9b0 +[TZImageManager manager] + 144
	12  SuperCarMan                         0x00000001008e9f60 -[TZImagePickerController viewDidLoad] + 400
	13  SuperCarMan                         0x00000001007672c0 __vcViewDidLoad + 440
	14  UIKit                               0x0000000186924a6c <redacted> + 692
	15  UIKit                               0x000000018692477c <redacted> + 32
	16  UIKit                               0x00000001869b46f4 <redacted> + 488
	17  UIKit                               0x00000001869b44e8 <redacted> + 532
	18  SuperCarMan                         0x00000001008ed34c -[TZImagePickerController pushViewController:animated:] + 1176
	19  UIKit                               0x0000000186a11e58 <redacted> + 148
	20  SuperCarMan                         0x00000001008ea8b0 -[TZImagePickerController initWithMaxImagesCount:delegate:] + 168
	21  SuperCarMan                         0x00000001004e350c -[TestViewController tableView:didSelectRowAtIndexPath:] + 400
	22  SuperCarMan                         0x000000010077f4b8 __tableDidSelectRow + 496
	23  UIKit                               0x0000000186a4d25c <redacted> + 1280
	24  UIKit                               0x0000000186b07578 <redacted> + 276
	25  UIKit                               0x00000001869a8028 <redacted> + 356
	26  UIKit                               0x00000001869184d4 <redacted> + 536
	27  CoreFoundation                      0x0000000181e5fff0 <redacted> + 32
	28  CoreFoundation                      0x0000000181e5cf7c <redacted> + 360
	29  CoreFoundation                      0x0000000181e5d35c <redacted> + 836
	30  CoreFoundation                      0x0000000181d88f74 CFRunLoopRunSpecific + 396
	31  GraphicsServices                    0x000000018b7e36fc GSEventRunModal + 168
	32  UIKit                               0x000000018698ad94 UIApplicationMain + 1488
	33  SuperCarMan                         0x0000000100422264 main + 124
	34  libdyld.dylib                       0x0000000194226a08 <redacted> + 4
)
2016-08-08 14:09:15.832 SuperCarMan[7275:690211] *** Terminating app due to uncaught exception 'NSObjectInaccessibleException', reason: 'This application is not allowed to access Photo data.'

**Comment by banchichen** [comment]
你好，谢谢反馈，最新的代码中已经修复了的哈。不过pod版本还没更新，还是1.5.0...
