### ISSUE TITLE
iOS16 present之后，内存出现暴涨，直至应用被关闭，状态栏已经改变，但是控制器未显示出来

### ISSUE THREAD

**Issue by CarvenChen** [banchichen/TZImagePickerController#1621]
如题
    TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:1 columnNumber:4 delegate:nil pushPhotoPickerVc:YES];
    imagePickerVc.allowTakePicture = NO;
    imagePickerVc.allowTakeVideo = NO;
    imagePickerVc.videoMaximumDuration = 0;
    imagePickerVc.allowEditVideo = NO;
    imagePickerVc.iconThemeColor = KColorTheme;
    imagePickerVc.showPhotoCannotSelectLayer = NO;
    imagePickerVc.cannotSelectLayerColor = [[UIColor whiteColor] colorWithAlphaComponent:0.8];
    imagePickerVc.allowPickingVideo = NO;
    imagePickerVc.allowPickingImage = NO;
    imagePickerVc.allowPickingOriginalPhoto = NO;
    imagePickerVc.allowPickingGif = NO;
    imagePickerVc.allowPickingMultipleVideo = NO;
    imagePickerVc.sortAscendingByModificationDate = YES;
    imagePickerVc.statusBarStyle = UIStatusBarStyleLightContent;
    imagePickerVc.showSelectedIndex = YES;
    imagePickerVc.allowCameraLocation = NO;
    imagePickerVc.preferredLanguage = @"zh-Hans";

    imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen;
    [self presentViewController:imagePickerVc animated:YES completion:^{
        
    }];

**Comment by Moshimol** [comment]
我也出现了

**Comment by graygrayh** [comment]
iOS16下出现了内存问题

**Comment by Moshimol** [comment]
imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen; 删除这一行

**Comment by CarvenChen** [comment]
> imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen; 删除这一行 目前还没探索什么原因呢

测试过，不行

**Comment by graygrayh** [comment]
> 
查看一下项目内对NSMutableDictonary的Hook，这里跟IOS16导航栏的rightBarButtonItem产生了冲突，注释掉项目内的Hook看看

**Comment by yunxiuwu** [comment]
> > 
> 
> 查看一下项目内对NSMutableDictonary的Hook，这里跟IOS16导航栏的rightBarButtonItem产生了冲突，注释掉项目内的Hook看看

根据所说，将UIBarButtonItem的rightBarButtonItem创建模式改成了CustomView，解决了问题。感谢

**Comment by lilin87788** [comment]
我也出现了，谁知道什么原因

**Comment by Moshimol** [comment]
https://juejin.cn/post/7146450825257156638

**Comment by lilin87788** [comment]
@banchichen  大神出来看一看

**Comment by lilin87788** [comment]
> imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen; 删除这一行 目前还没探索什么原因呢

亲测有效

**Comment by banchichen** [comment]
有人解决了，把 NSDictionary-NilSafe 库移除掉可解
这种Hook系统类的行为很危险的，系统升级都可能出问题，非必要不建议...
可以在这个issue里跟进：https://github.com/allenhsu/NSDictionary-NilSafe/issues/12

**Comment by herolsl** [comment]
> 有人解决了，把 NSDictionary-NilSafe 库移除掉可解
> 这种Hook系统类的行为很危险的，系统升级都可能出问题，非必要不建议...
> 可以在这个issue里跟进：[allenhsu/NSDictionary-NilSafe#12](https://github.com/allenhsu/NSDictionary-NilSafe/issues/12)

以及 [[UIBarButtonItem alloc]initWithTitle  这个方法也会爆内存
