### ISSUE TITLE
dismissViewControllerAnimated由业务控制

### ISSUE THREAD

**Issue by Jerryshen170918** [banchichen/TZImagePickerController#1622]
**问：你希望加什么新功能？**
答：dismissViewControllerAnimated由业务控制

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：大厂有这个功能

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合所有人，可以加属性开关控制

**其它你希望补充的内容**
dismissViewControllerAnimated动画在内部写死了，动画一闪而过体验不是很好。
业务场景：从相册选中完图片后，调用业务方裁剪控制器，此时相册控制器dismiss的动画给产品带来了不好体验。

**Comment by banchichen** [comment]
有个autoDismiss属性，可以设置为NO，可以试试哈
