### ISSUE TITLE
阿拉伯语未适配，且有bug

### ISSUE THREAD

**Issue by zhang-lei-333** [banchichen/TZImagePickerController#1623]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.3，不正常

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**bug内容描述**
1、设置阿拉伯语后，导航栏的文字和工具栏的文字未适配。将Localizable文件里面白色文字的双引号删除即可

2、未适配镜像模式（显示左右相反）。百度或者下载海外的app设置阿拉伯语后的效果

3、设置镜像后，点击的照片与详情的照片不一致，具体看截图

**我如何复现这个bug？**

设置镜像模式的代码
[UIView appearance].semanticContentAttribute = UISemanticContentAttributeForceRightToLeft;
[UISearchBar appearance].semanticContentAttribute = UISemanticContentAttributeForceRightToLeft;
[[UINavigationBar appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];

**截图**

![732A92F9-0326-4A07-9C5A-706A4E2D17E9](https://user-images.githubusercontent.com/34759865/192474802-9ad8b88f-afec-4d74-8fd7-38c5d1dfd04c.png)
![A45F03D9-0530-4758-95C0-458CBBD4C9BE](https://user-images.githubusercontent.com/34759865/192474865-057238dd-28ee-43b4-ad18-7d51dd7a9f5e.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

demo里面唯一会修改的地方是：设置语言

**Comment by banchichen** [comment]
导航栏上的文字，是读的系统返回的，如不是预期的语言，可以参考：
Q：系统语言是中文/英文，界面上却有部分相册名字、返回按钮显示成了英文/中文？
A：请参考 https://github.com/banchichen/TZImagePickerController/issues/443 和 https://github.com/banchichen/TZImagePickerController/issues/929

其它的部分，欢迎提个PR呀👍

**Comment by banchichen** [comment]
老哥，阿拉伯语适配的问题，有老哥提了个PR：https://github.com/banchichen/TZImagePickerController/pull/1611
我已经合了，你帮忙试下最新的demo是否正常？正常的话我发个版本

**Comment by wanghan295687016** [comment]
阿拉伯语言，相册选择正常，点击图片预览错误，这个什么时候修复

**Comment by banchichen** [comment]
@wanghan295687016 欢迎PR哈
