### ISSUE TITLE
图片预览页面增加下滑拖动手势关闭预览页面的功能

### ISSUE THREAD

**Issue by PandexLee** [banchichen/TZImagePickerController#1624]
**问：你希望加什么新功能？**
答：图片预览页面增加下滑手势关闭预览页面的功能

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合，不需要加开关

**其它你希望补充的内容**
如今大多数APP的图片预览时都支持滑动手势关闭预览，所以大多数iPhone用户都有此操作习惯。

而[TZImagePickerController](https://github.com/banchichen/TZImagePickerController)的图片预览时只能点击左上角返回按钮关闭预览，单击图片为全屏预览(隐藏导航栏和工具栏)，在如今的大屏时代操作起来非常困难，希望增加此功能。

操作起来类似[GKPhotoBrowser](https://github.com/QuintGao/GKPhotoBrowser)
GKPhotoBrowser使用示例：
```
var photos = [GKPhoto]()
let browser = GKPhotoBrowser(photos: photos, currentIndex: 0)
browser.showStyle = .zoom
browser.hideStyle = .zoomScale
browser.show(fromVC: Router.getTopViewController()!)

```

**Comment by banchichen** [comment]
老哥，欢迎来个PR哈
