### ISSUE TITLE
你好，请问是否支持记住之前选过的图片功能？

### ISSUE THREAD

**Issue by kakashilw** [banchichen/TZImagePickerController#1625]
就是比如我选择了一张图片，然后再点击选择图片时，自动调整到上次选择的图片周围。

**Comment by banchichen** [comment]
目前只能通过selectedAssets记录已选的图片

要实现类似「自动调整到上次选择的图片周围」的话，可以缓存住tzImagePicker实例，不让它销毁，类似pop出栈的效果，这样可以停留在上次滑动的位置

**Comment by banchichen** [comment]
目前只能通过selectedAssets记录已选的图片

要实现类似「自动调整到上次选择的图片周围」的话，可以缓存住tzImagePicker实例，不让它销毁，类似pop出栈的效果，这样可以停留在上次滑动的位置
