### ISSUE TITLE
取消按钮 会自动往右偏移

### ISSUE THREAD

**Issue by FzyJanm** [banchichen/TZImagePickerController#1626]
[**咨询前必看**]
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：
有
2、你用的是什么版本？升级到最新版后是否正常？
答：
3.8.3
3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有
![WechatIMG49](https://user-images.githubusercontent.com/29218978/196648832-6f6b7244-ddde-449d-8d45-2d65aad8e06a.png)

**Comment by banchichen** [comment]
无法复现，你确定你那demo可以复现？

**Comment by banchichen** [comment]
demo正常，你的项目有问题的话，考虑逐步注释掉可能对导航栏产生影响的库来定位，定位到了后，升级这个库 or 给这个库提issue

**Comment by FzyJanm** [comment]
好的 刚看到 我查一下项目里的问题吧
