### ISSUE TITLE
多张gif图上传的问题：会成为普通的静态图片。单传一张的可以从预览gifdata中获取，上传gifdata就可以，多张gif图上传没有地方拿到..

### ISSUE THREAD

**Issue by zhYes** [banchichen/TZImagePickerController#1627]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.3

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：否

**Comment by banchichen** [comment]
多张的时候，通过selectedAssets能获取到原始的图片data，可以看看TZImageManager里的方法
