### ISSUE TITLE
使用前置摄像头拍照照片会左右翻转，请问怎么关闭？

### ISSUE THREAD

**Issue by liuyidao** [banchichen/TZImagePickerController#1631]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**Comment by banchichen** [comment]
你用系统相机自拍，也是这样的吧...
