### ISSUE TITLE
我的需求是 只能选择 gif 格式的图片  不能选择其他格式的图片或视频 该如何设置 

### ISSUE THREAD

**Issue by shichuanyang** [banchichen/TZImagePickerController#1634]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：调试的demo 没有不知道该如何设置

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

我的需求是 只能选择 gif 格式的图片  不能选择其他格式的图片或视频 该如何设置

**Comment by banchichen** [comment]
看下头文件，有代理方法，让你设置照片是否展示、是否可选择
