### ISSUE TITLE
 在弹出的相册里只能显示选择 gif 格式的图片 不能显示选择其他格式的图片或视频 该如何设置

### ISSUE THREAD

**Issue by shichuanyang** [banchichen/TZImagePickerController#1635]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：调试的demo 没有这个功能  不知道该如何设置

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

可能是我上个issue 没表述明白  
现在我尝试设置了好多属性,  但在弹出的相册里   还会显示其他格式的图片

我需要的效果是: 在弹出的相册里 只显示gif格式的图片 其他格式的图片都不显示  这种效果该如何设置啊

**Comment by banchichen** [comment]
Duplicate of #https://github.com/banchichen/TZImagePickerController/issues/1634

**Comment by banchichen** [comment]
如钉钉群沟通：
Q：您好，我想让弹出的相册里 只显示GIF格式的图片，该如何设置？  demo里我弄不出来，看头文件也没有找到相关的设置，我看那些是否可以选择 是否可以显示的方法 都需要传一个phasset   
A：那个不是你传的，是代理方法，我里面传给你，你判断要不要显示的
