### ISSUE TITLE
iOS 16.4 Xcode 14.3 无法编译

### ISSUE THREAD

**Issue by YangShenLy** [banchichen/TZImagePickerController#1639]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：TZImageController 3.8.3 版本, 无法编译, iOS 16.4 Xcode 14.3

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

**bug内容描述**
无法编译

**我如何复现这个bug？**
 file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a

**截图**
<img width="888" alt="截屏2023-03-31 10 09 01" src="https://user-images.githubusercontent.com/16348872/229005038-6e5e4edd-18bb-45a8-b2c4-f2aadf05db61.png">

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by mengxianliang** [comment]
看这里：https://www.jianshu.com/p/fb1178645292
