### ISSUE TITLE
相册权限 选“选中的照片” 进到相册

### ISSUE THREAD

**Issue by linlishu8** [banchichen/TZImagePickerController#1640]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新的还是有

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**bug内容描述**

**我如何复现这个bug？**
相册权限 选“选中的照片” 进到相册 只允许选择视频，点开相册列表选择授权文件，不选所选视频只选图片，多选几次，无照片或视频的文字会多次添加，就算选择了视频返回，文字还在

**截图**
<img width="250" alt="image" src="https://user-images.githubusercontent.com/6946872/231745513-514aa286-ed10-472c-8252-5a44728d700b.png">

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
老哥，来个CR不

**Comment by banchichen** [comment]
试了下可以了，应该是这个PR修复了：https://github.com/banchichen/TZImagePickerController/pull/1663
