### ISSUE TITLE
iOS14系统 TZAlbumPickerController 数组添加了空对象报错

### ISSUE THREAD

**Issue by Mamakou** [banchichen/TZImagePickerController#1641]
出现两次这种报错，场景是一样的：
在WillResignActive 的时候，TZAlbumPickerController 执行了一段NSMutableArray add的代码，然后 bugly这里显示为添加了一个null对象，导致报错。
iPad Pro (11-inch) (3rd generation) 14.6的系统
iPhone 12 Pro Max 14.4的系统

TZImagePickerController的版本为 3.7.2。

**Comment by Mamakou** [comment]
Installing TZImagePickerController 3.8.3 (was 3.7.2),我指定安装为3.8.3了，但是显示仍然为3.7.2。

**Comment by banchichen** [comment]
@Mamakou 
Q：pod search TZImagePickerController 搜索出来的不是最新版本
A：需要在终端执行cd转换文件路径命令退回到Desktop，然后执行pod setup命令更新本地spec缓存（可能需要几分钟）,然后再搜索就可以了

**Comment by Mamakou** [comment]
已经升级到3.8.3了，过段时间看看 有没有问题上报吧，感谢解答！
