### ISSUE TITLE
图片较多时，点击完成获取特别慢

### ISSUE THREAD

**Issue by taotao2015** [banchichen/TZImagePickerController#1642]
当选择图片较多，譬如1000张，点击完成加载时间比较长，以iphone6s为例，大概120s以上才能完全获取图片 。如果是2000张图片，时间可能有500s以上。

**Comment by banchichen** [comment]
可以设置onlyReturnAsset为true，这样TZ内部不会去取大图，会立刻调用回调，你从回调里拿到assets数组后，再根据你们的业务场景，决定如何处理，静默获取、分批获取、降低获取的清晰度等等，来减少用户体感上的等待时间
