### ISSUE TITLE
TZPhotoPickerController 和 TZAlbumPickerController 的背景色希望可以暴露出来

### ISSUE THREAD

**Issue by uclort** [banchichen/TZImagePickerController#1644]
**问：你希望加什么新功能？**
答：希望暴漏这两个控制器的背景色设置

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

这两个控制器默认是白色，在相片选择页返回相册选择页的时候会看到白色的过渡，希望暴露这两个控制器的颜色，让色值可以统一

**Comment by banchichen** [comment]
可以去hook下他们的生命周期方法哈
