### ISSUE TITLE
TZImagePickerController 设置allowCrop 为true，设置cropRect 裁剪框范围会与实际裁剪框里的画面不一致

### ISSUE THREAD

**Issue by carry1024** [banchichen/TZImagePickerController#1645]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.3

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**bug内容描述**
TZImagePickerController 设置allowCrop 为true，设置cropRect 裁剪框范围会与实际裁剪框里的画面不一致，你选择一个相册进行裁剪，可能瞄准的是头部，但是裁剪的可能是颈部，没有对好rect，比如我设置
picker.cropRect = CGRect(x: 0, y: UIScreen.height/2 - UIScreen.width * 0.552, width: UIScreen.width, height: UIScreen.width * 0.552) 这样设置的时候，就会出现这个bug

**Comment by banchichen** [comment]
欢迎PR哈

**Comment by banchichen** [comment]
我试了下，确实复现了。不过你这个用法比较奇怪，为什么裁剪框不设置垂直居中呢？改为这样，让框居中，会是好的：
CGRect(x: 0, y: UIScreen.height/2 - UIScreen.width * 0.552 * 0.5, width: UIScreen.width, height: UIScreen.width * 0.552)
