### ISSUE TITLE
属性allowPickingGif无效，gif图片都能展示并选择

### ISSUE THREAD

**Issue by luo71418578** [banchichen/TZImagePickerController#1646]
applinks:leader.tailgvip.com

**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？

答：最新3.83版本；最新版仍有此问题

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有改

**bug内容描述**
设置是否可选gif图属性allowPickingGif无效，gif图片都会显示，让然会走imagePickerController:(TZImagePickerController *)picker didFinishPickingGifImage:(UIImage *)animatedImage sourceAssets:(PHAsset *)asset这个方法。

**我如何复现这个bug？**
首页“允许选择GIF图片”切换按钮，无论是否打开，点击下方选择图片按钮，跳出图片列表页里面都会有gif图，并且可以查看，或者选中，点击完成后，gif图也能加入到首页的选择列表中。

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
收到，这里的注释确实有点迷惑，已完善：
```objective-c
/// Default is NO, if set YES, user can picking gif image. When NO, gif will be treated as a regular image. If want not displayed, please refer to isAssetCanBeDisplayed
/// 默认为NO，如果设置为YES，用户可以选择gif图片。为NO时gif会被当成普通图片，若要不显示，请参考isAssetCanBeDisplayed
@property (nonatomic, assign) BOOL allowPickingGif;
```
