### ISSUE TITLE
多语设置问题

### ISSUE THREAD

**Issue by MeteoriteMan** [banchichen/TZImagePickerController#1651]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.3

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

**bug内容描述**
使用TZImagePickerConfig中的preferredLanguage指定多语文件,languageBundle指定bundle部分语言生效部分不生效.
因为TZImagePickerConfig匿名分类中定义的supportedLanguages属性是私有的,在外部不太方便修改(目前可以使用kvc去设置,期望把supportedLanguages属性放在TZImagePickerConfig.h里面)
```
config.supportedLanguages = [NSSet setWithObjects:@"zh-Hans", @"zh-Hant", @"en", @"ar", @"de", @"es", @"fr", @"ja", @"ko-KP", @"pt", @"ru", @"vi", nil];
```

**我如何复现这个bug？**

**截图**
<img width="1080" alt="image" src="https://github.com/banchichen/TZImagePickerController/assets/24759559/fdf91b3b-67cf-41f6-89f5-61e0297e4e3f">

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
可以参考下demo，直接设置languageBundle，应该可以解决你的问题。如果不行的话，也欢迎PR哈
