### ISSUE TITLE
使用缩略图进行裁剪，导致获取的裁剪后图片清晰度过低

### ISSUE THREAD

**Issue by Fairy-happy** [banchichen/TZImagePickerController#1652]
https://github.com/banchichen/TZImagePickerController/blob/5d4d6352d8db218e77644b8e59d48d2e088cabfa/TZImagePickerController/TZImagePickerController/TZPhotoPreviewCell.m#L226

**Comment by banchichen** [comment]
老哥，欢迎PR哈

**Comment by banchichen** [comment]
已发布新版本3.8.4，清晰度会提高，若需要也可以设置得更高，详见：
https://github.com/banchichen/TZImagePickerController/pull/1654
