### ISSUE TITLE
二次打开相册，已经选择过的照片，不能被取消选择

### ISSUE THREAD

**Issue by 173323222** [banchichen/TZImagePickerController#1659]
**问：你希望加什么新功能？**
答：二次打开相册，已经选择过的照片，不能被取消选择

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：咩有

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：需要加个属性开关

**其它你希望补充的内容**
比如选择的照片完成，然后照片上传到某一个地方，或者去检测是不是人像等等，再次打开之前已经选择的照片不期望能被重复选择

**Comment by banchichen** [comment]
默认选中有selectedAssets
不显示的话有isAssetCanBeDisplayed
不可被选中的话有isAssetCanBeSelected

不可被取消选中，目前倒没有这种API，需要的话，你可以参考isAssetCanBeSelected的逻辑，加个isAssetCanNotBeDeselected的代理方法，然后提个PR过来哈
