### ISSUE TITLE
图片加载缓慢

### ISSUE THREAD

**Issue by LongKangYao** [banchichen/TZImagePickerController#166]
你好，不好意思，我重新审查了一下，加载的图片是20000张。从外边按钮点击跳转到图库的时候，整个跳转present时间漫长，需要等待很长时间才能present出来。

**Comment by banchichen** [comment]
你好，请问这个时候微信、QQ的选择器表现怎么样？他们的等待时间比起我的有大幅降低对吗？

**Comment by banchichen** [comment]
我这里的图片只有1000张....  打开还算很快...  有20000张照片的设备的不好找....

**Comment by LongKangYao** [comment]
你好，微信和QQ的做法是点击的时候直接跳到图库，然后再选择加载。等待时间是TZImage的1/3。我用Time Profile分析了一下，在present出来选择器的时候：在viewdidload里获取照片，创建model花费了大量的时间，如果图库少的话是没问题的，图库大时间就都累计起来了。所以我建议放到viewdidappear里面，不知道你有没有更好的办法 ？

**Comment by banchichen** [comment]
建议你先试试把获取model的方法放在子线程~？  如果表现也不是很好的话，放到viewdidappear是比较合适的选择~

**Comment by banchichen** [comment]
优化好了顺便提个PR呗~     那进入微信和QQ的选择器的话，是不是刚进入选择器页面时，图片还没显示出来~？

**Comment by LongKangYao** [comment]
嗯，我目前是把获取model的方法放到子线程，获取结束后在主线程刷新UI。不过目前还是有些问题待优化，优化好的时候我提个PR，你看下。微信和QQ是进去之后，20000张，先是空白，然后大概1秒就加载出来了。

**Comment by banchichen** [comment]
刚刚提交了代码，对这里做了类似微信的处理~
获取照片数组的代码放到后台线程去执行~
