### ISSUE TITLE
新增一个属性控制相册选择时的CollectionView当前是滚动到最顶部还是最底部。

### ISSUE THREAD

**Issue by lxm1799** [banchichen/TZImagePickerController#1660]
**问：你希望加什么新功能？**
答：新增一个属性控制相册选择时的CollectionView当前是滚动到最顶部还是最底部。

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是

**其它你希望补充的内容**

**Comment by banchichen** [comment]
默认是滚动到最新的照片所在位置
没必要选时顶部还是底部

如果最新照片在顶部，开发者设置滚动到底部，给用户先看最旧的照片？

**Comment by bolee** [comment]
> 默认是滚动到最新的照片所在位置 没必要选时顶部还是底部
> 
> 如果最新照片在顶部，开发者设置滚动到底部，给用户先看最旧的照片？

好像并不是固定显示到最新照片的，有时候是显示在顶部，不是最新的，照片多的话就只能滑动到底部
