### ISSUE TITLE
能否添加只显示圆形裁剪框，但实际还是按方形裁剪图片的一个属性

### ISSUE THREAD

**Issue by dongyandan** [banchichen/TZImagePickerController#1664]
**问：你希望加什么新功能？**
答：增加一个属性，只显示圆形裁剪框，但实际仍然按方形裁剪图片

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：

**其它你希望补充的内容**

**Comment by banchichen** [comment]
没有计划，欢迎PR哈
