### ISSUE TITLE
点击添加更多可访问的照片后 怎么不要显示视频呢？

### ISSUE THREAD

**Issue by twlk-jzy** [banchichen/TZImagePickerController#1665]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

**bug内容描述**
点击添加更多可访问的照片后 显示了视频

**我如何复现这个bug？**

    imagePickerVc.allowPickingVideo = NO;
    imagePickerVc.allowTakeVideo = NO;
    imagePickerVc.allowTakePicture = NO;
    imagePickerVc.allowPickingMultipleVideo = NO;
    imagePickerVc.allowPickingGif = NO;
    imagePickerVc.allowPickingOriginalPhoto = NO;
**截图**
![image](https://github.com/banchichen/TZImagePickerController/assets/8147530/4a5e2c12-ce80-4d72-88a3-0214c6a3a007)
**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
无

**Comment by banchichen** [comment]
这个是调的系统的：
[[PHPhotoLibrary sharedPhotoLibrary] presentLimitedLibraryPickerFromViewController:self]
没有控制参数，应该做不到的
