### ISSUE TITLE
选择图片的时候，点击预览大图，显示原图的问题

### ISSUE THREAD

**Issue by Regansun** [banchichen/TZImagePickerController#167]
选择图片的时候，点击预览大图，当本地原图没有被下载完全的时候，显示原图需要一段时间，起初图片比较模糊，一段时间后，原图完全显示了以后，图片会变形（主要是图片的高度不对了），需回退到前一个界面，再次进入就显示正常了（不知道描述的够不够清楚）

**Comment by banchichen** [comment]
你好，麻烦下载最新的代码再试试，pod的最新版本有这个问题，最新的代码中这里应该是好的~   麻烦测试后再给个反馈哈谢谢~
