### ISSUE TITLE
v3.8.4已选图片在相册中回显序号不对

### ISSUE THREAD

**Issue by OYForever** [banchichen/TZImagePickerController#1671]
> 已发布新版本，3.8.4
这里刷新selectedModels 会导致selectedModels顺序变化，外部点进去回显图片选择顺序不对了，需要修正selectedModels顺序

https://github.com/banchichen/TZImagePickerController/assets/20378951/fcf3cd14-fb49-4a15-92c3-55dd3e5d34b0

_Originally posted by @OYForever in https://github.com/banchichen/TZImagePickerController/issues/1658#issuecomment-1966090091_

**Comment by OYForever** [comment]
具体问题在这https://github.com/banchichen/TZImagePickerController/pull/1658/commits/66c986adfcda8d29776d1048e0e2c05cac121d1d#r1524498545

**Comment by banchichen** [comment]
是为了修复 https://github.com/banchichen/TZImagePickerController/issues/1656 引起

目前序号错乱问题已经修复，1656 issue使用了新方案实现：https://github.com/banchichen/TZImagePickerController/commit/2a4caa806c4f9356df1bdc8233b42350bb41c652#diff-e0526319e03bba22c65b63d870193b138512ff0ac9047d894e1602ad957e4f47R1136

已发布了新版本3.8.7
