### ISSUE TITLE
添加苹果的隐私清单文件

### ISSUE THREAD

**Issue by lxm1799** [banchichen/TZImagePickerController#1672]
**问：你希望加什么新功能？**
答：添加苹果的隐私清单文件。
苹果官方文档：https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：无

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：是

**其它你希望补充的内容**
目前苹果在2024/5/1强制执行新政策，我看了下项目中应该仅需要添加“File timestamp ”即可。

**Comment by lxm1799** [comment]
![image](https://github.com/banchichen/TZImagePickerController/assets/30572071/77836729-6d88-4003-9feb-855c0e209ed7)
本来想pull request的，但在公司的电脑忘记了github的密钥...

**Comment by Rxx9723** [comment]
请问一下最新版本3.8.4是否添加苹果的隐私清单文件呢哈

**Comment by banchichen** [comment]
欢迎PR哈，最晚四月初我处理下发个版本

**Comment by banchichen** [comment]
感谢PR，已合并：https://github.com/banchichen/TZImagePickerController/pull/1675 
已发布3.8.5版本，可以试试哈
