### ISSUE TITLE
初始化里push到TZPhotoPickerController未生效

### ISSUE THREAD

**Issue by Kasign** [banchichen/TZImagePickerController#1673]
![image](https://github.com/banchichen/TZImagePickerController/assets/16473249/9e293316-395b-4655-9c07-e330de773453)

这里改成这样效果大不同
```objectivec
[[TZImageManager manager] getCameraRollAlbumWithFetchAssets:NO completion:^(TZAlbumModel *model) {
            photoPickerVc.model = model;
            dispatch_async(dispatch_get_main_queue(), ^{
                [self pushViewController:photoPickerVc animated:YES];
            });
            self->_didPushPhotoPickerVc = YES;
        }];
```
        
 如已修改请忽略 master貌似没有改

**Comment by banchichen** [comment]
我在demo试了就在主线程呢：
<img width="682" alt="image" src="https://github.com/banchichen/TZImagePickerController/assets/12755494/af77f339-c458-4624-802a-dc07c90af691">
