### ISSUE TITLE
图片裁剪的是实际图片的区域，还是屏幕上展示的区域？

### ISSUE THREAD

**Issue by CoderLGL** [banchichen/TZImagePickerController#1677]
图片裁剪好像只是对屏幕进行了裁剪，而非是裁剪实际的图片
能等比例对图片进行裁剪吗？不然只是裁剪屏幕会很模糊

**Comment by banchichen** [comment]
关于图片清晰度的问题，可以参考这里的评论：https://github.com/banchichen/TZImagePickerController/pull/1654
