### ISSUE TITLE
iPhoneX机型上选择一张图片时，底部最后一行两边的图片会被剪去一部分，希望图片仅展示到安全区域以上

### ISSUE THREAD

**Issue by WangCL-GitHub** [banchichen/TZImagePickerController#1679]
iPhoneX机型上选择一张图片时，底部最后一行两边的图片会被剪去一部分，希望图片仅展示到安全区域以上

**Comment by WangCL-GitHub** [comment]
![Uploading 截屏2024-05-20 14.34.41.png…]()

**Comment by WangCL-GitHub** [comment]
<img width="352" alt="截屏2024-05-20 14 34 41" src="https://github.com/banchichen/TZImagePickerController/assets/49604922/aa529aaf-0536-4711-833a-6092cdcac313">

**Comment by banchichen** [comment]
我这看demo是好的，你是不是要升级下版本：
<img width="264" alt="image" src="https://github.com/banchichen/TZImagePickerController/assets/12755494/a1599f91-b240-46a4-83f4-bf24b5338292">
