### ISSUE TITLE
作者您好,不支持iOS7

### ISSUE THREAD

**Issue by liberalisman** [banchichen/TZImagePickerController#168]
为什么在我的项目里报出TZImagePicker只支持iOS8及以上
我看介绍是iOS6以后都支持吧....
![attachmentimage](https://cloud.githubusercontent.com/assets/12613099/17693277/9f3711f6-63d0-11e6-8ddd-2fe1566422b0.png)

**Comment by liberalisman** [comment]
希望您能抽空帮我看一下.

**Comment by banchichen** [comment]
你好，其他人都没有出现这个问题噢，建议你先不用pod，直接下载代码过去使用~  我先分析一下~

**Comment by banchichen** [comment]
可以检查一下项目的podfile文件，是不是写了 platform:ios,"8.0"

**Comment by liberalisman** [comment]
问题已经解决，原因在于pod install之后，我自己手动导入了.framework，删掉就好了。

但是目前在模拟器上却无法运行，不知道为什么。。。。。

**Comment by banchichen** [comment]
那应该也还是pod的问题吧....
