### ISSUE TITLE
视频导出失败

### ISSUE THREAD

**Issue by xiaochengmomo** [banchichen/TZImagePickerController#1680]
**提bug前必看**请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是最新版本
2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本
3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：视频导出失败：视频导出失败，error:Error Domain=AVFoundationErrorDomain Code=-11800 "操作无法完成" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12551), NSLocalizedDescription=The operation couldnt be completed, NSUnderlyingError=0x2802041e0 {Error Domain=NSOSStatusErrorDomain Code=-12551 "(null)"}
从本地相册选取视频提示导出相册视频导出失败从本地相册选取视频提示导出相册视频导出失败
**我如何复现这个bug？**
抖音里随便下载一个大视频保存到本地200兆左右的都会失败 最新demo里也导出失败并闪退
**截图****其他说明**有没有其他要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
抖音里许多视频都不让保存到相册，我自己拍的，1个G的视频是可以导出成功的     

你把这个导出失败的，建一个共享相册吧，然后邀请我 736420282@qq.com
