### ISSUE TITLE
s.ios.deployment_target 版本问题

### ISSUE THREAD

**Issue by Dcell** [banchichen/TZImagePickerController#1681]
**咨询前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：没问题

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.5

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

最新3.8.5 ios.deployment_target 版本忽然升级到 12.
能否支持10版本

**Comment by banchichen** [comment]
好了，3.8.6支持iOS10了
