### ISSUE TITLE
您好，使用TZImagePickerController时，点击相册照片无法查看大图。只能点击右上角的圆圈选择。

### ISSUE THREAD

**Issue by LinkerM** [banchichen/TZImagePickerController#1682]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：没有的

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版本

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有改动

**bug内容描述**
您好，使用TZImagePickerController时，点击相册照片无法查看大图。只能点击右上角的圆圈选择。
点击每个itme,跳转不到图片浏览页
**我如何复现这个bug？**

**截图**

https://github.com/banchichen/TZImagePickerController/assets/33533167/b9cd5ad1-f091-486a-8870-04e56eb07388

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by LinkerM** [comment]
初始化代码
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:1 columnNumber:3 delegate:self pushPhotoPickerVc:YES];
        // 是否允许显示视频
    imagePickerVc.allowPickingVideo = YES;
    // 是否允许显示图片
    imagePickerVc.allowPickingImage = NO;
//    imagePickerVc.allowEditVideo = YES; // 允许编辑视频
    imagePickerVc.modalPresentationStyle = UIModalPresentationFullScreen;
    [self presentViewController:imagePickerVc animated:YES completion:nil];

**Comment by banchichen** [comment]
demo正常的话，对比下demo哈....
也可以debug下TZPhotoPickerController的didSelectItemAtIndexPath，看看为什么没去预览

**Comment by LinkerM** [comment]
项目浏览页面中当点击具体item的时候didSelectItemAtIndexPath方法没有走。
