### ISSUE TITLE
iOS18 beta:在使用当前master版本在Xcode16 beta，iOS18.0系统下运行时，打开图片选择时，选择完全允许后，界面里没有图片显示。debug命令行里显示： Unsupported fetch for asset collections with type 2 and subtype 2 

### ISSUE THREAD

**Issue by shiRocket** [banchichen/TZImagePickerController#1685]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：使用master分支下的代码运行还是有这个问题

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

**bug内容描述**

**我如何复现这个bug？**
使用Xcode16 beta，iOS18.0模拟器下运行

**截图**
![Simulator Screenshot - iPhone 15 Pro - 2024-06-24 at 14 10 50](https://github.com/banchichen/TZImagePickerController/assets/1744601/3a963779-3f3a-4cce-a3e0-7f5ff78b1057)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
感谢反馈，已经修复了。把PHAssetCollectionSubtypeAlbumRegular换成PHAssetCollectionSubtypeAny后可以了

已经发布3.8.6版本

**Comment by mzm008** [comment]
sure to reshow this problem. 
thanks
