### ISSUE TITLE
-[PHPhotoLibrary presentLimitedLibraryPickerFromViewController:]: unrecognized selector sent to instance 0x12462b040

### ISSUE THREAD

**Issue by YanBoCode** [banchichen/TZImagePickerController#1688]
-[PHPhotoLibrary presentLimitedLibraryPickerFromViewController:]: unrecognized selector sent to instance 0x12462b040
直接闪退了，点击添加更多图片

**Comment by banchichen** [comment]
哥，你没填issue的模板内容
试试demo
