### ISSUE TITLE
类似微信，标题可以选择不同的相册夹，而不是点击返回才能选择文件夹

### ISSUE THREAD

**Issue by YanBoCode** [banchichen/TZImagePickerController#1689]
**问：你希望加什么新功能？**
答：类似微信，标题可以选择不同的相册夹，而不是点击返回才能选择文件夹

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：是的

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答：适合所有人

**其它你希望补充的内容**

**Comment by banchichen** [comment]
欢迎PR哈
