### ISSUE TITLE
先选择几张图片，然后再选择图片前面图片的位置会改变，这个怎么解决？

### ISSUE THREAD

**Issue by gisxie** [banchichen/TZImagePickerController#1690]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.6

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：没有

**bug内容描述**
先选择几张图片，然后再选择图片前面图片的位置会改变

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
是为了修复 https://github.com/banchichen/TZImagePickerController/issues/1656 引起

目前序号错乱问题已经修复，1656 issue使用了新方案实现：https://github.com/banchichen/TZImagePickerController/commit/2a4caa806c4f9356df1bdc8233b42350bb41c652#diff-e0526319e03bba22c65b63d870193b138512ff0ac9047d894e1602ad957e4f47R1136

已发布了新版本3.8.7
