### ISSUE TITLE
希望能添加下照片滑动多选功能

### ISSUE THREAD

**Issue by huangfangkai** [banchichen/TZImagePickerController#1691]
**问：你希望加什么新功能？**
答：添加下照片滑动多选功能

**问：微信、QQ等大APP的选择器，是否有这个功能？**
答：网盘或者在线相册功能需要

**问：这个功能是否适合所有人？如不是，是否要加个属性开关？**
答加个属性开关

**其它你希望补充的内容**

**Comment by banchichen** [comment]
欢迎PR哈
