### ISSUE TITLE
选择本地视频，然后点击编辑，点击完成，导出来的清晰度非常低，设置这个属性也是一样的AVAssetExportPresetHighestQuality

### ISSUE THREAD

**Issue by YanBoCode** [banchichen/TZImagePickerController#1692]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答： 16.7.2， iPhone 8p

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答： 没有

**bug内容描述**
选择本地视频，然后点击编辑，点击完成，导出来的清晰度非常低，设置这个属性也是一样的AVAssetExportPresetHighestQuality

**我如何复现这个bug？**

选择本地视频，然后点击编辑，点击完成，导出来的清晰度非常低，设置这个属性也是一样的AVAssetExportPresetHighestQuality
**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
做该库视频编辑功能的开发转行了。。。欢迎PR哈

**Comment by banchichen** [comment]
不过看TZVideoCropController里的doneButtonClick代码，是有用到imagePickerVc.presetName配置的，建议：
1、可以找个该手机拍摄的清晰的视频试试
2、和不裁剪的导出视频对比下清晰度
好进一步确定问题
