### ISSUE TITLE
XCode16+iOS18 openUr失效

### ISSUE THREAD

**Issue by jaychen04** [banchichen/TZImagePickerController#1696]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有这个bug

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.6

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：否

**bug内容描述**
xcode16+iOS18，openurl已被废弃，无法跳转。之前仅提示废弃，现在该方法调用已无法跳转对应dest。

**我如何复现这个bug？**
未授权，选择跳转设置页，无法跳转

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码
使用系统建议的openurl方法即可。

**Comment by homeYsy** [comment]
+1

**Comment by banchichen** [comment]
不好意思，近期比较忙，处理晚了，已换成openURL:options:completionHandler:方法
已发布3.8.8
