### ISSUE TITLE
照片存储于iCloud时 下载失败

### ISSUE THREAD

**Issue by xmt0615** [banchichen/TZImagePickerController#17]
PHImageRequestOptions *option = [[PHImageRequestOptions alloc]init];
        option.networkAccessAllowed = YES;
        
        [[PHImageManager defaultManager] requestImageForAsset:asset targetSize:CGSizeMake(pixelWidth, pixelHeight) contentMode:PHImageContentModeAspectFit options:option resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info) {
            BOOL downloadFinined = (![[info objectForKey:PHImageCancelledKey] boolValue] && ![info objectForKey:PHImageErrorKey]);
            if (downloadFinined) {
                if (completion) completion(result,info,[[info objectForKey:PHImageResultIsDegradedKey] boolValue]);
            }
        }];
PHImageRequestOptions 设置为 允许网络图片下载 就可以了

**Comment by banchichen** [comment]
谢谢指出，已修改~
