### ISSUE TITLE
UIApplication openURL 用xcode16编译，在iOS18上失效，需要更新API

### ISSUE THREAD

**Issue by YGZhang** [banchichen/TZImagePickerController#1700]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：有

2、你用的是什么版本？升级到最新版后是否正常？
答：3.8.7

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：无

**bug内容描述**
[[UIApplication sharedApplication] openURL:[NSURL URLWithString:url]];用xcode16编译，在iOS18上这个API失效，需要更新成[[UIApplication sharedApplication] openURL:settingsURL options:@{} completionHandler:nil];

**我如何复现这个bug？**
关闭相册和相机权限，跳转到设置无法跳转

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by iCodey** [comment]
遇到同样的问题，按照楼上的方法解决了。



希望可以更新下仓库

**Comment by xiaomiyang** [comment]
+1

**Comment by SeriusXiang** [comment]
openURL:方法在iOS18已经完全弃用。必须使用新的API：openURL:options:completionHandler:];

**Comment by homeYsy** [comment]
+1

**Comment by banchichen** [comment]
不好意思，近期比较忙，处理晚了，已换成openURL:options:completionHandler:方法
已发布3.8.8
