### ISSUE TITLE
iOS 18系统打开相册是空白

### ISSUE THREAD

**Issue by unti1you** [banchichen/TZImagePickerController#1703]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：

2、你用的是什么版本？升级到最新版后是否正常？
答：

3、是否有改动过我库内部的代码？【**如有，请说明改动点**】
答：

**bug内容描述**

**我如何复现这个bug？**

**截图**

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by JunkyTang** [comment]
我也遇到了同样问题，获取到的相册很少很少
iOS 18

**Comment by JunkyTang** [comment]
更新3.8.8就好了
