### ISSUE TITLE
 有内存泄漏啊，求解决

### ISSUE THREAD

**Issue by GreatLiyi** [banchichen/TZImagePickerController#171]
这问题很严重啊，严重影响了app的流畅性，求解决

**Comment by banchichen** [comment]
你好，当进入照片预览页面后，如不返回上一个页面，而是直接点击确定dismiss掉的话，此时的内存释放会延后10s左右，而不会立即释放... 通过Leaks分析没提示说有泄露... 我试着优化一下，看怎样让内存尽快释放掉~        dealloc方法调用时机是由系统决定的，只有在dealloc调用时才回收内存，因此如果按照前面的操作方式，内存不会得到立刻释放，我试着强行让系统去调用dealloc，发现即使控制器dealloc了，内存还是要等10秒左右才会释放掉。你可以观察一下~

**Comment by GreatLiyi** [comment]
选完图片，然后点击确定，利用MLeaksFinder检测出内存泄漏，不用进入照片预览页面
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Possibly Memory Leak.
In case that TZImagePickerController should not be dealloced, override -willDealloc in TZImagePickerController by returning NO.
View-ViewController stack: (
    TZImagePickerController
)

**Comment by banchichen** [comment]
你好，MLeaksFinder库对于present出来的控制器，一定会报内存泄露的，是这个库的一个已知bug，参考链接： https://github.com/Zepo/MLeaksFinder/issues/27 。调试的时候也可以参考Xcode给出的内存运行情况数据，内存不会立即回收，但会在未来8-12秒的样子回收...

**Comment by longhongwei17** [comment]
确实 内存不是马上回收   MLeaksFinder 好像是3秒内部回收 就会弹框提示。开始我也以为是内存泄露了，一直不会跑dealloc
