### ISSUE TITLE
swift不能使用TZImageManager.manager()

### ISSUE THREAD

**Issue by Lafree317** [banchichen/TZImagePickerController#173]
如图...:
![2016-08-19 11 44 37](https://cloud.githubusercontent.com/assets/13520567/17798332/fbbba66a-6602-11e6-90c3-0cfbf548b325.png)
OC可以用...:
![2016-08-19 11 49 47](https://cloud.githubusercontent.com/assets/13520567/17798352/1ae703a4-6603-11e6-8414-cda525fbd5b1.png)
求解...谢谢

**Comment by banchichen** [comment]
我对swift不是很熟...不太清楚...

**Comment by Lafree317** [comment]
嗯...swift的语法,自动识别了你的manager单例方法,直接使用TZImageManager()就可以了,为你的语法规范赞一个~

**Comment by banchichen** [comment]
解决了就好~~
