### ISSUE TITLE
作者您好，预览图片之后，再返回选择图片的控制器，此时状态栏会消失

### ISSUE THREAD

**Issue by liberalisman** [banchichen/TZImagePickerController#174]
就是最上面高度20的statusBar，消失了。

而导航顺势上移了20的高度

**Comment by banchichen** [comment]
我这里iOS789的设备都没有这个问题噢...你可以比较下Demo的效果和你项目的效果...    注意下Demo中关于状态栏的设置View controller-based status bar appearance是为NO的，如果你项目中设置为YES的话，可能会导致这个问题，因为去预览控制器，有对状态栏进行了隐藏，之后再打开。

**Comment by banchichen** [comment]
如果还是一直有问题的话，建议你注释一下预览控制器中隐藏和显示状态栏的代码，如果不操作状态栏，是不会发生上面的情况的。只是这样的话预览的体验稍差一些。

**Comment by liberalisman** [comment]
作者您好,过来一看issue已经关闭.

不过您考虑的思路是对的,

这个问题已经解决了

**Comment by banchichen** [comment]
好的~解决了就好~
