### ISSUE TITLE
ios8上下方toolbar显示异常，取消按钮不见了，确定按钮不显示。

### ISSUE THREAD

**Issue by guoweikun621** [banchichen/TZImagePickerController#175]

**Comment by banchichen** [comment]
不会的吧....如果你那里使用的版本比较老的话，建议你更换下新版试试...

**Comment by banchichen** [comment]
1. 目前最新版本是1.6.1，你检查一下你本地是不是最新的版本哈。
2. 如果发现pod search TZImagePickerController 搜索出来的不是最新版本，需要在终端执行cd转换文件路径命令退回到Desktop，然后执行pod setup命令更新本地spec缓存（可能需要几分钟）,然后再搜索就可以了.

你这个问题应该是资源文件找不到导致的，我在我的两个项目中都把TZImagePickerController更新到了1.6.1版本，没有发现你这个问题....   

如果来不及解决，需要尽快加入照片选择功能的话，可以不适用pod，直接把文件导入过去，就不会有这个问题的。

**Comment by guoweikun621** [comment]
我用的1.6的不行。退回到1.5就好了
