### ISSUE TITLE
照片上限设置为9，选了9张图后，再进行照相机拍照，会出现10张图

### ISSUE THREAD

**Issue by Yoncn** [banchichen/TZImagePickerController#176]
同理 上限设置为N，通过相册选择选了N张图后，再点+号选择相机拍照，拍完collectionview会出现N+1张图，超过上限，逻辑有疏漏。

**Comment by banchichen** [comment]
你好，我刚刚又试了下，如果超过了上限，新拍的图不会是自动选中状态的。拍是可以一直拍的。

**Comment by tianglin** [comment]
我自己在拍照前判断已选的图片数量，如果等于N就提示用户达到上限，不拍照了。

**Comment by banchichen** [comment]
好吧~
