### ISSUE TITLE
cocopods 上面为什么只能搜索到1.30版本  求告知！！

### ISSUE THREAD

**Issue by Gordon2780** [banchichen/TZImagePickerController#177]
![1b79d86b-58c5-4f4d-9c3f-aadbe520ef60](https://cloud.githubusercontent.com/assets/17872771/17879704/ac34f00c-6926-11e6-8c1a-41d314c730aa.png)

**Comment by banchichen** [comment]
你好，在终端 pod setup 一下

**Comment by Gordon2780** [comment]
大兄弟  这个无法访问git的报错是因为我用了蓝灯吗  完全不行啊 怎么办呢
![4e939657-d7f2-4ba4-8aaa-7667df80effe](https://cloud.githubusercontent.com/assets/17872771/17882255/e8954cec-693d-11e6-9788-f6287673e969.png)

**Comment by Gordon2780** [comment]
还有你这个demo  在选择照片的时候  会有一个等待的时间  但是微信的没有  这个是自己手动设置的吗
![2150c785cb969524c1a3967f5c9ea3be](https://cloud.githubusercontent.com/assets/17872771/17882316/57cf6570-693e-11e6-9505-e63ded454d7f.jpg)

**Comment by banchichen** [comment]
提示说请求超时了..多试几次吧...

**Comment by banchichen** [comment]
微信的也有的，只是如果图片比较小，会很快就获取结束了，导致没注意到....
