### ISSUE TITLE
发现的的几处问题

### ISSUE THREAD

**Issue by chinelee** [banchichen/TZImagePickerController#178]
1.选择的图片数量大于设置的数量时
TZPhotoPickerController.m文件中，365行出现问题
` NSString *title = [NSString stringWithFormat:[NSBundle tz_localizedStringForKey:@"Select a maximum of %zd photos"], tzImagePickerVc.maxImagesCount];
`
2.我的手机时iOS9.3.4系统，选择图片时，底部没有完成，预览，原图等文字，只有按钮
我是使用的这三句
`TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:9 delegate:self];
    [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photots, NSArray *assets, BOOL isSelectOriginalPhoto) {
        NSLog(@"photos :%@",photots);
    }];
    [self presentViewController:imagePickerVc animated:YES completion:nil];`

3.我 pod search出来的是 1.6.0版本，没有1.6.1

**Comment by chinelee** [comment]
知道问题在哪里了，不能加载资源文件，所以崩溃。不使用cocopod之后，直接手动拖入文件，会好了

**Comment by banchichen** [comment]
3. 如果发现pod search TZImagePickerController 搜索出来的不是最新版本，需要在终端执行cd转换文件路径命令退回到Desktop，然后执行pod setup命令更新本地spec缓存（可能需要几分钟）,然后再搜索就可以了.

为什么会不能加载资源文件呢...

**Comment by chinelee** [comment]
已经可以更新到最新的了。等会再试试能不能加载本地化语言文件。使用cocopod之后便不能更改按钮图片了，还是手动拖入吧。😂

**Comment by chinelee** [comment]
TZImagePickerController very good！

**Comment by banchichen** [comment]
@property (nonatomic, copy) NSString *takePictureImageName;
@property (nonatomic, copy) NSString *photoSelImageName;
@property (nonatomic, copy) NSString *photoDefImageName;
@property (nonatomic, copy) NSString *photoOriginSelImageName;
@property (nonatomic, copy) NSString *photoOriginDefImageName;
@property (nonatomic, copy) NSString *photoPreviewOriginDefImageName;
@property (nonatomic, copy) NSString *photoNumberIconImageName;
你看看最新的头文件~ 已经可以在外面给图片名字了噢~

**Comment by chinelee** [comment]
👌！！！

**Comment by lx-xi** [comment]
TZImagePickerController类154行tz_localizedStringForKey取值为空，导致如果未开通相册权限时程序崩溃

**Comment by banchichen** [comment]
@lx-xi 你好，可以麻烦提供一个复现的Demo吗，我来看看...
