### ISSUE TITLE
TZImageManager 的单例方法中调用iOS9的API没有条件过滤

### ISSUE THREAD

**Issue by siriusW** [banchichen/TZImagePickerController#179]
+ (instancetype)manager {
    static TZImageManager *manager;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        manager = [[self alloc] init];
        manager.cachingImageManager = [[PHCachingImageManager alloc] init];
        if (iOS9Later) { //   这里没有过滤
            manager.cachingImageManager.allowsCachingHighQualityImages = NO;
        }
        
        TZScreenWidth = [UIScreen mainScreen].bounds.size.width;
        // 测试发现，如果scale在plus真机上取到3.0，内存会增大特别多。故这里写死成2.0
        TZScreenScale = 2.0;
        if (TZScreenWidth > 700) {
            TZScreenScale = 1.5;
        }
        CGFloat margin = 4;
        CGFloat itemWH = (TZScreenWidth - 2 * margin - 4) / 4 - margin;
        AssetGridThumbnailSize = CGSizeMake(itemWH * TZScreenScale, itemWH * TZScreenScale);
    });
    return manager;
}

**Comment by banchichen** [comment]
好吧...   已修复，对了，是iOS8的吧...     manager.cachingImageManager.allowsCachingHighQualityImages = NO; 这句代码是已经注释了的
