### ISSUE TITLE
获取gif图片时的问题

### ISSUE THREAD

**Issue by songhailiang** [banchichen/TZImagePickerController#180]
TZImageManager里的获取原图方法，是不是应该返回NSData更好？因为如果是gif图片，返回UIImage后，就不是gif图片了

**Comment by banchichen** [comment]
啊哈，那把NSData数据也返回回去吧~

**Comment by songhailiang** [comment]
如果UIImage和NSData都返回，会不会内存占用就高了？因为需要用NSData去初始化UIImage。

**Comment by banchichen** [comment]
理论上会升高一些的，最多几M吧~   也可以再写一个只返回NSData的方法~

**Comment by Yulei-Duan** [comment]
如何获取 gif的NSdata ? 我没找到很好的方式 把UIIMAGE 转成  NSdata

**Comment by banchichen** [comment]
@Yulei-Duan 如果拿得到asset对象的话，可以用TZImageManager的getOriginalPhotoDataWithAsset方法获取NSData

**Comment by Yulei-Duan** [comment]
嗯 解决这个问题了谢谢！
