### ISSUE TITLE
Swift 下TZImageManager 的 manager 静态方法被和谐了

### ISSUE THREAD

**Issue by sheodon** [banchichen/TZImagePickerController#181]
OC类静态方法manager() 无法编译到 Swift 里面

**Comment by banchichen** [comment]
恩，直接使用TZImageManager()就可以了...

**Comment by banchichen** [comment]
恩，直接使用TZImageManager()就可以了...

**Comment by banchichen** [comment]
恩，直接使用TZImageManager()就可以了...

**Comment by banchichen** [comment]
恩，直接使用TZImageManager()就可以了...

**Comment by banchichen** [comment]
恩，直接使用TZImageManager()就可以了...
