### ISSUE TITLE
求解...

### ISSUE THREAD

**Issue by chinelee** [banchichen/TZImagePickerController#182]
为什么我选择了照片之后，再次点击添加按钮，进去相册界面，之前选择的照片并没有被勾选上！！就是每次点击添加按钮，都是重新添加照片，而不是在原来的基础上添加。。。。
是哪句代码控制者？

**Comment by banchichen** [comment]
/// 用户选中过的图片数组
@property (nonatomic, strong) NSMutableArray *selectedAssets;

 imagePickerVc.selectedAssets = _selectedAssets; 
你好，详见Demo185行
