### ISSUE TITLE
新手问个问题，还请大家帮忙解答一下

### ISSUE THREAD

**Issue by github410117** [banchichen/TZImagePickerController#183]
如果说在一个TableView上有多个cell需要使用到图片选择器，用博主这个库的话，选择后的图片该怎么保存呢？不可能都保存在同一数组，但是又该怎么区分呢，求大神指点！

**Comment by banchichen** [comment]
你好，可以根据indexPath.row或indexPath.section为key保存在一个字典里，通过indexPath.row在字典中存取当前indexPath.row所已选中的图片数组。 类似这样{@"1":@[img1,img2],@"2":@[img21,img22,img23]}

**Comment by github410117** [comment]
但是我看您的demo里，collection的item数量是用数组的count来获取的，但是如果按您这样存字典，indexpath在collectionView numberOfItemsInSection方法中是获取不到indexPath的，有什么办法解决吗？您可以留个联系方式吗？因为毕竟急，又不是很会，真心想要请教您一下！谢谢

**Comment by banchichen** [comment]
你问的是UITableVeiw，我这里用的是UICollectionView，自然不一样的，不过只是思路是一样的，用一个唯一的值作为key来标记唯一一个cell, 来和这多个已选图片数组对接起来...   抱歉，联系方式就不贴了，实在抽不出精力回答TZImagePickerController之外的问题....
