### ISSUE TITLE
拍照拿不到正确的图片

### ISSUE THREAD

**Issue by JohnLif** [banchichen/TZImagePickerController#184]
当我拍照使用该图片后，好像把拍照前的最后一张图片复制了选中，只有dismiss controller后再进来才能看到刚刚拍照的图片.......我pod的是1.6.1的版本

**Comment by banchichen** [comment]
你好，请问你的手机系统版本是多少呢？每次都是这样吗？

**Comment by JohnLif** [comment]
并不是每次都这样，现在没出现刚刚的问题的。我的手机是iPod touch 9.2   谢谢！

**Comment by banchichen** [comment]
比较奇怪...  iOS9以上的话去保存图片是调用系统Photos库的API，保存图片成功后会给一个回调，回调来了后会去重新刷新数据，取最新的照片.....如果取到的是重复的，说明图片保存成功，但是相册数据并没有刷新...    不太好分析原因...  最直接的策略是等API回调回来后，再等0.5或者1秒钟后才去取图片....  再多给系统一点时间...就会取到最新的了...

**Comment by banchichen** [comment]
在iOS9以下时，保存图片走的AssetsLibrary的API，这里保存图片成功的回调block走了后，偶尔会出现相册数据还没刷新的情况。目前的处理方法在iOS9以下系统中，让保存图片成功的回调来了后，延迟0.5秒再刷新相册数据。这样处理后测试20多次没再出现这个问题....  最新版本目前是1.6.3版本
