### ISSUE TITLE
相册默认都是显示英语名，这是为什么？

### ISSUE THREAD

**Issue by maple1994** [banchichen/TZImagePickerController#185]
系统语言设置为中文后，相册名例如，相机胶卷还是显示camera roll，自拍还是显示Selfies。请问这个要自己处理吗？

**Comment by banchichen** [comment]
你好，1.6.1版本之前因为没有做国际化，我对相册名字做了特殊的显示处理。做了国家化之后，相册名字我直接取用的系统提供的相册名字。你可以运行下我的Demo比较，Demo中我这里是相册名显示中文的。可以设置把info.plist的Localization native development region属性，设置为China选项，再加上系统语言为中文，应该就会显示中文了。

**Comment by maple1994** [comment]
好的，已经解决了。非常感谢

**Comment by Zss1990** [comment]
相册名字可否不直接取用的系统提供的相册名字，也使用trings File这种多语言文件

**Comment by banchichen** [comment]
@Zss1990 不支持，需要自己改源码
