### ISSUE TITLE
当应用在viewWillAppear全局隐藏状态栏时，界面显示有问题，求教，谢谢！

### ISSUE THREAD

**Issue by LCcccccc** [banchichen/TZImagePickerController#187]
![image](https://cloud.githubusercontent.com/assets/12567638/17970681/363af1cc-6b0a-11e6-830f-bb233dfc636e.png)

如图，顶部没有状态栏时，显示有问题，怎么解决呢？谢谢了

**Comment by banchichen** [comment]
你好，请参考issue174。我这里iOS789的设备都没有这个问题噢...你可以比较下Demo的效果和你项目的效果... 注意下Demo中关于状态栏的设置View controller-based status bar appearance是为NO的，如果你项目中设置为YES的话，可能会导致这个问题，因为去预览控制器，有对状态栏进行了隐藏，之后再打开。

**Comment by banchichen** [comment]
最新代码中这里处理好了，不管View controller-based status bar appearance属性设置为YES还是NO，都不会出现状态栏的显示问题了~

**Comment by LCcccccc** [comment]
谢谢！
