### ISSUE TITLE
demo中加号按钮有时需要点几下才有反应

### ISSUE THREAD

**Issue by dengsss** [banchichen/TZImagePickerController#189]
demo中加号按钮有时点击直接弹到相册选择图片，有时弹出actionSheet，有时要连续点几下才有反应

**Comment by banchichen** [comment]
你好，如果 把拍照按钮放在外面 开关是开启的，就会弹出UIActionSheet，否则会直接进入相册。点几下才有反应，应该不会吧...

**Comment by banchichen** [comment]
你好，如果 把拍照按钮放在外面 开关是开启的，就会弹出UIActionSheet，否则会直接进入相册。点几下才有反应，应该不会吧...

**Comment by banchichen** [comment]
你好，如果 把拍照按钮放在外面 开关是开启的，就会弹出UIActionSheet，否则会直接进入相册。点几下才有反应，应该不会吧...

**Comment by banchichen** [comment]
你好，如果 把拍照按钮放在外面 开关是开启的，就会弹出UIActionSheet，否则会直接进入相册。点几下才有反应，应该不会吧...

**Comment by dengsss** [comment]
我刚刚又试了几下，确实有连续点击几下才能正常进入相册的情况。你试着点击加号，正常进入相册后取消。退回来后再点击加号，再取消。连续几次后就会频繁出现要连续点几次的情况。如果点击那个加号的边缘部分，出现的更加频繁

**Comment by banchichen** [comment]
我这里不会...(⊙o⊙)…

**Comment by dengsss** [comment]
真机就没问题。模拟器有问题
