### ISSUE TITLE
干脆都 statusBarHidden = YES吧

### ISSUE THREAD

**Issue by rushairer** [banchichen/TZImagePickerController#191]
TZImagePickerController
TZPhotoPickerController
都有statusBar

到了 TZPhotoPreviewController  又没有statusBar了

如果给UINavigationController 加了全屏手势来返回的话，滑动的过程就出现前后 statusBar 跳那么一下下了，不好看😂

另外建议用属性别用私有变量了，继承或Category重载都不方便，又不想破坏你的源代码😂

**Comment by banchichen** [comment]
你好，图片预览的时候有状态栏很丑吧....我这个界面是完全参照微信的做的，微信的处理是，在TZPhotoPreviewController控制器中，不允许侧滑返回...

**Comment by rushairer** [comment]
我的意思是都隐藏掉比较好看。
我手机越狱忘记转哪个插件，所有的侧滑都管用，代码管不住😂

**Comment by banchichen** [comment]
不过没见过有哪个图片选择器把导航栏隐藏掉的....要隐藏的话你自己改源码吧~不然会影响其他使用者。。。

**Comment by rushairer** [comment]
建议用属性别用私有变量了，这样可以不破坏你的源代码，用继承或Category重载就可以实现个性修改了。

**Comment by banchichen** [comment]
好吧~
