### ISSUE TITLE
请问如何获取选取图片的本地路径,能否通过本地路径获取到选取的图片?

### ISSUE THREAD

**Issue by MrDragonn** [banchichen/TZImagePickerController#192]
作者你好,我想知道返回图片信息中infos字典里的@"PHImageFileURLKey"是否是本地系统相册的路径,能否通过这个路径获取到本地系统相册中的图片

**Comment by banchichen** [comment]
你好，不可以这样的，详见issue149  https://github.com/banchichen/TZImagePickerController/issues/149
