### ISSUE TITLE
在相册列表选择图片的时候有时候右上角那个勾会变绿，有时候会变成预览图片

### ISSUE THREAD

**Issue by xmlhttp** [banchichen/TZImagePickerController#193]

**Comment by banchichen** [comment]
抱歉，我没太听懂... 有截图吗？

**Comment by xmlhttp** [comment]
![qq 20160830143914](https://cloud.githubusercontent.com/assets/16042339/18078726/ae171b7c-6ebf-11e6-9136-3765eda3a425.png)

**Comment by xmlhttp** [comment]
同一个操作出现了两种结果

**Comment by banchichen** [comment]
触摸点在选择框内，就会选中，否则就是去预览。选择框的响应范围好像是36px，不只是图片大小所在范围的。
