### ISSUE TITLE
新增的外观属性barItemTextFont和barItemTextColor设置无效

### ISSUE THREAD

**Issue by zhongdom** [banchichen/TZImagePickerController#194]
1、这两个属性实在viewDidLoad方法中设置，此时用的是默认的颜色和字体，之后设置无效；
2、建议增加一个UIImage的Category，将一张图片渲染成指定的颜色，这样的可以在设置导航栏的返回按钮的箭头时渲染成使用者所需要的颜色；

**Comment by banchichen** [comment]
你好:
1.  刚刚已经解决了哈~  现在最新是1.6.4版本~
2. 导航栏的返回按钮的箭头颜色，可以这样设置哈：imagePickerVc.navigationBar.tintColor = [UIColor blueColor]; 设置了navigationBar的tintColor，会对返回按钮的颜色产生影响的~
