### ISSUE TITLE
想请教一个关于坐标的问题，如何改变照片的Exif信息来保存位置信息

### ISSUE THREAD

**Issue by ShaoShuaiiOS** [banchichen/TZImagePickerController#195]
怎么将坐标写入到已经在相册里的照片并且保存啊？就是要改变照片的Exif信息，而不是改变它的location属性，真心求解。

**Comment by banchichen** [comment]
Hi, 久等了...😊
刚刚提交了代码，已经可以保存位置信息了~会随着这次发版发布~

不过...我是保存在location属性中，改变Exif信息的方式，我也没啥研究...😊
