### ISSUE TITLE
你好，预览里面获取到iCloud 的照片原图后显示的有点变形了。

### ISSUE THREAD

**Issue by Nsir15** [banchichen/TZImagePickerController#196]
还有就是预览的时候一开始显示的是模糊的缩略图，如果连着几张都是模糊图的话我左右滑上几次最后停在我一开始点击的预览页面得到的原图不是当前模糊图的结果，可能是最后下载下来的那个图。不知道怎么解决该

**Comment by banchichen** [comment]
你好，新版应该已经解决了~  请更新到新版试试~
