### ISSUE TITLE
相册中选取大图（如 全景图 被报内存溢出直接闪退）

### ISSUE THREAD

**Issue by zhulihuo** [banchichen/TZImagePickerController#197]
通过TZImagePickerController去读取本地相册图片，在大图（如 全景图 ），报内存溢出直接闪退；Received memory warning.
Message from debugger: Terminated due to memory issue

我用的是：
/// Get Original Photo / 获取原图
- (void)getOriginalPhotoWithAsset:(id)asset completion:(void (^)(UIImage *photo,NSDictionary *info))completion {}方法；

该方法中，有这么一段代码，应该这个方法导致读取全景图会崩溃：
[[PHImageManager defaultManager] requestImageForAsset:asset targetSize:PHImageManagerMaximumSize contentMode:PHImageContentModeAspectFit options:option resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info) {

**Comment by banchichen** [comment]
你好，getOriginalPhotoWithAsset方法在我的库中并没有使用吧，我只是在TZImageManager中提供了这样一个方法...   这里会去获取图片的原图，占用内存是会很大的..

**Comment by zhulihuo** [comment]
你好，现在需要支持全景大图，用getOriginalPhotoWithAsset这个方法的话，会崩；用另一个你在库中用到的getPhotoWithAsset方法的话，就不是原图，压缩了图片；不知道有什么好的处理方法，大图还是需要支持下；谢谢

**Comment by banchichen** [comment]
即时只是单纯取和屏幕等宽大图，在6plus上内存已经占有比较多了....   取原图显示内存更吃不消...    
/// Default is 600px / 默认600像素宽
@property (nonatomic, assign) CGFloat photoPreviewMaxWidth;
这个属性决定图片的最大预览宽度，我好像限制了最大取800，你设置成一个很大的值试试...
