### ISSUE TITLE
发现一个crash问题

### ISSUE THREAD

**Issue by uoveu789** [banchichen/TZImagePickerController#198]
您好，发现您这个控件一个bug，会导致奔溃，情况如下：
用PHFetchResult *topLevelUserCollections = [PHCollectionList fetchTopLevelUserCollectionsWithOptions:nil];获取到用户相册后，去循环的时候collection不一定是PHAssetCollection类，有一种“iphone事件”相册，collection是PHCollectionList类，没做类型判断会直接导致app奔溃

![image](https://cloud.githubusercontent.com/assets/3763529/18114859/4056e4f6-6f6d-11e6-9d74-651121bb1529.png)
![image](https://cloud.githubusercontent.com/assets/3763529/18114986/2e546a5c-6f6e-11e6-8e13-1bf7df65d93b.png)
![image](https://cloud.githubusercontent.com/assets/3763529/18114990/3b0f1846-6f6e-11e6-962d-383a148a23ec.png)

**Comment by banchichen** [comment]
谢谢提供这么重要的信息~ 已修复~    比较奇怪..

**Comment by uoveu789** [comment]
iphoto事件相册现在很少人用了，你在1.6.3更新了吗？

**Comment by banchichen** [comment]
好吧~ 现在倒还是1.6.3，我只是更新的代码，pod倒还没更新的...

**Comment by uoveu789** [comment]
求更新pod

**Comment by banchichen** [comment]
好吧~ 正在更新了，最晚15分钟后可以更新到1.6.4版本~

**Comment by uoveu789** [comment]
3q
