### ISSUE TITLE
crash , appearanceWhenContainedInInstancesOfClasses is available at 9.0

### ISSUE THREAD

**Issue by faimin** [banchichen/TZImagePickerController#2]
崩溃在TZImagePickerController类里的41行位置.
appearanceWhenContainedInInstancesOfClasses"这个方法是9.0之后才有的,但是你的判断却是让它在7.0之后的系统上执行,所以才导致崩溃

UIBarButtonItem *barItem = [UIBarButtonItem appearanceWhenContainedInInstancesOfClasses:@[[TZImagePickerController class]]];

**Comment by banchichen** [comment]
的确....感谢反馈，已修复，待会就push上来，还在发现的请麻烦告知~
