### ISSUE TITLE
pods集成无法运行了 

### ISSUE THREAD

**Issue by lixiang1994** [banchichen/TZImagePickerController#20]
我用pods集成的 项目开启就蹦了 - - 问题是我还没调用你的 只是单纯的集成而已 它蹦的信息是这个 
dyld`dyld_fatal_error: ->  0x120069098 <+0>: brk 

但是手动集成就没有事

**Comment by banchichen** [comment]
你好，不好意思最近太忙了，才有空来看这里...新版本已经解决了这个问题~~~
