### ISSUE TITLE
国际化和预览界面

### ISSUE THREAD

**Issue by 742631856** [banchichen/TZImagePickerController#200]
可以考虑把国际化的文字，做成属性提供给用户设置，自己默认中英的国际化就行，预览界面在返回和选中按钮中间加一个   “(当前是第几个)/(总共多少个) 如 ： 23/50” 的文字显示

**Comment by banchichen** [comment]
你好，这个选择器目前还暂时不考虑脱离微信的风格....    然后就是你这里提到的国际化，是无法实现的...
