### ISSUE TITLE
getOriginalPhotoWithAsset 获取原图严重问题

### ISSUE THREAD

**Issue by rain1458** [banchichen/TZImagePickerController#201]
(void)getOriginalPhotoWithAsset:(id)asset completion:(void (^)(UIImage *photo,NSDictionary *info))completion 使用这个方法获取原图, 有时候会重复获取, 获取渲染过(滤镜拍摄的图), 得到的图很小, 模糊不清

重复获取问题难以解决

**Comment by banchichen** [comment]
// If the asset's aspect ratio does not match that of the given targetSize, contentMode determines how the image will be resized.
//      PHImageContentModeAspectFit: Fit the asked size by maintaining the aspect ratio, the delivered image may not necessarily be the asked targetSize (see PHImageRequestOptionsDeliveryMode and PHImageRequestOptionsResizeMode)
//      PHImageContentModeAspectFill: Fill the asked size, some portion of the content may be clipped, the delivered image may not necessarily be the asked targetSize (see PHImageRequestOptionsDeliveryMode && PHImageRequestOptionsResizeMode)
//      PHImageContentModeDefault: Use PHImageContentModeDefault when size is PHImageManagerMaximumSize (though no scaling/cropping will be done on the result)
// If -[PHImageRequestOptions isSynchronous] returns NO (or options is nil), resultHandler may be called 1 or more times.
//     Typically in this case, resultHandler will be called asynchronously on the main thread with the requested results.
//     However, if deliveryMode = PHImageRequestOptionsDeliveryModeOpportunistic, resultHandler may be called synchronously on the calling thread if any image data is immediately available. If the image data returned in this first pass is of insufficient quality, resultHandler will be called again, asychronously on the main thread at a later time with the "correct" results.
//     If the request is cancelled, resultHandler may not be called at all.
// If -[PHImageRequestOptions isSynchronous] returns YES, resultHandler will be called exactly once, synchronously and on the calling thread. Synchronous requests cannot be cancelled. 
// resultHandler for asynchronous requests, always called on main thread
- (PHImageRequestID)requestImageForAsset:(PHAsset *)asset targetSize:(CGSize)targetSize contentMode:(PHImageContentMode)contentMode options:(nullable PHImageRequestOptions *)options resultHandler:(void (^)(UIImage *__nullable result, NSDictionary *__nullable info))resultHandler;

你好，这是苹果的解释，这个方法本身就是会调用一到多次的，第一次返回的可能是缩略图，原图较大，是异步获取。如果同步获取，界面很可能会卡死的。可以参考下这个方法- (PHImageRequestID)getPhotoWithAsset:(id)asset photoWidth:(CGFloat)photoWidth completion:(void (^)(UIImage *photo,NSDictionary *info,BOOL isDegraded))completion;  这里的isDegraded表示是否是缩略图，isDegraded = [[info objectForKey:PHImageResultIsDegradedKey] boolValue]，如果是缩略图，isDegraded就是YES，为NO的则是原图;

**Comment by rain1458** [comment]
非常感谢.
(PHImageRequestID)getPhotoWithAsset:(id)asset photoWidth:(CGFloat)photoWidth completion:(void (^)(UIImage *photo,NSDictionary *info,BOOL isDegraded))completion; 这里的isDegraded表示是否是缩略图，isDegraded = [[info objectForKey:PHImageResultIsDegradedKey] boolValue]
这个方法获取的缩略图非常小, 图片长宽只有40 * 30,  而且会调用很多次,  有没有指定获取缩略图大小的方法呢,  设置photoWidth看起来没有效果.   特别是加了滤镜、或者全景图,  取一张照片的方法甚至会调用6次以上... 囧

**Comment by banchichen** [comment]
你好，设置的photoWidth只对取到的大图有效果，缩略图是一定会返回的，任何一个应用做图片选择器，都不会先返回大图，苹果的这个API是这样调的。
