### ISSUE TITLE
大家xcode beta 8.6是否闪退？

### ISSUE THREAD

**Issue by hegelsu** [banchichen/TZImagePickerController#203]
大家xcode beta 8.6是否闪退？

**Comment by banchichen** [comment]
你好，我自己在Xcode8.0 beta6上是可以正常运行的，在iOS10上也是正常运行的。请问能帖一下闪退日志吗？   如果是运行在iOS10设备（包括模拟器）上闪退，可能是需要在info.plist中加入Privacy - Photo Library Usage Description和Privacy - Camera Usage Description两个字段，我的Demo中有加，在你们的项目中也应该加入~iOS10上需要的~

**Comment by hegelsu** [comment]
好，我试下。

**Comment by hegelsu** [comment]
加入权限后问题解决。
