### ISSUE TITLE
预览图片那边有点小BUG

### ISSUE THREAD

**Issue by GLWen** [banchichen/TZImagePickerController#206]
在外面collectionView中点击一个cell进行预览图片的时候， 然后取消图片上面右边按钮，再选择的时候会提示你最多只能选择0张照片！
这是BUG吗？还是本来就那样？但是微信，你取消再选择还是会继续选中的。

**Comment by GLWen** [comment]
还有一个问题，就是我在collectionView中点击一个cell进行预览图片的时候，我取消再点击完成，之前保存的NSArray *assets 数量不会变化，同样你在外面删除图片，也不会改变数组，也就说这个方法没走。[imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
    }];
 既然这个方法没走，我拿到的数组数量是错误的，那我上传到服务器肯定是错误的数组啊。该如果解决？

**Comment by GLWen** [comment]
还有无论我选择是否是原图，传进来的图片尺寸都是一样的。

**Comment by banchichen** [comment]
更新一下哈，这个bug已经默默修复了...

**Comment by tianglin** [comment]
我也遇到了，我试下最新版

**Comment by tianglin** [comment]
试了很多遍都有这问题

**Comment by banchichen** [comment]
你好，请问是在我的Demo上测试出来的吗？  我刚刚又试了，最新的Demo没这个问题。。

**Comment by GLWen** [comment]
你下载下来测试，你上传回复，我去测了下还是有问题。
发自 网易邮箱大师
在2016年09月14日 17:25，Zhen Tan 写道:

你好，请问是在我的Demo上测试出来的吗？ 我刚刚又试了，最新的Demo没这个问题。。

**Comment by banchichen** [comment]
又试了下...没问题的....

**Comment by tianglin** [comment]
对啊，是在demo上测试出来的，我选3张照片后返回，点击collectionView的某个cell进去预览，点击右上角按钮取消选择，再点击此按钮，则会提示「你最多只能选择0张照片」

**Comment by banchichen** [comment]
好吧，我明白了...我以为是点完成....之前是点完成也会那样... 我看一下~

**Comment by tianglin** [comment]
嗯嗯，辛苦~，这个应该好解决的

**Comment by banchichen** [comment]
解决了哈，在Demo的ViewController152行加入代码： imagePickerVc.maxImagesCount = self.maxCountTF.text.integerValue; 之前因为没有设置最大可选行数，所以maxImagesCount是默认的0~

**Comment by tianglin** [comment]
刚吃完点心回来，厉害👍
