### ISSUE TITLE
可不可以加入裁剪功能

### ISSUE THREAD

**Issue by GreatLiyi** [banchichen/TZImagePickerController#207]
在图片预览界面加入裁剪功能

**Comment by banchichen** [comment]
目前还没有这个计划....

**Comment by banchichen** [comment]
1.7.2版本更新，单选时可选裁剪功能，裁剪框可为任意矩形，新增如下属性：
/// Single selection mode, valid when maxImagesCount = 1
/// 单选模式,maxImagesCount为1时才生效
@property (nonatomic, assign) BOOL showSelectBtn; ///< 在单选模式下，照片列表页中，显示选择按钮,默认为NO
@property (nonatomic, assign) BOOL allowCrop; ///< 允许裁剪,默认为YES，showSelectBtn为NO才生效
@property (nonatomic, assign) CGRect cropRect; ///< 裁剪框的尺寸
@property (nonatomic, copy) void (^cropViewSettingBlock)(UIView *cropView); ///< 自定义裁剪框的其他属性
@property (nonatomic, copy) void (^cropBgViewSettingBlock)(UIView *cropBgView); ///< 自定义裁剪框背景的其他属性

详见Demo, 代码已更新到github，pod版本明天更新到1.7.2~

**Comment by GreatLiyi** [comment]
@banchichen 太棒了，感谢
