### ISSUE TITLE
Xcode8 iOS10调用奔溃

### ISSUE THREAD

**Issue by GitHubazuo** [banchichen/TZImagePickerController#209]
集成的是1.5.0 ，iOS9没有问题

**Comment by banchichen** [comment]
请问是我的Demo崩溃还是你的项目中崩溃？如果是在你的项目中的话，需要在info.plist中加入Privacy - Photo Library Usage Description和Privacy - Camera Usage Description字段的值，详见Demo中info.plist的设置。

**Comment by GitHubazuo** [comment]
谢谢，解决了，之前没设置是OK的，iOS10好像就不行了

**Comment by lucifer717** [comment]
为什么我设置了  还是偶尔崩啊   好烦
