### ISSUE TITLE
collectionView 3列时，来回拖动会有错乱感

### ISSUE THREAD

**Issue by JimWithJiang** [banchichen/TZImagePickerController#21]
collectionView 3列时，来回拖动会有错乱感，刷新不及时

**Comment by banchichen** [comment]
@JimWithJiang  我放的是4列的，是指你自己改成了用3列吗？

**Comment by JimWithJiang** [comment]
@banchichen  是的，我就是在你的demo上把4改3，来回拖动，刷新不及时，很明显的错乱感

**Comment by banchichen** [comment]
那就是cell重用没处理好....你们的产品经理要求展示3列么？这里的3列/4列，牵涉了多处代码...之后有空我再开放一个属性，允许自定义列数吧~

**Comment by JimWithJiang** [comment]
好的，谢谢
