### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by atrbx5** [banchichen/TZImagePickerController#210]
Hello in order to have ability to support more languages, you can change method 'tz_localizedStringForKey' to this:

`+ (NSString *)tz_localizedStringForKey:(NSString *)key value:(NSString *)value {
static NSBundle *bundle = nil;
    if (bundle == nil) {
        NSString *bundlePath = [[NSBundle bundleForClass:[TZImagePickerController class]]
                                pathForResource:@"TZImagePickerController" ofType:@"bundle"];
        bundle = [NSBundle bundleWithPath:bundlePath];
    }
    NSString *value1 = NSLocalizedStringFromTableInBundle(key, @"Localizable", bundle, value);
    return value1;
}`

**Comment by banchichen** [comment]
Thank you~ I just have a try, Unfortunately it not works. I think the reason is I just configured the Localizable.strings with Chinese and English, If I want to support more languages, I should configured Localizable.strings first ~

**Comment by atrbx5** [comment]
Of course you should also add more localizations for pod and add same languages in the app, but this way you don't need to hardcore 'en' 'zh' in the code

**Comment by banchichen** [comment]
Yeah, Now I understand~
