### ISSUE TITLE
在8.0.2系统下 无法显示相机胶卷

### ISSUE THREAD

**Issue by EnjoyWT** [banchichen/TZImagePickerController#211]
大神,你好,我安装的是你写的1.6.4最新版的,选择照片时只可以显示"最近添加". 无法显示"相机胶卷"等其他分类.但是在9.3系统下,可以正常显示所有分类.

**Comment by banchichen** [comment]
你好，请问在8.0.2系统下，用系统相机拍照，照片会保存在“最近添加”还是“相机胶卷”？

**Comment by EnjoyWT** [comment]
刚看到你的源码注释,看到了关于8.0-8.0.2的系统拍照图片会保存到"最近添加"中(这个我以前不知道),但是选择照片时,不是应该显示手机中所有的图片吗? 也就是显示"相机胶卷".

**Comment by banchichen** [comment]
是这样的，之前有同学反映在8.0-8.0.2的系统下，拍照的照片保存在“最近添加”，而不会保存在“相机胶卷”相册。8.0.2之后苹果才调整为拍照照片也会保存在“相机胶卷”。所以在8.0-8.0.2的系统下，所有照片就是“最近添加"了..      请你看一下你手中8.0.2系统的iPhone设备系统照片应用，拍照后照片保存在哪个相册~

**Comment by EnjoyWT** [comment]
关于8.0-8.0.2的系统拍照问题.大神,你说的是对的.可能是刚才我的表述有问题,现在重新表述一下:我的疑问是,选择图片时,应该显示的是手机中所有的图片(包括照片,手机屏幕截屏产生的图片等),而作者你选择显示的是仅仅是系统拍照的照片.这样选择显示"照片"而不是"所有图片",有什么特殊的考虑吗? 这是我不理解的.

**Comment by banchichen** [comment]
你去看看微信和QQ是怎么处理的，刚进入图片选择器的时候，是只展示一个相册的照片的，而不是把所有相册的所有照片先拿到，再显示出来的...     如果需要切换相册，是点击左上角的返回重新选择一个相册的....    每个图片选择器都是这样做的....

**Comment by EnjoyWT** [comment]
十分感谢,大神的耐心详细的回答.你说的切换相册的这个逻辑我明白了.但是还有一个问题是"是点击左上角的返回重新选择一个相册的..." 这一步操作过后,相册列表中,有且仅有一个"最近添加",没有"所有图片"和其他的分类.

**Comment by banchichen** [comment]
那这个时候系统照片应用有几个相册呢？ 对了，主要是微信和QQ，在我的图片选择器只有一个“最近添加”情况下，微信和QQ的图片选择器分别有多少个相册呢？

**Comment by EnjoyWT** [comment]
作者你故意写的只有一个"最近添加",还是我用错了.微信是两个 "所有照片" 和"最近添加".

**Comment by EnjoyWT** [comment]
刚才没说清楚,再补充一下 ," 如果需要切换相册，是点击左上角的返回重新选择一个相册的." 就是在返回按钮点击之后, 微信的有两个 "所有照片" 和"最近添加".

**Comment by banchichen** [comment]
当然不是咯，在相册列表页是取的所有相册来展示的...那微信的“所有照片”比“最近添加”照片数量要多嘛？

**Comment by EnjoyWT** [comment]
再次感谢大神, 我又要问一下了. 我说的是在8.0.2系统下, 你的相册列表页只有一个"最近添加", 没有"所有照片". 我的理解是"所有照片"也应该在相册列表页显示出来的.

**Comment by banchichen** [comment]
所有照片应该是微信手动加入的，如果“所有照片”比“最近添加”照片数量一样多，那就完全没必要...

**Comment by EnjoyWT** [comment]
是的,是这样的,如果“所有照片”和“最近添加”照片数量一样多的情况下,是没有必要显示了. 大神你的代码逻辑是这样处理的吗?,求更新呀.

**Comment by banchichen** [comment]
我的处理是没手动加入“所有照片"相册....你多比较几家试试，看看微博和QQ等，有没有手动加入“所有照片”相册...

**Comment by EnjoyWT** [comment]
好的,十分感谢作者的耐心回答,再次感谢.感谢作者的分享.
