### ISSUE TITLE
TZImagePickerController内存泄露

### ISSUE THREAD

**Issue by TheWindRises** [banchichen/TZImagePickerController#214]
使用的程序即成了MLeaksFinder内存检测工具，在使用的时候选择完照片以后，总是出现Memory Leak。不知道是什么原因引起的。

**Comment by banchichen** [comment]
你好，MLeaksFinder库对于present出来的控制器，一定会报内存泄露的，是这个库的一个已知bug，参考链接： Zepo/MLeaksFinder#27 。调试的时候也可以参考Xcode给出的内存运行情况数据，内存不会立即回收，但会在未来8-12秒的样子回收...

**Comment by TheWindRises** [comment]
谢谢 我用instruction的Leaks工具也没有检测到内存泄漏。希望这个库能越来越好用
