### ISSUE TITLE
iOS 10 上面点返回，相册中没有图片

### ISSUE THREAD

**Issue by BrookeMa** [banchichen/TZImagePickerController#216]
我的iPhone6，iOS10, 点开相册后，点返回键，table栏为空。另一个同事的iPhone6S，iOS10，点开相册后，点返回键，table栏有图片分类

**Comment by banchichen** [comment]
请问点返回键之前，相册中图片吗？    然后在微信上的图片选择器，你的iPhone6是否正常呢？

**Comment by BrookeMa** [comment]
微信里面正常，在Demo里面，点返回没有“相册选择”，但"所有图片"里图片有显示，其他功能正常

**Comment by banchichen** [comment]
啊哈，好奇怪....  我稍后拿同学的iPhone6试试...

**Comment by banchichen** [comment]
你好，问题已经找到了...  刚刚有个同学给我提了个PR....我稍后更新到1.6.5版本吧...   最新的代码中已经好了...

**Comment by BrookeMa** [comment]
好的，谢谢

**Comment by banchichen** [comment]
好了，1.6.5已经更新了~
