### ISSUE TITLE
选择图片结束后，再一次弹出选择页面时，怎么去掉上次选择的选中状态？

### ISSUE THREAD

**Issue by jihuaibin2015** [banchichen/TZImagePickerController#218]

**Comment by banchichen** [comment]
不传selectedAssets就好了

**Comment by jihuaibin2015** [comment]
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
     TZImagePickerController *imagePickerCtr = [[TZImagePickerController alloc] initWithMaxImagesCount:9 delegate:self];
//    imagePickerCtr.selectedAssets = _selectedAssets; // optional, 可选的
    imagePickerCtr.isSelectOriginalPhoto = NO;// 此处相机设置后还有相机的出现。
    self.imagePickerCtr = imagePickerCtr;
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
   
    
    // You can get the photos by block, the same as by delegate.
    // 你可以通过block或者代理，来得到用户选择的照片.
    [self.imagePickerCtr setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
    }];
    
    
    [self presentViewController:self.imagePickerCtr animated:YES completion:nil];
}


/// 用户选择好了图片，如果assets非空，则用户选择了原图。
- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto {
    
    NSLog(@"----================%@", photos);
}

**Comment by jihuaibin2015** [comment]
上面是代码，没有相应的效果出现。我希望重新模态出照片选择页面时，清空上次的选择状态。或者是直邮点击了确定，当再次弹出相册时才清空上次的选中状态。其次一个就是，相机的调用控制，代码设置没有起到做作用。作者很厉害，有时间我一定好好学习下内部的实现。谢谢！

**Comment by banchichen** [comment]
相机控制是这个属性：
/// Default is YES.if set NO, user can't take picture.
/// 默认为YES，如果设置为NO,拍照按钮将隐藏,用户将不能在选择器中拍照
@property(nonatomic, assign) BOOL allowTakePicture;

记录了选中状态，关键在这个属性。如果这个属性是空数组，就不会展示上次的选中结果的。
 // imagePickerCtr.selectedAssets = _selectedAssets; // optional, 可选的
