### ISSUE TITLE
选择图片总数限制问题

### ISSUE THREAD

**Issue by chenzhuogit** [banchichen/TZImagePickerController#22]
比如我设置了limit=9 我先选择了7张图 然后返回 然后继续选择 可以选择大于9张 就能绕过9张图的限制

**Comment by banchichen** [comment]
你好，如果你设置最大可选9张，创建的时候你给我的maxImageCount属性为9，如果这时候用户选择好了7张，你再次调用选择器时，手动设置maxImageCcount为2就可以了。
绝大部分情况下，选择好了的照片你要给用户提供删除功能，具体有没有删除，图片选择器是不知道的，它已经被销毁了。所以你再次调起图片选择器的时候，需要你给它一个新的最大可选张数的。

**Comment by chenzhuogit** [comment]
明白了 还有个问题 就是貌似这个选择器选择图片后没有删除功能

**Comment by banchichen** [comment]
你好，这个功能是你自己做的呢，我怎么替你做删除功能呢？我只是提供图片选择的功能，具体界面怎么搭，是否需要提供删除/浏览/编辑功能啥的，这些需求都因项目不同而不同呢，需要自己再实现的。Demo里只是做个展示而已~

**Comment by chenzhuogit** [comment]
好的理解了 谢谢
