### ISSUE TITLE
当设置可选张数为1张并允许照片原图时出现问题

### ISSUE THREAD

**Issue by fengyunjue** [banchichen/TZImagePickerController#221]
我打开图片选择器,选择第一张,点击原图,然后取消原图,之后滑动到第二张,点击确定,结果得到的是第一张!如果只选择一张图片的话,"确定"按钮的旁边应该不需要提醒选择了一张了吧,详细请见下面的录屏,麻烦作者了!
[bug.zip](https://github.com/banchichen/TZImagePickerController/files/486811/bug.zip)

**Comment by banchichen** [comment]
你好，谢谢你的视频，问题已经修复了~  详见最新的提交，pod的1.6.6版本已经发布，pod更新一下吧~
