### ISSUE TITLE
打开的相机取消按钮为英文

### ISSUE THREAD

**Issue by dragonsun7** [banchichen/TZImagePickerController#226]

**Comment by dragonsun7** [comment]
另外相册名称也为英文

**Comment by banchichen** [comment]
1. 你把设备/模拟器 跳转为中文语文环境；2. 在info.plist中加入字段Localization native development region，值设置为en，详见Demo的设置。

**Comment by banchichen** [comment]
调整...

**Comment by dragonsun7** [comment]
谢谢，刚才我也找到解决办法了。
 info.plist文件里面添加：Localized resources can be mixed           YES
