### ISSUE TITLE
☑️图片的时候，如果滑动到选择按钮那里，不动。

### ISSUE THREAD

**Issue by igouz** [banchichen/TZImagePickerController#227]
☑️图片的时候，如果滑动到选择按钮那里，不动。

**Comment by banchichen** [comment]
你好，没太听懂你的意思....

**Comment by longcontrol** [comment]
我猜@igouz 的意思应该是：比如在照片的collectionView批量选择时，如果手指刚好放到那个打勾的按钮上，然后从这个点开始滑动手势，collectionview就不会有反应。应该是选择按钮把触摸拦截住了，可以设置collectionView.delaysContentTouches = YES，让collectionView优先响应。

**Comment by banchichen** [comment]
@longcontrol  你好，谢谢你详细的解释~我发现问题了~   我刚刚提交了代码，问题解决了~  不过不是设置collectionView.delaysContentTouches = YES哈，delaysContentTouches属性默认就是YES的。我的解决办法是自定义一个TZCollectionView， 重写了UICollectionView的- (BOOL)touchesShouldCancelInContentView:(UIView *)view方法，详见我最新的提交哈~
