### ISSUE TITLE
关于单选模式的问题

### ISSUE THREAD

**Issue by tunfo** [banchichen/TZImagePickerController#228]
现在这个新的单选模式交互太不友好了，和多选时相差很远。之前没有单选模式的时候，用户选择一张图片就打钩，要选择另外一张先取消原来选的，再打钩一张新的。虽然比较麻烦一点，但是操作和多选的时候是一样的，比较友好。但是新的单选模式点击一张图片不是打钩，而是跳出大图预览，如果我不想要这个图片得后退再选择。大图预览的时候点击完成来完成图片的选择，这个很难接受。建议单选模式应该是和多选一样，选一张然后打钩，如果选另外一张，之前的勾取消掉，新的一张打钩。确认选择还是放在右下角那个绿色的完成那里。

**Comment by banchichen** [comment]
你好，目前这个单选的交互逻辑，和系统的相册是完全一样的....  市场上几乎所有的APP在选择头像时都是打开系统相册，我想这种交互方式大家都熟悉的....     而你提到的这个方式更适合多选...
