### ISSUE TITLE
iPhone4s，iOS8.3的设备上，拍照崩溃

### ISSUE THREAD

**Issue by Braddyu** [banchichen/TZImagePickerController#232]
在iPhone4s，iOS8.3的设备上，从照片选择页点击拍照进入拍照界面，然后点击拍照时崩溃，应该是内存一下增长过多被系统杀掉。请问作者有什么好的解决方案没有？

**Comment by banchichen** [comment]
请问这个设备在QQ等其他图片选择器中拍照会崩溃吗？

**Comment by Braddyu** [comment]
我用同一个iPhone4s，iOS8.3的设备测试过了，分别用微信和qq，在微信上也会崩溃，但是qq上不会！

**Comment by banchichen** [comment]
QQ的图片选择器做得是比微信牛逼的~  崩溃日志是啥~？  你有信心把这个问题解决了提个PR么~ 😊

**Comment by Braddyu** [comment]
我在尝试，不过这几天项目比较忙，等解决了的话我会提。

**Comment by banchichen** [comment]
好，加油~

**Comment by banchichen** [comment]
建议升级下版本试试，中间有几个小版本中，iOS8-9下，使用的保存照片方法有问题，请升级下试试哈...

还可以参考下这个issue：https://github.com/banchichen/TZImagePickerController/issues/481
新的情况请在这个issue下评论哈，把崩溃日志贴出来看下~

**Comment by HughLi** [comment]
#### iPhone4S 系统iOS8.1 不能使用,报错代码行如下
![](http://ostglltzu.bkt.clouddn.com/17-12-11/59155483.jpg)

#### 错误日志
![](http://ostglltzu.bkt.clouddn.com/17-12-11/82716392.jpg)

在其他设备测试 改行设置的依然为空(字典写入为nil),未发生crash

**Comment by banchichen** [comment]
@HughLi 你好，升级一下新版，新版对这里做了保护，在configDefaultSetting方法里给了一个默认值。
