### ISSUE TITLE
照相Cell是否需要放第一个；转屏后Grid不能正确适配。

### ISSUE THREAD

**Issue by uumailbox** [banchichen/TZImagePickerController#234]
1. Grid内的照相Cell是否应该放在第一个格子？以免照片太多时，如果用户要拍照，需要滚动到底部才知道；
2. 在转屏后，Grid不能正常适配。

**Comment by banchichen** [comment]
1. 请仔细看Demo吧，各个开关都打开一下... 放第一个和放最后一个都可以的.... 2. 是的，目前没有做横竖屏适配...

**Comment by uumailbox** [comment]
如果按时间降序排列的话，可以拍到第一个。这样不够完美！
谢谢你开发的这个库，很不错！
