### ISSUE TITLE
iOS8  PHAsset 怎么获取filename?

### ISSUE THREAD

**Issue by okmijnuhb** [banchichen/TZImagePickerController#236]
iOS8  PHAsset 怎么获取filename?

**Comment by banchichen** [comment]
你好，Demo中新增方法`/// 打印图片名字
- (void)printAssetsName:(NSArray *)assets {
    NSString *fileName;
    for (id asset in assets) {
        if ([asset isKindOfClass:[PHAsset class]]) {
            PHAsset *phAsset = (PHAsset *)asset;
            fileName = [phAsset valueForKey:@"filename"];
        } else if ([asset isKindOfClass:[ALAsset class]]) {
            ALAsset *alAsset = (ALAsset *)asset;
            fileName = alAsset.defaultRepresentation.filename;;
        }
        NSLog(@"图片名字:%@",fileName);
    }
}`    详见最新的Demo，pod1.6.9版本正在发布中...

**Comment by okmijnuhb** [comment]
fileName = [phAsset valueForKey:@"filename"];
这个不是私有API,审核会不会被拒绝?

**Comment by banchichen** [comment]
这个...不是很清楚...   不过目前我也没有其他合理的途径获取图片名....
