### ISSUE TITLE
您好，当已经选取图片后 会显示一个hud 这时候 点击左上角的返回 hud不会消失

### ISSUE THREAD

**Issue by xmt0615** [banchichen/TZImagePickerController#24]
当然这是我们的测试人员发现的问题，实在是不好意思，又提了一个小小的问题 我的做法是加了一个小方法 真的感谢您！

代码修改的是这里 
@implementation TZAlbumPickerController

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    
    TZImagePickerController *imagePickerVc = (TZImagePickerController *)self.navigationController;
    [imagePickerVc mt_hideProgressHUD];
    
    if (_albumArr) return;
    [self configTableView];
}
- (void)mt_hideProgressHUD {
    if (_progressHUD) {
        [_HUDIndicatorView stopAnimating];
        [_progressHUD removeFromSuperview];
    }
}

**Comment by banchichen** [comment]
你好，谢谢指出，虽然我没有复现成功......代码已经加上了，这样代码就更加健壮~
