### ISSUE TITLE
能否增加一个控制选项，打开的时候是直接到相册列表的？

### ISSUE THREAD

**Issue by hegelsu** [banchichen/TZImagePickerController#240]
能否增加一个控制选项，打开的时候是直接到相册列表的？

**Comment by banchichen** [comment]
还没见过哪个应用是直接到相册列表的.....    我后面有时间的话弄一下吧....  可能不会很快...

**Comment by hegelsu** [comment]
用的人多，需求也就广泛了嘛，尽快哈，谢谢。

**Comment by Yalin828** [comment]
微信就是直接到相册列表，我也有这个需求的，😄

**Comment by banchichen** [comment]
微信那个是系统自带的才跳转去了相册列表噢...
好吧，用的人多了确实有各种需求都有.... 我看一下，我尽快给加上吧~

**Comment by banchichen** [comment]
- (instancetype)initWithMaxImagesCount:(NSInteger)maxImagesCount columnNumber:(NSInteger)columnNumber delegate:(id<TZImagePickerControllerDelegate>)delegate pushPhotoPickerVc:(BOOL)pushPhotoPickerVc;

新增一个初始化方式如上，pushPhotoPickerVc传NO，则会停留在相册列表页，不会去照片列表页哈。
代码已经更新了，详见Demo，最新版本1.6.8，pod也更新了~

**Comment by Yalin828** [comment]
😄，谢谢了，感谢得很

**Comment by hegelsu** [comment]
同样感谢。
