### ISSUE TITLE
能不能增加一个最少选择多少张照片和选择0张的时候返回？

### ISSUE THREAD

**Issue by huafeihuamantian** [banchichen/TZImagePickerController#241]
1 有时候需要至少选择多少张的需求

2 有时候需要选择张数为0的时候也能确定返回

**Comment by banchichen** [comment]
好吧，用的人多了确实有各种需求都有....    我看一下，尽快给加上吧~

**Comment by banchichen** [comment]
/// The minimum count photos user must pick, Default is 0
/// 最小照片必选张数,默认是0
@property (nonatomic, assign) NSInteger minImagesCount;
/// Always enale the done button, not require minimum 1 photo be picked
/// 让完成按钮一直可以点击，无须最少选择一张图片
@property (nonatomic, assign) BOOL alwaysEnableDoneBtn;

代码已经更新了，详见Demo，最新版本1.6.8，pod5分钟后会更新成功~
