### ISSUE TITLE
修改布局

### ISSUE THREAD

**Issue by ChenBiaoHub** [banchichen/TZImagePickerController#242]
请问大神，这个框架我想把navigationController去掉，只要显示所有图像的collectionView的那个界面，怎么写啊。
我看了很久，每个文件之间联系比较紧，不知道怎么下手了，希望你能帮帮我，谢谢啦

**Comment by banchichen** [comment]
你去掉返回按钮就好了吧，这样就不能返回上一个相册列表界面，也就看起来只有照片列表界面了。

**Comment by ChenBiaoHub** [comment]
- 首先多谢大神回复
- 这样还是不行，我要去掉导航栏才可以。
- 我自己写的时候遇到一个问题，获取到相册所有图片之后，保存在数组中，然后用collectionView显示的时候，内存暴增，请问这个怎么解决啊？
