### ISSUE TITLE
在swift中使用时imagePickerControllerDidCancel这个方法名重复

### ISSUE THREAD

**Issue by chlsix** [banchichen/TZImagePickerController#243]
UIImagePickerControllerDelegate和TZImagePickerControllerDelegate中都有imagePickerControllerDidCancel方法，在swift中使用会报错

**Comment by banchichen** [comment]
你好，imagePickerControllerDidCancel代理方式可以不用实现哈~控制器会自己dismiss..  你先采用block的方式做吧~  我稍后把名字更新一下....

**Comment by chengxianghe** [comment]
我也遇到的这个问题 可以在代理方法前面加上 "tz_" 前缀

**Comment by banchichen** [comment]
大家好，新版中imagePickerControllerDidCancel已经弃用了，新方法的名字是tz_imagePickerControllerDidCancel。 稍后pod会更新到1.6.9
