### ISSUE TITLE
在demo里新设备第一次打开该应用都无法获取到任何图片。

### ISSUE THREAD

**Issue by wakingwwk** [banchichen/TZImagePickerController#245]
在demo里新设备第一次打开该应用都显示没图片的，等到第二次打开之后才能看到设备里的图片，这是为什么呢？

**Comment by haomemo** [comment]
我的也是,第一次打开没有图片,第二次才显示图片

**Comment by banchichen** [comment]
你好，已经修复了哈。在TZImagePickerController类的observeAuthrizationStatusChange方法中，在timer=nil 后加入  [self pushPhotoPickerVc]; 就可以了。 新的pod版本稍后再出~
