### ISSUE TITLE
返回键显示的不是『照片』而是『Back』

### ISSUE THREAD

**Issue by lulee007** [banchichen/TZImagePickerController#246]
每次打开返回键显示的不是『照片』而是『Back』,但是重新返回后正常。
![bug](https://cloud.githubusercontent.com/assets/5875280/19228939/523a7148-8efc-11e6-9853-dc9b2d0a94be.gif)

**Comment by banchichen** [comment]
你好，最新的提交中优化这里了，采用了和微信一样的方式....让相册列表的backBarButtonItem文字为返回...
