### ISSUE TITLE
现在的demo中不能选择一张图

### ISSUE THREAD

**Issue by liyang123** [banchichen/TZImagePickerController#247]
demo中为什么强制至少选择三张图？能选择一张或者两张图吗？当设置最大可选值是1的时候，直接选择一张图片后退出，并且返回选择的这一张图片

**Comment by banchichen** [comment]
你好，ViewController控制器的223行，注释掉这句imagePickerVc.minImagesCount = 3 就好了。

**Comment by liyang123** [comment]
好了，没有问题了
