### ISSUE TITLE
你好，当我选择原图时，点击确定，返回发现并不是原图的大小呢？

### ISSUE THREAD

**Issue by zuojx1013** [banchichen/TZImagePickerController#25]
你好，当我选择原图时，点击确定，返回发现并不是原图的大小呢？

**Comment by banchichen** [comment]
你好，返回的photos数组，都是适合屏幕大小的图片的。如果用户点击了原图，我是把对应的asset也返回出去，否则内存可能会爆的。
TZImageManager中有通过asset请求原图的方法，用那里提供的方法即可取得原图。
