### ISSUE TITLE
希望图片预览功能除支持selectedAssets之外，还支持传入UIImage, NSURL来预览

### ISSUE THREAD

**Issue by LCcccccc** [banchichen/TZImagePickerController#251]
`/// This init method just for previewing photos / 用这个初始化方法以预览图片
- (instancetype)initWithSelectedAssets:(NSMutableArray *)selectedAssets selectedPhotos:(NSMutableArray *)selectedPhotos index:(NSInteger)index;`

由于是缓存的照片，只有Image，没有Assets，无法传递selectedAssets参数，预览会崩溃。

**Comment by Immanito** [comment]
我也有这个问题，请问你解决了吗

**Comment by LCcccccc** [comment]
我直接改了代码，没有用Assets了，直接用Image操作图片

**Comment by Immanito** [comment]
麻烦可以给我发一份改过的代码吗？谢谢了，我这边已经集成进去了，换库代价太大了……方便的话希望加一下联系方式，我QQ547720714

**Comment by JIAZoro** [comment]
我的事预览图片方法进去和选择图片一样的界面。。。。无法预览图片

**Comment by chenYuCui** [comment]
这个我也碰到了同样的问题，预览直接崩溃，初始化的时候图片数组不为空，而selectedAssets 为空了，导致预览崩溃，再次上传图片代理过来以后也崩溃

**Comment by ungacy** [comment]
[ImageCrop.zip](https://github.com/banchichen/TZImagePickerController/files/1309578/ImageCrop.zip)

在原先基础上改的.可以参考下~

**Comment by banchichen** [comment]
Hi，3.0.1版本已支持，需新接一个插件库：[TZImagePreviewController](https://github.com/banchichen/TZImagePreviewController)，请参考TZImagePreviewController里面的Demo使用。

抱歉久等了...
