### ISSUE TITLE
无法给selectedAssets赋值

### ISSUE THREAD

**Issue by yujianfeikong** [banchichen/TZImagePickerController#252]
1.定义了一个UIImage数组
var selectedImages: [UIImage]
2.在didFinishPickingPhotos方法中给selectedImages赋值
func imagePickerController(picker: TZImagePickerController!, didFinishPickingPhotos photos: [UIImage]!, sourceAssets assets: [AnyObject]!, isSelectOriginalPhoto: Bool) {
        selectedImages = photos
        imagesCollectionView.reloadData()
}
3.设置删除图片方法
func deleteBtnClik(sender: UIButton) {
        selectedImages.removeAtIndex(sender.tag)
        imagesCollectionView.performBatchUpdates({
            let indexPath = NSIndexPath.init(forItem: sender.tag, inSection: 0)
            self.imagesCollectionView.deleteItemsAtIndexPaths([indexPath])
        }) { (finished) in
            self.imagesCollectionView.reloadData()
        }
}
4.图片删除后（如之前选了3个，删除后还剩2个），再次添加图片，此时图片选择器中，打钩的图片还是没删除前的几个（还有有3个图片打钩）。
5.为了解决上面的问题，参考例子给selectedAssets可变数组赋值，但是无法赋值。
下面为例子中的代码：
if (self.maxCountTF.text.integerValue > 1) {
        // 1.设置目前已经选中的图片数组
        imagePickerVc.selectedAssets = _selectedAssets; // 目前已经选中的图片数组
    }
6.无法赋值报错：
WriteMessageViewController.swift:341:43: Cannot assign value of type '[UIImage]' to type 'NSMutableArray!'

**Comment by banchichen** [comment]
如果图片不是从相册中返回出去的，是无法拿到asset对象的。这个时候也无法获取selectedAssets，只能不传selectedAssets，只是此时选择器无法记录已经选中的照片。这样情况只能这样做的，无法从UIImage对象找到一个唯一的asset

**Comment by RtzX** [comment]
我用swift 也是碰到了这个问题.. 多选 记录 已选择的照片... 看源码 selectedAssets 这个字段是 ! 的.如果是可选值就好了.. 但是OC 貌似没办法处理这个...  OC的话.. 设置 selectedAssets 是ok的... 蛋疼.swift 就是没办法记录已选择的照片了吗?
