### ISSUE TITLE
能不能加个代理方法判断图片是否能被选中，不能被选中弹个提示

### ISSUE THREAD

**Issue by mjx1003** [banchichen/TZImagePickerController#253]
rt

**Comment by banchichen** [comment]
基本是不能的，请问你是要通过什么信息来判断是否可以选中呢？  我看能不能通过传参来限制一下

**Comment by mjx1003** [comment]
主要是限制图片的尺寸，太小的图不让选，加个代理方法类似- (BOOL)imagePickerController:(TZImagePickerController *)picker shouldPickSourceAssets:(id)asset;

**Comment by banchichen** [comment]
我觉得最好这样，小的图片就不用显示出来。    既然不能选，显示出来也没意义了，比再去弹框提示用户好友些。   目前的太小的图片不能选，你是想限制图片的尺寸还是图片的data大小？

**Comment by mjx1003** [comment]
图片的尺寸，图片在相册存在却不显示会不会让用户觉得有bug

**Comment by banchichen** [comment]
那就再开放一个属性吧，是否显示不可选的图片，如果不可选，那就没有选择按钮。

**Comment by mjx1003** [comment]
OK, 3q

**Comment by banchichen** [comment]
你好，1.7.1版本代码已更新，新增如下属性：
/// Minimum selectable photo width, Default is 0
/// 最小可选中的图片宽度，默认是0，小于这个宽度的图片不可选中
@property (nonatomic, assign) NSInteger minPhotoWidthSelectable;
@property (nonatomic, assign) NSInteger minPhotoHeightSelectable;
/// Hide the photo what can not be selected, Default is NO
/// 隐藏不可以选中的图片，默认是NO，不推荐将其设置为YES
@property (nonatomic, assign) BOOL hideWhenCanNotSelect;

详见最新的Demo，pod正在更新，约10分钟后可以用pod更新1.7.1版本。
