### ISSUE TITLE
第一次就使用拍照，保存图片失败

### ISSUE THREAD

**Issue by chlsix** [banchichen/TZImagePickerController#256]
现象描述：第一次运行就执行拍照，允许拍照后，使用照片，允许访问相册，然后保存照片失败，提示要设置相册访问，点击设置闪退
问题：
1、在使用照片时已经允许访问相册了，还提示了要允许访问，而点击设置后闪退
2、不能保存图片
![img_0193](https://cloud.githubusercontent.com/assets/11608891/19378660/5813bd0a-9220-11e6-950b-2d72dbcb9885.PNG)
![img_0194](https://cloud.githubusercontent.com/assets/11608891/19378670/693a1b24-9220-11e6-975e-f22a96b0fd74.PNG)
![img_0195](https://cloud.githubusercontent.com/assets/11608891/19378672/6b8df4ea-9220-11e6-9f36-a86f22ff91ba.PNG)

**Comment by easongtd** [comment]
同问，只有第一次使用拍照才有这情况，第一次如果使用从相册选择就不会。

**Comment by banchichen** [comment]
你好，这个问题我刚刚优化了处理逻辑，现在改成了每次拍照前都会检查相册权限，如果没有的话会提示用户先开启相册访问权限。点击设置的话是去隐私设置页面，我这里测试了iOS10和iOS9都不会闪退的，你那个点击设置闪退的是什么机型什么系统呢？

**Comment by banchichen** [comment]
目前我先这样处理了：跳转到设置页面前先检查是否可以跳转，不可以跳转则弹出警告框提示用户手动跳转... 代码我稍后提交一下...
