### ISSUE TITLE
设置autoDismiss为NO时无法dismiss

### ISSUE THREAD

**Issue by CoderMaurice** [banchichen/TZImagePickerController#258]
if (imagePickerVc.autoDismiss) {
           [self.navigationController dismissViewControllerAnimated:YES completion:nil];
  }

问题出在cancel方法的这段代码 autoDismiss也会影响其他页面的dismiss吗?

**Comment by banchichen** [comment]
你好，autoDismiss设置为NO，说明你不希望图片选择器自动dismiss，你可能是需要拿到照片进入其他的控制器等等....   如果你需要图片选择器自动dismiss，为什么要设置autoDismiss为NO呢？

**Comment by CoderMaurice** [comment]
是我没有描述清楚 , autoDismiss = NO 时
TZPhotoPickerController和TZPhotoPickerController 的 取消按钮 也会不生效

**Comment by banchichen** [comment]
对，设置为NO时，取消按钮也不会dismiss，当时是有位同学有这样的需求。所以如果设置了autoDismiss为NO，就都不自动dismiss了...

**Comment by banchichen** [comment]
对，设置为NO时，取消按钮也不会dismiss，当时是有位同学有这样的需求。所以如果设置了autoDismiss为NO，就都不自动dismiss了...
