### ISSUE TITLE
图片的排序有问题

### ISSUE THREAD

**Issue by bairdweng** [banchichen/TZImagePickerController#259]
sortAscendingByModificationDate是默认的YES，最新的照片显示在后面，最后几张是没有问题的，再往上看图片的顺序就不正确了，是乱序。

**Comment by ZFbaby** [comment]
同问该问题，求楼主给个解决方案吧

**Comment by junlinfushi** [comment]
同问该问题，排序不对

**Comment by banchichen** [comment]
大家好，紧急解决方案是修改我库中的代码...
目前的问题是@"modificationDate"这个排序的key工作不正常了....
搜索@"modificationDate"，大家会在TZImageManager类中发现有两处代码，且上方都有一处包含@"creationDate"的注释了的代码，将注释的代码打开，并将带有@"modificationDate"的那句代码注释。

这样的话，相册中展示的图片将按 创建时间 排序，而不再是 修改时间... 但是不会出现乱序的问题。

更完善的解决方案再等一下...

**Comment by ZFbaby** [comment]
嗯 我自己给修复好了 按时间在排序下就好

**Comment by ZFbaby** [comment]
谢谢 大神

**Comment by bairdweng** [comment]
幸苦了，谢谢！
