### ISSUE TITLE
裁剪框可以是自定义的吗

### ISSUE THREAD

**Issue by dingchuandong** [banchichen/TZImagePickerController#260]

**Comment by ws4715535** [comment]
同问 , 可以自定义圆形的裁剪框吗?  而且裁剪框貌似不能裁剪....

**Comment by luo-h** [comment]
请问你们是怎么做裁剪框的，选择头像的时候应该需要裁减图片的

**Comment by banchichen** [comment]
1.7.2版本更新，单选时可选裁剪功能，裁剪框可为任意矩形，新增如下属性：
/// Single selection mode, valid when maxImagesCount = 1
/// 单选模式,maxImagesCount为1时才生效
@property (nonatomic, assign) BOOL showSelectBtn; ///< 在单选模式下，照片列表页中，显示选择按钮,默认为NO
@property (nonatomic, assign) BOOL allowCrop;     ///< 允许裁剪,默认为YES，showSelectBtn为NO才生效
@property (nonatomic, assign) CGRect cropRect;    ///< 裁剪框的尺寸
@property (nonatomic, copy) void (^cropViewSettingBlock)(UIView *cropView);     ///< 自定义裁剪框的其他属性
@property (nonatomic, copy) void (^cropBgViewSettingBlock)(UIView *cropBgView); ///< 自定义裁剪框背景的其他属性

详见Demo, 代码已更新到github，pod版本明天更新到1.7.2~

**Comment by banchichen** [comment]
圆形的裁剪框暂不支持...下一版本加上吧~

**Comment by banchichen** [comment]
1.7.4版本 加入对圆形裁剪框的支持
@property (nonatomic, assign) BOOL needCircleCrop;  ///< 需要圆形裁剪框
@property (nonatomic, assign) NSInteger circleCropRadius;  ///< 圆形裁剪框半径大小
