### ISSUE TITLE
当APP首次打开相册时页面会是空白的

### ISSUE THREAD

**Issue by zhumi108** [banchichen/TZImagePickerController#261]
下面是我的代码,每次我把APP卸载掉重装,然后重新present TZImagePickerController,弹出来的相册都是空的,退出重新进入相册后就正常了

     TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:1 delegate:nil];
    [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos,NSArray *assets,BOOL isSelectOriginalPhoto) {
    }];
    [self presentViewController:imagePickerVc animated:YES completion:nil];

**Comment by banchichen** [comment]
这个新版本好了的哟....中间有1-2个版本的有这个问题...
