### ISSUE TITLE
iOS10手机上问题

### ISSUE THREAD

**Issue by RiversMaJianCheng** [banchichen/TZImagePickerController#262]
在最新系统上，相机在外，用相机拍照后食用一直显示正在处理。。。。无法处理完成

**Comment by banchichen** [comment]
应该是没有允许相册权限，这个在新版中解决了的，试试新版吧~    或者直接卸载重装，同意相册权限就不会这样~

**Comment by EarthMass** [comment]
IOS10不可以，选择相册，相机都没什么反应
