### ISSUE TITLE
问一个小白的问题，如何获取原图或者828图片的拍摄日期之类的exif信息？

### ISSUE THREAD

**Issue by wot678** [banchichen/TZImagePickerController#263]
如题，实在找不到方法啊

**Comment by banchichen** [comment]
你好，关于原图请查看这个issue: https://github.com/banchichen/TZImagePickerController/issues/457

获取拍摄日期之类的信息，请查看PHAsset和ALAsset的头文件哈。在这里打个断点，就可以看到各个属性的值哈，如图：
![phasset](https://user-images.githubusercontent.com/12755494/27009873-6e5d1404-4ecb-11e7-8e36-091d2d789005.png)
