### ISSUE TITLE
在iOS10上 只允许选择视频 当视频是横屏拍摄的时候 在获取视频的时候 会崩溃在 session.videoComposition = [self fixedCompositionWithAsset:videoAsset]; 修正视频转向这一行代码...希望大神给出解决方案

### ISSUE THREAD

**Issue by jhchenchong** [banchichen/TZImagePickerController#266]
在iOS10上 只允许选择视频 当视频是横屏拍摄的时候 在获取视频的时候 会崩溃在 session.videoComposition = [self fixedCompositionWithAsset:videoAsset]; 修正视频转向这一行代码...希望大神给出解决方案

**Comment by banchichen** [comment]
你好，请先把这句代码注释吧~ 注释了不影响导出功能~

**Comment by jhchenchong** [comment]
也是通过注释这行代码暂时解决问题的  还有一个问题是 degrees 这个变量  当为0时  返回的是nil 之前以为是这个原因造成的崩溃 后来改掉之后 发现还是崩溃在那一行代码   谢谢您的回复

**Comment by banchichen** [comment]
感谢反馈~最新版已修复~
1.7.8 修复导出视频时的崩溃问题
