### ISSUE TITLE
iCloud获取的原图不是实际的原图，比原图模糊

### ISSUE THREAD

**Issue by haifenghuang** [banchichen/TZImagePickerController#272]
根据测试，在iCloud上的图像，选择原图，结果出来的不是实际的原图，请问这个怎么解决？

**Comment by banchichen** [comment]
你好，实际的原图要通过TZImageManager类的getOriginalPhotoWithAsset:completion
方法获取，我不会直接返给你...直接返给你的话内存会暴涨的...
至于用户选择的是否是原图，我有做了如下的说明：
// 如果isSelectOriginalPhoto为YES，表明用户选择了原图
