### ISSUE TITLE
bug:This application is not allowed to access Photo data.(crash)< iOS 10.0.2 ，iPhone 6 >——TZImageManager里会初始化cachingImageManager，此时如果未授权可能会出现上诉问题

### ISSUE THREAD

**Issue by chaoyue3116** [banchichen/TZImagePickerController#273]
![2016-11-04 10 18 45](https://cloud.githubusercontent.com/assets/15784911/19992357/1a576b20-a278-11e6-8a63-daa8221db7cd.png)

**Comment by hsjcom** [comment]
我最近也遇到这个问题

**Comment by waitingfor168** [comment]
有什么好的解决方案吗

**Comment by hsjcom** [comment]
已经找到原因了，TZImageManager构建单例时会[[PHCachingImageManager alloc] init]初始化manager.cachingImageManager，此时如果未授权可能会出现上诉问题，具体原因不明，不排除是系统bug。只要未授权时不初始化PHCachingImageManager，就不会出现，根据听云和友盟数据反馈。
我的解决方法，所有询问授权的都改成+方法，即先不创建单例不初始化manager.cachingImageManager

**Comment by waitingfor168** [comment]
多谢

**Comment by ginkgocy** [comment]
初始化PHCachingImageManager 后，没有访问相册权限，在内存紧张，系统回收内存的时候会释放cachingImageManager变量，引起crash。最新版虽然已经在manager 单列里注掉了初始化的代码。希望还用老版本的同学能躲开这个坑。 @waitingfor168
