### ISSUE TITLE
提示的原图大小和得到的原图大小，不一致。

### ISSUE THREAD

**Issue by immustard** [banchichen/TZImagePickerController#276]

**Comment by banchichen** [comment]
你好，实际的原图要通过TZImageManager类的getOriginalPhotoWithAsset:completion
方法获取，我不会直接返给你...直接返给你的话内存会暴涨的...
至于用户选择的是否是原图，我有做了如下的说明：
// 如果isSelectOriginalPhoto为YES，表明用户选择了原图
