### ISSUE TITLE
图片选中状态

### ISSUE THREAD

**Issue by NSUzi** [banchichen/TZImagePickerController#28]
你好，我想把图片的选中状态加到里面，就是选完图片再进去的时候可以看到我之前选中了哪些图片，

**Comment by Lynnll** [comment]
你这个需求不太科学吧...一般每次进相册都是重新选择吧。

**Comment by NSUzi** [comment]
我感觉应该算科学吧，比如说你第一次选了5张图片，再次点击进去相册的时候你又可以选9张图片了。

**Comment by banchichen** [comment]
如果你第一次选了5张图片，你只允许用户选择9张，那么当你再次进入图片选择器的时候，你把maxImageCount属性置为4，这样就好了。不要每次都给我传9。

**Comment by Lynnll** [comment]
每次选择相册图片的个数是动态计算的，假设最多选择9张，第一次选择了5张，点击完成。第二次在进入相册的时候，就最多最能选择4张了，而且不需要标记选择之前的5长图片，因为正常需求下，同一张图片是可以重复选择的吧。

**Comment by banchichen** [comment]
恩~如果要标记的话，那你们使用起来就麻烦一些，你得给我传一个asset数组，告诉我当前用户选择了哪些图片，我才能做出标记~

**Comment by NSUzi** [comment]
好的，太谢谢你了
