### ISSUE TITLE
iOS10 下用户同意权限后tipslabel消失，但没有显示相册

### ISSUE THREAD

**Issue by ice0github** [banchichen/TZImagePickerController#280]
![004269b282da949f3ea18e649fc1c844](https://cloud.githubusercontent.com/assets/5554889/20297384/3d8dd440-ab4b-11e6-9c29-c9613c20a0d3.png)
![e8ceac96d89765ba1353157bda7a18d0](https://cloud.githubusercontent.com/assets/5554889/20297385/3f2b1bdc-ab4b-11e6-978c-4ea0e30275c9.png)

**Comment by banchichen** [comment]
更新一下哈，新版应该没有这个问题。。。

**Comment by ice0github** [comment]
楼上说的对...我一直以为自己是最新版的，cocoapods自动更新的最新版是1.6.8，把podfile的版本改成1.7.1再update就好了
