### ISSUE TITLE
请问怎么设置只能选择视频或者图片？

### ISSUE THREAD

**Issue by XDB-Chang** [banchichen/TZImagePickerController#285]
请问怎么设置只能选择视频或者图片？

**Comment by banchichen** [comment]
/// Default is YES.if set NO, user can't picking video.
/// 默认为YES，如果设置为NO,用户将不能选择发送视频
@property (nonatomic, assign) BOOL allowPickingVideo;

/// Default is YES.if set NO, user can't picking image.
/// 默认为YES，如果设置为NO,用户将不能选择发送图片
@property(nonatomic, assign) BOOL allowPickingImage;

**Comment by XDB-Chang** [comment]
视频如果也要有选择的框框，是不是要自己改代码了？

**Comment by banchichen** [comment]
是的，要自己改
