### ISSUE TITLE
视频地址outputpath出不来

### ISSUE THREAD

**Issue by rap2016** [banchichen/TZImagePickerController#286]
[[TZImageManager manager] getVideoOutputPathWithAsset:asset completion:^(NSString *outputPath) {
         NSLog(@"视频导出到本地完成,沙盒路径为:%@",outputPath);
}
打印不出来这个路径

**Comment by banchichen** [comment]
你好，没有出来路径可能是视频导出失败了，之前的API设计得有问题，没有透出失败信息，目前已做优化：     
https://github.com/banchichen/TZImagePickerController/commit/88b5f37fa98c9ef093eba1d99cc0c3f4a84db475     
https://github.com/banchichen/TZImagePickerController/commit/1ab7b5a8dbfc023984ef90b7b259261ac68d8c1d     
新版本1.9.5已发布，建议升级，具体用法可参看Demo~
