### ISSUE TITLE
1.7.1版第一次拍照时相册授权问题

### ISSUE THREAD

**Issue by easongtd** [banchichen/TZImagePickerController#287]
1.7.1版在第一次拍照时会先弹出提示设置相册授权，再弹出提示相机授权，这样会弹出两个提示，用户体验不是非常好，能不能只弹出一个相机授权提示，同时默认设置相册授权。如果不行，能不能把相机拍照改成做本地存储，而不存储在相册中，这样子也能实现只弹出相机授权一个提示。不知道如何能实现上面的改进？

**Comment by banchichen** [comment]
“能不能只弹出一个相机授权提示，同时默认设置相册授权...”
这是系统弹框的...
在这个库里是必须获取相册权限的，存在本地无法进行接下来的操作。
所以这里是没有优化的计划和思路的...
你可以自己来改动代码，如果拍照的照片不需要在接下来去相册中选择时保留选中状态，你可以不把照片保存在相册，直接取到UIImage对象就够了。只是这样不能给我传selectedAssets，不能展示上次的选择状态而已。
