### ISSUE TITLE
代码小错误

### ISSUE THREAD

**Issue by Lynnll** [banchichen/TZImagePickerController#29]
TZPhotoPreviewController.m 中 cellForItemAtIndexPath 代理方法
`
__weak typeof(_naviBar) weakNaviBar = _naviBar;
__weak typeof(_naviBar) weakToolBar = _naviBar;
`
写重了，应该是_toolBar。楼主写的很棒。辛苦了！

**Comment by banchichen** [comment]
确实噢...谢谢指出~
