### ISSUE TITLE
博主你好，maxAccount 为1 的时候预览能否把按钮显示出来呢

### ISSUE THREAD

**Issue by lifeMiik** [banchichen/TZImagePickerController#292]
如题，这样子做的话可以删除照片，重新选择。谢谢

**Comment by banchichen** [comment]
你好，我下期优化的时候把这个需求放进去吧，开放一个这样设置的属性~  不过不会很快哈，最近忙成狗...

**Comment by banchichen** [comment]
1.7.2版本更新，新增如下属性：
@property (nonatomic, assign) BOOL showSelectBtn;  ///< 在单选模式下，照片列表页中，显示选择按钮,默认为NO

代码已更新到github，pod版本明天更新到1.7.2~
