### ISSUE TITLE
可以修改里面按钮的文字吗

### ISSUE THREAD

**Issue by lunZeng** [banchichen/TZImagePickerController#293]
如题

**Comment by turboxing** [comment]
同问

**Comment by banchichen** [comment]
1.7.2版本更新：
新增如下6个属性，可以自定义多个地方的文字...
@property (nonatomic, copy) NSString *doneBtnTitleStr;
@property (nonatomic, copy) NSString *cancelBtnTitleStr;
@property (nonatomic, copy) NSString *previewBtnTitleStr;
@property (nonatomic, copy) NSString *fullImageBtnTitleStr;
@property (nonatomic, copy) NSString *settingBtnTitleStr;
@property (nonatomic, copy) NSString *processHintStr;

代码已更新到github，pod版本明天更新到1.7.2~
