### ISSUE TITLE
不方便定制

### ISSUE THREAD

**Issue by lyleLH** [banchichen/TZImagePickerController#296]
作者花了很多心思去完成功能，但是代码的逻辑重复度高，代码没有很好的设计，多方的造势导致趋势上升很快，这一点值得肯定，但是又很多莫名其妙的的冗余代码，代码质量太低，冗余高，不推荐跟风的新手们选择该组件集成，现在轮到我维护的时候已经集成了很多功能，修改过很多次，被同事坑的很惨。
建议继续维护下去的话要注意代码质量，尽量找更精简的实现方式，不要被小白们的需求引导了回不去，后面越来越大的规模只会出现越来越来难以修复和调试的问题。

**Comment by lyleLH** [comment]
否则更多的人会选择别的开源组件，得不偿失

**Comment by lyleLH** [comment]
by the way，9个贡献者维护这个库未免太大材小用，但是主要代码量全部是第一作者贡献的，让人难以不怀疑作者们的别有用心。

**Comment by banchichen** [comment]
1. 没有一个作者是别有用心，这个库走到现在暴露和解决过很多bug，一些好同志自己解决了bug后顺手一个PR，我一合并于是就多了一个你眼中别有用心的作者。作者们不能以这个库赚钱都是业余时间有空了来维护。
2. 很多莫名其妙的冗余代码，我建议你直接删掉，代码就精简了。
3. 强烈推荐你换其他组件，谢谢配合。

**Comment by lyleLH** [comment]
1.a)同事集成在项目中的是早期版本，也许您的后续版本有很多大的改进，收回对您的代码"代码的逻辑重复度高，代码没有很好的设计"，"很多莫名其妙的的冗余代码，代码质量太低，冗余高”"的评价，对不起。希望您能选择后面的建议性的评价进行参考。
  b)对不起，请原谅我小人至今度君子之腹，请求您的原谅，对不起
2.同1a，也许您误会我是来吵架的。
3.暂时没有时间重写这么多的老代码，我会一直关注你的更新，不知道有没有其他好的开源组件推荐一下 👍 
4 .项目中很多对象的属性设置是以宏定义的形式实现的，建议可以考虑以参数字典或者对象结合构造方法来实现，并暴露一定的自定义设置性的接口来保证灵活性
5.祝愿您的开源越来越好

**Comment by banchichen** [comment]
我刚刚把代码大致看了一遍，目前的代码之所以比较复杂，可能由于以下几点：
1. 支持iOS6+的系统，TZImageManager类对AssetsLibrary库和Photos库做了一层封装，我研究了15+个开源图片选择器的代码，还没有看到其他库采用这种方式。而是直接把AssetsLibrary库或者Photos库的代码写在控制器里，对于使用者会更加复杂难懂。在TZImagePickerController中，因为有了TZImageManager，使用者不用关心AssetsLibrary库和Photos库的代码，已经很好减轻了使用者理解代码的负担。
使得这也是目前github中极少几个一份代码同时支持AssetsLibrary(iOS8以下)库和Photos(iOS8以上)库的图片选择器。
2. 这个库发展到现在，解决了很多同学自定义的需求。最开始它只是一个模仿微信的图片选择器，当时代码量大约是目前的一半。解决自定义需求的时候，难免代码会越来越复杂，每多开放一个属性出去，内部的逻辑就复杂一分。从Demo主界面来看，TZImagePickerController已经允许在外界自定义较多属性了。但庆幸的是，除了对网络图片预览的支持、iCloud图片选择的优化，没有其他重要bug。其中对网络图片预览对应了好几个issue，但它是无解的，技术上本身不可行，QQ空间也是如此。iCloud图片选择的优化是下一期的优化重点。
一直优化，代码只会更加复杂，但其中最复杂的控制器TZPhotoPickerController也就700多行代码，比起MWPhotoBrowser这类非常优秀的第三方库1700行的代码还有较大差距。至于不方便定制，目前我看到的issue中有需要定制按钮文字的，这个我确实没考虑进去，系统的相册选择器同样也不支持定义按钮文字，这个优先级着实不高。

其他：TZImagePickerController一共只用了四处宏定义，还都是iOS7Later这种系统版本的宏定义。参数字典和对象的方式来定义属性，我不认为是个很好的方式，这些自定义属性对应着3个界面，这个字典数组or对象怎么设计我没有思路。希望你解决了后可以提一个PR。

我当初写这个库，就是看到github上其他的库不好用or不适配iOS7等等原因，最近一次研究其他的图片选择器是三个月前，当时没有发现更好的选择器。如果你发现了，希望能告诉我。

**Comment by lyleLH** [comment]
😄😄😄😄😄

**Comment by 446226323** [comment]
作者直接关闭此issue就可以了，不知道回复此类人有何意义，一个个的用着开源框架，不顺意了上来就开喷，开上帝视角，恶意揣测，作者，你欠他们每人500万么？
