### ISSUE TITLE
奔溃错误（严重）：相册已选预览界面滑动，在最后一页用力划导致崩溃

### ISSUE THREAD

**Issue by volcanoljy** [banchichen/TZImagePickerController#297]
TZPhotoPreviewController.m 中的- (void)scrollViewDidScroll:(UIScrollView *)scrollView 方法：
如果用户滑动到最后一页，有可能在“offSetWidth = offSetWidth +  ((self.view.tz_width + 20) * 0.5)”之后，offSetWidth大于等于scrollView.contentSize.width 。从而，_currentIndex等于已选图片个数。在refreshNaviBarAndBottomBarState内部就会访问数组越界从而崩溃（TZAssetModel *model = _models[_currentIndex];
）。
个人尝试过修改如下，就不存在这个问题了：
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    CGFloat offSetWidth = scrollView.contentOffset.x;
    offSetWidth = offSetWidth +  ((self.view.tz_width + 20) * 0.5); //修改方案(1）注释此行
    /*修改方案(2)加入下面判断 如果用力滑动到最后一页
     导致活动距离大于等于contentSize的宽度，则修改
     为最后一页时的contentsize
    if (offSetWidth >= scrollView.contentSize.width) {
        offSetWidth = scrollView.contentSize.width - (self.view.tz_width + 20);
    }
     */
    NSInteger currentIndex = offSetWidth / (self.view.tz_width + 20);
    
    if (_currentIndex != currentIndex) {
        _currentIndex = currentIndex;
        [self refreshNaviBarAndBottomBarState];
    }
}

**Comment by banchichen** [comment]
发现了，谢谢指出~

**Comment by banchichen** [comment]
1.7.2版本已解决~   pod版本明天更新~
