### ISSUE TITLE
希望加入视频多选

### ISSUE THREAD

**Issue by shantj** [banchichen/TZImagePickerController#299]
手机  6p  
系统 10.1.1

使用的是你的demo

1、设置每行只显示1个视频，可是显示2个
2、视频没有办法多选
3、左下角没有大小统计

**Comment by banchichen** [comment]
你好：
1. 这个库最初设计的时候是模仿微信来设计的，视频只能选一个。如果要改动需要改库内部的代码。
2. 每行显示照片/视频的张数取值，我限制成了2-6张，要更改的话需要改动库内部的代码。
第一点的优化暂时没有计划...

**Comment by shantj** [comment]
@banchichen 好的，希望视频多选的功能日后能增加进去，多谢大神^o^

**Comment by banchichen** [comment]
你好，1.8.4版本已发布，已支持横屏。
