### ISSUE TITLE
长图会出现crash的情况

### ISSUE THREAD

**Issue by MrDML** [banchichen/TZImagePickerController#301]
选择3以上的类似长微博的长图会出现内存溢出,希望大神能够在出新功能的同时解决此bug,再次感谢大神的提供优质的代码和无私的分享.

**Comment by banchichen** [comment]
Hi, 欢迎使用新版哈，1.8.0+版本中，对长图的处理做了优化，避免了过长图片获取时内存占用过大的问题，超长图片预览/选择时内存占用会降低75%，同时清晰度会降低一些哈。和微信、微博的处理差不多~
