### ISSUE TITLE
浏览图片详情的时候 naviBar上面的两个按钮会因为设置的透明度 而影响原有的颜色

### ISSUE THREAD

**Issue by aixiaoyi** [banchichen/TZImagePickerController#302]
![fb47f8ec-84c3-4ebf-b2d6-8fed030f3045](https://cloud.githubusercontent.com/assets/23647248/20911704/d06bb930-bba4-11e6-880e-e8ab8aae503a.png)
本人觉得 直接修改naviBar这个view的透明度的做法不太适合，因为影响了原有图片的颜色
认为应该直接在 文件"TZPhotoPreviewController.m"第82行设置naviBar背景颜色的时候直接给颜色添加一个0.3透明度，去除第83设置naviBar的0.7透明度
![789bb8a9-5f9e-4951-850d-12a46efaac16](https://cloud.githubusercontent.com/assets/23647248/20911787/a4d97e6e-bba5-11e6-9ccd-c7016c96bf90.png)

**Comment by banchichen** [comment]
赞~  已优化~ 代码稍后更新~
