### ISSUE TITLE
拍照之后 如何裁剪?

### ISSUE THREAD

**Issue by RtzX** [banchichen/TZImagePickerController#304]
rt.相册选择之后.可以进入裁剪.拍照之后,如何进入呢?

**Comment by banchichen** [comment]
我刚刚提交了代码，在允许裁剪的状态下，拍照后会进入预览页面让用户裁剪。你看看这样是否可行？     可以的话我把pod更新到1.7.5~

**Comment by RtzX** [comment]
可以 是这个逻辑. 拍照之后的代理方法 返回的就应该是裁剪之后的图片

**Comment by RtzX** [comment]
感谢

**Comment by RtzX** [comment]
我看了下.. 是相册内部的拍照 之后 是可以进入裁剪的 . 你添加的是这个吗?  我的意思是外部的 就是在actionSheet 那里拍照之后. 能进入裁剪吗? 目前 我没找到方法.

**Comment by banchichen** [comment]
是的，我添加的是内部的...外部的也要裁剪对吧...   我再改一下试试...

**Comment by RtzX** [comment]
对的.. 就是拍照完成之后. 目前是直接返回了.. 对于裁剪来说, 应该是拍完照,直接进入裁剪.

**Comment by banchichen** [comment]
提交了~ 你试试~

**Comment by RtzX** [comment]
ok 了 ..谢谢
