### ISSUE TITLE
无法读取通过itenus导入手机的图片

### ISSUE THREAD

**Issue by 13213334722** [banchichen/TZImagePickerController#305]
无法读取通过itenus导入手机的图片
，ipone6 plus    9.0

![screen shot 2016-12-07 at 2 49 46](https://cloud.githubusercontent.com/assets/12411689/20957857/41bbd1ea-bc8d-11e6-9b25-8fc5a699b270.png)
![screen shot 2016-12-07 at 2 50 08](https://cloud.githubusercontent.com/assets/12411689/20957858/4244228e-bc8d-11e6-9dc1-7e165aa14d37.png)
![screen shot 2016-12-07 at 2 50 32](https://cloud.githubusercontent.com/assets/12411689/20957859/424b8970-bc8d-11e6-9cd7-b3a05336a608.png)

最初的版本是可以的，但是没找到那个版本号在哪看的，最近的版本都不能读取了，

**Comment by banchichen** [comment]
你好，谢谢提供详细资料，该bug已经解决。

新的pod版本已经发布: 
1.7.6 加入同步和共享相册
