### ISSUE TITLE
缺少一些自定义的方式

### ISSUE THREAD

**Issue by HoneyLuka** [banchichen/TZImagePickerController#306]
非常感谢TZ公开了这份picker代码

在使用过程中发现缺少了一些可自定义的方式，比如下方toolBar的'预览' 按钮的颜色，只能是黑色。
而'对勾'、'绿点'等元素只能是通过更换图片素材来自定义，感觉这种方式有点不必要，因为目前的这些UI元素可以通过一个UIColor对象来生成。
所以个人感觉最好的方式是指定一个Color，然后就可以达到更改主题色的目的。

当然目前可以通过fork的方式放到自己的repo里对代码进行直接修改，不过这样没办法随时用pod update更新到最新版。

**Comment by banchichen** [comment]
你好，感谢指出，建议非常中肯到位，目前2.1.4版本发布了，支持了绝大多数界面和组件的样式自定义，主题色iconThemeColor目前支持了部分图片，未来会进一步加强，也非常欢迎你来提交PR一起共建~

关于自定义UI的细节请参照：https://github.com/banchichen/TZImagePickerController/issues/787
