### ISSUE TITLE
ios7真机运行报错，程序无法启动。

### ISSUE THREAD

**Issue by LeeyYun** [banchichen/TZImagePickerController#307]
我打了个静态库包包含了这个照片选择器，然后再程序中加上静态库后在ios7真机设备上运行，程序无法启动，报错：dyld: Library not loaded: /System/Library/Frameworks/Photos.framework/Photos。
你的demo在iOS7的真机设备上能运行么？

**Comment by banchichen** [comment]
你好，Photos库是iOS8之后的，如果需要运行在iOS7的设备上，需要设置为Optional。可以参考下: https://segmentfault.com/a/1190000000657902，我前段时间把Xcode7.3.4卸载了，现在只有Xcode8，所以运行不了到iOS7的真机上了，用Xcode8以下版本是可以的。
