### ISSUE TITLE
大神，我发现一个问题

### ISSUE THREAD

**Issue by l1741741** [banchichen/TZImagePickerController#309]
新添加的裁剪功能，会出现图片旋转的情况，demo里就有这个问题，打开拍照按钮放在外面，允许裁剪，然后拍照，所有展示的图片都是逆时针旋转了一圈

**Comment by l1741741** [comment]
所有展示的图片都是逆时针旋转了90度

**Comment by banchichen** [comment]
你那里的设备是什么系统版本呢？我这里iOS10.1.1没发现这个问题...

**Comment by l1741741** [comment]
我的是9.2的系统
![6dd9a4bcceb2d5c22058a9d259515ecc](https://cloud.githubusercontent.com/assets/12538167/21135500/0c8f5fe4-c15d-11e6-9830-8375c10d9735.png)
![c841fd88e8bedb5c949c1ba99b440412](https://cloud.githubusercontent.com/assets/12538167/21135503/0e49d42c-c15d-11e6-82e0-049998f7ae1f.png)
![07edf9777ba4306803d52911309d7841](https://cloud.githubusercontent.com/assets/12538167/21135504/0f4be87e-c15d-11e6-863f-70709d8356d9.png)

**Comment by l1741741** [comment]
最后一张是正的，传上去给转了一下，点开看吧

**Comment by l1741741** [comment]
好像没有裁剪，只是按照尺寸压缩了

**Comment by l1741741** [comment]
我查了一下这个图片的方向是向右的
imageView.image.imageOrientation
UIImageOrientationRight

**Comment by l1741741** [comment]
http://www.jianshu.com/p/b20f1d7fc8ea

**Comment by banchichen** [comment]
你好，麻烦帮忙测试一下。在TZImageCropManager类的m文件中50行左右的代码：UIImage *cropedImage = [UIImage imageWithCGImage:imageRef]处后面，添加代码：cropedImage = [[TZImageManager manager] fixOrientation:cropedImage]; 看看是否能解决问题。 
为了编译成功，需要再操作2个地方:
1. 在TZImageCropManager类中import一下TZImageManager类；
2. 在TZImageManager的h文件中加入方法声明： - (UIImage *)fixOrientation:(UIImage *)aImage;

**Comment by l1741741** [comment]
好像在这里改方向不行，这里图片已经绘制过了，在45行图片传入时可以调用[[TZImageManager manager] fixOrientation:imageView.image].CGImage可以，但是fixOrientation: 方法
if (!self.shouldFixOrientation) return aImage; 这句给return了。我把这句话注掉了😀

**Comment by banchichen** [comment]
昂，我知道了~ 最好这样改~ 在TZPhotoPreviewController的viewDidLoad中，在[super viewDidLoad]后加入[TZImageManager manager].shouldFixOrientation = YES;然后在viewWillDisappear中加入    [TZImageManager manager].shouldFixOrientation = NO;   在预览界面时打开shouldFixOrientation修正转向，在列表界面关闭提高性能~

**Comment by banchichen** [comment]
你那样也没功能问题的~  赞~

**Comment by likekunkun** [comment]
@banchichen  大神 我用pod 的pod 'TZImagePickerController', '~> 1.7.1'   可是并没有提供剪裁的方法。。initCropTypeWithAsset。。😅

**Comment by banchichen** [comment]
@likekunkun  把1.7.1改为1.7.7 ...  不成功的话先pod setup更新下本地的pod索引...

**Comment by likekunkun** [comment]
ola  谢谢
