### ISSUE TITLE
视频选择确认问题

### ISSUE THREAD

**Issue by 371726787** [banchichen/TZImagePickerController#310]
TZImageManager.m文件
第638行，异常闪退，
session.videoComposition = [self fixedCompositionWithAsset:videoAsset];

同样的mov格式

**Comment by banchichen** [comment]
你好，这句代码先注释吧~ 我后续再来研究这里~

**Comment by 371726787** [comment]
说明下，两个视频一个是原生IOS系统保存的MOV格式视频，另外一个是我同事用的第三方框架WechatShortVideoController（https://github.com/AliThink/WechatShortVideo ）保存的mov格式视频，第一个没问题，第二个有问题

**Comment by banchichen** [comment]
感谢反馈~最新版已修复~
1.7.8 修复导出视频时的崩溃问题

**Comment by 371726787** [comment]
好的 感谢感谢
