### ISSUE TITLE
发现几处因循环引用导致内存泄漏的问题。

### ISSUE THREAD

**Issue by bairdweng** [banchichen/TZImagePickerController#311]
<img width="371" alt="0410d2c2-049b-4e69-94aa-7b4a1db0145c" src="https://cloud.githubusercontent.com/assets/8598304/21179894/2c4f0b52-c231-11e6-8975-3ea6b7101e6c.png">
TZImagePickerControllerm,TZVideoPlayerController,TZPhotoPickerController视图控制器中有部分block内部没有使用weak修饰。

**Comment by banchichen** [comment]
#214  请参考这个issue，以dealloc方法为准。那几处并没有循环引用的，因此没有使用__weak
