### ISSUE TITLE
每行展示照片数修改了 但是却没有效果。。。

### ISSUE THREAD

**Issue by likekunkun** [banchichen/TZImagePickerController#312]
我在您的demo中修改了每行展示照片数 但是仍然每行显示3个照片。。。直接在初始化的地方修改参数columnNumber 也没有效果。。。 谢谢

**Comment by banchichen** [comment]
columnNumber在内部set方法中限制值的范围是2-6...   你是打算改到多少~？ 如果不在2-6之间的话...把我内部的set方法直接注释吧...

**Comment by likekunkun** [comment]
我改的4。。。每一行还是3列。。。

**Comment by banchichen** [comment]
怎么会呢，我刚刚试了下是OK的...你是不是对Demo做了什么代码上的改动呢？  默认就是4的...

**Comment by likekunkun** [comment]
好的吧～  我再重新下载一个新的试试。。

**Comment by likekunkun** [comment]
![simulator screen shot 2016 12 15 6 09 55](https://cloud.githubusercontent.com/assets/16441213/21219938/c02d4b52-c2f1-11e6-8b3b-f372ac86ea45.png)
这个应该是4列 可是还是3列。
