### ISSUE TITLE
1.7.1 从一个控制器，presentViewController  TZImagePickerController会崩溃，xcode不报错

### ISSUE THREAD

**Issue by zuijiejieshen** [banchichen/TZImagePickerController#313]
代码如下

  TZImagePickerController *imagePicker = [[TZImagePickerController alloc] initWithMaxImagesCount:6 delegate:self];
    imagePicker.selectedAssets = self.assets;
    imagePicker.photoWidth = 640;
    [self presentViewController:imagePicker animated:YES completion:nil];

是需要做什么配置嘛

**Comment by banchichen** [comment]
崩溃时的控制器输入看一下~  要根据具体的错误信息才好分析呢...

**Comment by zuijiejieshen** [comment]
什么意思，就是一普通控制器，继承uiviewcontroller，崩溃时也不报错，什么信息都没有，就莫名其妙的崩了

**Comment by banchichen** [comment]
打错字了~  崩溃的时候 控制台 没有输出任何日志吗？不可能的吧....    
可以在参考下Demo中info.plist的配置，看看是否缺少了获取相册权限的配置吧...

**Comment by zuijiejieshen** [comment]
真没有，有的话我自己就能调了，什么信息都没有。

**Comment by banchichen** [comment]
好吧... 抱歉，没有崩溃日志的话我也提供不了可行的解决方案...

**Comment by zuijiejieshen** [comment]
TZImagePickerController.m  337行，崩溃
