### ISSUE TITLE
有icloud照片时能够多次点击done按钮，造成多次调用didFinishPickingPhotosHandle

### ISSUE THREAD

**Issue by kirayamato1989** [banchichen/TZImagePickerController#314]

**Comment by banchichen** [comment]
不会吧...我试了多次没有重现...

**Comment by kirayamato1989** [comment]
我看了下源码，发现你这hud是一个button但是它的frame并没有指定，所以拦截不到它frame外的点击事件（这个完成按钮当然也就是可以点击的）

**Comment by banchichen** [comment]
我这里的HUD确实没有拦截frame外的事件的...
不过如果iCloud照片正在同步的话，done按钮被点击是会弹出警告框提醒用户等待同步完成的。
等同步完成后，用户再点done按钮，才会触发didFinishPickingPhotosHandle的调用。所以和iCloud图片无关哈。

所以done按钮瞬间被点击多次，会出现这种情况哈。

这种情况我觉得也没必要避免，微信支付宝等国民级应用也会有这种问题，比如某个跳转按钮瞬间被点击多次，控制器也会跳转多个...
