### ISSUE TITLE
[[NSUserDefaults standardUserDefaults] setObject:allowPickingImageStr forKey:@"tz_allowPickingImage"]崩溃

### ISSUE THREAD

**Issue by zuijiejieshen** [banchichen/TZImagePickerController#316]
[[NSUserDefaults standardUserDefaults] setObject:allowPickingImageStr forKey:@"tz_allowPickingImage"];

**Comment by banchichen** [comment]
这句代码无非是把字符串 0 或者 1 存到偏好设置里，为什么会崩溃呢？ 代码执行到这一行的时候，allowPickingImageStr是有值的吧？

**Comment by zuijiejieshen** [comment]
有值，没有任何问题，但事实就是崩了

**Comment by banchichen** [comment]
抱歉，根据现有的信息无法分析，如果方便可以发送代码到 tanzhenios@foxmail.com，我看看能不能找到更多线索。

**Comment by rushairer** [comment]
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
`
里加上

`    [[NSUserDefaults standardUserDefaults] addSuiteNamed:@"Your bundle identifier"];
`

**Comment by banchichen** [comment]
刚刚提交了代码：https://github.com/banchichen/TZImagePickerController/commit/9fc4eb9ccb1afc50a1e825b9de19dc7ea382fa2b

新增了`TZImagePickerConfig`类，用`TZImagePickerConfig`类的单例对象来存储allowPickingImage和allowPickingVideo的值，避免了NSUserDefaults的使用，也提高了性能...

随着下版发布~
