### ISSUE TITLE
列表顶部多出来64高度

### ISSUE THREAD

**Issue by 3990995** [banchichen/TZImagePickerController#318]
我的导航是不透明都黑色的，弹出你都就如下图
![img_0185](https://cloud.githubusercontent.com/assets/1081005/21385021/d68e89a0-c7a7-11e6-9150-c438817107cc.PNG)
![img_0186](https://cloud.githubusercontent.com/assets/1081005/21385022/d690d098-c7a7-11e6-90a3-5c1f31e2f222.PNG)

**Comment by lulee007** [comment]
@3990995 可能你设置了`imagePickerVc.navigationBar.isTranslucent = true`，不要设置为`true`，
尝试使用
`imagePickerVc.navigationBar.setBackgroundImage(UIImage.imageWithColor(xxxx), for: .default)`
来代替
`imagePickerVc.navigationBar.barTintColor = UIColor(xxx)`，
同样能达到设置效果。

**Comment by CDYeah** [comment]
遇到了同样的问题，swift 3.1 ios8以上， @lulee007 你的这个方法没有起作用， @3990995 这个问题你解决了么？

**Comment by 3990995** [comment]
thk

**Comment by banchichen** [comment]
还可以参考下这个PR，是解决这个bug的，在2017年1月就已经merge了哈
  https://github.com/banchichen/TZImagePickerController/pull/321
