### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by wigl** [banchichen/TZImagePickerController#32]
**TZImageManager.m文件**

    /// Get photo bytes 获得一组照片的大小
    - (void)getPhotosBytesWithArray:(NSArray *)photos completion:(void (^)(NSString *totalBytes))completion {
    __block NSInteger dataLength = 0;
    for (NSInteger i = 0; i < photos.count; i++) {
        TZAssetModel *model = photos[i];
        if ([model.asset isKindOfClass:[PHAsset class]]) {
            [[PHImageManager defaultManager] requestImageDataForAsset:model.asset options:nil resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
                if (model.type != TZAssetModelMediaTypeVideo) dataLength += imageData.length;
                if (i >= photos.count - 1) {
                    NSString *bytes = [self getBytesFromDataLength:dataLength];
                    if (completion) completion(bytes);
                }
            }];
        } else if ([model.asset isKindOfClass:[ALAsset class]]) {
            ALAssetRepresentation *representation = [model.asset defaultRepresentation];
            if (model.type != TZAssetModelMediaTypeVideo) dataLength += (NSInteger)representation.size;
            if (i >= photos.count - 1) {
                NSString *bytes = [self getBytesFromDataLength:dataLength];
                if (completion) completion(bytes);
            }
        }
    }
    }

这样写有问题，由于requestImageDataForAsset默认是异步调用，当选择多张图片的时候，我们无法判断哪个请求先完成，假如选了5张图片，第五张求完成了，但是可能第一张请求还未完成，所以得到的照片大小和出错。
你可以采用手动开子线程，然后同步调用requestImageDataForAsset，比如：

    + (void)requestImageDataForAsset:(NSArray<PHAsset *>*)assets resultHandle:(void(^)(NSString * length))resultHandler{
     __block NSInteger totleLength = 0;
    //采用组队列，判断请求是否全部完成
    dispatch_group_t group = dispatch_group_create();
    dispatch_group_async(group, dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        PHImageRequestOptions *options = [[PHImageRequestOptions alloc] init];
        options.synchronous = YES;
        for (int i = 0 ;  i < assets.count; i++) {
            [[PHImageManager defaultManager] requestImageDataForAsset:assets[i] options:options resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
                totleLength += imageData.length;
            }];
        }
    });
    dispatch_group_notify(group, dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        NSString *bytes;
        if (totleLength >= 0.1 * (1024 * 1024)) {
            bytes = [NSString stringWithFormat:@"%0.1fM",totleLength/1024/1024.0];
        } else if (totleLength >= 1024) {
            bytes = [NSString stringWithFormat:@"%0.0fK",totleLength/1024.0];
        } else {
            bytes = [NSString stringWithFormat:@"%zdB",totleLength];
        }
        //回到主线程刷新页面
        dispatch_async(dispatch_get_main_queue(), ^{
            resultHandler(bytes);
        });
    });
    }

**Comment by banchichen** [comment]
你好，谢谢指出，不过这个问题已经解决了的~请看最新的代码~

**Comment by wigl** [comment]
你的解决方式好棒，涨知识了，感谢！
