### ISSUE TITLE
在系统语言为俄文时获取不到相册

### ISSUE THREAD

**Issue by ChenjbQAQ** [banchichen/TZImagePickerController#323]
![image](https://cloud.githubusercontent.com/assets/18003460/21465222/a4f4dd3e-c9d4-11e6-8b23-4916d2ab6382.png)
返回的相册名字是俄文，导致获取不到相册

**Comment by stelalae** [comment]
因为作者目前只兼容了中英文环境，对相册名称写死了的，所以在除中英文外的语言环境中对相册判断会出现问题。我更新代码做了对其他语言环境的兼容，但仅限于iOS8及以后。@ChenjbQAQ

**Comment by ChenjbQAQ** [comment]
谢谢你的回答~
