### ISSUE TITLE
相册中超长图片的时候  会崩溃

### ISSUE THREAD

**Issue by xcvzaq** [banchichen/TZImagePickerController#325]
当图片像素高度接近65535的时候 会崩溃

         // 修复获取图片时出现的瞬间内存过高问题
        // 下面两行代码，来自hsjcom，他的github是：https://github.com/hsjcom 表示感谢
        PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
        option.resizeMode = PHImageRequestOptionsResizeModeFast;

虽然有上面的代码 仍然会崩溃。

我暂时的做法 是把 PHImageContentModeAspectFill 改成PHImageContentModeAspectFit，这样有个问题就是得不到清晰的缩略图。

通过 PHImageRequestID imageRequestID = [[PHImageManager defaultManager] requestImageForAsset:asset targetSize:imageSize contentMode:PHImageContentModeAspectFit options:option resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info) {}

得到的image  传给UIImageView 然后  通过
 [self.view.layer renderInContext:UIGraphicsGetCurrentContext()]; 来做截图 这个方法之后 内存不会回收。（再次调用相册，选择新图片，然后确认，内存回收。。这个太奇怪了）

如果image 是别的方式获得 比如imageNamed  就没有问题。

通过 requestImageDataForAsset 得到imageData 转image 然后截图，内存也没有问题

**Comment by banchichen** [comment]
超长图估计让内存爆了，我这找了若干长图，暂时未能复现这个崩溃...
不过我看微信和微博对超高图片做了优化，如果图片过高，会限制获取图片的大小，使得超高图片有些模糊，但是防止了图片过大导致的内存暴增...
我这次也参考微信做了类似处理哈...

代码已经提交，会随着这次发布哈~
