### ISSUE TITLE
[UIApplication sharedApplication]优化

### ISSUE THREAD

**Issue by GreedBell** [banchichen/TZImagePickerController#33]
建议` [UIApplication sharedApplication] `相关的全局变量，在`viewWillAppear`的时候设置并备份原始的配置，`viewDidDisappear`的时候还原

**Comment by GreedBell** [comment]
还有默认的`UIStatusBarStyleLightContent`不支持iOS6

**Comment by banchichen** [comment]
你好，谢谢指出，修正了~
