### ISSUE TITLE
iPad横屏效果不是很理想  

### ISSUE THREAD

**Issue by QuanWeiErTong** [banchichen/TZImagePickerController#331]
1、iOS10 iPad Air  横屏时右边部分空白
2、当图片超过1屏时，最后几行的图片看不到

<img width="1025" alt="2016-12-29 2 22 27" src="https://cloud.githubusercontent.com/assets/8746311/21538028/7153002a-cdd3-11e6-92a1-ae13566f6858.png">

**Comment by MysteryRan** [comment]
iPad横屏下怎么使得TZImagePicker横屏显示
