### ISSUE TITLE
请教一下，为什么相机拍照的图片没裁剪，而从相册选择的图片有裁剪？

### ISSUE THREAD

**Issue by easongtd** [banchichen/TZImagePickerController#333]
请教一下，为什么相机拍照的图片没裁剪，而从相册选择的图片是按828*600裁剪的？如果拍照的图片了也按828*600裁剪要怎么改？
急，在线等〜〜〜

**Comment by easongtd** [comment]
打错了，是默认按828 * 600宽高比例裁剪，而不是新版本中弹出编辑裁剪窗口由用户裁剪。

**Comment by banchichen** [comment]
你好，你可能下的不是最新版，最新的Demo里，相机拍摄的也会去裁剪页面的~

**Comment by easongtd** [comment]
我刚才下过新版demo看过了，你是相机拍摄好后会跳转到裁剪页面，而我的意思是像以前从相册选择照片一样，选择好就不要跳裁剪页面了，就像以前那样默认按828 * 600的比例去缩小。我之前用的版本好像是1.6.9－1.7.1不确定是哪个。

**Comment by banchichen** [comment]
啊哈，如果不要裁剪的话，把allowCrop设置为NO就行了...如果设置了allowCrop为NO的话，是会直接返回大图，不去裁剪页面的~

**Comment by easongtd** [comment]
那把allowCrop设置为NO的话，图片会按828 * 600的比例去缩小吗？

**Comment by banchichen** [comment]
会按照photoWidth设置的宽度值去缩放，默认是828像素宽，高度不定死是600的，会保持图片的原有宽高比。

**Comment by easongtd** [comment]
好的，谢谢，兄弟回答好神速，赞一个。 还有一个问题是，你现在的1.7.8和我之前的1.7.1代码变化大吗？ 不大的话我想自己根据代码手工复制粘贴更新一下。因为我对你原来的代码有改动。 或者说我如果只更新这个allowCrop裁剪功能的话，是不是只用更新一部分代码就可以了。
