### ISSUE TITLE
选择照片的时候，如果maxImageCount为1，无法出现右上角的小勾

### ISSUE THREAD

**Issue by seasonZhu** [banchichen/TZImagePickerController#336]
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:1 delegate:self];

这个时候进入相片选择器，没有出现右上角的小勾，需要这边添加一个判断，感谢。

**Comment by banchichen** [comment]
你好，请参考TZImagePickerController的h文件105行，把showSelectBtn设置为YES应该就是你想要的了~

/// Single selection mode, valid when maxImagesCount = 1
/// 单选模式,maxImagesCount为1时才生效
@property (nonatomic, assign) BOOL showSelectBtn;   ///< 在单选模式下，照片列表页中，显示选择按钮,默认为NO

**Comment by seasonZhu** [comment]
不好意思，最近忙着改代码，刚刚上来才看见，通过你所说的，问题已经解决了，感谢！
