### ISSUE TITLE
图片路径在哪里获取呢？

### ISSUE THREAD

**Issue by wlxj1992** [banchichen/TZImagePickerController#338]
[imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets) 
中assets我这打印出来的信息都是只有1，那图片名称，路径在哪里获取呢？

**Comment by maple1994** [comment]
你要换一个block，要使用带info字样的block，你打印里面的字典，就可以看到路径了。
@property (nonatomic, copy) void (^didFinishPickingPhotosWithInfosHandle)(NSArray<UIImage *> *photos,NSArray *assets,BOOL isSelectOriginalPhoto,NSArray<NSDictionary *> *infos);

另外提醒一句，只能在模拟器上才能获取到图片的路径，真机是获取不了的！所以并不建议你使用图片路径来获得图片。
我的做法是

1. 通过PHAsset --> 获得asset的localIdentifier唯一标示，保存
2. localIdentifier --> PHAsset
3. PHAsset --> 转图片 （通过PHImageManager获得）

你可以参考我的一篇博客，不过只实现了1、2步
http://blog.csdn.net/bloody_leaves/article/details/53282030

**Comment by wlxj1992** [comment]
好的，因为我现在是要做一个把图片上传到腾讯云COS上，需要带有图片路径，所以一直在研究，你写的博客我先看看，不懂再请教你哈

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/374
