### ISSUE TITLE
请教问题,非bug

### ISSUE THREAD

**Issue by xiaochenyi** [banchichen/TZImagePickerController#34]
请教一下, 怎么能和系统相册一样,按照时间顺序进行排列?

**Comment by banchichen** [comment]
那种效果不是很好实现。用每个照片的创建时间来分组，处理成许许多多的小数组，再分组展示出来。搜索：iOS相册 moment，看几个这样的博客吧。

**Comment by xiaochenyi** [comment]
发现此框架是按照创建时间排序的,系统相册反而不是按照创建时间进行排序的,很好奇系统的相册的排序规则是怎么样的.
