### ISSUE TITLE
怎么提前放几张sdimage下载的图片 要做成编辑的功能

### ISSUE THREAD

**Issue by coderykw** [banchichen/TZImagePickerController#340]
求助

**Comment by ios582754** [comment]
这个问题你解决了吗

**Comment by chenYuCui** [comment]
你这是要提前放几张网络请求的照片，框架不支持的

**Comment by chenYuCui** [comment]
我也是碰到了这个问题，框架本身必须从自身设备上传图片

**Comment by 1284115201** [comment]
我也有这个需求，你们现在解决了么？

**Comment by suyongmaozhao** [comment]
可以把图片临时保存到相册 。然后就可以读取出来 asset了 。

**Comment by banchichen** [comment]
Hi，3.0.1版本已支持，需新接一个插件库：[TZImagePreviewController](https://github.com/banchichen/TZImagePreviewController)，请参考TZImagePreviewController里面的Demo使用。

抱歉久等了...
