### ISSUE TITLE
1.7.8版本，本地化语言有问题

### ISSUE THREAD

**Issue by githubLittleCode** [banchichen/TZImagePickerController#342]
TZImagePickerController.m文件 121行调用 [self configDefaultSetting]方法，里面调用的[self configDefaultBtnTitle]方法明明有调用[NSBundle tz_localizedStringForKey]这个方法，可是在NSBundle+TZImagePicker.m文件里tz_localizedStringForKey这个方法打了断点并没有被调用

**Comment by banchichen** [comment]
你好，方法走了打了断点却没执行，可能是打了断点后你对代码做了改动，导致断点记录的位置不准了。建议把断点全部去除，再重新加一次。

**Comment by zhangjingjingWoman** [comment]
你好，按照你说的方法还是会出现这种情况。我同事cocoapods的时候pod TZImagePicker 1.7.1版本，那个版本是没问题的，可是我的是TZImagePicker 1.7.8的版本的，不知道是不是和这个有关系

**Comment by banchichen** [comment]
啊哈，1.7.1 - 1.7.8的变动倒没涉及到国际化这一块，我刚刚在模拟器上测试了，国际化的功能没影响哈。我也打了断点试了下，tz_localizedStringForKey方法是有走的....  
还有一点需要注意的是NSBundle *bundle是用static修饰的，只会在第一次调的时候bundle为nil才去获取bundle的路径，此后bundle都不是nil了的，看你的断点是不是打的位置不是很合适。。。

**Comment by zhangjingjingWoman** [comment]
我重新pod了，没有修改过你的代码。我这边tz_localizedStringForKey还是不会走，所以即使手机系统语言改成英文了按钮标题还是显示中文。可是我同事的1.7.1版本的就会走，语言本地化化是正常的。

**Comment by banchichen** [comment]
好吧~ 请问那在你的设备上我的Demo国际化有问题吗~？

**Comment by zhangjingjingWoman** [comment]
而且我刚刚试了一下，1.7.1版本的tz_localizedStringForKey方法是会走的。

**Comment by zhangjingjingWoman** [comment]
那个没有问题。刚刚测试了一下， 我不通过cocoapods集成你的控件，直接把文件包拉到工程里面1.7.8版本是正常的，可是通过cocoapods pod下来的就不行了。现在就直接不通过cocoapods集成了，谢谢你的解答

**Comment by banchichen** [comment]
谢谢你的详细反馈，我稍后详细测试下~

**Comment by rushairer** [comment]
cocoapods下编译了framework对NSUserDefault操作可能是有权限限制了


试试
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
`
里面加个
`    [[NSUserDefaults standardUserDefaults] addSuiteNamed:@"Your bundle identifier"];
`

**Comment by banchichen** [comment]
你好，刚刚发布了1.8.7版本，这个问题应该好了~

如果还有问题，请再回来评论下~
