### ISSUE TITLE
通过asset获取原图，建议加一个同步参数，系统默认的是异步

### ISSUE THREAD

**Issue by OYForever** [banchichen/TZImagePickerController#344]
通过asset获取原图，建议加一个同步参数，系统默认的是异步

**Comment by banchichen** [comment]
你好，同步的话风险很大吧，如果图片存储在iCloud，用户网络较弱的话，整个APP就像死了一样...

**Comment by OYForever** [comment]
参数可选嘛。。我遇到的情况是要同步取图片。。  自由选择是否异步扩展性好点吧。。

发自我的 iPhone

**Comment by banchichen** [comment]
那个...这个需求比较过于个性化，做支持的优先级很低哈...😂

**Comment by OYForever** [comment]
没事，我就建议一下😂
，我自己在里面改了下😂
发自我的 iPhone
