### ISSUE TITLE
超宽图片显示模糊

### ISSUE THREAD

**Issue by Weever** [banchichen/TZImagePickerController#345]
图片超宽，选择图片预览的时候，图片是很模糊的，选择该图片后，回调的图也是模糊的
预览时，滑动到超长超宽的图片是，会卡顿后才显示

超长图在9.3系统下会崩溃

**Comment by banchichen** [comment]
之前选择全景照片的体验确实好差...
比较模糊、最大放大比只有2.5不够填满Y轴....

代码已经提交了，参照目前微信的体验优化了下这里~
清晰度提高了，最大可放大比提高了~
会随着这次发版发布哈~
久等了...😊

超长图估计让内存爆了，我这找了若干长图，暂时未能复现这个崩溃...
不过我看微信对超高图片也做了优化，如果图片过高，会限制获取图片的大小，使得超高图片有些模糊，但是防止了图片过大导致的内存暴增...
我这次也参考微信做了类似处理哈...
