### ISSUE TITLE
拍照保存图片，希望保存地理位置信息

### ISSUE THREAD

**Issue by chengyinglpl** [banchichen/TZImagePickerController#346]
Demo里面，在多图选择中，调用相机拍照，然后保存至相册，等待保存完成后，选择所拍的这张图片，获取所选图片的坐标，坐标为0

 [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
        for (PHAsset *asset in assets) {
            CLLocation *location = asset.location;
            CLLocationCoordinate2D coo = location.coordinate;
            NSLog(@"%f---%f",coo.latitude,coo.longitude);
        }
    }];

**Comment by JimmyLession** [comment]
升序和倒序后拍照完成取图片，取错了。。。 系统 ios 10.2，我也是在大神的demo中运行发现的。

**Comment by banchichen** [comment]
Hi, 久等了...😊
刚刚提交了代码，已经可以保存位置信息了~会随着这次发版发布~
