### ISSUE TITLE
用swift3.0调用右上角没有选中图片按钮，，OC下是正常的

### ISSUE THREAD

**Issue by zwlnihao** [banchichen/TZImagePickerController#348]
![snip20170112_4](https://cloud.githubusercontent.com/assets/17020586/21878125/fbf13d76-d8ca-11e6-89f9-29055b1c1971.png)

**Comment by banchichen** [comment]
我用最新的Xcode8.3版本，swift3.0的环境弄了一个Demo，用pod方式集成本库，界面正常，没有出现你这个情况...
是不是把maxImagesCount设置为了1导致的？

**Comment by codwam** [comment]
如果没有设置 maxImagesCount 或者 等于1，就没有那个选择的了。

另外我觉得拍照可以直接集成在里面，回调的话还是用TZ的代理会方便很多。
