### ISSUE TITLE
Gif controller和video controller中，当autoDismiss设置为NO时，还是会自动dismiss

### ISSUE THREAD

**Issue by baoyang2000** [banchichen/TZImagePickerController#349]
目前的逻辑：

> if (self.navigationController) {
>         if (imagePickerVc.autoDismiss) {
>             [self.navigationController dismissViewControllerAnimated:YES completion:^{
>                 [self callDelegateMethod];
>             }];
>         }
>     } else {
>         [self dismissViewControllerAnimated:YES completion:^{
>             [self callDelegateMethod];
>         }];
>     }

应该的逻辑：

> if (imagePickerVc.autoDismiss) {
>         if (self.navigationController) {
>             [self.navigationController dismissViewControllerAnimated:YES completion:^{
>                 [self callDelegateMethod];
>             }];
>         } else {
>             [self dismissViewControllerAnimated:YES completion:^{
>                 [self callDelegateMethod];
>             }];
>         }
>     } else {
>         [self callDelegateMethod];
>     }

**Comment by baoyang2000** [comment]
上述代码位于各自的doneButtonClick方法中

**Comment by banchichen** [comment]
你好，在TZImagePickerController导航控制器栈中的GIF与视频预览控制器，autoDismiss的设置是生效的。
你说的情况是单独使用GIF与视频预览控制器的时候，此时imagePickerVc都是nil, 已经不存在autoDismiss的设置了...
