### ISSUE TITLE
选取原图有点问题

### ISSUE THREAD

**Issue by Alamoalone** [banchichen/TZImagePickerController#35]
点击选取原图，但我去看大小的时候，没变化，是不是只点击原图只看得到原图大小，而拿到的还是编辑过的图，希望能看到并回复我一下

**Comment by banchichen** [comment]
你好，请看TZImagePickerController的头文件，每个公共方法都写清楚注释的。直接给你原图，内存会爆的，获取原图的方法，请参考TZImageManager的头文件，给我asset，我再给你原图。
