### ISSUE TITLE
关于图片选择上限的问题

### ISSUE THREAD

**Issue by q32784307** [banchichen/TZImagePickerController#350]
大神你好，刚刚看看了demo，有个小bug，希望你优化一下，比如我设置了最多选择5张，然后我选择了5张，这样的话，我选择第6张的时候，会提示。但是当我打开相机，去拍照之后直接使用，这个第6张照片还是会被选中，所以导致最大可选张数是5，实际选择的张数是6。还有就是，当我全部都用拍照来选择照片的时候，这个最大可选张数的限制也是无效了

**Comment by q32784307** [comment]
我觉得，是不是当照片数量达到最大可选张数的时候，拍照的按钮选项直接隐藏呢？或者有更好的优化方法？

**Comment by q32784307** [comment]
我是这样做的，虽然不太友好，就是当照片数量达到最大可选张数的时候，拍照的按钮选项直接隐藏，点击加号直接进入相册，然后在相册里如果想添加的话就会提示最大数了
在didSelectItemAtIndexPath方法里

if (_selectedPhotos.count == self.maxCountTF.text.integerValue) {
            [self pushImagePickerController];
        }else{
            if (showSheet) {
                UIActionSheet *sheet = [[UIActionSheet alloc] initWithTitle:nil delegate:self cancelButtonTitle:@"取消" destructiveButtonTitle:nil otherButtonTitles:@"拍照",@"去相册选择", nil];
                [sheet showInView:self.view];
            } else {
                [self pushImagePickerController];
            }
        }

**Comment by banchichen** [comment]
你好，选择器内部的拍照是做了限制的，超出张数限制的新拍照片不会被自动选中。但是外面的测试Demo是没做限制的，如果要做限制的话，直接把+号图标隐藏最好，微信也是这样做的...
