### ISSUE TITLE
會有內存洩漏問題。

### ISSUE THREAD

**Issue by KgarooRoey** [banchichen/TZImagePickerController#354]

**Comment by FighterJixes** [comment]
你指的是打开“TZPhotoPickerController”这个控制器的时候吗？我发现每打开一次这个界面内存增加1MB左右，退出该控制器后那些增加的内存并没有被销毁，用instrument查看并不存在内存泄漏，可这些内存就是没被释放。同时发现“TZPhotoPickerController”不走delloc。 @KgarooRoey

**Comment by rushairer** [comment]
Demo的内存会一直涨。
每次打开图片库页面会卡顿
