### ISSUE TITLE
自定义UI

### ISSUE THREAD

**Issue by gaojlieMan** [banchichen/TZImagePickerController#356]
进入相册选择照片，上面的导航栏，不能自我定义 UI样式属性，好多都是定义死的,许多属性你那边定义了私有方法，有事需要需改里面的UI东西，不好更改

**Comment by banchichen** [comment]
你好，比如是什么属性呢？ 你可以拿到导航栏控制器，那就可以拿到导航栏本身，你在外面是可以直接设置的....

**Comment by gaojlieMan** [comment]
能拿到导航栏？我想更换选中图片的，上面的“对号”图片，，还有导航栏的样式
，我创建一个类集成你创建的类，然后发现你里面的属性，是私有的外面继承了，也改不了，只能kvc，比较麻烦  怎么能拿到相册中的导航栏，我要更改他的样式，是你忘记写接口了吧，谢谢你的回信

**Comment by gaojlieMan** [comment]
我要更改他在选择图片的界面上面导航栏的 leftBarbuttonitem 按钮图片 以及点击这个按钮的点击事件，都是私有的方法，外面取不到，有什么接口，拿到相应界面的导航栏吗？

**Comment by banchichen** [comment]
可以重新set，覆盖我的默认设置。

**Comment by gaojlieMan** [comment]
但是，你的一些属性 我访问不到，如果能把说有的属性 改成公有的 这样你写的框架 肯定能更好被认可，我只是建议

**Comment by banchichen** [comment]
好的，谢谢你的建议，后期的版本中我会考虑进去~

**Comment by banchichen** [comment]
要改变库里用到的图片，可以留意下这些属性：
@property (nonatomic, copy) NSString *takePictureImageName;
@property (nonatomic, copy) NSString *photoSelImageName;
@property (nonatomic, copy) NSString *photoDefImageName;
@property (nonatomic, copy) NSString *photoOriginSelImageName;
@property (nonatomic, copy) NSString *photoOriginDefImageName;
@property (nonatomic, copy) NSString *photoPreviewOriginDefImageName;
@property (nonatomic, copy) NSString *photoNumberIconImageName;

**Comment by gaojlieMan** [comment]
好的谢了，我再研究看看

**Comment by rushairer** [comment]
写了个Category  把调起相机方法重写了

**Comment by gaojlieMan** [comment]
请问你的写了个Category 把调起相机方法重写了  Category 的名称是什么 下载下来没有找到

**Comment by gaojlieMan** [comment]
急用，求回复

**Comment by banchichen** [comment]
@rushairer   Hi,有gaojlieMan 小伙伴找你哈...

**Comment by banchichen** [comment]
@gaojlieMan  这个category，rushairer没有给我提PR的，因此在这个项目github主页下载的代码里，没有这个category的，你需要找rushairer单独分享给你...

**Comment by gaojlieMan** [comment]
你直接加我QQ 401633128 或者发我邮箱分享给我 我的QQ邮箱401633128@qq.com,谢谢

**Comment by yslyii** [comment]
是的，很多东西写的太死了，好多UI多改不动，比如底部栏configBottomToolBar这个样式。

**Comment by banchichen** [comment]
Hi，新版2.1.4发布了哈，支持了绝大多数界面和组件的样式定制，详细内容请参见：https://github.com/banchichen/TZImagePickerController/issues/787
