### ISSUE TITLE
ipad mini2 IOS10.1不可用，选择相册，相机都没什么反应

### ISSUE THREAD

**Issue by EarthMass** [banchichen/TZImagePickerController#358]
ipad mini2 IOS10.1 不可以，选择相册，相机都没什么反应
plist中添加过了，权限也选择过了,使用的是1.7
iphone上使用正常，使用起来非常棒，非常感谢
期待大牛的回复

**Comment by change6** [comment]
您好,现在这个库支持ipad吗？

**Comment by TuDoudong** [comment]
同样的问题，希望得到解决

**Comment by TuDoudong** [comment]
dispatch_async(dispatch_get_main_queue(), ^{
});
兄弟你重开一个异步主队列 在这里面执行就OK了，开启一个新的runloop 处理
http://www.cnblogs.com/Rinpe/p/5669903.html

**Comment by banchichen** [comment]
找了个iPad真机试了下，倒没问题...

**Comment by banchichen** [comment]
@TuDoudong @EarthMass 应该和这个是一个问题，已修复：https://github.com/banchichen/TZImagePickerController/issues/941

是把拍照按钮放在外面的时候会这样...控制台有打印的...这里没说清楚，当时试了没能复现...
