### ISSUE TITLE
对启动速度的优化建议

### ISSUE THREAD

**Issue by rushairer** [banchichen/TZImagePickerController#360]
现在是启动TZImagePickerController的时候，把所有相册数据加载进来，会有个约1秒的延迟。
所以启动TZImagePickerController的时候，用户体验会差些。

如果改成每次加载TZPhotoPickerController的时候loading动画，现加载对应的albums，这样体验上会快一些吧。

**Comment by banchichen** [comment]
很好的建议~~~ 微信也是这样做的~  我后续会考虑加入~~~

**Comment by rushairer** [comment]
现在的问题就是smartAlbums不能直接拿到照片数，必须 PHFetchResult 里count一次。
如果  先 option.fetchLimit = 1; 取fetchResult为一张图片，这样往albumArr插数据的时候会快很多。
然后再 
```
option.fetchLimit = 0;                
 PHFetchResult *fetchResultForCount = [PHAsset fetchAssetsInAssetCollection:collection options:option];


```
再改一下modelWithResult方法里的count逻辑。


这样虽然取了两次  PHFetchResult，但是速度却快了。内存占用也少了大概2M。
我估计性能损耗是在 albumArr 里存数据的时候。

**Comment by banchichen** [comment]
@rushairer 👍 Hi，我尝试了下初次启动时限制fetchLimit，耗时确实有减少哈，不过在我这只有不到10ms。我用Time profiler看了下耗时情况，优化了一个主线程耗时70ms的操作（获取所有照片），启动速度应该提升了不少~

可以升级到2.0.0.3试试哈。

https://github.com/banchichen/TZImagePickerController/issues/632

**Comment by saltcoffee** [comment]
@banchichen hi, 大佬，这个fetchLimit初次启动该怎么限制，我发现照片上万张后，还是会有一点慢。

**Comment by banchichen** [comment]
@saltcoffee 代码里搜素PHFetchOptions哈
