### ISSUE TITLE
能否添加一个默认值 选择默认进入 AlbumPickerController 或者 PhotoPickerController之类的

### ISSUE THREAD

**Issue by FocusLyn** [banchichen/TZImagePickerController#361]
能否添加一个默认值 选择默认进入 AlbumPickerController 或者 PhotoPickerController之类的

**Comment by banchichen** [comment]
好，可以的~  我有空的时候加上~~~

**Comment by banchichen** [comment]
咦~  我发现我加上了的.....   你看看TZImagePickerController类h文件的这个方法~ - (instancetype)initWithMaxImagesCount:(NSInteger)maxImagesCount columnNumber:(NSInteger)columnNumber delegate:(id<TZImagePickerControllerDelegate>)delegate pushPhotoPickerVc:(BOOL)pushPhotoPickerVc;
其中pushPhotoPickerVc传NO，就会是在AlbumPickerController页面~

**Comment by FocusLyn** [comment]
谢谢，我也看到了。非常感谢
