### ISSUE TITLE
iOS10以后调用系统相机拍照后会出现黑屏

### ISSUE THREAD

**Issue by qyfeng009** [banchichen/TZImagePickerController#363]
此时照片是真是存在的，只是在完成拍照后不显示照片而是整个黑色。
这是由于StatusBar冲突导致的，可以参考http://www.jianshu.com/p/d736dc82ae0f

我是在界面push之前设置[[UIApplicationsharedApplication]setStatusBarHidden:YES];
然后在viewWillAppear设置[[UIApplication sharedApplication] setStatusBarHidden:NO];解决的

**Comment by banchichen** [comment]
你好，复现不了这个问题噢...

**Comment by qyfeng009** [comment]
你好，我在审查代码时发现，引起这个问题的原因是在相册外部调用相机时调用的是自写的代码块，和这个库没有直接关系。不好意思当时没有审查仔细

**Comment by banchichen** [comment]
没事~赞👍
