### ISSUE TITLE
只读取部分相册

### ISSUE THREAD

**Issue by quanxin** [banchichen/TZImagePickerController#364]
现在对于相册的读取似乎都是读取的photos中的全部相册，有没有考虑过支持只读取部分相册呢？比如筛除掉“最近添加”、“连拍”。
如果考虑支持的话，会怎么设计设置接口呢？

**Comment by banchichen** [comment]
你好，如果要做的话，我觉得可以新提供一个协议方法，读取相册的时候，通过协议方法来询问外界该相册是否需要显示...外界通过实现协议方法，来控制相册的显示与否...

**Comment by banchichen** [comment]
你好，刚刚发布了1.8.1版本，新增两个代理方法，isAlbumCanSelect:result:和isAssetCanSelect:，可由上层通过实现代理方法来决定某个相册/照片/视频显示与否。

可以参考最新的Demo，实现isAlbumCanSelect:result代理方法，返回NO则此相册不会显示哈。
[// 决定相册显示与否 albumName:相册名字 result:相册原始数据
- (BOOL)isAlbumCanSelect:(NSString *)albumName result:(id)result;](url)
