### ISSUE TITLE
关于圆形的剪裁

### ISSUE THREAD

**Issue by hanshuushi** [banchichen/TZImagePickerController#368]
一般来说圆形的剪裁出现的条件都是头像选取，但是头像选取往往都是在上传的时候，只是剪裁方形的图片，在本地下载的时候，才会通过圆角或者其他形式变成圆形的。希望作者可以提供一个在圆形剪裁的情况下，依旧剪裁方形图片的功能。

**Comment by lifengios** [comment]
裁剪完了，怎么获取啊

**Comment by SlowDony** [comment]
楼主关于圆形剪裁的情况下，依旧剪裁方形图片,您是怎么处理的

**Comment by SlowDony** [comment]
楼主我现在是这样处理的给TZImageCropManager写一个分类,然后用runtime把TZImageCropManager 类里的circularClipImage:方法进行修改,然后可以满足在选择圆形剪切框的同时并把图剪切成方形图片
