### ISSUE TITLE
关于裁剪

### ISSUE THREAD

**Issue by hegelsu** [banchichen/TZImagePickerController#371]
虽然设置了大小框，但能否在裁剪的过程按长宽比例放大或缩小，因为有时候图片小于要裁剪的大小。裁剪完成后，再能按原来的大小扩大保存，就更好了。

**Comment by lifengios** [comment]
选择裁剪的完了 不用 像系统 那样的 使用 那个 UIImagePickerControllerEditedImage  key 获取 图片的啊， 直接在 photos 数组 获取 就行了 ，挺好

**Comment by banchichen** [comment]
@lifengios  裁剪后的图片，也是在photos数组里，我Demo里显示是正常的...所以图片是有的，也在photos数组里，建议你找找其他原因...

**Comment by yanxin0905** [comment]
@banchichen demo没问题 pod的最新版不行

**Comment by banchichen** [comment]
@yanxin0905 你pod search一下，显示的最新版是1.8.9吗~？

如果不是的话，先pod setup一下，再search，出现1.8.9就代表能pod最新版了...

**Comment by zhouxubin** [comment]
选择完图片之后进入剪裁页面，scrollview滚动不到图片的最上面，但是scrollview的下边多出了一部分黑色的区域，请问楼主咋解决呀，有点急呢

**Comment by banchichen** [comment]
@zhouxubin 你好，我的Demo也会这样吗？如果不会的话，能否制作一个能复现你这个问题的Demo，我看下

**Comment by zhouxubin** [comment]
[Uploading bug视频.zip…]()

这个就是我这边工程里遇到的情况，以前也用没出过问题，现在这问题有点诡异啊

**Comment by banchichen** [comment]
@zhouxubin 视频好像没传好..

**Comment by zhouxubin** [comment]
[bug视频.zip](https://github.com/banchichen/TZImagePickerController/files/1565566/bug.zip)
不好意思啊，前几天没注意没上传成功，我刚刚重新传了，可以帮我看下是什么原因吗

**Comment by banchichen** [comment]
@zhouxubin 看了一下，应该是状态栏异常了哈，更新到1.9.7试试哈~  这里有状态栏异常的解释：https://github.com/banchichen/TZImagePickerController/issues/689

**Comment by zhouxubin** [comment]
我刚刚更细到最新版本了，但是那个问题还在就是选择完图片，进入剪裁页面的时候，图片会往上跳一下，然后图片不能滚动到白框边上

**Comment by banchichen** [comment]
@zhouxubin 比较奇怪....来个Demo吧~

**Comment by fanxingmao** [comment]
@zhouxubin @banchichen  我的情况是裁剪框会上移 选不不到最下边的   使用默认的裁剪大小又没有问题  好忧伤啊https://upload-images.jianshu.io/upload_images/2224932-027e55bfbc73239d.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240
