### ISSUE TITLE
imagePickerControllerDidCancel方法代理导致UIImagePickerControllerDelegate不可用

### ISSUE THREAD

**Issue by Arbalest313** [banchichen/TZImagePickerController#372]
原本的imagePickerControllerDidCancel方法代理导致在swift中：
UIImagePickerControllerDelegate的 imagePickerControllerDidCancel不可用。提示命名冲突，
希望作者`删除`这个协议方法而不是仅仅标志 `弃用`

**Comment by banchichen** [comment]
谢谢反馈，相关代码已删除，稍后提交...
