### ISSUE TITLE
技术问题

### ISSUE THREAD

**Issue by q32784307** [banchichen/TZImagePickerController#373]
大神，你能否抽空搞一篇关于照片多选的实现逻辑思路的文章呢？我一直想自己搞一下，但是找不到资料，而且，看了很多demo，无从下手...

**Comment by q32784307** [comment]
或者方便留个QQ么

**Comment by jsl328** [comment]
328468161

**Comment by banchichen** [comment]
啊...我觉得源码和Demo已经是最好的资料了...😂

**Comment by q32784307** [comment]
额...主要是0.0源码看不太懂....我这太渣了。。关于这种功能，先实现什么，后实现什么的...查了查，都看不太明白

**Comment by banchichen** [comment]
可以先实现界面，一共有相册列表页、照片列表页、照片预览页、视频预览页，主要是这几个页面，把这个几个页面搭建起来，不就基本差不多了么~

**Comment by q32784307** [comment]
方便加你QQ吗？有问题的话可以问问
