### ISSUE TITLE
内存泄漏问题，少量泄漏（instruments检测）

### ISSUE THREAD

**Issue by malonguwa** [banchichen/TZImagePickerController#375]
@banchichen  您好，在用Swift 3, Xcode 8.2.1 使用过程中，会有少量内存泄漏（instruments检测）,最为明显的是使用照片拍摄功能，在点击拍照的瞬间就有泄漏，还有我在多相册选则照片的时候也会有少量的泄漏（发生情况比较随机）。。。不知道是不是iOS10.2.1新多出来什么坑或者bug~ 望大大能够关注下~

**Comment by banchichen** [comment]
我用Leask跑了几次，发现每次进入相机页面，都会发生内存泄漏，泄漏对象是VTImageRotationSession。建了一个拍照的Demo，发现也是这样~
应该是系统的bug，我的系统也是10.2.1....

保持观察吧~

**Comment by banchichen** [comment]
其他地方的泄漏，我之前在项目里也碰到几次，MLeaksFinder检测是TZAssetCell泄漏，但是没有找到循环引用，泄漏的TZAssetCell个数也很少，原因暂时未知~

**Comment by zhouxl** [comment]
是不是跟单例模式下的block持有实例有关，单例的block如果持有了self，不会释放的
