### ISSUE TITLE
ios 8.4 图片多的情况下来回滑动崩溃

### ISSUE THREAD

**Issue by BestKai** [banchichen/TZImagePickerController#38]
在Ios8.4下图片大概三百多张，来回滑动，会收到内存警告，然后崩溃。

**Comment by caofeiiOS** [comment]
我也遇到这种情况了,请问您知道为什么我上传内存比较大的图片,会闪退,出现内存警告么

**Comment by Quxiaolei** [comment]
block强引用,相册对象不会释放,导致内存暴涨.小内存手机会崩溃.

**Comment by banchichen** [comment]
应该解决了吧~ 内存泄露是挺早就解决了的~ 但是来回滑动崩溃........ 检测不到....     后面这里做了优化的，这里的滑动帧数我设备上基本在55以上，新版这里应该好许多了~

**Comment by Quxiaolei** [comment]
我试一下.
另外还有个问题:首次允许访问相册时,相册不是立即加载出来的,而是要再次进入时才有.

**Comment by caofeiiOS** [comment]
作者是0.2s刷新表了,,,第一次获取权限后的确不会立马显示的
