### ISSUE TITLE
能支持网络图片吗？

### ISSUE THREAD

**Issue by hugolubingshen** [banchichen/TZImagePickerController#381]
如题，举个例子，我做个表单提交，提交了图片上去，然后可以修改这个表单，对已经提交上服务器的图片进行修改，这个情况下，TZImagePickerController能支持吗？要是可以，需要怎么实现

**Comment by banchichen** [comment]
目前不可以的，需要你去修改代码....

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/251
