### ISSUE TITLE
取消和完成调用self.navigationController dismissViewControllerAnimated的Bug

### ISSUE THREAD

**Issue by novawei** [banchichen/TZImagePickerController#39]
在presented的Controller中再次present TZImagePickerController,点击取消的时候会把上一级的也dismiss。
完成和取消没有必要调用self.navigationController dismissViewControllerAnimated吧

**Comment by banchichen** [comment]
你好，self.navigationController是我的TZImagePickerController（这是一个导航控制器），只是dismiss了图片选择器而已。按理说不会把你的也dismiss的。

**Comment by Weinova** [comment]
@banchichen 你的注释（// 这个照片选择器不会自己dismiss，用户dismiss这个选择器的时候，会走下面的回调）,不明白你为何要调用dismiss，是否跟注释矛盾呢？

> 你好，self.navigationController是我的TZImagePickerController（这是一个导航控制器），只是dismiss了图片选择器而已。按理说不会把你的也dismiss的。

如果我在presented controller上，再次present TZImagePickerController，如果你调用self.navigationController的dismiss，实际上就已经dismiss了TZImagePickerController，这样回调里就不能再调用dismiss了（导致实现跟系统的图片选择的回调处理不一样）

> The presenting view controller is responsible for dismissing the view controller it presented. If you call this method on the presented view controller itself, UIKit asks the presenting view controller to handle the dismissal.

请确认代码注释是否符合你代码实现设计

**Comment by banchichen** [comment]
抱歉，注释没有及时更新。找到问题了就好。
