### ISSUE TITLE
相机胶卷界面的返回按钮是英文的，设置了系统语言，还是back，好像本地化在这里失效了一样

### ISSUE THREAD

**Issue by TomYiCL** [banchichen/TZImagePickerController#391]
感谢作者，我拉入你的文件夹，实验简单功能，结果导航栏标题，按钮标题都显示不了，怎么回事

**Comment by kongtianxintang** [comment]
是不是直接初始化的 ？
我在swift3.0的直接TZImagePickerController()也是不显示按钮和标题及图片
后面换成作者提供的初始化方法就好了 `- (instancetype)initWithMaxImagesCount:(NSInteger)maxImagesCount delegate:(id<TZImagePickerControllerDelegate>)delegate;`

**Comment by TomYiCL** [comment]
我是直接初始化的，不显示的原因是没添加bundle文件，现在还有一个问题，就是相机胶卷界面的返回按钮是英文的，设置了系统语言，还是back，好像本地化在这里失效了一样，不知道什么原因，

**Comment by banchichen** [comment]
你好，应该是第一次是back，后面就好了吧？ 解决方案请参考这个issue
https://github.com/banchichen/TZImagePickerController/issues/443
