### ISSUE TITLE
iOS8.4 拍照获取照片，保存照片的时候，会崩溃

### ISSUE THREAD

**Issue by BoomZoe** [banchichen/TZImagePickerController#394]

**Comment by banchichen** [comment]
你好，为啥不把崩溃日志贴出来呢....

可以参考下这个issue，你们的问题比较像...https://github.com/banchichen/TZImagePickerController/issues/481
新的情况请在这个issue下评论哈。

对了，建议先升级下版本试试，中间有几个小版本中，iOS8-9下，使用的保存照片方法有问题，请升级下试试哈...
