### ISSUE TITLE
notify_register_dispatch() failed:

### ISSUE THREAD

**Issue by waitingfor168** [banchichen/TZImagePickerController#395]
notify_register_dispatch() failed: (0xf4240) ; (
	0   CoreFoundation                      0x000000018401e1d8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000182a5855c objc_exception_throw + 56
	2   CoreFoundation                      0x000000018401e094 <redacted> + 0
	3   Foundation                          0x0000000184aab79c <redacted> + 112
	4   PhotoLibraryServices                0x000000018ed536b0 <redacted> + 816
	5   PhotoLibraryServices                0x000000018ed4e580 <redacted> + 436
	6   PhotoLibraryServices                0x000000018ed4e3a0 <redacted> + 48
	7   AssetsLibraryServices               0x000000018e5a5cf4 <redacted> + 36
	8   libdispatch.dylib                   0x0000000182ea91c0 <redacted> + 16
	9   libdispatch.dylib                   0x0000000182ea9fb4 dispatch_once_f + 56
	10  AssetsLibraryServices               0x000000018e5a5ccc pl_dispatch_once + 88
	11  PhotoLibraryServices                0x000000018ed4e35c <redacted> + 72
	12  PhotoLibraryServices                0x000000018ed35408 <redacted> + 184
	13  PhotoLibraryServices                0x000000018ed30cec <redacted> + 636
	14  PhotoLibraryServices                0x000000018ed30964 <redacted> + 200
	15  PhotoLibraryServices                0x000000018ec93d30 <redacted> + 840
	16  PhotoLibraryServices                0x000000018ec89ab4 <redacted> + 560
	17  Photos                              0x000000018f81fcd8 <redacted> + 60
	18  libdispatch.dylib                   0x0000000182ea91c0 <redacted> + 16
	19  libdispatch.dylib                   0x0000000182ea9fb4 dispatch_once_f + 56
	20  Photos                              0x000000018f81fc94 <redacted> + 156
	21  Photos                              0x000000018f82092c <redacted> + 180
	22  Photos                              0x000000018f80a2e8 <redacted> + 356
	23  Photos                              0x000000018f80ccc4 <redacted> + 40
	24                               0x00000001001e1b5c __25+[TZImageManager manager]_block_invoke + 208
	25  libdispatch.dylib                   0x0000000182ea91c0 <redacted> + 16
	26  libdispatch.dylib                   0x0000000182ea9fb4 dispatch_once_f + 56
	27                               0x00000001001e1a88 +[TZImageManager manager] + 108
	28                               0x000000010022e780 -[TZImagePickerController viewDidLoad] + 284
	29  UIKit                               0x0000000189e780b0 <redacted> + 1056
	30  UIKit                               0x0000000189e77c78 <redacted> + 28
	31  UIKit                               0x0000000189f0a010 <redacted> + 640
	32  UIKit                               0x0000000189f09d40 <redacted> + 652
	33                               0x0000000100230eb4 -[TZImagePickerController pushViewController:animated:] + 248
	34  UIKit                               0x0000000189f6aa84 <redacted> + 144
	35                               0x000000010022eef8 -[TZImagePickerController initWithMaxImagesCount:columnNumber:delegate:pushPhotoPickerVc:] + 172

**Comment by banchichen** [comment]
应该是[TZImageManager manager]里初始化了cachingImageManager导致的...
新版已经注释了哈，建议换上新版~
