### ISSUE TITLE
框架很好用，但是关于矩形剪裁时有点小疑问，求解答

### ISSUE THREAD

**Issue by songxing10000** [banchichen/TZImagePickerController#398]
![snip20170316_1](https://cloud.githubusercontent.com/assets/10040131/23987162/266d02c8-0a63-11e7-8291-9cc961e2db05.png)

现有需求：

1、图片宽：高 ＞ 3：2     图片默认放大到 - 高-与裁剪框尺寸相同，图片无法缩小到比初始更小，可以放大
2、图片宽：高 ＜ 3：2     图片默认放大到 - 宽- 与裁剪框尺寸相同，图片无法缩小到比初始更小，可以放大

找了好久，都找不到正确的设置位置，求更改代码的位置

**Comment by banchichen** [comment]
抱歉，久等了...
你好：
1. 图片无法缩小到比初始更小：这个本身就是这样的，照片预览类TZPhotoPreviewCell里的scrollView属性minimumZoomScale默认值就是1.0。
2. 图片本身是会全屏显示的，所以不需要把图片放大，只要设置好裁剪框的尺寸就行，裁剪框尺寸属性是cropRect，在项目中全局搜索cropRect，可以看到相应的源码，比如TZPhotoPreviewController中的configCropView方法，这里会通过cropRect属性把裁剪框画出来。
    2.1. 图片宽高比 > 1.5：裁剪框高=图片高，宽自拟
    2.2. 图片宽高比 < 1.5：裁剪框宽=图片宽(屏幕宽)，高自拟
如上根据当前预览的图片数据，动态设置cropRect的值，再刷新界面，应该可以实现你想要的效果...

**Comment by songxing10000** [comment]
收到，我试试看动态设置cropRect
