### ISSUE TITLE
cpu爆炸

### ISSUE THREAD

**Issue by iURWang** [banchichen/TZImagePickerController#4]
滑动的时候明显卡顿，cpu飙到一百多

**Comment by banchichen** [comment]
你好，请问是用什么设备测试的呢，系统版本是多少？

**Comment by MrReN** [comment]
图片展示的时候没有复用吗

**Comment by MrReN** [comment]
@banchichen

**Comment by banchichen** [comment]
有复用的，我刚刚测试了一下，CPU确实比较有压力，应该是取照片对象的时候没有做缓存的原因，这点稍后会修复...

**Comment by iURWang** [comment]
iphone6 ios9.2

**Comment by iURWang** [comment]
@banchichen 展示的时候你取得是小图嘛？还是原图？

**Comment by banchichen** [comment]
是小图的，跟cell本身大小一样的缩略图，我看苹果官方的代码是做了缓存的，我研究下这一块，到时候更新上去~

**Comment by iURWang** [comment]
@banchichen 我之前做相册时候取了缩略图还是比较大有些卡后来加载cell数据时加个线程不卡了

**Comment by jiangxk2015** [comment]
@banchichen 视频的也整个InfoHandle回调吧。。。

**Comment by huangxiongbiao12** [comment]
赞一个  之前自己尝试用iOS8.0的api做了过  结果有点卡顿  而且偶尔崩溃了  原来是没做适配
