### ISSUE TITLE
正在处理。。。等太久

### ISSUE THREAD

**Issue by vickmiller** [banchichen/TZImagePickerController#40]
正在处理。。。等太久，然后那个提示框就一直在那了，也去不了了，我那边的代码应该也没耗时那么长啊，还有imagePickerControllerDidCancel这个方法名重复了？

**Comment by banchichen** [comment]
你好，正在处理遮罩框如果没dismiss，说明图片没有成功取到，有可能是这张照片保存在iCould中，请问是不是只有部分照片是这样？对于同样的一张照片，这种情况是不是必然重现呢？我的QQ、微信：736420282，如果愿意提供更详细的测试信息，请加我~

**Comment by 00675901** [comment]
在iPad下使用,会出现一直"正在处理..."的情况,貌似是在TZPhotoPickerController.m 216行的地方直接返回了,导致没有dismiss...只能cancel...所以也娶不到图片...但是在iphone下就不会...

**Comment by banchichen** [comment]
目前还找不到是什么原因......新版本我在这里做了限制，默认是15秒没有获得图片，HUD也会dismiss掉~15秒这个值也可以自己设定~
