### ISSUE TITLE
TZPhotoPickerController 不会主动dealloc

### ISSUE THREAD

**Issue by YBYHunter** [banchichen/TZImagePickerController#400]
我的解决办法就是didFinishPickingPhotos或者 取消 后主动把imagePickerVc = nil。不知道作者有什么好的办法.

**Comment by banchichen** [comment]
你好，你这个已经是个好方法了~
在选择图片结束时，TZPhotoPickerController没有立即dealloc，而是过了大约15秒才dealloc。是因为TZImagePickerController的showProgressHUD方法....开启了一个延时执行的block，block强引用了TZImagePickerController...😂
已经修复，稍后提交~
