### ISSUE TITLE
Application tried to present modally an active controller <XXXXXViewController>.

### ISSUE THREAD

**Issue by cdx0062009** [banchichen/TZImagePickerController#402]
集成的是1.7.8版本和之前的1.7.1版本，手机系统版本iOS10以后，设备iPhone6 以后。这个crash是一个随机的crash，开发时，完全没测试出来过，线上版本（5个版本）有报过30多次，但是测试这边一直测试不出来。

>  0 CoreFoundation	___exceptionPreprocess + 124
> 1 libobjc.A.dylib	objc_exception_throw + 56
> 2 UIKit	-[UIViewController _presentViewController:withAnimationController:completion:] + 4884
> 3 UIKit	-[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 268
> 4 UIKit	-[_UIViewControllerTransitionContext _runAlongsideCompletions] + 148
> 5 UIKit	-[_UIViewControllerTransitionContext completeTransition:] + 132
> 6 UIKit	-[UITransitionView notifyDidCompleteTransition:] + 252
> 7 UIKit	-[UITransitionView _didCompleteTransition:] + 1240
> 8 UIKit	-[UITransitionView _transitionDidStop:finished:] + 124
> 9 UIKit	-[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 312
> 10 UIKit	-[UIViewAnimationState animationDidStop:finished:] + 160
> 11 QuartzCore	0x000000018985d000 + 1119236
> 12 libdispatch.dylib	__dispatch_client_callout + 16
> 13 libdispatch.dylib	_dispatch_main_queue_callback_4CF + 1000
> 14 CoreFoundation	___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
> 15 CoreFoundation	___CFRunLoopRun + 1660
> 16 CoreFoundation	CFRunLoopRunSpecific + 444
> 17 GraphicsServices	GSEventRunModal + 180
> 18 UIKit	-[UIApplication _run] + 684
> 19 UIKit	UIApplicationMain + 208
> 
> 10:22:10.860 [ UIApplicationRotationFollowingController ] WillAppear
> 10:22:11.006 [ UIAlertController ] WillAppear
> 10:22:14.214 UIApplication WillResignActive
> 10:22:14.701 [ CAMImagePickerCameraViewController ] WillAppear
> 10:22:14.746 [ CAMViewfinderViewController ] WillAppear
> 10:22:14.746 [ CAMPreviewViewController ] WillAppear

**Comment by banchichen** [comment]
你好，这个报错的意思是，应用在尝试Modal一个已经活跃的控制器（这个控制器已经被某某强引用了）...

比如导航控制器栈中的控制器A，A已经在栈中了，你再去present A，就会这样报错。
或者TabBar控制器viewControllers数组里的控制器B，你去present B也这样报错....

这个库没有这样的代码，去检查下你们的代码吧...
