### ISSUE TITLE
可否增加一个photoHeight属性呢（已有这样功能的属性：cropRect）

### ISSUE THREAD

**Issue by 90candy** [banchichen/TZImagePickerController#403]
有时候需要用到正方形的图片，又不想过多的写些代码自己裁剪

**Comment by banchichen** [comment]
是指裁剪的时候要得到正方形图片吗？可以看看这个属性：
@property (nonatomic, assign) CGRect cropRect;      ///< 裁剪框的尺寸

**Comment by 90candy** [comment]
好的 ，我去试试， 谢谢！
