### ISSUE TITLE
点击返回按钮崩溃：'NSConcreteMutableAttributedString initWithString:attributes:: nil value'

### ISSUE THREAD

**Issue by SmilePast** [banchichen/TZImagePickerController#406]
报错内容：'NSConcreteMutableAttributedString initWithString:attributes:: nil value'

**Comment by banchichen** [comment]
请问是返回相册列表的时候崩溃了吗？

看报错内容，是NSMutableAttributedString构造方法发生崩溃，项目里只有在显示相册名字时用到了NSMutableAttributedString，相册名字为空时会出现。
请问你那里有一个没有名字的相册吗？

**Comment by banchichen** [comment]
试了一下， 确实当相册名字为nil时会崩溃...

目前无法得知为何相册名字是nil，我先在相册名字的get方法里避免了。谢谢反馈~
已修复，会随着这次发版发布~
