### ISSUE TITLE
选择图片问题

### ISSUE THREAD

**Issue by ZClee128** [banchichen/TZImagePickerController#410]
如何可以使照片重复选择，而不超过选择图片数量

**Comment by banchichen** [comment]
你好，重复选择的话需要用户多次打开选择器来选取照片。改动主要是以下几点：
1. 不传selectedAssets，这样的话内部不会判断是否被选取过，所有照片都可以继续选取。
2. maxImagesCount传一个动态的值，比如最大允许9张，目前用户已选7张，那再次打开选择器时，maxImagesCount要传2。
