### ISSUE TITLE
sortAscendingByModificationDate=NO ，但是照相之后取到的照片并不是当前拍照的照片

### ISSUE THREAD

**Issue by Yulei-Duan** [banchichen/TZImagePickerController#412]
sortAscendingByModificationDate

**Comment by veryitman** [comment]
经过测试, sortAscendingByModificationDate=NO 并且允许裁剪, 允许显示相机的时候, 拍照后的照片不是当前拍摄的照片.
@banchichen

**Comment by banchichen** [comment]
@veryitman  你好，系统版本是多少呢~我这边2台iOS10.2.1系统的设备倒没这个问题。

**Comment by banchichen** [comment]
@veryitman  单选允许裁剪的时候，sortAscendingByModificationDate=NO情况下，拍照后带到裁剪页面的照片确实不是当前拍摄的照片。有个小伙伴提了PR，我merge了，可以用最新的代码试试...

**Comment by banchichen** [comment]
用最新代码测了下，我这里是好的咯...

**Comment by veryitman** [comment]
@banchichen 给力, 我也是昨晚才看了你的源码, 和你修改的地方一样.

**Comment by Yulei-Duan** [comment]
嗯，新版可以了，我用的是去年12月份的版本，最新版解决了这个问题。
