### ISSUE TITLE
怎么刷新TZPhotoPickerController？

### ISSUE THREAD

**Issue by vmei123** [banchichen/TZImagePickerController#414]
TZImagePickerController的selectedModels增加或移除元素后怎么刷新TZPhotoPickerController？

**Comment by banchichen** [comment]
直接 [_collectionView reloadData]; 不可以吗？

**Comment by vmei123** [comment]
TZPhotoPickerController类的对象并没有声明出来，怎么取其collectionView？

**Comment by banchichen** [comment]
TZPhotoPickerController控制器都没创建，那为何要去刷新它？

TZPhotoPickerController控制器创建的时候，会走initSubviews方法，里面会调用checkSelectedModels方法，已经会根据TZImagePickerController中selectedModels的值来绘制界面。

**Comment by vmei123** [comment]
我弄了个TZPhotoPickerController的全局变量，每次present的都是同一个对象，所以才需要刷新。

**Comment by DeTong** [comment]
实在不行就把源码改一下，把属性拿到头文件里。
