### ISSUE TITLE
用cocoapods集成框架, 状态栏的问题

### ISSUE THREAD

**Issue by SimleCp** [banchichen/TZImagePickerController#419]
我的项目需求是需要黑色的状态栏, 我试过写分类和继承子类修改状态栏, 但是都不行.

**Comment by banchichen** [comment]
你好，我建议你可以创建一个TZImagePickerController的子类，在子类里重写viewWillAppear来控制下...

**Comment by SimleCp** [comment]
我在自己的项目里面新建了子类, 并不行, 后来我把你的项目Fork了一份 然后clone到本地试了下, 重写子类可以控制, 问题解决.谢谢.
