### ISSUE TITLE
选择与取消选择的bug

### ISSUE THREAD

**Issue by qimuya3** [banchichen/TZImagePickerController#42]
就是选择后，进入预览界面，然后不选择，但是最后还是选择，这个有bug。

**Comment by banchichen** [comment]
你好，这里我测试过很多次了，也有不少应用在使用这个图片选择器，都没遇到过这个问题。你有对代码做了修改吗？或者，是不是和原图按钮弄混了？如果确实有这个问题，能否拍一小段描述视频发我呢？如果可以的话，请发我邮箱，736420282@qq.com，谢谢。

**Comment by qimuya3** [comment]
你好，感谢你的回复。我的环境是iOS7.1 iphone4, 我刚才重新测试了一下，bug总结如下：
1 当我限定选择一张图，选择完后，点击“预览”，进入预览界面，在预览界面然后又点击右上角的取消选择按钮，取消选择该图，然后点击右下角的“确定”，photos 里还是有一张图，
`                                          [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets) {
                                             // photos 会有一张图在里面； ###bug
                                          }];`

2 当我限定选择N张图，选择完后，点击“预览”，进入预览界面，在预览界面然后又点击右上角的取消选择按钮，取消选择《所有图片》，然后点击右下角的“确定”，photos 里还是有一张图，
`                                          [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets) {
                                             // photos 会有一张图在里面； ###bug
                                          }];`
