### ISSUE TITLE
iPhone 横竖屏切换时会报错。

### ISSUE THREAD

**Issue by lucasleelz** [banchichen/TZImagePickerController#423]
1. iPad 旋转是没有问题的。iPhone 竖屏切换横屏的时候会报错。
2. iPad 旋转时候布局会有问题。例如。在横屏时候切换到竖屏，底部栏会显示在中间了。竖屏切换到横屏。底部栏不见了。

**Comment by banchichen** [comment]
你好，1.8.4版本已发布，已支持横屏。

**Comment by afskalsfk** [comment]
> 你好，1.8.4版本已发布，已支持横屏。

怎么禁用横屏。。。。。选择相册手机旋转 会自动横屏
