### ISSUE TITLE
获取用户拍照或选择图片的URL

### ISSUE THREAD

**Issue by Mohscodes** [banchichen/TZImagePickerController#424]
您好,请问怎么获取用户拍照或者选择中要上传图片的URL

**Comment by fengbai** [comment]
楼上的  解决了吗???

**Comment by Mohscodes** [comment]
还没有

**Comment by lancelot9527** [comment]
选择的图片的物理地址？那个要PhotoKit才取得到。

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/374  大家看这个issue吧

**Comment by Mohscodes** [comment]
好的,非常感谢你抽出时间来解答,我觉得上传图片经常用到,觉得TZImagePickerController可以把URL功能添加上去
