### ISSUE TITLE
TZAlbumPickerController列表为空

### ISSUE THREAD

**Issue by ongnen** [banchichen/TZImagePickerController#425]
当初始化条件_pushPhotoPickerVc=NO且弹出 应用请求相册访问权限时，出现此BUG。

解决方法：在- (void)pushPhotoPickerVc {}方法中添加代码
if (!_pushPhotoPickerVc) {
        TZAlbumPickerController *albumPickerVc = (TZAlbumPickerController *)self.visibleViewController;
        if ([albumPickerVc isKindOfClass:[TZAlbumPickerController class]]) {
            [albumPickerVc configTableView];
        }
    }

**Comment by banchichen** [comment]
给力👍

代码已提交，会随着这次发版发布~
