### ISSUE TITLE
imagePickerControllerDidCancel->tz_imagePickerControllerDidCancel 崩溃

### ISSUE THREAD

**Issue by ss522749726** [banchichen/TZImagePickerController#426]
我把旧版本TZPhotoPickerController.m中imagePickerControllerDidCancel这个方法换成更新后的tz_imagePickerControllerDidCancel崩溃，这是什么原因？

**Comment by andyden9** [comment]
我碰到过，dismiss了两次 因为有autoDismiss

**Comment by andyden9** [comment]
我碰到过，dismiss了两次 因为有autoDismiss

**Comment by banchichen** [comment]
我试了试，在tz_imagePickerControllerDidCancel里也把picker dismiss一下，但是没有发生崩溃。请把崩溃日志贴一下吧~ @ss522749726
