### ISSUE TITLE
预览iCloud大图时快速滑动图片显示错误

### ISSUE THREAD

**Issue by lirenyumac** [banchichen/TZImagePickerController#428]
当在预览大图界面，快速向右滑动几张图片停下，如果图片是从iCloud下载，cell会显示之前下载的图片，因为没有停止之前PHImageRequestID，异步下载之后会有显示图片错误的问题。

**Comment by banchichen** [comment]
赞~
问题已经修复，代码提交了，会随着下次发版发布哈。
