### ISSUE TITLE
视频转向方法中可能发生的内存泄漏问题

### ISSUE THREAD

**Issue by ysghome** [banchichen/TZImagePickerController#430]
![image](https://cloud.githubusercontent.com/assets/7429281/25036915/e5df7506-2128-11e7-9581-24027d4af3d6.png)
/// 获取优化后的视频转向信息
- (AVMutableVideoComposition *)fixedCompositionWithAsset:(AVAsset *)videoAsset
这个方法中

**Comment by banchichen** [comment]
已修复~
会随着这次发版发布~
