### ISSUE TITLE
设置只能选择一张照片，无法获取到照片

### ISSUE THREAD

**Issue by YoungGA** [banchichen/TZImagePickerController#432]
设置最大选择数为1，打开TZImagePickerController，在delegate回调里面的photos每次都是第一次选择的图片。

**Comment by banchichen** [comment]
你好，我在Demo上试了下，最大选择数为1时，重新选择照片后，photos会更新呀，界面也展示了最新的选中图片。

**Comment by YoungGA** [comment]
尴尬。 应该是我的问题，今天解决了，感谢回复。 已经能通过block和delegate获取最新的图片了
