### ISSUE TITLE
相册列表未及时刷新

### ISSUE THREAD

**Issue by ljbshishabi** [banchichen/TZImagePickerController#434]
开启了相册内调用相机功能。
第一次进去之后会自动push到TZPhotoPickerController。
选择相机拍照。确定之后自动选中照片。
这时候点左上角返回可以看到最近添加相册和相机胶卷相册都有选中1个。
但是这时候再到相机胶卷相册去拍照再返回。最近添加相册选择数没有刷新了。
原因是第一次返回的时候TZAlbumPickerController还是没加载的。会去拿一次albumArr。第二次之后懒加载不管用了~所以albumArr没刷新。

我的做法是在返回的block  setBackButtonClickHandle里面重新调了一次albumArr的懒加载。使albumArr刷新。。

**Comment by banchichen** [comment]
给力👍

已修复，会随着这次发版发布~
