### ISSUE TITLE
为什么加入 pod 'TZImagePickerController' 会报错？

### ISSUE THREAD

**Issue by emodeqidao** [banchichen/TZImagePickerController#435]
为什么加入 pod 'TZImagePickerController' 会报错？

**Comment by banchichen** [comment]
你好，报什么错呢...

**Comment by emodeqidao** [comment]
@banchichen  pod search TZImagePickerController  搜索不出来的 ，不知道是不是我的问题， 我已经pod setup 到最新的了

**Comment by banchichen** [comment]
@emodeqidao  搜索TZImagePickerController不出来的话，搜索MJRefresh、AFNetworking、SDWebImage等其他库能搜出来吗？
如果已经setup到最新，可能是podfile文件里source配置的问题(比如在阿里需要走内部镜像源)，可能需要重装下CocoaPods...

**Comment by emodeqidao** [comment]
@banchichen  我sources 里面 是 *** CURRENT SOURCES ***

http://gems.ruby-china.org/
https://gems.ruby-china.org/

忘记改。 谢谢~~~
不过昨天 我尝试 pod install 没有成功，setup 之后才成功的 ☺️
