### ISSUE TITLE
建议遍历PHFetchResult时使用enumerateObjectsUsingBlock方法，否则部分手机无法读取相册目录。

### ISSUE THREAD

**Issue by bobociel** [banchichen/TZImagePickerController#436]
PHFetchResult.h  NSFastEnumeration

- (void)enumerateObjectsUsingBlock:(void (^)(ObjectType obj, NSUInteger idx, BOOL *stop))block

**Comment by ginkgocy** [comment]
`否则部分手机无法读取相册目录` 这句话的手机无法读取相册目录的具体表现是什么？有什么crash 的log吗还是会怎么样？

**Comment by bobociel** [comment]
设备：iPhone6 Plus  系统版本：iOS10.3     出现过无法执行回调问题
设备：iPhone6 Plus  系统版本：iOS10.3.1  没有出现过这个问题

**Comment by banchichen** [comment]
你好，目前获取相册数组的方式是Apple官方Demo里的方式，基本所有第三方库获取相册也是用这个方式，至今好像表现比较正常...

另外，PHFetchResult可以看做是一个相册，用enumerateObjectsUsingBlock遍历去获取相册里的照片，目前就是这样做的，这个和无法获取相册目录应该没联系的吧...

目前获取相册的代码如下：
>         PHFetchResult *myPhotoStreamAlbum = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeAlbum subtype:PHAssetCollectionSubtypeAlbumMyPhotoStream options:nil];
        PHFetchResult *smartAlbums = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeSmartAlbum subtype:PHAssetCollectionSubtypeAlbumRegular options:nil];
        PHFetchResult *topLevelUserCollections = [PHCollectionList fetchTopLevelUserCollectionsWithOptions:nil];
        PHFetchResult *syncedAlbums = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeAlbum subtype:PHAssetCollectionSubtypeAlbumSyncedAlbum options:nil];
        PHFetchResult *sharedAlbums = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeAlbum subtype:PHAssetCollectionSubtypeAlbumCloudShared options:nil];

不存在回调...   是不是哪里打错字了...？
