### ISSUE TITLE
在线图片预览的问题

### ISSUE THREAD

**Issue by qq432591** [banchichen/TZImagePickerController#438]
现有项目中遇到问题。想请教解决思路
现有功能是在A页面多图上传到服务器，服务器会返回图片的url做展示用，
那么下次再进入A页面的时候，此时就是只有图片的url了 那么如何把它组装成PhAsset或者ALAsset来进入到TZImagePhotoPreviewController 来进行展示呢？

**Comment by banchichen** [comment]
你好，无法封装成PHAsset和ALAsset对象的...
这种情况目前TZImagePhotoPreviewController还没有支持...

**Comment by chenYuCui** [comment]
跟我碰到是一个问题：

无法封装成PHAsset和ALAsset对象

这样导致再次上传或者预览图片会出现崩溃，希望Owner能想办法解决下，也是个挑战！

**Comment by 1284115201** [comment]
我项目也有这个需求，我把后台返回的图片URL转UIImage再转PHAsset对象（我适配iOS8），预览的时候崩溃

**Comment by banchichen** [comment]
@qq432591 @chenYuCui @1284115201 @Arthurli @tinpont 

Hi，3.0.1版本已支持，需新接一个插件库：[TZImagePreviewController](https://github.com/banchichen/TZImagePreviewController)，请参考TZImagePreviewController里面的Demo使用。

抱歉久等了...
