### ISSUE TITLE
1.7.9问题

### ISSUE THREAD

**Issue by ShannonCrazy** [banchichen/TZImagePickerController#439]
当我设置
     TZImagePickerController *imageVC = [[TZImagePickerController alloc] initWithMaxImagesCount:9 columnNumber:3 delegate:self pushPhotoPickerVc:YES];
        imageVC.allowPickingVideo = YES;
        imageVC.allowTakePicture  = NO;
        imageVC.allowPickingImage = NO;
        imageVC.autoDismiss = NO;
的时候，选择了视频，然后到达视频预览页面，点击了右下角完成按钮代理没有任何响应。

**Comment by banchichen** [comment]
你好，Demo是好的吧？建议仔细比对一下Demo，打断点调试下看看点击完成按钮后，代理方法有没有被调用；被调用的时候，代理是不是已经是nil了？

**Comment by ShannonCrazy** [comment]
Demo也是一样的，我只在你的demo上添加了一句imagePickerVc.autoDismiss = NO;  然后只允许选择视频，
![qq20170502-095452](https://cloud.githubusercontent.com/assets/22512845/25601277/7543a79c-2f1d-11e7-8be3-ccb9d9100b2a.png)

点击完成后直接走到else ，else里没有操作😭

**Comment by banchichen** [comment]
看起来是你没实现选择完视频的回调方法哈，因为autoDismiss是NO，所以需要你实现回调方法，自己dismiss选择器...

回调如下：
// If user picking a video, this handle will be called.
// If system version > iOS8,asset is kind of PHAsset class, else is ALAsset class.
// 如果用户选择了一个视频，下面的handle会被执行
// 如果系统版本大于iOS8，asset是PHAsset类的对象，否则是ALAsset类的对象
@property (nonatomic, copy) void (^didFinishPickingVideoHandle)(UIImage *coverImage,id asset);
