### ISSUE TITLE
请问国际化怎么弄？现在是中文环境，成了英文中文都有的界面

### ISSUE THREAD

**Issue by dushoupeng** [banchichen/TZImagePickerController#443]

**Comment by doubleJJJJ** [comment]
同问

**Comment by shaolelng** [comment]
在 #import "NSBundle+TZImagePicker.h"
找到这个方法，+ (NSString *)tz_localizedStringForKey:(NSString *)key value:(NSString *)value {
    static NSBundle *bundle = nil;
    if (bundle == nil) {
        NSString *language = [NSLocale preferredLanguages].firstObject;
        if ([language rangeOfString:@"zh-Hans"].location != NSNotFound) {
            language = @"zh-Hans";
        } else {
            language = @"en";
        }
        bundle = [NSBundle bundleWithPath:[[NSBundle tz_imagePickerBundle] pathForResource:language ofType:@"lproj"]];
    }
    NSString *value1 = [bundle localizedStringForKey:key value:value table:nil];
    return value1;
}


在 if ([language rangeOfString:@"zh-Hans"].location != NSNotFound) {
            language = @"zh-Hans";
        } else {
            language = @"en";
        }
添加要修改的语言 判断。

在 TZImagePickerController.bundle 中添加带翻译 语言文件。

**Comment by shaolelng** [comment]
试试

**Comment by banchichen** [comment]
标题里提到的"英文中文都有的界面"，如果系统语言设置的是中文，但出现了这样的情况：
1. 刚打开照片选择器时，导航栏的返回按钮是英文，相册名字是英文。
2. 相册列表页中，系统相册是英文，其他相册是中文

说明是应用的info.plist文件里，设置了Localization native development region不是China。

解决方式：
1. 去掉Localization native development region的设置（应用内语言跟随系统语言）
2. 将Localization native development region的值设置为China。

**Comment by voludenuit** [comment]
如果修改语言设置没有作用，要看看导航栏的显示是否正常，如果导航栏显示偏大，看看启动界面使用图片的尺寸是不是不对

**Comment by linyuezang** [comment]
是否支持视频拍照

**Comment by linyuezang** [comment]
是否支持长按上传视频

**Comment by cxm1150806259** [comment]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/5691535/47551834-cff16d00-d935-11e8-942f-da82365d8550.png">
添加下语言就OK了

**Comment by LassZhang** [comment]
PROJECT > Info > Localizations的Language列表中添加Chinese
