### ISSUE TITLE
gif图问题——禁止gif选择的时候，gif图目前是当做一个静态图处理

### ISSUE THREAD

**Issue by ZClee128** [banchichen/TZImagePickerController#444]
我设置了禁止选择gif图，但是这个图片本身是gif图，只是在手机里显示的是jpg，所以可以选择，这个怎么可以禁止，因为图片浏览的是不会动的，点击他又可以动

**Comment by banchichen** [comment]
你好，我试了下，禁止了gif的话，单独预览gif也是不会动的呀...
禁止gif选择的时候，gif图目前是当做一个静态图处理...
