### ISSUE TITLE
iOS10 把拍照按钮放在外面，点击sheet中的拍照，没有反应。

### ISSUE THREAD

**Issue by wongshouxin** [banchichen/TZImagePickerController#445]
必须先打开相册权限，拍照才有反应。拍照权限没有设置。

**Comment by gyyxiaogao** [comment]
怎么提示打开?

**Comment by gyyxiaogao** [comment]
放在外面死循环了,怎么处理?

**Comment by wongshouxin** [comment]
把takePhoto中这个死循环（else if ([TZImageManager authorizationStatus] == 0)）一段删除就可以了，bug解决。

**Comment by gyyxiaogao** [comment]
你这样做是有问题的,你首次拍照图片保存是失败的.

**Comment by banchichen** [comment]
上次因为另一个问题，合并了一个PR，导致这里出了问题...
刚刚已经修复了哈，代码会随着下次发版发布~

**Comment by banchichen** [comment]
代码已经提交了，下载最新的Demo可以看到~
