### ISSUE TITLE
不能设置navigationBar.translucent = NO

### ISSUE THREAD

**Issue by andyden9** [banchichen/TZImagePickerController#449]
设置为 NO 时：
![simulator screen shot 2017 5 4 6 03 23](https://cloud.githubusercontent.com/assets/14224413/25699048/207322fa-30f4-11e7-9408-0695e0052786.png)

但是不设置为NO 传进去的背景颜色会自动加一个半透明毛玻璃效果，使颜色不准：
<img width="624" alt="2017-05-04 6 07 09" src="https://cloud.githubusercontent.com/assets/14224413/25699153/960612fc-30f4-11e7-8a4f-368e64a8040a.png">

**Comment by lifengios** [comment]
我用appearance 修改了导航栏的颜色 ，present 的picker 导航栏就变成白色了

**Comment by banchichen** [comment]
我这里设置translucent为no是正常的咦...
你那里用的是1.7.9版本吗？

**Comment by banchichen** [comment]
可以参考下这个PR，是解决这个bug的，在2017年1月就已经merge了哈
  https://github.com/banchichen/TZImagePickerController/pull/321
