### ISSUE TITLE
图片浏览后返回选择图片的界面导航栏上移

### ISSUE THREAD

**Issue by woshiqqt** [banchichen/TZImagePickerController#45]
![](https://static.dingtalk.com/media/lADODMynT80FAM0C0A_720_1280.jpg_620x10000q90.jpg)

**Comment by banchichen** [comment]
你好，预览的时候我隐藏了状态栏的，预览结束后我又显示了状态栏。我当时在iOS6的4s手机上测试，已经修复了这个问题的...没想到又来了...请问你是什么机型什么系统呢？如果你比较急的话，可以关闭预览界面中对状态栏的隐藏代码，就不会有这个问题的。
