### ISSUE TITLE
大神请问下为什么不能选视频

### ISSUE THREAD

**Issue by Oopsjesse** [banchichen/TZImagePickerController#450]
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:9 delegate:self];
    
    imagePickerVc.allowPickingImage = !isOnlyVideo;
    imagePickerVc.allowPickingVideo = isOnlyVideo;
    
    [self.superController presentViewController:imagePickerVc animated:YES completion:nil];

    [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos,NSArray *assets,BOOL isSelectOriginalPhoto){
        XQHSendHuiboViewController *vc = [[XQHSendHuiboViewController alloc] init];
        vc.isOnlyVideo = isOnlyVideo;
        vc.selectedPhotos = photos.mutableCopy;
        vc.selectedAssets = assets.mutableCopy;
        
        [self.superController presentViewController:vc animated:YES completion:nil];
    }];

代码如上  弹出的imagePickerVc不能选视频,不知为何,希望能抽空解答下!不胜感激!

**Comment by banchichen** [comment]
// If user picking a video, this handle will be called.
你好，如果用户是选择了视频的话，是走下面的回调

// If system version > iOS8,asset is kind of PHAsset class, else is ALAsset class.
// 如果用户选择了一个视频，下面的handle会被执行
// 如果系统版本大于iOS8，asset是PHAsset类的对象，否则是ALAsset类的对象
@property (nonatomic, copy) void (^didFinishPickingVideoHandle)(UIImage *coverImage,id asset);
