### ISSUE TITLE
不知可否增加对视频长度的选择

### ISSUE THREAD

**Issue by PPFSaber** [banchichen/TZImagePickerController#454]

**Comment by banchichen** [comment]
你好，刚刚发布了1.8.1版本，新增两个代理方法，isAlbumCanSelect:result:和isAssetCanSelect:，可由上层通过实现代理方法来决定某个相册/照片/视频显示与否。

可以参考最新的Demo，实现isAssetCanSelect:代理方法，返回NO则此照片/视频不会显示哈。
