### ISSUE TITLE
设备只支持横屏

### ISSUE THREAD

**Issue by MysteryRan** [banchichen/TZImagePickerController#458]
设备只支持横屏，调用会闪退，该如何解决

**Comment by Jayxiang** [comment]
调用哪一个会闪退?

**Comment by MysteryRan** [comment]
我在plist里面设置屏幕只支持横屏,模态出TZImagePickerController就会闪退。

**Comment by Jayxiang** [comment]
哦哦  对哦 应该不支持横屏

**Comment by MysteryRan** [comment]
不是不支持横屏,如果是你设备支持所有方向,横屏时调用就不会出现问题。如果只支持横屏就会出现这种问题,请问有解决方法吗。

**Comment by Jayxiang** [comment]
我测试的时候 虽然支持所有方向但是 横屏时也没有横屏显示  仍然是竖屏的样式  或者你看一下这个https://github.com/zhangao0086/DKImagePickerController  支持横屏的

**Comment by lyle-luan** [comment]
遇到相同的问题，不知道大家有没有解决方法。

**Comment by lyle-luan** [comment]
`- (BOOL) shouldAutorotate {
    return NO;
}`

添加以上代码到`TZImagePickerController`

**Comment by MysteryRan** [comment]
我是改了源码,使他的方向支持横屏。
