### ISSUE TITLE
当MaxImagesCount=1时， 进去没有勾选按钮

### ISSUE THREAD

**Issue by QiaokeZ** [banchichen/TZImagePickerController#459]

**Comment by Jayxiang** [comment]
一张就直接选了.....为何还要勾选按钮

**Comment by banchichen** [comment]
你好，可通过设置showSelectBtn为YES来显示勾选按钮。

/// Single selection mode, valid when maxImagesCount = 1
/// 单选模式,maxImagesCount为1时才生效
@property (nonatomic, assign) BOOL showSelectBtn;   ///< 在单选模式下，照片列表页中，显示选择按钮,默认为NO
