### ISSUE TITLE
6 plus真机多选照片达到35M以上（基本10张以上），点击确定加载超过5秒应用会闪退

### ISSUE THREAD

**Issue by YangKa** [banchichen/TZImagePickerController#46]
不知道是什么原因，5s上没有这种现象

**Comment by banchichen** [comment]
抱歉哈，才留意到这个问题。我这里测试不出来这种情况，请问可以把崩溃的日志提供出来么~谢谢~

**Comment by ryzur-martin** [comment]
在 plus (9.0以上）使用的时候内存会增长到几百 M，其他情况下没有

**Comment by banchichen** [comment]
plus的话，屏幕是三倍屏，应该是取出来的图片尺寸比较大。可以把图片尺寸改一下试试，代码在TZImageManager类m文件的第30行，改成  CGFloat scale = 2.0，看看效果咋样~
。我手头没有plus真机不太方便测~  麻烦测试后再告知一下内存占用情况~

**Comment by ryzur-martin** [comment]
scale 改成2.0就没问题了，内存占用和其他机型一样

**Comment by banchichen** [comment]
好的，谢谢反馈~具体是什么原因倒不太清楚，scale从2变成3，图片size增大到2.25倍，内存竟然差距这么大....那我还是把这里改为2吧...
