### ISSUE TITLE
降序排序时拍照完成裁剪图片不是刚刚拍的那张

### ISSUE THREAD

**Issue by KyonLi** [banchichen/TZImagePickerController#462]
Xcode 8.3.2，iOS 10.3.2

maxImagesCount = 1
allowTakePicture = YES
allowCrop = YES
sortAscendingByModificationDate = NO

拍照完成进入裁剪模式时图片为列表中的最后一张，而不是刚刚拍的那张。

**Comment by banchichen** [comment]
请问是用的最新的1.7.9版本吗？

**Comment by KyonLi** [comment]
@banchichen 是1.7.9

**Comment by bacy** [comment]
我也是这个问题，sortAscendingByModificationDate = NO 拍照，裁剪的图片不是拍的那张

**Comment by bacy** [comment]
@KyonLi 请问这个 问题你后来就解决了吗

**Comment by banchichen** [comment]
奇怪，之前1.7.8确实顺序有问题，但是1.7.9已经解决了，我这里测试了多次没复现出来...
