### ISSUE TITLE
裁剪区域怎么设置

### ISSUE THREAD

**Issue by Mr-lins** [banchichen/TZImagePickerController#463]
裁剪出来就那么点太小了，怎么设置裁剪区域的大小？

**Comment by banchichen** [comment]
裁剪框相关属性：
@property (nonatomic, assign) BOOL allowCrop;       ///< 允许裁剪,默认为YES，showSelectBtn为NO才生效
@property (nonatomic, assign) CGRect cropRect;      ///< 裁剪框的尺寸
@property (nonatomic, assign) BOOL needCircleCrop;  ///< 需要圆形裁剪框
@property (nonatomic, assign) NSInteger circleCropRadius;  ///< 圆形裁剪框半径大小
@property (nonatomic, copy) void (^cropViewSettingBlock)(UIView *cropView);     ///< 自定义裁剪框的其他属性

**Comment by oceanfive** [comment]
补充一下自己使用过程中遇到的问题，是在带有导航栏的控制器中使用的，设置裁剪区域
    // 设置竖屏下的裁剪尺寸， 4:3 比例
    CGFloat margin = 30.0f;
    CGFloat width = self.view.frame.size.width - 2 * margin;
    CGFloat height = width * 3.0 / 4.0f;
    CGFloat y = ([UIScreen mainScreen].bounds.size.height - height) / 2;
    imagePickerVc.cropRect = CGRectMake(margin, y, width, height);

y值需要根据屏幕宽度来设置，如果根据 view 的高度设置，则会造成裁剪框和图片不能完全吻合，会留有一定的高度
CGFloat y = (self.view.frame.size.height - height) / 2;
