### ISSUE TITLE
图片裁剪，最顶部和最底部有白线

### ISSUE THREAD

**Issue by hailang47923** [banchichen/TZImagePickerController#464]
选择单张图片，设置裁剪区域后，能够获取到裁剪图片，但是裁剪后的图片，最顶部和最底部有两条白线，希望能看下。用的是1.7.8版本

**Comment by banchichen** [comment]
你好，我刚刚试了下，我把photos数组的图片保存在本机相册中，再去预览，没有发现白线的问题....截图如下：
![square crop](https://user-images.githubusercontent.com/12755494/27010319-2ecf5df2-4ed4-11e7-81a6-0f956e78fed2.png)
![circle crop](https://user-images.githubusercontent.com/12755494/27010320-3164bcec-4ed4-11e7-9d09-0a0cadaa0044.png)

是不是其他地方导致的..？

**Comment by banchichen** [comment]
在手机上试了下， 也是正常的哈...

**Comment by hailang47923** [comment]
你好，正常情况下，是没有白色线条出现的。我是用的矩形裁剪，而且裁剪框的长宽比例和选择要裁剪图片的长宽比例是一样的，例如，裁剪框是给的 375 * 200，所选图片宽高比是750 * 400，在这种情况下，选择完图片，进入到裁剪页面，不去拖动图片，直接点击完成，裁剪出来的图片会带有白条。

**Comment by banchichen** [comment]
你好，听你的描述，我猜测应该是你的cropRect设置错了，比如图片Y值是100，高度是200，你设置的cropRect里，Y值小于100，高度大于200，比如99.5，200.5

当cropRect的Y值小于图片起点、高度大于图片高度时，就会有白线了。
建议检查下你那里cropRect的设置方法，最保险的做法是，把计算的Y值向上取整，高度则向下取整，这样应该就没问题了
