### ISSUE TITLE
第一次打开选拍照，拒绝授权后，摄像屏幕是黑的仍然可以拍照，这个希望优化一下。

### ISSUE THREAD

**Issue by easongtd** [banchichen/TZImagePickerController#466]
第一次打开选拍照，拒绝授权后，摄像屏幕是黑的仍然可以拍照，这个希望优化一下。正确的应该是拒绝授权后关闭拍照窗口，或者不绝对点拍照按钮。

**Comment by banchichen** [comment]
很好的建议~👍
目前做的优化是，如果还未授权时用户点击拍照，会弹出授权弹窗，拒绝授权则不打开相机。
代码已提交，会在下次发版时带上~

**Comment by easongtd** [comment]
好的，给力。其实这问题微信已经也存在，只是后来他们修复了，也就去年底的事吧。
