### ISSUE TITLE
裁剪时，希望可以在界面上允许用户调整裁剪框的大小

### ISSUE THREAD

**Issue by ZHSY** [banchichen/TZImagePickerController#467]
图片剪切最好能够界面调整剪切框的大小，图片剪切最好能在拍照后再保存到相册

**Comment by emodeqidao** [comment]
现在这个版本 可以调整 裁剪框的大小了吗？@banchichen

**Comment by banchichen** [comment]
@emodeqidao 目前必须提前在代码里写死

**Comment by emodeqidao** [comment]
好的好的，谢谢，希望后面可以自己调整裁剪框的大小 以及形状

**Comment by banchichen** [comment]
你好，如果对裁剪的要求比较高的话，建议选择器dismiss后再去裁剪，配合[PhotoTweaks](https://github.com/itouch2/PhotoTweaks)使用~

我这个库暂时不打算升级裁剪功能哈...

[PhotoTweaks](https://github.com/itouch2/PhotoTweaks)是满足你需求的~
