### ISSUE TITLE
图片被压扁的问题

### ISSUE THREAD

**Issue by KatyChenLu** [banchichen/TZImagePickerController#469]
偶发，拾取之后预览的时候就已经被压缩了，有没有人碰到类似的情况。。

**Comment by Josin22** [comment]
长图的时候会出现

**Comment by banchichen** [comment]
图片被压扁，是指图片被压缩对吧...？

对于超长图、超高图，为了防止选择多张时内存暴增，返回的photos数组里只是大图，一般不是最清晰的。
要获取原图，请参考API说明哈：

> // 你可以通过一个asset获得原图，通过这个方法：[[TZImageManager manager] getOriginalPhotoWithAsset:completion:]
// photos数组里的UIImage对象，默认是828像素宽，你可以通过设置photoWidth属性的值来改变它
@property (nonatomic, copy) void (^didFinishPickingPhotosHandle)(NSArray<UIImage *> *photos,NSArray *assets,BOOL isSelectOriginalPhoto);
