### ISSUE TITLE
Access to PHImageFileURLKey

### ISSUE THREAD

**Issue by balkarov** [banchichen/TZImagePickerController#471]
Hello!

Thank you for your library.
How I can add access to image by PHImageFileURLKey?
Because now this url does not get image data.

**Comment by banchichen** [comment]
Hi，this answer may can help you: [https://stackoverflow.com/questions/26290443/read-from-url-obtained-from-phimagefileurlkey](url)

In TZImagePickerController library, you also can get image data by this api:
`- (PHImageRequestID)getPhotoWithAsset:(id)asset completion:(void (^)(UIImage *photo,NSDictionary *info,BOOL isDegraded))completion;`
in TZImageManager Class
