### ISSUE TITLE
多选图片时，图片数量显示只能递增，不能递减

### ISSUE THREAD

**Issue by iOSHJH** [banchichen/TZImagePickerController#472]
多选图片时，当我选中1张图片，图片数量显示1，选中两张则显示2。但我取消选中某一张，图片数量还是显示2，不会递减。望博主能早点修复此问题，在此非常感谢

**Comment by banchichen** [comment]
怎么会有这么低级的错误呢...
我这里是好的呀...
你那里运行Demo也有这个问题吗？

**Comment by iOSHJH** [comment]
我安装了最新版本就没有这个问题了，多谢博主
