### ISSUE TITLE
选择图片数量限制bug 

### ISSUE THREAD

**Issue by GitHubazuo** [banchichen/TZImagePickerController#473]
![4ce3981b-b8a8-4ea7-8ebd-6642ed046fb8](https://cloud.githubusercontent.com/assets/15389354/26676299/c17924a4-46f9-11e7-81cc-ed18c6cbbd62.png)
限制数量传入1张 选择按钮不显示
![26770872-d460-41ad-b373-1144c454d3d0](https://cloud.githubusercontent.com/assets/15389354/26676344/ed8387f6-46f9-11e7-8d0e-084bbaac3667.png)
裁剪框出现

**Comment by banchichen** [comment]
同学，不是界面默认表现不是你想要的，就是bug啊...

请参照如下属性进行设置：
/// Single selection mode, valid when maxImagesCount = 1
/// 单选模式,maxImagesCount为1时才生效
@property (nonatomic, assign) BOOL showSelectBtn;   ///< 在单选模式下，照片列表页中，显示选择按钮,默认为NO
@property (nonatomic, assign) BOOL allowCrop;       ///< 允许裁剪,默认为YES，showSelectBtn为NO才生效
@property (nonatomic, assign) CGRect cropRect;      ///< 裁剪框的尺寸
@property (nonatomic, assign) BOOL needCircleCrop;  ///< 需要圆形裁剪框
@property (nonatomic, assign) NSInteger circleCropRadius;  ///< 圆形裁剪框半径大小
@property (nonatomic, copy) void (^cropViewSettingBlock)(UIView *cropView);     ///< 自定义裁剪框的其他属性
