### ISSUE TITLE
选取大视频时卡顿，楼主有办法解决吗？

### ISSUE THREAD

**Issue by shaolelng** [banchichen/TZImagePickerController#474]

**Comment by banchichen** [comment]
卡顿表现在什么方面呢？在选取的时候，页面上会弹出正在处理的提示框，然后去获取视频数据，结束后关闭提示框，dismiss控制器，然后调用代理方法把视频返回出去...   卡顿表现在哪一个步骤呢？

然后请再提供一下系统版本、库的版本、设备型号、视频大小达到多大时会卡顿等信息

**Comment by shaolelng** [comment]
在这个 - (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingVideo:(UIImage *)coverImage sourceAssets:(id)asset；代理方法中，我需要使用视频的url，视频导出到本地，若视频太长，block回调等待的时间太长。若不等回调，直接使用TZImageManager.h中的url，及图片，获取不到视频的data。有方法解决吗？

**Comment by banchichen** [comment]
@shaolelng  回调太长的话，建议加一个Loading...
