### ISSUE TITLE
UI上的小建议

### ISSUE THREAD

**Issue by watermelon520** [banchichen/TZImagePickerController#479]
设置 minImagesCount 或者 maxImagesCount 这个属性之后，完成按钮的旁边的 图片张数的显示，能不能改为 X/X 这样的显示形式，这样会体验会好很多

**Comment by banchichen** [comment]
你好，看了下微信和微博都没有这样做哈，目前不打算改成这样

不过新版里有一个showPhotoCannotSelectLayer的属性，设置为YES的话，选中了maxImagesCount张照片后，其余照片会置灰，跟目前微信一样的体验。
