### ISSUE TITLE
pod集成失败

### ISSUE THREAD

**Issue by tooodooo** [banchichen/TZImagePickerController#48]
用的swift，集成后所有XIB/图片资源打包进 TZImagePickerController.framework 中

但是运行时会只在 app 根目录下寻找资源，导致找不到资源而崩溃

**Comment by tooodooo** [comment]
已经提交了一个修改分支

https://github.com/banchichen/TZImagePickerController/pull/49

**Comment by tooodooo** [comment]
https://github.com/banchichen/TZImagePickerController/pull/49

**Comment by banchichen** [comment]
你好，不好意思最近太忙了，才有空来看这里，谢谢你的PR。我后面不小心又提了些代码，导致如果merge你的PR会冲突....我就自己更新了...新版本已经解决了这个问题，谢谢~
