### ISSUE TITLE
请问有没有限制图片大小的功能

### ISSUE THREAD

**Issue by bcrystalest** [banchichen/TZImagePickerController#480]
现在有个需求要图片25mb以下的...

**Comment by banchichen** [comment]
那个...手机拍的图片，也可以达到25M以上吗~？

**Comment by banchichen** [comment]
你好，也可以参考这些属性：
/// Minimum selectable photo width, Default is 0
/// 最小可选中的图片宽度，默认是0，小于这个宽度的图片不可选中
@property (nonatomic, assign) NSInteger minPhotoWidthSelectable;
@property (nonatomic, assign) NSInteger minPhotoHeightSelectable;
/// Hide the photo what can not be selected, Default is NO
/// 隐藏不可以选中的图片，默认是NO，不推荐将其设置为YES
@property (nonatomic, assign) BOOL hideWhenCanNotSelect;
