### ISSUE TITLE
保存照片时出错，PLXPCDictionarySetArray unable to serialize array

### ISSUE THREAD

**Issue by zengshigang** [banchichen/TZImagePickerController#481]
PLXPCDictionarySetArray unable to serialize array (
        {
        creationOptions =         {
            originalFilename = "<null>";
            shouldMoveFile = 1;
            uniformTypeIdentifier = "<null>";
        };
        data =

**Comment by banchichen** [comment]
你好，请问你那里，Demo是正常的，是你的项目里有这个问题是吗？

这个链接或许可以帮到你：http://www.cocoachina.com/bbs/read.php?tid=1712751
建议排查一下...

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/377

**Comment by KinsonWu** [comment]
你好！看了你的Demo，Demo里可以将GPS信息写入照片，我跟你用同一个方式，GPS信息写入失败，以下代码是启动相机的方式
self.camera = [[UIImagePickerController alloc] init];
self.camera.delegate = self;
self.camera.sourceType = UIImagePickerControllerSourceTypeCamera;
self.camera.modalPresentationStyle = UIModalPresentationOverCurrentContext;

**Comment by Jorgezz** [comment]
还有个原因就是保存的时候[[PHAssetCreationRequest creationRequestForAsset] addResourceWithType:PHAssetResourceTypePhoto data:data options:options];
确保数据是UIImageJPEGRepresentation生成的JPEG的数据，PNG数据系统不识别。

**Comment by ddangPengf520** [comment]
iphone 6s 12.2版本  从微信电脑端传到手机图片保存在手机相册，微信提示保存成功，图片总数正确，使用
TZImagePickerController 上传照片时候，相机胶卷中不显示刚才保存的照片，返回一步  图片总数正确，
