### ISSUE TITLE
在哪里自己设置压缩的程度？

### ISSUE THREAD

**Issue by iostchan** [banchichen/TZImagePickerController#482]
麻烦你了，我的可以是旧板，选原图后发送也是被压了 ，我想不压或者压的程度我自己调

**Comment by banchichen** [comment]
你好，可以参考这个属性：photoWidth，这个是返回的photos数组里，照片的像素宽度。不过我代码里限制了，最大也只有当前屏幕宽度的1.5倍(1.8.0版本)
如果要更大的，或者是要原图，需要再通过TZImageManager来获取：

> // 这个照片选择器会自己dismiss，当选择器dismiss的时候，会执行下面的handle
// 你也可以设置autoDismiss属性为NO，选择器就不会自己dismis了
// 如果isSelectOriginalPhoto为YES，表明用户选择了原图
// 你可以通过一个asset获得原图，通过这个方法：[[TZImageManager manager] getOriginalPhotoWithAsset:completion:]
// photos数组里的UIImage对象，默认是828像素宽，你可以通过设置photoWidth属性的值来改变它
- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray<UIImage *> *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto;
- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray<UIImage *> *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto infos:(NSArray<NSDictionary *> *)infos;
//- (void)imagePickerControllerDidCancel:(TZImagePickerController *)picker __attribute__((deprecated("Use -tz_imagePickerControllerDidCancel:.")));
- (void)tz_imagePickerControllerDidCancel:(TZImagePickerController *)picker;
