### ISSUE TITLE
原图选择错位.

### ISSUE THREAD

**Issue by iOSleep** [banchichen/TZImagePickerController#483]
<img width="375" alt="qq20170613-170704 2x" src="https://user-images.githubusercontent.com/26478957/27074929-2838a86c-505b-11e7-8ab4-bdb7f27dc962.png">

因为全局设置了navbar的setTranslucent属性, TZPhotoPickerController.m line:194判断错误, 
```
    if (self.navigationController.navigationBar.isTranslucent) 
```
建议修改为
```
    if (!self.navigationController.navigationBar.isHidden) 
```

**Comment by kSimpleCoder** [comment]
1、把```TZPhotoPickerController.m```和```TZImagePickerController.m```中的 ```if (self.navigationController.navigationBar.isTranslucent) ```改成``` if (!self.navigationController.navigationBar.isHidden) ```。
2、在```TZPhotoPickerController.m```中的```viewDidLoad```里面加上    ```self.navigationController.navigationBar.translucent = YES;
    self.automaticallyAdjustsScrollViewInsets = NO;```

**Comment by banchichen** [comment]
Hi, 最新版1.8.2已发出~
