### ISSUE TITLE
设置选择图片的最大个数，超出个数还能选择（或设置为0）还可以选择

### ISSUE THREAD

**Issue by MagicCodeboy** [banchichen/TZImagePickerController#485]
TZImagePickerController * imagePick = [[TZImagePickerController alloc]initWithMaxImagesCount:5 - self.goodPicArray.count columnNumber:3 delegate:self pushPhotoPickerVc:YES];
我设置最大的个数是5个减去当前数组的个数，当当前的数组的个数为5 即结果为零的时候还是能够进入选择，能够再次选择5个

**Comment by MagicCodeboy** [comment]
![image](https://user-images.githubusercontent.com/17582992/27076630-590a2330-5060-11e7-94c7-61a21a39cb09.png)
我觉得作者这里应该设置为大于等于

**Comment by banchichen** [comment]
你好...
那个...你不觉得，当maxImagesCount为0的时候，你不应该再弹出图片选择器了吗...
微信的做法是，当剩余可选张数为0时，已经没有+号按钮了，不能再进入图片选择器了...

**Comment by MagicCodeboy** [comment]
恩恩，没想到这个，但是还是有一个问题    
_maxImagesCount = maxImagesCount;
    if (maxImagesCount > 1) {
        _showSelectBtn = YES;
        _allowCrop = NO;
    }
这个不是应该是大于等于1都要显示那个选择框吗？还是我理解有误

**Comment by banchichen** [comment]
这里的代码，是为了规避上层设置的非法值。

maxImagesCount大于1时，showSelectBtn必须是YES，allowCrop必须是NO。
