### ISSUE TITLE
为什么拉进项目一大片警告

### ISSUE THREAD

**Issue by yangjiangqq** [banchichen/TZImagePickerController#487]
Block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

项目用了混编？

**Comment by peanutgao** [comment]
@yangjiangqq  我已帮忙解决, 并提交了pull request, 等待作者@banchichen 同意

**Comment by banchichen** [comment]
你好，把TZPhotoPreviewCell.m文件的nullable删除吧。就不会报错了。

下一版我会删除这里，这次你就在代码里直接改吧...

**Comment by banchichen** [comment]
@peanutgao 已经merge了，不过还是有一些警告噢...

**Comment by banchichen** [comment]
Hi, 好像光删那个不够哈，还得把其他的nullable、nonnull都删掉...
最新代码已经修正了这个问题，已经提交了，这个周日应该会发一版哈，你可以先直接改我的代码...
