### ISSUE TITLE
已选图片显示

### ISSUE THREAD

**Issue by is0bnd** [banchichen/TZImagePickerController#488]
例: 图片多选模式, 选择2张图片确定后, 再次进入选择器, 期望以前选择的两张图片处于已选择状态

**Comment by banchichen** [comment]
那个，Demo不就是这样的效果么...
![demo ui](https://user-images.githubusercontent.com/12755494/27121377-a537b7d6-5119-11e7-8cc1-763ba1583025.png)

**Comment by is0bnd** [comment]
您好: 
	非常抱歉, 我没有注意到, 打扰您了, 非常感谢!
