### ISSUE TITLE
模拟器上获得的图片路径都可以显示，但是真机上获取的路径很多图片都找不到

### ISSUE THREAD

**Issue by giantss** [banchichen/TZImagePickerController#489]
`[[PHImageManager defaultManager] requestImageForAsset:asset targetSize:size contentMode:PHImageContentModeDefault options:options resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info)`
首先非常谢感谢你分享的源码，上面是我通过PHImageManager  NSURL *URL = [info valueForKey:@"PHImageFileURLKey"];获取图片路径，但是在真机上90%的图片图片路径都是错误的显示找不到图片资源，求解决方案啊 如果用沙盒应该如何实现呢 求代码 @banchichen

**Comment by banchichen** [comment]
你好，可以参考下这个issue：https://github.com/banchichen/TZImagePickerController/issues/471

看起来，是没有相应的API可以从PHImageFileURLKey读取图片数据的

要想从应用沙盒读取里图片的话，需要你先把图片存进沙盒里...

**Comment by giantss** [comment]
好的 谢谢。
