### ISSUE TITLE
初始状态需要加载从落网请求的图片（url地址）

### ISSUE THREAD

**Issue by chenYuCui** [banchichen/TZImagePickerController#490]
我的做法（1）请求过来的照片先转换成 UIImage的对象，存储在已初始化好的数组 _selectedQPhotos 中                
UIImage *bImg =[UIImage imageWithData:[NSData dataWithContentsOfURL:[NSURL URLWithString:bStr]]];
 [_selectedQPhotos addObject:bImg];
              （2）刷新collection
 [_collectionHview reloadData];

这样做加载没有问题，但问题出在
（1）再次上传时- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto
这个代理方法返回的 photos 我会再次➕到_selectedQPhotos数组中， 那么关键问题是存储assets的数组_selectedQAssets与实际图片的个数就对应不上了，其实最本质的原因还是因为请求过来的图片不能生成类似本地生成的assets，这样在预览图片的时候也会导致程序崩溃。

不知道问题说清楚了没有？是否有解决的方法，感谢大神！

**Comment by banchichen** [comment]
Q：预览界面能否支持传入NSURL、UIImage对象？
A：排期中，优先级高

你好，下一次改版会优先完善这一个地方哈

**Comment by chenYuCui** [comment]
期待，非常感谢 Owner

**Comment by 1284115201** [comment]
我也有这种需求，请问现在解决了么

**Comment by MichaelChai** [comment]
期待，我正好遇到了这个问题

**Comment by dzhlch** [comment]
等了一年这个问题还在排期，期待好渺茫 ~~~,我自己先改吧改吧

**Comment by banchichen** [comment]
@chenYuCui @1284115201 @MichaelChai @dzhlch @Arthurli 

Hi，3.0.1版本已支持，需新接一个插件库：[TZImagePreviewController](https://github.com/banchichen/TZImagePreviewController)，请参考TZImagePreviewController里面的Demo使用。

抱歉久等了...
