### ISSUE TITLE
关于照片、GIF、视频同时选择的问题

### ISSUE THREAD

**Issue by qyfeng009** [banchichen/TZImagePickerController#492]
最近在学习TZImagePickerController时，发现在同时允许选择照片、视频、GIF时，第一张选择照片时，不能再选择GIF或视频（会有提示：选择照片时不能选择GIF或视屏），同样的当第一张选择GIF或视屏时再选择是只能选择照片了不能选择GIF或视频，会有同样的提示。望指教

**Comment by banchichen** [comment]
这个是参考的当时微信的做法哈，照片与视频/GIF不能多选

未来会加入多选的支持哈。

**Comment by ChenZhenChun** [comment]
原来如此，我以为是bug，刚想提问。

**Comment by banchichen** [comment]
你好，1.8.4版本已发布，已支持照片/gif/视频同时选&多选。
