### ISSUE TITLE
循环引用

### ISSUE THREAD

**Issue by Danie1s** [banchichen/TZImagePickerController#493]
当没有打开相册权限的时候，会进入提示设置权限的界面，这时候如果按右上角的取消，从而退出这个界面，那么就会造成内存泄漏，应该是循环引用导致，估计是定时器没有销毁，请作者修改

**Comment by banchichen** [comment]
Hi, 请问此时控制器都dealloc了吗？每次内存会上涨多少呢？是用的什么版本呢？

**Comment by Danie1s** [comment]
用的是最新版本，你可以直接用你提供的demo试试
