### ISSUE TITLE
昨天更新后一大堆Block pointer is missing a nullability type specifier报错,不是警告,是报错

### ISSUE THREAD

**Issue by LRAYF** [banchichen/TZImagePickerController#494]
咋办

**Comment by banchichen** [comment]
你好，把TZPhotoPreviewCell.m文件的nullable删除吧。就不会报错了。

下一版我会删除这里，这次你就在代码里直接改吧...

**Comment by banchichen** [comment]
Hi, 好像光删那个不够哈，还得把其他的nullable、nonnull都删掉...
最新代码已经修正了这个问题，已经提交了，这个周日应该会发一版哈，你可以先直接改我的代码...
