### ISSUE TITLE
为什么进入相册的时候，返回按钮图片是我之前导航栏返回的图片，而不是自定义的图片

### ISSUE THREAD

**Issue by farewell17** [banchichen/TZImagePickerController#495]

**Comment by banchichen** [comment]
你好，TZAlbumPickerController页面的viewWillAppear方法里，有执行设置backBarButtonItem的代码：
`    self.navigationItem.backBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:[NSBundle tz_localizedStringForKey:@"Back"] style:UIBarButtonItemStylePlain target:nil action:nil];
`

**Comment by farewell17** [comment]
好的，谢谢。

**Comment by shaolelng** [comment]
您好，我想请问一下，您自定义的相册返回按钮的点击事件响应吗？

**Comment by lixiaonan** [comment]
@banchichen 只能修改源码, 来修改back按钮的图片吗? 不想文字, 只想要纯图片, 只能修改源码吗? 谢谢

**Comment by banchichen** [comment]
@lixiaonan  你好，可以试试写一个TZAlbumPickerController的分类，重载viewWillAppear方法，然后执行你自己的代码~
