### ISSUE TITLE
TZImageManager 消耗了 App 不必要的内存

### ISSUE THREAD

**Issue by InjoyDeng** [banchichen/TZImagePickerController#496]
TZImageManager 只是在 TZImagePickerController 项目中使用，但却是一个单例，常驻于内存，消耗
 App 4mb 内存。而对于很多 App 来说，大部分时间几乎并不需要操作这个对象，所以当使用完了 ImagePickerController，TZImageManager 就可以释放了。
可以在 ImagePickController、VideoPlayerController 等等释放后，释放 TZImageManager。或者在 TZImageManager 中加个函数，让开发者释放。

**Comment by banchichen** [comment]
释放了试了试，内存占用没什么变动...

你是如何认为TZImageManager的单例占用4M内存呢...？

研究了其他2个类似的图片多选库，第一次弹出图片选择器，再dismiss，内存占用上升了4.5M左右，相比之下TZImagePickerController的表现稍微好些，大约上升了4.1M左右...

具体原因不明...

**Comment by InjoyDeng** [comment]
用 Instruments 看的 TZImageManager 单例占用 4M 内存。

你试试我的代码呢，如果还不行，就从外部释放试试。我怀疑你释放后，在某处代码又创建了 TZImageManager。
```
static TZImageManager *manager;

static CGSize AssetGridThumbnailSize;
static CGFloat TZScreenWidth;
static CGFloat TZScreenScale;

+ (instancetype)manager {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        manager = [[self alloc] init];
        if (iOS8Later) {
            manager.cachingImageManager = [[PHCachingImageManager alloc] init];
            // manager.cachingImageManager.allowsCachingHighQualityImages = YES;
        }
   
        TZScreenWidth = [UIScreen mainScreen].bounds.size.width;
        // 测试发现，如果scale在plus真机上取到3.0，内存会增大特别多。故这里写死成2.0
        TZScreenScale = 2.0;
        if (TZScreenWidth > 700) {
            TZScreenScale = 1.5;
        }
    });
    return manager;
}

+ (void)deallocManager {
    manager = nil;
}
```
