### ISSUE TITLE
剪裁时，如果裁剪框尺寸大于图片尺寸，希望将图片放大到超过裁剪框

### ISSUE THREAD

**Issue by AlleniCode** [banchichen/TZImagePickerController#497]
有办法设置剪裁时候可以默认图片填充剪裁框吗？（图片显示不全无所谓，只要选中后，初始状态下照片的宽高能填充满所设置的剪裁框的大小）O(∩_∩)O谢谢！

**Comment by AlleniCode** [comment]
就像微博上传头像一样

**Comment by banchichen** [comment]
抱歉，没听懂‘默认图片填充裁剪框’是什么意思...

**Comment by aizexin** [comment]
选择过一次剪切图片后，及时关闭剪切功能后也不能全选

**Comment by banchichen** [comment]
@aizexin 开启裁剪的时候，图片最大可选张数被设置为了1，关闭裁剪后，你要再改一下Demo界面的图片最大可选张数

**Comment by AlleniCode** [comment]
就是选中一张照片，然后进入剪裁预览界面时，因为图片有大有小，剪裁框可能框出的区域大于选中的图片（我知道可以手动缩放图片，使其可以填充剪裁框），但是有没有方法设置选中的图片直接可以填充满设置的剪裁区域的大小呢？（如果我说的不清楚的话，麻烦加我的QQ3075504778，谢谢！）

**Comment by banchichen** [comment]
明白了... 就是：剪裁时，如果裁剪框尺寸大于图片尺寸，希望将图片放大到超过裁剪框  对吧...
可以做的，在裁剪页面，判断下图片尺寸是否小于裁剪框尺寸，如果小于，就将图片放大...
下次考虑优化这里哈...

**Comment by banchichen** [comment]
我上次试着优化了下这里，发现不是很好做。我将图片小于裁剪区域时对图片进行放大，测试了多次发现会引发其它的一些问题...特别是在裁剪状态下...

如果对裁剪的要求比较高的话，建议选择器dismiss后再去裁剪，配合[PhotoTweaks](https://github.com/itouch2/PhotoTweaks)使用~

我这个库暂时不打算升级裁剪功能哈...
