### ISSUE TITLE
进入“我的照片流”卡住（没有崩溃）

### ISSUE THREAD

**Issue by lihuaqigh** [banchichen/TZImagePickerController#498]
流程：弹出相机胶卷点击返回，在进入“我的照片流”，卡住
这个问题只有在连接Xcode运行状态下会出现。不用Xcode运行则不会卡住。
iPhone7，10.3.2

**Comment by banchichen** [comment]
当时我也发现过类似的问题，连线调试时会偶发比较奇怪的卡顿，非调试状态又是好的....

**Comment by zhuzhiyongai** [comment]
线程问题：
![Uploading image.png…]()

**Comment by zhuzhiyongai** [comment]
线程问题：
在全局线程中调用了UI
- (void)configTableView {
    if (![[TZImageManager manager] authorizationStatusAuthorized]) {
        return;
    }

    if (self.isFirstAppear) {
        TZImagePickerController *imagePickerVc = (TZImagePickerController *)self.navigationController;
        [imagePickerVc showProgressHUD];
    }

    dispatch_async(dispatch_get_global_queue(0, 0), ^{
        **TZImagePickerController *imagePickerVc = (TZImagePickerController *)self.navigationController;**
        [[TZImageManager manager] getAllAlbums:imagePickerVc.allowPickingVideo allowPickingImage:imagePickerVc.allowPickingImage needFetchAssets:!self.isFirstAppear completion:^(NSArray<TZAlbumModel *> *models) {

**Comment by banchichen** [comment]
@zhuzhiyongai 你这块代码好像不是最新的，可以参考最新版
