### ISSUE TITLE
iPad横竖屏切换时 table宽度错误

### ISSUE THREAD

**Issue by andyden9** [banchichen/TZImagePickerController#499]
![27365121-ee946dc8-5670-11e7-907b-f3a9b723dc85](https://user-images.githubusercontent.com/14224413/27465787-482f6692-5808-11e7-98d4-1219572b8279.png)

理论上iPad不应该支持进入picker时切换方向啊，iPhone就不行。试了覆盖shouldAutorotate也关不掉

**Comment by andyden9** [comment]
如果iPhone横屏进入，也有类似问题：

![simulator screen shot 2017 6 23 11 39 15](https://user-images.githubusercontent.com/14224413/27465826-97218dac-5808-11e7-83ea-a8cbce2eb9d0.png)

**Comment by banchichen** [comment]
你好，1.8.4版本已发布，已支持横屏。
