### ISSUE TITLE
第二次进入相册时，怎么默认选中第一次已选的图片

### ISSUE THREAD

**Issue by ZLIRYFIRYF921002** [banchichen/TZImagePickerController#50]
第二次进入相册时，怎么默认选中第一次已选的图片

**Comment by tooodooo** [comment]
保存一个TZImagePickerController变量，下次打开还是它就OK了

**Comment by banchichen** [comment]
你好，每个asset对象都有一个唯一标示的，如果要做默认选中上一次已选择的图片，你每次创建和显示TZImagePickerController时，要给我传一个asset数组，告诉我你目前已选择了哪些图片。然后我在里面判断一下...    我这个是模仿微信做的，微信也没有做这个效果...不过思路就是这个思路...

**Comment by banchichen** [comment]
你好，我刚刚更新了1.3.0版本，该功能已经加上去了~谢谢支持~
