### ISSUE TITLE
可以添加选择视频时的限制时长和视频编辑功能类似微信。

### ISSUE THREAD

**Issue by qixizhu** [banchichen/TZImagePickerController#500]

**Comment by banchichen** [comment]
你好：
1. 限制视频时长，请参考Demo和API说明，实现代理方法：
// 决定asset（照片/视频）显示与否
- (BOOL)isAssetCanSelect:(id)asset；

2. 这是已有issue...
优先级低，未来可以考虑...

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/390
