### ISSUE TITLE
cocospod下和demo中的有些差异

### ISSUE THREAD

**Issue by lvjsky** [banchichen/TZImagePickerController#502]
cocospod 下来的和你的demo中的有些差异：
TZImageManager.h 中 cocospod下来的 
- (void)getVideoWithAsset:(id)asset progressHandler:(void (^)(double progress, NSError *error, BOOL *stop, NSDictionary *info))progressHandler completion:(void (^)(AVPlayerItem * _Nullable, NSDictionary * _Nullable))completion;

存在_Nullable 导致警告，但是demo中的则没有_Nullable

**Comment by banchichen** [comment]
是哈，最新的代码还没发版本...

**Comment by banchichen** [comment]
Hi, 最新版1.8.2已发出~
