### ISSUE TITLE
照片流中的图片很多时，迅速滑动查看图片会出现卡屏现象

### ISSUE THREAD

**Issue by liuliang1991** [banchichen/TZImagePickerController#503]
进入我的照片流，图片很多（有一千张左右）,然后迅速上下来回滑动查看图片cpu就会飙到100+%以上，然后就卡屏了

**Comment by liuliang1991** [comment]
上面的机型:iphoneSE, 系统：9.3.2

**Comment by banchichen** [comment]
1000多张理论上不会出现这种情况，我自己的手机上有2000多张，使用上没什么问题...

是1.8.1的版本吗？
不是连线调试状态对吧？（连线调试的时候会有偶发的奇怪的卡顿）

**Comment by liuliang1991** [comment]
@banchichen 是连线测试的，不连线的话暂时没这个问题

**Comment by banchichen** [comment]
OK，连线情况确实有奇怪的卡顿...原因暂时未知...
