### ISSUE TITLE
iCloud图片问题

### ISSUE THREAD

**Issue by 78084367** [banchichen/TZImagePickerController#504]
iCould图片选择问题
例：如果选择9个未下载的iCloud图片，加载很漫长，一直不能点击完成来获取这些图片，体验不友好。
建议把选中iCloud图片的事件，发个代理或block给开发者
如：- (BOOL)imagePickerControllerShouldSelCloudImage:(TZImagePickerController *)picker
交给实际需求的开发者，是否允许选择iCloud图片吧；开发者可以自己在这个代理中返回NO不允许选择
并展示自定义ui来告诉用户“先下载下来的温馨提示”（如qq选择iCloud图片的提醒）

**Comment by banchichen** [comment]
你好，QQ当时的这个处理其实很不妥，这让用户直接无法选择iCloud图片，我当时是很反感这个设计的，只有QQ在发送iCloud图片时，我必须在相册里也找到这个图片，等待下载完毕，再返回QQ选择这个图片。

iCloud图片下载的等待时间没有变短，还让用户多了两次应用的跳转和在相册里多搜寻一次图片，不是更加不友好么...

刚刚又试了下QQ，已经改过来了，会在选择器里直接下载。估计被用户喷了。
