### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by hyuproject** [banchichen/TZImagePickerController#506]
在相册选择器中上下滑动，内存增长飞快，等内存达到650M左右demo崩溃

**Comment by banchichen** [comment]
很奇怪，我这6s上2000多张图片，来回多次滑动，内存还是20多M的，只涨了6M不到...

**Comment by hyuproject** [comment]
我用的是6,运行的是下载的demo

**Comment by hyuproject** [comment]
为什么换了个台机子就没有这个问题，很烦躁- -
