### ISSUE TITLE
只要视频列表，能获取到视频的名字吗

### ISSUE THREAD

**Issue by BlackCatSun** [banchichen/TZImagePickerController#507]

**Comment by BlackCatSun** [comment]
能获取到视频的名字吗

**Comment by banchichen** [comment]
你好，视频名字的获取和图片名字获取是一样的，参照Demo里图片名字的获取方法：`printAssetsName:`

**Comment by BlackCatSun** [comment]
嗯呢可以的，在相册获取的名字都是IMG格式的，不能保留原有的视频名字是吧

另外不带导航栏的获取相册的视频布局能实现吗（图片右侧为要实现的获取相册的视频和视频的名字）
![14](https://user-images.githubusercontent.com/25749083/27860025-68781116-61ad-11e7-8715-742f8a10d9a3.jpg)

**Comment by banchichen** [comment]
如果保存视频的时候保存了名字，那么获取的时候应该是有名字的，否则就是取的系统命名。

图片右侧的布局不就是个UITableView么，可以实现的，建议你参考我的源码，获取到当前设备的所有视频，图片右侧的页面就可以有数据了。
