### ISSUE TITLE
获取原图片问题

### ISSUE THREAD

**Issue by 78084367** [banchichen/TZImagePickerController#508]
直接在获取图片完成的回调代理方法中，通过TZImageManager获取原图片不能完成!
通过afterDelay 可以完成原图获取

#pragma mark TZImagePickerController Delegate
- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray<UIImage *> *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto
{
    [self performSelector:@selector(handleImage:) withObject:assets afterDelay:0.1];
}

#pragma mark TZImage 获取原图片
- (void)handleImage:(NSArray *)assets
{
    if (assets.count > 0)
    {
        WeakSelf(ws);
        [YYMaskHealper showWithStatus:@"正在处理图片..."];
        for (NSInteger i = 0; i < assets.count; i ++)
        {
            id obj = assets[i];
            [[TZImageManager manager] getOriginalPhotoWithAsset:obj completion:^(UIImage *photo, NSDictionary *info)
             {
                 NSString *logStr = [NSString stringWithFormat:@"第%lu个图片，size：%@",(unsigned long)i,NSStringFromCGSize(photo.size)];
                 NSLog(@"%@", logStr);
                 [ws.originalPhotoArr addObject:photo];
                 YYMAIN(^{
                     CFRunLoopStop(CFRunLoopGetCurrent());
                 });
             }];
            CFRunLoopRun();
        }
        [YYMaskHealper dismissHUD];
        [_collectionView reloadData];
    }
}

**Comment by banchichen** [comment]
这个应该不是库的问题吧...

可能是由于didFinishPickingPhotos方法在子线程执行，handleImage:操作了UI，应该在主线程执行。建议dispatch切换到主线程再调handleImage:试试...

**Comment by 78084367** [comment]
#pragma mark TZImagePickerController Delegate
- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray<UIImage *> *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto
{
    NSLog(@" 当前线程：%@",[NSThread currentThread]);
    NSLog(@" 主线程：%@",[NSThread mainThread]);
    // 直接在代理方法 获取原图片 不走回调
//    [self performSelector:@selector(handleImage:) withObject:assets afterDelay:0.1];
    dispatch_async(dispatch_get_main_queue(), ^{
        [self handleImage:assets];
    });
}

之前也考虑过线程问题，打印多次发现都在主线程中
 [第430行]  当前线程：<NSThread: 0x174262e00>{number = 1, name = main}
[第431行]  主线程：<NSThread: 0x174262e00>{number = 1, name = main}

用gcd调用处理图片方法依旧卡住不执行
还没找到原因，我在找找

**Comment by banchichen** [comment]
比较奇怪，我留意一下这里，有新情况我再来和你同步一下哈
