### ISSUE TITLE
单图选择模式+允许剪裁的情况下，会有内存泄漏

### ISSUE THREAD

**Issue by vvard3n** [banchichen/TZImagePickerController#509]
选一张图几m，多选几次就百多m内存占用了。。。

**Comment by vvard3n** [comment]
版本为1.8.1
系统为ios10
demo可以重现问题

**Comment by vvard3n** [comment]
<img width="1792" alt="2017-07-07 3 10 49" src="https://user-images.githubusercontent.com/6638211/27947112-1e31b15e-6327-11e7-8a04-f35f53013c75.png">

**Comment by banchichen** [comment]
我这复现不出来咦...

1.8.1倒是有一个照片预览页的泄漏问题，在最新版1.8.2修复了~

如果还是发现内存只升不降的情况，希望能用Memory Graph或者Leaks帮忙测试一下哈，谢谢~
