### ISSUE TITLE
点击拍照, 拒绝授权, 再次点击, 进入设置页面, 打开拍照权限, 回到app, 会闪退或重启app

### ISSUE THREAD

**Issue by lixiaonan** [banchichen/TZImagePickerController#510]
点击拍照, 拒绝授权, 再次点击, 进入设置页面, 打开拍照权限, 回到app时, 我的项目会闪退, Demo中重现出来的是重新启动!

**Comment by lixiaonan** [comment]
百度了一翻, 好像是苹果爸爸干的事情!!!       如果有这个问题的话, 我觉得是不是不要跳设置会比较好

**Comment by banchichen** [comment]
你好，也不能说是闪退，重启更贴切些。

不跳设置的话，那用户就要手动去设置页打开权限，打开权限的结果还是应用重启，结果都是一样的，为啥不给用户提供方便呢...
