### ISSUE TITLE
上线问题

### ISSUE THREAD

**Issue by huangshun11** [banchichen/TZImagePickerController#511]
Your app accesses and displays the contents of the OS filesystem outside of its designated sandbox. Specifically, This app contains code or network references to a piracy App Store. It would be appropriate to remove these references before resubmbitting for review

For security purposes, apps are contained within a sandbox environment. Interaction with other apps, or the rest of the OS, can only be done through the use of public interfaces, such as UIImagePickerController, available in the iOS SDK. Directly accessing files and folders outside of your sandbox is not permitted except through these public interfaces.

**Comment by huangshun11** [comment]
相册权限关掉仍然能访问相册。

**Comment by banchichen** [comment]
你好，TZImagePickerController访问系统相册是通过系统库Photos和AssetsLibrary进行的，是完全正规的方式....

Demo里，没有相册权限时，页面是会提示去开启权限，无法访问到相册的，不存在无权限时也能访问到相册的情况。建议检查下你项目中的其他库...
