### ISSUE TITLE
好像选出来的图片最大的width是750 能否修改这个数字

### ISSUE THREAD

**Issue by huang59160537** [banchichen/TZImagePickerController#513]

**Comment by Allansk2** [comment]
可以用imagePickerVc.photoWidth = 1200;修改

**Comment by huang59160537** [comment]
为什么我还是没用，我试过了

**Comment by xingfuqiu** [comment]
同样的问题,设置了 photoWidth 还是不行,如下图:

![2017-07-13 12 39 24](https://user-images.githubusercontent.com/391606/28150646-37da1a92-67c8-11e7-9f9b-ad7ad656b8dc.png)

**Comment by Allansk2** [comment]
要不试一下直接改源码，把下面的photoWidth 改成你想要的，以及保证你的图片原来的size大于设置的。在TZImagePickerController里

- (void)configDefaultSetting {
    self.timeout = 15;
    self.photoWidth = 828.0;
    self.photoPreviewMaxWidth = 600;
    self.naviTitleColor = [UIColor whiteColor];
    self.naviTitleFont = [UIFont systemFontOfSize:17];
    self.barItemTextFont = [UIFont systemFontOfSize:15];
    self.barItemTextColor = [UIColor whiteColor];
    self.allowPreview = YES;
    
    [self configDefaultImageName];
    [self configDefaultBtnTitle];
}

**Comment by xingfuqiu** [comment]
@Allansk2 试过,不行哈

> 要不试一下直接改源码，把下面的photoWidth 改成你想要的，以及保证你的图片原来的size大于设置的。在TZImagePickerController里

**Comment by huang59160537** [comment]
怎么感觉不是这个属性？因为他说了这个属性默认是828，可是实测是750

**Comment by banchichen** [comment]
Hi，是库的问题哈，获取图片的时候，全屏图直接以屏幕像素宽为导出图片宽度哈。

最新版1.8.2已修复这个问题，photoWidth的设置可以生效了哈。
