### ISSUE TITLE
对于 gif 是不是只能选择一张？

### ISSUE THREAD

**Issue by chenfengfeng** [banchichen/TZImagePickerController#514]
如果由于 gif 需要完整的 data 才可以的话
理论上是可以多 gif 选择的
目前情况是选择了一张 gif 后再选一张 gif 会提示选择照片时不能选择 gif

**Comment by banchichen** [comment]
这个是之前参考的微信的逻辑，gif只能选一张，且不能和图片一起选...

微信的已经改了，我这边还没有...

**Comment by chenfengfeng** [comment]
😂但至少提示要改下，应该提示只能选一张 gif 而不是“选择照片时不能选择 gif”

**Comment by banchichen** [comment]
是这样的，在多选图片时，从预览页面打钩选中的视频/gif是默认当做静态图处理的，所以你在预览页面打钩的视频、gif，实际是一张图片。

所以你再在照片列表页选gif时，提示是"选择照片时不能选择 gif"

不过视频处理得好一些，在预览页面打钩时，会提示："多选状态下选择视频，默认将视频当图片发送"

**Comment by chenfengfeng** [comment]
感谢解答~
