### ISSUE TITLE
这........

### ISSUE THREAD

**Issue by lixiaonan** [banchichen/TZImagePickerController#516]
![image](https://user-images.githubusercontent.com/13104094/28309581-606171fa-6bdc-11e7-820f-c10882e14747.png)
最新版,

**Comment by banchichen** [comment]
是指本地化的问题对吧？
这个情况，说明你应用内设置的语言是中文，但系统设置语言的是英文。
把info.plist文件里的Localization native development region设置去掉，语言就都跟随系统语言了。

**Comment by lixiaonan** [comment]
@ @banchichen 不是啊, 内容偏移了, 我只有7张图片, 一进来的时候内容有点往上偏移

**Comment by banchichen** [comment]
是我的Demo还是在你项目中呢？
有改动了TZImagePickerController导航控制器的什么属性吗？
我也有2个项目用了最新版，没出现这个情况

**Comment by lixiaonan** [comment]
@banchichen你好, 是在我项目中的, 首先, 我集成新版的时候, 也不记得第一次使用时是不是正常的,忘记了,  我想尝试着自定义下UI, 就创建了一个类继承TZImagePickerController, 然后在里面修改了nav的颜色, 增加一条分割线等等, 就出现了这样的情况.
之后, 我删掉了自定义, 尝试使用原生的TZImagePickerController, 发现还是这样, 我现在使用1.7.9版本正常

**Comment by banchichen** [comment]
我刚刚下了个Demo，在我这边是正常的，我继续观察下...

**Comment by banchichen** [comment]
和这个问题应该是同一个...
https://github.com/banchichen/TZImagePickerController/issues/519
