### ISSUE TITLE
已经设置了self.imagePicker.selectedAssets = _selectedAsset;但是选择的张数不同步

### ISSUE THREAD

**Issue by tyfinal** [banchichen/TZImagePickerController#518]
我选择三张以后然后删除一张。此时输出打印_selectedAsset的值已经变化了。然后在下次点击打开选择相册按钮的时候我执行了上面那句。但是相册打开以后我已经点击删除那张选中状态没有改变。我跟踪到 - (void)setSelectedAssets:(NSMutableArray *)selectedAssets   这边值也是没有问题的。

**Comment by banchichen** [comment]
你好，有更详细的资料吗？
这个功能很难出错，大家都在用，还没发现过有问题...
我这边无法复现这个情况...

建议自己再详细调试下看看：
1. 是否所有图片都有这个问题？
2. 如果只是某些图片有问题，这些图片的特征是什么？
3. Demo是否正常？应用里是否对选择器做了什么特殊设置？

**Comment by tyfinal** [comment]
demo是正常的。要说不同的话，我只是删除了里面一些nullable那些东西，因为警告看着有点烦，我想不至于会影响吧。
是所有图片都会有影响的。
 只设置了这个  _imagePicker.allowPickingVideo = NO;

**Comment by tyfinal** [comment]
还有另外一个小问题想问下。就是我看你这个是选完图片点击完成返回的是所有选择的图片。我现在想知道每次新增加的是哪几张图片。有什么办法嘛，谢谢了。

**Comment by banchichen** [comment]
这些改动倒和selectedAssets没啥关系....
要不更新到最新的版本/代码试试~？
nullable的警告在1.8.2+版本上处理了~

对了，其他设备也这样吗~？模拟器呢~？

**Comment by tyfinal** [comment]
恩，貌似跟设备没关系的。模拟器跟测试机都有那种问题。我看demo上就没有，所以不知道怎么弄的。我先更新一下看看吧。不知道是不是我改动粗问题了。

**Comment by banchichen** [comment]
好，如果同一个设备Demo正常你应用里有问题...那应该是哪里不小心改坏了吧...

**Comment by 350541732** [comment]
@banchichen 懒加载下的VC selectedAssets删除后显示的还是上一次显示的照片。姿势不对？
    lazy var imagePickerVC:TZImagePickerController = {
        let pickerController = TZImagePickerController(maxImagesCount:1, columnNumber:3, delegate:self, pushPhotoPickerVc: true)
        pickerController!.allowPickingVideo = false
        pickerController!.allowTakeVideo = false
        pickerController!.allowPickingGif = false
        pickerController!.sortAscendingByModificationDate = false
        pickerController!.selectedAssets = selectedAssets
        pickerController!.allowPickingOriginalPhoto = false
        pickerController!.showSelectedIndex = true
        pickerController!.showSelectBtn = true
        return pickerController!
    }()
PS:需要时创建VC 没问题

**Comment by banchichen** [comment]
对，暂不支持懒加载的，每次都创建一个新的吧
