### ISSUE TITLE
UI顶部少了22像素

### ISSUE THREAD

**Issue by dwanghello** [banchichen/TZImagePickerController#519]
![03614c44cd6176d32356453aedad9c4a](https://user-images.githubusercontent.com/15830996/28518406-51ef7e56-709a-11e7-9b79-3cd686b3fed1.png)

**Comment by banchichen** [comment]
Hi, 请问是用Demo测出来的吗？
有对TZImagePickerController做了什么设置吗？

**Comment by dwanghello** [comment]
没有做其他设置。demo也有问题 我我试了。默认不是顶部的。

**Comment by dwanghello** [comment]
#516和我的问题一样啊。都是内容偏移

**Comment by dwanghello** [comment]
最新系统10.3.3出现的问题 demo也有问题 之前么有

**Comment by banchichen** [comment]
不过我的手机就是10.3.3的...

我试了一下，在info.plist里将Status bar is initially hidden设置为YES，同时在Demo页面viewDidLoad方法里加入 [UIApplication sharedApplication].statusBarHidden = NO; 

此时的界面会是顶部少20像素，状态栏的高度没算上去...

你那里是这样设置的吗？

**Comment by dwanghello** [comment]
是的0.0。有什么解决方案吗？

**Comment by dwanghello** [comment]
我用的其他的库，设置了NO

**Comment by banchichen** [comment]
我现在把修复的代码提交了，如果你没有用pod的话，可以直接下最新的代码替换下。

如果用了pod，我刚刚发布1.8.5版本，更新一下~

如果搜索不到1.8.5版本，先执行下pod setup

**Comment by dwanghello** [comment]
ok 🙏
