### ISSUE TITLE
result = [self fixOrientation:result];纠正图片方向时会导致图片占用内存暴增

### ISSUE THREAD

**Issue by ETmanwenhan** [banchichen/TZImagePickerController#52]
result = [self fixOrientation:result];纠正图片方向时会导致图片占用内存暴增，希望大神想到更好的方案解决内存占用高的问题

**Comment by banchichen** [comment]
你好，麻烦更新到1.4.0版本试试~ 1.4.0版本性能已经比较不错了，滑动帧数平均在57-58左右，媲美QQ的图片选择器，略好于微信的图片选择器。我这段时间都没有发现内存占用高的问题，内存占用一直比较正常，应该不是fixOrientation导致的吧~？当然在快速滑动的时候，CPU有时候会占用很高，但我测试了QQ和微信的图片选择器，都有这个问题，苹果官方的Demo也是如此。帧数测试截图可以看博客中的截图~http://www.jianshu.com/p/1975411a31bb

**Comment by ETmanwenhan** [comment]
太感谢大神了，我有空一定换，谢谢！！！

**Comment by banchichen** [comment]
不客气~ 到时候不要直接更新到1.4.0哈~  记得更新到最新版，现在已经1.4.2咯~
