### ISSUE TITLE
同时获取4张4兆以上大图导致内存暴涨

### ISSUE THREAD

**Issue by LUJYM** [banchichen/TZImagePickerController#520]
你好 请问我用你的那个获取原图的方法同时获取4张几兆以上的大图 获得之后 TZImagePickerController也销毁了 但是内存就是暴涨 下不来 还导致崩溃 请问这是什么原因

**Comment by banchichen** [comment]
你好，高清的图取原图时是要特别小心的，返回的原图UIImage对象占用内存特别多，全景图可能达100多M...
占用内存的是这个UIImage对象，建议取原图一次只取一张，同时用完之后记得把这个UIImage销毁掉~

TZImagePickerController倒不占用多少内存~

**Comment by LUJYM** [comment]
你好 因为我取出原图之后 要显示在控制器上 所以这个uiimage应该是等控制器销毁过后才销毁吧 一次多选四张4m原图的时候 开始没问题 tzimagpick也销毁了 我上传的时候内存暴涨 然后一下到600m 就闪退了 多选4张小图没有问题 所以想请问下是什么原因 要怎么解决呢 谢谢了

**Comment by banchichen** [comment]
你好，建议可以这样：
1. 显示在控制器上的时候，不要取原图显示，显示大图就够了。比如可以设置photoWidth为1600，显示和放大都够用了。如果是要全屏预览且必须显示原图，再取原图来显示，切换了之后就把原图销毁掉。
2. 上传的时候一张一张上传...微信发原图也是这样的，也是一张一张发送的...

原图就是图片太大，得到的UIImage对象占用的内存就是很大...
