### ISSUE TITLE
参考最新微信的选择图片预览功能

### ISSUE THREAD

**Issue by ZClee128** [banchichen/TZImagePickerController#521]
希望可以参考最新微信选择图片预览功能，做成那样的，可以优化gif图和jpg，处理大图的时候，可以快速选择，不要加载很久然后就超时获取不到图片了

**Comment by banchichen** [comment]
啊哈，微信目前最新的预览界面，就是多了一个展示已选图片缩略图的区域咯....
此外没什么不一样的了吧...
