### ISSUE TITLE
调用相机后点击取消无响应

### ISSUE THREAD

**Issue by ArronMe** [banchichen/TZImagePickerController#522]

**Comment by ArronMe** [comment]
麻烦帮忙看看怎么回事

**Comment by banchichen** [comment]
你好，直接下载Demo运行是正常的吧...

你在项目里做了什么事情呢？如果是在拍照页面，点击取消没有反应，看看是不是imagePickerControllerDidCancel的代理方法没走，如果没走，看看代理是不是设置的当前控制器，和代理是不是还活着....
