### ISSUE TITLE
present出来后界面图标缺失

### ISSUE THREAD

**Issue by QiJing13** [banchichen/TZImagePickerController#523]
demo没问题，但集成到项目里来就有问题了。请看截图对比，bundle文件是有在bundle resource 里面的啊
git不知道怎么传图片。。。。 传到网盘，http://pan.baidu.com/s/1eR7cIwa

**Comment by banchichen** [comment]
你好，是用pod方式还是直接拖到项目中的方式呢~？

获取图片的方法是在TZImagePickerController.m文件的最顶部，有一个imageNamedFromMyBundle的分类方法，你打下断点看看，里面返回的UIImage都是nil吗~？

**Comment by banchichen** [comment]
对了，你直接把图片拖到输入框里来，或者复制好图片在输入框里粘贴一下，就可以传图了~

**Comment by banchichen** [comment]
你好，刚刚发布了1.8.7版本，这个问题应该好了~

如果还有问题，请再回来评论下~

**Comment by QiJing13** [comment]
哦，这么快解决了？  就是没法读取那个category函数造成的。  我自己重新做了个category也不行， 最后用的土方法，直接把图片拉出来，用imagenamed 来获取的。。。。

**Comment by banchichen** [comment]
嗯啊...

这样啊，那你有空试试新版哈~就可以把拉出去的图片干掉了~
