### ISSUE TITLE
相册列表滑动内存暴涨——极个别设备

### ISSUE THREAD

**Issue by jiejianyou** [banchichen/TZImagePickerController#524]
来回滚动图片列表的话  会导致内存一直上升，不会下降

**Comment by banchichen** [comment]
你好，是涨到多少M呢，是最新的版本吗？
如果控制器dismiss了，内存会降吗？

**Comment by banchichen** [comment]
我这边2500张图片，来回滑动多次，也就涨了6M的样子...
iPhone6s iOS10.3.3

**Comment by jiejianyou** [comment]
我是来回滚动 直到程序闪退  用的是最新的demo   dismiss控制器  内存也不会下降

**Comment by jiejianyou** [comment]
还有就是我相册里的图片有的蛮大的(最大有5M多) 这些图片蛮多的

**Comment by banchichen** [comment]
奇怪了，在照片列表，取回来显示的图是缩略图，不会占多少空间的...

在预览页面，才会去取大图...

**Comment by jiejianyou** [comment]
![656c9d3feb0aeb054d0b356e710a4851](https://user-images.githubusercontent.com/19336708/28707106-a353dcc6-73a9-11e7-8c00-8f125dc4dfdb.jpg)
![9ac643dd-1893-415c-aeb5-3ede1f1543dc](https://user-images.githubusercontent.com/19336708/28707105-a3528772-73a9-11e7-9129-5fda1098025b.png)
我在所有照片列表里来回滚动的

**Comment by banchichen** [comment]
咦，是什么设备，什么系统~？
是不是iOS8以下的系统~？

**Comment by jiejianyou** [comment]
iPhone SE 系统版本是10.3

**Comment by banchichen** [comment]
好，我去找个iPhone SE看看...

**Comment by jiejianyou** [comment]
我拿了个iPhone 5S  试了试 好像没我遇到的这个问题 。。。

**Comment by banchichen** [comment]
确实很奇怪，你这个是特例...
可能只有你的这个手机才能重现...

可以用Xcode自带的Memory Graph看一下，看内存里存在哪些对象，找下原因...

**Comment by banchichen** [comment]
![default](https://user-images.githubusercontent.com/12755494/28708728-ecb54728-73af-11e7-9f75-9b5965a1f250.png)
这是我这里的Memory Graph，也是几千张图片，内存是比较正常的

**Comment by jiejianyou** [comment]
![94bec27f-9986-43da-9d97-c2b6d33e5606](https://user-images.githubusercontent.com/19336708/28708852-518b3be4-73b0-11e7-8dc3-44b551140cbe.png)

**Comment by jiejianyou** [comment]
![b1126e32-b236-4467-b164-26fc51f026ff](https://user-images.githubusercontent.com/19336708/28708941-afd9f582-73b0-11e7-98bb-91c05573ffe5.png)
为什么我下面还有这么多的东西

**Comment by banchichen** [comment]
选中一下右下角的按钮，只看当前项目的

**Comment by jiejianyou** [comment]
右下角那个啊   我不会用。。。
