### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by ZClee128** [banchichen/TZImagePickerController#525]
我之前是直接把代码拖进项目，然后修改了内部的UI，因为项目需求，现在如果pod最新版会有影响吗

**Comment by banchichen** [comment]
pod的话，UI会回到Demo里的风格...

可以看看最新版的Demo，在不改内部源码的情况下，能否实现你们目前的UI需求，如果能的话可以pod。不能的话，pod进去了，还是得修改源码才能满足你们的UI需求...
