### ISSUE TITLE
选择照片界面如何删除默认选中的项？

### ISSUE THREAD

**Issue by QiJing13** [banchichen/TZImagePickerController#526]
比如我选择了5张，在app中删除了2张，再进TZImagePickerController默认还是选择了这5张，怎么才能控制默认选中哪几张呢？ 谢谢

**Comment by banchichen** [comment]
你好，删除的时候，把_selectedAssets里的也删除。

详见Demo:
![default](https://user-images.githubusercontent.com/12755494/28709859-8d378b30-73b4-11e7-9036-3eb5c7afe925.png)

**Comment by QiJing13** [comment]
2个array中对应数据都删除了，但进去后还是有呢。 是在didFinishPickingPhotos 这个delegate中获取到self.imageArray = [NSMutableArray arrayWithArray:photos];
    self.assetArray = [NSMutableArray arrayWithArray:assets];   然后删除两个array中对应index，  present出照片选择界面结果里面还是之前选择的打了勾

**Comment by banchichen** [comment]
那应该是删除不成功...？

你那里Demo是好的吧...

**Comment by QiJing13** [comment]
我跟了代码删除是成功了的，里面数据确实少了，这种arrayWithArray都是指向同一内存地址，所以应该都删除了的。   demo是好的，我看demo里删除代码方式也和我一样的呀，只是获取图片是用的block方法，我是用的delegate方法，这个应该没啥问题的

**Comment by banchichen** [comment]
注意给picker的selectedAssets赋值的时候，赋值表达式右边的数组是否是删除后的...

赋值的selectedAssets有几个，选择器里已选中的就是几个，好好检查下代码吧。
