### ISSUE TITLE
无法通过返回键返回到初始页

### ISSUE THREAD

**Issue by guangwzh** [banchichen/TZImagePickerController#527]
我通过一个选图片的按钮跳转到TZImagePickerController里，右上角的item默认显示“取消”，左边返回的item是我项目里自己设置的返回按钮，点击第一下返回到照片列表，在照片列表里点击返回按钮就没有任何反应了，只能通过右上角的“取消”来回到初始页，这个bug好难受。我们项目时通过cocoapods集成的，也不好修改源码，请看一下我的问题，希望能解决掉，谢谢

**Comment by guangwzh** [comment]
而且我也没有找到可以修改leftBarButtonItem的方法和属性

**Comment by banchichen** [comment]
你好，你们这个交互有点奇怪。
微信、QQ、微博、QQ空间、QQ邮箱，都是用present来跳转到图片选择器的。点击取消则dismiss掉整个图片选择器。

你项目是push了图片选择器吗？

这种情况，你还是改源码吧...

或者采用主流的方式，present图片选择器

**Comment by guangwzh** [comment]
![img_3226](https://user-images.githubusercontent.com/25175909/28780004-cee20418-7637-11e7-832d-6f8e93524c49.PNG)
![img_3228](https://user-images.githubusercontent.com/25175909/28780008-d31137e8-7637-11e7-8fdc-2a0a6a29d2c2.PNG)
<img width="919" alt="2017-07-31 9 36 00" src="https://user-images.githubusercontent.com/25175909/28780230-9b71e296-7638-11e7-9595-0447e186483a.png">

我看了代码并且很确定我们的项目是用的present，并没有使用push

**Comment by banchichen** [comment]
请问左侧的返回按钮，你是如何调出来的呢~？

**Comment by guangwzh** [comment]
没有做多余的操作，在github上我也把代码截图了，你应该也看了，跳转后自己就出来了




发自网易邮箱大师
在2017年07月31日 22:48，谭真 写道：

请问左侧的返回按钮，你是如何调出来的呢~？

**Comment by banchichen** [comment]
不可能的。图片库内部没有定义leftBarButtonItem的代码，你可以试试Demo，或者重开一个空白项目，会发现图片选择器表现是正常的。

建议排查下项目环境，是否在自己代码里/某个库里，重写了导航栏系统方法如pushViewController、或实现了导航栏代理方法，在这些方法里给viewController统一加了leftBarButtonItem。
