### ISSUE TITLE
圆形裁剪问题

### ISSUE THREAD

**Issue by OldBulls** [banchichen/TZImagePickerController#529]
裁剪完之后的图片，还是正方形？只不过是周围变成白边了，拿到图片后还要自己再弄成圆角么？

**Comment by banchichen** [comment]
你好，圆形裁剪后得到的图片就是圆的，白的只是背景。

**Comment by banchichen** [comment]
![default](https://user-images.githubusercontent.com/12755494/28777530-1aa0e48c-762e-11e7-87be-500a310f0cb1.png)

**Comment by lg1-09** [comment]
> 裁剪完之后的图片，还是正方形？只不过是周围变成白边了，拿到图片后还要自己再弄成圆角么？

需要把拿到的图片转成PNG格式的图片再使用就不会有这个问题。不进行图片格式转换就会出现保存到相册有白色背景的矩形。亲测！

**Comment by lg1-09** [comment]
> 你好，圆形裁剪后得到的图片就是圆的，白的只是背景。

亲测是图片格式问题，转场PNG格式后再使用或者保存到相册就不会出现楼主描述的矩形白色背景问题。
