### ISSUE TITLE
大神你好,我有个需求点击头像可以通过相册和相机中获取,看您框架中通过相机获取只能先进入相册

### ISSUE THREAD

**Issue by losedMemory** [banchichen/TZImagePickerController#530]
现在主流app都会给出两个选项,我想直接通过相机获取然后再进行裁剪,不知道您的框架可不可以实现

**Comment by banchichen** [comment]
你好，在Demo中打开这个开关：
![default](https://user-images.githubusercontent.com/12755494/28862826-1f095c36-7799-11e7-818b-5b28d2fad45b.png)

**Comment by losedMemory** [comment]
嗯,我是想拍完照之后跳转到裁剪的界面,不知可以吗

**Comment by losedMemory** [comment]
我知道怎么做了,多谢指点!
