### ISSUE TITLE
首次进入照片选择时顶部导航栏返回按钮显示为英文“back”

### ISSUE THREAD

**Issue by pp1232** [banchichen/TZImagePickerController#531]
在第一次进入照片选择时,顶部导航的左侧返回按钮显示为英文的"back"
点击一次"back"后再次进入照片选择时才显示为中文。
调试后发现TZImagePickerController.m文件中的TZAlbumPickerController类的viewWillAppear:在第一次打开是不会进入，因此其中设置导航的返回按钮的Title的代码(如下)不会执行。
```
// 1.6.10 采用微信的方式，只在相册列表页定义backBarButtonItem为返回，其余的顺系统的做法
    if (self.isFirstAppear) {
        self.navigationItem.backBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:[NSBundle tz_localizedStringForKey:@"Back"] style:UIBarButtonItemStylePlain target:nil action:nil];
        self.isFirstAppear = NO;
    }
```
目前将该代码移到TZAlbumPickerController类的viewDidLoad后，能够在首次时可以正常显示
不知道这是不是一个小小的bug

**Comment by banchichen** [comment]
你好，请参考这个issue下我的回复：https://github.com/banchichen/TZImagePickerController/issues/443
