### ISSUE TITLE
选择图片完成后，会有一个返回延迟消失

### ISSUE THREAD

**Issue by cirelir** [banchichen/TZImagePickerController#533]
![2017-08-03 2 27 08](https://user-images.githubusercontent.com/15341952/28908761-de124890-7857-11e7-8901-cf31df259a00.png)
如何取消

**Comment by banchichen** [comment]
这个返回真的是TZImagePickerController的吗...

Demo是正常的吧....

我也有多个项目用了TZImagePickerController，没遇到过这样的哦...

**Comment by cirelir** [comment]
真的是这个的，https://github.com/netease-im/NIM_iOS_UIKit这个库里面用的

**Comment by banchichen** [comment]
Demo是正常的...

你这个问题已经提交给NIM_iOS_UIKit...
