### ISSUE TITLE
1.8.7的几个问题

### ISSUE THREAD

**Issue by walteriOS** [banchichen/TZImagePickerController#535]
1.containsString引起的闪退
2.allowPickingGif 属性判断有误
3.相册列表中相册名称字体没加粗、没居中
4.设置 autoDismiss = NO 的时候，点击视频预览页面的完成按钮后，回调没有被调用的问题。Pull requests: https://github.com/banchichen/TZImagePickerController/pull/515 相同的Issues: https://github.com/banchichen/TZImagePickerController/issues/439
5.已隐藏相册感觉不应该显示

1.containsString引起的闪退，iOS6、iOS7下闪退
![image](https://user-images.githubusercontent.com/30791743/29016618-b710f6ca-7b85-11e7-8af6-259e7442525c.png)

2.allowPickingGif 属性判断有误，!应该去掉
![image](https://user-images.githubusercontent.com/30791743/29015640-6eddd2a0-7b81-11e7-8bc4-59c6e1d2da97.png)

3.相册列表中相册名称字体没加粗、没居中
![image](https://user-images.githubusercontent.com/30791743/29016035-3d5d9d08-7b83-11e7-8914-2c0fe9fdc8bc.png)

4.设置 autoDismiss = NO 的时候，点击视频预览页面的完成按钮后，回调没有被调用的问题。Pull requests: https://github.com/banchichen/TZImagePickerController/pull/515 相同的Issues: https://github.com/banchichen/TZImagePickerController/issues/439
![image](https://user-images.githubusercontent.com/30791743/29016212-0b17a540-7b84-11e7-9f54-37e8d74624f8.png)

5.已隐藏相册感觉不应该显示
![image](https://user-images.githubusercontent.com/30791743/29016224-320265e6-7b84-11e7-8bcc-e2348c6e92c4.png)

**Comment by banchichen** [comment]
你好：
1&4：谢谢指出，PR已经合并了~ containsString的问题我稍后提个commit~
2: 这里其实没问题哈，如果不允许选择gif时，遇到gif是当成图片处理的。
3: 居中确实应该好些，我稍后加一下，加粗倒没必要吧，许多相册都是不加粗的~
5: 谢谢指出，确实隐藏掉比较好~

**Comment by banchichen** [comment]
Hi , 刚刚发布了1.8.8版本，以上问题已经修复了哈~😊
