### ISSUE TITLE
裁剪时加个旋转功能吧

### ISSUE THREAD

**Issue by gxpzy** [banchichen/TZImagePickerController#537]
自己试了一下，我是旋转的`imageContainerView`，但之后就截取不到图片了= =，不知为何

**Comment by banchichen** [comment]
你好，如果对裁剪的要求比较高的话，建议选择器dismiss后再去裁剪，配合[PhotoTweaks](https://github.com/itouch2/PhotoTweaks)使用~

我这个库暂时不打算升级裁剪功能哈...

**Comment by gxpzy** [comment]
嗯嗯，好的。
