### ISSUE TITLE
1. 选择视频时也会调用setDidFinishPickingPhotosHandle 2.选择视频时，点击原图大小为0M

### ISSUE THREAD

**Issue by qq954499615** [banchichen/TZImagePickerController#538]
选择视频时，点击原图大小为0M；
问：我能否根据选择的图片或者视频获取到所在的URL路径，方便存取；
我获取视频的AVURLAsset后转为Data,为啥为空，求指教

**Comment by banchichen** [comment]
你好，如果是允许视频/gif/图片一起选的，则不管选啥，都是调didFinishPickingPhotosHandle。否则，只在视频预览页TZVideoPlayerController可以选视频，回调是didFinishPickingVideoHandle。

选择视频时，点击原图大小为0M，说明这个视频是存在iCloud中的，还没下载到本地，成功下载到本地后，就能获取到真实的视频大小了。这里我下次优化一下，如果是存在iCloud里，则去请求一下...

获取到视频的AVURLAsset后，选择器的使命基本完成了...建议可以参考下TZImageManager里的导出视频相关代码，在getVideoOutputPathWithAsset方法里...看看这个方法能不能正确获取到视频数据

**Comment by banchichen** [comment]
点击原图大小为0M的问题修复了~当图片从iCloud中加载完成后，会再刷新一下原图大小~
1.8.9版已发布~
