### ISSUE TITLE
如何在外面选择照片或者进行拍照

### ISSUE THREAD

**Issue by QiJing13** [banchichen/TZImagePickerController#539]
你好，需求需要在外面就进行选择照片或者拍照的选择。  我看demo有个外面选择的按钮， 但看代码这个takephoto的函数是封装在内部TZPhotoPickerController类中了，没法调用呢。 谢谢解答

**Comment by banchichen** [comment]
你好，Demo页也有相应的拍照代码的：
![default](https://user-images.githubusercontent.com/12755494/29272362-3cbd7e5e-8132-11e7-826b-e301c2d4392e.png)
