### ISSUE TITLE
发送原图并不是原图

### ISSUE THREAD

**Issue by horsley** [banchichen/TZImagePickerController#54]
第一是修正转向的时候导致图片重绘，丢失了原来拍照的exif信息，第二是重绘之后图片尺寸变大了很多

**Comment by banchichen** [comment]
你好，发送原图是不会把原图直接返给你的，否则内存会暴增，我是返给你了asset资源，可以通过TZImageManager类获取原图。重绘后的尺寸大小现在可以自定义了，默认是828像素宽。如果不修正转向的话，部分系统的部分照片会有照片颠倒的问题...有什么好的办法推荐吗？ 我只想到了这个...

**Comment by horsley** [comment]
我之前也研究过这个问题，目前还没有好的办法。

重绘修正转向会导致拍照exif信息丢失，新生成的文件和原文件大小不匹配（增大数倍）

看了一下微信的做法是不做修正的，由各个客户端自己做展示前的转向

**Comment by rain1458** [comment]
- (void)getOriginalPhotoWithAsset:(id)asset completion:(void (^)(UIImage *photo,NSDictionary *info))completion
使用这个方法获取原图, 有时候会重复获取,   获取渲染过(滤镜拍摄的图), 得到的图很小,  模糊不清

**Comment by banchichen** [comment]
/// Get full Image 获取原图
/// 该方法会先返回缩略图，再返回原图，如果info[PHImageResultIsDegradedKey] 为 YES，则表明当前返回的是缩略图，否则是原图。
- (void)getOriginalPhotoWithAsset:(id)asset completion:(void (^)(UIImage *photo,NSDictionary *info))completion;  
@Zhulmin   抱歉，方法注释没写好...这是新的方法注释...
