### ISSUE TITLE
allowPickingGif=NO还可以选择Gif图

### ISSUE THREAD

**Issue by Ssunnyy** [banchichen/TZImagePickerController#540]
在相册列表中 allowPickingGif = NO;进去提示不可以选择jif 点击其他图片看大图后滑动到gif图又可以选择。
建议 allowPickingGif = NO;直接不要在列表中显示gif。

![d4c20d2b004753a3ba15c9bf7a64d836](https://user-images.githubusercontent.com/7019575/29314469-97206a5e-8183-11e7-92c4-080e6f764f9c.png)
![13418520db51c03862c1ac84727bbbff](https://user-images.githubusercontent.com/7019575/29314373-50b5d9fa-8183-11e7-9006-250704e2ddda.png)

**Comment by banchichen** [comment]
咦，如果不允许选择gif的话，gif图是会被当做静态图处理的，不会有gif标识的，应该是上次做视频/gif/照片多选时把这里的逻辑改坏了...

建议你先这样做：
实现代理方法`- (BOOL)isAssetCanSelect:(id)asset;`，在这里判断asset如果是gif时返回NO，则gif就不会出现在列表里了~

**Comment by banchichen** [comment]
不允许选择gif图时，不再会显示gif标识~会当做静态图片处理~
1.8.9版已发布~

**Comment by Ssunnyy** [comment]
谢谢
