### ISSUE TITLE
Creating an image format with an unknown type is an error

### ISSUE THREAD

**Issue by Ssunnyy** [banchichen/TZImagePickerController#541]
在进入相机胶卷的时候 下滑时包的问题

![2017-08-16 9 11 50](https://user-images.githubusercontent.com/7019575/29343338-0507e4c6-81f6-11e7-9292-f83d75f43f47.png)

**Comment by banchichen** [comment]
你好，可以不用关心它...

详情参照：
[Creating an image format with an unknown type is an error Objective-C Xcode 8](https://stackoverflow.com/questions/40086636/creating-an-image-format-with-an-unknown-type-is-an-error-objective-c-xcode-8)
