### ISSUE TITLE
通过一个asset获得原图的方法返回的图片并不是原图,而是原图质量大小的五六倍

### ISSUE THREAD

**Issue by yuying2012** [banchichen/TZImagePickerController#542]
你可以通过一个asset获得原图，通过这个方法：[[TZImageManager manager] getOriginalPhotoWithAsset:completion:]
此方法返回的原图很大,我原图是1.8M但是这个方法返回的是6.7M
而我测试微信发送的原图,跟原图的大小是一致的,不知道怎么解决?

**Comment by banchichen** [comment]
你好，我这个方法只是返回UIImage对象，要获得图片二进制数据你得UIImagePNGRepresentation或者UIImageJPEGRepresentation一下对吧~？

我猜你是用了UIImagePNGRepresentation的压缩方式，这个方式是无损压缩，大小会变大的，你换成UIImageJPEGRepresentation试试~

**Comment by yuying2012** [comment]
谢谢您的回复,这两种方法都不能取到原始的图片质量,但是我从你的方法找到一个获取原始NSData的方法.已经解决了.再次感谢您的回复

**Comment by iosBob** [comment]
获取原始NSData的方法  怎么获取的

**Comment by banchichen** [comment]
@iosBob TZImageManager的requestImageDataForAsset

**Comment by githubLittleCode** [comment]
请问TZImageManager的requestImageDataForAsset这个方法返回的data数据可以直接上传到服务器吗，如果相册的图片方向不是向上的，这个data对应的图片方向会是正确的吗

**Comment by banchichen** [comment]
@githubLittleCode 可以试下，requestImageDataForAsset里面拿到的NSData是系统返回的

**Comment by githubLittleCode** [comment]
谢谢，测试了一下，用data直接上传，图片不是正的，方向没有修正，而且如果图片是HEIC格式的，直接data上传服务器会上传失败的，可能还是得使用getOriginalPhotoWithAsset方法获取原图后再进行上传操作
