### ISSUE TITLE
获取视频 url ，做视频压缩会出现 crash

### ISSUE THREAD

**Issue by yanglhan** [banchichen/TZImagePickerController#543]
使用 AVAsset 获取视频 URL ，处理 URL 时候 Log ： [GatekeeperXPC] Connection to assetsd was interrupted or assetsd died

**Comment by banchichen** [comment]
Hi，对于某一个视频，这个问题是必现的吗？网上许多资料指向内存问题，猜测可能是视频过大，但是光凭这个日志不好分析...
