### ISSUE TITLE
为什么我用说明中的方法使用时提示错误？

### ISSUE THREAD

**Issue by jennyket** [banchichen/TZImagePickerController#544]
TZImagePickerController *picker=[[TZImagePickerController alloc]initWithMaxImagesCount:1 delegate:self];
    [picker setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets) {
        
    }];
    [self presentViewController:picker animated:YES completion:nil];
第二句提示错误：
 Incompatible block pointer types sending 'void (^)(NSArray<UIImage *> *__strong, NSArray *__strong)' to parameter of type 'void (^)(NSArray<UIImage *> *__strong, NSArray *__strong, BOOL)'

**Comment by banchichen** [comment]
你更新到了新版是吧，API变了...

>     [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
        
    }];
