### ISSUE TITLE
相机好像不能在iOS11中打开

### ISSUE THREAD

**Issue by andyden9** [banchichen/TZImagePickerController#545]
iOS 11的适配需要帮忙吗？

**Comment by banchichen** [comment]
iOS11的适配目前只测试了模拟器，没测试真机...

真机测试时，打不开相机，控制台有什么日志吗~？

你来个PR吧~👍

**Comment by momo13014** [comment]
真机有打不开的可能性:

**Comment by momo13014** [comment]
真机有打不开的可能性：
（1）现象: 
单独跑你的Demo，真机是可以打开的，将你的代码添加到我的工程中，就获取不到照片。
（2）代码：
 TZImageManager Line：489行
[[PHImageManager defaultManager] requestImageForAsset... 获取到的result 为nil
 （3）参考信息：https://stackoverflow.com/questions/31037859/phimagemanager-requestimageforasset-returns-nil-sometimes-for-icloud-photos
（4）暂时解决办法(对我有用)：
  PHImageRequestOptions.networkAccessAllowed= YES(默认值为NO)
（5）Q: 
为什么单独Demo就没有问题，拉到大的项目中就有问题（都是真机）

**Comment by momo13014** [comment]
真机有打不开的可能性：
（1）现象:
单独跑你的Demo，真机是可以打开的，将你的代码添加到我的工程中，就获取不到照片。
（2）代码：
TZImageManager Line：489行
[[PHImageManager defaultManager] requestImageForAsset... 获取到的result 为nil
（3）参考信息：[result sometimes be nil](https://stackoverflow.com/questions/31037859/phimagemanager-requestimageforasset-returns-nil-sometimes-for-icloud-photos)
（4）暂时解决办法(对我有用)：
PHImageRequestOptions.networkAccessAllowed= YES(默认值为NO)
（5）Q:
为什么单独Demo就没有问题，拉到大的项目中就有问题???（都是真机）

**Comment by banchichen** [comment]
我升级到iOS11了...拍照正常...

[[PHImageManager defaultManager] requestImageForAsset如果获取到的result是nil，一般是因为图片存在iCloud中，此时会再来一次图片获取且设置networkAccessAllowed= YES...

如果result是nil，[info objectForKey:PHImageResultIsInCloudKey]却不是YES的话，会出现你说的这种情况，那比较诡异，我还没碰到过...
