### ISSUE TITLE
TZ_isGlobalHideStatusBar is not always right.

### ISSUE THREAD

**Issue by cocoay** [banchichen/TZImagePickerController#548]
TZ_isGlobalHideStatusBar is not always right.
e.g. 
`<key>UIStatusBarHidden</key>
	<true/>`
`[[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationFade]`
 
Using `[UIApplication sharedApplication].statusBarHidden` might be more accurate.

**Comment by banchichen** [comment]
你好，这个代码是来自这个PR的：https://github.com/banchichen/TZImagePickerController/pull/501      

因为要兼容应用初始化时就隐藏了状态栏的逻辑，所以每次显示状态栏时，判断一下是否初始化时就隐藏了状态栏，如果是的话，不去显示状态栏。

这里的宏命名和一些逻辑我稍微做了下优化：
https://github.com/banchichen/TZImagePickerController/commit/3d1a48df1ef74bd1ac464f700f2b2f8666401053
