### ISSUE TITLE
通过initWithSelectedAssets方法预览照片存在内存泄漏。

### ISSUE THREAD

**Issue by focus-ming** [banchichen/TZImagePickerController#549]
通过initWithSelectedAssets方法预览照片  每点击预览一次内存就增大一点。另外希望能新增一个预览图片时候可显示一个删除按钮点击后回调的功能。

**Comment by banchichen** [comment]
你好，没有内存泄漏的，用Xcode自带的Debug Memory Graph可以看到多次预览后，内存里存活的对象是正常的，没有泄漏的对象。
![image](https://user-images.githubusercontent.com/12755494/32838428-7ebe3568-c9d6-11e7-9df4-2e24e07f6660.png)

**Comment by banchichen** [comment]
删除按钮目前没有计划哈...
