### ISSUE TITLE
关于获取原图的问题

### ISSUE THREAD

**Issue by zuocai1993** [banchichen/TZImagePickerController#550]
你好，我是在代理方法中

- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto

去执行获取原图的。

![image](https://user-images.githubusercontent.com/16344283/29695691-e4d748a8-8976-11e7-830a-53010f1f277d.png)

info[PHImageResultIsDegradedKey]  这个值一直返回都是no  且只返回一次。

不知道怎么回事  还请告知。

**Comment by zuocai1993** [comment]
我直接打印返回的photo 大小  选择一张1.8M的图片  通过  uiimage 转 nsdata   计算出来图片有10M    我不知道这是什么原因造成的。还请回复

**Comment by banchichen** [comment]
你好：
1. 取原图的方法的回调会执行一到多次，只执行一次是合理的，详见内部调用的系统API的介绍，info[PHImageResultIsDegradedKey]是NO，就已经拿到原图了，回调不会再执行了，拿当前得到的图片来用即可。
2. 图片有10M，可以参考这个issue：https://github.com/banchichen/TZImagePickerController/issues/542
也可以直接使用取原图二进制数据的API：TZImageManager的getOriginalPhotoDataWithAsset
