### ISSUE TITLE
图片和视频分开选择时崩溃

### ISSUE THREAD

**Issue by wangguoming0** [banchichen/TZImagePickerController#551]
![snip20170825_3](https://user-images.githubusercontent.com/17560577/29697410-ac7eba94-8981-11e7-880e-1ebf02d4e1f1.png)
如上图所示为将图片和视频分开选择 发生崩溃如下
![snip20170825_7](https://user-images.githubusercontent.com/17560577/29697413-af373dce-8981-11e7-883d-a3f5b041fdd6.png)

**Comment by banchichen** [comment]
奇怪，我在Demo上没复现，你是用的什么版本呢~？ 
更新下试试~？

**Comment by wangguoming0** [comment]
我用的是1.8.9版本的  通过Localized resources can be mixed 该字段进行本地化的时候发生崩溃
![snip20170826_1](https://user-images.githubusercontent.com/17560577/29737790-e04e86ae-8a46-11e7-990a-f614e85cbeca.png)

**Comment by banchichen** [comment]
理论上跟Localized resources can be mixed没什么关系...我也试了一下，没有复现出来...

我看你是做了个Demo，把你做的Demo发到百度网盘分享给我一下~？我看看~
