### ISSUE TITLE
使用 MLeaksFinder 发现内存溢出

### ISSUE THREAD

**Issue by DeqiuTseng** [banchichen/TZImagePickerController#552]
In case that UIImagePickerController should not be dealloced, override -willDealloc in UIImagePickerController by returning NO.
View-ViewController stack: (
    UIImagePickerController
)

**Comment by banchichen** [comment]
你好，Demo没有的，可以试一下。

还有就是最好使用最新版的MLeaksFinder，旧版有bug...
