### ISSUE TITLE
iCloud图片不能得到原图吗?

### ISSUE THREAD

**Issue by smallevil** [banchichen/TZImagePickerController#555]
项目中需要用户选择照片并上传.
有用户反应会上传失败.
现在怀疑是因为选择的是iCloud的图片,所以造成无法得到.
对TZ的机制不太了解,自己也是IOS开发半吊子.
想问一下.用户如果选择了iCloud图片,是不是不能得到原图路径??
我用的设置是:
imagePickerVc.allowPickingOriginalPhoto = YES;
imagePickerVc.isSelectOriginalPhoto = YES;
即默认只要用户选择了,就是原图方式.

因为希望得到完整的图片信息和大小.
不知道这个应该如何处理??
感谢

**Comment by banchichen** [comment]
你好，1.7.3版本开始对iCloud图片的选取做了优化，样式如下图：
<img width="512" alt="default" src="https://user-images.githubusercontent.com/12755494/29772089-a97e6d1c-8c29-11e7-8448-0a904f4e4053.png">

可以检查下你们项目当前使用的版本，如果版本低于1.7.3，建议升级到最新版。

然后，最好是能确定在哪一个步骤失败的，是选取图片没成功，还是上传的时候没成功....
