### ISSUE TITLE
关于图片大小限制问题

### ISSUE THREAD

**Issue by smallevil** [banchichen/TZImagePickerController#556]
比如我限制所选图片必须是1200px的.
现在我看代码是长和宽必须达到这个数才行.
但我希望的是,只要长或宽有一个达到这个限制就可以了.
这个要怎么设置呢??

**Comment by banchichen** [comment]
你好，请参考这个issue，限制视频大小和图片大小，都可以通过实现代理方法来达到目的：https://github.com/banchichen/TZImagePickerController/issues/558
