### ISSUE TITLE
选择图片内存过大

### ISSUE THREAD

**Issue by lichenyu123** [banchichen/TZImagePickerController#557]
同时选择九张图片上传，ipadmini1会导致内存过大导致崩溃

**Comment by banchichen** [comment]
你好，对于低配置设备，可以通过设置photoWidth来设置导出图片的大小，photoWidth变小，则内存占用会降低。

> /// The pixel width of output image, Default is 828px / 导出图片的宽度，默认828像素宽
@property (nonatomic, assign) CGFloat photoWidth;
