### ISSUE TITLE
选择多张图片会引发内存崩溃

### ISSUE THREAD

**Issue by LIVE1016** [banchichen/TZImagePickerController#56]
如果选择多张原图会引发内存崩溃，个人觉得应该是把图片路径返回给调用者，而不是直接把图片返回

**Comment by banchichen** [comment]
这里新版本做了优化的~ 可以试试新版~ 我返回出去的图片是828像素宽的图片，一般一张图片大的话会有1M左右，返回出去的asset就是源图片资源，需要通过Photos库才能取到，你们用起来会麻烦许多~所以还是会把图片返回给你~

**Comment by LIVE1016** [comment]
OK，有时间试试，tks~
