### ISSUE TITLE
1.8.9 获取bundle出错

### ISSUE THREAD

**Issue by pyooboom** [banchichen/TZImagePickerController#562]
![image](https://user-images.githubusercontent.com/18424253/29810209-afa7db98-8c64-11e7-8781-a32acf2f9b22.png)

崩在了这一句，po出来的url是nil

**Comment by pyooboom** [comment]
目前解决方案：不用cocoapods导入，直接拖进工程，然后需要在Build Phases - Copy Bundle Resources里添加bundle。希望作者能看看这个问题😁

**Comment by banchichen** [comment]
你好，我这里无法复现出这个问题，能否麻烦制作个Demo，比如发到百度网盘，我来复现一下。
