### ISSUE TITLE
我的navigationBar不显示，但是存在还可以点击

### ISSUE THREAD

**Issue by shengdayan** [banchichen/TZImagePickerController#565]

**Comment by banchichen** [comment]
你好，Demo没问题吧，你是工程里做了什么特殊设置么....

**Comment by herobin22** [comment]
我也遇到这个问题了, 发现是bar颜色和title颜色都为白色, 导致看不到
应该是项目里使用[UINavigationBar appearance], 把bar改成白色了

**Comment by banchichen** [comment]
@herobin22 赞👍
