### ISSUE TITLE
能否新增一个当选择视频时，限制10秒钟，超过时，可进行编辑的功能？

### ISSUE THREAD

**Issue by caizhaojin** [banchichen/TZImagePickerController#566]
能否新增一个当选择视频时，限制10秒钟，超过时，可进行编辑的功能？

类似微信朋友圈选择视频时，当视频时长超10秒，就只能进行编辑后才能选择。

**Comment by lancelot9527** [comment]
:D 源码你都有了。自己不会改吗

**Comment by banchichen** [comment]
@caizhaojin 你好，功能有点大哦，这个库应该不会加入该功能，建议你自己拓展：设置autoDismiss为NO，这样当用户选择好视频时会调代理方法而不会dismiss，这里你自己判断是选择结束还是要去编辑，要编辑的话再push你的编辑界面，还算比较好拓展~

**Comment by caizhaojin** [comment]
好的。 感谢各路大神的建议。 

我自己再进行修改拓展。

谢谢作者源码。
