### ISSUE TITLE
关于图片预览的问题

### ISSUE THREAD

**Issue by gwlCode** [banchichen/TZImagePickerController#567]
allowPreview属性关闭了下方预览功能，
是否可以添加个点击图片也无法预览的功能属性

**Comment by banchichen** [comment]
你好，其实设置了allowPreview=NO，是不会跳转到预览界面的，不过这个效果在适配横竖屏那个版本里改坏了...

刚刚提交了~这两天会发一个版本1.9.2~

**Comment by banchichen** [comment]
1.9.2版本已经发布了~

**Comment by OpenFeyn** [comment]
allowPreview=NO
2.1.6版本
只选中一张图片，还是会进入预览页面。怎么破？

**Comment by OpenFeyn** [comment]
allowPreview=NO
只允许选择一张
2.1.6版本
只选中一张图片，还是会进入预览页面。怎么破？

**Comment by banchichen** [comment]
确实，发现是allowPreview不支持单选模式，多张的时候倒正常...
刚刚发布了2.2.2版本，修复了哈。
