### ISSUE TITLE
选中图片后，返回到相册列表。在进入，之前选中的图片变成未选状态。

### ISSUE THREAD

**Issue by Lynnll** [banchichen/TZImagePickerController#57]
步骤：
1、在某一个相册（例如：相机胶卷）中任意选几张图片；
2、点击左上角返回；
3、再次进入“相机胶卷”
结果：
之前选中的图片变成为勾选状态。

**Comment by banchichen** [comment]
你好，我没有做这个效果的，微信也没做，我是参照微信的效果来做的。实现是好实现的，每个asset资源都有一个唯一标示的。

**Comment by banchichen** [comment]
你好，我刚刚更新了1.3.0版本，该功能已经加上去了~谢谢支持~
