### ISSUE TITLE
 单选的时候  影藏多选按钮

### ISSUE THREAD

**Issue by maoyuhu** [banchichen/TZImagePickerController#570]
楼主你好:我在项目中使用你的图片选择器  有的项目一次最多需求选择一张图片 但是我试了你的maxImagesCount = 1 时 设置了showSelectBtn为false 但是选择的时候还是会展示多选时候的那个按钮 是我设置有问题吗  谢谢

**Comment by banchichen** [comment]
你好，我刚刚试了最新的Demo，是正常的呀....

你那里Demo正常吧~？参考下Demo的写法~？

**Comment by maoyuhu** [comment]
谢谢  我之前用的旧版本  新版本正常
