### ISSUE TITLE
图片选取预览去掉问题

### ISSUE THREAD

**Issue by heyiji** [banchichen/TZImagePickerController#571]
楼主您好：进入图片选择界面--选中一张图片--点击预览--然后把右上角的√去掉（右下角变完成）--点击完成--回到首页把图片还带过来了

**Comment by banchichen** [comment]
你好，这是借鉴微信的逻辑，如果一张照片都没选，点击完成，会把当前展示的照片带出去。

**Comment by heyiji** [comment]
这样的啊！好的！万分感谢！！！！
