### ISSUE TITLE
点击已选择图片的回调？

### ISSUE THREAD

**Issue by ichampionT** [banchichen/TZImagePickerController#574]
请问，点击已选择的图片进入相册把这张照片取消选择，有没有监听的回调函数？

**Comment by banchichen** [comment]
你好，没有的。取消选择的瞬间，你想做什么事？

**Comment by ichampionT** [comment]
我在图片的下面还有其他内容，有的时候取消掉之后，collectionView的frame要改变，所以想监听取消选择，后来在collectionView加载的时候做了frame的改变，也算解决了吧。

**Comment by banchichen** [comment]
你好，你在选择完照片后的协议方法里判断就可以了：
- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray<UIImage *> *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto;

这里会返回用户选择的照片，想改变frame，在这里做就行
