### ISSUE TITLE
选择图片后裁剪图片，最终得出的图片内容与自己选择的图片相比往下偏移了64

### ISSUE THREAD

**Issue by xuwenlang** [banchichen/TZImagePickerController#575]
设置了allowCrop和cropRect后，进行图片裁剪，裁出的图片内容与自己选择的图片相比往下偏移了64

**Comment by banchichen** [comment]
你好，你那里Demo是正常的吧？

你在工程里是不是有什么和Demo不一样的设置...

方便做一个Demo吗，通过百度网盘分享给我，我来分析下

**Comment by xuwenlang** [comment]
您好，网盘链接: https://pan.baidu.com/s/1i5vKnUt 密码: qdrv

**Comment by banchichen** [comment]
你好，我看了你的例子，产生偏移是因为裁剪范围一开始就在图片之外，且裁剪区域离顶部和底部的距离不一致...（这2点碰在一起导致了偏移）
建议你先把裁剪区域设置为离顶部和底部的距离一致，这样不会产生偏移...

**Comment by xuwenlang** [comment]
是的，裁剪框放在中部就没事了，谢谢
