### ISSUE TITLE
1.9.2 使用pod导入，在swift项目中运行报错

### ISSUE THREAD

**Issue by 358489351** [banchichen/TZImagePickerController#576]
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

项目崩溃在TZImagePickerController类中的第260行

**Comment by banchichen** [comment]
你好，我这里看260行是个空行...崩溃在哪一行代码呢？

**Comment by banchichen** [comment]
你好，我是swift工程里没有复现出这个问题，能否麻烦制作个Demo，比如发到百度网盘，我来复现一下。
