### ISSUE TITLE
Xcode中关于C Language Dialect 不兼容C99

### ISSUE THREAD

**Issue by dmcBig** [banchichen/TZImagePickerController#578]
我用cordova创建的项目 默认XCode下的C Language Dialect 配置是C99标准，然后会报几个错。
比如编译器识别不了typeof关键字。
请问怎么办？在不改动C99默认配置的情况下

**Comment by banchichen** [comment]
你好，可以去除这些关键字，采用替代办法:
比如在TZImagePickerController.m文件里，把__weak typeof(self) weakSelf = self; 改成 __weak TZImagePickerController *weakSelf = self; 其它地方同理

**Comment by dmcBig** [comment]
好的谢谢
