### ISSUE TITLE
保存本地.mp4视频失败

### ISSUE THREAD

**Issue by Caolongs** [banchichen/TZImagePickerController#580]
Error Domain=AVFoundationErrorDomain Code=-11800 "这项操作无法完成" UserInfo={NSUnderlyingError=0x600000244830 {Error Domain=NSOSStatusErrorDomain Code=-12551 "(null)"}, NSLocalizedFailureReason=发生未知错误（-12551）, NSLocalizedDescription=这项操作无法完成}

**Comment by Caolongs** [comment]
个别视频~~

**Comment by banchichen** [comment]
Hi, 可以把这个视频发给我吗，通过百度云盘分享一下，我测试一下~

**Comment by xispower** [comment]
@Caolongs 这个问题解决了吗？

**Comment by xispower** [comment]
我的解决了，我的是是沙盒路径问题，我替换NSHomeDirectory为NSSearchPathForDirectoriesInDomains就没问题了。 @Caolongs @banchichen

**Comment by banchichen** [comment]
@xispower 好的，感谢反馈~

**Comment by jaydenin** [comment]
@Caolongs 保存到本地的代码怎么写？？可以给一些截图看看吗？
