### ISSUE TITLE
TZImageManager中Export Video 导出视频的接口block缺少返回值

### ISSUE THREAD

**Issue by zcinclude** [banchichen/TZImagePickerController#582]
TZImageManager中Export Video 导出视频的接口缺少返回值，建议在block回调中返回导出失败的错误。
而且在.m Line724私有方法startExportVideoWithVideoAsset:completion:一些位置直接return或者break，没有处理block，会导致外部调用一直无法返回。

**Comment by BlackCatSun** [comment]
请问你导出视频到本    个别视频   有没有不走回调的情况，

**Comment by banchichen** [comment]
你好，之前的API设计得有问题，没有透出失败信息，目前已做优化：     
https://github.com/banchichen/TZImagePickerController/commit/88b5f37fa98c9ef093eba1d99cc0c3f4a84db475     
https://github.com/banchichen/TZImagePickerController/commit/1ab7b5a8dbfc023984ef90b7b259261ac68d8c1d     
新版本1.9.5已发布，建议升级~具体用法可参看Demo~
