### ISSUE TITLE
怎么隐藏照相功能呢

### ISSUE THREAD

**Issue by liuxinixn** [banchichen/TZImagePickerController#584]
我只是想选择图片

**Comment by banchichen** [comment]
你好，Demo里就有展示这个效果的...

/// 默认为YES，如果设置为NO,拍照按钮将隐藏,用户将不能选择照片
@property(nonatomic, assign) BOOL allowTakePicture;

**Comment by zuoshijun** [comment]
设置allowTakePicture为NO后,内部仍然显示拍照按钮,版本3.2.1

**Comment by banchichen** [comment]
@zuoshijun 3.2.1版本也可以拍视频，你看到的可能是拍视频的按钮

设置allowTakeVideo为NO可以隐藏掉
