### ISSUE TITLE
关于图片裁剪

### ISSUE THREAD

**Issue by 860311018** [banchichen/TZImagePickerController#585]
现在的裁剪框是固定的，只能对图片放大，但是不能缩小裁剪呀

**Comment by banchichen** [comment]
你好，是的，最小缩放比是1，不允许缩到更小...

**Comment by sunjincai** [comment]
同样是裁剪的问题，如果设备中有一张类似金箍棒一样的图片，发现裁剪出来的图片会有白色空白区域，能否支持如果图片尺寸无法填充满裁剪框，就将裁剪框自动缩小到适合图片宽高呢

**Comment by zhouxubin** [comment]
同问，当图片小于剪裁框的时候能否将图片自动放大到适合剪裁框呢

**Comment by wcgLR** [comment]
建议图片自适应裁剪框！可以定一个规则即: 图片宽度填充满裁剪框的宽。

**Comment by airdragon0915** [comment]
你好！关于图片剪裁我想提个建议：拍照后进入图片剪裁必须拿到asset，并传入！这样我就必须要保存照片，但是我只是想单纯的剪裁而已，所以能否给一个选择：传入照片后就给出剪裁界面

**Comment by WeMadeCode** [comment]
可以试试这个git@github.com:WeMadeCode/TZImagePickerController.git

**Comment by WeMadeCode** [comment]
可以试试这个https://github.com/WeMadeCode/TZImagePickerController.git

**Comment by iOSDaishang** [comment]
作者这里没有做处理，源码中加个判定即可，在TZImageCropManager.m文件的获得裁剪后图片方法中做如下修改：
//判断裁剪框的高度是否大于图片高度，如果大于就传图片frame，否则传裁剪框size
CGFloat outputWidth;
CGSize cropSize;
if (rect.size.height > imageView.frame.size.height)
{
outputWidth = imageView.frame.size.width * [UIScreen mainScreen].scale;
cropSize = imageView.frame.size;
}else
{
outputWidth = rect.size.width * [UIScreen mainScreen].scale;
cropSize = rect.size;
}
CGImageRef imageRef = [self newTransformedImage:transform
sourceImage:imageView.image.CGImage
sourceSize:imageView.image.size
outputWidth:outputWidth
cropSize:cropSize
imageViewSize:imageView.frame.size];

**Comment by banchichen** [comment]
感谢PR：https://github.com/banchichen/TZImagePickerController/pull/1102
刚刚发了新版哈，大家试下

3.2.1：新增裁剪用scaleAspectFillCrop属性，设置为YES后，照片尺寸小于裁剪框时会自动放大撑满

**Comment by 472125266** [comment]
你好，我用了3.2.1版本中scaleAspectFillCrop属性，非常之好用。赞！
但是，如果我选择一张想要裁剪的图片，然后左右滑动图片，再次回来此图片将无法撑开（图片短边自适应宽/高）。
