### ISSUE TITLE
两个问题，1，怎么实现多选的时候，点击计数（对号那里）2，怎么退出后，怎么再次进入的时候，标记出已选的媒体资源？

### ISSUE THREAD

**Issue by cloudsafe** [banchichen/TZImagePickerController#586]

**Comment by banchichen** [comment]
你好：
1. 没听懂是什么意思...
2. Demo里就是这个效果，设置这个属性即可：
/// 用户选中过的图片数组
@property (nonatomic, strong) NSMutableArray *selectedAssets;
