### ISSUE TITLE
希望增加旋转图片功能

### ISSUE THREAD

**Issue by fryindancy** [banchichen/TZImagePickerController#587]
您好：
       我在使用中，在裁剪图片时遇到横屏拍的照片，无法旋转图片裁剪，所以需要旋转图片的功能，目前是我自己修改了你的代码实现，希望您能考虑增加此功能，谢谢。

**Comment by fryindancy** [comment]
目前的需求是每点一次旋转90度就可以了，所以我自己只修改了这个，不是那种自由旋转功能。

**Comment by AGcaterpillar** [comment]
哥,能看一下 增加图片旋转的的代码吗

**Comment by AGcaterpillar** [comment]
哥,能看一下 增加图片旋转功能 后的代码吗 或者我家一下您QQ

**Comment by fryindancy** [comment]
我QQ3287581381

**Comment by fryindancy** [comment]
1、在TZPhotoPreviewCell加个rotateImage方法
- (void)rotateImage
{
    self.previewView.imageView.image = [self image:self.previewView.imageView.image rotation:UIImageOrientationLeft];
    [self.previewView recoverSubviews];
}

- (UIImage *)image:(UIImage *)image rotation:(UIImageOrientation)orientation
{
    long double rotate = 0.0;
    CGRect rect;
    float translateX = 0;
    float translateY = 0;
    float scaleX = 1.0;
    float scaleY = 1.0;
    
    switch (orientation) {
        case UIImageOrientationLeft:
            rotate = M_PI_2;
            rect = CGRectMake(0, 0, image.size.height, image.size.width);
            translateX = 0;
            translateY = -rect.size.width;
            scaleY = rect.size.width/rect.size.height;
            scaleX = rect.size.height/rect.size.width;
            break;
        case UIImageOrientationRight:
            rotate = 33 * M_PI_2;
            rect = CGRectMake(0, 0, image.size.height, image.size.width);
            translateX = -rect.size.height;
            translateY = 0;
            scaleY = rect.size.width/rect.size.height;
            scaleX = rect.size.height/rect.size.width;
            break;
        case UIImageOrientationDown:
            rotate = M_PI;
            rect = CGRectMake(0, 0, image.size.width, image.size.height);
            translateX = -rect.size.width;
            translateY = -rect.size.height;
            break;
        default:
            rotate = 0.0;
            rect = CGRectMake(0, 0, image.size.width, image.size.height);
            translateX = 0;
            translateY = 0;
            break;
    }
    
    UIGraphicsBeginImageContext(rect.size);
    CGContextRef context = UIGraphicsGetCurrentContext();
    //做CTM变换
    CGContextTranslateCTM(context, 0.0, rect.size.height);
    CGContextScaleCTM(context, 1.0, -1.0);
    CGContextRotateCTM(context, rotate);
    CGContextTranslateCTM(context, translateX, translateY);
    
    CGContextScaleCTM(context, scaleX, scaleY);
    //绘制图片
    CGContextDrawImage(context, CGRectMake(0, 0, rect.size.width, rect.size.height), image.CGImage);
    
    UIImage *newPic = UIGraphicsGetImageFromCurrentImageContext();
    
    return newPic;
}
2、在TZPhotoPreviewController里面如果是裁剪状态，在完成的旁边显示旋转按钮，每点一次旋转90度。

**Comment by fryindancy** [comment]
还有一个问题，裁剪6寸的相片时，裁剪图片时图片会超出部分无法选择，宽高都超出，只能裁剪中间部分。看了代码有这个方法：refreshScrollViewContentSize，但是并不如意。

**Comment by banchichen** [comment]
比较小众，不考虑增加旋转功能哈
