### ISSUE TITLE
照片最大可选张数 设置为1的时候 选择器中没有显示选择按钮

### ISSUE THREAD

**Issue by AGcaterpillar** [banchichen/TZImagePickerController#589]
照片最大可选张数 设置为1的时候 选择器中没有显示选择按钮

**Comment by banchichen** [comment]
你好，设置这个属性为YES：
@property (nonatomic, assign) BOOL showSelectBtn;        ///< 在单选模式下，照片列表页中，显示选择按钮,默认为NO

Demo里设置的是NO
