### ISSUE TITLE
希望可以单独打开预览controller

### ISSUE THREAD

**Issue by GanHuaLin** [banchichen/TZImagePickerController#59]
照你代码里的打开预览，但是发现在 TZPhotoPreviewController.m 下 configBottomToolBar函数里，获取NavigationController里的allowPickingOriginalPhoto报错。

TZImagePickerController *imagePickerVc = (TZImagePickerController *)self.navigationController;
    if (imagePickerVc.allowPickingOriginalPhoto) {
｝

我现在需要在我自己的controller里打开这个预览，希望判断下 imagePickerVc  != nil

**Comment by AndyLeeBlue** [comment]
同求，希望可以单独使用图片预览和视频预览功能。

**Comment by banchichen** [comment]
好，那我抽时间写一下吧~  我尽快~

**Comment by banchichen** [comment]
18天过去了啊.....不好意思啊各位，今天才挤出点时间弄这里，最新版1.3.4版本已经可以单独打开预览功能，详见代码.....
