### ISSUE TITLE
请问下 我 的项目中需要用到相册里的视频的地址 进行播放      获得本地地址的话是必须要用导出视频这个方法吗，但是用这个方法导出一个小视频需要好久的时间，请问有什么解决办法吗

### ISSUE THREAD

**Issue by BlackCatSun** [banchichen/TZImagePickerController#590]
- (void)getVideoOutputPathWithAsset:(id)asset completion:(void (^)(NSString *outputPath))completion

**Comment by banchichen** [comment]
你好，如果只要播放的话，直接用asset也可以播放，具体可以看我的TZVideoPlayerController。如果是需要保存到沙盒，通过沙盒的路径上传到服务端的话，必须调getVideoOutputPathWithAsset，这个方法会把视频保存到沙盒，并把outputPath通过回调传出来...   

当然你也可以研究下其它的导出方案咯，应该有比getVideoOutputPathWithAsset更好的...

**Comment by CoderJackySong** [comment]
那个TZVideoPlayerController没有播放视频进度及快进功能，能优化下吗？

**Comment by banchichen** [comment]
@CoderJackySong 目前没这个计划，微信和QQ的都没这个功能...
