### ISSUE TITLE
你好, 当我选择图片时, 大图模式左右滑动查看时, 内存和CPU都会暴涨

### ISSUE THREAD

**Issue by lixiaonan** [banchichen/TZImagePickerController#592]
机型 iPhone5s, 系统10.3, 大图左右滑动查看, 内存暴涨, 图片也不清晰, 要等三十多秒, 内存才会降下来, 图片变清晰, 最新版本

在我的iPhone6s, ios11上不会出现这个问题

**Comment by banchichen** [comment]
图片是存在iCloud里吧？是不是有个下载的进度条...
去本地的大图应该是速度很快的...

**Comment by lixiaonan** [comment]
@banchichen 不是的, 是本机的图片, 我这边只在iPhone5s上真机才出现, cpu会暴涨到90%+, 手机发热严重.

**Comment by banchichen** [comment]
好吧...比较奇怪，走的是同一份代码...目前没有什么思路~

可以去测试下其它的图片选择器，看看他们的选择器，在这个5s上表现如何~
