### ISSUE TITLE
导航栏上面的tintColor 改变不了， 取消按钮  看不见

### ISSUE THREAD

**Issue by KangYJie** [banchichen/TZImagePickerController#593]
<img width="403" alt="2017-09-21 4 06 54" src="https://user-images.githubusercontent.com/19221483/30685314-134ced98-9ee7-11e7-802b-cd3a7b553bfe.png">
<img width="461" alt="2017-09-21 4 07 10" src="https://user-images.githubusercontent.com/19221483/30685316-13e2ad56-9ee7-11e7-8608-debb798435ce.png">

<img width="362" alt="2017-09-21 4 09 56" src="https://user-images.githubusercontent.com/19221483/30685406-61fd07b6-9ee7-11e7-817c-b8f4f7ce1be6.png">
<img width="362" alt="2017-09-21 4 10 09" src="https://user-images.githubusercontent.com/19221483/30685407-627fce80-9ee7-11e7-8106-b4d6668ea1f6.png">

<img width="362" alt="2017-09-21 4 10 09" src="https://user-images.githubusercontent.com/19221483/30685458-8bffd61a-9ee7-11e7-8619-a22fe7702fd4.png">

**Comment by AAChartModel** [comment]
兄弟,关于这个问题逆神如何解决的?

**Comment by AAChartModel** [comment]
我提了一个类似的问题#595,在 iOS 11系统下,导航栏的颜色变为全白色,在 iOS 10等其他系统下则正常
