### ISSUE TITLE
导出视频到本地 为什么有的视频不会走回调

### ISSUE THREAD

**Issue by BlackCatSun** [banchichen/TZImagePickerController#594]
<img width="599" alt="2017-09-24 23 53 33" src="https://user-images.githubusercontent.com/25749083/30784198-9b149066-a183-11e7-82b1-d9c26e673b74.png">

**Comment by banchichen** [comment]
你好，不走回调应该是视频导出失败了，之前的API设计得有问题，没有透出失败信息，目前已做优化：     
https://github.com/banchichen/TZImagePickerController/commit/88b5f37fa98c9ef093eba1d99cc0c3f4a84db475     
https://github.com/banchichen/TZImagePickerController/commit/1ab7b5a8dbfc023984ef90b7b259261ac68d8c1d     
新版本1.9.5已发布，建议升级~具体用法可参看Demo~
