### ISSUE TITLE
iOS 11系统下图片选择控制器的导航栏头部变为全白色了!!! iOS 10下正常

### ISSUE THREAD

**Issue by AAChartModel** [banchichen/TZImagePickerController#595]
![img_2207](https://user-images.githubusercontent.com/16357599/30795881-4396387e-a202-11e7-9141-6136ac07b588.PNG)

**Comment by AAChartModel** [comment]
如上图所示,导航栏头部视图全变为白色了

**Comment by AAChartModel** [comment]
iOS 10系统下相册选择器显示无异常

**Comment by AAChartModel** [comment]
抱歉,经排查,应该是个人问题,非`TZImagePickerController` 的原因

**Comment by jackhmy** [comment]
把导航栏半透明translucent改成NO可解决白色问题。但是这样就没有半透明的效果了。。

**Comment by AAChartModel** [comment]
嗯,谢谢指点!!!🎉按照此方法,确实解决了问题,但奇怪的是为何之前是正常的,突然出现了这种问题?
