### ISSUE TITLE
xcode9下初始化崩溃

### ISSUE THREAD

**Issue by yuying2012** [banchichen/TZImagePickerController#596]
+ (NSBundle *)tz_imagePickerBundle {
    NSBundle *bundle = [NSBundle bundleForClass:[TZImagePickerController class]];
    NSURL *url = [bundle URLForResource:@"TZImagePickerController" withExtension:@"bundle"];
    bundle = [NSBundle bundleWithURL:url];
    return bundle;
}

pod导入的,url执行后为nil

**Comment by banchichen** [comment]
你好，方便制作一个Demo到百度网盘吗，我这复现不出来...

**Comment by yuying2012** [comment]
不好抽出来,感觉跟本地化有关,+[NSBundle tz_localizedStringForKey:]: unrecognized selector sent to class 0x1b353a3d0这里也会crash.有点怪

**Comment by yuying2012** [comment]
已经找到原因了,是应用了新版的编译系统导致的,用了新版预览版编译系统,好多Pod库都出问题了

**Comment by banchichen** [comment]
好的，解决了就好~👍

**Comment by w258958134** [comment]
遇到同样的问题，请问怎么解决的

**Comment by MerenguesGeek** [comment]
我也遇到了同样的问题，Xcode 9.2
