### ISSUE TITLE
啥时候适配iPhone X 

### ISSUE THREAD

**Issue by Jayxiang** [banchichen/TZImagePickerController#597]
虽然还没发售

**Comment by banchichen** [comment]
在iPhone X模拟器上玩过几次，基本没有什么问题，有一处样式细节待优化：底部工具条在iPhone X上过于靠下了，应该拔高（83-49）像素高。国庆节把这个优化掉吧~

**Comment by asd8855** [comment]
<img width="271" alt="1231231231" src="https://user-images.githubusercontent.com/20153584/30914898-a95ab628-a3c7-11e7-81f9-e83ee2cf379d.png">

**Comment by banchichen** [comment]
@asd8855 是最新的Demo吗，即使不是iPhoneX，效果也是一样的吧...

**Comment by Tuikai** [comment]
如图所示，问我一样

**Comment by jian8138** [comment]
![cc9dd17b-8751-458d-92c6-7ab8cafc2b5b](https://user-images.githubusercontent.com/23274722/31527549-ba8f6b10-b000-11e7-874c-10b74f89998c.png) @banchichen 在iphoneX上预览图片时，导航栏的高度应该再高点，返回按钮应该再往下一点

**Comment by sunjames** [comment]
怎么适配iPhoneX？

**Comment by yuanzhiying** [comment]
如何适配iPhone X？

**Comment by fuyunmanbu** [comment]
解决iPhoneX导航条过长问题
![snip20171020_1](https://user-images.githubusercontent.com/16368126/31804774-548fbb10-b58e-11e7-81d3-24f921ea106f.png)
![snip20171020_3](https://user-images.githubusercontent.com/16368126/31804780-5d447a34-b58e-11e7-83d8-c9b0224cfa34.png)

**Comment by banchichen** [comment]
你好，1.9.4版本已发布，已适配iPhonex。
不好意思，这段时间公司实在太忙了，久等🤝

**Comment by asd8855** [comment]
666666666666
