### ISSUE TITLE
有些手机会发生数组越界崩溃

### ISSUE THREAD

**Issue by Jun008** [banchichen/TZImagePickerController#598]
-[TZAlbumPickerController tableView:cellForRowAtIndexPath:] 
(TZImagePickerController.m:630)

**Comment by Jun008** [comment]
猜测可能是这个方法-(void)configTableView频繁太快调用造成的。
当reloadData异步执行cellForRowAtIndexPath的时候，_albumArr元素发生了变化，导致数组越界。(在configTableView中_albumArr有在一个全局队列中更改)。

**Comment by Jun008** [comment]
reloadData的危险性可参考这个：
http://mrpeak.cn/blog/tableview-danger/

**Comment by shenyuan000** [comment]
我的也是 崩溃在configTableView这里
-[TZAlbumPickerController cconfigTableView]_block_invoke 
报了这个错误 |NSArray invalid index:[-1]

**Comment by banchichen** [comment]
有道理👍
_albumArr的赋值测量了下耗时在10毫秒左右，完全可以放到主线程，目前我把_albumArr的赋值操作搬到了主线程，应该就不会出现这样的意外了~ 
相关commit：https://github.com/banchichen/TZImagePickerController/commit/e7b60ddf35cb2499dd5e420f959269d51305fbd0
随着下个版本发布哈

**Comment by banchichen** [comment]
新版1.9.8版本已经发布了哈。
