### ISSUE TITLE
希望照片和视频可以一起选..

### ISSUE THREAD

**Issue by LiYongXD** [banchichen/TZImagePickerController#6]
(づ￣ 3￣)づ么么哒

**Comment by banchichen** [comment]
其实一起选是OK的，容易实现，不过这样的话，项目和imagePicker的交互就复杂一些了，你得判断每一个返回的asset是照片还是视频，需要使用者对PhotoKit有一定的了解，会让imagePicker用起来不太方便~微信也是不允许同时选择照片和视频的~    以后有空了会开放一个属性，让外界来定是否允许照片和视频同时选吧~

**Comment by banchichen** [comment]
你好，1.8.4版本已发布，已支持照片/gif/视频同时选&多选。
