### ISSUE TITLE
iOS11适配问题讨论、收集！

### ISSUE THREAD

**Issue by mrhyh** [banchichen/TZImagePickerController#601]

**Comment by banchichen** [comment]
你好，很早之前就适配过的...
你发现什么问题吗？

**Comment by yjjwxy2** [comment]
导航栏左侧按钮位置不对iOS11

**Comment by mrhyh** [comment]
我暂时没发现什么问题，只是在更新日志没看到适配iOS11的说明。要不这个issues暂时不关闭了，留给大家反馈iOS11遇到的问题，一段时间后再关闭.

**Comment by remember17** [comment]
选择圆形图片的时候，白色线条选框与真实选择的部位没有重合在一起，请问是我没设置好么？

**Comment by cAibDe** [comment]
我用ios11的时候选择图片 控制台会提示 unable to load image data

**Comment by yjjwxy2** [comment]
@banchichen   能给个联系方式吗  关于iOS11适配有个问题想问你

**Comment by RtzX** [comment]
iphonex 适配的问题
问题描述: 当多选情况时,假如可以选择五张图片.已经选择了4张图片.这时候,默认进入了单选模式.如果点击了图片,进行了图片预览. 返回按钮,确定按钮的的布局 是有问题的[http://wx3.sinaimg.cn/mw690/8623d96bgy1fkda5lkjg0j20c10nowku.jpg](url)
正确的布局
[http://wx3.sinaimg.cn/mw690/8623d96bgy1fkda5hc51hj20c10notbx.jpg](url)

望修复.thks

**Comment by johann-wang** [comment]
我遇到的是:导航栏左侧返回按钮位置偏下方

**Comment by inrtgdje** [comment]
在iPhone X模拟器上从相册选择图片时，导航栏底部覆盖了最上面一排图片的一部分,其他机型没有这个问题

**Comment by EricCartman** [comment]
也遇到了导航栏左侧返回按钮位置偏下的问题
![img_2823](https://user-images.githubusercontent.com/1150106/31483407-d9799f92-aef1-11e7-9682-4be724dfaa63.jpg)

**Comment by GitHubazuo** [comment]
ios11 1.9.3返回键向下偏移

**Comment by GitHubazuo** [comment]
返回键向下偏移的找到这个代码改成这样就好了  [[UIBarButtonItem appearance] setBackButtonTitlePositionAdjustment:UIOffsetMake(-100, 0) forBarMetrics:UIBarMetricsDefault];

**Comment by fuyunmanbu** [comment]
解决iPhoneX导航条过长导致cell被覆盖问题
![snip20171020_1](https://user-images.githubusercontent.com/16368126/31804801-8e22cdcc-b58e-11e7-9840-cea9c4811be8.png)
![snip20171020_3](https://user-images.githubusercontent.com/16368126/31804802-8e55aeb8-b58e-11e7-8975-c27ecf3c20ee.png)

**Comment by fuyunmanbu** [comment]
图片浏览的工具条等位置问题
![snip20171020_4](https://user-images.githubusercontent.com/16368126/31805889-fb2ad664-b596-11e7-893e-2dbabab4a881.png)

**Comment by banchichen** [comment]
@fuyunmanbu @inrtgdje @RtzX 
你好，1.9.4版本已发布，已适配iPhonex。
不好意思，这段时间公司实在太忙了，久等🤝

**Comment by banchichen** [comment]
@johann-wang @yjjwxy2  Hi，导航栏返回按钮位置偏下的问题，我这里未能重现，请问你们在Demo里能复现这个问题吗？对我的Demo做了什么改动呢？

**Comment by ChaoGuoGuo** [comment]
@banchichen 那个判断是否是iPhoneX我觉得最好加前缀，不然可能会冲突（🤣），还有判断，还有个10,6也是X，我将你的代码改成如下：
+ (BOOL)tz_isIPhoneX {
    struct utsname systemInfo;
    uname(&systemInfo);
    NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
    if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
        // 模拟器下采用屏幕的高度来判断
        return [UIScreen mainScreen].bounds.size.height == 812;
    }
    BOOL isIPhoneX = NO;
    if ([platform isEqualToString:@"iPhone10,3"] || [platform isEqualToString:@"iPhone10,6"]) {
        isIPhoneX = YES;
    }
    return isIPhoneX;
}
我看里面好多地方都是写死的数值比如X上tabbar的增加高度数值34等，我觉得可以考虑把它换成宏，这样有改变只需要改宏(isIPhoneX ? 34.0f : 0.0f)即可😂，而不必一个一个文件找，修改量大

**Comment by asd8855** [comment]
@banchichen iOS 11 [ImageManager] Unable to load image data, /var/mobile/Media/DCIM/102APPLE/IMG_2495.JPG

**Comment by banchichen** [comment]
@asd8855 你好，这个应该是Apple的bug，详情参见这个issue哈：https://github.com/banchichen/TZImagePickerController/issues/622

**Comment by banchichen** [comment]
@ChaoGuoGuo 你好，多谢指出，已经修复了，将随着下个版本发布~

**Comment by banchichen** [comment]
@asd8855 假的，ZLPhotoBrowser实际没解决，还是有很多这样的打印。

**Comment by asd8855** [comment]
@banchichen  哦哦 好的
