### ISSUE TITLE
初始化就直接崩溃在 bundle = [NSBundle bundleWithURL:url];...可以怎么修改吗

### ISSUE THREAD

**Issue by vistaLin** [banchichen/TZImagePickerController#604]
<img width="1095" alt="2017-10-10 11 01 01" src="https://user-images.githubusercontent.com/16410016/31367578-c59f7f60-ad3d-11e7-82ec-6d344ef39f98.png">
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:9 delegate:self];  用的xcode8.3打开的

**Comment by ishepherdMiner** [comment]
刚好碰到这个问题,
环境
Xcode Version 9.0 (9A235)
macOC 10.12.6

因为 ``url``为 ``nil`` 所以崩溃,看了工程的``Product``生成``app``里面确实没有``TZImagePickerController.bundle``
所以找不到,我暂时就在工程的``Build Phases``中将``TZImagePickerController.bundle``添加进去
即不崩溃。

**Comment by githhhh** [comment]
看看是不是 这里被勾选了【cp】copy Pods Resources -> Run script only when installing
