### ISSUE TITLE
快速滑动 满屏闪烁

### ISSUE THREAD

**Issue by simplecode-k** [banchichen/TZImagePickerController#61]
快速滑动 满屏闪烁
已经选中图片预览的页面中, 快速左右滑动, 选中状态不能及时显示
很容易crash

**Comment by banchichen** [comment]
你好，我今天下午测的时候（6s设备），快速滑动图片列表页，帧数基本保持在55帧以上，你是用什么设备呢，可以看看在你设备上帧数是多少吗？不及时显示是因为我本身就把刷新选中按钮的方法写在滑动结束的时候，微信是写在正在滑动的时候，如果要改成那样子，一句代码就可以的。
