### ISSUE TITLE
大大什么时候能支持Carthage?

### ISSUE THREAD

**Issue by HanXiaoTeng** [banchichen/TZImagePickerController#610]
跪求尽快支持Carthage的导入，谢谢大大

**Comment by tinpont** [comment]
我提交了一个PR https://github.com/banchichen/TZImagePickerController/pull/625，麻烦 @banchichen 看一下

**Comment by banchichen** [comment]
@HanXiaoTeng @tinpont Hi，1.9.8版本已经支持了Carthage了哈。
