### ISSUE TITLE
怎么样才能跳一级页面不是二级页面呢？

### ISSUE THREAD

**Issue by zhouhaokefd** [banchichen/TZImagePickerController#611]
![Uploading 1508384490861.jpg…]()
![Uploading 1508384396202.jpg…]()

现在点击相册直接进的是二级页面。我想点击相册进入一级页面，在点击里面的选项在到二级页面。请问下该如果设置或修改呢。。谢谢

**Comment by banchichen** [comment]
你好，把Demo里用的初始化方法，pushPhotoPickerVc属性传NO就行。
