### ISSUE TITLE
部分建议

### ISSUE THREAD

**Issue by biqinglin** [banchichen/TZImagePickerController#612]
1：我使用alloc init 初始化，并设置了相关参数present出来的页面其实是空的，也就是你并未做alloc init方法的处理，要么处理下要么用NS_UNAVAILABLE限制不能使用alloc init进行初始化。
2.我使用lazy load的方式创建，出现一个问题就是：我下次再进行选择的时候默认帮我选择了之前选择的图片（同一个对象）。建议开放一个api让我进行重置操作，因为有时候我就是想只有这一个对象存在

**Comment by banchichen** [comment]
你好，第二个问题可以参考Demo，不设置selectedAssets就不会默认选中
// 1.设置目前已经选中的图片数组
imagePickerVc.selectedAssets = _selectedAssets; // 目前已经选中的图片数组

**Comment by biqinglin** [comment]
iOS 9.3.3 
lazy load:
- (TZImagePickerController *)imagePickerController {
    
    if(!_imagePickerController) {
        _imagePickerController = [[TZImagePickerController alloc] initWithMaxImagesCount:0 delegate:self];
        _imagePickerController.allowPickingVideo = NO;
        _imagePickerController.naviBgColor = [UIColor whiteColor];
        _imagePickerController.naviTitleColor = ThemeRedColor;
        _imagePickerController.barItemTextColor = ThemeRedColor;
        _imagePickerController.naviTitleFont = [UIFont boldSystemFontOfSize:17];
        _imagePickerController.barItemTextFont = [UIFont systemFontOfSize:16];
        _imagePickerController.isStatusBarDefault = YES;
    }
    return _imagePickerController;
}
使用:
self.imagePickerController.maxImagesCount = count;
 [self presentViewController:self.imagePickerController animated:YES completion:nil];
问题描述：
第一次调用无问题，第二次调用已经默认选取了第一次调用选择的图
不管我设置selectedAssets与否，都是如此。

**Comment by banchichen** [comment]
@biqinglin 你好，懒加载情况下，第二次打开时如果不想要上一次的选中，就把selectedAssets置为空。置为空后，不可能还有上次的。

**Comment by banchichen** [comment]
第一点已做优化：https://github.com/banchichen/TZImagePickerController/commit/46389c43773b3c89b4367770fbecec06618ca656 
👍
