### ISSUE TITLE
关于国际化的建议

### ISSUE THREAD

**Issue by China-Robin** [banchichen/TZImagePickerController#613]
现在大部分APP都是内置切换语言，此时插件的语言还是跟随的本地语言，可以在NSBundle的扩展类中，加一个设置APP语言的方法，如果没有设置的话，默认跟随本地语言，这样会更方便一些

**Comment by China-Robin** [comment]
还有一个问题，当“完成”按钮的翻译过长的时候，会变成省略号

**Comment by LiuWenYu93** [comment]
现在也在做APP内切换语言的功能，请问您是怎么在系统中文下，而用户切换英文后，修改照片选择器中的语言的，能不能提供个思路

**Comment by China-Robin** [comment]
如果是自己修改的话，只能手动引入了，然后修改NSBundle+TZImagePicker.m这个扩展类

**Comment by banchichen** [comment]
@China-Robin Hi，你那里‘完成’按钮变省略号，是在什么语言环境下呢？
如果你那支持了更多的语言的话，欢迎提个PR哇~

**Comment by banchichen** [comment]
已支持，代码提交了：新增preferredLanguage属性，可以设置首选语言，优先于系统语言
https://github.com/banchichen/TZImagePickerController/commit/9fc4eb9ccb1afc50a1e825b9de19dc7ea382fa2b

同时新增了languageBundle的属性，允许使用选择器bundle外的语言文件~
```objectivec
@interface TZImagePickerConfig : NSObject
/// 语言bundle，preferredLanguage变化时languageBundle会变化
/// 可通过设置bundle，让选择器支持更多的语言。欢迎提交PR把语言文件提交上来~
@property (strong, nonatomic) NSBundle *languageBundle;
@end
```
随着下版发布~

**Comment by China-Robin** [comment]
@banchichen 你好，关于新的语言，我已经提交PR了，如果后续需要添加翻译可以@我，或者给我发email，另一个问题，完成按钮变成省略号是在越南语环境下才会出现的问题，下面是截图。
![simulator screen shot - iphone 8 plus - 2018-01-26 at 22 38 11](https://user-images.githubusercontent.com/13116572/35444704-4cf79e6e-02ea-11e8-8bcc-8e3934986cb1.png)
![simulator screen shot - iphone 8 plus - 2018-01-26 at 22 38 14](https://user-images.githubusercontent.com/13116572/35444705-4d2e36c2-02ea-11e8-9b32-04da2d7da599.png)

**Comment by banchichen** [comment]
感谢PR~

当时做国际化支持只考虑了中文和英文，所有完成按钮的宽度没有跟随文字宽度去适配，写死了44...
代码提交了~  
修复越南语下完成按钮显示不下的问题：https://github.com/banchichen/TZImagePickerController/commit/7b51c36ba645e6018925fd74145143a0b69c4c2e  

话说，越南语这个完成，字符好多呀...在照片选择页，5的屏幕下，选中原图按钮后会重叠...
这个完成，越南语下有字符少一点的表达吗？

**Comment by China-Robin** [comment]
@banchichen 你好，我问过翻译了，没有更简短的翻译了！不过可以考虑，如果文字过长，折行显示，这样就可以显示完全了

**Comment by banchichen** [comment]
@China-Robin 麻烦了，好的，我试试~👍

**Comment by JpacheGitHub** [comment]
@China-Robin 想问一下你在适配越南语的时候有没有遇见过下图的问题
![img_0470](https://user-images.githubusercontent.com/15686977/50534582-8dd4e980-0b79-11e9-80bd-83ce74029535.PNG)
PingFangSC-Regular, 使用的是这个字体, 我尝试了一下, 同一台设备, 给label赋值的时候如果使用的是text就会这样, 如果使用的是attributedText就没问题.
还有就是如果使用- systemFontOfSize: 字体就使用哪个方式赋值都没问题
然后我在另一台手机上运行, 所有赋值方式, 所有字体, 都没有问题, 机型iPhone X, 系统11.x...
这是为什么啊...我应该往哪个方向去找解决方案...不想全局换文字赋值方式...

**Comment by JpacheGitHub** [comment]
@China-Robin 适配越南语时候发现 iOS 12 之后所有版本, 使用 PingFangSC-Regular 这个字体, 给 UILabel.text 赋值的时候, 会出现一个字符被分成了两个字符, 觉得可能是 iOS 12 之后苹果暗改了字符集, 使用 attributedText 赋值就没问题, 但是又不可能全工程修改 label 的赋值方式, 有什么好的解决方案么...现象如下图 : 
![img_0470](https://user-images.githubusercontent.com/15686977/50536280-af3fd080-0b8d-11e9-934e-2f0759d929a6.PNG)
