### ISSUE TITLE
好像是线程错误 求解！

### ISSUE THREAD

**Issue by KionCh2n** [banchichen/TZImagePickerController#615]
libsystem_kernel.dylib`__abort_with_payload:
    0x11279f0a0 <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x11279f0a5 <+5>:  movq   %rcx, %r10
    0x11279f0a8 <+8>:  syscall 
->  0x11279f0aa <+10>: jae    0x11279f0b4               ; <+20>
    0x11279f0ac <+12>: movq   %rax, %rdi
    0x11279f0af <+15>: jmp    0x112798caf               ; cerror_nocancel
    0x11279f0b4 <+20>: retq   
    0x11279f0b5 <+21>: nop    
    0x11279f0b6 <+22>: nop    
    0x11279f0b7 <+23>: nop

**Comment by banchichen** [comment]
你好，你就贴个这日志我怎么解...

我该如何复现这个问题呢？
