### ISSUE TITLE
相册里面明明有GIF图片可是却筛选不出来!急

### ISSUE THREAD

**Issue by LiuYuHangNB** [banchichen/TZImagePickerController#616]
- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary<NSString *,id> *)info{
    
    NSString *assetString = [[info objectForKey:UIImagePickerControllerReferenceURL] absoluteString];
    if([assetString hasSuffix:@"GIF"] || [assetString hasSuffix:@"gif"]){
        //这个图片是GIF图片
        NSLog(@"gif");
        UIImage *img = info[UIImagePickerControllerEditedImage];
        NSLog(@"%f___%f",img.size.width,img.size.height);
        //这个图片是GIF图片
        ALAssetsLibrary *assetLibrary = [[ALAssetsLibrary alloc]init];
        [assetLibrary assetForURL:[info objectForKey:UIImagePickerControllerReferenceURL] resultBlock:^(ALAsset *asset) {
            ALAssetRepresentation *re = [asset representationForUTI:(__bridge NSString *)kUTTypeGIF];;
            NSUInteger size = (NSUInteger)re.size;
            uint8_t *buffer = malloc(size);
            NSError *error;
            NSUInteger bytes = [re getBytes:buffer fromOffset:0 length:size error:&error];
            NSData *data = [NSData dataWithBytes:buffer length:bytes];//这个就是选取的GIF图片的原二进制数据
            if (self.gifBlock) {
                self.gifBlock(data,img);
            }
            free(buffer);
        } failureBlock:^(NSError *error) {
            
        }];
            
    }
用上边这种方法就可以取到Gif 但是    imagePickerVc.allowPickingImage = YES;时却不走选择Gif的代理方法

**Comment by banchichen** [comment]
你好，可以这样排查：
1. 检查allowPickingGif是否为YES
2. 如果没有允许多选GIF，选择了GIF图片时，会走这个回调：didFinishPickingGifImage
3. 如果是允许多选GIF，选择了GIF图片时，会走这个回调：didFinishPickingPhotos

**Comment by LiuYuHangNB** [comment]
ok 谢谢
