### ISSUE TITLE
- (int32_t)getPhotoWithAsset:(id)asset photoWidth:(CGFloat)photoWidth completion:(void (^)(UIImage *photo,NSDictionary *info,BOOL isDegraded))completion progressHandler:(void (^)(double progress, NSError *error, BOOL *stop, NSDictionary *info))progressHandler networkAccessAllowed:(BOOL)networkAccessAllowed

### ISSUE THREAD

**Issue by Rochester-Ting** [banchichen/TZImagePickerController#617]
你好 由于UI 方面的原因  我只能使用您的Api获取数据,但是为什么- (int32_t)getPhotoWithAsset:(id)asset photoWidth:(CGFloat)photoWidth completion:(void (^)(UIImage *photo,NSDictionary *info,BOOL isDegraded))completion progressHandler:(void (^)(double progress, NSError *error, BOOL *stop, NSDictionary *info))progressHandler networkAccessAllowed:(BOOL)networkAccessAllowed这个方法 获取系统相册里的图片 为什么都是模糊的图啊 但是使用您的就是很清楚的图片 我的networkAccessAllowed设置为yes

**Comment by banchichen** [comment]
你好，图片清晰度取决于photoWidth传的值，因为TZImagePickerController的需要，根据不同的photoWidth传入值，内部会有取缩略图和适合屏幕尺寸大图的判断，详见源码哈。
如果要取清晰的图，photoWidth需传入大于或等于屏幕宽度的值，或者直接调用不需要传photoWidth的API...
