### ISSUE TITLE
取全景图片时.偶尔会卡.

### ISSUE THREAD

**Issue by ijldxyygy** [banchichen/TZImagePickerController#62]
类似一些拍得不好的全景图片,会卡

**Comment by banchichen** [comment]
你好，这种情况，应该QQ和微信的图片选择器也会卡哦~ 请测试一下会卡的那张全景图，在QQ和微信的图片选择器中表现如何~   另外，TZImagePickerController刚刚更新到了1.4.0版本，性能已经比较不错了，佳于微信的媲美QQ的了~  三个图片选择器的帧数表现可以看博客中的截图~http://www.jianshu.com/p/1975411a31bb

**Comment by ijldxyygy** [comment]
谢谢哈..我测试下

2016-05-23 17:01 GMT+08:00 Zhen Tan <notifications@github.com>:
