### ISSUE TITLE
iOS6 适配问题

### ISSUE THREAD

**Issue by weakGG** [banchichen/TZImagePickerController#621]
- (void)setNaviBgColor:(UIColor *)naviBgColor {
    _naviBgColor = naviBgColor;
    self.navigationBar.barTintColor = naviBgColor;
}

@property(nullable, nonatomic,strong) UIColor *barTintColor NS_AVAILABLE_IOS(7_0)

class TZPhotoPickerController  #296 。。。挺多地方
CGFloat previewWidth = [tzImagePickerVc.previewBtnTitleStr boundingRectWithSize:CGSizeMake(CGFLOAT_MAX, CGFLOAT_MAX) options:NSStringDrawingUsesFontLeading attributes:@{NSFontAttributeName:[UIFont systemFontOfSize:16]} context:nil].size.width + 2;

- (CGRect)boundingRectWithSize:(CGSize)size options:(NSStringDrawingOptions)options attributes:(nullable NSDictionary<NSString *, id> *)attributes context:(nullable NSStringDrawingContext *)context NS_AVAILABLE(10_11, 7_0);

**Comment by banchichen** [comment]
你好，感谢指出，代码已提交，将随着下版发布~   
https://github.com/banchichen/TZImagePickerController/commit/e0a4eda95d7ce29a031be5299b8609d3bab6f1ec      

最开始这个库是适配了iOS6的，慢慢地iOS6基本没啥APP适配了，写的新代码也就没注意iOS6了。
我手头目前不方便测试iOS6的表现，请问除了这2个地方，还有其它的吗？
