### ISSUE TITLE
iOS11问题 - [ImageManager] Unable to load image data

### ISSUE THREAD

**Issue by asd8855** [banchichen/TZImagePickerController#622]
[ImageManager] Unable to load image data, /var/mobile/Media/DCIM/101APPLE/IMG_1958.JPG

**Comment by banchichen** [comment]
应该是Apple的bug，目前没找到workaround，不过这个只在控制台打印，不影响使用，继续关注...

参考链接：   
https://forums.developer.apple.com/thread/85717        
https://stackoverflow.com/questions/46377824/ios-11-imagemanager-unable-to-load-image-data

**Comment by Lrgbird** [comment]
我获取的图片上传到服务器老是不成功，是不是因为这个bug的问题呢

**Comment by banchichen** [comment]
@Lrgbird 不是...这个是系统bug，所有图片选择器都这样，不影响功能的哈...
