### ISSUE TITLE
选完图片浏览时状态栏的隐藏问题

### ISSUE THREAD

**Issue by zhurlo** [banchichen/TZImagePickerController#623]
大神发现个问题，选完图片，浏览时，如果当前是导航控制器，present出TZPhotoPreviewController时，状态栏隐藏动画就会出现，原来的视图就会上移，感觉这种效果不太好。如果不在TZPhotoPreviewController的viewWillAppear方法里写 if (iOS7Later) [UIApplication sharedApplication].statusBarHidden = YES; 而是在didTapPreviewCell处理，让状态栏和导航一起隐藏显示，就和微信效果差不多了。
- (void)didTapPreviewCell {
    self.isHideNaviBar = !self.isHideNaviBar;
    _naviBar.hidden = self.isHideNaviBar;
    _toolBar.hidden = self.isHideNaviBar;
    [UIApplication sharedApplication].statusBarHidden = self.isHideNaviBar;
}

**Comment by banchichen** [comment]
你好，每次点击PreviewCell时都会走didTapPreviewCell，但是这个时候微信的图片选择器的状态栏是一直隐藏的，如果根据你的这个来修改的话，每次点击PreviewCell，状态栏的隐藏状态都会取反，和微信的效果是不一样的...

**Comment by zhurlo** [comment]
大神，我说的不是选完图片在相册里点图片(或者点预览)进行浏览。而是选完图片在上一界面（比如你demo里的ViewController里面）点击图片进行浏览，（微信里面从这两个地方进预览对状态栏的处理是不一样的）。如果把你demo里的ViewController放到导航控制器的话，点照片进预览的时候状态栏隐藏动画就会出现，导航栏就会向上偏移。感觉这是个问题，大神可以测试一下。

**Comment by banchichen** [comment]
你好，我觉得这里微信的处理也不是很好，页面显示后才隐藏状态栏，不是特别合适...

建议你这样，不要用导航栏控制器去present，改为直接用当前页面控制器去present，就不会有导航栏向上偏移的情况了...
