### ISSUE TITLE
选择图片视频后导出来不知道是什么东西

### ISSUE THREAD

**Issue by ZFbaby** [banchichen/TZImagePickerController#628]
<3,8,0x600000e46330>,[0x6000006b34a0--1920448] [0x6040006a4140--3941760] [0x6000000ba760--1931968] [0x6000006b3a40--1918048] [0x6040006a49e0--3938640] [0x6000006b5600--1933168] [0x6040006a3420--3942960] [0x6040002a4860--3940560]
图片资源没获取到，获取到了上面一连串不知道啥东西

**Comment by ZFbaby** [comment]
已解决

**Comment by banchichen** [comment]
👍
