### ISSUE TITLE
在iOS 8上用命令构建版本无法调用

### ISSUE THREAD

**Issue by RHwill** [banchichen/TZImagePickerController#629]
- (void)setNaviTitleColor:(UIColor *)naviTitleColor {
    _naviTitleColor = naviTitleColor;
    [self configNaviTitleAppearance];  // 这行
}

- (void)setNaviTitleFont:(UIFont *)naviTitleFont {
    _naviTitleFont = naviTitleFont;
    [self configNaviTitleAppearance];  // 这行
}

- (void)configNaviTitleAppearance {
    NSMutableDictionary *textAttrs = [NSMutableDictionary dictionary];
    textAttrs[NSForegroundColorAttributeName] = self.naviTitleColor
    textAttrs[NSFontAttributeName] = self.naviTitleFont
    self.navigationBar.titleTextAttributes = textAttrs;
}

self.naviTitleColor
self.naviTitleFont
// 在调用的时候上面两个值会有一个值是空的会导致无法调用。只有在命令构建版本时候出现，联调时并没有出现。

**Comment by banchichen** [comment]
你好，1.9.4版本已发布，对这里做了优化~
