### ISSUE TITLE
能否在第一张图片的位置自定义控件

### ISSUE THREAD

**Issue by Migo24K** [banchichen/TZImagePickerController#63]
如题，我们的设计稿在第一张照片的位置添加了一个“拍摄照片”，目前有办法实现吗？

**Comment by banchichen** [comment]
微博是第一张是拍摄照片，QQ是最后一张是拍摄照片。我现在的照片排列顺序是照微信和QQ做的，我试着把最后一张弄为拍摄照片吧。我现在写一下。

**Comment by banchichen** [comment]
QQ是指QQ空间~

**Comment by Migo24K** [comment]
或者这个有没有办法设置为选项，可自定义为第一个或最后一个

**Comment by banchichen** [comment]
不方便设置为选项，改动的代码就多了些，因为照片的时间顺序也定了的，我是按照了QQ空间、微信的排序做的。如果可以第一个，又可以最后一个，代码就多了，判断也多了...反而显得代码不好看...

**Comment by banchichen** [comment]
哥们...拍照的cell，图片素材你拿到了吗？发我下吧~  736420282@qq.com，我这个比较丑...

**Comment by Migo24K** [comment]
稍等下

**Comment by Migo24K** [comment]
大神，您能等到晚上或者明天吗？UI正好缺了这张图给我，我刚找她要，她在过周末，我让她晚上补给我

**Comment by banchichen** [comment]
你好，我直接拿的QQ空间的素材了，素材还挺可以的~功能加上去了，1.3.0版本~
