### ISSUE TITLE
TZImageManager 类中  修改原图大小文字  方法有点小问题

### ISSUE THREAD

**Issue by aluoshuai** [banchichen/TZImagePickerController#630]
此方法在数组Count为0的情况下，Block的回调是不起作用的，
getPhotosBytesWithArray:(NSArray *)photos completion:(void (^)(NSString *totalBytes))completion

我这里有个需求需要默认可以点击原图按钮，我用Runtime修改了refreshBottomToolBarStatus 这个方法发现的问题。

**Comment by aluoshuai** [comment]
我使用pod添加的源码，所以没法直接修改代码。

**Comment by banchichen** [comment]
你好，代码已经提交，随着下版发布~   
https://github.com/banchichen/TZImagePickerController/commit/9ec606b144fb2088c67fa4427939105adaf8b682
