### ISSUE TITLE
iOS8系统下拍照保存,保存失败且会崩溃

### ISSUE THREAD

**Issue by wuyang1989** [banchichen/TZImagePickerController#631]
在内部加入版本兼容处理，代码如下：
if (iOS8Later && !iOS9Later) {
                // 位于iOS8至iOS9之间
                PHAssetChangeRequest *request = [PHAssetChangeRequest creationRequestForAssetFromImage:image];
                if (location) {
                    request.location = location;
                }
                request.creationDate = [NSDate date];
            } else {
                // 高于iOS9
                PHAssetResourceCreationOptions *options = [[PHAssetResourceCreationOptions alloc] init];
                options.shouldMoveFile = YES;
                PHAssetCreationRequest *request = [PHAssetCreationRequest creationRequestForAsset];
                [request addResourceWithType:PHAssetResourceTypePhoto data:data options:options];
                if (location) {
                    request.location = location;
                }
                request.creationDate = [NSDate date];
            }

你看是否可以？

**Comment by banchichen** [comment]
在iOS8时，ALAssetsLibrary的writeImageToSavedPhotosAlbum应该也是稳定的，我刚刚在iOS11.1.1的系统下保存照片是OK的。   
我手头没有iOS8的真机，不过PHAssetChangeRequest保存照片也是OK的，在我目前的设备上测试OK，代码已经提交，随着下次版本发布~    
https://github.com/banchichen/TZImagePickerController/commit/98bd8e0a838d33be03ed45c94a77a73196e8f9cb

**Comment by wuyang1989** [comment]
我发现在iOS8系统中，拍照保存后，通过[[TZImageManager manager] savePhotoWithImage:image completion:保存照片，再通过[[TZImageManager manager] getCameraRollAlbum:NO allowPickingImage:YES completion:获取相册会失败,我断点跟踪到[self isCameraRollAlbum:collection]这个方法，发现在iOS8找不到‘新增照片’这个相册的枚举(PHAssetCollectionSubtypeSmartAlbumRecentlyAdded)

**Comment by banchichen** [comment]
@wuyang1989 我知道了，你的iOS8系统，是iOS8.0 ~ iOS8.0.2之间吗？这几个系统版本下，拍照完的照片是保存在最近添加里的，要特别判断下。这个地方被其它人提过PR，对判断逻辑做了优化，但是没注意特殊处理iOS8.0 ~ iOS8.0.2版本，我给这个特殊处理再补上一下...      
可以看看这个issue: https://github.com/banchichen/TZImagePickerController/issues/148

**Comment by banchichen** [comment]
@wuyang1989 我把代码提交了：https://github.com/banchichen/TZImagePickerController/commit/4282dfd0bdbb2ca8b19e37caeefdd6726799023f   麻烦你再测试下~

**Comment by wuyang1989** [comment]
这个方法我已经做过处理了，你看是否有问题，代码如下:
- (BOOL)isCameraRollAlbum:(id)metadata {
    
    if ([metadata isKindOfClass:[ALAssetsGroup class]]) {
        ALAssetsGroup *group = metadata;
        return ([[group valueForProperty:ALAssetsGroupPropertyType] intValue] == ALAssetsGroupSavedPhotos);
    }
    if ([metadata isKindOfClass:[PHAssetCollection class]]) {
        if (((PHAssetCollection *)metadata).assetCollectionSubtype == PHAssetCollectionSubtypeSmartAlbumUserLibrary || ((PHAssetCollection *)metadata).assetCollectionSubtype == PHAssetCollectionSubtypeSmartAlbumRecentlyAdded) {
            return YES;
        } else {
            return NO;
        }
    }
    
    return NO;
}

**Comment by banchichen** [comment]
@wuyang1989 有问题的，在iOS8.1及以上系统上，所有照片和最近添加2个相册都存在，但拍照的照片存在所有照片里。所以不能只 || 一下...，如果在iOS8.1及以上系统上，把最近添加当做了CameraRollAlbum，就又要崩溃了
