### ISSUE TITLE
手机里的图片超过一万张的时候，进入TZImagePickerController需要等待1到2秒

### ISSUE THREAD

**Issue by Slience2015** [banchichen/TZImagePickerController#632]
手机里的图片超过一万张的时候，进入TZImagePickerController需要等待1到2秒，延时很严重。。。。。。

**Comment by banchichen** [comment]
你好，请问这个时候微信和QQ的图片选择器，进入时有卡顿吗？
我这里是3000张图片，在6s上表现比较OK。

等待1-2秒，是弹出选择器就需要1-2秒，还是进入后loading了1-2秒呢？

**Comment by Slience2015** [comment]
是弹出选择器需要等待1到2秒，6sPlus手机里面大概1万五千多张图片 @banchichen

**Comment by Slience2015** [comment]
微信和QQ的没有 @banchichen

**Comment by banchichen** [comment]
好的，看来要好好研究一波...

**Comment by xispower** [comment]
如果在ios 7 上，超过5000张，也非常慢。

**Comment by JsoonLi** [comment]
现在碰到老板相博里有9万张图，iPhoneX等5秒以上才能出来，也在想办法如何优化。

**Comment by banchichen** [comment]
@Slience2015 @xispower @JsoonLi 刚刚看了一下，我这iPhone8下，3800张图片，打开选择器时在主线程获取所有照片的方法耗时约70ms，是最耗时的方法，目前已经对这块做了优化，打开选择器应该比较快且不随着照片增多而变慢：https://github.com/banchichen/TZImagePickerController/commit/6474f6815ece270f164a4ac6dc5cdb27c6c59106

获取所有照片的方法，被放到了子线程执行，并且会有“正在处理...”的提示，体验有进步哈。刚刚发布了新版2.0.0.3，如果升级后，还和微博、QQ、微信等的选择器有差距，请再回来指出~

**Comment by JsoonLi** [comment]
我发现有的手机上有上千个空相册，测试时2千个空相册模拟器打开3秒左右。目前通过
`if (collection.estimatedAssetCount == 0) continue;` 这种方式优化的

**Comment by banchichen** [comment]
@JsoonLi 我看我这里的空相册，微信是会展示的。这种上千个空相册的情况，应该微信也得loading转圈3秒~？

**Comment by JsoonLi** [comment]
@banchichen 我们老板的手机微信不卡。他的空相册多，照片也多，9万多张。正在找问题，代码
`TZImageManager`中 `PHFetchResult *fetchResult = [PHAsset fetchAssetsInAssetCollection:collection options:option];if (fetchResult.count < 1) continue;` 这不是已经过滤了吗

**Comment by banchichen** [comment]
恩，看来之前是过滤了空相册的...
`fetchAssetsInAssetCollection: options:`确实有一定的耗时，你升级了2.0.0.3，再加上`if (collection.estimatedAssetCount == 0) continue;`，老板的手机还卡吗？

**Comment by banchichen** [comment]
@JsoonLi 对了，微信的图片选择器应该会有缓存，退出微信进程，第一次进入图片选择器，比第二次及之后的进入，明显要顺畅些。所以要拿退出微信进程后的第一次进入来比较哦。。。

**Comment by JsoonLi** [comment]
@banchichen 卡，还是那个一个相册9万张图的问题，把空相册去掉了也还是等很久。微信稍微快一点，但微信有时候会直接卡住，不稳定。

**Comment by banchichen** [comment]
@JsoonLi 读取9万张图片的时候是在后台读取的，这个等很久是指进入照片选择页的loading要转很久是吧？
还有一种优化方案，就是进入照片选择页后，先读取最多2000张照片（估计100毫秒左右），读取2000张结束后刷新界面让用户先看到照片，再开一个后台任务读取剩余的照片。应该对你老板这种情况有效果，我最近几天没空弄，如果你弄好了的话欢迎提个PR~

**Comment by saltcoffee** [comment]
这个问题有解么大佬。

**Comment by saltcoffee** [comment]
@banchichen 这个问题有解么大佬。
