### ISSUE TITLE
可以在选择列表添加一个拍照按钮吗，类似微信。

### ISSUE THREAD

**Issue by JiekangLiao** [banchichen/TZImagePickerController#634]
怎么在选择列表中添加一个拍照按钮呢，就是第一个按钮是用来拍照的，其他的全都是供选择的照片。
还有，另外一个问题就是，我想用自己的按钮标题，例如，左侧返回按钮，右侧取消按钮，左下方要一个从下方弹出照片分组的列表的按钮，右下方的按钮同样也要自定义。好像都看不到有地方可以设置呢。

**Comment by MuseYkh** [comment]
有拍照按钮的啊

**Comment by banchichen** [comment]
@JiekangLiao 拍照按钮目前是有的。你提到的这些自定义我不是特别明白，目前应该是没有支持的，如果需要，建议修改源码。

**Comment by JiekangLiao** [comment]
@banchichn就是跟微信的选择器一样，在第一个item作为拍照按钮

**Comment by JiekangLiao** [comment]
我用这个打开相册就崩溃了

**Comment by banchichen** [comment]
@JiekangLiao 开启这个开关：《把拍照按钮放在外面》，是不是就是你想要的效果...

**Comment by JiekangLiao** [comment]
这么说吧，就是collectionview的第一个item作为拍照按钮其他item是图片。好像安卓才有这个功能

**Comment by banchichen** [comment]
@JiekangLiao 目前就是这样的啊...
![image](https://user-images.githubusercontent.com/12755494/32777775-18928d54-c8fd-11e7-9a06-1327a062e902.png)

**Comment by JiekangLiao** [comment]
哦哦，我怎么看不到的，不过相机按钮不应该放前面比较好吗

**Comment by banchichen** [comment]
@JiekangLiao 拍第一和拍最后可以调的，关掉《照片按修改时间升序排列》即可。只在相机胶卷或所有照片相册内有。

**Comment by Liyongcong** [comment]
> @JiekangLiao 排第一和排最后可以调的，关掉《照片按修改时间升序排列》开关即可。只在相机胶卷或所有照片相册内有。你先把Demo跑起来看看...就知道有多少功能了...
    TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:self.maxCountTF.text.integerValue columnNumber:self.columnNumberTF.text.integerValue delegate:self pushPhotoPickerVc:YES];
  imagePickerVc.sortAscendingByModificationDate = NO;
我这样设置没有用

**Comment by banchichen** [comment]
@Liyongcong Demo是正常的，参考下Demo
