### ISSUE TITLE
iPhoneX判断

### ISSUE THREAD

**Issue by hegelsu** [banchichen/TZImagePickerController#635]
+(BOOL)isIPhoneX{
    struct utsname systemInfo;
    uname(&systemInfo);
    NSString *platform = [NSString stringWithCString:systemInfo.machine encoding:NSASCIIStringEncoding];
    if ([platform isEqualToString:@"i386"] || [platform isEqualToString:@"x86_64"]) {
        // 模拟器下采用屏幕的高度来判断
        return [UIScreen mainScreen].bounds.size.height == 812 || [UIScreen mainScreen].bounds.size.width == 812;
    }
    BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] || [platform isEqualToString:@"iPhone10,6"];
    return isIPhoneX;
}

**Comment by banchichen** [comment]
谢谢指出~已修复并提交，随着下版发布~

**Comment by asd8855** [comment]
能否用宽高来判断是否是iPhoneX

**Comment by hegelsu** [comment]
目前来说是可以的，但用platform来判断是更合理的一种方式

**Comment by asd8855** [comment]
懂了

**Comment by coderchou** [comment]
###  一个模拟器上判断设备是否iPhone X 的方法
```objc 
//进程信息类
@interface NSProcessInfo : NSObject {
@property (class, readonly, strong) NSProcessInfo *processInfo;
@property (readonly, copy) NSDictionary<NSString *, NSString *> *environment;
@property (readonly, copy) NSArray<NSString *> *arguments;
```
 **environment** 这个字典属性中, 有 **SIMULATOR_MODEL_IDENTIFIER** 这个key，拿到的设备型号跟真机是一样的

```
"SIMULATOR_MODEL_IDENTIFIER" = "iPhone10,3";
```

```objc
+ (BOOL)isIPhoneX{
    static BOOL isIPhoneX = NO;
    static dispatch_once_t onceToken;
    
    dispatch_once(&onceToken, ^{
        
#if TARGET_IPHONE_SIMULATOR
        //根据进程信息获取模拟器型号
        NSString *model = NSProcessInfo.processInfo.environment[@"SIMULATOR_MODEL_IDENTIFIER"];
#else
        struct utsname systemInfo;
        uname(&systemInfo);
        
        NSString *model = [NSString stringWithCString:systemInfo.machine
                                             encoding:NSUTF8StringEncoding];
#endif
        isIPhoneX = [model isEqualToString:@"iPhone10,3"] || [model isEqualToString:@"iPhone10,6"];
    });
    
    return isIPhoneX;
}

```
