### ISSUE TITLE
裁切时缩小图片无法拖动，会自动拉伸到屏幕边缘

### ISSUE THREAD

**Issue by huowenxuan** [banchichen/TZImagePickerController#636]
如果是正方形的图片，无法选择整张图片，只能切中间一部分
![11 -13-2017 16-35-29](https://user-images.githubusercontent.com/13825444/32716371-aa41e7c6-c890-11e7-83a3-e81d9e2ec069.gif)

**Comment by aimm** [comment]
我也遇到了同样的问题，请问你是怎么处理的？

**Comment by huowenxuan** [comment]
@aimm 没有处理。。希望作者能处理一下

**Comment by banchichen** [comment]
这个裁剪是模仿UIImagePickerController的，如果需要选择整张图片，裁剪框的宽度应当设置为屏幕宽度....
