### ISSUE TITLE
为什么不做一个相册浏览的功能呢?向微信查看大图一样的

### ISSUE THREAD

**Issue by CarlXu1008** [banchichen/TZImagePickerController#638]

**Comment by banchichen** [comment]
你好，因为这个库的定位是照片选择器...不考虑开发成相册浏览器...

**Comment by CarlXu1008** [comment]
哦,可以考虑一下,把这个功能加进来,一般项目要使用照片选择都会用到照片浏览,这样用第三方就得导入2个库,使用比较麻烦,如果能有一个库可以统一实现这个功能,相信应该能很受欢迎!
