### ISSUE TITLE
iOS9.3貌似没没有相机胶卷导致进入不了照相界面.但是模拟器中有胶卷,不知道是什么问题

### ISSUE THREAD

**Issue by Bastionhh** [banchichen/TZImagePickerController#64]

**Comment by banchichen** [comment]
那你进去的是相册列表页么？  我当时9.3的系统，是没问题的......现在9.3.1也没问题...    你用picker看到的相册列表页，和自带的相册看到的相册列表页，得到的相册列表是一致的吗？

**Comment by Bastionhh** [comment]
是一致的.只是个人收藏和全景照片还是英文状态.刚去网上查了查,难道是我个人的原因吗...我手机有一个叫所有照片的想薄而没有相机胶卷.

**Comment by banchichen** [comment]
为什么你的相册列表，没有相机胶卷呢....我在里面是是判断相机胶卷的，如果有这个相册就到这个相册详情页，没有的话就在相册列表页。请问你如果在微信里面的话，是会进去到哪个相册详情页呢？  微信也是优先展示相机胶卷详情页的，不知道做没做了你这种情况的处理...

**Comment by Bastionhh** [comment]
嗯嗯,我看了你的代码.我改成了所有照片貌似能进去了,可是一看好多呀...怕改乱了. 我在微信测试的是进入所有照片.估计是做了判断,不过微信的拍照按钮不是做到cell上,可不可以把拍照那个按钮单独拿出来呢,或者告诉我这个按钮是在那个类里面,我进去调一下也好.谢谢了!

**Comment by banchichen** [comment]
恩，那还是微信牛。你搜索takePicture方法，在TZPhotoPickerController的371行，里面是拍照的相关代码，使用的是系统的UIImagePickerController去拍照，初始化在41行的懒加载里面。

**Comment by Bastionhh** [comment]
嗯嗯好,多谢.对了,系统的个人收藏还有全景照片这两个相薄还是英文.

**Comment by browningweb** [comment]
title可以设为中文，只要在项目的info.plist里面添加Localized resources can be mixed，值设为YES就行了。

**Comment by browningweb** [comment]
我把“相机胶卷” or “全部照片” 放到了 TZImagemanager 里面了
`- (BOOL)isAllPhoto:(NSString *)name
{
    return [name isEqualToString:@"Camera Roll"] || [name isEqualToString:@"相机胶卷"] || [name isEqualToString:@"所有照片"];
}`

**Comment by Bastionhh** [comment]
@browningweb 请问该怎么使用呢 在外面做判断吗

**Comment by browningweb** [comment]
@Bastionhh 把代码里判断这个的，全部用这个方法做判断，算是个折中的办法吧

**Comment by banchichen** [comment]
大家好，这个问题1.3.1版本已经解决好了，更新下吧~谢谢指出~
