### ISSUE TITLE
在iPhone X下底部的toolbar和虚拟home键区域重叠啦

### ISSUE THREAD

**Issue by ice0github** [banchichen/TZImagePickerController#640]
如题
![simulator screen shot - iphone x - 2017-11-15 at 13 18 12](https://user-images.githubusercontent.com/5554889/32820169-f8f3d32a-ca07-11e7-95a2-aa787b33e56e.png)

**Comment by banchichen** [comment]
你好，已经适配过啦，升级到1.9.4哈：https://github.com/banchichen/TZImagePickerController/issues/597
