### ISSUE TITLE
hello ! 发现一个需求: 选择用拍照模式,获取到的照片太大了!! 怎么处理好呢~~

### ISSUE THREAD

**Issue by Xianlau** [banchichen/TZImagePickerController#641]

**Comment by banchichen** [comment]
可以拿到图片后，缩放一下：
/// Scale image / 缩放图片
- (UIImage *)scaleImage:(UIImage *)image toSize:(CGSize)size {
    if (image.size.width < size.width) {
        return image;
    }
    UIGraphicsBeginImageContext(size);
    [image drawInRect:CGRectMake(0, 0, size.width, size.height)];
    UIImage *newImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return newImage;
}

**Comment by Xianlau** [comment]
感谢哈! 我昨天下午找到了这个方法! 挺实用
