### ISSUE TITLE
关于网络和本地的图片视频混合预览

### ISSUE THREAD

**Issue by WangYongBo** [banchichen/TZImagePickerController#642]
请问大神是否考虑在框架中加入 类似 微信-聊天页面中 网络和本地的图片视频混合预览功能呢 看了下git上类似此功能的框架还比较少 而且大多做的不是很好

**Comment by banchichen** [comment]
Hi，3.0.1版本已支持，需新接一个插件库：[TZImagePreviewController](https://github.com/banchichen/TZImagePreviewController)，请参考TZImagePreviewController里面的Demo使用。

抱歉久等了...
