### ISSUE TITLE
选取iCloud视频崩溃

### ISSUE THREAD

**Issue by yaoxc** [banchichen/TZImagePickerController#643]
<img width="715" alt="wx20171117-111143 2x" src="https://user-images.githubusercontent.com/6771120/32927542-cc39833c-cb12-11e7-9b80-686f4bb0e34e.png">

**Comment by yaoxc** [comment]
手机：iPhone 5s  iOS11.1.1

**Comment by banchichen** [comment]
是在我的Demo里测试的吗，有修改了什么吗？

**Comment by banchichen** [comment]
可以定位到崩溃在哪行代码吗，打一个异常断点看看...

**Comment by yaoxc** [comment]
是你的demo，我下载下来直接运行的

**Comment by yaoxc** [comment]
<img width="981" alt="wx20171117-114157 2x" src="https://user-images.githubusercontent.com/6771120/32928326-083b3f70-cb17-11e7-8e46-f7cf71c97204.png">

**Comment by yaoxc** [comment]
还有，我选取一个iCloud视频，该视频还没下载下来，怎么弹出 HUD提示用户啊？现在是我只要选取视频，就会立刻回调，但是也没有拿到视频信息

**Comment by banchichen** [comment]
这个coverImage还是空对吧....
好的，这里我完善一下，iCloud视频没下载完时提醒下用户，下载完后再回调，做成和选iCloud图片一样~

**Comment by yaoxc** [comment]
@banchichen 嗯，或者把提醒给我们开放出来。现在直接回调会有问题。期待你的修改。。。

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/620

**Comment by yaoxc** [comment]
@banchichen 如何解决呢？现在选择iCloud视频会直接回调，UI操作不下去了！

**Comment by banchichen** [comment]
@yaoxc 你好，可以先这样处理，如果发现coverImage是nil，就再去获取一下。可以参考TZVideoPlayerController里configMoviePlayer方法...

**Comment by AYJk** [comment]
@banchichen 我从icloud选择后，coverImage不是nil诶，我想还没同步完成的话，禁用完成按钮，请问该怎么做？或者有什么规避方案吗？因为我这边做的是选取视频得到Asset通过七牛的接口上传处理，七牛这边报错说无法打开文件。我貌似不能从你返回的coverImage和asset去判断吧？
![1514292951866](https://user-images.githubusercontent.com/16362013/34357122-47044cec-ea7f-11e7-9b4e-00dd4d77680b.jpg)

**Comment by banchichen** [comment]
@AYJk 那应该是七牛的问题...asset资源即使保存在iCloud里，七牛既然允许通过asset来上传，就要做好iCloud支持的。

**Comment by banchichen** [comment]
目前新版优化成了视频封面未成功获取前，完成按钮无法点击，不会再出现coverImage可能为nil的情况。用户选取的视频可能存在iCloud里，这种视频的鉴别办法是看PHImageResultIsInCloudKey字段是否是1，比如库内部的如下代码里，如果是iCloud视频，info字典里会有PHImageResultIsInCloudKey字段且值为1：
```objectivec
[[PHImageManager defaultManager] requestPlayerItemForVideo:asset options:option resultHandler:^(AVPlayerItem *playerItem, NSDictionary *info) {
    if (completion) completion(playerItem,info);
}];
```

但是不影响大家使用，如果是通过七牛上传，直接传asset即可，asset是通用的，如果需要本地文件路径，则通过TZImageManager的getVideoOutputPathWithAsset导出到本地沙盒即可，iCloud视频是能成功导出的：
![image](https://user-images.githubusercontent.com/12755494/40281014-4f8e3a9a-5c8e-11e8-8e7a-7ce356b8bee2.png)
