### ISSUE TITLE
真机上,第一次授权,选择是,显示空白

### ISSUE THREAD

**Issue by tiger8888** [banchichen/TZImagePickerController#65]
真机上,第一次授权,选择是,显示空白,得第二次进入,才能正常显示,不知道是什么原因,能解决下嘛,谢谢

**Comment by tiger8888** [comment]
ios版本是ios9.1

**Comment by tiger8888** [comment]
我自己土方法修复了一下,希望坛主官方修复下

**Comment by banchichen** [comment]
你好，这个是很久之前的一个问题的，请更新到新版本试试~新版本不会有这个问题的~
