### ISSUE TITLE
请问什么时候适配iPhone X

### ISSUE THREAD

**Issue by Bruce-pac** [banchichen/TZImagePickerController#650]

**Comment by banchichen** [comment]
你好，已经适配了...
![image](https://user-images.githubusercontent.com/12755494/33156839-84e91be8-d038-11e7-8351-2c53e2f809dd.png)

**Comment by banchichen** [comment]
用最新版1.9.6   https://github.com/banchichen/TZImagePickerController/releases/tag/1.9.6
