### ISSUE TITLE
gif 和 video 预览页面底部_toolBar没有适配iPhone X

### ISSUE THREAD

**Issue by Beyond-Chao** [banchichen/TZImagePickerController#651]
TZVideoPlayerController 和 TZGifPhotoPreviewController 页面底部的_toolBar 没有适配iPhone X。

**Comment by Beyond-Chao** [comment]
最新版本 1.9.5

**Comment by banchichen** [comment]
谢谢指出，已修复，稍后发个1.9.6版本~

**Comment by banchichen** [comment]
已发布：https://github.com/banchichen/TZImagePickerController/releases/tag/1.9.6
