### ISSUE TITLE
ios11中 状态栏消失的问题

### ISSUE THREAD

**Issue by CoCodeIsLife** [banchichen/TZImagePickerController#653]
app 设置了白色状态栏,在选择图片时候预览图片,再返回 会导致app的状态栏消失,

**Comment by lingfengmarskey** [comment]
我也遇到了这个问题

**Comment by GitHubOfLeon** [comment]
我也是这个问题，info.plist 没有像demo那样设置是否隐藏statusbar，只是设置了白色状态栏。

然后刚打开进入TZPhotoPickerController的时候是显示状态栏的，点击图片进入TZPhotoPreviewController的时候在慢放动画里能看到 ：
demo里的状态栏和导航栏是一起消失，然后返回TZPhotoPickerController的时候状态栏和导航栏一起出现的。
而在我这里，进入TZPhotoPreviewController的时候，慢放动画里只看到了statusbar消失了，导航栏还在，导致返回TZPhotoPickerController的时候，statusbar没了，但是导航栏还在，也就是上移了20像素...
[我的工程效果.zip](https://github.com/banchichen/TZImagePickerController/files/1516491/default.zip)
[demo效果.zip](https://github.com/banchichen/TZImagePickerController/files/1516500/demo.zip)

**Comment by lingfengmarskey** [comment]
解决方案是:preset 之前,设置autoDismiss = NO;
`然后,再回调方法中如下设置
`
- (void)imagePickerController:(TZImagePickerController *)picker
       didFinishPickingPhotos:(NSArray<UIImage *> *)photos
                 sourceAssets:(NSArray *)assets
        isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto
{
    if (picker.childViewControllers.count == 3) {
        UIViewController *preview = picker.childViewControllers.lastObject;
        if (preview) {
            [preview.navigationController popViewControllerAnimated:NO];
        }
    }
    [picker dismissViewControllerAnimated:YES completion:^{ 
    }];
`
就正常了

**Comment by banchichen** [comment]
抱歉，被我改坏了...   这里有解释哈：https://github.com/banchichen/TZImagePickerController/issues/689

**Comment by banchichen** [comment]
1.9.7版本发布了哈，修复了这个问题~
