### ISSUE TITLE
关于电池条隐藏的问题，有一行代码不理解 TZPhotoPreviewController.m - (void)viewWillDisappear:(BOOL)animated 

### ISSUE THREAD

**Issue by VanishTan** [banchichen/TZImagePickerController#658]
TZPhotoPreviewController.m

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    [self.navigationController setNavigationBarHidden:NO animated:YES];
//    if (TZ_showStatusBarInitial && iOS7Later) {
    if (iOS7Later) {
        [UIApplication sharedApplication].statusBarHidden = NO;
    }
    [TZImageManager manager].shouldFixOrientation = NO;
}

line：81
我替换了这行代码，解决了电池条隐藏后不显示的问题，以及，像素偏移的问题
//    if (TZ_showStatusBarInitial && iOS7Later) {
    if (iOS7Later) {
        [UIApplication sharedApplication].statusBarHidden = NO;
    }

大大，引起这个问题的原因是因为我在plist文件中设置了电池条隐藏，为了方便开屏时隐藏电池条。然而您的Demo电池条设置为NO。

**Comment by VanishTan** [comment]
但是这样就隐藏不了电池条了

**Comment by banchichen** [comment]
这里的逻辑是这样，如果info.plist里设置了状态栏隐藏，那么选择器不会设置显示状态栏。

这个逻辑是之前一位同学提的，他们APP里需要全局隐藏状态栏...

看来最好应该提供一个代理方法...

**Comment by weiminghuaa** [comment]
是的，这里有点怪了，TZImagePickerController是显示状态栏，进入TZPhotoPreviewController后隐藏，这没问题，但是返回TZImagePickerController仍然隐藏，就不是很好了，希望大神改一下。

**Comment by xiaohuapunk** [comment]
mark 同样发现这个问题

**Comment by banchichen** [comment]
@xiaohuapunk @weiminghuaa @VanishTan  1.9.7版本发布了哈，废弃了TZ_showStatusBarInitial，修复了这个问题~
