### ISSUE TITLE
你好,可以请教你一些问题吗,关于OC和JS交互的问题

### ISSUE THREAD

**Issue by Bastionhh** [banchichen/TZImagePickerController#66]
JS调用OC代码成功了 并且要传递参数给我,JS代码是这样的pia.uploadPicture({
'success': function(res){
var resp = eval('(' + res + ')');
obj.src = 'img:'+resp.urls;
obj.height = $(window).width()*0.65;
$('#' + photoItem).val(resp.ids);
},
single: true
});
其中single接收到了为1. 但是success接收不到,想问一下OC是不是不能接收这样的,这个success里面貌似是活的,每次都不一样,并且有对象不是单纯的字符串什么的.OC是不是不能接收这样的.

**Comment by banchichen** [comment]
抱歉啊...我不太会JS....
