### ISSUE TITLE
GIF上传，如何限制2M以内的gif可选？

### ISSUE THREAD

**Issue by lifengios** [banchichen/TZImagePickerController#660]

**Comment by banchichen** [comment]
你好，限制大小的话不好限制的，如果gif保存在iCloud里，查看gif大小是要发请求的。

具体控制gif能不能选，可以参考Demo的isAssetCanSelect协议方法实现，这里返回NO，这个gif就不会展示出来。

gif的mediaType是PHAssetMediaTypeImage，其asset的filename属性会有GIF的后缀。可以在isAssetCanSelect里看看asset的其它直接能获取的属性，来做过滤...
