### ISSUE TITLE
选取存储在iCloud的视频希望添加一个类似读取图片的进度

### ISSUE THREAD

**Issue by stickor** [banchichen/TZImagePickerController#661]
手机(ios11)勾选了这个选项后,读取iCloud视频时希望加个进度条---☺️

![image](https://user-images.githubusercontent.com/17432227/33371344-580836f2-d535-11e7-9bac-a55a4092be84.png)
![image](https://user-images.githubusercontent.com/17432227/33371536-0871cd00-d536-11e7-9a5c-8f1d7158e14c.png)

**Comment by banchichen** [comment]
如果视频存储在iCloud的话，选中的时候会去获取封面大图，如果封面也在iCloud里，这个时候也是有进度条的，不过是封面的进度条。

使用TZImagePickerController选取视频不需要把iCloud视频下载到本地哈，在预览页面的播放不需要先下载的，选取了视频后如果需要保存到本地沙盒，用TZImageManager的getVideoOutputPathWithAsset来导出，会把视频下载好保存到本地沙盒。
