### ISSUE TITLE
TZPhotoPreviewController 执行doneButtonClick 奔溃

### ISSUE THREAD

**Issue by luckywbj** [banchichen/TZImagePickerController#662]
剪切图片后，点击完成doneButtonClick，程序执行到
  [self.navigationController dismissViewControllerAnimated:YES completion:^{
            [weakSelf callDelegateMethodWithPhotos:photos assets:assets infoArr:infoArr];
 }];

dismissViewController后，奔溃！
偶然现象，不好复现！

**Comment by luckywbj** [comment]
目前开发过程中一直没有复现，这个问题是线上奔溃日志捕捉到的
dismissViewController后，回到我自己的viewController,执行到viewDidAppear后，就奔溃了

**Comment by XAmateur** [comment]
剪切图片后，点击完成doneButtonClick，程序执行到
   
CGContextRef context = CGBitmapContextCreate(NULL, outputSize.width, outputSize.height, CGImageGetBitsPerComponent(source), 0, CGImageGetColorSpace(source), CGImageGetBitmapInfo(source));
创建的context为nil
崩溃。

**Comment by luckywbj** [comment]
望解答！

**Comment by banchichen** [comment]
@luckywbj 不好复现，也就不好分析...你贴出的这个崩溃堆栈也看不出什么信息...

**Comment by banchichen** [comment]
@XAmateur 你好，有必然的复现步骤或环境吗？我这里裁剪图片没遇到过这样的情况...
