### ISSUE TITLE
获取不到所有的图片

### ISSUE THREAD

**Issue by wangxiaola** [banchichen/TZImagePickerController#663]
首先谢谢大神的demo，最近小弟在使用demo的时候发现获取手机相册图片的时候有些图片是获取不到的，后来查看这些异常图片都是一些大图片，十几兆的那种高清图。

**Comment by banchichen** [comment]
@wangxiaola 你好，那这些图片，在微信和QQ的图片选择器里，可以获取到吗？

**Comment by wangxiaola** [comment]
不好意思，我这边看错了  图片太多了没看清，谢谢。

**Comment by banchichen** [comment]
好吧...👍
