### ISSUE TITLE
iOS 11.1 , iPhone 7 crash

### ISSUE THREAD

**Issue by zywang** [banchichen/TZImagePickerController#665]
<img width="1002" alt="2017-12-01 11 22 17" src="https://user-images.githubusercontent.com/680810/33466601-f6d0c010-d689-11e7-983f-2f3ab4fd32a0.png">

打开相册选照片crash

**Comment by banchichen** [comment]
Hi，可以打个异常断点，看看程序崩在哪一行吗，然后看看崩的时候，这个相册是否有异常，把获取的一些属性贴出来看看哈
