### ISSUE TITLE
关于选择gif以及静态图的问题

### ISSUE THREAD

**Issue by ChenZhenChun** [banchichen/TZImagePickerController#667]
1、gif只能选择一张吗？
2、当我先选择gif之后再次选择gif时提示信息是“选择照片不能选择gif”（我两张都是gif其实）

**Comment by ChenZhenChun** [comment]
什么时候才能支持gif及静态图都可以选择，而且gif可以选择多张

**Comment by ChenZhenChun** [comment]
状态栏颜色都是白色的，我设置成黑色也无效果，我需要延时设置状态栏的颜色才有效果。

**Comment by banchichen** [comment]
你好，参考Demo的效果，设置allowPickingMultipleVideo为YES，就可以多选视频/gif/图片。要修改状态栏颜色，设置下isStatusBarDefault为YES。
