### ISSUE TITLE
iPhoneX 适配中的问题

### ISSUE THREAD

**Issue by STShenZhaoliang** [banchichen/TZImagePickerController#668]
1、+ (BOOL)tz_isIPhoneX中针对模拟器的代码有问题
建议改为 return (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) ||
                CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)));

2、手机横屏 下方的toolBar显示高度有问题，对于系统软件Pages

**Comment by banchichen** [comment]
1：已完成
2：系统Pages底部是系统UITabBar，横屏时布局会变化，TZ是写死的高度，没计划正对横屏优化哈
