### ISSUE TITLE
ios7选择照片 选择除了相机胶卷之外的相册最后一张会崩溃

### ISSUE THREAD

**Issue by haha1077** [banchichen/TZImagePickerController#67]
ios7选择照片 选择除了相机胶卷之外的相册最后一张会崩溃（比如选择照片流，最后一张图片来回选中取消选中取消，选中数字一直在叠加，返回时候导致崩溃）；求解决一下，别的几星不方便调试没有测试

另外，最后一张图片一直显示空白（相机胶卷之外的相册）。

**Comment by banchichen** [comment]
这么奇怪，可以帖一下一下崩溃的信息吗？我QQ：736420282，我想了解下详细的信息~ 加一下我~ 我这里测试了8和9是没有问题的

**Comment by banchichen** [comment]
4天过去了居然~  都修复咯~  还顺便修复个内存泄露，Demo界面的一个问题~
