### ISSUE TITLE
获取相册视频  返回nil 急！

### ISSUE THREAD

**Issue by yhq-iOS** [banchichen/TZImagePickerController#670]
求解答 万分感谢

**Comment by banchichen** [comment]
你好，是在哪个回调里哪个参数返回了nil呢...

**Comment by czhen09** [comment]
等待回调之后就不是nil了

**Comment by banchichen** [comment]
@czhen09 没看懂...

**Comment by yhq-iOS** [comment]
就是下面这个回调，根据返回的asset获取视频 获取不到
`[imagePickerVc setDidFinishPickingVideoHandle:^(UIImage *coverImage, id asset) {}];`

**Comment by yhq-iOS** [comment]
您说的是哪里会抛出错误呢  找了找 没有看到

**Comment by banchichen** [comment]
@yhq-iOS  你根据返回的asset获取视频，是通过这个方法吗：
    [[TZImageManager manager] getVideoOutputPathWithAsset:asset presetName:AVAssetExportPreset640x480 success:^(NSString *outputPath) {
        NSLog(@"视频导出到本地完成,沙盒路径为:%@",outputPath);
        // Export completed, send video here, send by outputPath or NSData
        // 导出完成，在这里写上传代码，通过路径或者通过NSData上传
    } failure:^(NSString *errorMessage, NSError *error) {
        NSLog(@"视频导出失败:%@,error:%@",errorMessage, error);
    }];
这个方法如果内部失败了，会抛出错误哈

**Comment by yhq-iOS** [comment]
@banchichen 非常感谢！ 之前没有用到您这个方法`getVideoOutputPathWithAsset `，我是直接使用的系统那个`requestAVAssetForVideo`， 我看您里面也是使用了这个方法`requestAVAssetForVideo`。虽然不知道为啥，但是目前看来是没问题了。非常感谢！

**Comment by yhq-iOS** [comment]
顺便问一句，使用AVCaptureSession录制视频或者拍照。我加了判断如果录制时间少于一秒，就是拍照。目前遇到一个问题，把手机平放在桌子上，点击拍照，获取的图片是nil，但是把手机从桌子上拿起来拍照，就不会有这个问题。您能帮忙分析下吗？

**Comment by banchichen** [comment]
@yhq-iOS OK，解决了就好。第二个问题不太清楚哈...
