### ISSUE TITLE
有Bug啊

### ISSUE THREAD

**Issue by liangjiawei19920721** [banchichen/TZImagePickerController#671]
用你的Demo，选项是
“显示内部拍照按钮” ->YES
"照片按修改时间升序排列"->NO
拍一张照，结果并不是这张照，而是相册里的第一张照片

**Comment by banchichen** [comment]
@liangjiawei19920721 你好，你手机是什么系统呢，Demo是最新的吗，我这iOS11.1拍照是正常的。

**Comment by liangjiawei19920721** [comment]
我简单看了下你的代码，我猜想出现bug的原因是你按date排序，假设新拍的照片就是第一张或者最后一张?
这个假设不一定成立的......你试下改系统时间拍一张照，这样新拍的照就会排在中间。结果就不对了，我改了你的代码，新拍的照片另外存起来就能解决这个bug。
