### ISSUE TITLE
预览页面的导航栏如何去除啊？

### ISSUE THREAD

**Issue by Abiu1314** [banchichen/TZImagePickerController#672]
如题，弄了一晚上都没去掉，iOS11系统 。

**Comment by Abiu1314** [comment]
好累啊，弄不了这个导航栏
<img width="393" alt="111 2x" src="https://user-images.githubusercontent.com/23489556/33726618-766e7134-dbb0-11e7-8de7-27a9fcad740a.png">

**Comment by Abiu1314** [comment]
附上==图床链接http://ww2.sinaimg.cn/large/0060lm7Tly1fm8om7olzej30lu14gh5y.jpg

**Comment by Abiu1314** [comment]
原来页面的导航栏通过纯色图片设置的，是这个原因么？我设置了纯色的，单预览页面还是有这个导航栏，代码已经隐藏导航栏了，不知道为什么还出现

**Comment by banchichen** [comment]
@Abiu1314 你好，参考这个issue： https://github.com/banchichen/TZImagePickerController/issues/652

**Comment by Abiu1314** [comment]
感谢大佬，解决了我多年的月经不调。昨晚折腾到大半夜
