### ISSUE TITLE
设置MaxImagesCount=1有bug     

### ISSUE THREAD

**Issue by 2360219637** [banchichen/TZImagePickerController#673]
用的最新版本，每张图片右上角没有选中按钮
<img width="431" alt="2017-12-08 11 20 05" src="https://user-images.githubusercontent.com/13285489/33749627-c375de32-dc09-11e7-8c41-d58e03196d3d.png">

**Comment by 2360219637** [comment]
大于等于2才会显示

**Comment by banchichen** [comment]
@2360219637 你好，单选模式下，如果也要现实选择按钮，需设置showSelectBtn为YES：
/// 单选模式,maxImagesCount为1时才生效
@property (nonatomic, assign) BOOL showSelectBtn;        ///< 在单选模式下，照片列表页中，显示选择按钮,默认为NO
