### ISSUE TITLE
Linker warning

### ISSUE THREAD

**Issue by whisper-bye** [banchichen/TZImagePickerController#674]
ld: warning: Linker asked to preserve internal global: 'AssetGridThumbnailSize'

**Comment by whisper-bye** [comment]
@banchichen 老兄你关掉了我的issue也得告诉我是个什么情况吧？

**Comment by banchichen** [comment]
@whisper-bye 因为没有解决计划...

**Comment by LeoAiolia** [comment]
![图片](https://user-images.githubusercontent.com/16910025/88797692-4e97d000-d1d6-11ea-8edd-d0566dd1bce3.png)

**Comment by LeoAiolia** [comment]
![图片](https://user-images.githubusercontent.com/16910025/88798221-25c40a80-d1d7-11ea-9e81-1d280a0a62df.png)

**Comment by LeoAiolia** [comment]
![图片](https://user-images.githubusercontent.com/16910025/88798247-32e0f980-d1d7-11ea-98ba-f0250bda68c7.png)
这么多库，只有你的有警告，好难受，解决下吧。
