### ISSUE TITLE
裁剪模式下，完成按钮被裁剪view遮挡住

### ISSUE THREAD

**Issue by CCBrother** [banchichen/TZImagePickerController#676]
裁剪模式下，完成按钮被裁剪view遮挡住，显示灰色，怎么修改？

**Comment by banchichen** [comment]
你好，修复代码已经提交了哈，会随着下版发布，commit信息：https://github.com/banchichen/TZImagePickerController/commit/24753b8db08984c2a345534ae5ea9c67e2ac7db3

**Comment by banchichen** [comment]
新版1.9.8版本已经发布了哈。
