### ISSUE TITLE
拍照问题

### ISSUE THREAD

**Issue by ZClee128** [banchichen/TZImagePickerController#677]
调起照相机拍照后，内存会疯涨，而且无法释放，是怎么回事

**Comment by banchichen** [comment]
@ZClee128 你好，疯涨是涨了多少呢？我这iPhone8，iOS11.1.2的设备，拍照11张，内存大概涨了11M。相册列表页的UIImagePickerController是懒加载的，拍照后这部分内存不会释放，但是选择器销毁后这个也会随着销毁的。
可以跑下Demo，用Xcode8+版本自带的Debug Memory Graph，看看项目的内存情况，是没有泄露和异常存活对象的。

**Comment by ZClee128** [comment]
因为你手机本身性能好，我们这边有两台测试机内存小性能不好，16g的
