### ISSUE TITLE
导航栏的那条线为什么没有了？

### ISSUE THREAD

**Issue by flyweights** [banchichen/TZImagePickerController#678]
我将navbar设置为白底黑字，导航栏的那条线为什么没有了？

**Comment by banchichen** [comment]
导航栏的分割线，我这里没操作过噢...你那里Demo正常吗？

**Comment by AllenDongCoder** [comment]
导航栏变纯白色的了

**Comment by flyweights** [comment]
@banchichen 我就单纯地直接修改了属性，一点都没有修改你的代码，我明天再把代码和效果截图发上来给你看看，谢谢🙏

**Comment by banchichen** [comment]
@flyweights 好的，放上来看看吧~

**Comment by zcw46229412** [comment]
怎么修改了 ？？？ 我的情况跟你一样

**Comment by zcw46229412** [comment]
@banchichen   确实出现了这个问题。我自己在viewWillAppear  里给了个颜色图片解决问题
  [self.navigationBar setShadowImage:[self createImageWithColor:Z_BGCOLOR]];

**Comment by banchichen** [comment]
@zcw46229412 你那里Demo正常吗？

**Comment by zcw46229412** [comment]
@banchichen demo 我这里跑不起来。。。。  还有一个问题是statusBarStyle 这个我设置了也不管用，我是白色nav，然后给的是白色的statusBar, 我只好在appledage里设置    [UIApplication sharedApplication].statusBarStyle = UIStatusBarStyleDefault;

**Comment by banchichen** [comment]
@zcw46229412 状态栏的颜色，可以这样设置：
```objectivec
/// 顶部statusBar 是否为系统默认的黑色，默认为NO
@property (nonatomic, assign) BOOL isStatusBarDefault;
```

加油把Demo跑起来不...理论上clone下来就可以跑咦...

**Comment by AllenDongCoder** [comment]
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:1 delegate:self];
imagePickerVc.navigationBar.backgroundColor = KBlueColor;
imagePickerVc.allowTakePicture =  NO;
 imagePickerVc.navigationItem.title = @"";

你改下 navigationBar的背景色就好了

**Comment by herobin22** [comment]
博主的代码中: self.navigationBar.barStyle = UIBarStyleBlack; 直接将barStyle设置了
当使用默认的bar,也就是UIBarStyleDefault时,bar有一条灰色的分割线, 而设置为UIBarStyleBlack就没有了, 也可以再通过self.navigationBar.shadowImage手动添加一条线

**Comment by hzhh110** [comment]
![snip20180118_10](https://user-images.githubusercontent.com/19906209/35101400-627de3ca-fc9a-11e7-9d9e-fd7ea87038f8.png)

**Comment by hzhh110** [comment]
导航栏不知道怎么回事,取消和返回啥的都看不到

**Comment by banchichen** [comment]
@hzhh110 是不是你们项目里，导航栏的颜色被全局设置成了白色。。
