### ISSUE TITLE
有内存泄漏啊，选完图片不会销毁

### ISSUE THREAD

**Issue by swsdyg** [banchichen/TZImagePickerController#68]
@banchichen 每次打开内存都会增加好多，选完图片之后内存不会下降，重写了一下dealloc方法，发现没有走，应该是有内存泄漏

**Comment by banchichen** [comment]
你好，这个问题是挺久之前了的吧？ 已经修复了的，试试新版吧~

**Comment by swsdyg** [comment]
@banchichen  你好，我刚下载了最新的，测试了一下还是不行，下面是我添加的dealloc方法，根本不会走，并且看内存确实是没次打开都会增加，并且除了添加了dealloc方法之外，其它的我没有进行任何修改，使用的您的下载下来的代码直接测试的，有空您也可以这样测试一下，谢谢
![d8bd5617-d34b-4ef7-a0a9-2121ace45397](https://cloud.githubusercontent.com/assets/8267484/15104660/538795f4-15ed-11e6-8645-353c0b6e9920.png)

**Comment by banchichen** [comment]
我刚刚试了一下，确实是的...最近加的新功能又引发了这个问题...谢谢指出，我看一下~

**Comment by banchichen** [comment]
你好，新版已经修复了~
