### ISSUE TITLE
图片裁剪的一个疏漏

### ISSUE THREAD

**Issue by Yoncn** [banchichen/TZImagePickerController#680]
当多选图片时，可以通过photoWidth来指定图片的裁剪宽度。

**Comment by Yoncn** [comment]
但是当单选图片，并选择了圆形裁剪框时，传入photoWidth再也无效了。因为用了[TZImageCropManager cropImageView]，根据圆形框裁剪了，但是并没有根据用户传入的photoWidth来再次指定输出图片的尺寸。这个比如上传图片时服务器需要，所以这点可能是产品流程上需要改进的吧

**Comment by ccqwert** [comment]
望楼主加入多张图片选中后依次剪裁功能

**Comment by SlowDony** [comment]
楼主我想问一下,如何做到就是选择圆形裁剪框后图片不裁剪成圆形,也就是只是展示成圆形框,但实际还是把图片裁成正方形,因为我看了一下,只要设置成圆形裁剪框后就默认把图片裁剪成圆形了,然后我又试了下设置needCircleCrop=NO,然后在cropViewSettingBlock把里面的cropView设置成圆形,这样虽然可以显示圆形并把图片剪切成正方形,但是由于needCircleCrop=NO,所以默认剪切框为正方形,就会显示一个正方形中间又加一个圆形框,也不是很好,请问这样的需求怎么处理

**Comment by SlowDony** [comment]
楼主我现在是这样处理的给TZImageCropManager写一个分类,然后用runtime把TZImageCropManager 类里的circularClipImage:方法进行修改,然后可以满足在选择圆形剪切框的同时并把图剪切成正方形,而不是切成圆图

**Comment by Yoncn** [comment]
> 楼主我想问一下,如何做到就是选择圆形裁剪框后图片不裁剪成圆形,也就是只是展示成圆形框,但实际还是把图片裁成正方形,因为我看了一下,只要设置成圆形裁剪框后就默认把图片裁剪成圆形了,然后我又试了下设置needCircleCrop=NO,然后在cropViewSettingBlock把里面的cropView设置成圆形,这样虽然可以显示圆形并把图片剪切成正方形,但是由于needCircleCrop=NO,所以默认剪切框为正方形,就会显示一个正方形中间又加一个圆形框,也不是很好,请问这样的需求怎么处理

可以同时拿到裁剪前的图片的
