### ISSUE TITLE
拍照按钮能不能设置放在第一个？拍照时能不能设置不用定位？

### ISSUE THREAD

**Issue by oshiwei** [banchichen/TZImagePickerController#684]

**Comment by banchichen** [comment]
你好，可以设置拍照按钮位置的：
/// 对照片排序，按修改时间升序，默认是YES。如果设置为NO,最新的照片会显示在最前面，内部的拍照按钮会排在第一个
@property (nonatomic, assign) BOOL sortAscendingByModificationDate;

不能设置不用定位，为什么有这个需求呢？
