### ISSUE TITLE
选择GIF 图片的时候 如何转NSDATA上传，

### ISSUE THREAD

**Issue by fanruoyang** [banchichen/TZImagePickerController#685]
拿到你的数据 ，也没法转NSDATA 啊，这个怎么做呢？

**Comment by CoderJWLu** [comment]
同问

**Comment by CoderJWLu** [comment]
拿到PHAsset对象,然后这样转.发现gif还是显示静态图.捉急
   [[PHCachingImageManager defaultManager] requestImageDataForAsset:asset options:nil resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
            NSLog(@"%@",dataUTI);
         
        }];

**Comment by banchichen** [comment]
@fanruoyang 你好，用`TZImageManager`的`- (void)getOriginalPhotoDataWithAsset:(id)asset completion:(void (^)(NSData *data,NSDictionary *info,BOOL isDegraded))completion;
`方法可以拿到图片的NSData。

**Comment by banchichen** [comment]
@CoderJWLu `PHCachingImageManager`是做缓存的，用上面提到的那个方法试试。
