### ISSUE TITLE
如果我gif备份到icloud,点击加载gif,显示是静态图.想问的是如何从iCloud拉取gif.demo好像忽略了这点

### ISSUE THREAD

**Issue by CoderJWLu** [banchichen/TZImagePickerController#687]

**Comment by banchichen** [comment]
你好，设置了allowPickingGif属性为YES吗？
如果设置了为YES，也是静态图的话，可能是gif图片数据损坏了。可以去微信的图片选择器里选择下试试，微信会提示此gif是静态的。
也可能是iCloud gif图没加载完成...

**Comment by CoderJWLu** [comment]
allowpickingGif设置了.我看了下微信是可以的.然后demo那边也试了 发现也是不行.

**Comment by banchichen** [comment]
@CoderJWLu 好吧，说明这个gif图片没下载完成.....

**Comment by banchichen** [comment]
好奇微信是怎么解决的，查了一些资料，很多讨论都指向系统bug，这个bug出现在这样的设备里：
1、打开了设置-照片里的iCloud图片图库开关
2、在设置-照片页里，选中了"优化iPhone储存空间"
这样的情况下，如果大gif或大图片、视频存储在iCloud里，用系统Photos库通过asset数据data的API会出错，没有返回data...
所以在这里导致了gif不能播放...
出现在iOS11+的设备里
iOS10.x貌似没问题

相关链接：
https://forums.developer.apple.com/thread/16244
https://stackoverflow.com/questions/28170444/photos-framework-requestimagedataforasset-occasionally-fails/28171024#28171024

**Comment by banchichen** [comment]
原来是我昨天测试机连了代理.........

关闭代理后测试没问题，顺便做了点优化，在gif图同步iCloud的时候加了进度条，体验会好些。

之前确实有gif在iCloud里不能播放的bug，后面是加了这句修复的：
```objectivec
        if ([[asset valueForKey:@"filename"] hasSuffix:@"GIF"]) {
            // if version isn't PHImageRequestOptionsVersionOriginal, the gif may cann't play
            option.version = PHImageRequestOptionsVersionOriginal;
        }
```

大家可以升级到2.1.7，如果gif不能播放且进度条没出来，检查下网络是否能通，看看getOriginalPhotoDataWithAsset里resultHandler的info里是否有报错信息。

**Comment by banchichen** [comment]
是的，我发现对于部分存在本地的gif，不加这一句读的会是静态图片。
可能是系统在保存gif图片的时候，对部分图片做了编辑处理，不加PHImageRequestOptionsVersionOriginal取的是系统编辑后的静态图...
