### ISSUE TITLE
ios11系统下选择原图，iCloud图片的大小始终为0M，不管选几张图都是一样。

### ISSUE THREAD

**Issue by xiaohuahao** [banchichen/TZImagePickerController#688]
ios11系统下真机测试，设置这个两个属性后 “imagePickerVc.isSelectOriginalPhoto = YES;
imagePickerVc.allowPickingOriginalPhoto = YES;”，得到的图片的大小始终为0M；把得到的图片转为NSData会出现nil的情况，NSData *data = UIImageJPEGRepresentation(img, 0.81);  data始终未nil。

网上找了一下原因，还是没有找到合适的解决办法，下面使用微信的方法，imageData却获取不到。
“对于IM的发送原图功能，iOS11启动全新的HEIC 格式的图片，iPhone7以上设备+iOS11排出的live照片是".heic"格式图片，同一张live格式的图片，iOS10发送就没问题（转成了jpg），iOS11就不行

微信的处理方式是一比一转化成 jpg 格式

QQ和钉钉的处理方式是直接压缩，即使是原图也压缩为非原图

最终采取的是微信的方案，使用以下代码转成jpg格式

// 0.83能保证压缩前后图片大小是一致的
// 造成不一致的原因是图片的bitmap一个是8位的，一个是16位的
imageData = UIImageJPEGRepresentation([UIImage imageWithData:imageData], 0.83);”

**Comment by banchichen** [comment]
你好，感谢指出，代码已经提交了：https://github.com/banchichen/TZImagePickerController/commit/e679fc77b226652e6522fb895729e01c6a0adab1

是因为图片存储在iCloud里，之前没有设置获取图片大小时允许访问网络。

会随着下版发布掉哈，预计是2.1.5版本
