### ISSUE TITLE
更新到最新版本（1.9.6）后 - 状态栏不见了

### ISSUE THREAD

**Issue by 90candy** [banchichen/TZImagePickerController#689]
选择图片完成 或者 取消选择 ，状态栏随之不见了
老版本一切正常，未动过代码

**Comment by RiberWang** [comment]
same to you.

**Comment by banchichen** [comment]
@90candy @RiberWang 好吧，应该是你们的项目里info.plist设置了Status bar is initially hidden为YES哈，我处理坏了...我修复一下...

**Comment by banchichen** [comment]
1.9.7版本发布了哈，修复了这个问题~
