### ISSUE TITLE
图片裁剪完成时，出现一个crash

### ISSUE THREAD

**Issue by Yoncn** [banchichen/TZImagePickerController#690]
![image](https://user-images.githubusercontent.com/16697649/34072585-d4a8c946-e2c4-11e7-9b23-dc8365cc0097.png)
![image](https://user-images.githubusercontent.com/16697649/34072589-e45a9400-e2c4-11e7-87e5-40123788b045.png)

**Comment by Yoncn** [comment]
没做nil判断。。。

**Comment by banchichen** [comment]
asset倒不可能是nil，那应该cropedImage是nil，上图中的代码看来是已经避免了，是你自己优化的咯？

出现这种情况的时候，有其它什么信息吗？

**Comment by banchichen** [comment]
可能和这个问题一样，看看这哈：https://github.com/banchichen/TZImagePickerController/issues/971
