### ISSUE TITLE
升级了最新1.9.8版本后，任然会出现左边返回按钮向下偏移大约20点左右的问题？

### ISSUE THREAD

**Issue by jerrywangjing** [banchichen/TZImagePickerController#692]
看到前面同学有关于此问题的issues，我也遇到了这个问题，并在源码中没有得到修复，自己尝试修复也没有效果，希望您能看看此问题，机型iphone6s，ios11 版本。如下图：
![image](https://user-images.githubusercontent.com/14274153/34144895-9f4c1c10-e4ce-11e7-9a55-ba6e98a0eaac.png)

**Comment by banchichen** [comment]
@jerrywangjing Hi，可以麻烦提供一个Demo吗，分享到百度云盘我来调试下看看..

**Comment by jerrywangjing** [comment]
公司项目，不方便提供，我通过自定义返回按钮的block，修改了一下btn的图片就可以了，也不知道是什么原因

**Comment by banchichen** [comment]
@jerrywangjing 好的👌

**Comment by banchichen** [comment]
原因在这里哈：https://github.com/banchichen/TZImagePickerController/issues/703
