### ISSUE TITLE
照片选择页面导航栏不显示标题。

### ISSUE THREAD

**Issue by Jonzzs** [banchichen/TZImagePickerController#694]
```
if (imagePickerVc.allowTakePicture) {
    self.navigationItem.title = [NSBundle tz_localizedStringForKey:@"Photos"];
} else if (imagePickerVc.allowPickingVideo) {
    self.navigationItem.title = [NSBundle tz_localizedStringForKey:@"Videos"];
}
```

源码中只判断了 `allowTakePicture` 和 `allowPickingVideo` 为 `YES` 的情况下才会显示标题，否则导航栏标题就是空的，希望能多一个设置导航栏标题的接口。

**Comment by banchichen** [comment]
@Jonzzs 你那里需要allowTakePicture和allowPickingVideo都设置为NO吗？这个是什么场景呢？

**Comment by muxiaodeng** [comment]
不能设置title么？如果我allowPickingVideo == YES，按back返回的时候，title显示videos,也是很诡异吧？

**Comment by banchichen** [comment]
@muxiaodeng 只选择视频时标题不设置为Videos/视频，你希望设置成什么？

**Comment by muxiaodeng** [comment]
判断条件是allowPickingVideo == YES，我允许用户选择视频，然后返回的时候，我看到的也是相册列表，并不是videos啊，如果你的title是videos那么至少说明这里都是videos，但是并不是啊，所以就是有点不合理。如果说的不对，望谅解；

**Comment by banchichen** [comment]
@muxiaodeng 设置标题的代码是：
```objectivec
if (imagePickerVc.allowTakePicture) {
    self.navigationItem.title = [NSBundle tz_localizedStringForKey:@"Photos"];
} else if (imagePickerVc.allowPickingVideo) {
    self.navigationItem.title = [NSBundle tz_localizedStringForKey:@"Videos"];
}
```
你可以打个断点看下，只有这两种标题。

你是用很旧的版本吗？
