### ISSUE TITLE
取不到bundle里面的资源

### ISSUE THREAD

**Issue by lx-xi** [banchichen/TZImagePickerController#697]
TZImagePickerController类154行tz_localizedStringForKey取值为空，导致如果未开通相册权限时程序崩溃；

**Comment by banchichen** [comment]
@lx-xi 你好，可以提供一个复现的Demo吗，我来调试下...

**Comment by lx-xi** [comment]
@banchichen 你好，问题是TZImagePickerController.bundle这个nsbundle找不到路径，返回空，但是我按照项目写了个结构一样的demo测试，这个bundle文件是可以访问到的，然而我项目里面访问不到

**Comment by banchichen** [comment]
@lx-xi 最快的解决办法是把源码拖进去哈，引入源码应该不会出现这个问题...

**Comment by banchichen** [comment]
@lx-xi 可以看看这issue哈：https://github.com/banchichen/TZImagePickerController/issues/604    里面的解决方案应该管用

**Comment by lx-xi** [comment]
@banchichen 我这比较特殊，是弄静态库，在库里面调用TZImagePickerController，这个又是在库外用cocoapods管理，现在我这比较蠢的办法就是把TZImagePickerController.bundle放到自己的资源文件里面来

**Comment by banchichen** [comment]
@lx-xi 好吧，原来是这样的场景...
