### ISSUE TITLE
1.0.7版本选择时报错

### ISSUE THREAD

**Issue by fuximin** [banchichen/TZImagePickerController#7]
在pod下

添加方法后运行出现如下错误

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle <xxx.app> (loaded)' with name 'TZAlbumCell''

报错地方

    TZAlbumCell *cell = [tableView dequeueReusableCellWithIdentifier:@"TZAlbumCell"];

猜测

检查了下nib的名字和imagepiccontroller  中引用的名字，没有错误，难道是其他问题引起的？

**Comment by hosven** [comment]
me too

**Comment by banchichen** [comment]
你好，抱歉最近特别忙，没怎么顾得上。。。你那里用的是什么版本呢？如果不是最新的话，请把TZImagePickerController升级一下，新版本应该没有这个问题的~  如果升级了后问题还在，请再来回复一下~

**Comment by banchichen** [comment]
你好，不好意思最近太忙了，才有空来看这里...新版本已经解决了这个问题~~~
