### ISSUE TITLE
内存暴涨问题

### ISSUE THREAD

**Issue by gfyangtao** [banchichen/TZImagePickerController#700]
相册图片每张10M，选择9张原图，模拟器内存最高值达到1G以上，请问有没有什么解决办法？
获取原图方法是用的这个 [[TZImageManager manager] getOriginalPhotoWithAsset:assets[i] completion:^(UIImage *photo,NSDictionary *info){}

**Comment by banchichen** [comment]
你好，参考这个issue：https://github.com/banchichen/TZImagePickerController/issues/520
