### ISSUE TITLE
math.h的头文件的导入

### ISSUE THREAD

**Issue by smilehappy05** [banchichen/TZImagePickerController#701]
math.h的头文件， 使用尖括号时用的就是系统里的，而使用双引号的话则会使用项目中自己写的那个，当我们的项目中之前已经写了一个叫做math.h的头文件，在导入这个TZImagePickerController框架后，math.h头文件会报错找不到，所以最好应该用尖括号导入吧

**Comment by banchichen** [comment]
好的~
代码已提，下次发版时带上~
https://github.com/banchichen/TZImagePickerController/commit/cf38326022c8b4febffa35a83dfd99bc2287f63b
