### ISSUE TITLE
iOS 11中导航栏返回键错位

### ISSUE THREAD

**Issue by Mayinwei** [banchichen/TZImagePickerController#703]
<img width="380" alt="qq20171222-164753 2x" src="https://user-images.githubusercontent.com/20430546/34291913-8d6f0ba2-e739-11e7-9158-bc1c82ecd888.png">

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/692

**Comment by banchichen** [comment]
另外，方便提供一个Demo吗？我来排查一下...

**Comment by Mayinwei** [comment]
我也是公司项目，不太方便，我先私底下调整一下，试试_

**Comment by Mayinwei** [comment]
链接: https://pan.baidu.com/s/1slG83It 密码: 7az3
这是出现问题的代码，我创建了一个项目，步骤就是，自定义导航栏，导航按钮，就会出现这个问题，麻烦您，调整一下，发版之后您通知我一下，感谢！！

**Comment by banchichen** [comment]
@Mayinwei 好的，感谢Demo，我来调一下

**Comment by banchichen** [comment]
@Mayinwei 你好，问题原因是你工程里的这句代码：
````
[[UIBarButtonItem appearance] setBackButtonTitlePositionAdjustment:UIOffsetMake(NSIntegerMin, NSIntegerMin) forBarMetrics:UIBarMetricsDefault]
````
好像这样的设置比较危险，有博客这样提到：[iOS 切换App会闪动的原因
](https://www.jianshu.com/p/77325910eea2)
如果要自定义该选择器返回按钮的样式，请参考Demo，打开这句设置哈：
````
    // 自定义导航栏上的返回按钮
    [imagePickerVc setNavLeftBarButtonSettingBlock:^(UIButton *leftButton){
        [leftButton setImage:[UIImage imageNamed:@"back"] forState:UIControlStateNormal];
        [leftButton setImageEdgeInsets:UIEdgeInsetsMake(0, -10, 0, 20)];
    }];
````
打开这句设置后就没问题了。
