### ISSUE TITLE
请求增加一个方法

### ISSUE THREAD

**Issue by YBYHunter** [banchichen/TZImagePickerController#705]
- (void)getVideoOutputPathWithAsset:(id)asset success:(void (^)(NSString *outputPath))success failure:(void (^)(NSString *errorMessage, NSError *error))failure;
这个方法请求时间会很长，希望增加：取消导出：的功能。

**Comment by banchichen** [comment]
你好，近期没有这个计划哈，建议你把这个方法的实现搬到你的项目中，视频导出时的`AVAssetExportSession`对象有一个`cancelExport`的API可以取消导出。
