### ISSUE TITLE
能否增加一个属性，相册只展示选择照片，视频，视频和照片都能选择

### ISSUE THREAD

**Issue by a2525a2009** [banchichen/TZImagePickerController#706]
能否增加一个属性，相册只展示选择照片，视频，视频和照片都能选择。
有时候要用户上传视频，但是拉起来选择器有很多图片，用户需求只展示相册所有的视频

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/34316686-d204bac6-e7d6-11e7-9cfb-62dcd8fe4519.png)
你好，参考Demo，只单独打开某个开关，就可以实现只展示照片或视频，两个都打开，则照片和视频都有。

**Comment by a2525a2009** [comment]
嗯，发完消息我也知道这个设置了😂




| |
罗欣
|
|
邮箱：a2525a2009@163.com
|

签名由 网易邮箱大师 定制

在2017年12月23日 11:47，谭真 写道：


你好，参考Demo，只单独打开某个开关，就可以实现只展示照片或视频，两个都打开，则照片和视频都有。
