### ISSUE TITLE
差评

### ISSUE THREAD

**Issue by laizhiVP** [banchichen/TZImagePickerController#708]
基础的使用方法描述不清楚

**Comment by banchichen** [comment]
好的，去使用别人的库吧。

**Comment by laizhiVP** [comment]
不，我就用你的




发自网易邮箱大师
在2017年12月26日 11:18，谭真 写道：

好的，去使用别人的库吧。

**Comment by banchichen** [comment]
@laizhiVP 把Demo页面的代码看懂就应该会用了...
