### ISSUE TITLE
有carthage 标识，但实际上并不支持carthage

### ISSUE THREAD

**Issue by EnderRule** [banchichen/TZImagePickerController#709]
使用carthage build 时有如下错误
Dependency "TZImagePickerController" has no shared framework schemes for any of the platforms: iOS

**Comment by EnderRule** [comment]
另外，希望能支持一下繁体^_^

**Comment by banchichen** [comment]
你好，carthage是1.9.8版本开始支持的，我这边倒build正常，要不你在Cartfile里指定下版本试试？
`github "banchichen/TZImagePickerController" "1.9.8"`

![image](https://user-images.githubusercontent.com/12755494/34353416-e04d1a40-ea62-11e7-93dc-e6d2af50c04d.png)

繁体的目前还没计划哈，欢迎提PR~

**Comment by EnderRule** [comment]
pr提了

**Comment by EnderRule** [comment]
carthage 的问题，我刚开始用的时候还是1.9.5版本、也是显示支持carthage。现在改指定1.9.8 确实可以build。

**Comment by banchichen** [comment]
赞，已merge👍
