### ISSUE TITLE
UINavigationController问题

### ISSUE THREAD

**Issue by arsonzhang** [banchichen/TZImagePickerController#71]
Navigation总是出现延迟效果，能不能在跳转之前就给它赋上UINavigationController？？我自己试着加上nav，但是会崩溃

**Comment by banchichen** [comment]
没太看懂是什么意思呢，TZImagePickerController是继承自UINavigationController的

**Comment by arsonzhang** [comment]
就是图片都出来了，nav还没变颜色，显得上面一条白色的，不到一秒钟颜色才能变为自己设置的颜色

**Comment by banchichen** [comment]
请问什么机型，什么系统呢？

**Comment by arsonzhang** [comment]
iPhone5和iPhone 6P，一个iOS7.0一个iOS8.3

**Comment by banchichen** [comment]
好吧....好奇怪....这种问题没碰到过...

**Comment by arsonzhang** [comment]
还有，NSArray<UIImage *> *photos像这种泛型xcode6打包是不可以的

**Comment by banchichen** [comment]
恩，是的...

**Comment by arsonzhang** [comment]
还有一个问题需要解决，就是当我只选择了8张，然后再进去选择还能选9张，按照逻辑应该只能选1张

**Comment by banchichen** [comment]
这个你可以直接设置maxImageCount的值哦。9 - _selectedPhotos.count 就行
