### ISSUE TITLE
导出的视频编码为mp42,在ios9的uiwebivew，还有pc浏览器不能直接播放，如果转成ISOM

### ISSUE THREAD

**Issue by xinheblue** [banchichen/TZImagePickerController#713]
如题，用导视频的接口导出视频，上传到七牛云一类的云端，发现部分ios 版本( IOS 9)不能播放，网页也不能播放。经MediaInfo查看发现编码是mp42，需要转成ISOM通用格式才能保证在各个平台播放

**Comment by banchichen** [comment]
@xinheblue 我后面看一下，你可以直接用asset上传，七牛有给这样的API

**Comment by xinheblue** [comment]
我的问题。。。html的video标签必须要有controls属性。如果没有，在部分IOS和安卓能播放，在部分IOS系统上面就播放不了 @banchichen

**Comment by xinheblue** [comment]
mp4v2封装的视频格式没有问题

**Comment by banchichen** [comment]
这样啊，好的👍
