### ISSUE TITLE
查看大图为什么要传assets 啊，好恶心人啊， 传nil 还会崩溃，怎么解决呢

### ISSUE THREAD

**Issue by Goallying** [banchichen/TZImagePickerController#716]
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithSelectedAssets:_assets selectedPhotos:_images index:idx];

**Comment by banchichen** [comment]
恩，目前还不支持网络图片...你可以先去改我源码...

**Comment by Goallying** [comment]
不是支持网络图片啊，在相册或者相机选择完了图片已经有了，只需要传入图片数组就可以直接用多好？？

**Comment by banchichen** [comment]
@Goallying 不好的，返回给你的图片放大起来看就模糊了，用asset就能很清晰地预览。你既然不需要支持网络图片，把asset保存一份就可以了，参考Demo。
