### ISSUE TITLE
TZAssetCell load有问题

### ISSUE THREAD

**Issue by CSX1991** [banchichen/TZImagePickerController#72]
UMLOG: error: session_id=680C2EF44163112DA104E3D8723E12A9, context=Could not load NIB in bundle: 'NSBundle </Users/zhaoyang/Library/Developer/CoreSimulator/Devices/A0AAB646-5A6F-4B51-BA47-161B7FA31035/data/Containers/Bundle/Application/E7A91D7C-B41A-4A2B-95F3-D0FA5E3FB128/carnetworking.app> (loaded)' with name 'TZAssetCell'

你好 ，我pod更新过了 1.0.0的版本 走这里必崩 查了TZAssetCell看着没啥问题啊
求解救

**Comment by banchichen** [comment]
现在是1.3.3版本啦，之前的有问题~

**Comment by banchichen** [comment]
更新到最新版吧~
