### ISSUE TITLE
是否会出Swift对应版本

### ISSUE THREAD

**Issue by KYangLei** [banchichen/TZImagePickerController#721]

**Comment by banchichen** [comment]
我觉得是个好想法，我让我哥弄一个...

现在启动...

**Comment by KYangLei** [comment]
期待中。

**Comment by hanl001** [comment]
你哥什么时候弄好呀，要不带上我呗

**Comment by banchichen** [comment]
出倒是出了，不是特别稳定...

https://github.com/tanhuang/TZImagePickerControllerSwift

@hanl001 你要来贡献下不~？
