### ISSUE TITLE
【体验优化】图片裁剪

### ISSUE THREAD

**Issue by xiaohuapunk** [banchichen/TZImagePickerController#723]
版本：1.9.8
1.从pick页面选择一个图片后跳转到预览裁剪页面会执行隐藏导航栏和状态栏，pick页面在隐藏的瞬间会看到导航栏位置下面白色背景，从预览页面返回pick页面，执行显示导航栏状态栏动画过度不自然；
2.裁剪页面布局应该有问题，顶部的返回所在的view高度设置貌似少了状态栏的高度；
3.图片放大后，拉到最下面的时候顶部已经超过裁剪框了；
下面是截图
![img_3287_markman](https://user-images.githubusercontent.com/9956517/34549868-0c1d3db8-f147-11e7-9ca0-22ead06aa2af.png)

**Comment by banchichen** [comment]
@xiaohuapunk 你好，你这个截图有点异常，在裁剪页面左上角应该只有一个返回图标，没有文字的。裁剪框上方有部分区域没盖住图片应该和这个有关系。

状态栏的事情下个版本优化下~

**Comment by xiaohuapunk** [comment]
@banchichen 多谢回复，果然如你所说，原来是因为使用了 `FDFullscreenPopGesture` 引起的，预览页面导航栏没有隐藏，两个解决方法：
1. 修改`TZImagePickerController`源码，使用 `FD`隐藏导航栏的方法；
2.修复 `FDFullscreenPopGesture`源码，屏蔽掉 `TZImagePickerController`相关ControllerView；
选择的是后者，因为 FD 也引起 了一些其他库的问题，如下图，如果有其他同学遇到这个问题可以参考一下
![image](https://user-images.githubusercontent.com/9956517/34595615-6b89f688-f214-11e7-955d-15be3c5ad565.png)

**Comment by oceanfive** [comment]
我也遇到了这个问题，不过我是这么处理的：

    // 设置竖屏下的裁剪尺寸， 4:3 比例
    CGFloat margin = 30.0f;
    CGFloat width = self.view.frame.size.width - 2 * margin;
    CGFloat height = width * 3.0 / 4.0f;
    CGFloat y = ([UIScreen mainScreen].bounds.size.height - height) / 2;
    imagePickerVc.cropRect = CGRectMake(margin, y, width, height);

y值需要根据屏幕高度来设置，如果根据 view 的高度设置，则会造成裁剪框和图片不能完全吻合，会留有一定的高度
CGFloat y = (self.view.frame.size.height - height) / 2;

我是把裁剪的y值根据屏幕高度来设置的
