### ISSUE TITLE
UIImagePickerController拍照后的图片进行剪切跳转动画出现不连贯

### ISSUE THREAD

**Issue by IPOSDai** [banchichen/TZImagePickerController#725]
就是在 我使用UIImagePickerController拍照后，在使用你这个图片裁剪。
[picker dismissViewControllerAnimated:NO completion:nil];
[self presentViewController:imagePicker animated:NO completion:nil];
主要是控制这里的animated, 不管怎么控制都会出现两个页面是先返回在进入下一个页面，这样的动画效果不是很好。如何实现拍照完成直接裁剪，然后裁剪完成直接让picker和TZImagePicker dismiss, 给别人的感觉就是我当我进入TZImagePicker的时候 picker这个页面已经被删除的，所以TZImagePicker dismiss就只有一个动画

**Comment by banchichen** [comment]
@IPOSDai 你可以试试拍照结束后不执行`[picker dismissViewControllerAnimated:NO completion:nil]`，直接让picker去push裁剪控制器，采集结束把picker再dismiss掉。

**Comment by IPOSDai** [comment]
这样做的话，我需要自定义返回按钮了

**Comment by IPOSDai** [comment]
并且navigationControllerpush到navigationController是不允许的
