### ISSUE TITLE
请问下怎么更换导航栏返回按钮的（左箭头）图片？

### ISSUE THREAD

**Issue by iOS-Kel** [banchichen/TZImagePickerController#728]
请问下怎么更换导航栏返回按钮的（左箭头）图片，我想换成我自己的图片。

**Comment by banchichen** [comment]
@iOS-Kel 参照Demo：
```objectivec
    // 自定义导航栏上的返回按钮
    [imagePickerVc setNavLeftBarButtonSettingBlock:^(UIButton *leftButton){
        [leftButton setImage:[UIImage imageNamed:@"back"] forState:UIControlStateNormal];
        [leftButton setImageEdgeInsets:UIEdgeInsetsMake(0, -10, 0, 20)];
    }];
```

**Comment by iOS-Kel** [comment]
谢谢你，我找到设置的地方了




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：754922492@qq.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年01月08日 22:07，谭真 写道： @iOS-Kel 参照Demo：
    // 自定义导航栏上的返回按钮
    [imagePickerVc setNavLeftBarButtonSettingBlock:^(UIButton *leftButton){
        [leftButton setImage:[UIImage imageNamed:@"back"] forState:UIControlStateNormal];
        [leftButton setImageEdgeInsets:UIEdgeInsetsMake(0, -10, 0, 20)];
    }];

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/banchichen/TZImagePickerController","title":"banchichen/TZImagePickerController","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/banchichen/TZImagePickerController"}},"updates":{"snippets":[{"icon":"PERSON","message":"@banchichen in #728: @iOS-Kel 参照Demo：\r\n```objectivec\r\n    // 自定义导航栏上的返回按钮\r\n    [imagePickerVc setNavLeftBarButtonSettingBlock:^(UIButton *leftButton){\r\n        [leftButton setImage:[UIImage imageNamed:@\"back\"] forState:UIControlStateNormal];\r\n        [leftButton setImageEdgeInsets:UIEdgeInsetsMake(0, -10, 0, 20)];\r\n    }];\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/banchichen/TZImagePickerController/issues/728#issuecomment-355975401"}}}
