### ISSUE TITLE
进入主界面一瞬间，有抖动现象

### ISSUE THREAD

**Issue by zhoupeiyu** [banchichen/TZImagePickerController#729]

**Comment by banchichen** [comment]
@zhoupeiyu 你好，你所使用的版本是多少呢？升级下版本试试，目前最新版1.9.8

**Comment by zhoupeiyu** [comment]
应该是你最新的，想添加选中图片有顺序标签，类似微信，发现刷新时候有抖动，以为原本没有，但是重新看了你的效果，发现原来就存在这个问题，不知道是不是图片大小计算的问题。

**Comment by banchichen** [comment]
@zhoupeiyu 不改我的Demo情况下有抖动吗？ 如果有的话麻烦录一个gif哈...

**Comment by zhoupeiyu** [comment]
重新看了，有抖动，拍摄的人物比较容易看出来，但是自己手机，有一些私人照片，不好发gif图

**Comment by zhoupeiyu** [comment]
我觉得挺好复现，你什么都不做，在你选中一张照片时候，在你block 回调刷新一下collectionView，现象很明显，应该是图片处理的有些问题
![snip20180112_1](https://user-images.githubusercontent.com/13362258/34865250-efea68e2-f7b2-11e7-8bb2-07415d27d5bf.png)

**Comment by zhoupeiyu** [comment]
想给你录屏，发现不仔细看效果看不出来

**Comment by banchichen** [comment]
@zhoupeiyu 你改了代码咯？
我的代码里，没有调`[strongSelf.collectionView reloadData];`....

**Comment by banchichen** [comment]
你在这里调`[strongSelf.collectionView reloadData]`，那每个cell会重新走`cellForItemAtIndexPath`方法，会重新根据asset获取图片并赋值。这样造成了抖动。

如果要修复，应该是要改一下TZAssetCell的`setModel:`，在里面判断下如果_model和model是同一个对象，就直接return。

**Comment by zhoupeiyu** [comment]
那句话是我加的，是让你看抖动现象。

**Comment by banchichen** [comment]
@zhoupeiyu 加了reloadData不处理TZAssetCell是会有抖动的。不加reloadData有抖动才是有问题...

**Comment by banchichen** [comment]
代码你应该都看了，点击事件里走的代码，没有操作imageView的。

**Comment by zhoupeiyu** [comment]
嗯嗯，我那样添加刷新，是为了让你看到那个抖动现象，刚从github上下载你的demo，然后在我手机运行，不改东西，也是抖动的，只是很轻微抖动，不容易看出来，所以，我添加那个刷新，就是想让你看一下抖动效果

**Comment by zhoupeiyu** [comment]
我这里录制了一个视频，不知道怎么发给你，一点没动你的代码，出来的效果

**Comment by banchichen** [comment]
@zhoupeiyu 麻烦发到tanzhenios@qq.com哈

**Comment by zhoupeiyu** [comment]
已发送，注意查收

**Comment by banchichen** [comment]
@zhoupeiyu 看到了...
你杀死微信，再打开，第一次进入图片选择器，也是这样的...

因为第一次会返回缩略图来显示，第二次才返回大图。如果缩略图和大图的返回时间间隔长了一些，就会出现你说的抖动。

**Comment by banchichen** [comment]
这是正常现象...
如果在拿到缩略图的时候强行不set，等到大图再set。看到的就不是抖动，而是先空白再有图...

**Comment by zhoupeiyu** [comment]
这个添加选中顺序功能，但是刷新选中照片时候，抖动现象改怎么解决，近期会有添加顺序的功能吗

**Comment by banchichen** [comment]
@zhoupeiyu 近期没有这个计划。该如何解决上面的回复里提到过了，去翻一下。。。

**Comment by FrankSwift** [comment]
大佬你好，你说：如果要修复，应该是要改一下TZAssetCell的setModel:，在里面判断下如果_model和model是同一个对象，就直接return。 cell是复用的，怎么才能判断_model和model是不是同一个对象呢？图片选中带数字的话，选中一个图片就要reloadData来改变每张图片的标识，这种情况下setModel:方法会被调用，就会出现抖动

**Comment by banchichen** [comment]
@FrankSwift 在cell的setModel里，看_model和传入的model是否是同一个

cell复用，model没复用是唯一的
