### ISSUE TITLE
5月14号新版本添加了预览TZPhotoPreviewController  dealloc方法 没走

### ISSUE THREAD

**Issue by hbxn740150254** [banchichen/TZImagePickerController#73]
5月14号新版本添加了预览TZPhotoPreviewController  dealloc方法 没走，频繁点击预览内存不减，可以达到700M，无上限，真机肯定崩，陈兄肯定哪里遗漏了，有时间看看哈，谢谢

**Comment by banchichen** [comment]
啊，又泄露了~   刚刚修复好了~  看最新的代码~  pod的我稍后也更新一下~
