### ISSUE TITLE
未知导航栏问题

### ISSUE THREAD

**Issue by hzhh110** [banchichen/TZImagePickerController#733]
![snip20180118_10](https://user-images.githubusercontent.com/19906209/35103174-1946d792-fca0-11e7-808e-9ea25ed7fb9a.png)

**Comment by banchichen** [comment]
@hzhh110 是不是你们项目里，导航栏的颜色被全局设置成了白色。。

**Comment by JpacheGitHub** [comment]
和你一样的问题, 全局搜[UINavigationBar appearance], 目测是不是被设置了个白色背景图片上去

**Comment by JpacheGitHub** [comment]
和你一样的问题, 全局搜[UINavigationBar appearance], 目测是不是被设置了个白色背景图片上去, 我的就是...
