### ISSUE TITLE
单图选择时，往返多次会导致返回按钮文字变化，请问是在哪里设置了吗

### ISSUE THREAD

**Issue by FlyerYe** [banchichen/TZImagePickerController#735]

**Comment by FlyerYe** [comment]
![8cff87be-25a6-4620-b384-39ac9e0ea67c](https://user-images.githubusercontent.com/15828484/35140127-110180be-fd31-11e7-81f4-1f4d98a7ead5.png)

**Comment by FlyerYe** [comment]
![2f39d7ab-5a08-4040-bfed-18de7f828bee](https://user-images.githubusercontent.com/15828484/35140217-6247bd4e-fd31-11e7-88bb-8c9461f74f65.png)

**Comment by banchichen** [comment]
@FlyerYe 是设置了navLeftBarButtonSettingBlock吗。。。
我看我的Demo里不会这样呀。。。
