### ISSUE TITLE
导出视频方法报错

### ISSUE THREAD

**Issue by sunzhongliangde** [banchichen/TZImagePickerController#737]
当选择多个视频时，使用这个方法
[TZImageManager manager] getVideoOutputPathWithAsset 到处视频，会报错无法存储，请重试存储，不知是什么原因？

**Comment by banchichen** [comment]
建议你自己排查下哈，看看这个错误是在哪个环节产生的，然后是不是有某个视频总报错，寻找更多的线索哈。。
