### ISSUE TITLE
审核被拒绝

### ISSUE THREAD

**Issue by Ssunnyy** [banchichen/TZImagePickerController#738]
![2018-01-24 11 25 05](https://user-images.githubusercontent.com/7019575/35313089-798f0496-00f9-11e8-8813-b1d411a89628.png)
![Uploading attachment-5124831009436426585Screenshot-0118-104429.png…]()

**Comment by banchichen** [comment]
@Ssunnyy 附件上传失败了，如邮件所说，修改info.plist中Privacy - Photo Library Usage Description的值，说明清楚访问相册的用途。
