### ISSUE TITLE
 isStatusBarDefault 在Swift 下面失效

### ISSUE THREAD

**Issue by CivelXu** [banchichen/TZImagePickerController#739]
Swift 下 设置了导航的背景色为白色, 然后设置 isStatusBarDefault 不起作用

**Comment by banchichen** [comment]
不是swift下失效，而是因为你们工程里设置的View controller-based status bar appearance为YES哈。

代码提交了：支持info.plist设置View controller-based status bar appearance为YES时的状态栏颜色设置：
https://github.com/banchichen/TZImagePickerController/commit/bdb5b4fe86e67d9481e8952918d23c134b1f6a23

随着下版发布~

**Comment by banchichen** [comment]
2.0.0版本发布了，升级一下哈

**Comment by CivelXu** [comment]
Thank you!
