### ISSUE TITLE
为什么 didFinishPickingPhotos 里面返回的 缩略图 photos 比 原图大 ？

### ISSUE THREAD

**Issue by xiaoruiling** [banchichen/TZImagePickerController#741]
当图片比较小时，
```
 - (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:
    (NSArray *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:
    (BOOL)isSelectOriginalPhoto {
       }
```
中返回的 photos 中的图片 用

`                NSData *photoData = UIImageJPEGRepresentation(photos[0], 1.0)`

 转化后的缩略图 **photoData** 比
```
[[TZImageManager manager] getOriginalPhotoDataWithAsset:assets[0] completion:^(NSData *origianlData, NSDictionary *info, BOOL isDegraded) {
}
```
中的到的 原图的  **origianlData** 大

**Comment by banchichen** [comment]
用`UIImageJPEGRepresentation`压缩图片，不是总能让图片二进制数据变小的...

https://www.cnblogs.com/lizilong/p/4720673.html
https://segmentfault.com/q/1010000000701850
