### ISSUE TITLE
在我自己的APP里第一次安装的时候,只显示当前屏幕的照片,其余的照片显示不出来,请问这个怎么解决

### ISSUE THREAD

**Issue by sunxiaoyi** [banchichen/TZImagePickerController#742]
![wechatimg98](https://user-images.githubusercontent.com/15356404/35387406-9c6ad21c-020a-11e8-866f-725460fcc09d.png)

**Comment by banchichen** [comment]
@sunxiaoyi 第一次只显示这4张图片，第二次启动就全显示吗？

**Comment by sunxiaoyi** [comment]
第二次是全的

**Comment by banchichen** [comment]
@sunxiaoyi 很奇怪...如果卸载重装再打开，能稳定复现这个bug吗？

**Comment by sunxiaoyi** [comment]
可以复现 我把TZPhotoPickerController.m中viewDidLayoutSubviews的这个方法中的[self.collectionView reloadData];注释掉就不会出现了

**Comment by banchichen** [comment]
viewDidLayoutSubviews方法会在横竖屏切换的时候也调，在这里需要刷新collectionView，如果不支持横竖屏的话，干掉是不会有影响的哈。

这样的问题倒还是第一次听到，如果注释掉`[self.collectionView reloadData]`就OK的话，说明在`viewDidLayoutSubviews`前`TZPhotoPickerController`的_models属性变化了。

麻烦你Debug下哈，定位下问题的真正原因...

**Comment by banchichen** [comment]
如果在你们APP里，任何设备都能复现这个问题的话，可以制作一个小Demo，我来调试下~

**Comment by sunxiaoyi** [comment]
好的 有时间我弄个演示上去~
