### ISSUE TITLE
视频预览页面，完成按钮出现不可点击问题

### ISSUE THREAD

**Issue by LeAustinHan** [banchichen/TZImagePickerController#743]
TZVideoPlayerController中的configMoviePlayer方法，里面先后有两个方法的block中设置了_doneButton.enabled属性。在第一个方法的block中设置按钮_doneButton.enabled = YES。第二个方法的block中的configBottomToolBar中有设置_doneButton.enabled = NO。实测会出现block出现先后顺序的问题。导致_doneButton按钮不可点击。希望尽快查看处理。

**Comment by banchichen** [comment]
感谢指出，这里没写好...

代码已经提交：https://github.com/banchichen/TZImagePickerController/commit/763c623484ba836f355f490982c9cbd4ca1a9a61

刚刚发布了2.0.0.2版本~
