### ISSUE TITLE
点击图片进入预览状态，滑动到gif格式图片会变成静态图

### ISSUE THREAD

**Issue by JmoVxia** [banchichen/TZImagePickerController#745]
点击图片，进入图片浏览，滑动的时候，如果是gif格式图片，会变成静态图，如果在这里选择了gif图片，不会走gif的回调，而是走普通图片的回调。还有能不能增加一个限制图片大小的属性，比如大于5Mb不能选择，弹出对应提示框。
![](https://user-images.githubusercontent.com/19339708/35430660-38b41350-02b4-11e8-9cd6-10436bc27081.gif)

**Comment by banchichen** [comment]
@JmoVxia 你好，请参考最新Demo。
设置这个属性为YES，图片预览页gif就可以动了。
```objectivec
/// Default is NO / 默认为NO，为YES时可以多选视频/gif图片，和照片共享最大可选张数maxImagesCount的限制
@property (nonatomic, assign) BOOL allowPickingMultipleVideo;
```

实现这个代理方法，来决定图片是否可选，可参考Demo的实现
```objectivec
// Decide asset show or not't
// 决定asset显示与否
- (BOOL)isAssetCanSelect:(id)asset;
```
