### ISSUE TITLE
循环引用

### ISSUE THREAD

**Issue by Danie1s** [banchichen/TZImagePickerController#747]
当没有打开相册权限的时候，会进入提示设置权限的界面，这时候如果按右上角的取消，从而退出这个界面，那么就会造成内存泄漏，应该是循环引用导致，估计是定时器没有销毁，请作者修改

这个问题我之前已经提过一次了，用的是最新版本中的demo

![img_0782](https://user-images.githubusercontent.com/19432029/35499871-35ed3a9a-050f-11e8-8577-490c770a2847.PNG)

**Comment by banchichen** [comment]
感谢指出，已修复：https://github.com/banchichen/TZImagePickerController/commit/9a2d80e6d41f12e3f945eccbfe335ffbfd3c6f5f ，发布了2.0.0.4版本。
