### ISSUE TITLE
进入相册，当不允许访问相册或者相册为空时，页面会loading，直到超时。

### ISSUE THREAD

**Issue by LeAustinHan** [banchichen/TZImagePickerController#748]
进入相册，当不允许访问相册或者相册为空时，页面会loading，直到超时。看看是不是可以优化一下，把loading尽快去掉。

**Comment by banchichen** [comment]
@LeAustinHan 感谢指出，已修复：https://github.com/banchichen/TZImagePickerController/commit/9a2d80e6d41f12e3f945eccbfe335ffbfd3c6f5f，发布了2.0.0.4版本。
