### ISSUE TITLE
GIF预览是静态图，GIF的NSData不能播放

### ISSUE THREAD

**Issue by nierongcheng** [banchichen/TZImagePickerController#749]
在我的项目中或在demo中运行，gif图片的预览都不能播放动画；

通过 [[TZImageManager manager] getOriginalPhotoDataWithAsset:obj completion:^(NSData *data, NSDictionary *info, BOOL isDegraded) 拿到的GIF的NSData也不能播放

TZImagePickerController 的参数如下：

        imagePickerVc.allowPickingGif = YES;
        imagePickerVc.allowPickingOriginalPhoto = NO;
        imagePickerVc.allowPickingVideo = NO;
        imagePickerVc.allowPickingMultipleVideo = YES;
        imagePickerVc.isSelectOriginalPhoto = NO;

**Comment by banchichen** [comment]
@nierongcheng 你好，你那边拿到NSData后，是怎么进行播放的呢？
我这里通过NSData播放是用的SDWebImage的方法，在`TZPhotoPreviewView`类的`setModel:`方法中，可以去Debug下看看哈
```objectivec
self.imageView.image = [UIImage sd_tz_animatedGIFWithData:data]
```
