### ISSUE TITLE
选择拍照，拍照后无反应

### ISSUE THREAD

**Issue by xhz0813** [banchichen/TZImagePickerController#751]
相机拍照后，使用照片，不执行- (void)imagePickerController:(UIImagePickerController*)picker didFinishPickingMediaWithInfo:(NSDictionary *)info代理方法
修改办法，将代理设置在presentViewController中
[self presentViewController:_imagePickerVc animated:YES completion:^{
            _imagePickerVc.delegate = self;
        }];

**Comment by banchichen** [comment]
@xhz0813 TZImagePickerController没有对外设置有拍照成功的代理方法...`imagePickerController: didFinishPickingMediaWithInfo:`在Demo里只是演示在选择器外拍照的...

在选择器内部拍照，拍完后如果照片已选数量小于最大可选数量会自动选中，但不会通知代理，点击完成按钮后才会走代理方法...
