### ISSUE TITLE
DEMO关闭按时间排序后，所有的album列表点进去都是获取所有图片，并没有获取对应album类型下的assert

### ISSUE THREAD

**Issue by ericyao11** [banchichen/TZImagePickerController#754]
在TZPhotoPickerController中获取assert的判断逻辑

        _**# if (!tzImagePickerVc.sortAscendingByModificationDate && _isFirstAppear && iOS8Later) {**_

            [[TZImageManager manager] getCameraRollAlbum:tzImagePickerVc.allowPickingVideo allowPickingImage:tzImagePickerVc.allowPickingImage needFetchAssets:YES completion:^(TZAlbumModel *model) {
                _model = model;
                _models = [NSMutableArray arrayWithArray:_model.models];
                [self initSubviews];
            }];
        } else {
            if (_showTakePhotoBtn || !iOS8Later || _isFirstAppear) {
                [[TZImageManager manager] getAssetsFromFetchResult:_model.result completion:^(NSArray<TZAssetModel *> *models) {
                    _models = [NSMutableArray arrayWithArray:models];
                    [self initSubviews];
                }];
            } else {
                _models = [NSMutableArray arrayWithArray:_model.models];
                [self initSubviews];
            }
        }

TZPhotoPickerController的isFirstAppear 在viewDidLoad中置为YES，而TZImagePickerController保存的_isFirstAppear变量在进入TZPhotoPickerController的时候并没有赋值给它，导致了tzImagePickerVc.sortAscendingByModificationDate = NO的时候始终取getCameraRollAlbum的assert。

我的解决方案：
1.TZPhotoPickerController 在viewDidLoad self.isFirstAppear = YES 不设置为YES
2.在跳转TZPhotoPickerController时，把TZImagePickerController保存的isFirstAppear赋值给TZPhotoPickerController
这样可以解决上面我提出的问题。
请问下作者，我的方案可行吗？

**Comment by banchichen** [comment]
Hi，确实有这个问题哈，我回想了下当时的逻辑，是设置sortAscendingByModificationDate=NO的时候，第一次进入所有照片页面，排序可能不准，所以重新拿了相册model。前几天做优化时没注意到这里所以...

代码已经提交了哈：https://github.com/banchichen/TZImagePickerController/commit/eea9c162661020b90ced50428c7bcf05a066c399  判断条件了多来一个&&就行，随后我发一个版本~

**Comment by banchichen** [comment]
2.0.0.5版本发布了哈
