### ISSUE TITLE
设置sortAscendingByModificationDate为NO，所有相册点进去都显示全部照片了

### ISSUE THREAD

**Issue by nyz110** [banchichen/TZImagePickerController#755]
sortAscendingByModificationDate 设置NO，点击返回相册列表页面，选择任意一个相册，进去看到的图片是全部的图片不是当前相册的图片

**Comment by banchichen** [comment]
Hi，跟上一个issue是一样的哈：
https://github.com/banchichen/TZImagePickerController/issues/754
