### ISSUE TITLE
拍照完成后我进行图片剪裁，导致状态栏不见了是什么情况

### ISSUE THREAD

**Issue by IPOSDai** [banchichen/TZImagePickerController#756]
当我拍照完成后，dismiss 没有使用动画，然后present (也没有用动画)出来一个裁剪的，完成后导致状态栏消失了

**Comment by banchichen** [comment]
@IPOSDai 是把拍照按钮放在外面吗？是用的什么版本的？Demo有问题吗？

**Comment by banchichen** [comment]
https://github.com/banchichen/TZImagePickerController/issues/763
