### ISSUE TITLE
审核问题

### ISSUE THREAD

**Issue by zx1050336132** [banchichen/TZImagePickerController#760]
加了权限信息还是审核失败
Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage

We noticed that your app requests the user’s consent to access their photo but does not clarify the use of this feature in the permission modal alert.

Please see attached screenshots for details.
![attachment-5795789404526547064screenshot-0205-154940](https://user-images.githubusercontent.com/6093400/35907732-c1428066-0c29-11e8-8914-2c248994b710.png)

**Comment by banchichen** [comment]
苹果的意思是"程序需要上传照片，是否允许打开相册"没有说清楚访问相册的用途，希望你把用途描述清楚。

建议直接搬微信、QQ、支付宝等大APP的文案。

如果还是被拒，打苹果电话吧。。。
