### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by OrageKK** [banchichen/TZImagePickerController#762]
相册选择页，预览界面右上角不打勾，完成按钮可以点击，点击完成会直接选中图片。
个人认为，不打勾完成不应该能够点击

**Comment by banchichen** [comment]
这个是学习的微信的逻辑的，感觉挺好的...

**Comment by OrageKK** [comment]
恩，我后来发现微信也是这样。不过你缺少微信点击完成之后选中右上角对勾的动画。加油




| |
oragekk
邮箱：oragekk@163.com
|

签名由 网易邮箱大师 定制

在2018年02月08日 22:15，谭真 写道：

Closed #762.
