### ISSUE TITLE
你好,请教一下,关于选择了单张图片之后状态栏突然不见的问题

### ISSUE THREAD

**Issue by jniosdeveloper** [banchichen/TZImagePickerController#763]
你好,我在使用你的这个三方库的时候,设置maxCount为1,然后点击确定之后,我控制器的状态栏没了,请问这个是什么原因呢?

**Comment by banchichen** [comment]
@jniosdeveloper 是用的什么版本呢，Demo有问题吗？

**Comment by jniosdeveloper** [comment]
用的2.0.0.5,我找不到出现这个现象的原因,知道后来我直接在你的源码中的TZPhotoPreviewController.m的prefersStatusBarHiddlen方法中把return改为NO就行了,我之前用你的TZImage选择图片都没有,这次却发现这个现象,不知道是不是因为我是改的别人的老项目,里面做了什么操作?但是我检查了很久代码都没找到什么地方有设置状态栏,只有在你的库中发现有几个地方,所以才在你的源码中去改了一下,请教一下是不是因为你代码中在预览VC中点击dismiss之后没有把状态栏显示出来呢?

**Comment by banchichen** [comment]
@jniosdeveloper 如果是从预览页回到照片选择页的话，照片选择页实现了`prefersStatusBarHidden`且返回了NO，状态栏应该显示出来。你出现这个问题，是不是从预览页直接回到了你们的页面？这样的话需要你们的页面像Demo里的`ViewController`一样，实现下`prefersStatusBarHidden`：
```objectivec
- (BOOL)prefersStatusBarHidden {
    return NO;
}
```
