### ISSUE TITLE
how to add new language?

### ISSUE THREAD

**Issue by balkarov** [banchichen/TZImagePickerController#764]
If I installed lib via cocoapods, how to add new Language?

**Comment by banchichen** [comment]
You can set `languageBundle` before present `TZImagePickerController` instance.

`languageBundle` is the property of `TZImagePickerConfig` Class. 
By default，the value of `languageBundle` decide on `preferredLanguage`, the code is：
```objectivec
- (void)setPreferredLanguage:(NSString *)preferredLanguage {
    _preferredLanguage = preferredLanguage;
    
    if (!preferredLanguage || !preferredLanguage.length) {
        preferredLanguage = [NSLocale preferredLanguages].firstObject;
    }
    if ([preferredLanguage rangeOfString:@"zh-Hans"].location != NSNotFound) {
        preferredLanguage = @"zh-Hans";
    } else if ([preferredLanguage rangeOfString:@"zh-Hant"].location != NSNotFound) {
        preferredLanguage = @"zh-Hant";
    } else if ([preferredLanguage rangeOfString:@"vi"].location != NSNotFound) {
        preferredLanguage = @"vi";
    } else {
        preferredLanguage = @"en";
    }
    _languageBundle = [NSBundle bundleWithPath:[[NSBundle tz_imagePickerBundle] pathForResource:preferredLanguage ofType:@"lproj"]];
}
```

You also can hook `setPreferredLanguage` method to add new language.

Welcome to open a pull request to add new language bundle!

**Comment by balkarov** [comment]
Ok, I will set it. But lib get language from imagePickerBundle. But how to add language to there?

**Comment by balkarov** [comment]
And after lib check only zh, vl and en. 
But how it will be get “ru”? 
Could you send example?

**Comment by banchichen** [comment]
@balkarov Hi，the demo had add a example to use new language：
```objectivec
// 设置languageBundle以使用其它语言 / Set languageBundle to use other languageimagePickerVc.languageBundle = [NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:@"tz-ru" ofType:@"lproj"]];
```
the localized string in `tz-ru.lproj` is just for example, you need finish it before use.

By setting languageBundle, you can use other language not in imagePickerBundle.

**Comment by banchichen** [comment]
And you need use `TZImagePickerController` 2.0.0.6+

**Comment by banchichen** [comment]
When you finish the `ru.lproj`, welcome to open a pull request to add it to `TZImagePickerController `!
