### ISSUE TITLE
系统时间更改后，拍摄后，选择的照片不是最新拍摄的照片

### ISSUE THREAD

**Issue by fanfanqy** [banchichen/TZImagePickerController#768]
我们项目中有一个需求，测试人员把手机系统时间设置为未来的时间，然后拍照或者截图，图库增加一个照片，然后再设置为正常时间，拍照，这个时候assetModel =  [models lastObject] 为系统时间为未来时间拍摄的照片，不是刚刚拍照的照片

- (void)reloadPhotoArray{
...
if (tzImagePickerVc.sortAscendingByModificationDate) {
                assetModel = [models lastObject];
                [_models addObject:assetModel];
            } else {
                assetModel = [models firstObject];
                [_models insertObject:assetModel atIndex:0];
            }
...
}

**Comment by fanfanqy** [comment]
我们暂时的解决方案：照片的存储的assetid传回来生成asset，然后从_models 找对应的assetModel，成功后向_models 添加拍照的图片assetModel，再根据时间排序

PHAsset *assetHunt = [PHAsset fetchAssetsWithLocalIdentifiers:@[assetId] options:nil].firstObject;
if (tzImagePickerVc.sortAscendingByModificationDate) {
                
                /**
                 测试人员把手机系统时间设置为未来的时间，然后拍照或者截图，图库增加一个照片，然后再设置为正常时间，拍照，这个时候assetModel = [models lastObject] 为系统时间为未来时间拍摄的照片，不是刚刚拍照的照片,修改代码
                 */
//                assetModel = [models lastObject];
                
                for (TZAssetModel *model in models) {
                    if ([(PHAsset *)model.asset isEqual:assetHunt]) {
                        assetModel = model;
                        break;
                    }
                }
                
                [_models addObject:assetModel];
            } else {
                
//                assetModel = [models firstObject];
                
                for (TZAssetModel *model in models) {
                    if ([(PHAsset *)model.asset isEqual:assetHunt]) {
                        assetModel = model;
                        break;
                    }
                }
                [_models insertObject:assetModel atIndex:0];
            }
            
            //根据时间排序
            for (int i = 0; i < _models.count; i++) {
                for (int j = i + 1; j < _models.count; j++) {
        
                    TZAssetModel * model1 = [_models objectAtIndex:i];
                    TZAssetModel * model2 = [_models objectAtIndex:j];
                    PHAsset *asset1 = (PHAsset *)model1.asset;
                    PHAsset *asset2 = (PHAsset *)model2.asset;
                    
                    NSDate * time1 = asset1.modificationDate;
                    NSDate * time2 = asset2.modificationDate;
                    
                    if (tzImagePickerVc.sortAscendingByModificationDate){
                        if ([time1 timeIntervalSinceDate:time2] > 0.0) {
                            [_models exchangeObjectAtIndex:i withObjectAtIndex:j];
                        }
                    }else{
                        if ([time1 timeIntervalSinceDate:time2] < 0.0) {
                            [_models exchangeObjectAtIndex:i withObjectAtIndex:j];
                        }
                    }
                    
                }
            }

**Comment by Iwiii** [comment]
我也偶发了一个这种问题在一个测试机上.拍摄照片给我返回了相册中的第一张图片而不是拍摄后的照片

**Comment by Iwiii** [comment]
看了下源码 这里确实有问题

**Comment by banchichen** [comment]
Hi，新版3.0.2已修复。

保存的时候可以拿到一个localIdentifier，保存完成后可以直接用localIdentifier去取之前保存的照片。

做一次排序性能不太好，建议更新哈。
