### ISSUE TITLE
iOS  8.4系统下拍照照片不保存，拍照完后也会默认选取上一张图片

### ISSUE THREAD

**Issue by w609720426** [banchichen/TZImagePickerController#77]

**Comment by banchichen** [comment]
你好~已经解决了，这个是系统Photos库埋的坑。在iOS8的时候，Photos库提供的保存图片的方法回调中返回了成功，但是图片并没有成功保存。iOS67和9没问题的。所以，解决方案是：在TZImageManager的savePhotoWithImage:completion:方法里，把第一个if判断的条件iOS8Later，改成iOS9Later，让iOS8系统里的保存图片方法，走AssetsLibrary库，不走Photos库。代码我稍后提交上来...

**Comment by w609720426** [comment]
哈哈！你这个图片选择框架很好用！我就知道是那两个库的问题

**Comment by banchichen** [comment]
恩~  原来是你~  哈哈

**Comment by w609720426** [comment]
为什么叫 原来是我？？

**Comment by banchichen** [comment]
咦，简书里也有一个人说 猜是那两个库的问题....   和你的提问时间差不多....  哈哈

**Comment by w609720426** [comment]
我不会告诉你那个也是我，我好像在cocoaChina上也说了！

**Comment by banchichen** [comment]
那就是你咯~  我就是这样猜的~
