### ISSUE TITLE
选完图片点击完成按钮后 代理方法会在dismiss 后执行 ,如果代理方法涉及到UI的改变,就会有明显卡顿(UI突兀改变)

### ISSUE THREAD

**Issue by Iwiii** [banchichen/TZImagePickerController#771]
我改成这样就ok 看看是否有问题
- (void)didGetAllPhotos:(NSArray *)photos assets:(NSArray *)assets infoArr:(NSArray *)infoArr {
    TZImagePickerController *tzImagePickerVc = (TZImagePickerController *)self.navigationController;
    [tzImagePickerVc hideProgressHUD];
    [self callDelegateMethodWithPhotos:photos assets:assets infoArr:infoArr];
    if (tzImagePickerVc.autoDismiss) {
        [self.navigationController dismissViewControllerAnimated:YES completion:^{
           
        }];
    }
}

**Comment by banchichen** [comment]
你这样改也可以的，把代理方法的调用提前了，代理方法里刷新UI的操作和dismiss动画一起执行，动画结束前UI刷新一般都结束了，所以看不到刷新UI的过程。

Demo里的效果是dismiss结束后调代理方法，会有UI变化的过程，不是卡顿。

你也可以不改动库代码，设置autoDismiss为NO，自己在代理方法里dismiss一下即可。
