### ISSUE TITLE
如何删除选中的图片呢？

### ISSUE THREAD

**Issue by mrhyh** [banchichen/TZImagePickerController#772]

**Comment by banchichen** [comment]
可以参考下Demo界面，库本身不提供已选图片编辑界面：
![image](https://user-images.githubusercontent.com/12755494/36841597-c50aa2b2-1d83-11e8-90d5-27f7611ca46a.png)

**Comment by mrhyh** [comment]
不是这个删除，是把图片从相册移除

**Comment by banchichen** [comment]
@mrhyh 这个库没有删除相册照片的功能，需要你自己写。可以参考我的写法，我用`PHAssetChangeRequest`来创建新照片，也可以用`PHAssetChangeRequest`来删除照片。

**Comment by mrhyh** [comment]
好的
