### ISSUE TITLE
图片压缩的问题

### ISSUE THREAD

**Issue by Ze8898** [banchichen/TZImagePickerController#773]
能否手动设置压缩质量? 现在基本上都是压缩到20K以下 感觉质量非常低

**Comment by banchichen** [comment]
@Ze8898 20K这个值你是怎么拿到的呢？我返回的是UIImage和PHAsset，UIImage是默认是828像素宽的缩率图，通过PHAsset可以获取其它尺寸的图。如果原图是2M的话，UIImage用`UIImageJPEGRepresentation`压缩`compressionQuality`为0.9时，大小一般是100-200K。
