### ISSUE TITLE
调用TZPhotoPreviewController奔溃

### ISSUE THREAD

**Issue by FrankChung1121** [banchichen/TZImagePickerController#775]
大神你好,我在选择完图片以后,点击完成后,回到我自己的发布界面并且也能获取图片,但是当我想在自己的发布界面点击图片的缩略图,然后创建TZPhotoPreviewController,并且传入了所有图片photos和当前点击的图片currentIndex,然后model控制器就奔溃了,请问TZPhotoPreviewController类,是不是除了传递上面两个参数外,还需要传递其它参数或者是设置吗?我的代码如下:
TZPhotoPreviewController *photoPreviewVc = [[TZPhotoPreviewController alloc] init];
    photoPreviewVc.photos = self.selectedPhotos;
    UIImageView *imageView = (UIImageView *)[gesture view];
    photoPreviewVc.currentIndex = imageView.tag;
    [self presentViewController:photoPreviewVc animated:YES completion:nil];

**Comment by banchichen** [comment]
预览需要用`TZImagePickerController`的这个初始化方法：
```objectivec
/// This init method just for previewing photos / 用这个初始化方法以预览图片
- (instancetype)initWithSelectedAssets:(NSMutableArray *)selectedAssets selectedPhotos:(NSMutableArray *)selectedPhotos index:(NSInteger)index;
```
需要传入asset数组，目前不支持只传UIImage或URL
