### ISSUE TITLE
下载在XCode中无法运行，报错

### ISSUE THREAD

**Issue by CJHCAi** [banchichen/TZImagePickerController#776]
Code Signing Error: No account for team "T86X98NCU2". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "T86X98NCU2" with a private key was found.

**Comment by banchichen** [comment]
再试一下：
- 去除代码签名：https://github.com/banchichen/TZImagePickerController/commit/60458234d3e4114ad2c9e7585d6181e3d028ad02
