### ISSUE TITLE
选择照片个数过多会crash

### ISSUE THREAD

**Issue by SLPowerCoder** [banchichen/TZImagePickerController#783]
选择照片个数过多会crash

**Comment by banchichen** [comment]
@SLPowerCoder Hi，把crash日志贴一下哈，再说一下版本，说了多少张图，当时的内存情况...

**Comment by lishaSunny** [comment]
设置的只能选择3张,选了4张后crash,版本2.1.0
 Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'

**Comment by banchichen** [comment]
@lishaSunny 设置了只能选3张，也可以选出来4张吗？你这个崩溃情况下的堆栈贴一下哈，现在不好判断是在哪个环节崩溃的。
