### ISSUE TITLE
循环获取原图会导致内存过高crash

### ISSUE THREAD

**Issue by MrDZ** [banchichen/TZImagePickerController#789]
for (int i = 0; i<assets.count; i++) {
                    UIImage *photo = photos[i];
                    PHAsset *asset = assets[i];
                    UPImageUploader *uploader = [UPImageUploader imageWithPickerimage:photo asset:asset];
                    if (uploader) {
                        BorrowData *data = _borrowDataArry[_indexpath.section - 2];
                        NSMutableArray *photos = data.photos;
                        
                        [photos addObject:uploader];
                    }
                }

+ (instancetype)imageWithPickerInfo:(NSDictionary *)info sourceType:(UIImagePickerControllerSourceType)sourceType
{
    
    UPImageUploader *uploader = [[UPImageUploader alloc] init];
    uploader.image = [info objectForKey:UIImagePickerControllerOriginalImage];
    uploader.uploadStatus = UPImageStatusUploading;
   
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        
            [[HProtocol share] uploadImageWith:uploader.image withUnique:[[DefaultManager getInstance] getRandomString] progress:^(NSProgress * _Nonnull uploadProgress) {
                
            } success:^(NSURLSessionDataTask * _Nonnull sessionDataTask, id  _Nullable responseObject) {
                NSDictionary *dict = [BDGWUtils JSONObjectWithData:responseObject error:nil];
                HLog(@"UPLOAD : %@",dict.description);
                if ([APIKit succeed:dict]) {
                    uploader.uploadStatus = UPImageStatusFinished;
                    uploader.iconUrl =  dict[@"iconUrl"];
                }
                else
                {
                    uploader.uploadStatus = UPImageStatusFailed;
                }
                
            } failure:^(NSURLSessionDataTask * _Nullable sessionDataTask, NSError * _Nonnull error) {
                uploader.uploadStatus = UPImageStatusFailed;
            }];
       

    });
    
    return uploader;
}

+ (nullable instancetype)imageWithPickerimage:(nullable UIImage *)image asset:(nullable PHAsset *)asset
{
    UPImageUploader *uploader = [[UPImageUploader alloc] init];
//    uploader.image = image;

    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        
        [[TZImageManager manager] getOriginalPhotoWithAsset:asset completion:^(UIImage *photo, NSDictionary *info) {
            if ([info[PHImageResultIsDegradedKey] boolValue]!=YES) {
                [[HProtocol share] uploadImageWith:photo withUnique:[[DefaultManager getInstance] getRandomString] progress:^(NSProgress * _Nonnull uploadProgress) {
                    
                } success:^(NSURLSessionDataTask * _Nonnull sessionDataTask, id  _Nullable responseObject) {
                    NSDictionary *dict = [BDGWUtils JSONObjectWithData:responseObject error:nil];
                    HLog(@"UPLOAD : %@",dict.description);
                    if ([APIKit succeed:dict]) {
                        uploader.uploadStatus = UPImageStatusFinished;
                        uploader.iconUrl =  dict[@"iconUrl"];
                    }
                    else
                    {
                        uploader.uploadStatus = UPImageStatusFailed;
                    }
                    
                } failure:^(NSURLSessionDataTask * _Nullable sessionDataTask, NSError * _Nonnull error) {
                    uploader.uploadStatus = UPImageStatusFailed;
                }];
            }
            
        }];

    });

    return uploader;
}
能帮忙看看是什么原因么？

**Comment by banchichen** [comment]
获取原图时会得到一个超大的UIImage对象，比较占用内存，建议一个一个获取，不要一起来...

也可以试试`TZImageManager `的`requestImageDataForAsset`方法，拿到NSData去上传
