### ISSUE TITLE
把拍照放在前面

### ISSUE THREAD

**Issue by ryzur-martin** [banchichen/TZImagePickerController#79]
看了很多类似的实现，拍照功能都是放在第一个，然后照片的顺序从上边开始排列。现在是反着的，是不是改成这样更符合用户习惯？

**Comment by banchichen** [comment]
微博的照片选择器确实是那种方式。不过照片的顺序我是完全参考微信做的（QQ、QQ空间也是这样），拍照功能的放置是按照QQ空间的规则放置的...   没有更多考虑，没有采用微博的方式...  你需要微博的那种方式，可以试着改我的代码~
