### ISSUE TITLE
可以加上浏览网络图片吗

### ISSUE THREAD

**Issue by LittleCuteCat** [banchichen/TZImagePickerController#791]
目前貌似只能对本地相册操作，能不能浏览网络图片呢？从外界传入图片地址数组就行的那种？

**Comment by ouhuiju** [comment]
我也有这个需求,同求

**Comment by guyuliunian** [comment]
可以试试MWPhotoBrowser

**Comment by AAChartModel** [comment]
MWPhotoBrowser作者已经放弃维护很久了,虽然星星多的上天!

**Comment by banchichen** [comment]
@LittleCuteCat @ouhuiju @AAChartModel 

Hi，3.0.1版本已支持，需新接一个插件库：[TZImagePreviewController](https://github.com/banchichen/TZImagePreviewController)，请参考TZImagePreviewController里面的Demo使用。

抱歉久等了...

**Comment by Lucifer0103** [comment]
> @littlecutecat @ouhuiju @AAChartModel
> 
> Hi，3.0.1版本已支持，需新接一个插件库：[TZImagePreviewController](https://github.com/banchichen/TZImagePreviewController)，请参考TZImagePreviewController里面的Demo使用。
> 
> 抱歉久等了...

TZImagePreviewController不太满足, 是不是可以在TZImagePickerController设置几个属性, 传入 imageUrlArr, 使用的界面与加载本地的一样?

**Comment by banchichen** [comment]
@Lucifer0103 不太满足的地方是？使用TZImagePickerController改造有点大...
