### ISSUE TITLE
iPhoneX的适配问题？，预览图片的“完成”按钮，不知道为什么高度变长了，导致位置偏移了

### ISSUE THREAD

**Issue by flyweights** [banchichen/TZImagePickerController#792]
![wx20180323-164336](https://user-images.githubusercontent.com/12111609/37819917-0b1eb526-2eba-11e8-98db-6f201835ebf1.png)
![wx20180323-164446](https://user-images.githubusercontent.com/12111609/37819946-150ee696-2eba-11e8-9967-39507fafa6c0.png)

源码明明是这样的，写死了是44的啊，什么原因导致的呢？
```
#pragma mark - Layout

- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    
    _previewView.frame = self.view.bounds;
    _previewView.scrollView.frame = self.view.bounds;
    CGFloat toolBarHeight = [TZCommonTools tz_isIPhoneX] ? 44 + (83 - 49) : 44;
    _toolBar.frame = CGRectMake(0, self.view.tz_height - toolBarHeight, self.view.tz_width, toolBarHeight);
    _doneButton.frame = CGRectMake(self.view.tz_width - 44 - 12, 0, 44, 44);
}
```

**Comment by banchichen** [comment]
@flyweights 适配越南语那次，完成按钮的高度被我写错了...😂
已提交：https://github.com/banchichen/TZImagePickerController/commit/dd7a3cc932b9c7cf116c7b8d2cc39749e961fd28
已发布新版：2.0.1
