### ISSUE TITLE
手动拖到项目里

### ISSUE THREAD

**Issue by lvxiang0208** [banchichen/TZImagePickerController#793]
拖到项目里报错:   ld: framework not found TZImagePickerController
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by banchichen** [comment]
删除掉，重新拖，记得勾上这3个：

![image](https://user-images.githubusercontent.com/12755494/38010374-506be3f4-328b-11e8-9410-adae21c0b73c.png)
