### ISSUE TITLE
自定义导航栏，返回按钮错误

### ISSUE THREAD

**Issue by Mayinwei** [banchichen/TZImagePickerController#794]
自定义导航栏返回按钮在ios11中错位，以前提过一次，这个更新中没看见效果，希望作者及时处理
<img width="379" alt="qq20180329-095536 2x" src="https://user-images.githubusercontent.com/20430546/38065793-a8a9dd44-3337-11e8-8cf4-220f876f02c2.png">

**Comment by banchichen** [comment]
@Mayinwei 给你回复过了：https://github.com/banchichen/TZImagePickerController/issues/703
