### ISSUE TITLE
iPhone5s拍照的时候闪退（9.3的系统）

### ISSUE THREAD

**Issue by zzcshao** [banchichen/TZImagePickerController#797]
Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.

Trapped uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x16064b550 of class AVCaptureVideoPreviewLayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x1604b91e0> (
<NSKeyValueObservance 0x1604e8ec0: Observer: 0x160257df0, Key path: changeSeed, Options: <New: YES, Old: YES, Prior: NO> Context: 0x1a1347b18, Property: 0x1604b91b0>

**Comment by banchichen** [comment]
Demo里也这样吗？如果不是的话，可以提供一个稳定复现的Demo吗？

**Comment by smileykevin** [comment]
我也是 9.3 的系统，刚开始还没事，突然就不行了，倒是不闪退，提示 Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates. 打印的 error 信息是 Resource busy

**Comment by banchichen** [comment]
@smileykevin 拍照用的是系统的，这个是系统的打印，原因暂时不清楚

**Comment by smileykevin** [comment]
@banchichen 嗯，在比较老的手机上会比较频繁地出现

**Comment by fanxiangyang** [comment]
ipod 5代  9.3.6系统     拍摄视频时报错报错   The operation couldn’t be completed. Resource busy
