### ISSUE TITLE
pod 下载下来的最新版本是 1.9.8，并不是最新版本。

### ISSUE THREAD

**Issue by smilehappy05** [banchichen/TZImagePickerController#798]

**Comment by redye** [comment]
![0e92e2d9f502d68b332014c3141842d2](https://user-images.githubusercontent.com/7239131/38193484-dcf75c1e-36a4-11e8-8b27-a3d9fd34cd4f.jpg)

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/38205543-98d43dd8-36d9-11e8-9640-f3d77b87ad48.png)
