### ISSUE TITLE
Memory Issue: The memory will keep increasing while you browse the images

### ISSUE THREAD

**Issue by gujinku** [banchichen/TZImagePickerController#80]
请在iPad真机上测试，打开CollectionView 浏览大量图片时，收到内存警告，闪退！！！

**Comment by gujinku** [comment]
请尽快修复， 后面使用的人也要注意了！

**Comment by banchichen** [comment]
你好，麻烦更新到1.4.0版本试试~ 1.4.0版本性能已经比较不错了，滑动帧数平均在57-58左右，媲美QQ的图片选择器，佳于微信的图片选择器。我这段时间都没有发现内存占用高的问题，内存占用一直比较正常（870张图片）.....当然在快速滑动的时候，CPU有时候会占用很高，但我测试了QQ和微信的图片选择器，都有这个问题，苹果官方的Demo也是如此。帧数测试截图可以看博客中的截图~http://www.jianshu.com/p/1975411a31bb

不过，我没有Pad真机.....只测试了6s和4s...

**Comment by banchichen** [comment]
你好，代码更新到了1.4.4版本，我刚刚通过模拟器进行了多次测试，问题已经修复了。iPad的屏幕比较大，图片的size会特别大，之前我只是做了简单限制，在屏幕宽度超过600时，只取600宽度的图片。这里处理地比较草率。现在已经修复了，请测试一下最新版，有问题再在这里告知下~     如果嫌取的图片清晰度不够，可以通过设置photoPreviewMaxWidth属性来调整，默认是540px，这里设置的值越大，占用内存会越多。
