### ISSUE TITLE
ios 11中，自定义导航栏，该控件返回按钮位置错位

### ISSUE THREAD

**Issue by Mayinwei** [banchichen/TZImagePickerController#800]
<img width="379" alt="qq20180329-095536 2x" src="https://user-images.githubusercontent.com/20430546/38294401-54a72950-381d-11e8-81a2-6d89ca1f1498.png">

**Comment by banchichen** [comment]
@Mayinwei 这是你第三次提了....
给你回复过了啊...   https://github.com/banchichen/TZImagePickerController/issues/703
