### ISSUE TITLE
图片裁剪的三个问题，已经放弃。

### ISSUE THREAD

**Issue by titman** [banchichen/TZImagePickerController#804]
裁剪的三个问题。
1. 当图片宽或高小于裁剪尺寸时不能自动缩放。
2. 裁剪后即使图片尺寸小于裁剪尺寸，裁剪后的图片也会与裁剪尺寸一样。
3. 基于2，裁剪后透明部分会变为白色。

以上三条与预期不符。

**Comment by banchichen** [comment]
前辈，来个PR不~？

**Comment by WeMadeCode** [comment]
前辈 如何解决

**Comment by WeMadeCode** [comment]
可以试试这个https://github.com/WeMadeCode/TZImagePickerController

**Comment by KevinKingCN** [comment]
+1

**Comment by songyuanhang** [comment]
添加了这个判断，当图片的高度小于剪切框的高度，返回的照片还是有白边。

**Comment by 814349837** [comment]
+1

**Comment by banchichen** [comment]
感谢PR：https://github.com/banchichen/TZImagePickerController/pull/1102
刚刚发了新版哈，大家试下

3.2.1：新增裁剪用scaleAspectFillCrop属性，设置为YES后，照片尺寸小于裁剪框时会自动放大撑满
