### ISSUE TITLE
选择gif图后gif图没有选中标识

### ISSUE THREAD

**Issue by ChenZhenChun** [banchichen/TZImagePickerController#805]
bug描述：选择gif图后（单选）gif图的没有标识选中状态，此时还可以选择其他图片，但是右下角选中标识是计算了gif图的标识。
期望：在多选图片并且允许单选gif时，若第一张选择的是gif图片则其他图片不能选择，若第一张选择的不是gif图片后面的图片不允许选择gif。

**Comment by banchichen** [comment]
如果需要gif和普通图片一起选的话，设置下allowPickingMultipleVideo为YES。
```objectivec
/// Default is NO / 默认为NO，为YES时可以多选视频/gif图片，和照片共享最大可选张数maxImagesCount的限制
@property (nonatomic, assign) BOOL allowPickingMultipleVideo;
```

否则gif和视频一样，只能在gif和视频单独的预览页选择，不能在预览普通图片的时候选择（会被当成普通图片）。
