### ISSUE TITLE
pod 安装问题

### ISSUE THREAD

**Issue by zwcshy** [banchichen/TZImagePickerController#808]
![image](https://user-images.githubusercontent.com/4241636/38847702-9a906cf2-4235-11e8-9f10-485144a96459.png)
没有代码，只有资源文件

**Comment by banchichen** [comment]
看下你的podfile，版本号是多少，别的库正常吗？

**Comment by zwcshy** [comment]
别的库都正常，我尝试了1.98版本、2.0.1 版本都不显示

**Comment by banchichen** [comment]
@zwcshy 好的，我这边也是这样的环境，pod是正常的，方便制作一个小Demo吗？然后把下载地址给我，我看看我这行不行

**Comment by cddjr** [comment]
xcode9.3得使用pod1.5+版本， 1.2这个太老了
