### ISSUE TITLE
sourceAssets 归档问题

### ISSUE THREAD

**Issue by a1274786993** [banchichen/TZImagePickerController#809]
如何将代理imagePickerController:  didFinishPickingPhotos: sourceAssets:  isSelectOriginalPhoto:方法返回来的sourceAssets进行归档后缓存，以便再次进入此界面时通过initWithSelectedAssets: selectedPhotos: index:初始化预览照片。由于对PhotoKit框架不熟悉，自己通过创建对象转换却老是出错，  谢谢

**Comment by banchichen** [comment]
@a1274786993 是否可以保存在应用中某个单例对象的属性里？应用退出后这个缓存也不合适了...

**Comment by a1274786993** [comment]
已经解决了 思路有错误
可以通过存储PHAsset的localIdentifier，再在需要的时候通过fetchAssetsWithLocalIdentifiers: options: 查询出PHAsset就好了

**Comment by banchichen** [comment]
赞👍
