### ISSUE TITLE
Carthage 缺少TZImageManager类

### ISSUE THREAD

**Issue by josercc** [banchichen/TZImagePickerController#810]
用Carthage 集成最新版本 没有TZImageManager这个文件暴露 工程抱错

**Comment by banchichen** [comment]
恩，目前没有把TZImageManager暴露，我下版本暴露下。

不过，工程报错倒不会吧，我这里的用Carthage的Demo是正常的，只是不能在工程里使用TZImageManager中的API

**Comment by banchichen** [comment]
刚刚加上了：https://github.com/banchichen/TZImagePickerController/commit/4ab796d1f5705025ecb2cdc2dda6b493ba76dd98  这两天会发布个新版本

**Comment by josercc** [comment]
@banchichen 我们之前的用到 TZImageManager 这个类 准备用 Carthage 就抱错 没有这个文件

**Comment by banchichen** [comment]
@josercc 好的，新版2.1.0.1已发布哈，把TZImageManager等类设置为Public了。
