### ISSUE TITLE
进入“相册”选择好图片后，再点击预览，再逐个去掉预览上的钩，点击确定就会出现bug

### ISSUE THREAD

**Issue by airdragon0915** [banchichen/TZImagePickerController#812]
步骤：点击进入“相册”---选择好多张图片---然后点击“预览”---然后在预览图片的右上角去掉选择的钩（即取消选择这张图片）---然后把所有选择好的图片在预览中都取消选择（此时预览中没有一张图片选择）----然后再点击右下脚的“完成”按钮---然后在选择图片的回调方法中会得到一张图片（此时不应该返回一张图片，因为所有选择的图片都已经取消了）

**Comment by banchichen** [comment]
@airdragon0915 这里的处理和微信是一样的，如果没有选择任何照片，在预览页点击完成按钮，会选择上当前预览的图片。

**Comment by CG-Kerr** [comment]
不太理解产品为什么要这样做?用户明明都取消的

**Comment by banchichen** [comment]
@CG-Kerr 可能产品认为更多的场景是：用户大致挑好一个图片，点击图片去了预览，发现就是要这张，就直接点完成。这种场景的话该设计可以让用户少操作一步。

如果是用户要取消，更常见的场景是在相册/照片列表页直接取消，点到预览页面一个个取消选中再点完成，这种场景还算比较少。
