### ISSUE TITLE
源码里许多的block中会出现循环引用的警告！

### ISSUE THREAD

**Issue by airdragon0915** [banchichen/TZImagePickerController#813]

**Comment by banchichen** [comment]
截个图看下，版本是多少？

**Comment by banchichen** [comment]
已修复：https://github.com/banchichen/TZImagePickerController/commit/328d1fc6f6a274ac39af1a4bd09b0e6d00383911  这两天发布个新版

**Comment by banchichen** [comment]
已发布新版 2.1.0.1
