### ISSUE TITLE
关于从“相册”选择好照片，进入预览后的bug

### ISSUE THREAD

**Issue by airdragon0915** [banchichen/TZImagePickerController#814]
微信里预览照片在未选择图片的情况下“确定”按钮是不可点击状态，而“TZImagePickerController”在选择多张照片后进入“预览”，然后在“预览”中去掉所有照片，此时“确定”按钮还是可以点击状态，这个逻辑似乎有点不合常理

**Comment by banchichen** [comment]
微信里，选中多张照片，点击某张选中的照片去预览，逐一取消选中，这个时候发送按钮是可点击状态。这个是不是也是个bug？

你说的情况，是点击预览按钮时的情况，这个是微信后面加的。在微信里两种逻辑都存在。

**Comment by banchichen** [comment]
而且，未选择任何照片的情况下去预览，微信的发送按钮是可点击的。从选中多张照片到未选中照片，只是多了几个操作步骤，还是回到了“未选择任何照片的情况下”，微信的两种逻辑才不应该。
