### ISSUE TITLE
导航栏外观自定义异常

### ISSUE THREAD

**Issue by DemonLover** [banchichen/TZImagePickerController#815]
![2018-04-19 11 47 11](https://user-images.githubusercontent.com/20568661/38970335-710ca74a-43c7-11e8-80d0-b852fa298362.png)
将要present imagePickerVc导航栏颜色正常 加载完成之后不管怎么设置颜色永远是白色（没有对UINavigationController做任何处理）

**Comment by DemonLover** [comment]
![2018-04-19 12 08 02](https://user-images.githubusercontent.com/20568661/38970838-56d5b36e-43ca-11e8-96c5-90836033946f.png)

**Comment by zinkuro** [comment]
我也遇到了，怎么解决的？
