### ISSUE TITLE
TZImagePickerController中的PickDelegate 在预览选择图片完成后不执行代理

### ISSUE THREAD

**Issue by talka123456** [banchichen/TZImagePickerController#816]
原因是因为在TZPhotoPickerController类中的- (void)callDelegateMethodWithPhotos:(NSArray *)photos assets:(NSArray *)assets infoArr:(NSArray *)infoArr方法,执行的时候tzImagePickerVc已经dismiss导致delegate已经销毁,怀疑是版本更新将delegate改为weak导致,

**Comment by banchichen** [comment]
不会的，dismiss的时候completion回调持有了self，回调走完self才会释放，回调里我看pickerDelegate是有值的，否则Demo也就不正常了。你那里Demo也是正常的吧？

可以检查下设置的pickerDelegate是否在别的地方释放了，图片多选择不会强引用pickerDelegate的。如果还有是问题，可以制作一个必现的Demo我看下。
