### ISSUE TITLE
iOS 11.2 上传图片崩溃

### ISSUE THREAD

**Issue by VictDog** [banchichen/TZImagePickerController#817]
iOS 11.2 上传图片 崩溃，提示[AVCaptureSession release]: message sent to deallocated instance 0x1c0010290

**Comment by banchichen** [comment]
@VictDog  上传图片不是你们自己上传吗？

**Comment by VictDog** [comment]
这个不是说上传服务器崩溃了，图片上传服务器成功了，也正常显示了，但是报错显示坏内存，报错的意思是AVCaptureSession 提前释放了。

**Comment by banchichen** [comment]
报错是哪里报错，服务端还是客户端？在显示的时候报错还是？

不可能是这个库的问题，你可以试试用系统的选择器对比下。

**Comment by cddjr** [comment]
显然是你自身的代码缺陷造成，比如在回调中用阻塞方法上传了文件

**Comment by VictDog** [comment]
首先说一句抱歉，这个问题并不是您框架的问题。 后来我使用了原生的也会出现这个问题，经检查是使用了一个分类引起的。注释掉这个分类，就不会引起这个问题。但是我无法分析出为什么会出现这个问题，您能帮我分析一下吗？

**Comment by banchichen** [comment]
@VictDog 可以制作一个必现的demo，把下载链接放上来

**Comment by VictDog** [comment]
@banchichen 这两天有点忙，忘记把demo放上来了，这个是崩溃demo下载地址 https://git.coding.net/VictDog/BugDemo.git 。 tips：拍照才会出现崩溃，请大佬帮忙看看。

**Comment by VictDog** [comment]
好的😀，还是谢谢你了
