### ISSUE TITLE
About update

### ISSUE THREAD

**Issue by v2panda** [banchichen/TZImagePickerController#82]
升级后这个方法没了，导致项目出了问题
`- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray *)photos sourceAssets:(NSArray *)assets`

话说下次更新还会替换原方法吗？

**Comment by banchichen** [comment]
抱歉哈。没这方面经验。。。改起来很快，换一个就行了~ 多给你返了个参数~
