### ISSUE TITLE
相册里点击拍照，选择视频，视频拍摄完成后出现bug

### ISSUE THREAD

**Issue by liwanlu** [banchichen/TZImagePickerController#821]
视频拍摄完成后，**显示有一个选中项，但是列表里不论照片，还是视频都没有一个显示被勾选**。而此时点击某个视频会提示：“选择照片时不能选择视频”，点击完成发现原来是刚才拍摄的视频被选中了。

**Comment by banchichen** [comment]
@liwanlu 贴一下你的选择器配置代码

**Comment by banchichen** [comment]
@liwanlu 如果视频只需要选一个，设置下maxImagesCount。如果视频需要多个，设置下allowPickingMultipleVideo。就不会出现你上面的情况。

**Comment by banchichen** [comment]
可能我应该判断下，如果allowPickingMultipleVideo为NO，拍完视频后不默认选中，跳转去视频预览页给用户操作？

**Comment by banchichen** [comment]
这里做了点优化：不能多选视频的情况下，不选中拍摄的视频： https://github.com/banchichen/TZImagePickerController/commit/fb2980d2db1fc168e3faf14e5f3f70eb0a789aee

发布了2.1.0.3版本
