### ISSUE TITLE
内存猛增

### ISSUE THREAD

**Issue by hkshenSmart** [banchichen/TZImagePickerController#824]
我屏蔽了原图按钮，所以选不了原图。我选了几张图片后，点击右下方的 完成 偶尔出现crash，xcode9.3/iOS11.3，我又打开xcode的内存查看，发现点击完成时，内存猛然增高，出现一个内存峰值，估计有时候就在这个内存峰值太高而crash了

**Comment by banchichen** [comment]
贴一下你那的内存变化曲线，和你的版本。你那Demo正常吗？

我这Demo的结果，不选原图的时候，选择9张图片（手机拍的，2M大小），获取图片那一刹车内存只涨了10-20M左右，iPhone8的真机情况下。

![image](https://user-images.githubusercontent.com/12755494/39345651-3c3df2ac-4a1c-11e8-8093-41de30225669.png)
