### ISSUE TITLE
代码错了？？

### ISSUE THREAD

**Issue by Zhangguiguang** [banchichen/TZImagePickerController#825]
https://github.com/banchichen/TZImagePickerController/blob/37dc1af9d5274077e6cf27e71a8ca6e3dce38758/TZImagePickerController/TZImagePickerController/TZAssetCell.m#L157

你好，你这里的判断貌似写错了，我认为应该是这样的，你认为呢？
`if (_selectImageView == nil)`  →→ `if (_selectPhotoButton == nil)`

**Comment by banchichen** [comment]
赞👍

已merge

**Comment by LeoAiolia** [comment]
哈哈，最新的原来已解决了这个问题了啊。
我们的需求是视频和图片可以同时选择，结果发现视频会变成图片被选中，查了半天发现是这里的问题，来看看解决了没有，然后提个issue，结果已经有人提过这个问题了。👍👍👍👍👍👍
