### ISSUE TITLE
[bug] 拍照图片的问题

### ISSUE THREAD

**Issue by ShaoSikang** [banchichen/TZImagePickerController#826]
```objectivec
/// Sort photos ascending by modificationDate，Default is YES
/// 对照片排序，按修改时间升序，默认是YES。如果设置为NO,最新的照片会显示在最前面，内部的拍照按钮会排在第一个
@property (nonatomic, assign) BOOL sortAscendingByModificationDate;
```
实际情况与描述相反

**Comment by banchichen** [comment]
你好，之前确实是总是按modificationDate排序，后面有段时间发现modificationDate这个排序工作不正常，图片顺序会乱，所以改为了目前的样子，这是当时的issue： https://github.com/banchichen/TZImagePickerController/issues/259

我重新试了下用modificationDate来排序，发现还是乱的， 顺序和系统相册里的顺序很多对不上，你可以check下。
目前设置sortAscendingByModificationDate为YES的情况下，图片顺序和系统相册的一样的，最近的照片排在下面。
