### ISSUE TITLE
希望尽快修复关于视频的bug

### ISSUE THREAD

**Issue by tangguoan** [banchichen/TZImagePickerController#827]

**Comment by cddjr** [comment]
又不说具体什么bug、如何复现，一点都不像一个做技术的人。

**Comment by tangguoan** [comment]
基本上就随便测试了一下
> http://chuantu.biz/t6/297/1524884611x-1566688431.jpg
> http://chuantu.biz/t6/297/1524884630x-1566688431.jpg

**Comment by tangguoan** [comment]
基本上随便测试了一下就发现
> http://chuantu.biz/t6/297/1524884611x-1566688431.jpg
> http://chuantu.biz/t6/297/1524884900x-1566688431.jpg
视频怎么没有选中  最新的demo下载

**Comment by tangguoan** [comment]
基本上随便测试了一下就发现
<img src=http://chuantu.biz/t6/297/1524884611x-1566688431.jpg /> <img src=http://chuantu.biz/t6/297/1524884900x-1566688431.jpg /> 视频怎么没有选中 最新的demo下载

**Comment by banchichen** [comment]
@tangguoan 你说的问题，这里有回复： https://github.com/banchichen/TZImagePickerController/issues/821
