### ISSUE TITLE
部分图片获取不到

### ISSUE THREAD

**Issue by woshiqqt** [banchichen/TZImagePickerController#83]
从微信上下载到相册的图片获取不到

**Comment by banchichen** [comment]
我刚刚试了下，我从微信上保存的图片，在我的相机胶卷相册下。iOS9.3.2的6s和iOS8.4的5s都可以。 你那里是什么型号和系统呢？

**Comment by banchichen** [comment]
iOS7的4s也是好的...在相机胶卷相册下...

**Comment by woshiqqt** [comment]
不好意思，我发现是照片时间的问题，新添加的照片跑到最上面去了。

**Comment by banchichen** [comment]
没事，好的~
