### ISSUE TITLE
性能优化和demo bug

### ISSUE THREAD

**Issue by heysunnyboy** [banchichen/TZImagePickerController#838]
（1）demo 首页横屏的时候，那个点击相册按钮，不见了6s的手机
（2）相册里面滑动图片时，滑动速度较快的话，cpu会超过100，有较明显掉帧的感觉

**Comment by banchichen** [comment]
1、demo不支持横屏
2、滑动速度快cpu压力大，短时间超过100是正常的，你可以和其它图片选择器比较下帧数，TZImagePickerController算是很优秀的，博客里有帧率测试数据：https://www.jianshu.com/p/1975411a31bb

**Comment by heysunnyboy** [comment]
1进入相册页面是可以横屏的，但是刚进去页面横屏就滑动不到了

**Comment by banchichen** [comment]
恩，你再转成竖屏
