### ISSUE TITLE
关于图片裁剪问题

### ISSUE THREAD

**Issue by Shameless521** [banchichen/TZImagePickerController#839]
楼主好，希望在单选情况下，左下角可以实现自定义view ，或者button，目前现在有这样的一个需求，在选择完图片后，可以选择裁剪的尺寸，进行裁剪，感谢楼主。

**Comment by banchichen** [comment]
目前没有计划升级裁剪功能...

**Comment by Shameless521** [comment]
我看到有两个属性 一个是设置 竖屏裁剪，一个是设置横屏裁剪，这个的使用 是两个方法一起设置么，还是只能设置一个，我分别设置了两个，和一个，  效果都不对。还有什么别的属性么需要设置么。感谢楼主

**Comment by banchichen** [comment]
@Shameless521 你参考下Demo的使用，你只设置cropRect就行，里面会计算cropRectLandscape和cropRectPortrait
