### ISSUE TITLE
更新到 1.4.0 后，相册列表的图片显示不出来

### ISSUE THREAD

**Issue by IAMJ** [banchichen/TZImagePickerController#84]
![001](https://cloud.githubusercontent.com/assets/2928760/15474576/fe98975e-2137-11e6-8336-b39449c9966f.jpg)

**Comment by izemo** [comment]
你好，请问是什么机型和什么系统呢？

**Comment by IAMJ** [comment]
@izemo 6s plus / iOS 9.3.2

**Comment by IAMJ** [comment]
@izemo 进入这个判断分支
[https://github.com/banchichen/TZImagePickerController/blob/master/TZImagePickerController/TZImagePickerController/TZAssetCell.m#L49](url)

**Comment by banchichen** [comment]
_model = model;
    if (!iOS8Later) {
        self.representedAssetIdentifier = [[TZImageManager manager] getAssetIdentifier:model.asset];
    }
    PHImageRequestID imageRequestID = [[TZImageManager manager] getPhotoWithAsset:model.asset photoWidth:self.tz_width completion:^(UIImage *photo, NSDictionary *info, BOOL isDegraded) {
        // Set the cell's thumbnail image if it's still showing the same asset.
        if (!iOS8Later) {
            self.imageView.image = photo; return;
        }
        if ([self.representedAssetIdentifier isEqualToString:[[TZImageManager manager] getAssetIdentifier:model.asset]]) {
            self.imageView.image = photo;
        } else {
            NSLog(@"this cell is showing other asset");
            [[PHImageManager defaultManager] cancelImageRequest:self.imageRequestID];
        }
        if (!isDegraded) {
            self.imageRequestID = 0;
        }
    }];
妹的，我明明测试了好几台设备都是好的。。。没想到push前多加了个感叹号....    把上面这段代码的第二句，！iOS8Later去掉前面的非就好了。。

**Comment by banchichen** [comment]
代码已经更新了，1.4.1哈~  抱歉~
