### ISSUE TITLE
大神您好，有张不到300K的Gif，在预览的时候内存暴涨，您抽时间看一下吧

### ISSUE THREAD

**Issue by smileykevin** [banchichen/TZImagePickerController#842]
![img_4524](https://user-images.githubusercontent.com/30530425/39742799-729de6aa-52d1-11e8-8649-b1e83ea2fede.GIF)

**Comment by banchichen** [comment]
搜一下这个属性：gifPreviewMaxImagesCount，默认是200，设置小一点内存就占用少些，但是gif的播放体验也差些。
