### ISSUE TITLE
takePictureImage 不起作用

### ISSUE THREAD

**Issue by CivelXu** [banchichen/TZImagePickerController#843]
设置  takePictureImage 没用

**Comment by banchichen** [comment]
@CivelXu 贴下你的初始化代码，如果设置了iconThemeColor，需要在设置iconThemeColor后再设置takePictureImage，因为设置iconThemeColor的时候会根据主题色生成相应的初始icon。

**Comment by CivelXu** [comment]
>          let imagePicker = TZImagePickerController(
>             maxImagesCount: 9, columnNumber: 3, delegate: self)
>         imagePicker?.isSelectOriginalPhoto = true
>         imagePicker?.allowTakePicture = true
>         imagePicker?.allowPickingVideo = false
>         imagePicker?.sortAscendingByModificationDate = true
>         imagePicker?.showSelectBtn = false
>         imagePicker?.allowCrop = false
>         imagePicker?.naviBgColor = UIColor.white
>         imagePicker?.barItemTextColor = Color_ED5634
>         imagePicker?.naviTitleColor = Rcolor.c333333()
>         imagePicker?.statusBarStyle = .default
>         imagePicker?.allowPickingGif = true
>         imagePicker?.takePictureImage = Rimage.xiangji1()


设置了没变

**Comment by banchichen** [comment]
@CivelXu 在Demo里设置takePictureImage=[UIImage imageNamed:@"photo_delete"]是生效的。Rimage.xiangji1()是一个有值的UIImage对象吗？
你参照Demo调试一下吧
