### ISSUE TITLE
是否显示图片选中序号有点小问题

### ISSUE THREAD

**Issue by xcvzaq** [banchichen/TZImagePickerController#844]
都显示的1，我看了下在默认初始化方法里面 selectedAssetIds，没有初始化导致的，希望有时间修复下。
还有个需求，可以加入横向滑动多选图片么，类似系统相册的，滑动多选。

**Comment by banchichen** [comment]
@xcvzaq 看下你的初始化方法，Demo是正常的，你比较下
横向滑动多选的应该不会，还有很多更应该做的...

**Comment by xcvzaq** [comment]
我看了你的Demo
如果注释下面的属性设置，Demo也会出现问题
if (self.maxCountTF.text.integerValue > 1) {
        // 1.设置目前已经选中的图片数组
        imagePickerVc.selectedAssets = _selectedAssets; // 目前已经选中的图片数组
    }
你可以验证下

**Comment by banchichen** [comment]
@xcvzaq 确实，赞👍
下版修复掉，你先设置下selectedAssets避免下~

**Comment by wukongzhikong** [comment]
你好，更新到2.1.3版本后，设置showSelectedIndex为true，显示的图片序号依然全是“1” @banchichen

**Comment by banchichen** [comment]
你好，这个问题这版本忘记修了...你再设置下selectedAssets哈...
