### ISSUE TITLE
打包上传App Store 时出现 ERROR-ITMS 90046错误

### ISSUE THREAD

**Issue by EnderRule** [banchichen/TZImagePickerController#845]
使用carthage build 集成，.framework 中的 Info.plist 文件 的CFBundleShortVersionString 有四段时会报错。例如版本号=2.1.0.3 就会报错Error-ITMS 90060.

参见 https://blog.csdn.net/lovehalok/article/details/50965397

**Comment by banchichen** [comment]
好的，你先本地改下，我以后避免这个问题

**Comment by banchichen** [comment]
你好，2.1.2版本发布了。
