### ISSUE TITLE
为什么在项目中获取了地理位置？

### ISSUE THREAD

**Issue by vvard3n** [banchichen/TZImagePickerController#846]
为了添加照片拍摄地点？？？
还是说有其他需求？？
刚刚被拒了。。。

Guideline 5.1.5 - Legal - Privacy - Location Services

Your app uses location services but does not clarify the purpose of its use in the location modal alert. Apps that collect, transmit, or use location data must notify and obtain the user’s consent prior to accessing this data.

但是我有写权限内容

**Comment by banchichen** [comment]
看起来是描述不够清晰，没把目的写明确，手淘的描述参考一下：
![image](https://user-images.githubusercontent.com/12755494/39848375-34f3c22a-5439-11e8-9fc2-ea3489051f9c.png)

**Comment by banchichen** [comment]
Demo里我写的是：允许定位以把位置保存到照片中。
一个完整的照片是会带定位的，系统相机也是

**Comment by vvard3n** [comment]
就是这样写的，一脸懵逼hhhh

**Comment by banchichen** [comment]
我把Demo的描述改为这样吧："XXX"想访问您的位置，为了拍照时将您的位置信息保存到照片中

**Comment by cooaer** [comment]
遇到同样的问题了，可是我们的应用除了这个地方都不要位置权限！已经被拒了！添加描述后不知道能不能审核通过！

**Comment by ZenonHuang** [comment]
一样因为这个被拒绝了。添加描述也没用。

**Comment by banchichen** [comment]
@ZenonHuang 定位权限是很基础的权限，应该是描述的目的不够清晰哈，参考下上面手淘的描述吧~

**Comment by vvard3n** [comment]
要写详细点哈兄弟萌

> 一样因为这个被拒绝了。添加描述也没用。



> 遇到同样的问题了，可是我们的应用除了这个地方都不要位置权限！已经被拒了！添加描述后不知道能不能审核通过！
