### ISSUE TITLE
导航栏颜色

### ISSUE THREAD

**Issue by 1120892638** [banchichen/TZImagePickerController#847]
我的导航栏整体颜色为白色  然后present到选择控制器导航栏上就显示不出内容了

**Comment by cddjr** [comment]
picker.navigationBar.barTintColor = vc.navigationController?.navigationBar.barTintColor
        picker.navigationBar.tintColor = vc.navigationController?.navigationBar.tintColor
        picker.navigationBar.titleTextAttributes = vc.navigationController?.navigationBar.titleTextAttributes
        picker.barItemTextFont = nil
        picker.barItemTextColor = nil
        picker.statusBarStyle = vc.preferredStatusBarStyle

**Comment by banchichen** [comment]
@1120892638 哥，你改了导航栏颜色，那你把别的颜色也改掉啊...示例：
```objectivec
    // 导航栏改为白色
    imagePickerVc.navigationBar.barTintColor = [UIColor whiteColor];
    // 其它文字/icon颜色改为黑色
    imagePickerVc.navigationBar.tintColor = [UIColor blackColor];
    [imagePickerVc.navigationBar setTitleTextAttributes:@{NSForegroundColorAttributeName: [UIColor blackColor]}];
    imagePickerVc.barItemTextColor = [UIColor blackColor];
```
