### ISSUE TITLE
iPhone4 iOS 7.1.2 系统出现问题

### ISSUE THREAD

**Issue by GitHubazuo** [banchichen/TZImagePickerController#85]
1.选取图片，图片的选中状态消失，但功能还可以使用
2.拍照完成，得到的照片与拍得的照片不一致
3.期待完善。

**Comment by banchichen** [comment]
你好，请更新到1.4.1版本哈，这里的是好的~  之前几个版本是有这个问题~

**Comment by banchichen** [comment]
然后~ 1.4.1版本，性能有了大幅提升~ 滑动帧数达到了57，跟QQ的图片选择器帧数基本无差~

**Comment by GitHubazuo** [comment]
好
