### ISSUE TITLE
照片选择数量限制问题

### ISSUE THREAD

**Issue by shen0607** [banchichen/TZImagePickerController#851]
假设我最多可选择5张照片，在我已经选择了5张照片的情况下，再去点击拍照按钮又拍了一张照片，这样最后返回给了我6张照片

**Comment by banchichen** [comment]
哥，已选5张后再拍照，再拍的照片不会默认选中啊。
如果你是把拍照按钮放在外面的，你自己控制啊，代码都不是我库里的了。

**Comment by shen0607** [comment]
嗯，我拍照按钮是在里面的，跟选择照片一起

**Comment by shen0607** [comment]
在照片选择完成的函数里面我确实得到了6张照片

**Comment by banchichen** [comment]
@shen0607 你在Demo里试试，我正常的。
