### ISSUE TITLE
pod 'TZImagePickerController'和下载示例Demo的代码不一致

### ISSUE THREAD

**Issue by iOSCountry** [banchichen/TZImagePickerController#852]
使用cocoapod得到的源码确实示例demo中的这2个属性(暂且发现2个),但是版本号都显示的是version 2.1.1 - 2018.05.07 
![image](https://user-images.githubusercontent.com/17453419/39959553-ddddbd06-5645-11e8-9c90-f08c068a966d.png)
![image](https://user-images.githubusercontent.com/17453419/39959565-01bc4fee-5646-11e8-830f-dd6f06eea406.png)

**Comment by iOSCountry** [comment]
@property (assign, nonatomic) BOOL showPhotoCannotSelectLayer;
@property (strong, nonatomic) UIColor *cannotSelectLayerColor;
缺少这2个

**Comment by banchichen** [comment]
showPhotoCannotSelectLayer属性还在开发阶段，尚未发布
