### ISSUE TITLE
property 'contentInsetAdjustmentBehavior' not found on object of type 'UIScrollView *'

### ISSUE THREAD

**Issue by neatchenheng** [banchichen/TZImagePickerController#853]
error happened with version >2.1.0

TZPhotoPreviewCell.m:117:25: error: property 'contentInsetAdjustmentBehavior' not found on object of type 'UIScrollView *'
            _scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;

TZPhotoPreviewCell.m:117:58: error: use of undeclared identifier 'UIScrollViewContentInsetAdjustmentNever'
            _scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;

**Comment by banchichen** [comment]
contentInsetAdjustmentBehavior是iOS11下UIScrollView的熟悉，用Xcode9及以上的版本。
