### ISSUE TITLE
Hi, 拍摄视频不是很清晰呢？

### ISSUE THREAD

**Issue by RanchenY** [banchichen/TZImagePickerController#854]
iPhone 7p, iOS 11.3.1 
使用TZImagePickerController demo 选择拍摄视频，视频页面不清晰。
使用demo
![img_0218](https://user-images.githubusercontent.com/34503597/39966405-d1fbfc30-56dd-11e8-9fa5-7a548339f07d.PNG)
使用系统相机
![Uploading IMG_0219.PNG…]()

谢谢！

**Comment by banchichen** [comment]
拍摄视频用的系统的UIImagePickerController，没有指定视频质量videoQuality，默认是中等质量，下版开个设置属性出来

**Comment by banchichen** [comment]
2.1.2版本发布了，新增了一个名为uiImagePickerControllerSettingBlock的block，可定制UIImagePickerController的其它属性，具体使用可参看Demo。
