### ISSUE TITLE
model出来的界面点击返回，选择一个相册目录进来，顶部的返回，allphoto 和取消都没有了

### ISSUE THREAD

**Issue by ProgrammerXZ** [banchichen/TZImagePickerController#856]
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:9 delegate:self];
    imagePickerVc.naviBgColor = LJDColor(106, 168, 231);
    imagePickerVc.naviTitleColor = [UIColor whiteColor];
    imagePickerVc.preferredLanguage = @"zh-Hans";
    // You can get the photos by block, the same as by delegate.
    // 你可以通过block或者代理，来得到用户选择的照片.
    [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
        for (UIView *view in cell.contentView.subviews) {
            if ([view isKindOfClass:[PictureItem class]]) {
                PictureItem *item = (PictureItem *)view;
                [item setBackgroundImage:photos[0] forState:UIControlStateNormal];
                [item setImage:[[UIImage alloc] init] forState:UIControlStateNormal];
                [item setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
                UIView *view = [[UIView alloc] initWithFrame:item.frame];
                view.backgroundColor = [UIColor blackColor];
                view.alpha = 0.2;
                [item addSubview:view];
                [item.titleLabel bringSubviewToFront:item];
            }
        }
    }];
    [self presentViewController:imagePickerVc animated:YES completion:nil];`

**Comment by banchichen** [comment]
请先对比Demo自查：
![image](https://user-images.githubusercontent.com/12755494/39974088-cc360f90-5758-11e8-88f2-b6a1a39f4fcd.png)

**Comment by banchichen** [comment]
初始化看起来没有问题，试试这段初始化代码在Demo里正不正常

**Comment by luzhaung** [comment]
找到原因了吗？主要原因应该是把导航栏背景色设置成了白色，返回字体的颜色也是白色，所以就看不到“消失了”

**Comment by luzhaung** [comment]
imagePickerVc.navigationBar.tintColor = UIColor.black
