### ISSUE TITLE
发现了两处代码书写错误

### ISSUE THREAD

**Issue by Lucaziki** [banchichen/TZImagePickerController#859]
TZPhotoPickerController和TZPhotoPreviewController中，在UICollectionView的代理方法中，都是使用的indexPath.row,这是不对的，应该使用indexPath.item。

**Comment by banchichen** [comment]
赞👍
大兄弟，来个PR不~？

**Comment by Lucaziki** [comment]
晚上下班了来一发🤪

**Comment by Lucaziki** [comment]
@banchichen 等不到下班了，反正改动也不多，已经提交PR🤪

**Comment by banchichen** [comment]
已merge，👍👍

**Comment by Lucaziki** [comment]
🎉🎉🎉
