### ISSUE TITLE
图片数组下标越界

### ISSUE THREAD

**Issue by angihu** [banchichen/TZImagePickerController#86]
2016-05-24 17:07:45.574 TZImagePickerController[999:195943] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]'

怎么出现的呢？
1、选择2张图后点击确定回到主界面；
2、点击其中一张到预览；
3、在预览页面点击右上角取消选中；
4、再点击预览页面左上角返回箭头，返回主界面；
5、然后主界面上还是2张图，但是，这个时候点击最后一张图（第2张）的时候，程序崩溃，是下标越界了。
6、总结完毕。

我猜想，是，你在预览页面点击右上角取消选择时改变了数据源（而不是点击右下角确定时更改），但没有及时更新主界面的UI，导致的。

**Comment by banchichen** [comment]
谢谢~特别喜欢这种提bug的姿势！！！
将TZImagePickerController的第116行改为：self.selectedAssets = [NSMutableArray arrayWithArray:selectedAssets];就可以了。
我在这里的设计逻辑是：如果在外界单独打开预览控制器，若点击了取消按钮，数据是不做更新的，放弃此次选中状态的更改。
我之前这句代码是self.selectedAssets = selectedAssets;  此时并没有进行深复制，所以即使用户点击了取消按钮返回，但是数据还是改了，而selectedPhotos没改，界面是根据selectedPhotos来显示的，从而selectedAssets越界了....
我更新一下代码，pod也更新一下吧....1.4.2~     谢谢哈~

**Comment by angihu** [comment]
哈哈，我还曾暴力解决你这个问题；现在看到你修复了，真好！

我是在你那个TZPhotoPreviewController的back事件里面加了一个判断：
if (!_selectButton.isSelected) {
       [self select:_selectButton];
}

因为没仔细看你写的其他控制器，我也看不懂……
不过现在已经将你给我的代码改过来了，已经不会出现我说的那个问题了，谢谢啊！

**Comment by banchichen** [comment]
哈哈，好吧~  代码太多了还没怎么写注释~ 握爪~
