### ISSUE TITLE
开启显示照片的选中序号， 都是显示1

### ISSUE THREAD

**Issue by wlingf** [banchichen/TZImagePickerController#861]
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:2 delegate:self];
    imagePickerVc.sortAscendingByModificationDate = NO;
    imagePickerVc.showSelectedIndex = YES;
    [self presentViewController:imagePickerVc animated:YES completion:nil]
<img width="369" alt="wx20180517-164621 2x" src="https://user-images.githubusercontent.com/19945512/40166745-e2d0d096-59f1-11e8-8900-9d2834d9610a.png">

**Comment by wlingf** [comment]
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:9  delegate:self ];
    imagePickerVc.sortAscendingByModificationDate = NO;
    imagePickerVc.selectedAssets = self.selects;
    imagePickerVc.showSelectedIndex = YES;
    [self presentViewController:imagePickerVc animated:YES completion:nil];

需要配合selectedAssets 这个配置，选中的序号才会正常的显示，看下能不能去掉这个配置，也可以正常配置，demo如果没配置这个，也是显示不正常

**Comment by banchichen** [comment]
你好，2.1.4版本发布了，修复了这个问题
