### ISSUE TITLE
self.iconThemeColor 设置后又被设置成了默认颜色

### ISSUE THREAD

**Issue by liubang0909** [banchichen/TZImagePickerController#862]
如果继承TZImagePickerController的话。。self.iconThemeColor 设置后又被设置成了默认颜色，self.iconThemeColor的默认设置 能否放在viewDidLoad里面？

**Comment by liubang0909** [comment]
每次setIconThemeColor 都会 设置 configDefaultImageName  里面一些常量的设置是不是也放在viewDidLoad里面比较好？我之前升级都是直接替换图片。。 这次替换了图片之后发现不使用preview_number_icon，photo_number_icon了。。

**Comment by banchichen** [comment]
第一条：继承的话，你重写 `- (instancetype)initWithMaxImagesCount:(NSInteger)maxImagesCount columnNumber:(NSInteger)columnNumber delegate:(id<TZImagePickerControllerDelegate>)delegate pushPhotoPickerVc:(BOOL)pushPhotoPickerVc;`方法，在这里设置你要的iconThemeColor。

**Comment by banchichen** [comment]
替换图片也一样哈，等我的默认设置走完后，你再设置就O了

**Comment by liubang0909** [comment]
好的 谢谢回复

**Comment by liubang0909** [comment]
有个想法。。与其重写初始化方法（虽然目前常用的初始化方法只有一个。。）  重写默认设置的方法。。将默认设置方法暴露出来是不是更友好点。。
