### ISSUE TITLE
如何直接进入拍照

### ISSUE THREAD

**Issue by lovelyelfpop** [banchichen/TZImagePickerController#865]
我想不经过照片墙，直接进入拍照；拍完也不经过照片墙多选(有也没关系)；
然后一样的能得到预览图和原图asset。

**Comment by banchichen** [comment]
那你直接调系统的拍照就好了，然后参考库里的代码拿到asset

**Comment by xiaotian777888** [comment]
直接进入拍照这个有必要加一下，自己直接调用系统相机再去拍照，还要另外写授权相机等业务逻辑。
