### ISSUE TITLE
点击一张图片会出现iCloud同步很多张，另外iCloud会出现多次请求下载

### ISSUE THREAD

**Issue by misuqian** [banchichen/TZImagePickerController#866]

**Comment by banchichen** [comment]
获取iCloud图片只会在选中某个图片和预览大图时触发，可以在源码里看到这些逻辑，你是通过什么表现确定预览一张图片会触发多张iCloud照片的下载呢？

**Comment by misuqian** [comment]
开启显示顺序数字之后，图片选取一次之后你会调用 collectView reload，然后界面内所有cell都会重新赋值一次model，之前选取好的图片会重新触发一次大图，另外会出现一些没有select图片也会触发一次大图请求，你可以showIndex开启验证一下

**Comment by heysunnyboy** [comment]
@banchichen 我退出icloud ，然后在登录，也出现了这个bug，然后在反复测试了几次的确重现了，看了下代码，看到了问题，当在进入相册，icloud 还没有加载出大图的时候，可以重现这个bug,
TZPhotoPickerController 488行
TZAssetModel *model;
    if (tzImagePickerVc.sortAscendingByModificationDate || !_showTakePhotoBtn) {
        model = _models[indexPath.row];
    } else {
        model = _models[indexPath.row - 1];
    }
TZAssetModel *model 是个局部变量
当我改成这样问题,bug 就修复了
if (tzImagePickerVc.sortAscendingByModificationDate || !_showTakePhotoBtn) {
        cell.model = _models[indexPath.row];
    } else {
        cell.model = _models[indexPath.row - 1];
    }
我猜大概是，cell.model 强引用的是局部变量，因此你在cell 里面获取的cacheimage 其实并没有添加给 controller _model数组里的model.

**Comment by YueMing-11** [comment]
我按照上述方式改正  还是有这个问题

**Comment by heysunnyboy** [comment]
@YueMing-11 能看下你的代码截图吗

**Comment by banchichen** [comment]
@YueMing-11 @heysunnyboy 欢迎二位加群讨论：778723997

**Comment by banchichen** [comment]
排查发现是因为最近几个版本，在选中和取消选中的时候，会刷新collectionView导致的。之前为了优化体验，库内部会对于选中的图片做提前获取大图的操作，提前下载iCloud图片，防止点完成后长时间等待。

刷新collectionView后，asset基本会得到一个新model，会再次获取大图，而没有成功取消上次的request，如果新model不在iCloud，旧model在iCloud，旧iCloud的request进度更新后会更新进度条的进度，错乱地又显示了进度条。

刚刚发布了2.1.5版本，已经修复了这个问题，麻烦大家更新到新版测试下。
