### ISSUE TITLE
为什么提前获取大图，这个大图没有看到你的使用，这样有什么作用？

### ISSUE THREAD

**Issue by heysunnyboy** [banchichen/TZImagePickerController#867]
![24f479da-1598-45ff-9b5b-7276adb3406d](https://user-images.githubusercontent.com/14311318/40298409-9edda1ee-5d15-11e8-8fc9-8d2bc29ff109.png)

**Comment by banchichen** [comment]
大图可能存在iCluod里，如果选中，则提前会用户下载，此时cell上会有进度条

**Comment by heysunnyboy** [comment]
这样提前获取是会帮缓存到相册内部，方便你下次获取吗
