### ISSUE TITLE
cell 重用引发bug?

### ISSUE THREAD

**Issue by heysunnyboy** [banchichen/TZImagePickerController#868]
![a2e2df94-66d7-40f7-ab5a-2321e26d9306](https://user-images.githubusercontent.com/14311318/40300092-ce47ea66-5d1a-11e8-8854-5474a2c3e5bc.png)

icloud 未能拉取到图片的话,也就是block 没有回调，self.imageView.image 就没有设置过image，有可能存在cell 重用导致的图片错乱的风险？

**Comment by banchichen** [comment]
cell重用，则会有新的model，则会根据新的model取图片来显示。

在这里，当前model未能拉取到图片的几率是0，因为iCloud图片在本地是有缩略图的，在TZAssetCell显示的这种尺寸，是缩略图，不需要经过iCloud下载。

**Comment by heysunnyboy** [comment]
最稳妥的是在未设置之前，置空

**Comment by heysunnyboy** [comment]
我只是提提建议，希望没有打扰到您
