### ISSUE TITLE
第一次打不开相机

### ISSUE THREAD

**Issue by 200895045** [banchichen/TZImagePickerController#869]
我使用actionSheet做的相机与相册的选项，选择相机，会提示两个授权信息，都同意后，相机没打开，再选就可以了，之前的版本没有这个问题

**Comment by banchichen** [comment]
我刚刚在Demo里试了，是可以的，iPhone8，iOS11.3.1，你是在Demo里试的吗？

**Comment by banchichen** [comment]
每次授权完成的回调里，都会再调一下 [self takePhoto]
