### ISSUE TITLE
没有单选模式

### ISSUE THREAD

**Issue by sa124a** [banchichen/TZImagePickerController#87]
好像没有单选模式，只能修改最大选取数来控制，比较生硬

**Comment by banchichen** [comment]
你好，如果是用在要单选的地方，我是建议用系统的UI去选择，可以裁剪，可以选时刻。我下次自己把系统的图片选择器封装成一个方法集成进来吧。

**Comment by codwam** [comment]
+1

**Comment by teng555teng** [comment]
什么时候加

**Comment by banchichen** [comment]
昂，最近好忙....

**Comment by banchichen** [comment]
已支持单选模式..... 最新的commit：新增单选模式，设置maxImagesCount为1即可..
