### ISSUE TITLE
关于导航高度问题

### ISSUE THREAD

**Issue by xiaomage1478** [banchichen/TZImagePickerController#872]
您好，我集成进项目之后，从预览图片页面返回到选择图片页面之后导航高度变窄，iOS 11.3 ，6s 。请问有什么合理的解决办法么

**Comment by banchichen** [comment]
截个图看看，最好你能制作个稳定复现的Demo。我没你们的工程，我这不好调试。

**Comment by xiaomage1478** [comment]
![wechatimg59](https://user-images.githubusercontent.com/25787973/40405473-572d9d1a-5e8f-11e8-9566-1b0c0efda05e.jpeg)
![wechatimg60](https://user-images.githubusercontent.com/25787973/40405480-605c5458-5e8f-11e8-997a-84e878182f72.jpeg)
<img width="513" alt="wx20180523-134207 2x" src="https://user-images.githubusercontent.com/25787973/40405483-624cb1b8-5e8f-11e8-9ce2-4a15e58dd4fe.png">
这是效果图和初始化代码，稳定复现的demo我看能不能制作出来，毕竟用你的demo是没问题的，我剥离项目试试

**Comment by banchichen** [comment]
好的，重点关注下状态栏的一些设置，进入预览页的时候会隐藏状态栏，出来的时候会再显示。可以注释下这个隐藏状态栏的代码看看效果调试下。
