### ISSUE TITLE
关于获取Bundle url为空崩溃的问题

### ISSUE THREAD

**Issue by zhangjieJay** [banchichen/TZImagePickerController#876]
+ (NSBundle *)tz_imagePickerBundle {
    NSBundle *bundle = [NSBundle bundleForClass:[TZImagePickerController class]];
    NSURL *url = [bundle URLForResource:@"TZImagePickerController" withExtension:@"bundle"];
    bundle = [NSBundle bundleWithURL:url];
    return bundle;
}

在获取url报空指针,用cocoapods进行安装的,目前不知道具体原因,能找到bundle目录,但是就是不行,报空指针

**Comment by banchichen** [comment]
Demo是正常的，制作一个稳定复现的Demo看下。
如果我这里bundle url是空的话，其他库也会这样，大家都是这样取bundle路径的。

**Comment by duckls** [comment]
我也遇到这个问题了 
ios 12.1  6s 模拟器

**Comment by banchichen** [comment]
@duckls 帮忙制作个必现demo出来

**Comment by 2018Cool** [comment]
我也需要类似的问题  ios12.2
