### ISSUE TITLE
iPhone5 iOS 7.1.1 的几个问题

### ISSUE THREAD

**Issue by DearYe** [banchichen/TZImagePickerController#88]
我下载的是1.4.4版本
1、图片右上角选择按钮没有显示
2、点击预览后，返回按钮有点偏右，点击返回后卡顿了一会儿

**Comment by banchichen** [comment]
抱歉，第一点现在已经修复了。在TZAssetCell的m文件115行 _imageView = imageView; 后面加一句
[self.contentView bringSubviewToFront:_selectImageView];就好了。之前是被imageView被挡住了。
第二点是这样的：预览中的返回按钮不是导航栏里的，是自定义的一个视图，位置是那样设计的。卡顿我这里倒没发现。。。
