### ISSUE TITLE
多次调用无法清除已选记录

### ISSUE THREAD

**Issue by hubin97** [banchichen/TZImagePickerController#880]
[_tzImagePickerController.selectedAssets removeAllObjects];
 [_tzImagePickerController.selectedModels removeAllObjects];
数据是删除了, 但是浏览时还是有记录勾选的

**Comment by banchichen** [comment]
参考Demo的调法：

```objectivec
// 1.设置目前已经选中的图片数组
imagePickerVc.selectedAssets = _selectedAssets; 
```

**Comment by hubin97** [comment]
这两个没区别, imagePickerVc.selectedAssets和imagePickerVc.selectedModels即使为空数组了,但是 presentViewController后显示的页面还是有勾选记录问题 , 除非我重新初始化imagePickerVc

**Comment by hubin97** [comment]
您好, 问下上面的"需要回一下相册页面才行。"这个是什么意思?
最开始的设想与需求是这样的, 因为存在一个九宫格,有多处需要上传图片,切依据类型或者说是下标不同,限制上传图片数量不一,所以我设想在getter方法中取得,代码大致如下:
- (TZImagePickerController *)tzImagePickerController
{
    //!!!!: 如果不每次初始化tzImagePickerController新的则会记录之前的选中照片
    //if(_tzImagePickerController == nil)
    {
        // 根据类型设定 1.默认baseIcons 2.二次上门场景 仅传1张图片即可
        BOOL isBaseUser = [noNullStr(_iconManagerModel.accNature) isEqualToString:@"02"];
        NSUInteger needUploadNum = (_didClickIndex < 4 || (isBaseUser && _didClickIndex == 17))? 1:2;

        _tzImagePickerController = [[TZImagePickerController alloc]initWithMaxImagesCount:needUploadNum delegate:self];
        _tzImagePickerController.allowPickingVideo = NO; // 不允许视频
        _tzImagePickerController.photoPreviewMaxWidth = 300.0f;
        _tzImagePickerController.sortAscendingByModificationDate = NO; // 默认由新到旧排列
    }
    
    // 每次选择图片之前清空之前的内容 (不能清除显示标记)
    //[_tzImagePickerController.selectedAssets removeAllObjects];
    //[_tzImagePickerController.selectedModels removeAllObjects];

    return _tzImagePickerController;
}

**Comment by banchichen** [comment]
相册页会刷新照片的选中情况，一般选完照片是在照片列表页和照片预览页，这2个页面不会刷新，所以出现上面那个情况，返回到相册页后会变好。

你可以在回调里，对_tzImagePickerController执行一次pop到根页面，第二次进去总是先到相册页，可以解决这个问题。

**Comment by banchichen** [comment]
也可以把getter改造下，总是创建一个新的...

**Comment by hubin97** [comment]
额, 感谢您的解答, 谢谢!

**Comment by syf345894943** [comment]
你特么的解决不了问题巴巴啥呢

**Comment by syf345894943** [comment]
> 也可以把getter改造下，总是创建一个新的...

https://github.com/banchichen/TZImagePickerController/issues/880#issuecomment-393054357

**Comment by syf345894943** [comment]
> 也可以把getter改造下，总是创建一个新的...
你特么的解决不了问题巴巴啥呢
