### ISSUE TITLE
忍不住想喷一句

### ISSUE THREAD

**Issue by iOS-XHWang** [banchichen/TZImagePickerController#881]
这TM的，我这本地仓库好久没更新了，一直用的1.9.6。我想吐槽的就是这个版本，不知道别的版本怎么样，我只知道最新的版本是没有这个问题的。默认的是导航栏黑色，状态栏白色。可是我想让导航栏白色，状态栏黑色。我他妈改个状态栏改了一个小时，死活就是改不了，在info.plist里面加上View controller-based status bar appearance竟然可以解决，真是费解了，完全不知道状态栏怎么变白的。。。真不知道哪个SB改成这个样子，是不是拿这个框架来练手来了？我想说，作者怎么审查这么不仔细，随随便便就让人提交呢？

**Comment by banchichen** [comment]
控制状态栏颜色的方式一共是两种：
1、如果info.plist里设置了`View controller-based status bar appearance`为NO，则每个页面都使用全局的状态栏设置，通过设置`[UIApplication sharedApplication].statusBarStyle`可以改变所有页面的状态栏。
2、如果设置了`View controller-based status bar appearance`为YES或没设置，则每个页面自己控制自己的状态栏样式，每个页面自己重写`preferredStatusBarStyle`来设置自己页面的状态栏。
