### ISSUE TITLE
ipad 使用选中图片（图片比较大）会出现图片类似重用的效果

### ISSUE THREAD

**Issue by heysunnyboy** [banchichen/TZImagePickerController#883]
ipad 选中某个图片，然后向上滑动到看不到，然后在选中其他的，这样图片有时候就会乱了，选中的时候会使用cache 去显示model.cacheImage , 去刷新，但是我感觉这个model.cacheImage 的指向的image 好像会出现错乱，因为获取对应的尺寸图片block的回调是异步的，如果当前cell 不在屏幕内，则是另一个cell 的的self.model.cacheImage 给赋值了，然后一用cacheimage就错乱了,不知道是不是这个原因

**Comment by heysunnyboy** [comment]
我觉得不应该用cell.model 去保存cache image 而是 去对controller 的models 数组赋值取出对应的model 去给cacheimage 赋值，看下能不能避开这个问题

**Comment by banchichen** [comment]
@heysunnyboy 出现错乱后，再来回滑动一下，图片会重新显示正确吗？
如果图片较大且存在iCloud里，再选中其它照片前如果cachedImage还没有，是会出现这个情况，我刚刚提交了代码，在请求新的cachedImage前先清空旧的，麻烦你试下新Demo行不行。
QQ群：778723997，可以加一下，我们群里交流下

**Comment by heysunnyboy** [comment]
@banchichen 我的不是存在icloud 是一些ppt 生成的长图，也会有这个问题，

**Comment by banchichen** [comment]
如QQ沟通，2.1.5版本已经OK了。
