### ISSUE TITLE
DEMO里在 collectionView 添加图片后, 再点击不能预览, 要点击多次才会偶尔能预览, 什么原因呢

### ISSUE THREAD

**Issue by Kittycats** [banchichen/TZImagePickerController#886]

**Comment by banchichen** [comment]
不会吧，我这是好的。。。
你在cell的点击事件里debug下看看走到哪停掉了？

**Comment by Kittycats** [comment]
点击didSelectItemAtIndexPath: 不响应哦, 点击多次才会偶尔响应了, 才能预览

**Comment by Kittycats** [comment]
你用的那个 layout,  和 cell 的点击方法手势有冲突

**Comment by banchichen** [comment]
这样吗。。。
加下群：778723997   拍个视频我看下~？

确定是最新的Demo且没做什么改动吗？

**Comment by banchichen** [comment]
如QQ沟通，是鼠标有问题，误触发了长按或pan手势，用了触摸板后正常。
