### ISSUE TITLE
photoSelImage 设置没有生效

### ISSUE THREAD

**Issue by ChenZhenChun** [banchichen/TZImagePickerController#887]
photoSelImage设置了图片没有效果，后发现是把showSelectedIndex设置在了photoSelImage之后引起的，showSelectedIndex放在前面设置则可避开这个bug。

**Comment by banchichen** [comment]
恩，设置了showSelectedIndex后photoSelImage不再是默认的对勾，是个纯色背景了，我内部会改photoSelImage。
