### ISSUE TITLE
发现一个天坑，内存问题

### ISSUE THREAD

**Issue by STDawn** [banchichen/TZImagePickerController#89]
如果选了9张图片，然后在全部取消，那么这内存任然在，iPhone6，iOS9.3.1, 占用RAM 40M,

**Comment by banchichen** [comment]
你好，对象销毁的时间是由系统来管理的，销毁对象和创建对象一样，也是一个比较耗时的操作，所以系统会在合适的时间去销毁对象，来释放内存，不是即时释放的。所以有的时候，dealloc方法并不会在控制器一消失的时候就走。我刚刚测试了，选择了多张图片，再取消选择，继续操作一会，内存就释放掉了。
