### ISSUE TITLE
Location Error

### ISSUE THREAD

**Issue by chenpeimin2** [banchichen/TZImagePickerController#891]
- (void)locationManager:(CLLocationManager *)manager didUpdateToLocation:(CLLocation *)newLocation fromLocation:(CLLocation *)oldLocation;
if oldLocation is nil, the project will be reported wrong.

**Comment by banchichen** [comment]
这个Api比较老了，升级下新版，新版用的是locationManager:didUpdateLocations:

**Comment by chenpeimin2** [comment]
我是通过pod更新的最新版本哦

**Comment by chenpeimin2** [comment]
发现问题了，原来是pod没有更新到最新的库，谢谢了
