### ISSUE TITLE
无法使用相机的弹窗点击设置无法跳转

### ISSUE THREAD

**Issue by jokiazhang** [banchichen/TZImagePickerController#892]
1.无法使用相机 的弹窗没有国际化
2.点击设置没有跳转到设置界面

**Comment by banchichen** [comment]
库内部做了国际化的，Demo没做

点击设置，只是调了`[[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]]`
还没听说这个API有问题，我这正常，你可以试着换个手机/模拟器试下。
