### ISSUE TITLE
系统相册增删监听没有实现

### ISSUE THREAD

**Issue by 393385724** [banchichen/TZImagePickerController#893]
如题：
如果正在选取照片，此时app进入后台，已选照片是否该删除掉？有计划新增这个功能么？

**Comment by banchichen** [comment]
微信QQ都没处理这种情况，这种case太少了

如果用户只是回到后台看了下别的App，立马又回来，发现已选的照片都被取消选中了，用户内心会咋想。。。

**Comment by 393385724** [comment]
确实，不过为了支持iOS8之前的系统，导致fetch出来的系统Asset需要做一层转换(create中间model)，当图片量达到万级的时候就会loading较长时间了

**Comment by banchichen** [comment]
这方面的耗时倒还好，根据time profiler的分析来看主要还是系统方法耗的时，用UIImagePickerController会更慢

**Comment by 393385724** [comment]
如果放弃支持iOS8之前系统，完全拥抱PhotoKit，fetch耗时可以忽略，直接使用fetchresult而不做中间model的转换，耗时上基本上和微信差不多了
