### ISSUE TITLE
【BUG】在预览图片界面，如果全部取消选择后，点击完成或者返回数据异常

### ISSUE THREAD

**Issue by lzp0717** [banchichen/TZImagePickerController#895]
【DEMO】以下情况均在已经选择了几张照片后，然后第二次进入相册选择图片的时候出现
1.在预览界面取消选择所有图片后 点击完成后，应该是没有图片了吧？为何还有图片
TZPhotoPreviewController  中的完成事件
// 如果没有选中过照片 点击确定时选中当前预览的照片
    if (_tzImagePickerVc.selectedModels.count == 0 && _tzImagePickerVc.minImagesCount <= 0) {
        TZAssetModel *model = _models[_currentIndex];
        [_tzImagePickerVc addSelectedModel:model];
    }

2.在预览界面取消选择的图片后，返回到选择照片的界面，发现照片的数字标显示有异常。

**Comment by banchichen** [comment]
1、在预览界面点完成，如果当前没有选中图片，会选中当前预览的图片再完成。（微信的逻辑）
2、是最新的Demo吗，我这正常的

**Comment by lzp0717** [comment]
1.微信最新版本，如果预览的时候没有任何一张图片被选中了，则done按钮会置灰，无法点击。
2.是最新的Demo，需要步骤前提。 @banchichen 
步骤
1.选择几张照片后(打开图片显示数字的属性)，点击done后，离开图片选择器，回到主页面此时已经选择了几张照片
2.再次进入图片选择器中，直接点击右下角浏览，然后取消勾选的照片，再次返回选择照片界面发现数字坐标异常

**Comment by lzp0717** [comment]
https://github.com/lzp0717/TZImagePickerController
fork了一下 然后上传了关于第二个问题的操作录像。 @banchichen

**Comment by banchichen** [comment]
@lzp0717 你好，视频已看到，感谢复现素材
2.1.6版本已发布，已经修复了该Bug。

**Comment by lzp0717** [comment]
@banchichen  👍赞！ 顺便请问下关于预览界面如果取消选择所有图片后，done按钮置灰这个交互。会考虑提供一个属性吗或者如果尝试RP一个这样的属性可以么

**Comment by banchichen** [comment]
这里微信的话是允许点done的，会默认带上目前预览的那张图片。
比如你什么都没选中的时候，去到预览页，找到了想要的图片，按done就可以直接发送，不需要先选中再发送了。感觉体验还是可以的。

也欢迎你提PR允许设置是否用微信这个逻辑，

**Comment by lzp0717** [comment]
@banchichen  微信的稍微做了一点小细节的处理。
1.如果是在选择照片的时候点击cell进入预览界面的，此时用的是你目前的逻辑，done无论何时都可以点击
2.如果是从左下角的“预览”按钮进入预览界面的话，如果把照片全部取消了，此时done是会置灰的

RP我尝试一下能否符合你的代码标准哈哈。。=-=
