### ISSUE TITLE
pickerDelegate属性weak可能会存在问题

### ISSUE THREAD

**Issue by lewsilver** [banchichen/TZImagePickerController#896]
pickerDelegate在整个项目中的重要性还是挺高的，建议使用strong。我在使用您的项目的时候，pickerDelegate不是一个viewcontroller，就会出现回调无法进行。我调试了很久，最后发现是weak属性的问题。
建议把属性改为strong。

**Comment by banchichen** [comment]
你看系统的UIImagePickerController、UITableViewDelegate等，有用strong的吗....

**Comment by cddjr** [comment]
delegate用Strong 简直是不要命了
