### ISSUE TITLE
多次选图片，可以超过九张

### ISSUE THREAD

**Issue by Alamoalone** [banchichen/TZImagePickerController#9]
这个图片选择的时候，第一次选八张，发表界面预览8张，第二次选超过1张，发表界面就回超过9张，
你的picker没有记录总选择数应该9张，选过之后，应该记录还剩几张还能选，不然就会出现上述问题

**Comment by banchichen** [comment]
你好，发表界面关于图片总数的限制，在发表界面很好做的，需要你在发表界面自己判断一下。如果图片超过了9张，是不允许再弹出图片选择界面的。微信是这样做的。

**Comment by Alamoalone** [comment]
我解决了，用了你暴露出的属性maxImagesCount，每次都用最大张数去减掉添加的照片数组就能在选照片界面也只能选剩下的张数了，谢谢提供这么好的imagepicker

**Comment by banchichen** [comment]
恩，对的~谢谢认可~
