### ISSUE TITLE
选择图片回调错误——不要用懒加载，每次present都创建一个TZ

### ISSUE THREAD

**Issue by Kid-J** [banchichen/TZImagePickerController#903]
在setDidFinishPickingPhotosWithInfosHandle方法中，TZImagePickerController的实例化没有Delloc的情况下，再次调起setDidFinishPickingPhotosWithInfosHandle，回调的信息内容没改变；

如：
第一次选择完A图，返回的是A图；
第二次选择完B图，返回的仍然是A图；

**Comment by banchichen** [comment]
你debug下看看TZImagePickerController的addSelectedModel:方法是否有异常，返回的图片由TZImagePickerController的selectedModels决定，你排查下看看

**Comment by pstkqzy** [comment]
我也遇到了  我在一个页面要多次用到TZImagePickerController  我就用的懒加载 结果后面几次回调的都是一张图片
