### ISSUE TITLE
选取的PHAsset格式的视频怎么压缩后上传到七牛啊

### ISSUE THREAD

**Issue by luo-h** [banchichen/TZImagePickerController#904]
选取的PHAsset格式的视频怎么压缩后上传到七牛啊，主要是怎么压缩，有没得大佬做过的

**Comment by banchichen** [comment]
七牛自己有Api，可以直接传asset

也可以参考Demo，把视频导出到本地沙盒，拿到二进制数据/视频沙盒路径传给七牛，导出视频的方法：TZImageManager的getVideoOutputPathWithAsset，设置presetName选择不同的压缩方式

**Comment by luo-h** [comment]
大佬、我现在就是用的七牛的api传asset，只是相册选择的视频太大了，想把内存压缩得小一点，又不要太小，然后presetName主要是前面三种格式，但是不能控制，比如我60M的视频被压缩成1M和6M了，还有没得其他法可以控制压缩多少呢

**Comment by banchichen** [comment]
除了设置presetName，没有别的办法。

**Comment by luo-h** [comment]
大佬，视频压缩我还是有点儿问题，如果设置AVAssetExportPresetHighestQuality相当于没压缩，AVAssetExportPresetMediumQuality压缩挺快，但是有点儿模糊（60M压缩成10M了），AVAssetExportPresetLowQuality就更加模糊了，AVAssetExportPreset960x540（这个有点儿奇怪，有时候很快有时候很慢，几M的视频有时候会压缩成10多M），大佬可有啥建议？

**Comment by banchichen** [comment]
看你如何取舍了，只有这些选项...

**Comment by banchichen** [comment]
百度搜索下，如果播放本地视频...
沙盒的路径也是URL呀

**Comment by luo-h** [comment]
沙盒路径在APP重新运行后就无法播放了，没有重新运行可取出来播放，所以我感觉你导出的到沙盒存下来的路径是一个缓存，重新运行是被清空了吗

**Comment by banchichen** [comment]
是这样的，我是存放在沙盒tmp目录下，这个目录内容是系统决定清空时机的。如果你需要长期保存的话，可以把我的代码拿出来自己把目录改一下。
