### ISSUE TITLE
弱网下偶现选择照片完成后没有照片数据

### ISSUE THREAD

**Issue by hfq-donghuixiang** [banchichen/TZImagePickerController#907]
弱网下，多次选择照片，会出现偶然的选择图片完成后没有图片数据

**Comment by banchichen** [comment]
是在我Demo里吗？版本号多少？
弱网下如果是iCloud照片，会有正在同步的提示，不会dismiss掉。
如果不是iCloud照片的话，与网络没有关系。。。
