### ISSUE TITLE
选择图片框显示问题

### ISSUE THREAD

**Issue by diaodepeng** [banchichen/TZImagePickerController#908]
Xcode9.4 Swift4.1
version: 2.1.6
设置了iconThemeColor为蓝色, showSelectedIndex/showPhotoCannotSelectLayer = true之后, 选择icon显示异常(数字和钩子同时存在):
![image](https://user-images.githubusercontent.com/24413777/41757203-258093d0-7613-11e8-9d6d-c79a88138bb5.png)

**Comment by banchichen** [comment]
你对Demo额外做了什么操作？

如果设置了iconThemeColor，选中的图片也会是iconThemeColor颜色：
![image](https://user-images.githubusercontent.com/12755494/41778756-4a33fc54-7662-11e8-8f17-5a3ce376dce2.png)

**Comment by banchichen** [comment]
配置看起来没问题，好像你设置的iconThemeColor没生效，比较怪异，你把这个配置拿到Demo里试试？

**Comment by diaodepeng** [comment]
这是2.1.6的demo, 仅仅修改了这些...抱歉比较忙, 暂时没有时间仔细看代码.
<img width="1207" alt="qq20180623-101646 2x" src="https://user-images.githubusercontent.com/24413777/41804890-32108dda-76d1-11e8-902d-03c45089626f.png">

**Comment by banchichen** [comment]
找到原因了，你先调换下设置顺序哈...

![image](https://user-images.githubusercontent.com/12755494/41804982-023dcaa8-76d3-11e8-9269-880cac2e6eba.png)

设置showSelectedIndex之后会把photoSelImage设置为无对勾的，
设置了iconThemeColor又回到了默认图片

下版把这里优化下

**Comment by diaodepeng** [comment]
Thank you very much.
