### ISSUE TITLE
比较大的图片，在选择图片的时候 找不到。 附件为测试图

### ISSUE THREAD

**Issue by qijiangtao** [banchichen/TZImagePickerController#91]
![2016-05-19 003815](https://cloud.githubusercontent.com/assets/4817269/15670577/cee9a3be-2758-11e6-8a8b-02c3fca9e7be.jpg)

**Comment by qijiangtao** [comment]
辛苦大神啦!!!

**Comment by banchichen** [comment]
咦，我刚才拿你这个图片试了一下。可以找到的~

**Comment by qijiangtao** [comment]
是的，我搞错了，图片的排序顺序 好像不是按照添加时间来排序的，相册里面图片太多了，没看清楚
大哥，这响应速度太快了！！！

**Comment by banchichen** [comment]
哈哈~
