### ISSUE TITLE
使用脚本打包时NSBundle+TZImagePicker类报错

### ISSUE THREAD

**Issue by FFFang** [banchichen/TZImagePickerController#910]
he following build commands failed:
	CompileC /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Soul_New-cpyjltijsibimobokdbqnbmsvwlf/Build/Intermediates.noindex/ArchiveIntermediates/Soul_New/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/TZImagePickerController.build/Objects-normal/armv7/NSBundle+TZImagePicker.o TZImagePickerController/TZImagePickerController/TZImagePickerController/NSBundle+TZImagePicker.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by banchichen** [comment]
可以看到更具体的错误吗？

NSBundle+TZImagePicker是2016年写的，应该很多App都用上了，还没见人反馈过这个问题。。。

**Comment by FFFang** [comment]
项目里编译和运行都没问题，放到jenkins上用插件打包就出问题了。
而且1.7.8版本没有问题，升级到1.9.0以上就有问题了。/(ㄒoㄒ)/~~

**Comment by FFFang** [comment]
** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/Soul_New-emaodvgwlbqgqnczncetiqepokdd/Build/Intermediates.noindex/ArchiveIntermediates/Soul_New/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/TZImagePickerController.build/Objects-normal/armv7/TZLocationManager.o TZImagePickerController/TZImagePickerController/TZImagePickerController/TZLocationManager.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Build step 'Xcode' marked build as failure
Finished: FAILURE

**Comment by banchichen** [comment]
好吧...
这个错误看不出什么信息来，不好分析...
看了下1.7.8和1.9.0以上版本代码没有什么明显区别。。
现在最新版是2.1.6，试试这个~？
