### ISSUE TITLE
使用这个组件，发布被苹果退回，Your app uses the "prefs:root=" non-public URL scheme

### ISSUE THREAD

**Issue by DeliriousLee** [banchichen/TZImagePickerController#911]
在TZimagePickerView~>1.7.7版本中
发现在TZimagePickerController.m文件里面使用了“prefs:root=”，需要修复，希望作者可以修复一下？

**Comment by banchichen** [comment]
1.9.0以上版本修复了
现在最新是2.1.6

![image](https://user-images.githubusercontent.com/12755494/41804914-ccae302c-76d1-11e8-8172-2c72d6bd53d6.png)
