### ISSUE TITLE
2.1.6多选图片, 数字底图圆角噪点非常大

### ISSUE THREAD

**Issue by popor** [banchichen/TZImagePickerController#913]
今天使用的最新版本,发现在iPod,iPhone6手机上面,显示有问题.
https://github.com/banchichen/TZImagePickerController,第二张效果图数字3的圆角背景图,有很大的噪点.

之前使用的2.1.0.2版本是正常的,我下载你的demo在iPod上面运行也是一样的效果.

**Comment by banchichen** [comment]
@popor 你的图片没传上来

显示数字时，图片是贝塞尔画的，这是代码和效果：
![image](https://user-images.githubusercontent.com/12755494/41846616-d09daf3a-78a9-11e8-952d-58a232dec8dc.png)

**Comment by popor** [comment]
我说的不是这个数字,是屏幕下面最下面这一栏.
预览 原图 (1.1M) 3 确定
 这个数字3底图有很大噪点

**Comment by popor** [comment]
明天我在公司电脑看能不能发个截截图.

**Comment by popor** [comment]
iPod图片仅仅是下面控制栏有问题,iPhone6的截图是所有的贝塞尔画曲线都有问题.这2个截图都是你的demo直接运行的.我这边无法上传图片,发到你的火狐邮箱了.
iPod:11.3,iPhone6:11.3.1

**Comment by banchichen** [comment]
一直没找到合适的机器，今天找到个pod试了下...

问题已经修复哈，刚刚发布了2.2.4版本~
