### ISSUE TITLE
预览点击闪退

### ISSUE THREAD

**Issue by linmaojia** [banchichen/TZImagePickerController#915]
TZImagePickerController *_tzImagePickerVc = (TZImagePickerController *)self.navigationController;
    TZAssetModel *model = _models[_currentIndex]; 
这里崩溃

**Comment by banchichen** [comment]
我的Demo能复现吗？
可以在我的Demo里复现出来吗？

**Comment by linmaojia** [comment]
你的项目没问题，我的项目是模块化开发，自己的私有库导入进来的，然后在其他模块调用就出问题

**Comment by banchichen** [comment]
对比下你们那调用和Demo里调用的差别吧，不能在我Demo出现我也不好分析。
