### ISSUE TITLE
希望能添加使用image预览图片的功能

### ISSUE THREAD

**Issue by MQGreen** [banchichen/TZImagePickerController#916]
目前项目需要预览网络图片，但是TZImagePickerController只能传asset才能预览

**Comment by ouhuiju** [comment]
同求

**Comment by AndroidEngineerChenXiaoshuang** [comment]
怎么构建asset呢？
我试过了，但是项目在抛异常，你看看我的对吗？
`let uiImage = UIImage.init(data: self.imageData)!
            let assets = TZAssetModel.init()
            assets.asset = uiImage
            
            TZImagePickerController.init(selectedAssets: NSMutableArray.init(array: [assets]), selectedPhotos: NSMutableArray.init(array: [assets]), index: 0)`

**Comment by AndroidEngineerChenXiaoshuang** [comment]
那怎么构建asset呢？
我的代码是这样构建的，但是一直在抛异常
`let uiImage = UIImage.init(data: self.imageData)!`
`let assets = TZAssetModel.init()`
`assets.asset = uiImage`

`TZImagePickerController.init(selectedAssets:`
`NSMutableArray.init(array: [assets]),`
`selectedPhotos: NSMutableArray.init(array:`
`[assets]), index: 0)`

**Comment by banchichen** [comment]
@MQGreen @ouhuiju @AndroidEngineerChenXiaoshuang 

Hi，3.0.1版本已支持，需新接一个插件库：[TZImagePreviewController](https://github.com/banchichen/TZImagePreviewController)，请参考TZImagePreviewController里面的Demo使用。

抱歉久等了...
