### ISSUE TITLE
求救

### ISSUE THREAD

**Issue by zacklam** [banchichen/TZImagePickerController#917]
跳到过去的时候navigation下有一片空白

**Comment by zacklam** [comment]
![image](https://user-images.githubusercontent.com/13661790/42070132-9438a352-7b87-11e8-9d34-dd71fae0ccf3.png)
像这样的

**Comment by zacklam** [comment]
已经解决 只需要添加imagePickerVc.navigationBar.translucent = NO;即可解决白条问题

**Comment by banchichen** [comment]
好的
