### ISSUE TITLE
怎么设置弹出的图选择器的导航栏背景色

### ISSUE THREAD

**Issue by vitasapple** [banchichen/TZImagePickerController#918]
如题，我是隐藏了导航栏，然后选择图片是present，发现导航栏是橘黄色，我就用了naviBgColor这个属性设置，但是并没有什么用，请问要怎么改变导航栏的背景色
我是这么写的
```
TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:1 delegate:self];
    imagePickerVc.naviBgColor = ThemeColor;
    [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
        
    }];
    [self presentViewController:imagePickerVc animated:YES completion:nil];
```

**Comment by vitasapple** [comment]
解决了，是我自己的问题

**Comment by MrCaiWH** [comment]
@vitasapple 我也碰到这个问题了，你是什么原因不生效，帮忙解决一下

**Comment by vitasapple** [comment]
他的导航栏就是项目里的系统导航栏，所以如果是改变不了导航栏颜色的，应该是你自己的导航栏颜色设置问题发自我的iPhone------------------ 原始邮件 ------------------发件人: 黄花菜  <notifications@github.com>发送时间: 2018年7月17日 14:23收件人: banchichen/TZImagePickerController <TZImagePickerController@noreply.github.com>抄送: vitasapple <cjqgxx@126.com>, Mention <mention@noreply.github.com>主题: 回复：[banchichen/TZImagePickerController] 怎么设置弹出的图选择器的导航栏背景色 (#918)@vitasapple 我也碰到这个问题了，你是什么原因不生效，帮忙解决一下

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/banchichen/TZImagePickerController","title":"banchichen/TZImagePickerController","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/banchichen/TZImagePickerController"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MrCaiWH in #918: @vitasapple 我也碰到这个问题了，你是什么原因不生效，帮忙解决一下"}],"action":{"name":"View Issue","url":"https://github.com/banchichen/TZImagePickerController/issues/918#issuecomment-405473081"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/banchichen/TZImagePickerController/issues/918#issuecomment-405473081",
"url": "https://github.com/banchichen/TZImagePickerController/issues/918#issuecomment-405473081",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [banchichen/TZImagePickerController] 怎么设置弹出的图选择器的导航栏背景色 (#918)",
"sections": [
{
"text": "",
"activityTitle": "**黄花菜**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@MrCaiWH",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"banchichen/TZImagePickerController\",\n\"issueId\": 918,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/banchichen/TZImagePickerController/issues/918#issuecomment-405473081"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 351496811\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Liyongcong** [comment]
> 如题，我是隐藏了导航栏，然后选择图片是present，发现导航栏是橘黄色，我就用了naviBgColor这个属性设置，但是并没有什么用，请问要怎么改变导航栏的背景色 我是这么写的
> 
> ```
> TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:1 delegate:self];
>     imagePickerVc.naviBgColor = ThemeColor;
>     [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto) {
>         
>     }];
>     [self presentViewController:imagePickerVc animated:YES completion:nil];
> ```

我设置这个属性也没效果
