### ISSUE TITLE
环境Xcode9.4.1，用9.0模拟器没问题，10.0以上的初始化都闪退

### ISSUE THREAD

**Issue by max321** [banchichen/TZImagePickerController#919]
let imgPickerController = TZImagePickerController(maxImagesCount: 9, delegate: nil)
self.present(imgPickerController!, animated: true, completion: nil)
以上是初始化代码，用9.0的模拟器可以正常使用
10.0以上直接闪退
libsystem_kernel.dylib`__abort_with_payload:
    0x106303ecc <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x106303ed1 <+5>:  movq   %rcx, %r10
    0x106303ed4 <+8>:  syscall 
->  0x106303ed6 <+10>: jae    0x106303ee0               ; <+20>
    0x106303ed8 <+12>: movq   %rax, %rdi
    0x106303edb <+15>: jmp    0x1062fbb00               ; cerror_nocancel
    0x106303ee0 <+20>: retq   
    0x106303ee1 <+21>: nop    
    0x106303ee2 <+22>: nop    
    0x106303ee3 <+23>: nop

**Comment by banchichen** [comment]
如QQ沟通，是info.plist没配访问相册的隐私说明所致
