### ISSUE TITLE
从其他地方（比如百度云）保存到相册的图片，它的位置与在相册或者微信选择页里的位置 不一致

### ISSUE THREAD

**Issue by qijiangtao** [banchichen/TZImagePickerController#92]

**Comment by banchichen** [comment]
你好。请提供下更详细的测试信息，比如设备型号、系统版本号，出现的不一致具体是什么不一致。我刚刚在8和9系统的设备下测试，不管是保存百度云还有其他地方的图片，图片出现的位置和微信与相册都是一致的。

**Comment by qijiangtao** [comment]
机型：5s
版本:9.3.2

复现步骤：
1. 把一张很早之前拍摄的照片上传到百度云
2. 把该照片从百度云下载到本地相册
3. 使用相册或者微信查看的话，该图片会在最后一个位置， 使用大神的TZImagePickerController 查看的话，位置与步骤1中上传时的位置一样

**Comment by banchichen** [comment]
发现了~  我这里的照片排序时间，是按创建时间排序~  他们是按更新时间排序~  我下次更新下这里~

**Comment by qijiangtao** [comment]
好的，辛苦大神了！！！！

**Comment by banchichen** [comment]
你好，抱歉哈最近比较忙，代码还没提交上来呢。解决这个问题涉及的代码量很少的~你可以尝试修改TZImageManager类的代码：
option.sortDescriptors = @[[NSSortDescriptor sortDescriptorWithKey:@"creationDate" ascending:YES]]
把这里的@"creationDate"改成@"modificationDate" ~  然后排序就对了~
