### ISSUE TITLE
'xxx' is only available on iOS 8.0 or newer

### ISSUE THREAD

**Issue by changxingyu** [banchichen/TZImagePickerController#923]
Xcode 9.4创建的项目, 导入之后运行, 出现190个警告都是关于这个的.
建议#define iOS8Later ([UIDevice currentDevice].systemVersion.floatValue >= 8.0f) 这一系列宏用 #define iOS8Later @available(iOS 8.0, *)替换

**Comment by banchichen** [comment]
已修复，新版本2.1.9，demo现在是没有这类警告了
