### ISSUE TITLE
设置最小可选中的图片宽度、高度仍然可以选择不符合要求的照片

### ISSUE THREAD

**Issue by winann** [banchichen/TZImagePickerController#926]
当设置最小可以选中的图片宽高，
在单张图的页面没有可选的按钮
但是在缩略图页面仍然可以选中，

**Comment by banchichen** [comment]
和showSelectBtn属性冲突了....

已修复，新版本2.1.9

也可以参照demo实现isAssetCanSelect代理方法自定义更多过滤条件
