### ISSUE TITLE
本地化问题，App 内切换语言环境，控制器的导航title 和返回 title 不随语言变化

### ISSUE THREAD

**Issue by Daemonson** [banchichen/TZImagePickerController#929]
你好，现在做本地化的时候遇到如下问题，App 内切换语言环境，PHAssetCollection取出来的文字不会变化，只是对应着 App 启动起来的时候的语言。因此选择图片 VC 的导航 title 和返回按钮title不会随着 App 语言变化。

**Comment by banchichen** [comment]
看readme

![image](https://user-images.githubusercontent.com/12755494/42672115-9d87151e-8696-11e8-86b7-092f605a94e6.png)

**Comment by banchichen** [comment]
你App的切换是指你们App自己做的语言切换吗？

你看微信能做吗？系统是中文，微信选择英文，相册名字也是中文的，系统相册名字不支持单独设置语言。

这个做不了的大兄弟，相册的名字是系统提供的，只跟随系统语言。

**Comment by Daemonson** [comment]
对，我们做的是和微信一样的，应用内有语言切换功能。嗯，这个目前来看是做不了的。感谢回复。

**Comment by banchichen** [comment]
刚刚发布了2.2.1版本，对首次进入相册时的返回按钮title做了优化，做成了跟随tz设置的首选语言，而非系统或Localization native development region的语言。

**Comment by Daemonson** [comment]
更新试了下，可以的，感谢！
