### ISSUE TITLE
demo里的TZImagePickerController 和pod ‘TZImagePickerController’， 两个里面的方法有很多不一样了

### ISSUE THREAD

**Issue by Climb0516** [banchichen/TZImagePickerController#930]
我在demo里的TZImagePickerController 和pod ‘TZImagePickerController’， 两个里面的方法有很多不一样了，authorizationStatus，
savePhotoWithImage:(UIImage *)image location:(CLLocation *)location completion，
saveVideoWithUrl:(NSURL *)url location:(CLLocation *)location completion等，导致现在用pod导入后，以前的方法报错：
<img width="824" alt="default" src="https://user-images.githubusercontent.com/11717015/42816179-90b70b5a-89fc-11e8-959f-c020fb75c0b3.png">
<img width="1066" alt="default" src="https://user-images.githubusercontent.com/11717015/42816229-bc39ba16-89fc-11e8-87a2-774f81a310a2.png">
<img width="1177" alt="default" src="https://user-images.githubusercontent.com/11717015/42816241-c845895c-89fc-11e8-8eca-e56ef603dfff.png">
麻烦看下

**Comment by banchichen** [comment]
你们是源码导入的对吧？

建议体验下最新demo，看看是否可以放弃你们现有的源码导入，改为pod集成。
集成pod的话，你们源码导入的那份TZImagePickerController移除掉。

如果你截图里的代码是拿的demo页面的，那你pod最新版后，去最新的demo页把相应方法复制过来即可...

**Comment by banchichen** [comment]
就是github这个...
单独下载demo工程跑不起来？
不可能

**Comment by Climb0516** [comment]
能跑起来啊，
<img width="1109" alt="default" src="https://user-images.githubusercontent.com/11717015/42868007-cb2010c8-8aa3-11e8-8800-cfff8b60addd.png">
方法什么的 和我pod ‘TZImagePickerController’ 的 有一些出入

**Comment by Climb0516** [comment]
<img width="1119" alt="default" src="https://user-images.githubusercontent.com/11717015/42868102-0850cbd6-8aa4-11e8-945a-5720aed09522.png">
<img width="1065" alt="default" src="https://user-images.githubusercontent.com/11717015/42868114-13c7d1a8-8aa4-11e8-854c-e1b515c752fc.png">
demo里viewcontroller里， 还能用截图的这几个方法， 但我pod ‘TZImagePickerController’ ， 就用不了这些方法了。 
你这个demo里的TZImagePickerController ，和你组件TZImagePickerController，不一样啊

**Comment by Climb0516** [comment]
哦哦  我以为直接pod就是最新的了，，，，
叨扰了～
