### ISSUE TITLE
选择图片后状态栏消失

### ISSUE THREAD

**Issue by junjiewang1111** [banchichen/TZImagePickerController#934]
在点击完成返回app界面后,状态栏消失了!

**Comment by banchichen** [comment]
我的demo不会这样...

你提供个复现的demo发来看看吧...

**Comment by banchichen** [comment]
是这样的，TZPhotoPreviewController的`viewWillDisappear`里有再通过：
```objectivec
if (tzImagePickerVc.needShowStatusBar && iOS7Later) {
    [UIApplication sharedApplication].statusBarHidden = NO;
}
```
把状态栏打开，不过只适用由UIApplication全局控制状态栏的情况。

对于控制器自己决定导航栏的方式，我在TZPhotoPreviewController里是这样实现：
```objectivec
- (BOOL)prefersStatusBarHidden {
    return YES;
}
```
需要外面调起TZImagePickerController的控制器也实现一下并返回NO（如我的demo）。
