### ISSUE TITLE
2.2.2版本 选择图片时，提示TZAssetCell 循环引用

### ISSUE THREAD

**Issue by Climb0516** [banchichen/TZImagePickerController#936]
2.2.2版本 选择图片时，提示TZAssetCell 循环引用

**Comment by banchichen** [comment]
这个有哥们提过PR，merge了还没发，刚刚发了2.2.3，可以更新了~

https://github.com/banchichen/TZImagePickerController/pull/931/commits/034ed246ba040b92721781934245ae31828513ac

**Comment by Climb0516** [comment]
干的漂亮！
