### ISSUE TITLE
当在图片预览的时候点击确定状态栏消失了

### ISSUE THREAD

**Issue by jniosdeveloper** [banchichen/TZImagePickerController#938]
作者,你好.我在使用的过程中出现的问题是,当我在点击图片到预览图片时,这个时候状态栏应该是被你隐藏起来的,然后这个时候我点击确定,dismiss之后我App的控制器的状态栏也变成了隐藏状态,用了好多方法都不起作用,请问下有什么方法可以解决吗

**Comment by banchichen** [comment]
可以参考下demo，demo是正常的。
如果可以制作一个复现demo的话，可以看readme加一下QQ群，把demo发来看看

**Comment by banchichen** [comment]
是这样的，TZPhotoPreviewController的`viewWillDisappear`里有再通过：
```objectivec
if (tzImagePickerVc.needShowStatusBar && iOS7Later) {
    [UIApplication sharedApplication].statusBarHidden = NO;
}
```
把状态栏打开，不过只适用由UIApplication全局控制状态栏的情况。

对于控制器自己决定导航栏的方式，我在TZPhotoPreviewController里是这样实现：
```objectivec
- (BOOL)prefersStatusBarHidden {
    return YES;
}
```
需要外面调起TZImagePickerController的控制器也实现一下并返回NO（如我的demo）。
