### ISSUE TITLE
压缩图片不清晰

### ISSUE THREAD

**Issue by maybenai** [banchichen/TZImagePickerController#939]
手持身份证照相的这种图片，利用这个库选择之后保存到沙盒，沙盒里的图片比原图还有大，并且沙盒里的图片不清晰，请问应该怎么处理？

**Comment by banchichen** [comment]
保存进沙盒之前的图片清晰吗？

对清晰度要求高可以选用PNG压缩方法试试

**Comment by banchichen** [comment]
你保存到沙盒不是要把UIImage转成NSData吗，这个压缩方式会影响清晰度。

我问的是你保存图片进沙盒的UIImage对象清晰不清晰。。。

如果UIImage对象清晰，沙盒里的不清晰，就用UIImagePNGRepresentation的方式压缩，沙盒里的应该就清晰了。

**Comment by maybenai** [comment]
![d4ab379c-16a4-4a82-a6c2-7175714967eb](https://user-images.githubusercontent.com/12791647/43373853-df8958f0-93de-11e8-8623-d6da5a73120d.png)

**Comment by banchichen** [comment]
恩，那你应该问的是返回的UIImage不清晰，而不是保存进沙盒后不清晰。。。

需要更高清晰度的，自己用TZImageManager的getOriginalPhotoDataWithAsset取一下原图的NSData。

**Comment by banchichen** [comment]
你仔细看看，你存的还是photo[0]啊。。。
photo[0]还是缩略图

取了原图后，用photo啊。。。

**Comment by maybenai** [comment]
嗯嗯，这个后面我注意到了，改了保存的图片能看清了。谢谢你。但是对于这个有个疑问，在选择图片的左下角不是有一个原图按钮吗？那点显示的0.4m，但是到沙盒中去看变成了6.7m..沙盒里保存的不是原图吗？

**Comment by banchichen** [comment]
大哥，调这个API就是0.4M，看清楚点吧。。。

![image](https://user-images.githubusercontent.com/12755494/43389515-80368298-941e-11e8-8036-b237cc9ce357.png)

PNG压缩后会变大

**Comment by maybenai** [comment]
嗯嗯，谢谢你，我用JPEG保存原图这种能达到我想要的效果。谢谢你啦。
