### ISSUE TITLE
每个图标右上角的勾选按钮

### ISSUE THREAD

**Issue by hegelsu** [banchichen/TZImagePickerController#94]
真机4s 7.1.2(11D257)
1. 图片不少，刚开始打开的时候，显示的是很多白底图片，右上角也有灰色的未勾选的图标，然后不到1秒所有图片加载完成之后就看不到勾选的图标了，点击那块区域还是可以点的，但是就是没图标，用户不知道怎么用。
2. 似乎感觉，当有图片选择的时候，点左上角的返回比没有选择图片的时候要慢。
3. 在图片列表界面，此时没有选择任何图片，点击一张图进行预览，这个时候“确定”按钮是否应该不显示或灰色才对，如果点了右上解的勾才显示出“确定”按钮或变成可用。
4. 我现在的项目需求是，这个界面可以控制能不能拍照

希望尽快改正且完善。

另外有两个比较好的图片选择器，你可以参考下：
https://github.com/guillermomuntaner/GMImagePicker
https://github.com/denty/ImagePicker

**Comment by RicoCL** [comment]
我也是
iPhone 4 iOS7.1.2
打开图片Collection选择页面，小图片右上角不显示勾选☑️的按钮，望解决

**Comment by sglyqfh** [comment]
我也是这样的。小图片不显示勾选情况。大图中，选了原图也看不到勾选情况，上方的返回也看不到，但是可以点击。

望解决。

**Comment by banchichen** [comment]
抱歉，现在已经修复了。在TZAssetCell的m文件115行 _imageView = imageView; 后面加一句
[self.contentView bringSubviewToFront:_selectImageView];就好了。之前是被imageView被挡住了。

**Comment by banchichen** [comment]
@hegelsu  你好，关于你提的第三点，这里的逻辑我是完全搬照微信照片选择器的逻辑，他们也是这样处理的。关于第四点，我待会开放一个属性，就叫allowTakePicture吧，置为NO就不会出现拍照按钮。关于第二点，确实是的。当中有一个遍历的代码，影响了速度...
