### ISSUE TITLE
iCloud 上的图片，在图片列表中，缩略图的现实有问题

### ISSUE THREAD

**Issue by hjxSummerWind** [banchichen/TZImagePickerController#940]
缩略图展示的为其他图片，并不是原图的缩略图

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/43389912-7e98f258-941f-11e8-9c4a-32f7cbf0a2e6.png)

哥，你这么惜字如金，让我怎么查？

**Comment by hjxSummerWind** [comment]
不好意思，可能我没有表达清楚。
我的意思是，当我选择添加图片的时候，如果本地相册中有 icloud 中的但没有下载到本地图片，该图片在相册中展示的缩略图有为其他图片的缩略图，而不是该图片的缩略图。而且每次都会变。（不能加截图，好尴尬啊，不知道你理没理解。。。）

**Comment by banchichen** [comment]
这里可以发图的，图片拖进来就行。

你还是没看我上面回的内容，你的问题我早就明白了，但是你要告诉我你那里：
1、demo是否正常？
2、用的TZImagePicker的什么版本？
3、是用的最新版本吗？不是且demo正常，就升级下新版。
4、怎么初始化的TZImagePicker的？
5、你认为可以帮助我定位问题的一些信息。

**Comment by hjxSummerWind** [comment]
![unadjustednonraw_thumb_31](https://user-images.githubusercontent.com/38033101/43442751-7c4e76b4-94d1-11e8-8071-8f651b88de43.jpg)
![unadjustednonraw_thumb_32](https://user-images.githubusercontent.com/38033101/43442753-7da6a108-94d1-11e8-89e4-476181e07a1f.jpg)
1、是用刚下载的demo运行的，想看看效果来着
2、图1中的最后一张图片和图二中的倒数第二张图片，为一张图片，但是现实不同且都不为原图片
3、该图片为icloud上的，并未下载到本地的图片

**Comment by banchichen** [comment]
复现不了....

是这样的，iCloud图片在本地是有缩略图的，获取缩略图不涉及网络请求，你把网给断了这个页面也会正常显示。所以这个情况跟图片是否存在iCloud倒没关系。

加下QQ群发个视频看看吧：778723997
