### ISSUE TITLE
ipad设备下，拍照按钮放在外面点击拍照和相册中选择，调用不起来相机和相册

### ISSUE THREAD

**Issue by shaveKevin** [banchichen/TZImagePickerController#941]
控制台打印
TZImagePickerController[2375:758499] Warning: Attempt to present <TZImagePickerController: 0x1050f4e00>  on <ViewController: 0x10501d800> which is already presenting <UIAlertController: 0x1050d9600>
设备情况：iOS11.4.1
设备：ipad pro

**Comment by banchichen** [comment]
刚刚提交了代码，已修复~
