### ISSUE TITLE
在初始化时，设置maxImagesCount的值为1时，拍摄视频的回调有问题

### ISSUE THREAD

**Issue by zhumimi** [banchichen/TZImagePickerController#945]
如题，设置maxImagesCount的值为1时，在拍摄视频后，会进入选择照片的回调，在设置maxImagesCount的值为2后。再拍摄视频，会正常进入选择视频的回调，麻烦看一下问题出在哪里，谢谢

**Comment by zhumimi** [comment]
![0e31531c-7f1a-47d3-b7ea-1bd68c30ed9e](https://user-images.githubusercontent.com/37438422/43942106-4f7494a4-9ca9-11e8-8e0b-9aabb15cca80.png)
我打断点看了一下，应该就是这里的判断有问题，当我可以同时选择视频和照片，但是只选能选一张的时候，在我拍摄视频结束后，在这个地方无法进入返回视频的回调，然后会进入返回照片的回调

**Comment by banchichen** [comment]
嗯嗯👍
刚刚发布了2.2.5版本，更新一下哈

**Comment by zhumimi** [comment]
哈哈，也谢谢你分享这么一个好用的库～帮了不少忙～～点赞👍👍
