### ISSUE TITLE
TZImageManager 获取照片怎么走两遍回调

### ISSUE THREAD

**Issue by koreadragon** [banchichen/TZImagePickerController#947]
[manager getPhotoWithAsset:assets.firstObject completion:^(UIImage *photo, NSDictionary *info, BOOL isDegraded) {
           //方法执行两遍
        
    }];

**Comment by banchichen** [comment]
是的，看下系统的解释：
![image](https://user-images.githubusercontent.com/12755494/43997462-17822e74-9e0e-11e8-999a-f330f9a1f63b.png)

第一遍回调，isDegraded为YES，是缩略图
第二遍回调，isDegraded是NO，是你想要的尺寸的图
