### ISSUE TITLE
选择了一张照片以后不能选择视频

### ISSUE THREAD

**Issue by Viviannn** [banchichen/TZImagePickerController#948]
在选择视频前先选照片 视频就无法选择 并提示选择照片时 不能选择视频

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/44024728-bf4765e4-9f20-11e8-9b0c-85ad71671e24.png)

**Comment by Viviannn** [comment]
只想一个视频 多个图片 所以没有设置这个属性 如果要设置这个属性 图片和视频就只能分开写 不能共用同一个assetArr 如果我单独写视频 将选择图片禁用 提示只能选择一张照片（应该为视频）

**Comment by banchichen** [comment]
1、如果设置只能选视频，不可选图片，你别给TZImagePickerController传selectedAssets就不会提示"只能选择一张照片"，selectedAssets代表已经选中的。
2、目前不能设置单独限制视频个数，只能和图片一起共用maxImagesCount的限制。

貌似现在只能分开写，建议你本地用selectedVideoAssets、selectedPhotoAssets来记录已经选取过的视频、图片，比如选视频时给selectedAssets赋值selectedVideoAssets，选图片时给selectedAssets赋值selectedPhotoAssets，maxImagesCount分别赋值1和8。

**Comment by Viviannn** [comment]
嗯嗯 我是分别存的视频和图片 只是在视频选择的时候 如果多选一个视频提示的还是“只能选择一张照片” 其实就是提示有点问题 按理说应该是“只能选择一个视频” 其他都可以通过分开写来解决

**Comment by banchichen** [comment]
嗯嗯，其实只能选一个视频的情况下，不应该出现这种提示的，是误传了selectedAssets导致的。
如果不误传selectedAssets就是OK的哈。

后期可以考虑把这种误传导致的错误提示优化下~
