### ISSUE TITLE
手机系统语言设置成英文后，无法直接进入相机胶卷，且内部拍照按钮不见了

### ISSUE THREAD

**Issue by ZHThinker** [banchichen/TZImagePickerController#95]

**Comment by banchichen** [comment]
你好，我刚刚试了三台手机，7和8和9系统的都试了，没测出这个问题。你可以看一下TZPhotoPickerController中的UICollectionView的数据源方法中的collectionView:numberOfItemsInSection:方法，那里有一个if判断，满足条件的才会显示拍照按钮，希望能连线调试一下以提供更多信息。

**Comment by ZHThinker** [comment]
手机系统语言设置成英文后，判断条件中，@"所有照片"应针对英文环境添加 @"All Photos"，添加之后，问题解决

**Comment by banchichen** [comment]
2016.6.22更新:
刚刚更新了代码，现在版本更新到了1.5.0。更新如下：
1.可把拍照按钮放在外面了,可以设置弹出一个sheet提示用户选择相册或相机；
2.新增了sortAscendingByModificationDate属性，默认为YES，设置为NO时，照片会按修改时间降序，拍照按钮会在第一个；
3.优化了Demo页面的UI，新增6个开关控件，可方便地更改各个设置来打开选择器；
4.修复了若干bug；

你好，感谢反馈，这个bug在新版中已经顺便解决了~

**Comment by ZHThinker** [comment]
你很棒，加油！
