### ISSUE TITLE
视频导出时间长

### ISSUE THREAD

**Issue by NSUzi** [banchichen/TZImagePickerController#951]
你好，想问一下视频导出的到本地沙盒的时候，时间会很长。1分多钟的视频选用AVAssetExportPreset640x480，会处理10多秒。要是选用原本分辨率的话，时间会更长。有没有什么好的解决办法

**Comment by banchichen** [comment]
暂时没有...

如果你有的话，欢迎提个PR...

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/44378020-ec39ed80-a531-11e8-8eec-3b8399f2aa7c.png)

**Comment by banchichen** [comment]
慢的视频是不是存在iCloud的视频？
