### ISSUE TITLE
iOS 因存在私有API  prefs:root= 权限问题被拒

### ISSUE THREAD

**Issue by championship456** [banchichen/TZImagePickerController#952]
Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.
请作者尽快处理这个问题

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/44185714-b965b300-a147-11e8-975d-4c0f29e8c12f.png)

处理完一年了...
