### ISSUE TITLE
移除选中状态的某个照片后，UI没有及时刷新，需要手动返回tableView列表

### ISSUE THREAD

**Issue by koreadragon** [banchichen/TZImagePickerController#953]
在多选状态下，选中照片后，使用代码移除某个照片，如：removeSelectedModel,但是再次present出来页面后，发现那张照片选中状态还是存在，必须要手动返回相册列表，那个数字才会更新。
麻烦处理下，谢谢

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/44255949-4426da80-a23a-11e8-89a6-597ff8807c2c.png)

**Comment by banchichen** [comment]
@koreadragon 再次present的时候，你重新创建下TZImagePickerController，不要用上次的。这样的话，选中与否只取决于给TZImagePickerController传的selectedAssets。

**Comment by koreadragon** [comment]
是的，最后我也是这么处理的。
不过你可以把这当成一个小bug或者小需求处理下。
谢谢！

**Comment by banchichen** [comment]
嗯嗯，以后支持下懒加载的方式🤝
