### ISSUE TITLE
选择视频无法得到回调

### ISSUE THREAD

**Issue by ChenZhenChun** [banchichen/TZImagePickerController#954]
微信下载的MP4格式视频无法导出，过很久提示“视频导出失败”，MOV格式的正常。
[http://i1.bvimg.com/657244/b711300ef049e83a.png](url)
![Markdown](http://i1.bvimg.com/657244/b711300ef049e83a.png)

**Comment by banchichen** [comment]
应该不是mp4格式的问题，我这试了下是OK的：
> 2018-08-21 09:58:16.342645+0800 TZImagePickerController[38547:4218712] 视频导出到本地完成,沙盒路径为:/var/mobile/Containers/Data/Application/5096B9AA-3BA3-48E3-887D-1FF7CC564F85/tmp/output-2018-08-21-09:58:15-461.mp4

你把这个文件发我下？QQ群：778723997

或者你看看这个视频有啥特殊的...

**Comment by banchichen** [comment]
升级下新版哈：

![image](https://user-images.githubusercontent.com/12755494/44378040-0e337000-a532-11e8-8fd7-2dccf1e33e3c.png)
