### ISSUE TITLE
UINavigationBar 问题

### ISSUE THREAD

**Issue by Lucifer0103** [banchichen/TZImagePickerController#955]
预览时候 由于使用 [FDFullscreenPopGesture](https://github.com/forkingdog/FDFullscreenPopGesture)  会导致 出现UINavigationBar问题, 请问如何解决?
![snip20180820_1](https://user-images.githubusercontent.com/19343587/44318882-3a37ee00-a46b-11e8-8d47-569788328861.png)

**Comment by banchichen** [comment]
这里有解决方案：https://github.com/banchichen/TZImagePickerController/issues/652

**Comment by banchichen** [comment]
1、这个不能算是个问题...
2、如652所述，这个现象是FDFullscreenPopGesture导致的，参考里面的解法即可。未来有机会可以都改成自定义的NavigationBar，优先级较低。

**Comment by Lucifer0103** [comment]
2. 不是FDFullscreenPopGesture的问题, 是由于 **info.plist** 设置了View controller-based status bar appearance = NO.    因为支持侧滑所以会特别明显.
![cesssss](https://user-images.githubusercontent.com/19343587/44374409-a163aa00-a520-11e8-9628-1a87ea093889.gif)

还是谢谢作者封装的功能与细心的解答, 希望TZImagePickerController越来越完善, 给你点赞, 棒棒哒~

**Comment by banchichen** [comment]
嗯嗯，如果没有FDFullscreenPopGesture，这个预览页应该不能侧滑😂

有兴趣来个PR不~？
