### ISSUE TITLE
关于选取的图不是原图问题...

### ISSUE THREAD

**Issue by luoxiao** [banchichen/TZImagePickerController#957]
你好，最近需求的图质量比较高，发现选出来的图，即便勾选了“原图”，得到的图也不是原图。
- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray<UIImage *> *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto infos:(NSArray<NSDictionary *> *)infos；

即便  isSelectOriginalPhoto 为 YES，photos数组选出来的图，也比实际的图小。比如实际的照片500KB，这个选出的图只有140多KB，并不是真正的原图。

麻烦，有空看下这个问题。谢谢～

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/44342182-c1fa1880-a4bc-11e8-82c5-c01208437726.png)

看下FAQ
