### ISSUE TITLE
侧滑返回的bug

### ISSUE THREAD

**Issue by CherishSmile** [banchichen/TZImagePickerController#958]
设置照相机按钮在末尾，侧滑手势返回，相机按钮会自动回到第一个。详见压缩文件，视频演示
[ScreenRecording_08-21-2018 09-38-45.mp4.zip](https://github.com/banchichen/TZImagePickerController/files/2304439/ScreenRecording_08-21-2018.09-38-45.mp4.zip)

**Comment by banchichen** [comment]
老哥，你试下我最新的demo，我这复现不出来这个问题

**Comment by CherishSmile** [comment]
demo正常，我也懵逼了。昨天刚pod的库，应该是最新的吧，我在找找，看具体是什么原因导致的
