### ISSUE TITLE
紧急bug

### ISSUE THREAD

**Issue by OpenFeyn** [banchichen/TZImagePickerController#959]
设置:
pickerController.allowPickingOriginalPhoto = NO;
pickerController.allowPickingVideo = YES;
pickerController.allowPickingMultipleVideo = NO;
pickerController.allowPreview = NO;
结果：
1、选取视频，重复点击同一个视频，计数在累加；
2、即使只选取一个视频，也无法触发视频回调，只能触发图片回调

**Comment by OpenFeyn** [comment]
当下为了线上版本，只好设置pickerController.allowPreview = YES，如此可以解决

**Comment by banchichen** [comment]
其实是你配置没传对，既然设置了allowPickingMultipleVideo为NO，为什么maxImagesCount不是1？

解决办法：
1、设置allowPickingMultipleVideo为YES
2、设置maxImagesCount为1

**Comment by banchichen** [comment]
那在下面的配置下：
```objectivec
pickerController.allowPickingOriginalPhoto = NO;
pickerController.allowPickingVideo = YES;
pickerController.allowPickingMultipleVideo = NO;
pickerController.allowPreview = NO;
```
你把maxImagesCount指定为1。

在选择照片的模式下，就把maxImagesCount指定为9
