### ISSUE TITLE
barTintColor设置无效

### ISSUE THREAD

**Issue by nsuxin** [banchichen/TZImagePickerController#96]
iOS9.3.2
appdelegate自定义导航视图
imagePickerVc设置barTintColor无效

**Comment by nsuxin** [comment]
自己处理了，原因是在appdelegate的translucent属性设置为true。
在设置imagepicker时应做一遍imagePickerVc.navigationBar.translucent = false处理。
其次，由于translucent = false后视图向下移动64像素，也应该在相应的位置做-64处理。就搞定了

**Comment by banchichen** [comment]
我在imagepicker的viewDidLoad中设置了self.navigationBar.translucent = YES的。我刚刚测试了，即使设置为NO，设置的barTintColor也是生效的。  不太清楚你那里是什么情况，解决了就好~
