### ISSUE TITLE
prefs:root=Privacy&path=PHOTOS 私有方法上架被拒了哦

### ISSUE THREAD

**Issue by MeterSunlight** [banchichen/TZImagePickerController#964]
prefs:root=Privacy&path=PHOTOS 私有方法上架被拒了哦！用了好几个版本了，这次不知道怎么被拒绝了。这个是删除就行了是不是啊？兼容ioS8以前的
if (iOS8Later) {
        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
    } else {
        NSURL *privacyUrl = [NSURL URLWithString:@"prefs:root=Privacy&path=PHOTOS"];
        if ([[UIApplication sharedApplication] canOpenURL:privacyUrl]) {
            [[UIApplication sharedApplication] openURL:privacyUrl];
        } else {
            NSString *message = [NSBundle tz_localizedStringForKey:@"Can not jump to the privacy settings page, please go to the settings page by self, thank you"];
            UIAlertView * alert = [[UIAlertView alloc]initWithTitle:[NSBundle tz_localizedStringForKey:@"Sorry"] message:message delegate:nil cancelButtonTitle:[NSBundle tz_localizedStringForKey:@"OK"] otherButtonTitles: nil];
            [alert show];
        }
    }

**Comment by Cocowyr** [comment]
我也是刚刚被拒调的

**Comment by Cocowyr** [comment]
怎么解决

**Comment by MeterSunlight** [comment]
马上去公司解决。昨晚发版，上午休息哦。上午收到杯具。应该删掉就可以了。我看了代码是兼容ios8以前的。我们从ios9开始了

**Comment by MeterSunlight** [comment]
加下QQ313820908，看这样还有问题不

**Comment by banchichen** [comment]
![image](https://user-images.githubusercontent.com/12755494/44832615-dc22bc00-ac5d-11e8-8f88-4af2dcd30d84.png)

最新版3.0.2，支持iOS8起，升级下吧

**Comment by MeterSunlight** [comment]
@banchichen 当前版本移除会不会有问题。我已经移除了。下个版本升级可以不。我现在这样处理的。把上面的代码移除了。请问会有问题不啊。

NSURL *privacyUrl = [NSURL URLWithString:@"prefs:root=Privacy&path=PHOTOS"];
if ([[UIApplication sharedApplication] canOpenURL:privacyUrl]) {
[[UIApplication sharedApplication] openURL:privacyUrl];
} else {
NSString *message = [NSBundle tz_localizedStringForKey:@"Can not jump to the privacy settings page, please go to the settings page by self, thank you"];
UIAlertView * alert = [[UIAlertView alloc]initWithTitle:[NSBundle tz_localizedStringForKey:@"Sorry"] message:message delegate:nil cancelButtonTitle:[NSBundle tz_localizedStringForKey:@"OK"] otherButtonTitles: nil];
[alert show];

**Comment by banchichen** [comment]
不使用prefs:root就不会被拒的。
隐藏了跳转实现，把"设置"按钮也隐藏掉即可。
