### ISSUE TITLE
能否在选择位于iCloud中的图片或视频的时候弹窗提示，禁止选择。

### ISSUE THREAD

**Issue by xcvzaq** [banchichen/TZImagePickerController#966]
判断是否在iCloud中，代码类似以下：
- (BOOL)judgeAssetisInLocalAblum:(PHAsset *)asset
{
    __block BOOL result = NO;
    if (@available(iOS 10.0, *)) {
        // https://stackoverflow.com/questions/31966571/check-given-phasset-is-icloud-asset
        // 这个api虽然是9.0出的，但是9.0会全部返回NO，未知原因，暂时先改为10.0
        NSArray *resourceArray = [PHAssetResource assetResourcesForAsset:asset];
        if (resourceArray.count) {
            result = [[resourceArray.firstObject valueForKey:@"locallyAvailable"] boolValue];
        }
    } else {
        PHImageRequestOptions *option = [[PHImageRequestOptions alloc] init];
        option.networkAccessAllowed = NO;
        option.synchronous = YES;
        
        [[PHCachingImageManager defaultManager] requestImageDataForAsset:asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
            result = imageData ? YES : NO;
        }];
    }
    return result;
}

**Comment by banchichen** [comment]
为什么要禁止选择iCloud图片呢，是出于怎样的考虑？

**Comment by xcvzaq** [comment]
原因是当选择的图片和视频是多张，或者比较大，下载比较慢，这时候获取的资源可能也无法使用。
选择的时候，给出提示，让用户去系统相册中下载，或许比较友好。

**Comment by banchichen** [comment]
在选择器里下载慢，在相册不也会下载慢？

而且用户需要到相册再次找到这张照片，点击进入预览页面，才会开始下载。这个步骤反而浪费了用户的时间。

没有哪个大APP这样做吧？

**Comment by xcvzaq** [comment]
问题是，因为在icloud中，资源可能无法使用，需要开发者添加一些在下载中的逻辑和界面展示等。
我看微信的视频选择，如果视频在icloud中，点击选择的时候，会先同步下载，这时不能选择其他视频或图片。
选择图片又是另外的逻辑，它应该是异步下载，发送之后在聊天界面中，显示iCloud下载中。
如果这些都得做，就比较麻烦，不如直接给用户提示，让他先从icloud中下载。
当然也可以做个开关，继续保留现在的逻辑。通过开关控制是否允许用户从iCloud下载。
