### ISSUE TITLE
适配新款iPhoneX，tz_isIPhoneX方法实现需要更新

### ISSUE THREAD

**Issue by LukeChow** [banchichen/TZImagePickerController#967]
这个方法用
BOOL isIPhoneX = [platform isEqualToString:@"iPhone10,3"] || [platform isEqualToString:@"iPhone10,6"];
来判断是不是iPhone X，以决定状态栏的高度等，然而还有不到一个月就出新版iPhone X了，如不提前更新，使用此库的APP会有问题

**Comment by LukeChow** [comment]
建议改成height>=812作为是否是iPhone X的判断方法

**Comment by banchichen** [comment]
@LukeChow 应该不用担心的，新款iPhoneX肯定是跑在iOS12上，用Xcode10的正式版打的包才会开启新款iPhoneX的特性。

就像刚出iPhoneX的时候，用Xocde8打的包运行在iPhoneX上不会开启全面屏效果，刘海那块周围会是黑的。

然后听说新款iPhoneX的刘海会缩小，用目前iPhoneX的适配方式去适配还不行，要微调下。

有最新的进展，欢迎交流和评论🤝

欢迎加QQ群：778723997

**Comment by banchichen** [comment]
已适配，3.0.7版本哈。
