### ISSUE TITLE
定位功能需要添加 info.plist 描述

### ISSUE THREAD

**Issue by arayinfree** [banchichen/TZImagePickerController#968]
需要在 info.plist 添加 Privacy - Location When In Use Usage Description 
否则在最新政策下, 会被打回. 
当代码中使用了 定位的api ,不管实际是否使用该功能,都需要添加该描述.

**Comment by banchichen** [comment]
嗯嗯，Demo的info.plist里有的。

**Comment by arayinfree** [comment]
不加也不会崩溃,只是上传后,会收到警告邮件. 
在 2019 年 3月以后, 只要代码包含定位的api , 不管是否实际使用,都需要添加描述.

**Comment by banchichen** [comment]
嗯嗯，试了下确实不会崩溃👍

只是控制台会给日志提醒：
```
This app has attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSLocationWhenInUseUsageDescription key with a string value explaining to the user how the app uses this data
```

我在readme上加了下说明，给大家提个醒：
![image](https://user-images.githubusercontent.com/12755494/45105321-93d83200-b166-11e8-9f7b-43ddae7898da.png)

**Comment by wodeweilai123** [comment]
<key>NSLocationUsageDescription</key>
 <string>App需要您的同意,才能始终访问位置</string>
 <key>NSLocationWhenInUseUsageDescription</key>
 <string>允许定位以把位置保存到照片中</string>
这俩需要成对添加，我只加了NSLocationWhenInUseUsageDescription 构建版本提交不上去，发邮件说是需要加上NSLocationUsageDescription

**Comment by banchichen** [comment]
@wodeweilai123 感谢反馈，我把readme更新一下

**Comment by wodeweilai123** [comment]
是NSLocationAlwaysUsageDescription，昨天写错了抱歉
