### ISSUE TITLE
Application tried to present modally an active controller <TZPhotoPickerController: 0x106933600>.

### ISSUE THREAD

**Issue by VinothKuppanna** [banchichen/TZImagePickerController#969]
I have used this TZImagePickerController in my application. When i test it was good. When my app goes into app store. Lot of users have seen this crash. I have enabled crashlytics in my app. I found this crash from there. Can't reproduce in my side. Any help would be appreciated. Thanks.

@banchichen 
@tinpont 
@VincentSit

**Comment by banchichen** [comment]
@VinothKuppanna You are getting this error because you are attempting to present the 'TZPhotoPickerController' view controller twice.

You can try to make a judgement before present. like this:
```objectivec
if (self.presentedViewController == nil) {
    [self presentViewController:imagePickerVc animated:YES completion:nil];
} else {
    NSLog(@"Already presented TZImagePickerController");
}
````

More information, you can browse these links：
https://stackoverflow.com/questions/15157009/application-tried-to-present-modally-an-active-controller-uiimagepickercontrol
https://recalll.co/app/?q=ios%20-%20Application%20tried%20to%20present%20modally%20an%20active%20controller%20-%20crashing%2C%20why%3F%20-%20Stack%20Overflow
https://stackoverflow.com/questions/7429014/application-tried-to-present-modally-an-active-controller

**Comment by VinothKuppanna** [comment]
@banchichen Thanks for your comments. My code for calling TZImagePickerController is shown below.

TZImagePickerController *imagePickerVc = [[TZImagePickerController alloc] initWithMaxImagesCount:150 delegate:self];
    imagePickerVc.isSelectOriginalPhoto = true;
    imagePickerVc.allowTakePicture = NO;
    imagePickerVc.allowPreview = NO;
    imagePickerVc.allowPickingVideo = NO;
    imagePickerVc.allowPickingGif = NO;
    imagePickerVc.allowPickingMultipleVideo = NO;
    [imagePickerVc setDidFinishPickingPhotosHandle:^(NSArray<UIImage *> *photos, NSArray *assets, BOOL isSelectOriginalPhoto)
    {
		//Process my images here.       
    }];
    
    [self  presentViewController:imagePickerVc animated:YES completion:nil];

Called this method on button actions. So how this issue happens? I didn't have any other views presented in this controller. My app don't have tabbar controller too.

**Comment by banchichen** [comment]
Yeah, that's a weird question. Can you show me the call stack?

**Comment by banchichen** [comment]
@VinothKuppanna The main thread call stack was contaminated by crashlytics. I can't find any useful information. I saw the app's name is Demo. Could you send the code to github or a cloud disk and give me the link?

**Comment by VinothKuppanna** [comment]
@banchichen Sorry . I changed the app name to demo. Can't share source code.  Thanks for your efforts and help. I will try to reproduce with my app and will fix it. Thanks once again.

**Comment by banchichen** [comment]
@VinothKuppanna  I'm sorry I didn't solve your problem. Good luck!

**Comment by shijian123** [comment]
> @banchichen Sorry . I changed the app name to demo. Can't share source code. Thanks for your efforts and help. I will try to reproduce with my app and will fix it. Thanks once again.

I also encountered this problem. How did you solve it？
