### ISSUE TITLE
当选择9张大图多次点击完成导致内存溢出崩溃

### ISSUE THREAD

**Issue by jyyjkt** [banchichen/TZImagePickerController#970]
选择相册 点击选择图片 点击原图 然后快速点击多次完成按钮 完成按钮响应多次 导致内存溢出崩溃

**Comment by jyyjkt** [comment]
主要这个HUD没有覆盖操作栏部分

**Comment by jyyjkt** [comment]
_progressHUD = [UIButton buttonWithType:UIButtonTypeCustom];
        [_progressHUD setBackgroundColor:[UIColor clearColor]];
        _progressHUD.frame = CGRectMake(0, 0, KScreenWidth, KScreenHeight);
加个frame就行了

**Comment by banchichen** [comment]
赞👍

已修复，新版本：3.0.3
