### ISSUE TITLE
单选裁剪模式下闪退

### ISSUE THREAD

**Issue by chenfengfeng** [banchichen/TZImagePickerController#971]
能够从demo复现

设备:iPhone7 plus 11.3.1系统
设置参数:
```swift
imagePicker?.sortAscendingByModificationDate = false
        imagePicker?.allowPickingOriginalPhoto = false
        imagePicker?.alwaysEnableDoneBtn = true
        imagePicker?.allowPickingVideo = false
        imagePicker?.allowPickingGif = false
        imagePicker?.allowCrop = true
```
场景复现:
点击iCloud照片,这个时候会去加载照片,加载完毕后如下图:
![](https://user-images.githubusercontent.com/6957977/45131350-315f5000-b1bf-11e8-827f-82f899a6b546.PNG)
之后点击确定就闪退

全局断点位置:
TZPhotoPickerController.m =》 722行
- (void)pushPhotoPrevireViewController:(TZPhotoPreviewController *)photoPreviewVc needCheckSelectedModels:(BOOL)needCheckSelectedModels
这个方法里面
[photoPreviewVc setDoneButtonClickBlockCropMode:^(UIImage *cropedImage, id asset) {
        __strong typeof(weakSelf) strongSelf = weakSelf;
        [strongSelf didGetAllPhotos:@[cropedImage] assets:@[asset] infoArr:nil];
    }];

cropedImage为nil

**Comment by banchichen** [comment]
@chenfengfeng 其它图片会这样吗？我试了几个iCloud图片，关闭手机网络，在预览界面是会有缩略图，可以正常裁剪的。

你这个图片好像没读到，界面的整屏灰色，是预览页的背景色，图片似乎没加载出来。

这个图片在别的选择器展示正常吗？在相册展示正常吗？

**Comment by chenfengfeng** [comment]
@banchichen 只有第一次选择未加载完成的iCloud照片会这样,第二次选择这张照片就正常了...

**Comment by banchichen** [comment]
@chenfengfeng 我这边即使断网，iCloud图预览时也是有缩略图的，因为缩略图是存在本地的。所以无法复现你这个情况。

我这边加个判断，如果预览时image是nil，让完成按钮不可点击？

**Comment by chenfengfeng** [comment]
我这边仔细看了，其实cell的imageview 有值而且可以看到照片，就是在裁剪得到image的时候拿不到image

**Comment by banchichen** [comment]
@chenfengfeng 嗯嗯，赞👍，有更深入的发现吗？怎样的场景或图片容易复现这个问题~？

**Comment by chenfengfeng** [comment]
@banchichen 我这边只要是iCloud照片,第一次加载必定会复现

**Comment by banchichen** [comment]
@chenfengfeng 能稳定复现的话，Debug下到底在哪出的问题？然后修复了提个PR~ 
也可以加QQ群详聊：778723997

**Comment by chenfengfeng** [comment]
@banchichen 找到问题,但是比较迷..我也搞不明白为什么会这样

获取imageView.image.size的size出现问题,如果从相册加载,不会有问题,如果从iCloud加载则会出现问题
获取到的size乘10了
![](https://user-images.githubusercontent.com/6957977/45250020-5093e400-b35d-11e8-8fbe-27c6c841b565.jpg)

其实这张照片尺寸应该是width = 3264, height = 2448

比较迷...

**Comment by chenfengfeng** [comment]
我在TZImageManager这个类里面
```obj
// Download image from iCloud / 从iCloud下载图片
[[PHImageManager defaultManager] requestImageDataForAsset:asset options:options resultHandler:^(NSData *imageData, NSString *dataUTI, UIImageOrientation orientation, NSDictionary *info) {
                UIImage *resultImage = [UIImage imageWithData:imageData scale:0.1];
                if (![TZImagePickerConfig sharedInstance].notScaleImage) {
                    resultImage = [self scaleImage:resultImage toSize:imageSize];
                }else{//如果不是压缩,则除以10
                    CGSize size = resultImage.size;
                    size.width = size.width/10;
                    size.height = size.height/10;
                    resultImage = [self scaleImage:resultImage toSize:size];
                }
                if (!resultImage) {
                    resultImage = image;
                }
                resultImage = [self fixOrientation:resultImage];
                if (completion) completion(resultImage,info,NO);
            }];
```

我这样能解决问题,但是我觉得这样不对,问题不应该是这里

**Comment by banchichen** [comment]
我代码提交了哈，发布了3.0.5版本...

不太记得当初为什么这样写了...

你试下最新demo，还能复现的话，再打开issue哈。

**Comment by chenfengfeng** [comment]
@banchichen OK了~我还以为你当初那样写是遇到什么问题...

**Comment by banchichen** [comment]
😂
