### ISSUE TITLE
您好 楼主！ 您的这个控件剪切图片怎么不能移动边框的大小 非要移动图片了？而且也不能改变图片的形状只能正方形 和原型

### ISSUE THREAD

**Issue by TzyTman** [banchichen/TZImagePickerController#976]

**Comment by banchichen** [comment]
@TzyTman 目前没这个计划哈...

**Comment by TzyTman** [comment]
做项目都是用的你的这个控件.用了好久了。现在突然加了这个需求。 楼主计划一下吧！这个功能还是很普及的。 我看了其他有第三方图片编辑库都有这个功能。有劳楼主加一下这个功能吧。让这个控件变得更加的强大！

**Comment by banchichen** [comment]
@TzyTman 你可以试试使用这个做裁剪：https://github.com/itouch2/PhotoTweaks

**Comment by TzyTman** [comment]
能剪切的工具类有很多。还是希望楼主能把该功能加到我们自己的控件里面去！呵呵呵 .....

**Comment by banchichen** [comment]
@TzyTman 应该不会加了，裁剪的需求许多人不需要，直接放进去库会臃肿，包大小增大，一些对包大小严格要求的APP就不会选择TZ了。

后续TZ会设计一套插件机制，由业务方选择是否集成XX插件。

**Comment by TzyTman** [comment]
问题已经解决了。 自己写了一个很简单的图片剪切类。 楼主以后更新了记得通知我。

**Comment by banchichen** [comment]
赞👍

**Comment by KangYJie** [comment]
> 问题已经解决了。 自己写了一个很简单的图片剪切类。 楼主以后更新了记得通知我。

能否借鉴一下
