### ISSUE TITLE
能否增加拍照功能

### ISSUE THREAD

**Issue by jianjianhao** [banchichen/TZImagePickerController#98]
![g9n uz_10 u5sqfkgdmcddu](https://cloud.githubusercontent.com/assets/12797357/15989541/76f28d54-30ab-11e6-89c4-8707a6a8972e.jpg)
类似微信那种可以拍照

**Comment by banchichen** [comment]
你好，这个你自己实现吧。我的在相机胶卷列表页有拍照按钮的。    如果改成在外面拍照，需要改动的地方挺多的，暂时不能兼容这样的设置。
