### ISSUE TITLE
是我没搞清楚使用方法还是说只有我发现这个问题？（状态栏问题）

### ISSUE THREAD

**Issue by ynnynn** [banchichen/TZImagePickerController#984]
我的项目是vc based status bar appearance的，使用的是demo里面最简练的设置，一切都是TZImagePickerController的默认配置，看过源码后也发现了默认的status bar style 是 UIStatusBarStyleLightContent，结果present出来的图片选择器的状态条是UIStatusBarStyleDefault的，各种设置都试过了，运行的结果死活都是UIStatusBarStyleDefault这种，后来跑去TZPhotoPickerController加入了preferredStatusBarStyle为UIStatusBarStyleLightContent后，终于跑出来是白色的状态条了...>_<

**Comment by ynnynn** [comment]
1. demo正常的
2. 版本是3.0.7

但是情况确实是这样，我的项目也没有特别使用一些特殊配置，也没有相关的第三方库，结构就是tabController->navigationController->vc

这个vc push一个vc(vc2)，vc2再push一个vc(vc3)后，present出来的选择器就是没法修改状态条颜色了>_<

**Comment by banchichen** [comment]
嗯嗯，可以制作个Demo吗？还没遇到过这个情况

QQ群：778723997

**Comment by ynnynn** [comment]
这个我稍后看下弄个复现demo看看
刚刚我把我的项目和demo对比了下，demo里面调整了vc based status bar appearance是YES，TZImagePickerController的preferredStatusBarStyle触发了
而我的项目也是vc based status bar appearance的，结果preferredStatusBarStyle没触发

可以说应该是这个原因给导致的，可是也想不通已经是vc控制的状态条为什么不触发preferredStatusBarStyle。。。。

**Comment by banchichen** [comment]
@ynnynn 把demo的vc based status bar appearance设置为NO也是正常的，你可以试下。应该是其它的原因。

**Comment by ynnynn** [comment]
问题终于找到了，是一个播放器的三方库里面的一个UINavigationController的category造成的（其实也不一定算是这个三方库的问题，但是未免有点太霸道了），里面重写了childViewControllerForStatusBarStyle，返回了topViewController，当图片选择器要present的时候，第一次返回的topViewController是TZAlbumPickerController，第二次返回的是TZPhotoPickerController，然而，像之前说的，这两个类里面没有重写preferredStatusBarStyle，所以返回的是默认的黑色字状态条，所以昨天说的我尝试去在这两个类的实现加入preferredStatusBarStyle就正常了

作者是否有好的修改建议？

**Comment by banchichen** [comment]
我适配了下，在各个控制器都实现了preferredStatusBarStyle。

新版本：3.0.8
