### ISSUE TITLE
如果选择只能选择视屏。不能选择图片。并且容许裁剪的话，点击确定的时候会闪退

### ISSUE THREAD

**Issue by ldgkings** [banchichen/TZImagePickerController#985]

**Comment by ldgkings** [comment]
谭大哥，demo也有这个问题。希望你百忙中看下

**Comment by banchichen** [comment]
@ldgkings 嗯嗯，为啥没有根据提bug模板填写相应信息？

**Comment by ldgkings** [comment]
最新的版本，不选图片，只选视屏。容许多选视频。可以裁剪
![3ef04b55-63b2-42e6-9712-0435d1ac1749](https://user-images.githubusercontent.com/15611861/46129620-d672c300-c269-11e8-88f3-436888d26ff0.png)

**Comment by banchichen** [comment]
OK，已修复，新版本：3.0.8
