### ISSUE TITLE
需要每次都present一个新的TZImagePickerController对象吗？TZImagePickerController 这个不走dealloc

### ISSUE THREAD

**Issue by zhouZ813** [banchichen/TZImagePickerController#986]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？——是【**如果Demo没问题，请升级新版**】
2、你用的是什么版本？升级后是否正常？——3.0.7，已经是用的最新版
3、是否有改动过我库内部的代码？——否【**如有，请告诉我你改了什么**】

**bug内容描述**
请在这里描述bug的内容：

**如何复现这个bug？**
以下是示例，请替换你的bug复现步骤：
1、Demo默认设置，去选择照片
2、选择一个照片去预览
3、导航栏没有消失

**截图**
如有，请在这贴上你的截图：

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
@zhouZ813 请先回答模板内的问题。信息太少，无法处理。

**Comment by banchichen** [comment]
在demo里，TZImagePickerController的dealloc是会走的，你对照下代码。
