### ISSUE TITLE
保存宽图（全景图片）会把预览小图也保存下来

### ISSUE THREAD

**Issue by PandexLee** [banchichen/TZImagePickerController#990]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？——是
2、你用的是什么版本？升级后是否正常？——3.0.7，已经是用的最新版
3、是否有改动过我库内部的代码？——否

**bug内容描述**
保存宽图（全景图片）会把预览小图和原始大图都保存下来。
推测是在 YBImageBrowser.m 的569行把 else if 写成了 if，我这样修改过后就没问题了

**如何复现这个bug？**
以下是示例，请替换你的bug复现步骤：
预览图sourceImage的地址：   http://img.okay.do/acagrid/usercontent/moment/e6a217e7ec4927f6029b73012d4a0c57_W3705_H828_G0?x-oss-process=image/resize,l_400

大图地址：http://img.okay.do/acagrid/usercontent/moment/e6a217e7ec4927f6029b73012d4a0c57_W3705_H828_G0

**Comment by banchichen** [comment]
@PandexLee 老哥，我这没有保存图片的功能，也没有YBImageBrowser，是不是走错片场了？
