### ISSUE TITLE
选择原图和非原图的时候，得到的图片大小一样大！！怎么回事啊？

### ISSUE THREAD

**Issue by pangyunxiu** [banchichen/TZImagePickerController#993]
- (void)imagePickerController:(TZImagePickerController *)picker didFinishPickingPhotos:(NSArray<UIImage *> *)photos sourceAssets:(NSArray *)assets isSelectOriginalPhoto:(BOOL)isSelectOriginalPhoto infos:(NSArray<NSDictionary *> *)infos {
    _selectedPhotos = [NSMutableArray arrayWithArray:photos];
//    NSLog(@"图片大小：%lu", UIImagePNGRepresentation(photos[0]).length);
    
    PHAssetResource *resource1111 = [PHAssetResource assetResourcesForAsset:assets[0]].firstObject;
    NSLog(@"图片大小:%@", [resource1111 valueForKey:@"fileSize"]);
}
获取到的图片文件大小是一样的，请问为什么啊？

**Comment by banchichen** [comment]
看readme。

**Comment by pangyunxiu** [comment]
恩，看了，非常感谢
