### ISSUE TITLE
在demo里面点击相机，导航栏会有偏移的动画

### ISSUE THREAD

**Issue by DotaAntiMagic** [banchichen/TZImagePickerController#994]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？——最新的demo有这个bug
2、你用的是什么版本？升级后是否正常？——3.0.7，已经是用的最新版
3、是否有改动过我库内部的代码？——否【**如有，请告诉我你改了什么**】

**bug内容描述**
请在这里描述bug的内容：在demo里面点击相机，导航栏会有偏移的动画,手机版本ios 12.0

**如何复现这个bug？**
以下是示例，请替换你的bug复现步骤：
1、Demo默认设置，去选择照片
2、在弹出的相机胶卷里面，点击相机按钮，注意观察顶部的导航栏，导航栏会有偏移的明显动画

**截图**
如有，请在这贴上你的截图：
![1539314823091](https://user-images.githubusercontent.com/13567812/46846482-67bd6a00-ce12-11e8-9a85-c1f99c56c0bb.jpg)

**Comment by banchichen** [comment]
不可避免的...
