### ISSUE TITLE
demo里面打印的视频沙盒路径地址与实际沙盒文件名称不一样

### ISSUE THREAD

**Issue by DotaAntiMagic** [banchichen/TZImagePickerController#997]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？——是【**如果Demo没问题，请升级新版**】
2、你用的是什么版本？升级后是否正常？——3.0.7，已经是用的最新版
3、是否有改动过我库内部的代码？——否【**如有，请告诉我你改了什么**】

**bug内容描述**
请在这里描述bug的内容：
demo里面选择视频，会打印视频沙盒路径，这是我进沙盒查看视频，发现视频的名称不一样
**如何复现这个bug？**
以下是示例，请替换你的bug复现步骤：
1、Demo默认设置，去选择视频
2、查看控制台视频沙盒路径打印
3、去手机沙盒查看原视频对比下

**截图**
<img width="1141" alt="wx20181017-211503 2x" src="https://user-images.githubusercontent.com/13567812/47088906-284baf00-d252-11e8-8b31-dbeabfb1fef5.png">

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by DotaAntiMagic** [comment]
请问下那我该怎么拿到正确的视频沙盒路径呢，我现在将outputPath的路径直接扔到第三方的SDK上传，一直在报找不这个视频

**Comment by DotaAntiMagic** [comment]
> 通过Xcode拿到应用沙盒的时候，中间的路径应该变了的。
> 
> 但是文件名没变呀，还是xxx-383.mp4

请问下那我该怎么拿到正确的视频沙盒路径呢，我现在将outputPath的路径直接扔到第三方的SDK上传，一直在报找不这个视频

**Comment by DotaAntiMagic** [comment]
不好意思搞错了，原来是application后面这一段老是会变，导致的没找到视频
![image](https://user-images.githubusercontent.com/13567812/47137002-f2f1a080-d2e7-11e8-9d0b-609a33a0194b.png)

**Comment by DotaAntiMagic** [comment]
![image](https://user-images.githubusercontent.com/13567812/47137027-01d85300-d2e8-11e8-9c83-92b20e7d2836.png)

**Comment by banchichen** [comment]
@DotaAntiMagic 没事，那你最后给这个第三方传了什么路径？不是我返回的outputPath吗？

**Comment by banchichen** [comment]
OK

要你自己实现的

**Comment by SUWW** [comment]
> 对，就是你的返回的outputPath，对了还有问题想问下，我用的是阿里的视频上传SDK，SDK里面需要视频的封面沙盒路径，我看你的库里面是返回uiimage对象的，请问库里面有那种保存图片到沙盒的操作么，还是这个是要我自己去实现？



> > 通过Xcode拿到应用沙盒的时候，中间的路径应该变了的。
> > 但是文件名没变呀，还是xxx-383.mp4
> 
> 请问下那我该怎么拿到正确的视频沙盒路径呢，我现在将outputPath的路径直接扔到第三方的SDK上传，一直在报找不这个视频

我做的是聊天app，在选择视频之后，outputPath直接上传阿里oss是没问题的。但是因为会有发送消息失败的时候，失败的时候，我会把outputPath保存起来，重新发送的时候，我再使用outputPath的地址再上传视频就出现了找不到视频文件的错误，请问你是怎么解决的？

**Comment by banchichen** [comment]
@SUWW 失败的时候，你可以把outputPath的内容，复制到沙盒的Documents目录下，保存Documents目录下的路径，这种路径就不会失效。但要注意，再次上传成功时，最好把文件删掉，否则会无谓增加你们APP的占用磁盘大小
